batfish/batfish

projects/batfish-common-protocol/src/org/batfish/datamodel/questions/Question.java
projects/batfish/src/org/batfish/main/Batfish.java

Add a new Question type and, when a question is parameterized by a variable
of type question, preprocess that question too. Note that this is different
from an inner question, for which each question can only have one and is
shares variables from the other question. This is instead a nested question,
which is currently in a completely different parameter space (aka, in a
composite query).
This partially addresses #162, but does not yet improve testing or really
code clarity. (It does make errors slightly better.)

Batfish: preprocess inner Questions

---

projects/batfish/src/org/batfish/main/Batfish.java

Instead, callers can type it to be a question, and the existing internal code
should handle it.
This closes https://github.com/batfish/batfish/issues/166

Remove special handling for innerQuestion

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java

It should only be used when there's actually a format string.

Client: fix use of outputf

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/BatfishObjectMapperTest.java

ObjectMapper has two separate configurations for inclusion: value and
content. The default method for configuring the inclusion applies the
supplied inclusion strategy to both.  However, Batfish's default of
NON_NULL means that we could serialize {map: {key: []}} to {} (where the
class Foo has a single property Map<String, String[]>), because:
1. key's value is empty, so we drop key
2. the map is empty, so we drop the map.
By swapping from value=NON_NULL (which applies to properties like
Foo.map) and content=NON_NULL (which applies to the content of
collections that are inside of objects) to content=ALWAYS, we do not
drop key from the map and thus don't drop the map.
This fixes batfish/batfish#256.

BatfishObjectMapper: use ALWAYS content serialization

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/question/src/main/java/org/batfish/question/InferRolesQuestionPlugin.java
test_rigs/example2/node_roles.json
tests/basic/commands
tests/basic/nodes-unit-tests.ref
tests/basic/roleNeighbors2.ref
tests/ui-focused/list-testrigs1.ref

Role inference is performed when a testrig is initialized.  The produced NodeRoleSpecifier is written to the file node_roles_inferred.json.  When roles are required to answer a question, explicitly provided node roles (in node_roles.json) are used if available, and otherwise the inferred roles are used.

infer node roles when a testrig is initialized

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java

AbstractRouteBuilder#setNextHopIp does accept null IPs; it overrides
them with the UNSET value.
Propagate the @Nullability into AWS VPC Route to fix a warning.

[Findbugs] Improve @Nullable annotations in route builders

---

projects/pom.xml

Two reasons not to run it yet:
- It takes over 2 minutes to analyze Batfish module alone, probably because it doesn't yet exclude generated code.
- The checks aren't even close to passing.

Add Findbugs configuration, but do not run it automatically yet

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/BackoffTest.java

The existing code checks to see if the work item is done every 1s. The new code ramps up from 1ms to 1s, so very fast work items are handled quickly.
We should consider the time constants + how often we print... with current constants and behavior the Java client may be spammy at the beginning.
The efficiency of this improvement is obviously limited by coordinator-side latency. I think right now the coordinator still polls every 1s.

Batfish-Client: poll ramping up using exponential backoff

---

projects/coordinator/src/main/java/org/batfish/coordinator/Main.java

Sets up the workMgr before starting the workMgrService, this will remove the possible condition that the service already started, but the workMgr is not set.

set up workMgr before starting the workMgrService

---

projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesChain.java

Set a default policy for iptables rules

---

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java

The VPN gateway address was never set; we assigned both internet and VPN
gateways addresses to the igwAddress.
Q: what did this fix, if anything? How should I add a test?

AWSVPC/Subnet: fix a mistaken variable assignment

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Pair.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Route6FilterLine.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Route6FilterList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java
projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv6Network.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfNetwork.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfWildcardNetwork.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineExact.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineLengthRange.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineLonger.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineOrLonger.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineThrough.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineUpTo.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineExact.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineLengthRange.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineLonger.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineOrLonger.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineThrough.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLineUpTo.java

* Short-circuit self-equals.
* Handle null and incorrect class (together, as `null instanceof T` is false.)
The only interesting one is Pair, where I used `Objects.equals` to simplify null handling.

[Findbugs] Fix a few equals(Object o) methods

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java

There should be less magic in our code.
I ran the following test to confirm that the old implementation and the new
are equivalent:
```java
@Test
public void testMagic() {
for (int numInterfaces = 1; numInterfaces < 33; ++ numInterfaces) {
int numHostBits = 0;
for (int shiftedValue = numInterfaces - 1;
shiftedValue != 0;
shiftedValue >>= 1, numHostBits++) {
}
assertThat(Integer.numberOfLeadingZeros(numInterfaces - 1), equalTo(32 - numHostBits));
}
}
```

Batfish: use built-in bit twiddling

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

BfConst.RELPATH_TESTRIGS_DIR is empty now, the function call 'listTestrigs' will also include the analyses path in the result. Also, I modified initContainer to also create the path for testrigs and analyses(these were created when first time the client upload a testrig/analysis). Notice I didn't remove the existence check in listTestrigs and listAnalyses, they can't be empty from now on. (assume no direct operations on file system)

assign a value to testrigs path constant

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish/pom.xml
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/ReachabilityQuerySynthesizer.java
projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java

This adds support for the following:
- transitNodes: set of transit nodes (packet must transit through all of them)
- notTransitNodes: set of non-transit nodes (packet does not transit through any of them)
Now one can check that all traffic ingress|egress to a zone goes through a transit node for example by issuing the following query
```
get reachability type=standard, ingressNodeRegex=from, srcIps=[1.1.1.0/24], dstIps=[2.2.2.2], actions=[accept], notTransitNodes=[firewall]
```
From @jkhourybbn

Fixes #345: extends reachability to support checks for transit nodes

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java

For issue #359 
The configuration of each Jersey client are actually same, so I think we can remain one Jersey Client for a BfCoordWorkHelper. The release note of Jersey 2.0 mentioned the Jersey Client is thread safe, however, they remove the descriptions of thread safe since Jersey 2.1. I am not sure whether it is thread safe now, but our Java client doesn't use multi-thread anywhere (need to verify it), I think it should be fine. I am not sure whether or not this solution is acceptable, if so, I'll change the creation of Jersey Client in WorkMgr in next PR.

make Jersey Client a class field in BfCoordWorkHelper

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/.gitignore
projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoSourceNat.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java
test_rigs/parsing-tests/unit-tests.ref
tests/basic/init-unit-tests.ref
tests/basic/nodes-unit-tests.ref

Allow interfaces to have multiple source nat rules

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

The intended invariant is that the Coordinator pool manager and Worker server are
either both using SSL or neither using SSL. Fix this for the connection that
the Coordinator's work maanger uses when opening a connection to the Worker server.

WorkMgr: Connect to the client via the pool manager settings

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java

Missed allowed values validation in client's validate function. After the type is verified, we should also check the value is allowed for the variable if specified.

add allowed_values validation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralAsList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/PrependAsPathTest.java

When prepending a path of N nodes, we used to insert each node at the front of existing lists.
For something like an array list, this is N full shifts of the array. Optimize this by
computing the entire prefix to be appended first, then doing a single array shift.

PrependAsPath: optimize algorithm and fix bug

---

projects/pom.xml

The option is backwards. See https://issues.apache.org/jira/browse/MCOMPILER-209

pom.xml: turn on incremental compilation

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java

Use some useful libraries to do the work for us, cleaner code.
I tested equivalence of the hashing as follows:
```java
private static final String[] messages =
new String[] {
"", "foo", "bar", "éüñ", "thequickbrownfox jumped over the_lazy!dog",
};
@Test
public void testDigestSha256() {
for (String m : messages) {
String old = CommonUtil.sha256Digest(m);
String newH = Hashing.sha256().hashString(m, StandardCharsets.UTF_8).toString();
assertThat(newH, equalTo(old));
}
}
```

CommonUtil: simplify hashing and matching

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
test_rigs/parsing-tests/unit-tests.ref
test_rigs/unit-tests/configs/cisco_interface
test_rigs/unit-tests/configs/cisco_rip
tests/basic/init-unit-tests.ref
tests/basic/nodes-unit-tests.ref

Questions:
* When do we use CiscoStructureType.IPV4_ACCESS_LIST vs IP_ACCESS_LIST? It looks like CiscoStructureType.IP_ACCESS_LIST_EXTENDED is never used, nor is CiscoStructureType.IP_ACCESS_LIST_STANDARD.
* (aka, should these be registered as IPV4 or IP)
* What determines which types of structures we "mark references to IPv4/6 ACLs that may not appear in data model". Why do we not mark all references, regardless of whether they appear in the data model? Only mildly redundant work.

Fix some missing structure references

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java

1. Inability to handle serialized objects bigger than 2GB
2. Leaked streams
The fix for 1 involves not reading the data into an array before
passing it to the deserializer.
The fix for 2 involves making sure we close streams, even in exception cases.
Guava's Closer makes this easier, although it still throws IOException which
makes integration with Batfish's exception policies more challenging.

PluginConsumer: fix a number of bugs

---

.travis/build.sh
projects/batfish/src/main/java/org/batfish/main/Batfish.java
tools/common.sh

Travis wasn't running unit tests any more after #383. Fix this by adding a new command `batfish_test_all`, then fix the recently-broken unit test.

Fix Travis checking of unit tests, fix unit tests

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLinesAnswerElement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/batfish/src/main/java/org/batfish/representation/cisco/StaticRoute.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/smt/LogicalGraph.java
projects/checkstyle.xml
projects/question/src/main/java/org/batfish/question/RolesQuestionPlugin.java

We actually used to fail the build on unused import statements, but @arifogel deleted it in https://github.com/batfish/batfish/commit/99ee00da221f82dabc96075cb4642c004165f1aa#diff-c8602ac9b6ac80a8ed85c9dfcc308e79L14.
Re-add these checks, and fix the existing bugs.

Checkstyle: add back in unused import checks

---

projects/batfish/src/main/java/org/batfish/smt/Encoder.java
projects/batfish/src/main/java/org/batfish/smt/utils/PatternUtils.java

The fix avoids adding "don't care" variables to the final model. There was also a second issue with iBGP edges being included as valid destination interfaces.
This fixes #444

Fix NPE in SMT code due to z3 don't care assignments to variables

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java

This will allow the garbage collector to clear the cache if memory pressure is on.
I tried soft references instead, which in principle should be collected less aggressively, but unfortunately they were not actually garbage collected in practice. This may be OS-related [swap on?] or JRE-related [garbage collector algorithm?], but tl;dr: I was not able to make soft references work.

Batfish: use a cache of weak references for the data plane

---

projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java
projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
tests/basic/aclReachability.ref
tests/basic/nodes-unit-tests.ref
tests/basic/nodes.ref
tests/basic/traceroute-1-2.ref

Assign a name to each accessListLine that read from iptable files for host configuration format.
Mimic the way how we set the name for accessListLine in `.config` file, for example: 
for line: `access-list 101 permit ip host 1.0.1.0 host 255.255.255.0`, we set the name to `101 permit ip host 1.0.1.0 host 255.255.255.0`. 
What current solution does:
for line: `-A INPUT -p udp --dport 53 -j ACCEPT` in iptable file, we set the name to `-p udp --dport 53 -j ACCEPT`. 
This closes #437

assign a name for accessListLine that from an iptable file

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java
projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesMatch.java
projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
test_rigs/router-iptables/configs/host1.cfg
test_rigs/router-iptables/hosts/host1.json
test_rigs/router-iptables/iptables/host1.iptables
tests/basic/commands
tests/basic/router-iptables-init.ref
tests/basic/router-iptables-nodes.ref

- Writes host vendor configs to a separate directory
- Converts iptables ACLs to router ACLs
- Added tests
- Fixes #221

Allow iptables rules from hosts to be merged into routers

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

If there's no source IP that could be used in VRRP election.

Fix crash when a VRRP is configured but unusable

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/PluginConsumerTest.java

And add a test that serialization is correct in both regular and text
serialization.
The test fails with serializeToText true before this patch.

PluginConsumer: fix serialization when text serialization is enabled

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

Actually say 'putObject' in that API call.
Use infof instead of info when printing complex strings.

WorkMgsService: clean up logging

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

* Introduce utility functions for making the standard 2-element array response
for success and failure, and use everywhere.
* Make sure the logged function names match the functions they're in.
Things to verify in review:
* old SVC_KEY_SUCCESS -> successResponse
* old SVC_KEY_FAILURE -> failureResponse
* WMS:foo matches the name of the function/API call it's in.

WorkMgrService: minor cleanup

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java

Fixes invalid reuse of cache when testrig is replaced (deleted and reinitialized) or otherwise repaired.

invalidate cache when repairing environment

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/smt/Graph.java
projects/batfish/src/main/java/org/batfish/smt/PropertyChecker.java
projects/batfish/src/main/java/org/batfish/smt/answers/SmtDeterminismAnswerElement.java
projects/batfish/src/main/java/org/batfish/smt/answers/SmtNondeterminismAnswerElement.java
projects/question/src/main/java/org/batfish/question/SmtDeterministicQuestionPlugin.java
tests/java-smt/commands
tests/java-smt/ospf3-deterministic.ref
tests/java-smt/stable3-nondeterministic.ref

Adds an "smt-deterministic" question that implements #525 to check if there can be more than one stable network solution. If the can be, it will show the different forwarding behavior for the two cases. The question takes the usual headerspace, number of failures, baseEnvType etc as parameters. The output for the classic bi-stable BGP network:
init-testrig test_rigs/smt-examples/STABLE3
get smt-deterministic
Flow<ingressNode:(none) ingressVrf:default srcIp:0.0.0.0 dstIp:42.42.42.1 ipProtocol:HOPOPT dscp: 0 ecn:0 fragmentOffset:0 packetLength:0 state:NEW tag:SMT>
Delta forwarding case 1:
R2,Serial1 --> R3,Serial0 -- BgpRoute<42.42.42.0/24,nhip:192.168.43.1,nhint:dynamic>
R3,Serial1 --> R1,Serial1 -- BgpRoute<42.42.42.0/24,nhip:192.168.44.2,nhint:dynamic>
Delta forwarding case 2:
R2,Serial0 …

Query for determinism

---

projects/batfish/.externalToolBuilders/.gitignore
projects/batfish/.externalToolBuilders/org.eclipse.xtext.ui.shared.xtextBuilder.launch
projects/batfish/.project

- just too slow to use other than in exceptional circumstances
- may be re-added later if parsers are broken up and xtext index refresh
no longer takes forever

disable xtext builder by default for batfish project

---

projects/batfish/src/main/java/org/batfish/smt/EncoderSlice.java
tests/java-smt/stable3-forwarding.ref
tests/java-smt/stable3-nondeterministic.ref

Need to use the canonical network prefix so that set membership queries work properly.
Should fix the issues with the demo queries.

Minor fix for handling of BGP network statement

---

projects/batfish/src/main/java/org/batfish/bdp/AbstractRib.java
projects/batfish/src/test/java/org/batfish/bdp/AbstractRibTest.java

Refactoring AbstractRib and adding tests

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java

Reverts batfish/batfish#493
This changes the output of the `load-questions` command. The output after the change includes only lower-case names of questions. This behavior should be prevented, and a unit test added to make sure the name that comes out is the actual `instanceName` of the loaded question.

Revert "updating client to fetch questions from batfish service"

---

projects/pom.xml

From the docs:
> This rule requires that dependency version numbers converge. If a
> project has two dependencies, A and B, both depending on the same
> artifact, C, this rule will fail the build if A depends on a different
> version of C then the version of C depended on by B.
This will generally improve build safety. Also resolve two existing
dependency convergence issues.

pom.xml: turn on Maven dependency convergence

---

projects/batfish-client/pom.xml
projects/batfish/pom.xml
projects/coordinator/pom.xml

We can run all the main classes from allinone-bundle, so we do not need the
Batfish, Client, or Coordinator bundles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/621)

Batfish: stop producing bundles other than allinone

---

projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java

- eliminate mark and defer strategy
- instead, if you don't have priority to send advert, send it iff you sent it last iteration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/657)

fix oscillation recovery

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

The method `WorkMgr.initTestrig` now creates a metadata.json file in the testrig's base folder. That file looks like:
```
{
"timestamp": 1510696220687
}
```
where 1510696220687 is the time upon testrig initialization (in milliseconds since 1970).
Let me know if I should make changes to better match existing conventions (e.g. how I'm getting the timestamp, how and when I'm creating the file, where and how I'm storing it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/668)

Add testrig metadata file with timestamp

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserErrorListener.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/ParseTreePrettyPrinterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/TestGrammarSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/RecoveryGrammarTest.java
projects/batfish/src/main/java/org/batfish/config/Settings.java

Integrating [Dustin's change](https://github.com/batfish/batfish/pull/510)
Added option to specify a maximum number of characters to display for parse tree pretty print (defaults to 0, meaning no maximum) and unit test for new printWithCharacterLimit function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/675)

Add option to truncate parse tree print

---

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcEntity.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NatGateway.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NatGatewayAddress.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java
test_rigs/parsing-tests/unit-tests.ref
test_rigs/unit-tests/aws_configs/NatGateways.json
tests/basic/init-unit-tests.ref
tests/basic/nodes-unit-tests.ref

this is mostly parsing. deeper integration of nat gateways is not done. opened issue #681 for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/682)

aws natgateways parsing

---

projects/pom.xml
tools/common.sh

* Adds a Maven profile called 'fast' that disables checkstyle, findbugs,
PMD, CPD, and tests and which is enabled by default.
It can be disabled by using '-P !fast'.
* This profile is automatically activated unless the user explicitly
opts out. This was requested by the team.
* Make sure that Travis and related still execute the full tests by
ensuring that the fast profile is disabled in `batfish_test_all`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/686)

pom.xml: add fast profile and use it everywhere but batfish_test_all

---

projects/batfish-common-protocol/pom.xml
projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java
projects/batfish/pom.xml
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/coordinator/pom.xml
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/pom.xml

1.) Updating workItem to pass on the spancontext between different threads
2.) Currently using a child_of relationships for all spawned threads, other alternative is follows_from
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/683)

Connecting the Worker service runTask API to the trace of the client and the coordinator

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

Improved alternative to #678. No new API calls, but the existing API calls have been modified to anticipate this storage setup:
```
myContainer
|- analyses (contents unchanged)
|- questions
|- myAdhocQuestion
|- question.json
|- testrigs
|- myTestrig
|- answers
|- myAdhocQuestion
|- myTestrigEnv
|- standard
|- answer.json
|- differential
|- myDeltaTestrig
|- myDeltaEnv
|- answer.json
```
Testrig directories are no longer expected to contain a folder called `questions`, so old testrigs will lose track of their existing adhoc questions when this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/690)

Alter where API stores/finds adhoc questions and answers

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChain.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Disjunction.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DisjunctionChain.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Not.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/WithEnvironmentExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/BufferedStatement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/CallStatement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statement.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/701)

fix spurious circular references in routing policy called policy detection

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/IpsecTunnel.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnConnection.java
tests/basic/nodes-example-aws.ref
tests/basic/nodes-unit-tests.ref
tests/basic/topology-example-aws.ref

- consistently hash pre-shared-keys across vendors
- properly add aws generated interfaces to aws nodes
- set default ipsec and ike properties for cisco ipsec vpns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/718)

various vpn fixes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java

- generate peer ip address if none specified
- don't use empty constructor (reserved for Jackson)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/709)

fix bgp neighbor builder behavior wrt owner and remote ip

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NodeRoleSpecifier.java
tests/basic/roles.ref

The act of pretty printing the answer would change the role map from
the user's input. This seem like undesired behavior.
Note that the failing test aimed to test the case when roles were provided
and role inference was off. But the ref did not match the input roles
(and now does).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/721)

NodeRoleSpecifier: add a missing deep copy

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/symbolic/Graph.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/OspfSessionCheckQuestionPlugin.java

environment-level topology is dumped for the default environment as part of testrig initialization. there is no obvious hook for doing that for environments that come later, so punting on that for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/727)

generating environment level topology for the default environment

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

Instead of stopping in-memory, serialize directly to disk. On a small-scale testbed (~1100 configs), these two changes let me reduce memory requirements to under 500MiB from a couple of gigs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/729)

Serialize memory improvement

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java

We already have computed it in settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/730)

Batfish: don't recompute env topology path

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java

Includes some refactoring to make the disabling code more accessible.
Also:
* Make getXBlacklist() return empty set instead of null if no blacklist present,
to simplify caller code.
* And add some Javadoc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/734)

Batfish: serialize env_topology after disabling unusable interfaces

---

projects/batfish/src/test/java/org/batfish/bdp/VirtualRouterTest.java

Removed constant apparently unused in `VirtualRouterTest`. Reviewers should verify this was not meant to be used somewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/742)

remove unused constant

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java

Fixed the header field from which ApiKey was extracted in the v2 API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/754)

Fixed v2 rest api key extraction from request

---

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Instance.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Vpc.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnGateway.java
tests/basic/nodes-example-aws.ref
tests/basic/topology-example-aws.ref

- add iBGP sessions between VPN gateways and VPC router
- only send routes from VPN gateway to VPC router
- Subnet "router"s are now only connected to their instances and VPC
router
- Add null route for each VPC CIDR block on VPC router
- Add static routes pointing to each subnet "router" on VPC router
- Apply network ACL only to subnet "router" interface facing VPC router
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/756)

rework VI structures generated from AWS

---

projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/MapAuthorizer.java
projects/coordinator/src/test/java/org/batfish/coordinator/MapAuthorizer.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java

As promised, adding tests for #754. Combining a straight-forward in-memory authorizer with jersey tests to check that the API key is extracted from the correct HTTP header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/764)

Tests for WorkMgrServiceV2, ensure correct api key header is used

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java

It was never finding any matching workitems because it was comparing container and testrig names using `==` instead of `.equals`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/776)

Change == to equals for some important strings

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTests.java
projects/batfish/.settings/org.eclipse.core.resources.prefs
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/question/src/main/java/org/batfish/question/IpsecVpnCheckQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/PairwiseVpnConnectivityQuestionPlugin.java

When two `SourceNat`s share at least one public IP, use the
disjunction of the induced `IpSpace`s when considering whether a
private ip lies behind a given public ip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/773)

fix crash on snats with overlapping ips

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

Updated checkTasks in the work manager to check on all incomplete, assigned work (and updated the work queue manager to support providing a list of these work items).
This fixes #775 where only the first incomplete, assigned work item is checked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/777)

Check status for all incomplete, assigned tasks

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureEquivalenceSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureEquivalenceSets.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/question/src/main/java/org/batfish/question/CompareSameNameQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/OutliersQuestionPlugin.java

`CompareSameName` now runs asymptotically faster by hashing and caching JSON representation of structures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/787)

optimize CompareSameName

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java

Since other clients use the instance name as the question name, this makes it so we can find and use these questions later.
This is for the `answer <question>` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/797)

Client: copy question name to question instance name

---

projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

Logs to capture info about
1. Number of data-plane iterations and # log entries per node
2. Whether hosts config, topology, bgp, routing tables provided with testrig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/801)

Logs for data-plane generation meta-data and additional test-rigs data

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/DisplayHints.java
projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathResult.java

- use `Long` instead of `Integer` to avoid losing precision
- include inner exception when displayhints extraction fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/834)

displayhints fixes

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

It becomes clearer now why the client is getting the response much later after the job actually completes. The interval between coord's subsequent checktaskstatus calls and also client's get work status calls cause the delay in getting the final answer to generate dataplane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/856)

adding spans for checktask status in coordinator

---

projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java
projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java
projects/batfish/src/main/java/org/batfish/z3/NodJob.java
tests/basic/commands
tests/java-smt/commands

Added a batfish setting for Z3's `timeout` parameter. Passed it to Z3 in Minesweeper's `PropertyChecker` and Batfish's `NodJob` and `CompositNodJob` classes. Had to add some plumbing to get the Settings object to `PropertyChecker`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/855)

Z3 timeout

---

tools/install_z3_osx.sh

We should install the z3 binary on osx as well as the libraries.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/877)

Copy over z3 binary in the install script for osx

---

projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/RdsInstanceMatchers.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/RdsInstanceMatchersImpl.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/SubnetMatchers.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/SubnetMatchersImpl.java
projects/batfish/src/test/resources/org/batfish/representation/aws/RdsInstanceTest.json
projects/batfish/src/test/resources/org/batfish/representation/aws/SubnetTest.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/NetworkAcls.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/NetworkInterfaces.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/RdsInstances.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/Reservations.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/SecurityGroups.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/Subnets.json
projects/batfish/src/test/resources/org/batfish/representation/aws/rds-instance/aws_configs/Vpcs.json
test_rigs/example-aws/aws_configs/us-west-2/RdsInstances.json
test_rigs/example-aws/aws_configs/us-west-2/SecurityGroups.json
tests/aws/nodes-example-aws.ref
tests/aws/topology-example-aws.ref

Includes:
1)changes for RDS instance
2)changes for allocation of unique Ips from subnet CIDR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/872)

Including RDS in aws representation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTest.java
projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/Abstraction.java
projects/batfish/src/main/java/org/batfish/symbolic/utils/PrefixUtils.java

* simplify getNetworkEnd to be O(1) instead of linear time.
* Add tests of canonicalization and also containment.
* Update Prefix#containsPrefix to include equal prefixes
and update all callers / delete unused callers.
Fixes #644.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/883)

Prefix: simplify and add tests

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
test_rigs/parsing-errors-tests/recovery-no-verbose.ref

I noticed we print the line text twice -- that seems unnecessarily verbose.
Also explains why the warnings can't really be linked to a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/884)

Less verbose warnings for unrecognized lines

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

Adds API calls `getParsingWork` and `getDataplaningWork`. Both take in a testrig name and return the most recent parsing or dataplaning work on that testrig, complete or incomplete, in the same format you would get it from `listIncompleteWork`. Makes progress information more accessible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/885)

Add API calls to get parsing or dataplaning work

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java

Currently workers can crash when logging very large answer strings, because we are doing an in-memory utf-8 encoding.
This fixes the crash by switching the encoding to be done using streams
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/895)

Use output stream when writing task log files

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureOutlierSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/IRoleConsistencyQuestion.java
projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/NamedStructureRoleConsistencyQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/OutliersQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/RoleConsistencyQuestionPlugin.java
tests/basic/inferPolicies.ref
tests/basic/nsRoleConsistency.ref
tests/basic/outliers-verbose.ref
tests/basic/outliers.ref
tests/basic/outliers2.ref
tests/basic/outliers3.ref
tests/basic/perRoleOutliers.ref

Fixes a bug that caused pretty printing to differ across different clients.
And a few other changes:
- lower threshold for inferring policies
- remove outliers about server sets that should not exist, as they seem likely to be false positives
- add Jackson annotations so that IRoleConsistencyQuestions can be deserialized
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/893)

include the structure definition in the output for named structure outliers

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish/src/main/java/org/batfish/main/Driver.java

Moved `sigint` handling from the worker to the client. 
I believe this more closely matches the expected `ctrl+c` behavior: if the mode is interactive (or client only): the signal is ignored and request to kill work is sent.
If the mode is coordinator or worker, the interrupt will kill the process.
Tested locally with intellij.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/896)

Moved signal handling from worker to client

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfArea.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaSummary.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4
projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfCost
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfCostDefaults
test_rigs/parsing-tests/unit-tests.ref
test_rigs/unit-tests/configs/cisco_ospf
tests/basic/nodes-unit-tests.ref

For #873.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/897)

Cisco ospf cost

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

Fixes the issue where testrig is left in dataplaning_failed state after parsing fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/900)

handing queue failure status separately from abnormal termination

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnalysisMetadata.java
projects/coordinator/src/main/java/org/batfish/coordinator/AnalysisMetadataMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

Adds analysis metadata (containerName/analyses/analysisName/metadata.json) with a creation timestamp and a boolean `suggested` property. `configureAnalysis` now has an optional boolean argument `suggested`. When `configureAnalysis` is called:
- with `suggested` set to a non-null value:
- if analysis already has a metadata file, update its `suggested` property
- otherwise create a metadata file with the given `suggested` value
- with `suggested = null`:
- if creating a new analysis, create a metadata file with `suggested = false`
- otherwise do not check or change metadata
Creation timestamps are not currently used but seem like a reasonable thing to include.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add analysis metadata

---

projects/coordinator/src/main/java/org/batfish/coordinator/AnalysisMetadataMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

`listAnalyses` now has an optional Boolean parameter `suggested`. If `suggested` is:
- `true`: only suggested analyses will be returned
- `false`: only user analyses will be returned
- `null`: all analyses will be returned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/904)

Add "suggested" filtering to listAnalyses

---

.travis/build.sh

- temporary fix for listen ports not reopening quickly enough after watchdog kills worker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/906)

temporary fix for listen ports not reopening quickly enough

---

.travis/build.sh
.travis/travis_coordinator.properties

Shaves about 2 minutes off of Travis build time, which suggests that redesigning the coordinator's task completion mechanism would give gains.
cc: @haverma
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/921)

travis: reduce the coordinator assign work period to speed up tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Task.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EnvironmentMetadata.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/coordinator/src/main/java/org/batfish/coordinator/TestrigMetadataMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

The idea is that if a testrig has failed to parse or dataplane, the metadata should contain the error message that caused the failure (e.g., "No valid configurations found"). This is implemented by adding an `errMessage` property to `Task`. Details:
- `Batfish._terminatedWithException`, a boolean, has been replaced with `Batfish._terminatingExceptionMessage`, a String that is null if no error occurs
- In `Driver.runBatfish()`, when an exception occurs in the running thread, the Batfish instance stores the error message as `_terminatingExceptionMessage`
- `runBatfish()` returns the error message (if any, otherwise null) instead of a boolean
- `Driver.runBatfishThroughService` sets its task's error message to the output of `runBatfish()` if any error occurred
- …

If parsing or dataplaning fails, put err msg in metadata

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

Renames folders in /containerName/original to include timestamp. Example for testrig named Dakota: `LHR/original/Dakota_2018-02-15T18:41:47.341Z/testrig.zip`
Fixes #944.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/950)

Put timestamp into names of folders in /original

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfExternalType1RouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfExternalType2RouteTest.java

OSPF external type routes were not doing and `instanceof` check.
Added the check and tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/948)

Implement stricter type checking in equals OSPF external routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BaseSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java
projects/batfish/pom.xml
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/config/SettingsTest.java
projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
projects/coordinator/src/test/java/org/batfish/coordinator/config/SettingsTest.java

*Purpose*:
Partially addressing #894 
Allow settings to be copyable, which in turn allows task arguments to be layered on top of arguments passed to the worker at the start (as opposed to overriding them completely, which is what is happening currently and is not the desired behavior).
*Implementation*:
- Use the underlying configuration object for storing settings as opposed to local fields
- Keeping the existing getters/setter for compatibility
- Additional tests for settings
- Changes to `runBatfishThoughService`: task settings are copied over from `_mainSettings`
*Not in this PR*:
Settings hooks, i.e., allowing different plugins to register custom settings. Deferring to a different PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Settings changes

---

projects/batfish/src/main/java/org/batfish/z3/expr/Comment.java

The `Arrays` functions do handle `null`.
* IntelliJ warned about one of these.
* Bazel warned about both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/967)

Comment: fix equals/hashCode

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Snapshot.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ConvertConfigurationAnswerElement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ValidateEnvironmentAnswerElement.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/EnvironmentTest.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishStorageTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/question/src/main/java/org/batfish/question/PerRoleQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/UnusedStructuresQuestionPlugin.java

A hodge-podge of restructuring in an attempt to make it more obvious where and how configurations are cached. Now all loading and cache management is in a single place.
* Added `BatfishStorage`, to which we can start moving the code in Batfish that deals with file serialization. Started by moving the code that loads configurations off of disk.
* Added `Snapshot` as a concise way to specifically represent which the testrig+environment under use. Made `Snapshot` the key for the testrig cache, as it contains the only two fields that were actually used in hashcode/equals.
This change and the above are steps towards getting rid of `TestrigSettings`. For example, I was able to delete both two paths for vendor-independent configs and convert answer element.
* Rewrote `loadConfigurations` in …

Batfish: cleanup caching and loading testrigs

---

projects/batfish/src/main/java/org/batfish/symbolic/Graph.java

No tests broke?
My reading of the current version of the code is that the [OSPF costs are initialized](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2969) before the [vendor-independent configurations](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1584) are even written to disk.
What was this code for? Is it necessary?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/968)

Graph: delete seemingly unnecessary code

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

The new API call retrieves the parsing warnings recorded in `parse_answer` file, which is a Java-serialized `ParseVendorConfigurationAnswerElement`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/974)

Add API call to get parsing warnings

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java

Couple of logging tweaks:
- Add logging message when compressed dataplane is being computed
- In `BatfishStorage` one of the log strings wasn't producing the right output. It's not python nor were we using `MessageFormat`

Small log message tweaks

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/AnalysisMetadataMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

- Using boolean caused the client to always get only the user policies even when it passed `null` for `suggested` parameter, as  `null` was converted to `false` when received by `WorkMgrService`
- Enum will prevent `nulls` being exchanged between the client and service when providing a valid value of `AnalysisType` is made mandatory for client in the future

Using enum instead of boolean to filter analyses in list-analysis

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishANTLRErrorStrategy.java

You can't `@link` to a parameter of the current function

BatfishANTLRErrorStrategy: fix javadoc

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/AbstractOutlierSet.java

Was comparing a String to an Optional<String> -- now comparing two Optional<String> objects.

equals() bug fix in AbstractOutliersSet

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/InlineCommunitySet.java

Eclipse Oxygen does not like this cast again. Moving to separate function so I can suppress with minimal side effects.

Shut eclipse up about unchecked intersection cast

---

projects/batfish/src/main/java/org/batfish/main/Driver.java

(this gap was created when we moved the signal handler to client.)

ignoring ctrl+c when run through watchdog

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

This fixes a bug where trying to update a check without changing its name would cause a `Question 'foo' already exists for analysis 'bar'` error. The bug occurred because the code that deletes questions was after the code that adds questions. This PR just moves the question deletion section to before the question addition section.

In configureAnalysis, do question deletions before adding questions

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

If client doesn't supply an analysis type, it should list only user analyses by default.

List only user analyses by default

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospfmetric

* Fix inheritance (inverted condition on whether inheritance had been performed)
* Add parsing for metric configuration for an ospf area interface
* Add inheritance of ospf cost and ospf area
* Rename parameter in setOspfCost
* and test with new matchers and everthing.

Juniper: support ospf area interface metric

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/job/BatfishJobExecutor.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java
projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java
projects/batfish/src/main/java/org/batfish/z3/Field.java
projects/batfish/src/main/java/org/batfish/z3/NodContext.java
projects/batfish/src/main/java/org/batfish/z3/NodJob.java
projects/batfish/src/main/java/org/batfish/z3/NodProgram.java
projects/batfish/src/main/java/org/batfish/z3/OriginateVrfInstrumentation.java
projects/batfish/src/main/java/org/batfish/z3/TransformationHeaderField.java
projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java
projects/batfish/src/main/java/org/batfish/z3/expr/VarIntExpr.java
projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BitVecExprTransformer.java
projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BoolExprTransformer.java
projects/batfish/src/main/java/org/batfish/z3/expr/visitors/ExprPrinter.java
projects/batfish/src/main/java/org/batfish/z3/expr/visitors/VariableSizeCollector.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/FuncDeclTransformer.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java

For queries with the same destination node and header constraints but
with different origination node/vrf, we can combine them into a single
query and use model refinement to find solutions to each original query.
Use a Field class for NoD variables, rather than only the enums in
BasicHeaderField and TransformationHeaderField. Using Field makes it easier to
do instrumention. The enums are still there though, at least for now.
We can consider moving away from them later.
Instrument ReachabilityProgram to solve for OriginateVrf.
The instrumentation adds a field of variable width. The instrumentation
is a post-processing step that runs after Synthesizer. This is for three
reasons: 1st, I wanted to avoid adding complexity to Synthesizer; 2nd,
synthesizer doesn't know what OriginateVrfs to …

Combine multiple reachability queries into chunks

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interfaceMtu
test_rigs/parsing-tests/unit-tests.ref
tests/basic/init-unit-tests.ref
tests/basic/nodes-unit-tests.ref

We have a helper to get the interface name out, but we were not using it in all places.
Now all references to Interface_idContext.name go through the helper, and we no longer
drop suffix in various places.

FlatJuniper: more rigorous about interface name

---

projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java

Fixes a NPE bug that occurs when a network device does not own any IPs. The solution is to initialize the ipOwners map so that each device has an entry.

fix ipOwners bug

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java

It's not like this provides all that much more security, especially if authorizers are not setup; just annoyances when developing.
**Note**: Removing associated coordinator arg/setting as well, since I doubt anyone uses it.

Allow listing containers with default api key

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/main/BatfishStorageTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java

Until we can debug/optimize compression on large networks, start
caching the compressed configs in addition to the compressed dataplane,
and switch reachability to use general compression, rather than
compressing per-query (which yields better NoD performance).

Cache compressed configs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BaseSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/pom.xml

Followup on #1038:
Add an argument to control the behavior (i.e., whether the reachability check is performed)
Side effect of this PR: Update commons-configuration to version 2.2, as it has better handling of `ImmutableConfiguration`s

Add flag to control bgp session reachability check

---

projects/batfish-common-protocol/pom.xml
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
projects/batfish/pom.xml
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
projects/pom.xml

*Purpose*:
Switch from gzip to lz4 for faster (de-)serialization times.
*Implementation*:
- Replace gzip with lz4
- Keep backwards compatibility with gzip by allowing de-serialization of gzip-compressed files
- Which led to slightly more involved (but seemingly more versatile) format detection.
*Additional changes*:
- Perform deserialization without intermediate byte arrays, using streams directly and in one batch in `deserializeObjects`.
*Notes*:
@dhalperi Switched from lz4 block streams to frame streams. This way files have magic numbers (for format detection), and also the internet claims it more interoperable with other tools (e.g., cli tools)
Co-authored-by: dhalperi <dhalperi@users.noreply.github.com>

Switch default compression to lz4 when (de-)serializing objects

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

Right now, we don't find out questions have bad parameters until we run them. This PR changes this by having the coordinator validate the question before saving it to disk.
@ratulm opinion?

WorkMgr: validate questions before accepting and saving them

---

projects/pom.xml

The Bill of Materials is a single thing you import that
automatically defines the dependency version for all related
projects. Seems significantly simpler to maintain, since we
won't accidentally add new versions of every thing we want to
depend on.

pom.xml: switch to Jackson BOM

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java

The null values are allowed, and handled.
This was causing runtime errors in IntelliJ, which actually uses Nullability analysis at runtime.

BgpAdvertisement: remove bogus nullable annotations

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java

Otherwise, testout files may be incorrectly leftover for passing tests.

Client: delete any existing testout file

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/aws/ElasticsearchDomain.java
projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java
projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/Route.java
projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/main/java/org/batfish/representation/aws/Vpc.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnGateway.java
test_rigs/parsing-tests/unit-tests.ref
tests/basic/init-unit-tests.ref

`ConvertConfigurationResult` class supported a map of `Configurations` but accepted only a single `Warnings` object, changed that to a `Map` of `<Hostname, Warnings>` so that we can store a separate `Warnings` object for each configuration. It worked for physical `Configuration` nodes as in that case the `configurations` map contains just a single node at a time, whereas for AWS configs it contains all AWS nodes parsed.

Enable recording warnings per AWS config node

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java

Supplements #clone(Class) for generic types.

BatfishObjectMapper: add #clone(TypeReference)

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
tests/aws/commands
tests/basic/commands
tests/jsonpath-addons/commands
tests/ui-focused/commands
tests/watchdog/commands

Always falling-back to comparing raw file content masks deserialization errors in answer elements.

 Client: indicate non-answer tests explicitly using raw test mode

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpLink.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfNeighbor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfNeighborTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LinkMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchersImpl.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/AbstractionBuilder.java
projects/batfish/src/test/java/org/batfish/bdp/OspfTest.java
tests/basic/commands
tests/basic/neighbors-summary.ref
tests/basic/neighbors.ref

1) Reorder the basic commands file to make it clear which refs we'll keep.
2) Fix a bug in OspfNeighbors serializability -- it had no creator.
3) Replace Pair<Ip,Ip> with IpLink throughout OspfNeighbor. Pair is not
JSON-serializable by choice.
This is for #1084

Reorder commands and fix OspfNeighbor and yak shaving.

---

test_rigs/example-aws/aws_configs/us-west-2/ElasticsearchDomains.json
test_rigs/example-aws/aws_configs/us-west-2/SecurityGroups.json
tests/aws/nodes-example-aws.ref

- Changed the VPC ID in the RDS security group to match RDS's VPC
- Changed Elasticsearch's security to a security group in the same VPC as Elasticsearch
- Removed a security group with a duplicate SG-ID which was only used by RDS as RDS is not using it now

Fixing AWS refs for elasticsearch and RDS

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json
tests/aws/nodes-example-aws.ref

In addition to allowed inbound/outbound packets, also allow packets containing ACK and packets containing reversed inbound/outbound rules

Adding rules to allow responses to permitted TCP requests

---

projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
projects/batfish/src/main/java/org/batfish/representation/aws/ElasticsearchDomain.java
projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java
projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/Route.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/NetworkAcls.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/NetworkInterfaces.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/Reservations.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/SecurityGroups.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/Subnets.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/Vpcs.json
test_rigs/example-aws/aws_configs/us-west-2/SecurityGroups.json
tests/aws/nodes-example-aws.ref

- Moved out conversion of SG to ACLs from the individual `toConfigurationNode` methods as we will need all associations of SGs -> IPs to populate ACLs, and for some AWS constructs(Database instances) we generate IPs on the fly. 
- Use SG->IP mapping to populate Dest/Src for IP Permissions
- Testing this in RDS and ES as that will cover the changed code

Adding support to use Security Groups IDs as source or dest in Inbound/Outbound rules

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java

The forwarding analysis can take close to a minute for large networks. Since it is independent of the question, we can compute it once and cache it.

cache forwarding analysis

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/FalseExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/MatchHeaderspace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/MatchSrcInterface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/NotMatchExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TrueExpr.java

`IpAccessListLine` constructor now creates a `MatchHeaderspace` to support new `AclLineMatchExpr` functionality in parallel with current ACL line matching

Populate MatchHeaderspace when creating IpAccessListLine

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CommonUtilTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

1. The vrrp group with highest priority should take precedence, we were using lowest.
2. Added the tie breaker (highest IP) in case group priorities are equal
(Following https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/priority-edit-interfaces-vrrp.html)
3. (2) required a change to an existing test: `testMultipleBestVrrpCandidates`

Fix Vrrp handling in computeIpOwners

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java

Followup on #1137, make vrrp group comparisons look cleaner using chained comparators.

Cleanup vrrp comparison

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureType.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/access-group-acl/configs/iosAccessGroupAcl
test_rigs/parsing-tests/unit-tests-undefined.ref
test_rigs/parsing-tests/unit-tests.ref

Cisco does not mentions anywhere that only IP access lists are allowed with access-groups (https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/qos/command/qos-cr-book/qos-m1.html#wp7738095440),
So we should support mac-acl as well

Allowing access-groups to also accept mac-acls

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserATNSimulator.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/parsing-recovery/configs/ios-recovery-1141

Otherwise we lose the rest of the file (or until a line is valid in the
current context).
Fix https://github.com/batfish/batfish/issues/1141

BatfishParserATNSimulator: leave outer context if its line is thrown out

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java

It was possible for `Interface.equals` to throw a nullpointer when bandwidth was unset. Fixed.

Avoid null pointer in Interface.equals

---

projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java

Include all ACLs in the synthesizer, not just ACLs attached to edge
interfaces. Also removed the default source NAT ACL that permitted
everything. It's simpler and more efficient to simply remove the
ACL prestate for source NATs with no ACL.

Synthesize all ACLs

---

projects/batfish/src/main/java/org/batfish/representation/cisco/BgpProcess.java

Was only honored for static sessions.
I anticipate needing to update some refs, but this is the issue.

BgpProcess: honor _defaultActivate in dynamic sessions too

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/nxosBgpVrf

In cisco (nxos at least) it's valid to have `bestpath as-path multipath-relax` in a router bgp vrf block. We didn't support that, and the parser was resetting to the default vrf, causing bgp neighbors to assigned to wrong vrfs.

Cisco: add as-path relax-multipath under vrf block

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishException.java

Parsing could fail in a certain case due to Java trying to serialize a BatfishException.

Don't try to serialize property _exception of BatfishException

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NextHopExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetNextHop.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassfulTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/PrependAsPathTest.java
projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetNextHopPeerAddress.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicyNextHopPeerAddress.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicyNextHopSelf.java

Context:
- We were crashing with NPE when executing next-hop-self
- Root cause: Passing in wrong VRF when creating environments in (i)bdp, fixed now.
Additional changes: 
- Support not just peer address but also peer prefix in routing policy/environment.
- Better nullable annotations (RoutingPolicy is used for multiple protocols, where we pass `peerAddress==null`
- Builder for `routingpolicy.Enviroment` to make dealing with all of this easier.
- Small fixes to ibdp that were part of #1165 for regular bdp

Fixing routing policy null pointers + support for dynamic sessions

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java

When performing traceroutes to check BGP neighbor reachability, ingress VRFs matter.

Honor vrfs during bgp topology construction

---

projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java
projects/batfish/src/main/java/org/batfish/z3/state/NodeInterfaceNeighborUnreachable.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/GenericStateExprVisitor.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/Parameterizer.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/StateVisitor.java
projects/batfish/src/test/java/org/batfish/z3/state/visitors/DefaultTransitionGeneratorTest.java

- transition from nodeInterfaceNeighborUnreach to nodeNeighborUnreach
- allows us to determine if a header injected at some ingress interface, egresses a specific interface
- add tests
- passes full regression test

Add finer-grained neighborUnreachable predicate by interface

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java

Follow up on #1208 
Reply packets can originate in a differently-named vrf, need update the flow builder for reply traceroute.

Honor vrfs during bgp topology construction, followup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacesSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacesSpecifierTest.java

Allow specifying interfaces by regexes on VRF name. Example: `vrf:internal.*`.

 Enable specifying interfaces by VRF.

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/ITracerouteEngine.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/bdp/BdpDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java

Incremental progress towards cleaner dataplane code
*Changes*:
- No functionality changes
- Pull out a traceroute engine
- Single traceroute engine interface (`TracerouteEngine`, formerly `FlowProcessor`)
- Single traceroute implementation (`TracerouteEngineImpl`), as a singleton.
- De-duplicate tests.
- Decouple traceroute engine from dataplane internals. No need for traceroute to know about `Node` and `VirtualRouter`, it operates on datamodel classes and info extracted from `Dataplane` interface, namely `Configuration` and `Fib`

Pull out traceroute engine into a separate class

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java

Not sure why travis didn't flag this, but fix build because `FlowProcessor` is no longer there.

Resolve #1252 and #1245

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java

Followup on #1262:
Boxing/unboxing won't work for null values, so updated getters and setter to primitives as well.
There was only one place where we expected a `Boolean` and we weren't handling that in any sophisticated way, so this change should not be a problem.

ProxyArp: update getter & setter to primitive boolean

---

projects/batfish/src/test/java/org/batfish/dataplane/bdp/DynamicBgpTest.java
projects/batfish/src/test/java/org/batfish/dataplane/bdp/RipAndBgpTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobAclTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java

Quality of life enchancement:
- Automatically register both dataplane plugins for tests when getting batfish instance through `initBatfish` or `getBatfishFromTestrigText`.
- This simplifies writing tests that are not tied to a particular dataplane engine. No need to explicitly create `BdpDataplanePlugin` and this will also make tests work with ibdp.
- The plugin picked will the the default one specified in `Settings`, which currently is still **bdp** (working towards switching).

Register dataplane plugins in BatfishTestUtils

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixListExcept.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourcePrefixList.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourcePrefixListExcept.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDestinationPrefixListExceptTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDestinationPrefixListTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromSourcePrefixListExceptTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromSourcePrefixListTest.java

* Added null checks for IpSpaces when applying `FwFrom`s to headerSpaces

Add null checks in Juniper FwFrom conversion

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4

1. Remove special handling for default, since it's really complicated.
2. Update grammar to support template peer-session inability to change address-family.

Make the NXOS grammar differently strict

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixRange.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterLine.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixRangeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixSpaceTest.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLineLonger.java
projects/batfish/src/test/java/org/batfish/dataplane/bdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
test_rigs/parsing-tests/unit-tests-nodes.ref
tests/basic/nodes.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref

Three changes to simplify use of PrefixRange:
* simplify construction PrefixSpace construction - relax `Set<PrefixRange>` to `Iterable<PrefixRange>`, add a varargs version. 
* introduce `DEFAULT_PREFIX_ONLY`, which is the same as `PrefixRange(0.0.0.0/0, [0, 0])`
* introduce `PrefixRange.moreSpecificThan(prefix)`, which is the same as `PrefixRange(p, [p.length+1, 32])`.

Prefix range: simplify

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Route6FilterList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterList.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/IpAsPathAccessListLine.java
test_rigs/parsing-tests/unit-tests-nodes.ref

Also a bit of cleanup so they all work roughly the same way.

CiscoConversions: move a bunch of static utility methods out of CiscoConfiguration

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java

Defining variables far from where they're used and then only using them
once just makes the code harder to read and understand.

CiscoConfiguration: reduce cognitive overhead

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4
test_rigs/parsing-tests/unit-tests-nodes.ref
test_rigs/parsing-tests/unit-tests.ref
test_rigs/unit-tests/configs/cisco_nxos

Before you ask, yes `queuing` is spelled that way on NX-OS:
```
switch(config-cmap)# class-map type ?
*** No matching command found in current mode, matching in (config) mode ***
control-plane  Control-Plane
network-qos    Network QoS class
qos            Qos class
queuing        Queuing class
```

Cisco: improved class-map parsing

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
test_rigs/parsing-tests/unit-tests-nodes.ref
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref

Less clutter in the data model, it's never called anyway, and we definitely shouldn't create it on devices where IPv6 address family isn't even enabled.

CiscoConfiguration: only create BGP_NETWORK6_NETWORKS_FILTER if there are IPv6 networks

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/storm-control

We can parse and ignore storm-control in Juniper like we are doing in Cisco

Parsing storm-control

---

projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java

If remote neighbor does not match the node2Regex we should `continue` to avoid evaluating `matchesStatus`

Fix a bgpStatus null pointer

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
test_rigs/parsing-tests/unit-tests-nodes.ref
tests/basic/nodes.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref

CiscoConfiguration: extract policy to suppress summary-only specifics

---

projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/test/java/org/batfish/dataplane/GetRoutesTest.java

*Context*
- We used to not include node/vrf pairs in the output of the routes question if there were no routes for that vrf.
- This created some confusion when doing dataplane validation (both "visually" and when trying to assert rib size of a vrf using scripts)
*Fix*
- Keep all node/vrf pairs, introducing empty sets where necessary
- Also ensure `getRoutes` of both dataplane plugins return immutable data structures.

Keep all node and VRF names when getting dataplane routes

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-destination-address
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-source-address

* Added null check in `formIpWildCard` to stop crashing on ipv6 addresses
* Updated related tests

Fix IPv6 address parsing in Juniper firewall filter

---

projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicyPrefixSetName.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
test_rigs/parsing-tests/indirection.ref
test_rigs/parsing-tests/unit-tests-undefined.ref
test_rigs/parsing-tests/unit-tests-unused.ref
test_rigs/parsing-tests/unit-tests.ref

Rather than marking a ReferenceCountedStructure and then looping over
them, instead just update the defined structures map (and/or warn
undefined) based on the references made by the extractor.

VendorConfiguration: add functionality to do structure marking directly

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java

Decided that generated ACLs should always be analyzed for reachability, at least for now.
Fixes #1275.

Remove commented code that skipped Juniper SRX generated ACLs

---

projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java

Removed `disabledAcls` from project. Instead, builder for `SynthesizerInputImpl` has a field `enabledAclNames`. If this field is set, the resulting synthesizer input encodes only the specified ACLs; if it is not set, the synthesizer input encodes all ACLs as usual.
This new setup makes it much simpler to create ACL synthesizers in Batfish because it's easier to assemble ACL whitelists than blacklists.
Before this gets merged, I want to add tests to prove that the appropriate ACLs are getting encoded. Any ideas on how to capture that information?

Only encode ACLs being analyzed for reachability

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java
projects/batfish/src/main/java/org/batfish/z3/NodJob.java
projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java

Moves method `optimizedProgram()` from `NodJob` to its grandparent `Z3ContextJob` so that `NodJob`'s aunt/uncle (auncle?) `NodFirstUnsatJob` can also make use of it.

Prune ACL reachability jobs to find blocking lines

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/NodSatJob.java

Third round of jobs (finding blocking lines) was already getting optimized; now first two rounds (finding unreachable and unmatchable lines) also get optimized. Other changes:
- For unmatchable line jobs, a separate synthesizer is now created for each ACL
- Since we decided there's no benefit to creating synthesizers that encode multiple ACLs, the parameters of `synthesizeAcls()` were changed from:
`Map<hostname, configuration>, Map<hostname, aclName>`
to:
`hostname, configuration, aclName`

Optimize all NoD jobs in ACL reachability

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-http-inspection

* Added http inspect class-map parsing support (to stop crashing on encountering these structures)
Fixes #1302

Parsing support for http inspect class-maps

---

projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
tests/roles/inferRoles.ref

fixed a bug in node-name parsing that was requiring 2+ characters in certain tokens where only 1+ character should be required

small role parsing bug fix

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java
projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

And, for now, declare unsupported.

VendorConfigurationFormatDetector: recognize Palo Alto configs

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

- Make registering tracing on `ClientBuilder` optional
- Do not register tracing with the `javax.ws.rs.Client` used by coordinators to poll the workers. 
Because
- They do not have any useful tracing information
- Logs keep crowding the client prompt
- Although there will be logs from `WorkMgr.checkTask()`  still as we create a new `Client` for each ping and they look like: 
```
May 21, 2018 12:22:04 PM io.opentracing.contrib.jaxrs2.client.ClientTracingFeature configure
INFO: Registering client OpenTracing, with configuration:io.opentracing.contrib.jaxrs2.client.ClientTracingFeature$Builder@513ba759
```
But they are not as intrusive as they appear when `batfish-client` is performing some task for the user. This will probably get fixed when …

Fix for OpenTrace client register logs

---

projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java
projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestion.java
projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java
tests/basic/commands
tests/basic/ipowners.ref

"Proper" version of #1291 
- Add the new question, with the `duplicatesOnly` flag, which can function as uniqueIpAssignments
- Return table containing IP and node, vrf, and interface names

Add the IpOwners question in the new table format

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4
test_rigs/unit-tests/configs/cisco_qos
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

Apparently on Cisco ASA at least, something like `1.2.3.4-24` would be a valid name.

Cisco_qos: use more permissive variable names

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
tests/aws/nodes-example-aws.ref

- Based on our previous discussion, tested on an EC2 instance and found that this should be done in both directions, tests are documented [here](https://docs.google.com/document/d/1dDxmZ8aNXSj6qE-xZhkMJAjmkn3sTY4SArkoJeXS2WE/edit#)
- Adding reversed ACLs in the beginning to avoid unreachable ACL lines

Adding reversed ACLs for AWS SGs in the beginning

---

projects/batfish/src/main/java/org/batfish/representation/cisco/Keyring.java

Avoid NPE, which I think is related to this warning:
RedFlag MISCELLANEOUS : Can't get IkeGateway: Local or remote address is not set for isakmpProfile 
(not sure why/when the warning happens)

avoid NPE when we can't figure out the local address in a isakmp profile

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureType.java
test_rigs/unit-tests/configs/cisco_crypto
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

I initially defined the structure too, but this appears to only be usable for a certificate generate request that is only issuable in interactive console mode. Not sure why it shows in the config at all, except that it does...

Cisco: parse Certificate Signature Request params

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-route-preference

- preference is treated as admin distance
- corrected conversion of Juniper static routes where we were storing metric as admin cost

Setting Static route preference for Juniper

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java

Downstream tools can therefore use exit code for useful things.
Had to delete a broken test -- server is not up for these unit tests.

Client: set exit code when, in batch mode, some command fails

---

projects/allinone/src/test/java/org/batfish/allinone/AclReachability2Test.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLines2Rows.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLinesAnswerElementInterface.java
projects/question/src/main/java/org/batfish/question/aclreachability2/AclReachability2Answerer.java
tests/basic/aclReachability2.ref

AclReachability2AnswerElement was already not an answer element -- it didn't use super.rows.
- remove inheritance
- rename class
- simplify API now that it can calls its results things like getRows
- remove Jackson stuff now that it's not JSON-serialized
And a little very minor cleanup like removing an erroneous @Nullable
annotation.

AclReachability2AnswerElement: not an AnswerElement

---

WORKSPACE
projects/pom.xml

This reverts commit 049debda33753bf33306fc89ea1d2bcfc8208da5.
New guava doesn't work with findbugs because they switched Nullable annotations and the world is sad. Figuring this out will be more work.

Revert "Upgrade guava and transitive"

---

projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java

We have some tests that just load the configurations into the cache without
actually generating corresponding config files. However, the cache was using
only weak references, so they could go out of cache under pressure. If this
happened, Batfish would try to re-parse the configs (that don't exist) and
give a stack trace like this:
org.batfish.common.BatfishException: No valid configurations found
at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:4186)
at org.batfish.main.Batfish.repairVendorConfigurations(Batfish.java:3718)
at org.batfish.main.Batfish.loadParseVendorConfigurationAnswerElement(Batfish.java:2668)
at org.batfish.main.Batfish.loadParseVendorConfigurationAnswerElement(Batfish.java:2653)
at org.batfish.main.Batfish.repairConfigurations(Batfish.java:3626)
at …

BatfishTestUtils: prevent test flake under pressure

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

No functionality changes. Just trying to make VirtualRouter smaller/more readable.

ibdp: split some OSPF logic from VirtualRouter

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-default-originate/configs/listener
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-default-originate/configs/originator
tests/aws/nodes-example-aws.ref
tests/parsing-tests/unit-tests-nodes.ref

*Context*:
Routing policy would not set OriginType on default routes, causing ibdp to crash
*Fix*:
When matching default routes, also use `SetOrigin` statements.
Since there is no easy way to nest put an `If` into a disjuction, just pulled this out into a separate policy, hence the ref changes.
*Note*
Made test for IOS; Test for nxos already exists, but is skipped (it needs more dataplane support, coming soon).

Cisco: set BGP origin type when using default originate

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/UndirectedBgpSession.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

- Have a cleaner split between export processing (happens before queuing messages) and import processing (happens when reading messages)
- Minor findbugs fixes, typo & naming/field reordering fixes

ibdp BGP refactoring: split export processing from import

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/ReachabilitySettings.java

* It has been replaced by ReachabilityParameters in IBatfish.
* No longer unset srcIp in the HeaderSpace, because pathDiff doesn't use
sources (it originates from VRFs with changed or removed edges). In
the future, we should add a new question for pathDiff that only
allows the parameters that are used by it.

move ReachabilitySettings into the question project

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/WildcardApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/WildcardPruner.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-wildcards

Fix improper pruning of strings that look like wildcards but did not get generated via `apply-groups`.
Implementation:
- Create new virtual token called `WILDCARD_ARTIFACT` that is used instead of `WILDCARD` when generating lines.
- Prune only lines with `WILDCARD_ARTIFACT` instead of `WILDCARD` as before
- Update parser rules to allow `WILDCARD` or `WILDCARD_ARTIFACT` via new rule `wildcard` so parsing during group line generation phase still works

fix juniper wildcard handling

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java
projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

Update format detection to find other palo alto lines and differentiate between normal and flat (set) format.

Update Palo Alto Networks config format detection

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/InspectClassMap.java

For Cisco Inspect class map style tracking, the defineStructure and referenceStructure along with the markConcreteStructure are already present in the code. It is just matter of updating the DefinedStructure -> ComparableStructure and updating the definition Line calculation.

Cisco Inspect class map style tracking

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/InspectPolicyMap.java

For Cisco inspect policy, as the defineStructure and referenceStructure along with the markConcreteStructure are already present in the code. It is just matter of updating the DefinedStructure -> ComparableStructure and updating the definition Line calculation.

adding stying check for cisco inspect policy map

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/AsPathSet.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java

For Cisco as-path-set, there is no relevant reference made. Hence, just updated the DefinedStructure -> ComparableStructure and updating the definition Line calculation.

as-path-set style checking

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpProcessMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpProcessMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

Fixes #1556 
`bestpath as-path multipath-relax` actually enables multipath for ebgp without explicit `max-path n` needing to be set.
Fix the extraction, which in turn fixes the bug found in #1556

Multipath-relax should enable ebgp multipath 

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/GeneratedRouteHelper.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoNxosTest.java
tests/aws/nodes-example-aws.ref

Fixes #1351 
- Send neighbor-specific generated routes upon session establishment
- Split & test some generatedRoute logic from VirtualRouter
- Un-skip NxOs default-originate test
*Note* Change to CiscoConfiguration:
We were using a setOrigin statement on a generatedRoute policy, which would crash. This change uncovered that code path, so made a fix. Proper origin-set is still executed using per-peer bgp export policy (because of #1528)

ibdp: support neighbor-specific generated routes

---

.gitignore
.travis/build.sh
.travis/jacoco-common.sh
.travis/jacoco-report.sh

Though codecov reports are nicer, we may sometimes want to be
able to view jacoco's reports locally. Added a script
.travis/jacoco-report.sh to do this. It takes an optional parameter
that, when set to "junit", will be a report for junit test coverage only
(excluding ref tests).
Also add jacoco coverage (html and xml) reports to .gitignore

New script to generate local jacoco reports

---

projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java
projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/question/src/main/java/org/batfish/question/ReachabilitySettings.java

Go back to removing srcIp from headerspace when converting ReachabilitySettings to ReachabilityParameters.
Now we modify pathDiff to give meaning to the location and srcIp specifiers: we only originate from edges for which the source interface is a specified source location, and we use the source Ip constraint corresponding to that location.

update pathDiff to use the sourceIpAssignment

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/ColumnMetadataTest.java

Add a private `@JsonCreator` with all-nullable parameters. We can't
guarantee that all parameters will be present when dynamically
deserializing JSON.
Swap to `@ParametersAreNonNullByDefault`, and add the needed `@Nullable`
annotations.

ColumnMetadata: minor fixes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EncryptionAlgorithm.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecProposalMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecProposalMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/arubaCryptoTransformSet
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-crypto-transform-set
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ipsec-proposal
tests/aws/nodes-example-aws.ref
tests/parsing-tests/unit-tests-nodes.ref

- Included representation for  authentication algorithms  using the `Authentication Header` protocol in Cisco and Juniper transform-sets to the data-model([cisco](https://www.cisco.com/c/en/us/td/docs/ios/12_2/security/command/reference/srfipsec.html#wp1017694), [juniper](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/services-ipsec-proposals-configuring.html))
- Added rules for parsing  Aruba ESP encryption algorithm names  having the format - `esp-aes[XXX]`

Ipsec proposals (transform-sets) - improve extraction

---

.travis/jacoco-report.sh

Before trying to build the jacoco report, check if any coverage files
exist. If not, give a helpful error message and exit.

check for coverage files

---

projects/allinone/BUILD
projects/allinone/pom.xml
projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Main.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishException.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/RowMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsApplicator.java
projects/batfish/src/main/java/org/batfish/job/BatfishJobExecutor.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/coordinator/BUILD
projects/coordinator/pom.xml
projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java

Rationale: every module is likely to depend on guava, but less likely to
depend on commons-lang3. Since they're essentially the same function,
prefer the guava one.
This allows us to remove two dependencies on commons-lang3 (in modules
that already depended on guava).

Use guava's Throwable over commons-lang3's ExceptionUtils

---

projects/batfish-common-protocol/BUILD
projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishException.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserErrorListener.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/flatvyos/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/iptables/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/mrv/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/eos/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/ios/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/nxos/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/vyos/BUILD

This PR is a bit more interesting than other Bazel PRs.
Basically, establish an as-small-as-possible set of files in `batfish-common-protocol` that a parser can be compiled against. This way, we don't have to recompile all parsers any time that anything at all in the data model changes.
Trying to do this type of work highlights where encapsulation and separation of functions are useful. It seems strange that we can't build a parser without depending on `AnswerSummary`. Also, this would have been completely impossible had I not broken one dependence on `CommonUtil`, since that common utility class depends on absolutely everything else in the data model FWICT.

batfish-common-protocol: establish parser_common to reduce rebuilding parsers

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java

* static functions can be static
* tighten access from public to package or private
* unnecessary printf concerted to print

BfCoordWorkHelper: remove all warnings

---

projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java
tests/basic/commands

use specialization in reachability queries by default

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/ITracerouteEngine.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/z3/NodJobAclTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java

- move cached ForwardingAnalysis objects out of Batfish and into their
corresponding DataPlane. This reduces the opportunity for bugs caused
by using the wrong key to look up the ForwardingAnalysis (thus getting
the wrong one).
- Made IncrementalDataPlane immutable (except for transient fields) and 
added a builder. This required some small changes to IncrementalDataPlaneEngine.
- Now that IncrementalDataPlane is immutable, we can cache the results
of its expensive non-getter methods. This is also how we cache 
ForwardingAnalysis (so it is still computed lazily).
- Use CommonUtil.toImmutable(Sorted)Map when possible, for improved
readability.

move ForwardingAnalysis to DataPlane, make IncrementalDataPlane immutable

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/IncrementalBdpAnswerElement.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
tests/basic/genDp-delta.ref
tests/basic/genDp-env.ref
tests/basic/genDp.ref

Some further cleanup of dataplane classes:
- Remove unused/unimplemented methods & fields from dataplane and corresponding answer element
- DP engine now returns DataPlaneResult
- Add `Warnings` to dataplane answer element. Currently unused, groundwork for future use.

Cleanup dataplane interfaces a bit more

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java

- modernize `equals` and `hashCode` (and make sure they include all fields)
- make `prettyPrint` and `toString` include all fields, omit fields with default values

clean up Flow

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/config-filesystem-format

Add support for `filesystem` format PAN configs.
Previously, only `show` format configs were supported, the kind seen when issuing `show` command on the device CLI.

Add parsing support for alternate PAN config format

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4

* Cleanup formatting in PAN parser
* Remove redundant, unused rule
* Update `null_rest_of_line` to not consume newline token

Cleanup formatting in PAN parser

---

projects/allinone/src/test/java/org/batfish/allinone/SpecifiersReachabilityQuestionTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/FlowMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/FlowMatchersImpl.java

- Null annotations on all object fields.
- Change builder field types to match corresponding Flow fields.
- Maintain and check the invariant that exactly 1 of _ingressVrf and
_ingressInterface is non-null.
- Use Object.equals instead of Objects.equals for @Nonnull fields.
- Include _ingressInterface in compareTo
- Remove setter for final field _ingressInterface
The change to compareTo broke a unit test (because more flows are now
considered distinct), so fixed that too.

More Flow fixes.

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

Fixes a duplicate warning: one under ipv4-only, one under v4/v6 both.

Cisco: proper ref tracking of NAT ACLs

---

projects/batfish/src/main/java/org/batfish/representation/cisco/Tunnel.java

* No longer reference counted.
* Fields private.
* Add missing getter.

Cisco: cleanup Tunnel

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclLineMatchExprTest.java

Can't use `thenComparing(AclLineMatchExpr::getDescription)` because `_description` is Nullable and `thenComparing()` throws exceptions for null arguments.

Avoid error in compareTo if Nullable field is null

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

Rather than passing lots of (redundant) paths around, pass a single `storageBase` argument and then also pass other keys (`containerName`).
Other paths, which are fully constructable from things like `storageBase`, `containerName`, `testrigName`, and `questionName`, for example, are constructed from those components.
Suggestions for simplification would be great.

Simplify Coordinator/Batfish communication

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java
projects/question/src/main/java/org/batfish/question/routes/RoutesQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/routes/MockRib.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesQuestionTest.java

Begin work addressing #1684 by creating a new routes question that:
- Uses table answer format
- Supports VRF filtering
- Only extracts relevant data based on the type of RIB being examined.
So far only mainRIB is supported, mimicking the existing behavior, more in a separate PR.

New routes question, first pass

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
test_rigs/unit-tests/configs/cisco_interface
test_rigs/unit-tests/configs/cisco_misc
test_rigs/unit-tests/configs/cisco_ospf
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

Most of these constructs we don't parse. Interesting ones:
* support OSPF shutdown. Per recent discussion, we should probably redo the data model around this, but I'm assuming that's for future work.
* ref-tracking for redistribute eigrp route-maps.

A whole bunch of Cisco parsing fixes

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

We only care about incoming routes so reduce number of queues kept in memory.
Assuming `node1` is the source/tail of the edge, hence identifies remoteVr

Reduce number of ISIS queues

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsoAddress.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IsisRouteTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java

Commits separate/self-contained
- Add systemId to IsisRoute
- Fix route propagation, L1 routes now get advertised to L2 on L1-L2 routers
- Add extra negative assertions to test.

Isis route float up

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/IntersectionLocationSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/UnionLocationSpecifier.java
projects/batfish/src/test/java/org/batfish/specifier/LocationSpecifierTest.java

Added missing equals and hashCode implementations needed to test location specifier factories (will be used in a separate PR).

new equals, hashCode implementations for location specifiers

---

projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java
projects/batfish/src/test/java/org/batfish/job/FlattenVendorConfigurationJobTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-brackets
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-brackets-flattened
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nested-config-brackets
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nested-config-brackets-flattened

Previously, after a bracketed list was flattened, lines following the list were also duplicated (once per bracketed list item).
This PR fixes that behavior, by clearing the list of bracketed words once they have been flattened.

Fix Juniper flattener to work with bracketed lists

---

projects/batfish/BUILD

For batfish project, add dependency on common_testlib, as that's where route matchers reside.

Bazel: Add dependency to access matchers

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleLocationSpecifierFactoryTest.java

A LocationSpecifierFactory that parses a specification from a string. The goals are to be suitable for use on the command line (so a fairly terse format), while also being expressive enough to express any subset of locations. For example, you can simply enumerate a list of locations.

flexible location specifier factory

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java

- Use hostname for ordering
- Still not overriding hashcode or equals: deep versions would be incredibly expensive, and we never node as a map key or in a set.

ibdp Node: do not inherit from comparable structure

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleIpSpaceSpecifierFactoryTest.java

Simple IpSpaceSpecifierFactory that delegates to ConstantIpWildcardSetIpSpaceSpecifierFactory except when input is null, in which case it defaults to InferFromLocation.

New FlexibleIpSpaceSpecifierFactory

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSession.java

Currently no need for it. 
Eventually this class will be re-written anyway.

Remove comparable from BgpSession

---

projects/coordinator/src/main/java/org/batfish/coordinator/ApiKeyAuthenticationFilter.java
projects/coordinator/src/main/java/org/batfish/coordinator/CrossDomainFilter.java
projects/coordinator/src/main/java/org/batfish/coordinator/VersionCompatibilityFilter.java
projects/coordinator/src/test/java/org/batfish/coordinator/CrossDomainFilterTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/VersionCompatibilityFilterTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java

These filters should run unconditionally before any resource expansion
happens.

Jax-RS: add @PreMatching to filters

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/VerboseOspfEdge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighbor.java

instead of using the compareTo implementation inherited from
ComparableStructure

compare OspfNeighbor IpLinks directly

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/CaseInsensitiveRegexLocationSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NodeRoleRegexLocationSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/TypedLocationSpecifierFactory.java

* Don't let children override functions in intermediate abstract
classes.
* Make private variables that can be.

specifiers: tighten signatures

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObject.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-object-group-network
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/network-object
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

Add Cisco ASA `network object` datamodel support and ref tracking.  Also fixed existing ref tracking using `network object-group` structure type instead of `network object`.

Add support for ASA network objects

---

projects/batfish-common-protocol/BUILD

Missed this one when I simplified parser deps

bazel: fix recovery grammar dependency

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/IsakmpPolicy.java
projects/batfish/src/main/java/org/batfish/representation/juniper/IkeProposal.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ike-proposal
tests/parsing-tests/unit-tests-nodes.ref

- this will help in minimizing changes if data-model changes(only toVendorIndependent() method will change)
- makes the code cleaner and consistent with the rest of vendor dependent data-models
- Also added tests for Juniper to make sure nothing broke
- Default value for Juniper ike proposal's lifetime added([link](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/security-edit-lifetime-seconds-ike.html))

Not using V.I. datamodel for IKE proposal in V.D. representations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java

This is really just an internal method, it's always equivalent to getVrf(default).

NodePropertySpecifier: remove default-vrf

---

.travis/build.sh
.travis/common.sh
.travis/install.sh
projects/allinone/allinone
projects/batfish-client/batfish-client
projects/batfish/batfish
projects/coordinator/coordinator
tools/common.sh
tools/completion-allinone.sh
tools/completion-batfish-client.sh
tools/completion-batfish.sh
tools/completion-coordinator.sh
tools/package_rpm.sh
tools/package_ubuntu.sh

* simple variables ($foo to ${foo})
* missing shebang lines
* path fixups when bash scripts reference other scripts

IntelliJ: automated bash fixes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkConfigurations.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkConfigurationsTest.java

*Purpose*:
Have a helper wrapper around `Map<String,Configuration>` that extracts desired objects from the configuration tree based on a key and simplifies a sequential null checks we do in a bunch of places.
First use case (coming soon): pass this around in the dataplane code and remove dependency on `Configuration` from `Node` class.
fyi @arifogel @anothermattbrown

Add network configurations helper

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4

We usually do not define non-mode-specific tokens in a mode. Assuming this is not intentional, or else there would be a comment.

FlatJuniperParser: move NO_ADVERTISE out of lexer mode

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/WellKnownCommunity.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java

* Use the standard names, not the cisco names
* add link to the reference defining the constants
* use constants, not enums where we always then do `.longValue()`
Main changes to scrutinize:
* gshut had the wrong number before (verify?)

Batfish: update and flesh out definition of BGP well-known communities

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleLocationSpecifierFactoryTest.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteQuestion.java
tests/basic/commands

- traceroute2: source is now traceStart
- FlexibleLocationSpecifierFactory:
- LocationType "interface" is now "source"
- LocationType "interfaceLink" is now "intermediate"

Renaming in TracerouteQuestion and FlexibleLocationSpecifierFactory

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_vsys.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/log-settings-syslog
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/vsys-zones

Add support for PAN virtual systems (`vsys`)
* `vsys` shares some syntax with `shared` set commands, so those have been grouped into a `common` rule in `shared` grammar
* `syslog server` and `zones` moved from top-level of PAN configuration to `vsys`

Add support for PAN virtual system

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionInfo.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java

If the local BGP configuration has no remote AS specified, flag it as a separate kind of bug.

Add BGP session status indicating remote AS is not configured

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-type-internal
tests/parsing-tests/unit-tests-nodes.ref

I accidentally broke this in #1812, fixing + test.

Juniper: fix handling of "bgp group type internal"

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

*Problem*:
If a stub area contains multiple ABRs, all ABRs would inject default route to other ABRs and they would be installed.
*Fix*: 
Check if both neighbors are ABRs before allowing default route propagation.

OSPF: do not propagate default route to other ABRs within an area

---

projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java

*Issue*:
When traceroute is given `ingressNode` not in the network, NPE occurs.
*Fix*:
Still crash but at least with custom exception and a meaningful error message (since currently there is no way to "gracefully" return custom errors).

Traceroute: crash with a meaningful error message on missing ingressNode

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NodeNameRegexConnectedHostsIpSpaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NodeNameRegexConnectedHostsIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpSpaceSpecifierFactoryTest.java
projects/batfish/src/test/java/org/batfish/specifier/IpSpaceSpecifierTest.java

A new IpSpace specifier for sane mode. The input is a regex, which matches on node names. Specifiers the union of host subnets (/29 or shorter prefixes) on those nodes, excluding the IPs owned by the nodes themselves.

new IpSpace specifier by node host subnets

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-interface-point-to-point

Currently we were parsing but not extracting this property. 
See https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/interface-type-edit-protocols-ospf.html
*Note*: this does not include additional parsing/extraction support for `nbma | p2mp | p2mp-over-lan`

Juniper: extract OSPF point to point interface type

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

*Issue*:
ISIS routes have next-hop IPs pointing at their own node.
*Fix*:
During propagation flip node1 and node2.

ISIS: fix nexthop

---

projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis

*Issue*:
When converting to VI configs, no interfaces would come up unless an ISO address was explicitly configured.
Once fixes, **all** the inferfaces would be labeled ISIS because we were doing a null check on settings instead of `.getEnabled()`.
*Fix*:
- Fix if statement in `toIsisInterfaceSettings`
- Add annotations for clarity
- Expand existing test with negative example

Juniper Is-is: fix interface setting conversion

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisProcessMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisProcessMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis-iso-non-loopback
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis-no-iso

As specified [here](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/isis-network-configuring.html#id-10095177)
loopback is preferred, but not required.

Juniper ISIS: ISO address can be configured on any interface

---

projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityAnswererUtilsTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/CircularReferenceException.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/UndefinedReferenceException.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceDereferencer.java
projects/question/src/main/java/org/batfish/question/aclreachability2/AclReachabilityAnswererUtils.java
projects/question/src/main/java/org/batfish/question/aclreachability2/HeaderSpaceSanitizer.java
projects/question/src/main/java/org/batfish/question/aclreachability2/TypeMatchExprsCollector.java

Fixes an issue where references to ACLs, IpSpaces, and interfaces could go unnoticed during ACL sanitization if they were hidden inside And, Or, or Not match expressions.

Sanitize references in And, Not, and Or expressions

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDOps.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/BDDOpsTest.java

Factor out variants of and and or that return null when all inputs are null. The idea is that null means "unconstrained", which is different than the identity elements true and false.

New BDDOps methods andNull, orNull

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

While it doesn't make sense for all route types, the field is so common for learned routes that decided to just include it for all routes in the main RIB.

Routes2: Add metric column to all main RIB routes

---

projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

The number of actions in a delta can vary based on route ordering which is not deterministic (simple `Set`). 
Delete flaky assertions; really important assertions are still preserved (`contains`, etc.)

Delete flaky assertions

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/UnzipUtility.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/UnzipUtilityTest.java

Update unzip utility to create parent directories when unzipping files.
Fixes #1864

Handle zips missing directory entries

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java
projects/batfish/src/main/java/org/batfish/z3/IpSpaceIpAccessListSpecializer.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/z3/IpAccessListSpecializerTest.java
projects/batfish/src/test/java/org/batfish/z3/IpSpaceIpAccessListSpecializerTest.java

Move everything specific to how we are representing the header space
we're specializing the ACL to into a subclass.

factor out IpAccessListSpecializer as an abstract class

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java

PAN structure references may implicitly span multiple namespaces.
For example:  consider the config line:`set vsys vsys1 service-group GROUP members SERVICE1`.
Here, `GROUP` is an object inside the logical firewall `vsys1`, and it is made-up of a reference to `SERVICE1`.
`SERVICE1` may refer to a `service` or `service-group` defined in either `vsys1` or in the `shared` namespace.
This PR sets up infrastructure to handle marking these abstract structure types across multiple namespaces, and applies this to `service` and `service-group` marking.

Added support for marking structures in multiple namespaces

---

projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java
projects/batfish/src/test/java/org/batfish/z3/IpAccessListSpecializerTest.java

After specializing a HeaderSpace, check for empty disjunctions of
required header field values (i.e. a field was required to be equal to
one of some number of choices, but specialization ruled out all of them)

improve simplification and clean up IpAccessListSpecializer

---

projects/batfish/BUILD
projects/question/BUILD

Add/remove dependencies as needed after changes to question tests, bdd work, and new topology tests.
*Note*: Not sure why topology tests use empty batches (perhaps as a "log statement"?) so had to suppress a couple of warnings.

Fix bazel build

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/CommunityListTest.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/StandardCommunityList.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref
tests/roles/nsRoleConsistency.ref

* add JSON annotations for `_invertMatch`
* make `_invertMatch` final and explicit (all params in constructor, or none) -- hodgepodge of both is least useful
* no longer ComparableStructure.

CommunityList: minor cleanup

---

projects/pom.xml

javadoc: don't warn on missing tags

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java

Replaces `container` with `network` and `testrig` with `snapshot` in Javadocs, including in names of parameters. Skipped deprecated methods and methods that still need to be changed more fundamentally.

Update terminology in WorkMgrService javadocs

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java

Example interaction with java client:
```
batfish> list-containers
WARNING: Command list-containers has been deprecated and may be removed. The term "container" has been replaced with "network". Use list-networks instead.
Networks: [LHR, aclContainer]
batfish> init-container abc
WARNING: Command init-container has been deprecated and may be removed. The term "container" has been replaced with "network". Use init-network instead.
Active network is set
batfish> list-networks
Networks: [LHR, abc_81777451-945e-432a-8c87-a12c0eef999b, aclContainer]
batfish> del-container abc_81777451-945e-432a-8c87-a12c0eef999b
WARNING: Command del-container has been deprecated and may be removed. The term "container" has been replaced with "network". Use del-network instead.
Result of deleting network: true …
```

Deprecate "container" in java client

---

tests/questions/experimental/commands
tests/questions/stable/commands

Template validation does not require testrigs to be initialized.

questions: remove unnecessary testrig initialization

---

projects/batfish/src/main/java/org/batfish/grammar/flatvyos/FlatVyosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/EigrpProcess.java
projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesTable.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/StaticRoute.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/SyslogServer.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/representation/vyos/BgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/vyos/BgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/vyos/EspGroup.java
projects/batfish/src/main/java/org/batfish/representation/vyos/EspProposal.java
projects/batfish/src/main/java/org/batfish/representation/vyos/IkeGroup.java
projects/batfish/src/main/java/org/batfish/representation/vyos/IkeProposal.java
projects/batfish/src/main/java/org/batfish/representation/vyos/Interface.java
projects/batfish/src/main/java/org/batfish/representation/vyos/IpsecPeer.java
projects/batfish/src/main/java/org/batfish/representation/vyos/PrefixList.java
projects/batfish/src/main/java/org/batfish/representation/vyos/PrefixListRule.java
projects/batfish/src/main/java/org/batfish/representation/vyos/RouteMap.java
projects/batfish/src/main/java/org/batfish/representation/vyos/RouteMapRule.java

Only one actual change from a Set to a Map where we were using the ComparableStructure-backed hack.

ComparableStructure: finish removing from vendor-specific representations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPathAccessList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AuthenticationKey.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AuthenticationKeyChain.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkeGateway.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkePolicy.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/DocsisPolicyRule.java

Most were easy.
Did not add equals, hashCode, or toString to any class, except as needed to make tests pass or compiler warnings succeed.
These two were affected by the latter (and have commits with good messages explaining why).
* Configuration
* AsPathAccessList
Thoughts?

Some beginners work removing ComparableStructure from datamodel

---

projects/question/src/main/java/org/batfish/question/aclreachability2/AclReachability2Answerer.java

- relax question parameter so client can pass alternate question type

make AclReachabilty2 metadata generation accessible to clients

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationIpSpaceSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpSpaceSpecifierFactoryTest.java
projects/batfish/src/test/java/org/batfish/specifier/IpSpaceSpecifierTest.java

Given a LocationSpecifier, it infers an IpSpace for each location, and
then unions them into a single IpSpace. This is useful for specifying
destination IpSpaces by location. In the future this will probably
replace InferFromLocationIpSpaceSpecifier so we can simplify the
IpSpaceSpecifier API. At that point, we will no longer union all the
spaces into a single IpSpace, but instead construct a separate
assignment entry for each.

new IpSpaceSpecifier that specifies an IpSpace by locations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

*Issue*:
In some cases when constructing FIBs we need a less specific route to match (e.g., in case of non-forwarding routes). Currently that's not possible.
*Fix*:
Add ability to constrain the max number of bits matched when long `longestPrefixMatch`

Allow length constraints on longest prefix match in a RIB

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLinesAnswerElement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLinesAnswerElementInterface.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/z3/AclIdentifier.java
projects/batfish/src/main/java/org/batfish/z3/AclLine.java
projects/batfish/src/main/java/org/batfish/z3/AclReachabilityQuerySynthesizer.java
projects/batfish/src/test/java/org/batfish/z3/AclLineIndependentSatisfiabilityTest.java

- Refactored back to the version where all the jobs for each phase are submitted in one big batch
- needed for parallelization, until Batfish can run one z3 job with low overhead
- Changed AclReachabilityQuerySynthesizer to generate 1 query per job
- Changed the way AclSpecs provides a representative hostname and ACL name, because I was concerned that it might have been possible to conflate the previous "representative" aclName with `aclSpec.acl.getAclName()`.

Better parallelization, 1 query per unreachable line job

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
tests/parsing-tests/unit-tests.ref

The redflag was generating false positives.
After some digging around looks like it's perfectly valid to have delay defined even if its not used, L3 protocols can choose to use it, but don't have to ([docs](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/5_x/nx-os/interfaces/configuration/guide/if_cli/if_basic.html#74566))

Delete misleading EIGRP redflag

---

projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java

We recently started using `null` as the default for these specifiers, and this PR adds `@Nullable` annotations to the getters and setters.
Also removed a redundant initialization of `_destinationIpSpaceSpecifier` and make it final.

Fix nullness annotations and finality

---

projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
projects/coordinator/src/test/java/org/batfish/coordinator/MainTest.java

- last template in the list of `templatedirs` will be retained in the map of question templates

Not throwing exception on duplicate question template instance names

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java

* delete a bunch of unused code from Warnings
* remove the ability to make Warnings throw when logging. We've changed philosophy fundamentally, and now believe that logging and making progress is a significantly better strategy.

Warnings remove

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/ICoordinator.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRoleDimensionBeanTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRoleDimensionResourceTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRolesDataBeanTest.java

Continuation of the migration from container/testrig to network/snapshot terminology.
* Added `uploadSnapshot` and deprecated `uploadTestrig` REST API
* Update `ICoordinator` interface to use new terminology

Deprecate upload testrig and add upload snapshot API

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/question/src/main/java/org/batfish/question/BgpLoopbacksQuestionPlugin.java

- Remove comparable structure
- Better javadoc in places
- Had to keep overriding `equals` and `hashcode` in a weird way for compatibility (deferring proper fix for later).

Cleanup RoutingPolicy

---

projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java
projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
tests/ui-focused/commands
tests/ui-focused/del-snapshot.ref
tests/ui-focused/del-testrig.ref
tests/ui-focused/list-snapshots1.ref

Deprecates "testrig" terminology in Java client. Modeled after #1919. Also changes some internal terminology: "testrigdir" and "testrigid" became "snapshotdir" and "snapshotid". I don't think these are surfaced at all, so don't think changing them will affect existing clients. (A quick check with the web UI didn't trigger anything unusual.)

Deprecate & replace testrig-related commands in client

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDPacket.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/BDDPacketTest.java

In the near future we will need to allow `BDDPacket` clients to reserve bits for auxiliary variables (e.g. for non-header ACL conditions). Factored out two allocation methods (for single-bit and `BDDInteger` variables), and rewrote the constructor to use those.
cc @corinaminer

factor BDD variable allocation into public methods

---

projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Fib.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureEquivalenceSets.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/FiltersSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacesSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfPropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/AltFlexibleLocationSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContext.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PrefixTracer.java
projects/batfish/src/main/java/org/batfish/symbolic/CommunityVar.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java
projects/batfish/src/main/java/org/batfish/z3/IpSpaceIpSpaceSpecializer.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInput.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/visitors/SimplifierTest.java
projects/question/src/main/java/org/batfish/question/filtertable/Filter.java

Replaced all the non-tag instances of `<` with `&lt;` and of `>` with `&gt;`. Also mostly standardized arrows to use one n-dash.

Fix angle brackets in javadocs

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/autonomous-system-loops
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/autonomous-system-loops-routing-instance

Allowas-in can also be expressed as `loops` [Docs](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/loops-edit-routing-options-autonomous-system.html) so write extraction code for that.
*Note*: this does not implement the logic for how many times local as can appear in as path, that's still unhandled across all vendors.
*Side effect*: alphabetized some more tests in FlatJuniperGrammarTest, only `testAutonomousSystemLoops` is new.
CC @anothermattbrown if you are curious about the fix.

Juniper: extract autonomous-system loops

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

The issue: Many API calls that we don't want to deprecate take a parameter whose key contains "testrig" or "container" -- for example, `getAnswer` requires network and snapshot names with keys `SVC_KEY_CONTAINER_NAME` and `SVC_KEY_TESTRIG_NAME`. Meanwhile, we have some new API calls that require new versions of those keys; for example `delSnapshot`, intended to replace `delTestrig`, requires network and snapshot names with new keys `SVC_KEY_NETWORK_NAME` and `SVC_KEY_SNAPSHOT_NAME`. We don't want clients to have to know multiple versions of these keys, but with this setup they would be forced to do so if they wanted to stop using deprecated API calls.
The solution: API calls that use these keys now take one parameter for each version; e.g. one parameter with key `SVC_KEY_CONTAINER_NAME` …

Allow old or new SVC_KEYs in WorkMgrService

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDDTest.java

Fixed a typo: we used icmpTypes instead of notIcmpTypes, which meant
that any headerspace constraint that constrained icmpTypes would be
encoded as false.

AclLineMatchExprToBDD: fix BDD encoding of notIcmpTypes headerspace constraint

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

No test. The change occurs in the middle of a huge method `VirtualRoute.computeBgpAssignmentsToOutside`, which should be refactored so we can test it. Until then, it's unclear how to test this change.

don't export BGP routes with no-advertise community

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

The javadoc for `uploadQuestion()` was claiming the new question would be run in the given snapshot, but this was not being done, and the snapshot name was ignored outside of logging it.

Remove unused snapshot param from uploadQuestion

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/UnimplementedAccessListServiceSpecifier.java
tests/parsing-tests/unit-tests-nodes.ref

Cisco: treat unimplemented ACL match clauses as unmatchable

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Zone.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java

The only things populated in the data model for Zone are the names of the various
things. Handling both optionally at runtime, rather than just in the initial build
of the object, seems crazy.
Also add nullness annotations and fix a few bugs that exposed.
Fixes #2025

Zone: remove weird indirection, just store names

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDPacket.java

Enable automatic variable reordering. This seems to have a small
performance benefit (< 10%), but doesn't seem to hurt.
Remove maximum node table increase size. The factory dynamically grows
the node table. If we limit its growth, we end up collecting more often
for large jobs. Removing the limit thus reduces the frequence of GCs,
and can save significant time for large jobs. For smaller jobs, this
doesn't make a difference as we wouldn't reach the default limit.
Change the default variable ordering by moving the ip protocol to after the IP
addresses and ports. This provides significant speedup for dataplane
analysis. It's possible that the old order is better for control plane,
so we may want to provide different orderings. For now, this seems to
be the better ordering.

BDD parameter tuning

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfArea.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

Makes these values explicit in the datamodel, since Juniper and Cisco behave differently.  Update the logic that injects default routes for OSPF areas to check these values.

add injectDefaultRoute and metricOfDefaultRoute properties to OspfArea

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpSpaceSpecifierFactoryTest.java

We're not ready to remove this yet. This is used to specify an `IpSpace` using locations specified by `FlexibleLocationSpecifierFactory`. Specifically useful for destination IP. The recent changes to `FlexibleLocationSpecifierFactory` affect how this is used, but it still works.

restore FlexibleLocationIpSpaceSpecifierFactory

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableDiffTest.java

I had this behavior earlier in which, if we had multiple instances of a key in the table, only one will be retained. Changed that to include all instances.

keep all instances of the same key

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-virtual-router

Context:
Interfaces on PAN devices must explicitly be placed in a virtual-router (vrf), otherwise they are functionally inactive/shutdown.
Change:
Now, in the PAN `toVendorIndependentConfiguration` method:
* Where applicable, simply set an interface's vrf to the one specified in the config
* Add all interfaces not associated with a vrf to a constructed `null` vrf
* Shutdown these orphaned interfaces so they do not inadvertently tx/rx traffic

Fix PAN Vrf assignment for interfaces

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleInferFromLocationIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleUniverseIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleInferFromLocationIpSpaceSpecifierFactoryTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpSpaceSpecifierFactoryTest.java
projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteQuestion.java
tests/questions/experimental/traceroute.ref

Factored out an abstract superclass from FlexibleIpSpaceSpecifierFactory
so we can have two factories that share the parsing logic but have
different defaults.

New flexible IpSpaceSpecifierFactory with universe as the default

---

projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterAnswerer.java

The root cause here (I believe) is the fact that PAN does not properly populate ipSpaces during conversion; until then reachfilter won't work properly.
This hotfix prevents the crash and returns an empty answer; The error message is (still) written to disk via `catch (Throwable t)` block.

Hotfix NPE in reachfilter

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java

When converting a NetworkObjectGroup to an IpSpace, we should interpret
the an empty group as EmptyIpSpace. Previously, an empty group is
converted to null, which can cause NPEs later.

Interpret empty NetworkObjectGroup as EmptyIpSpace

---

questions/experimental/reachfilter.json
tests/questions/experimental/reachfilter.ref

No need to force specification of src/dst IPs

Reachfilter: make headerspace specifiers optional

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDPacket.java

Experiments show this to be significantly better than LSB-first (2x-15x) for both control plane and data plane.

Order variables for IP addresses MSB-first.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/ColumnMetadataTest.java

Support additional types of characters in the metada required for space and characters such as ~ which is required to support configurations for named structures.

Support additional types of characters in the metada.

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ExtendedCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CommonUtilTest.java

Disable checks for whether the community is 16-bit, cleanup ExtendedCommunity class a tiny bit.

Fix crash with converting extended communities

---

projects/allinone/src/test/java/org/batfish/question/multipath/MultipathConsistencyQuestionTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyReferenceTest.java

JUnit test classes are supposed to end with `Test` -- if not, they are not detected
by several test finders (including bazel). Fix a few, and add comments.

JUnit: fix names of test classes

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/StandardAccessList.java
projects/batfish/src/main/java/org/batfish/representation/cisco/StandardIpv6AccessList.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-in-routemap

*Problem*: We did this dance of converting standard ACLs to extended ACLs and then to route filter lists, which incorrectly captures how standard ACLs are used in route maps.
In reality route prefixes are matched against source wildcards in standard acls.
*Fix*: convert standard and extended acls to routelists separately. 
Side effects: tweaked some helper functions that relied only on acl name.

Cisco: Fix conversion of standard ACLs to route filter lists

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/HeaderSpaceToBDD.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/HeaderSpaceToBDDTest.java

If HeaderSpace's negate field is set, we should negate the entire BDD constructed for it.

HeaderSpaceToBDD: handle negate

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

There is a lot of confusion between who is receiver/sender in our OSPF code (we both missed this originally)
There is a more general fix that needs to be applied here, with better design patterns and terminology; but for now let's just unblock correct functionality.

OSPF: fix default route propagation for stub areas

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/service
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/zones

Palo Alto Networks devices allow spaces in the names for many structures, e.g.:
```
set service "service name with spaces" protocol tcp
set service-group "service group name with spaces" members "service name with spaces"
```
This PR updates configuration building for PAN to extract struct names from quotes where applicable.

Handle PAN structure names in quotes

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

I had a configuration parse error: 
> Caused by: java.lang.NumberFormatException: For input string: "4202002800"
Core of the issue: Private 32-bit ASNs (rfc6996, range 4200000000 - 4294967294) are outside of the range of an Int (upper range 2,147,483,647).
Should use a Long to store these.

Updating peerAS from Int to Long for 32bit private ASNs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AnswerMetadata.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AnswerMetadataUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ColumnAggregationResult.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/GetAnalysisAnswerMetricsAnswer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Metrics.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AnswerMetadataUtilTest.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

Answer metadata for table answers is now stored separately in `answer-metadata.json` file along `answer.json`.
Breaking change:
- no longer able to request aggregations via coordinator `getAnalysisAnswersMetrics`
- instead, pass '-aggregations ...' to batfish work item args when analysis is run

Separate answer metadata from answers

---

questions/experimental/interfaceMtu.json
tests/questions/experimental/interfaceMtu.ref

Looks like this parameter type got skipped in #2140.

Interface MTU param type to nodeSpec

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AclLines2Rows.java
projects/question/src/main/java/org/batfish/question/aclreachability2/AclReachability2Question.java
questions/experimental/aclReachability.json
tests/basic/aclReachability2.ref
tests/questions/experimental/aclReachability.ref
tests/questions/experimental/commands

- changed question params to `filters` and `nodes`
- changed type of `nodes` to `nodeSpec`
- updated template descriptions for question and parameters
- changed column names to Uppercase_Underscore_Separated_Format
- changed name returned by `getName()` to camel case

Make ACL reachability template consistent

---

skylark/ref_tests.bzl

Run only one ref test at a time.
https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags

Bazel: don't kill the user's machine on ref tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Header6Space.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpProtocol.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlagsMatchConditions.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TcpFlagsMatchConditionsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TcpFlagsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/ExtendedIpv6AccessListLine.java
projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromTcpFlags.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/HeaderSpaceToBDD.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/IpAccessListToBoolExpr.java
projects/batfish/src/main/java/org/batfish/z3/BDDIpAccessListSpecializer.java
projects/batfish/src/main/java/org/batfish/z3/expr/HeaderSpaceMatchExpr.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/HeaderSpaceToBDDTest.java
projects/batfish/src/test/java/org/batfish/z3/BDDIpAccessListSpecializerTest.java
projects/batfish/src/test/java/org/batfish/z3/IpAccessListSpecializerTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/visitors/BoolExprTransformerTest.java
tests/aws/nodes-example-aws.ref
tests/parsing-tests/unit-tests-nodes.ref

This begins the bottom-up work of cleaner data structures for Flow/headerspace-related data structures.

 Separate TCP flags from TCP match conditions, make both immutable

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java

This property is in deletion at #2176, this is a user-facing shortcut
while that one is in progress.

InterfaceProperty: skip inbound-filter-name altogether

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclLineMatchExprsTest.java

Smart constructors of AndMatchExpr and OrMatchExpr that do constant-time simplifications.

Smart And/Or AclLineMatchExpr constructors

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDAcl.java

Make the computeACL method only used during initialization static (so its dependencies are explicit and guaranteed to have already been initialized); remove support for `null` ACLs.

Clean up BDDAcl

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceTest.java

Fix a bug in union: union of only EmptyIpSpaces is EmptyIpSpace. Previously, we removed those and returned null (interpreted as unconstrained/universe).
Also simplify output of intersection when the intersection has only 1 element or contains EmptyIpSpace, short-circuit.

detect empty unions of IpSpace

---

WORKSPACE
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/pom.xml
projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
skylark/ref_tests.bzl

Minor fixups to match beta Guava APIs, and a new type-inference-caught bugfix enabled by the update.

Upgrade Guava to latest version

---

projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresAnswerer.java
projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresQuestion.java
questions/experimental/namedStructures.json
tests/questions/experimental/commands
tests/questions/experimental/namedStructures.ref

- Replace parameters "nodeRegex" and "propertySpec" with "nodes" and "properties"
- Capitalize node column name
- Standardize parameter descriptions
- Camel case java question name

Update NamedStructures with standardized parameters

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowTrace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowTraceHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java

This is bad design, but we shouldn't crash.
Related changes:
* Since we allow multiple different next hops on the same interface, we now need to
no longer compare FlowTraceHops identically if they have the same edge. We need to
implement a correct comparator.
* Refactor equals methods / nullable annotations in other classes I thought the bug was
in before.
* Add a missing toString.

Traceroute: handle multiple nextHopIps on the same interface

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/pom.xml
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/test/java/org/batfish/config/SettingsTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishStorageTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/main/FileBasedStorageTest.java

- Conduct all worker storage operations through `StorageProvider`
- Move all worker file access to `FileBasedStorage`
- Clean up heinous question path hackery
Follow-on work: make Coordinator use new StorageProvider for storage operations

BatfishStorage refactor and overhaul

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java

Crash is not happening, but was present in every other variant that I saw and
I was getting IDE warnings for it.
cc @mkremerbbn fyi, but nothing needed.

CiscoControlPlaneExtractor: null guard

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPropertySpecifier.java

* Collapse active and passive neighbors
* Rename multipath equivalence mode
* Remove origination space
* Remove generated routes
* Suppress cluster_id column (for the time being)

Simplify BGP properties:

---

projects/allinone/src/test/java/org/batfish/question/CompareSameNameTest.java
projects/allinone/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationLoginTest.java
projects/allinone/src/test/java/org/batfish/question/aclreachability/AclReachabilityTest.java
projects/allinone/src/test/java/org/batfish/question/multipath/MultipathConsistencyTest.java
projects/allinone/src/test/java/org/batfish/question/reachfilter/ReachFilterDifferentialTest.java
projects/allinone/src/test/java/org/batfish/question/reachfilter/ReachFilterTest.java
projects/allinone/src/test/java/org/batfish/question/reducedreachability/ReducedReachabilityTest.java
projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityTest.java
projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersTest.java
projects/allinone/src/test/java/org/batfish/question/testfilters/TestFiltersTest.java
projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteTest.java
projects/batfish/src/test/java/org/batfish/dataplane/PathDiffTest.java
projects/question/src/test/java/org/batfish/question/NeighborsAnswerElementTest.java
projects/question/src/test/java/org/batfish/question/aclreachability/AclReachabilityAnswererTest.java
projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererTest.java

* Unit tests should not be here, so moved a bunch of those next to the code they test
* Test names should make sense and be unique. Specifically, unified on
`<QuestionName>Test` for e2e tests and `<ClassName>Test` for unit tests of `<ClassName>`.
`<ClassName>` is typically `FooQuestion`, `FooAnswer`, whereas
`<QuestionName>` is `Foo`.
* Add trivial javadocs.

Allinone: e2e test cleanup

---

projects/allinone/BUILD
skylark/junit.bzl

Since these are fairly large, it's nice to make them independent and parallelizable.
1. Rewrite JUnit rule to allow non-Test files in the set of files to compile.
2. Factor each test into its own test case.
After #2227 , this only touches .bzl and BUILD files.

bazel: refactor allinone tests

---

projects/batfish/src/main/java/org/batfish/z3/BDDIpAccessListSpecializer.java
projects/batfish/src/main/java/org/batfish/z3/BDDIpSpaceSpecializer.java
projects/batfish/src/test/java/org/batfish/z3/BDDIpAccessListSpecializerTest.java
projects/batfish/src/test/java/org/batfish/z3/BDDIpSpaceSpecializerTest.java

Ordinarily specializers simplify constraints that are always true to UniverseIpSpace (IpSpaceSpecializer) or TrueExpr (IpAccessListSpecializer). 
For headerspace explanation, we want to keep those constraints unmodified. This change adds a flag to the BDD specializers to indicate whether to simplify them or not.

BDD specializers: flag whether to simplify to True/Universe

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/normalize/Negate.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/normalize/NegateTest.java

Negate an AclLineMatchExpr, applying deMorgan to AndMatchExpr and OrMatchExpr (at most once -- uses NotMatchExpr instead of recursion to negate when applying deMorgan). Everything else is wrapped in a NotMatchExpr (including MatchHeaderSpace, which could also be negated using the flag in HeaderSpace), and double-negation is eliminated.

negate AclMatchExprs

---

projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

- interface column already has this information, rename it `(Remote_)Node:(Remote_)Interface`

Drop node column from edges question to reduce redundancy

---

networks/example-with-delta/configs/as1border2.cfg
networks/example-with-delta/configs/as1core1.cfg
networks/example-with-delta/configs/as2border1.cfg
networks/example-with-delta/configs/as2border2.cfg
networks/example-with-delta/configs/as2core1.cfg
networks/example-with-delta/configs/as2core2.cfg
networks/example-with-delta/configs/as3border1.cfg
networks/example-with-delta/configs/as3border2.cfg
networks/example-with-delta/configs/as3core1.cfg
tests/basic/init-delta.ref
tests/basic/nodes-diff.ref

Although we discussed and decided to get rid of example-with-delta, I found that apart from the deleted demo script, it is being used in `tests/basic/commands` in some non-trivial tests (like generate-delta-dataplane, differential nodes question etc.). So thought it would be better to not remove it, instead bringing over the changes from example snapshot.

Bring example-with-delta in sync with example

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/AclLineMatchExprSetBuilder.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/ConjunctsBuilder.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/DisjunctsBuilder.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/explanation/ConjunctsBuilderTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/explanation/DisjunctsBuilderTest.java

The goal of these classes is to build sets of conjuncts/disjuncts that have no redundant members. 
Most of the logic exists in the abstract base class `AclLineMatchExprSetBuilder`. It uses BDDs to determine which members are redundant and remove them as they are inserted.

Build sets of AclLineMatchExprs conjuncts/disjuncts

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java

Looks like `convertVirtualSystems` is called twice (duplicated in a previous merge - called near the beginning and end of the `toVendorIndependentConfiguration` method).
This only needs to be called once to put vsys sub-components into the vendor independent model.

Remove duplicate vsys conversion call

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

`getIngressLocationAcceptBDDs()` returns for each ingress location the `BDD` representing headers that are accepted from that location. For locations that have no such headers, the map may be empty. Rather than crashing, default to `zero` `BDD`.

tolerate missing entries in reverse reachable states map

---

tools/install_z3.sh

Add exit on error to z3 install script.
FYI top level `set -e` applies to functions in the script as well.

Add exit on error to z3 install script

---

projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
tests/basic/commands

The bug: NeighborsAnswerElement was getting `layer2Neighbors` using:
`TopologyUtil.computeLayer2Topology(layer1Topology, configurations)`
`layer1Topology` came from `_batfish.getLayer1Topology()`, whose return value is nullable, but the `layer1Topology` parameter for `computeLayer2Topology` is nonnull.
The bug wasn't caught because our ref test didn't ask for layer2 neighbors. Now it does (current master would fail with the new test), but the neighbors ref didn't change because `layer2Neighbors` ends up null.
It looked like someone had already run into this in some other context, because Batfish already had a `getLayer2Topology` method with a safeguard against null `layer1Topology`.

Fix NPE bug for layer2 neighbors

---

projects/allinone/src/test/java/org/batfish/question/testfilters/TestFiltersTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java

* Keep track of indirection by separating out traces
* Return the last action at each level of indirection
* Ignore the "nothing matched" events unless it's at the top level of the tree.

Simplify testfilter presentation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/normalize/AclToAclLineMatchExpr.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/normalize/AclToAclLineMatchExprTest.java

Self-contained means we inline all references to other ACLs.

convert an entire ACL to a single self-contained AclLineMatchExpr

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDAcl.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpAccessListToBDD.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/normalize/AclToAclLineMatchExprTest.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/IpAccessListToBDDTest.java

Previously BDDAcl did two things: provide an abstraction of an ACL
represented by a BDD for minesweeper, and a factory to convert ACLs to
BDD (handling references to IP spaces and other ACLs, sources, etc).
This splits them into two classes, which simplifies things and makes it
easier and more efficient to reuse the factory functionality.

factor IpAccessListToBDD out of BDDAcl

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisEdge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisNode.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
questions/experimental/viModel.json
tests/basic/commands
tests/basic/viModel.ref
tests/questions/experimental/commands
tests/questions/experimental/viModel.ref

The new question produces all the information produced by the existing Nodes and Neighbors questions, new & improved, in one big JSON.
The keys are: nodes, bgpEdges, eigrpEdges, layer1Edges, layer2Edges, layer3Edges, ospfEdges, and ripEdges. Let me know if it would be better to group all the edges output under one `edges` key.
The only (intentional) difference between the new question's answer and the Nodes/Neighbors answers is that Neighbors separates ebgpEdges and ibgpEdges, whereas the new question combines them into bgpEdges (based on advice from @progwriter ).

Add VI Model question and tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclExplanation.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/AclExplanationTest.java

Constructs simplified AclLineMatchExprs of a particular form, used for headerspace explanations.
The form is a conjunction of:
- at most 1 positive `MatchHeaderSpace` expression
- at most 1 `MatchSrcInterface` or `OriginatingFromDevice` expression
- 0 or more negative `MatchHeaderSpace` expressions (subtracted from the positive one).
`AclExplanation` expects a set of literals whose conjunction is satisfiable. The normalizer is used to get arbitrary expressions into that form.

AclExplanation

---

projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/AclLineMatchExprSetBuilder.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/ConjunctsBuilder.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/explanation/DisjunctsBuilder.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/explanation/ConjunctsBuilderTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/explanation/DisjunctsBuilderTest.java

This is a simplification that is especially useful for building ACL expressions that describe the difference between two acls. In general, an ACL is encoded as an expression of the form `or(permitLine1Expr permitLine2Expr ...)`, where each permit line expression is of the form `and(not(denyLine1), not(denyLine2), ... permitLine)` (for each deny line preceding the permit line).   
When expressing the difference between two ACLs, each permit line expression will have the form:
```
and(not(denyAcl), not(denyLine1), not(denyLine2), ... permitLine)
```
Where `denyAcl` is itself a big disjunction `or(denyAclPermitLine1, denyAclPermitLine2, ...)`.
This change will reduce `not(or(denyAclPermitLine1, denyAclPermitLine2, ...))` to `and(not(denyAclPermitLine1), not(denyAclPermitLine2), ...)` and …

apply deMorgan and expand and/or exprs to remove redundant (con/dis)juncts

---

projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
tests/basic/traceroute-1-2.ref
tests/basic/traceroute2-1-2.ref

If the flow passes through an input filter, populate the field. Even if flow is denied.

Traceroute: populate filterIn unconditionally

---

projects/allinone/BUILD
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/question/BUILD
projects/question/pom.xml
projects/question/src/main/java/org/batfish/question/aclreachability/AclReachabilityAnswerer.java
projects/question/src/test/java/org/batfish/question/UndefinedReferencesAnswererTest.java
projects/question/src/test/java/org/batfish/question/UnusedStructuresAnswererTest.java
projects/question/src/test/java/org/batfish/question/aclreachability/AclReachabilityTest.java
projects/question/src/test/java/org/batfish/question/initialization/FileParseStatusAnswererTest.java
projects/question/src/test/java/org/batfish/question/initialization/ParseWarningAnswererTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java

Part 1 of batfish/batfish#2318
* Delete IBatfish#answerAclReachability. Inline the logic in AclReachabilityQuestion.
* Move AclReachabilityTest from allinone to question, since it now does not need
Batfish to run. This required fixing up IBatfishTestAdapter a little.
Lots still to do, but this is a nice first step.

AclReachability: move out of batfish and integrate test

---

projects/batfish/BUILD

This will stop it from recompiling batfish whenever we change questions.

bazel: batfish does not actually depend on question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclExplanation.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/AclExplainer.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/DifferentialIpAccessList.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/AclExplainerTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/DifferentialIpAccessListTest.java

Generate explanations of the headerspace permitted by an ACL or the
difference between the headerspaces permitted by two ACLs.

AclExplainer

---

projects/BUILD
skylark/javadoc.bzl

My hope is this can be a foundation of a script to update the website. The main advantage of using bazel for this: it's not affected in any way by the local state so there's no Maven/IDE screwups. And the commands are simpler.
To try it:
1. `bazel build //projects:javadoc`
2. Look at the produced file: `ls $(bazel info bazel-bin)/projects/javadoc.zip`

bazel: add javadoc generation

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/Edge.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

Rather than hard-coding two-types of edge (normal constraint edges and
source NAT edges), an edge is now represented as two functions -- one
for traversing forwards and one for backwards.
This will make it easier to add more kinds of transformations (other than source NAT).

generalize graph edges in BDDReachabilityAnalysis

---

projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java

renaming variable names in CounterExample.java for code readability

renaming variable names for readability

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/networks/unit-tests/configs/cisco_acl
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

Even though this is now an IPv6 code, this is an old v4 flag that means
fragmentation needed but DF bit set.

Cisco: support icmp v4 ACL packet-too-big

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

Add a factory method that builds multiple BDDSourceManagers, one per  node in the network, but all backed by the same BDD variables. This is going to be used by BDDReachabilityAnalysis

BDDSourceManager: share variables among all nodes in the network  

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactorySourcesTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/TestNetworkSources.java

For MatchSrcInterface and OriginatingFromDevice ACL expressions.
Maintains the invariant that whenever a packet is inside a node, it has
a valid source (according to the BDDSourceManager of that node). For
forward edges this is established by constraining to a single source.
For backward edges it's established using BDDSourceManager#isValidValue.
Also moved all edge creation into the factory. Previously,
BDDReachabilityAnalysis created edges that are specific per query. This
is too complicated now that we have to maintain this invariant -- better
to make that the responsiblity of the factory. The reason for the prior
separation was so that the edges that don't vary across queries could be
cached (someday). We can still do that, but will do it another way.

Track packet sources in BDDReachabilityAnalysis

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

Previously I memoized the reverse-reachability BDDs for all
dispositions. This is wasteful for reduced reachability, as it doesn't
care about all dispositions. This change should make it use less time
and memory.

Compute reverse reachability on demand.

---

projects/allinone/src/test/java/org/batfish/question/reducedreachability/ReducedReachabilityTest.java
projects/allinone/src/test/java/org/batfish/symbolic/smt/TwoNodeNetworkWithTwoLinks.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/StaticRouteTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/TestNetwork.java
projects/batfish/src/test/java/org/batfish/dataplane/PathDiffTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/PrefixTracerTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobAclTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
projects/batfish/src/test/java/org/batfish/z3/ReducedReachabilityTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

*Problem*:
- In StaticRoute builders, we defaulted to making admin cost -1, unless explicitly set. 
- We had no validity checks for this value elsewhere (e.g., RIBs)
- In some corner cases, this made static route better than *any other route* including connected, which is wrong (as discovered by @yifeiyuan).
This affected tests only, admin distance was/is set correctly (AFAIK) upon conversion VS -> VI.
*Fix*:
- Require valid (>= 0) admin cost upon construction of static routes
- Cleanup constructors/builder pattern for static routes: constructor is now private, builders are used everywhere, admin cost is explicitly set. Since many of our tests are Cisco IOS-ish, went with admin cost of 1 for existing tests.
*Future work*:
We should probably pull up admin cost/tags up to abstract route …

Fix static route builder; hide public constructors

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java
projects/question/src/main/java/org/batfish/question/bgpproperties/BgpPeerConfigurationAnswerer.java
projects/question/src/main/java/org/batfish/question/bgpproperties/BgpPeerConfigurationPlugin.java
projects/question/src/main/java/org/batfish/question/bgpproperties/BgpPeerConfigurationQuestion.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpPeerConfigurationAnswererTest.java
questions/experimental/bgpPeerConfiguration.json
tests/questions/experimental/bgpPeerConfiguration.ref
tests/questions/experimental/commands

Each row of the table answer is a BGP peer with the following properties:
-  Node
- VRF
- Local AS
- Remote AS (which is a list for passive neighbors)
- Local IP
- Remote IP (which is a prefix for passive neighbors)
- Route-reflector client
- Peer group
- Import policy
- Export policy
- Send community
More properties will be added as we find ways to surface them effectively; see [design doc](https://docs.google.com/document/d/1SZeswG8qsXcjeMhETQr6QRLSboEv73R7-UQqQGBqC-I) for details.

Create BgpPeerConfiguration question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes

*Note* no changes to FIB computation process, extraction only (to keep self-contained).

Juniper: parse and extract static route no-install

---

projects/coordinator/BUILD

- Add guava testlib to coordinator tests
- Fix alphabetization I messed up earlier 🙂

Fix coordinator test dependencies in bazel

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorageDirectoryProvider.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/config/SettingsTest.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

Deprecate old constant but leave present for now.
Since we redid the entire file structure inside the storage system, start fixing constants in there too.

BfConsts: rename testrigs to snapshots in path

---

.travis/common.sh
WORKSPACE
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceAddressGroupIpSpaceSpecifierFactoryTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierFactoryTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/schedule/NodeColoredSchedule.java
projects/batfish/src/test/java/org/batfish/dataplane/DynamicBgpTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/checkstyle.xml
projects/coordinator/pom.xml
projects/coordinator/src/main/java/org/batfish/coordinator/ExceptionMapper.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
projects/pom.xml

1. Disable the bootclasspath warning with -Xlint:-options
2. Fix two tests using deprecated APIs
3. Relax the version check to 1.8 and later
4. Upgrade jacoco to one that supports jdk11

maven: java 11 compatibility

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java
projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java
projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java
projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java
projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java
projects/batfish/src/main/java/org/batfish/z3/ReachabilityQuerySynthesizer.java
projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/main/ReachabilityParametersResolverTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobAclTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobChunkingTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
tests/java-smt/commands

Switch to AclLineMatchExpr as an intermediate representation in the reachability question pipeline (from ReachabilityParamters on). Mostly straightforward, with the following exceptions:
- Compression is now completely disabled since it expects a headerspace expressed as a single `HeaderSpace` object. Was already mostly disabled for different reasons. I left the code there for when we fix it. For now, an error is thrown if the user sets the `useCompression` flag.
- `AclLineMatchExprToBooleanExpr` needed a new parameter to indicate that `HeaderSpace` constraints should be applied to the original headerspace variables (i.e. before any transformation).

use AclLineMatchExpr to represent HeaderSpace constraints in reachability

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpLink.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighbor.java
projects/question/src/main/java/org/batfish/question/OspfSessionCheckQuestionPlugin.java

* Move off of comparable structure
* Cleanup json creators
* Move out `OspfNeighborSummary` to the session check question (only place it's used).
Some JSON prop names are weird (`name` where it should be `link`) but kept it that way in the interest of backwards compatibility, can change later.

Cleanup IpLink and OspfNeighbor

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/FileBasedIdResolver.java
projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/IdResolver.java
projects/batfish-common-protocol/src/test/java/org/batfish/identifiers/TestIdResolver.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/id/FileBasedIdManager.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/LocalIdManager.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java

- add snapshotname arg that gets passed by coordinator to worker
- remove extraneous mapping APIs for getting names from IDs
- clean up snapshot deletion test that broke as result
- implement v2 call for maximum cleanliness

Cleanup snapshot-name passing and handling

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraintsUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsUtilTest.java
projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java
projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java
projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java
tests/questions/experimental/commands
tests/questions/experimental/searchfilters.ref

Benefits:
- Can now support port exclusions
- Cleaner support for singleton ranges 
- Simplifies some of the validation logic and conversions
Side effect:
- Cleanup of conversion(s) to headerspace in SearchFilters and new reachability

Switch to using IntegerSpace in PacketHeaderConstraints

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/InboundStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Step.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/StepAction.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
tests/questions/experimental/tracerouteListHops.ref

Fix #2463
* Only use EnterSrcIfaceStep if there is actually a src interface. If the
packet originates in a virtual router, do not add this step.
* Add an InboundStep, which is a terminal step taking the place of RoutingStep,
for handling traffic destined to the node itself. This catches the old "ingressVrf"
case as well as coming after any enter src interface processing.
* This automatically makes us check inbound filter before handling traffic
destined for the node itself, fixing #2463.

Traceroute: add InboundStep

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsTest.java

*Issue*:
If one specifies exclusions only in string form, e.g., "!22" an empty integer space is produced.
Sort of makes sense... Excluding something from an empty space is still empty; The problem is that there is some implicit finite universe space from which we are excluding, however it varies and isn't known ahead of time.
*Fix*:
Switch PHC to de-serialize to IntegerSpace builder instead and do some post-processing, defining the universe space as needed (per field).

Header constraints: support spaces consisting of *only* exclusions

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

1. Remove the dummy hop :tada:
2. Remove the ARP analysis. The intended semantics of this question
is that the flow is delivered to this interface and processed from
there.

Traceroute: fix enter(interface)

---

projects/batfish-common-protocol/src/main/java/org/batfish/question/reducedreachability/DifferentialReachabilityParameters.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

Make the engine robust to non-exist final nodes and source locations.  These can arise in the context of differential reachability (if nodes/locations are added or removed). It's not immediately clear what the desired semantics is in this case, but it should be up to the question. So the engine should be able to tolerate handle non-existent nodes/locations.

 handle non-existent source locations and final nodes in bdd reachability engine

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowTrace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VerboseEdgeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/role/InferRolesMixedCaseTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/role/InferRolesTest.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/symbolic/Graph.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java
projects/batfish/src/test/java/org/batfish/z3/state/visitors/DefaultTransitionGeneratorTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/question/src/test/java/org/batfish/question/NeighborsAnswerElementTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

Goal: wanted to make a push for less confusing, our topology (currently looking at OSPF) code. `node1`/`node2` is hard to read reason about and it's even worse with `getFirst()` and `getSecond()` inherited from pair. Decided to settle on `tail`/`head` terminology from graph theory (alternative would be guava's `source`/`target` terminology).
Thoughts? 
Work along the way:
* Do not extend pair
* Switch to head/tail language
* Add static factory methods, limit number of constructors
* Add javadoc and some tests

Edge class: cleanup, meaningful getters

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RouteInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RoutingStep.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
tests/questions/experimental/tracerouteListHops.ref

Not showing routes in the `Routing` step which differ in properties which are not a part of the `RouteInfo` class.
Also removing the unused `routesForThisNextHopInterface ` attribute of `TransmissioinContext`

Fixing duplicate routes in traceroute

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/test/java/org/batfish/main/AwsParseWarningsTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpcPeeringConnectionTest.java
tests/aws/init-example-aws.ref

Rather than sending warnings to the BatfishLogger when parsing AWS configs, it now adds them to the `ParseVendorConfigurationAnswerElement` under hostname `aws_configs`, which hopefully won't collide with any real hostnames.
I can change `Region.getChildConsumer()` back closer to its original form if reviewers want me to do so -- might be a bit less opaque that way. Each case ends up being annoyingly verbose, though:
```
case (key):
for (int i = 0; i < jsonArray.length(); i++) {
JSONObject jsonObj = jsonArray.getJSONObject(i);
// stuff specific to this case
}
break;
```
as opposed to
```
case (key):
return jsonObj -> {
// stuff specific to this case
}
```

Record AWS parsing warnings in answer element

---

projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NodeInterfacePair.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CommonUtilTest.java
projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java

This seems like the behavior that would happen in practice, right? Should we support this?
@anothermattbrown  - everything passes except the traceroute tests with hardcoded networks that rely on the edges not being there.

Topology: add L3 edges between interfaces with different subnet masks that could still ping

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfArea.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkFactoryTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

I did this as an exercise to see how easy/challenging it would be to move towards immutable Configurations or even smaller datamodel pieces (spoiler alert, it's hard 🙂 )
Key points:
* Move OspfArea off of comparable structure
* Make most fields final and immutable sets/maps
* Replace `name` with `areaNumber` (although kept as `name` in JSON representation for backwards compatibility
* Annotations/Javadoc, etc. usual cleanup.

Make VI OSPF area class as immutable as possible

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java
tests/basic/filterLineReachability.ref

Various things including TableDiff rely on rows' columns exactly matching their column metadata. This change ensures that's the case when rows get built.

Automatically add missing columns when building Row

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java

Previously, it was called 8 times, which is both expensive, and creates
a lot of copies of the same complex IpSpaces.

Only call Rib.getMatchingIps once per Vrf.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableAnswerElement.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AnswerMetadataUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableAnswerElementTest.java

`TableAnswerElement` now throws an `IllegalArgumentException` if you call `addRow` or `addExcludedRow` with a row whose columns don't exactly match the table metadata columns.

Check row for correct columns when adding to table

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MemoizedIpSpaceToBDD.java

ForwardingAnalysis (especially after recent changes) creates too many
different value-equal objects. With IdentityHashMap, memoization wasn't
helping enough. HashMap works significantly better now.
Long-term, we may want to reduce the number of value-equal IpSpaces we
keep around. For example, there are many ways to express Universe or
Empty -- we could make an effort to canonicalize. Also, each call to
toIpSpace() on an Ip, Prefix or IpWildcard creates a new object.

use HashMap instead of IdentityHashMap

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

Fixes #2543 
This detects infinite loops, as opposed to loops that will exit eventually due to NAT. The check is based on the history of visited VRFs and the current flow at the time of each visit. Since this is not already present in the `Hop`s and `Step`s, I added a new `Breadcrumb` class and keep a stack of them.

implement loop detection in the new traceroute engine

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

Fixes an IllegalArgumentException after stricter standards added in #2541

Routes question: bgp rib should include tag column

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

The breadcrumbs stack was being shared by multiple threads(!!), which lead to false-positives. Made it a parameter instead of a field.
Also removed the unused variable `visitedHops`

Traceroute: Fix race in loop detection; remove unused parameter

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java

Differential context boolean was not used anywhere.

Remove unused parameter in computeDataplane

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperAggregationTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/aggregation/configs/ae1
projects/batfish/src/test/resources/org/batfish/grammar/juniper/aggregation/configs/ae2
tests/parsing-tests/networks/unit-tests/configs/juniper_interfaces
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

NB: Batfish currently only supports if->if direct aggregation for Cisco channel groups, but
for Juniper and even more advanced Cisco use cases, need to support interface->interface
bindings at a higher level in the hierarchy, with subinterfaces of the aggregation.
E.g., ge-0/0/0 -> ae0, and then ae0 has ae0.0, ae0.1, ae0.2, ...
For now, model Juniper 802.3ad aggregation as always linking ge-0/0/0 (e.g.) to ae0.0.
Includes a unit test we will need to fix when we improve the model.

Juniper: partial support for 802.3ad aggregate interfaces

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorageDirectoryProvider.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java

Currently there is no way for clients to get logs/errors for generic "queue work" workitems (it used to be available in a hacky way via `get_object` API call). 
This makes investigating parsing/DP failures and reporting them quite difficult. 
Add a new API call that clients can use to fetch a workitem log if the work terminates abnormally.
Was planning to add tests from clients, but if you have suggestions on how to test in the backend, please lmk.

Add an API call to retrieve a workitem log

---

projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java

- This will allow specifiers reachability to include `LOOP` disposition in normal reachability queries

Integrate loop in bdd single reachability

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

It seems perfectly legal to configure both a native VLAN on a trunk switchport
and to limit the set of allowed VLANs on that trunk. Make the L2 topology
helpers resilient to this configuration.
cc: @agember does this fix your issue?
cc: @arifogel 
still needs tests, but the offending NX-OS config snippet is:
```
interface Ethernet2/1
no shutdown
switchport
switchport mode trunk
switchport trunk native vlan 23
switchport trunk allowed vlan 23
```

(draft) TopologyUtil: robust to native vlan in allowed vlans

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java

Catching up after 6b3a90845876934928ba6bd18851dc5cd1fcdab9. 
(There are downstream tests that started failing after the commit. That nothing failed in this repo reveals a testing gap.)

Pack allowed vlans as String, not List<String>

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

This code has been carried from old bdp and it looks like incorrect tests were written for it long ago.
A route from a different area should not be considered as a contributing route to a particular area summary.

Update OSPF summary metric computation

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java

When task requeueing fails, add exception message to the fake task to surface a little more detail to clients 
I opted out of adding stack trace as that ends up being a wall of unformatted text from the client's standpoint - but I can add that back in if the consensus is to err on the side of more data over readability.

Add more detail to requeue failure

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

Suppression of type3 LSAs should happen regardless of link/route area numbers.

OSPF inter-area route propagation: better honor suppress type3 LSAs

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

Previously we were not suppressing the more specific are routes at the juniper ABRs
cc @arifogel

Juniper: construct route filter lists for OSPF area summaries 

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java

We used to grab filter lists from the wrong area so the specifics wouldn't be suppressed.

OSPF: Get correct filter lists on intra- to inter- area route conversion

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java

* Add snapshot validation to snapshot init in `WorkMgr`
* Checks for existence of configs, aws_configs, or hosts dir
* Surface more details to clients during snapshot init failure
* Including failures in the newly added ss validation
For example: when uploading an improperly formatted snapshot dir, `Pybatfish` previously displayed:
```
>>> bf_init_snapshot("/networks/example", name="example", overwrite=True)
BatfishException: Initializing snapshot example_snapshot failed with status TERMINATEDABNORMALLY
Exception in container:0be21c77-3056-48dc-98d3-bf3ec929825e, testrig:17e18286-7aea-4553-9292-b02bc13461e2; exception:org.batfish.common.BatfishException: No valid configurations found in snapshot path /path/to/containers/0be21c77-3056-48dc-98d3-bf3ec929825e/snapshots/17e18286-7aea-4553-9292 …
```

Add snapshot validation

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

Enables running the prefix-tracer question on dataplanes that have been deserialized from disk without crashing.
*Note*: this will introduce some overhead when (de-)serializing dataplane. Working on improving prefix tracer logic.

Make prefix-tracer non transient

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

See discussion in #1556. 
Restoring the behavior where `bgp bestpath as-path multipath-relax` should not by itself enable ebgp multipath. 
Keeping the tests and cleanup introduced in #1582
This resolves #1556.

Restore behavior before #1582

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java

Fixed two bugs in the code that adds edges to the BGP topology:
1. When considering passive candidates for the remote peer, the old code filtered out candidates whose remote peer prefix didn't contain the neighbor's peer address (old line 153). AFAICT this should have been filtering for peer prefix containing the neighbor's local IP instead. However, that's already done a few lines later with `bgpCandidatePassesSanityChecks()`, so I just took out the filter.
2. For passive candidates for the remote peer, we were never checking that the passive peer's host owned the neighbor's remote IP. Since passive peers have their local IPs set to `Ip.AUTO`, this wasn't caught by sanity checking the `BgpPeerConfig` fields. I added a line to `bgpCandidatePassesSanityChecks()` to ensure that for passive …

Fix 2 bugs in BGP topology generation; start tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
tests/parsing-tests/unit-tests-nodes.ref
tests/questions/experimental/searchfilters.ref

Fixes InterfaceProperties for allowed vlans
After #2666, since the refs will conflict.

IntegerSpace: prettyify toString by default

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java

Make directory existence checks more robust in `FileBasedSotrage`.
Consider the following (when `dir` does not yet exist):
```
if (dir.toFile().exists() || dir.toFile().mkdirs()) {
doSomething();
}
```
If multiple calls were simultaneously made to this snippet, it would be possible for all to see `dir` does not exist, and all try to create it.  However, only one would succeed in `mkdirs` and therefore only one call would get to `doSomething`.
After changing the order of `exists` and `mkdirs`, simultaneous calls may fail to `mkdirs` but should see `dir` exists and all should continue on to `doSomething`.

Make dir existence checks more robust

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionAnswerer.java

Used to check for `degree > 2`, on the assumption that:
- an active peer with degree 1 must be correctly configured to peer with a passive peer
- an active peer with degree 2 must be correctly configured to peer with another active peer
Changing because it seems plausible that there are some broken edge cases that could violate those assumptions.

Saner condition to check for multiple remotes

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/TypeNameRegexInterfaceSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactoryTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/TypeNameRegexInterfaceSpecifierTest.java

Adds `TypeNameRegexInterfaceSpecifier`, which allows interfaces to be specified by type, and incorporates it into `FlexibleInterfaceSpecifier`. This will allow us to provide generic queries that work on any network, e.g. verify reachability or multipath consistency  between all pairs of loopbacks.
```
bfq.reachability(
pathConstraints=PathConstraints(startLocation="[type(loopback)]"),
headers=HeaderConstraints(dstIps="ofLocation([type(loopback)])"),
actions="FAILURE")
bfq.multipathConsistency(
pathConstraints=PathConstraints(startLocation="[type(loopback)]"),
headers=HeaderConstraints(dstIps="ofLocation([type(loopback)])"))
```
cc @saparikh

support for specifying interfaces by type

---

questions/experimental/loopbackMultipathConsistency.json
questions/experimental/subnetMultipathConsistency.json
tests/questions/experimental/commands
tests/questions/experimental/loopbackMultipathConsistency.ref
tests/questions/experimental/subnetMultipathConsistency.ref

Two new scoped multipath checks that should be more usable on an arbitrary network than the unscoped version. One checks all subnet pairs, and the other all loopback pairs.
cc @saparikh

new scoped multipath consistency question templates

---

projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
tests/parsing-tests/unit-tests.ref

Detect and skip parsing empty files - even when config format is not dynamically detected.

Skip parsing empty files

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NamedStructureSpecifier.java
projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresAnswerer.java
projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresPlugin.java
projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresQuestion.java
projects/question/src/test/java/org/batfish/question/namedstructures/NamedStructuresAnswererTest.java
questions/experimental/namedStructures.json
tests/questions/experimental/commands
tests/questions/experimental/namedStructures.ref

Clean up in preparation for better downstream usage
1. Structures go along rows, not columns, in the answer table
2. Use constants in NamedStructureSpecifier
3. Rename the question field 
4. Test

cleanup named structures answerer

---

projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java
projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java
projects/batfish/src/test/java/org/batfish/main/ReachabilityParametersResolverTest.java
projects/question/src/main/java/org/batfish/question/ReachabilitySettings.java
projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java
projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java

This simplifies SpecifiersReachabilityQuestion, but also changes the
invariants of ReachabilityParameters: now all node specifiers are
@Nonnull, but may resolve to the empty set.

Conform to the standard set by createPathConstraints.

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserErrorListener.java

A missing part of batfish/batfish#2518
This is currently only used on parser errors, so when you're editing parser.

BatfishParserErrorListener: cleanup mode output

---

projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2TestBase.java

- add constant that can be altered to adjust test log level

silence jersey/grizzly logging during junit tests

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java

- NX-OS follows a different codepath, so the TODO is bogus
- the unimplemented ACL clauses are now handled by a catch-all at the end and can be deleted

CCPE: delete unused code

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java

For the interim until better OSPF topology generation is ready

Remove lying nonnull annotation on ospfNeighbors

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisEdge.java
projects/batfish/src/test/java/org/batfish/dataplane/topology/IsisEdgeTest.java

Fixes bug where `intersection(LEVEL_1, LEVEL_2)` threw a `NullPointerException` because the `reduce` method [throws NPE if the result of the reduction is null](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#reduce-java.util.function.BinaryOperator-).

IsisLevel.intersection method: fix and test

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

@sfraint has scoped out how to make this unnecessary, but it involves replacing how we map line numbers during conversion from hierarchical to flattened configs.

Juniper: fix hierarchical line tracking

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperAggregationTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

Few things happening here:
- Put juniper physical interfaces in the VI datamodel
- Track dependencies between units and physical interfaces
- Fix the todo introduced in #2604 
- Introduce another todo: we should be disabling interfaces based on dependencies now and not portChannelGroupMembers. I have fixes for this locally but I didn't want to glom too much into 1 PR since it's a non-trivial change.
- Correctly identify loopback and unit interfaces on juniper

Juniper: put physical interfaces in VI datamodel, track dependencies

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NamesTest.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

Beginning with zone-to-zone, which is not a generated structure name and
clarifies when it should be used.

Start a canonical place to put Batfish-chosen names

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperAggregationTest.java

Dependency pointer should go AE -> physical interface, not the other way around.

Juniper: fix a bug where interface dependency was pointing the wrong way

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatRule.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleSet.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java

Currently NatRules in a NatRuleSet are kept in a map, and the order in
which they are defined is lost. The semantics requires they be applied
in definition order, so this change stores them in a list instead (and
makes the NatRule name a field rather than a key in the map).

preserve order of NatRule definitions

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-bandwidth
tests/parsing-tests/networks/unit-tests/configs/juniper_interfaces
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

It means cells, which are apparently a unit of 384bps.
Includes a little test simplification using multiple units on the same physical interface.

Juniper interface: add support for 'c' modifier

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfExternalType1RouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfExternalType2RouteTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/question/src/main/java/org/batfish/question/OspfStatusQuestionPlugin.java

This also made me add them to all child builders, which was a far-reaching but brainless change.
In the process, I found that StaticRoute did not compare these properties when checking equality, and I found that it did not hash on the network. Fix both of these changes.

AbstractRoute: add nonForwarding/nonRouting to builder

---

projects/coordinator/src/main/java/org/batfish/coordinator/QueuedWork.java
projects/coordinator/src/test/java/org/batfish/coordinator/QueuedWorkTest.java

Record work termination time.  Previously, terminated `QueuedWork` always had a null `dateTerminated`.

Record QueuedWork termination time

---

projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis-no-reference-bandwidth

Tests that reference-bandwidth is applied correctly in the juniper-isis unit test and that the default Juniper IS-IS cost is used in the absence of reference-bandwidth.
Question: Is it worth making `JuniperConfiguration.DEFAULT_ISIS_COST` public and renaming to `JUNIPER_DEFAULT_ISIS_COST` rather than using a literal `10` in these tests?

Add unit test for reference bandwidth

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfEdge.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfEdgeTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TestUtils.java
projects/batfish/src/test/java/org/batfish/main/TestrigText.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/ospf-edge/configs/A1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/ospf-edge/configs/A2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/ospf-edge/configs/FWL

* OSPF Neighbors for a VirtualRouter are now a list of OspfEdge, where this router
is always the first node in the edge.
* OSPF incoming routes for a VirtualRouter is now a Map of OspfEdge -> Queue, where
this router is always the *second* node in the edge. (Aka, the receiving edge).
* Stop iterating over L3 topology, just iterate over the queues.
* Some code duplication reduction between processing E1 and E2 routes.
Still needs tests, but making progress.

OSPF: fix neighbors and routes to key on OspfEdge

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/Edge.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

This fixes a long-standing known bug, and prepares us for implementing source NAT on juniper in a sensible way.
Some other minor changes:
- precompute BDDNat objects since they're used multiple times.
- Created a zero-argument Edge constructor for identity edges (rather than using the one BDD).
- Consolidate null-checking of ACL names.

Apply source nat before arp failure dispositions in BDD reachability

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java

this is a useful API which can be used while overriding `answerDiff()` so could be made public

Making diff table schema conversion API public

---

projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java

Only one of the non-computed properties of SearchFiltersQuestion was not public.  Making it public makes it easier to manipulate these questions externally.

make all non-computed properties of SearchFiltersQuestion public

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

Those in TransmissionContext seem to be empty when they shouldn't be. Anyway, this fixes the problem, though I don't fully understand what's going on here, or why the unit tests didn't catch it.
cc @haverma

don't use the aclDefinitions and namedIpSpaces from TransmissionContext

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

Since these happen inside a loop, we need to copy _hopsSoFar before adding the hop.

Fix traces for NULL_ROUTED or DENIED by preSourceNat outgoing filters

---

projects/batfish/src/main/java/org/batfish/datamodel/acl/AclExplainer.java
projects/batfish/src/main/java/org/batfish/datamodel/acl/DifferentialIpAccessList.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/AclExplainerTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/DifferentialIpAccessListTest.java

- allow the set of named ACLs given to AclExplainer to either include or not include the top-level acl being analyzed
- only include the top-level deny ACL in a differential query once in the set of deny named ACLs

AclExplainer named acls fixes

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContext.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContextImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/MockSpecifierContext.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/TestSpecifierContext.java

Simplifies future work on caching results of ipOwners

Remove vrfOwnedIps from specifier context

---

projects/question/BUILD
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityQuestion.java
projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswererTest.java
tests/basic/filterLineReachability.ref

When line L is blocked and lines 1..L-1 terminate some of the flows that line L match, the old code returns all of lines 1->L-1 as blocking lines. In reality, this is usually overly conservative because many of the lines may represent "trivial" overlaps.
Prune down the list of blocked lines by building up a subset of lines 1..L-1 that:
- considers lines in decreasing order of how much they overlap with L.
- stop when we have a subset that fully covers L, hopefully much smaller than 1..L-1.
- if some line has a different action than L, includes at least the largest such line. This indicates to the user that some packets L intended to permit/deny are denied/permitted, and lets the user decide how important this is.
Refactors the internals of FilterLineReachabilityAnswerer for readability, …

FilterLineReachability: proposal to simplify blocking lines reported

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
tests/parsing-tests/networks/unit-tests/configs/juniper_security
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

Fixed what appears to be a misunderstanding in Juniper address book implementation. There is only one global address book with name "global," and there can be other non-global address books with custom names.

Juniper address books

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java

Testing on GNS3 showed that when wide-metrics-only is not set and IS-IS route cost is more than 63, the cost is simply clipped to 63 (regardless of whether the original cost was explicitly set in the interface's IS-IS configuration or calculated from the reference bandwidth).

Clip IS-IS route cost when wide-metrics-only unset

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/ipspace/IpSpaceSimplifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/ipspace/IpSpaceSpecializer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceDereferencer.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceDereferencerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceDescriberTest.java
projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceRenamer.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/z3/expr/visitors/IpSpaceBooleanExprTransformerTest.java
projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswererTest.java

- Creation: add a few new functions mimicking the Guava APIs and use them
throughout.
- AclIpSpace.Builder: delete setLines(), make _lines final. This ensures a
clean path to adding lines to a builder, and in fact most/all uses of
setLines were really just to make an AclIpSpace directly with only those lines.
- AclIpSpace.Builder: short-circuit adding lines once a catch-all line
(UniverseIpSpace) is added. This is a conservative but constant-time
optimization. Test.
- Patch up one test that relied on the short-circuit not happening.
- Fix a bug in IpSpaceDereferencer where a line action was ignored.
Add test.

AclIpSpace: simplify creation, short-circuit building

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InterfaceType.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Tunnel.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
tests/parsing-tests/unit-tests-nodes.ref

* Cisco: properly set dependencies for tunnels (source-interface)
and portchannels
* Disable portchannels based on dependencies only
* Introduce new interface type for Juniper ae unit interfaces

Interface dependencies: use for tunnels and portchannels

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
tests/parsing-tests/networks/unit-tests/configs/juniper_bgp
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

No actual support needed currently. See:
https://kb.juniper.net/InfoCenter/index\?page\=content\&id\=JSA10491\&cat\=SRX_SERIES\&actp\=LIST

junos: parse bgp drop-path-attributes

---

projects/allinone/pom.xml
projects/allinone/src/test/java/org/batfish/question/searchfilters/SearchFiltersDifferentialTest.java
projects/allinone/src/test/java/org/batfish/question/searchfilters/SearchFiltersTest.java
projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java

searchFilters should not catch all exceptions from reachFilter -- that was causing errors to be masked.
searchFilters should rename ACLs when they are modified, so they don't conflict with the original versions of those ACLs when generating explanations.

Search filters hygiene

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/AbstractAggregateRoute.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/parsing-tests/networks/unit-tests/configs/juniper_routing_options
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

And implement semantics. Note that Juniper has both 'reject' and 'discard' semantics,
but Batfish does not yet distinguish between them. So aggregate routes overridden from
reject to discard are still dropped.

Juniper: parse routing-options aggregate route discard

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/networks/unit-tests/configs/juniper_bgp
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

`loops` were only handled at the autonomous system level before, but apparently can also be specified as config for the address family:
https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/loops-edit-protocols-bgp-family.html

Juniper: support bgp loops in more stanzas

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixSpaceTest.java

- Make _prefixRanges immutable
- Rewrite the prune logic for fewer copies (same # passes)

PrefixSpace: cleanup

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-isis

Only add interface ISIS settings when ISIS is enabled on the interface
(as indicated by a set mode)
Fixes #2841

Cisco: fix interface ISIS conversion

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java

Code was assuming all passive BGP peers would be included in the established BGP topology, but actually they can be left out if they don't pass [`BgpTopologyUtils.bgpConfigPassesSanityChecks()`](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java#L200).

Check if establishedBgpTopology contains node

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

This code was entirely unused because it's not part of any BGP advertisement plugin (which is now the primary way of loading external BGP advertisements). 
Considering that the format is also very obscure and there have been plans to overhaul how external BGP advertisements are specified, chose to just get rid of this code.

Remove unused BGP advertisement code

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java

- Fix typo in two variables: `builer` to `builder`
- Remove unused variable `DEFAULT_ISIS_INTERFACE_COST` in IsisProcess (there's also a `DEFAULT_METRIC` in IsisRoute, which is used)
- Give `generateIsisInterfaceRoutesPerLevel()` the smarts to check which ISIS level it's dealing with, and consequently simplify `generateAllIsisInterfaceRoutes()`
- Simplify `RibDelta.getActions()` by using `getOrDefault()`
I don't believe there are any merge conflict concerns with #2889.

Simplifications and typo fixes

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/unit-tests-nodes.ref

In an unlikely corner case, we could end up with an interface in the wrong RI (or 2 RIs)
because we initialized it not in the default routing instance. It should be initialized
in the default RI, and only set to the current RI in the
set routing-instance <RI> interface <I>
syntax by which interface RI membership is configured.

Juniper: honor configured routing-instance

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/TransformationStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/AssignIpAddressFromPool.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/Noop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/ShiftIpAddressIntoSubnet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/Transformation.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStepVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/transformation/AssignIpAddressFromPoolTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/transformation/NoopTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/transformation/ShiftIpAddressIntoSubnetTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/transformation/TransformationTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java
projects/batfish/src/main/java/org/batfish/datamodel/transformation/TransformationEvaluator.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatRule.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleSet.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationTransitionGenerator.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformationToTransitionTest.java
projects/batfish/src/test/java/org/batfish/datamodel/transformation/TransformationEvaluatorTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatRuleSetTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatRuleTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/TransformationTransitionGeneratorTest.java

In order to produce the same traces, also added TransformationTypes to
each TransformationStep. The transformation evaluator uses those to
generate trace steps. Also added a new Noop transformation step, which
allows us to generate steps correctly for "no-nat" style
transformations. A transformation can no longer have an empty list of
transformation steps.

use Transformations in traceroute

---

projects/batfish/src/main/java/org/batfish/z3/SynthesizerInput.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationExpr.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationStepExpr.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationTransitionGenerator.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/Parameterizer.java
projects/batfish/src/test/java/org/batfish/z3/MockSynthesizerInput.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/TransformationExprTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/TransformationStepExprTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/TransformationTransitionGeneratorTest.java
projects/batfish/src/test/java/org/batfish/z3/matchers/SynthesizerInputMatchers.java
projects/batfish/src/test/java/org/batfish/z3/matchers/SynthesizerInputMatchersImpl.java
projects/batfish/src/test/java/org/batfish/z3/state/visitors/DefaultTransitionGeneratorTest.java

Switch NOD reachability to use the outgoing transformations instead of source nat. Incoming transformation is not (yet) integrated. Changed TransformationExpr and TransformationStepExpr to be parameterized by edge instead of interface.

use Transformations in NOD reachability engine

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisEdge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisLevel.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/isis/IsisLevelTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisRouteMatchers.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/topology/IsisEdgeTest.java

Only functional change is line 1422 in VirtualRouter, which stops route propagation if the ISIS interface level that received the advertised route is passive.
Very open to suggestions for simplifying the test.

 Stop IS-IS route propagation if level is passive

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatPacketLocation.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleSet.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatPacketLocationTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatRuleSetTest.java

In Juniper, outgoing transformations are applied conditionally depending
upon the source interface. We need to check the source interface before
applying the transformation. Incoming transformations do not need to do
the check, since they are installed on the source interface (i.e. we can
hard-code the value).

Check from location (interface/zone/routing instance) for outgoing transformations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IsisRouteTest.java

- add `toBuilder()` method
- check `_network` in `hashCode()`
- remove redundant variable `_administrativeCost` in favor of `AbstractRoute._admin`

IsisRoute cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpProcessPropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NamedStructureSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfPropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java

So that the implementor can use order to signify preference, e.g., in property tables.

PropertySpecifier: switch from a set to a list

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CommonUtilTest.java

And add test.
The L1->L3 topology pathway already allows this to happen.

L3 inferred topology: allow self-edges across VRFs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AnswerMetadataUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AnswerMetadataUtilTest.java

Prevents null pointer exception if `rowToInteger` for `Schema.INTEGER` produces `null` values.

AnswerMetadataUtil.computeColumnMax - filter null values in calculation of return value

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-from-prefix-list

Fixes a bug where routes were required to match every prefix list within a policy statement term instead of any one of them.

JNPR policy-statement: OR all prefix-lists

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/CryptoProfile.java

Partially fixes #2938 (gets rid of error in `network ike`).

PaloAlto CryptoProfile was not serializable

---

README.md

Folks need not clone via git, they can just use `pip` to do that directly.

Cleanup pybatfish installation via pip

---

.travis/fix_java_format.sh

1. Avoids "argument list too long" error
2. Simplify script to not bother counting the files.

Update fix_java_format script to use a temp file.

---

projects/pom.xml

We only need code coverage results when running in CI, or manually.

Maven: Add jacoco.skip to fast profile

---

.buildkite/pipeline.sh

It's the slow part of the pipeline, now bazel is not the slowest part.

buildkite: exclude javadoc

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/TracerouteEngine.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowHistory.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishBDDDetectLoopsTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishBDDDifferentialReachabilityTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobAclTest.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/main/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswerer.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/main/java/org/batfish/question/loop/DetectLoopsAnswerer.java
projects/question/src/main/java/org/batfish/question/multipath/MultipathConsistencyAnswerer.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java

Now, rather than going through dataplane plugin or batfish, clients use the TracerouteEngine interface to run traceroutes. Removed the old `processFlows`/`getHistory*` song and dance, and the `_flowTraces` map in dataplane plugin that depended upon. Now we use a single method call on TracerouteEngine. The engine is no longer a singleton, but keeps a reference to the dataplane it will use. 
Among other benefits, this will allow us to change the interface to traceroute (e.g. add a method for bidirectional traceroute) without affecting batfish or dataplane plugin.
cc @dhalperi @arifogel

move interface to traceroute out of dataplane plugin

---

projects/allinone/src/test/java/org/batfish/question/edges/EdgesTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer1EdgeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer1NodeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java

- Logical topology replaces aggregated interfaces with the aggregate
interface of which they are a constituent.
- Layer-2 topology computation is now based off of Layer-1 logical
topology.
- Edges question now returns Layer-1 logical topology when edgeType is
Layer-1.

Computation of Layer-1 Logical topology

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperControlPlaneExtractor.java

Question: Is it correct that `dlp` is run twice? I couldn't find anything in the code that makes it obvious this should happen.

FlatJuniperControlPlaneExtractor: add spans to subdivide the many phases

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testrigs/static-route-communities/configs/r1
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testrigs/static-route-communities/configs/r2

Since Juniper static routes can have BGP communities but our VI routes don't (and shouldn't, since Juniper is the only vendor that does this), this PR adds statements at the beginning of BGP export policies that tack the appropriate communities onto static routes before exporting them.

Extract and use Juniper static route communities

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LocalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LocalRouteTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java

* Add toBuilder() method for Connected, Local, and BGP routes.
* Note: toBuilder() is currently unimplemented for other types for routes (not in the critical path of RibGroups)
* Add tests for route types mentioned above.

Begin work on toBuilder() for routes.

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-interface-ribgroup-with-transformation

Applying a rib group to interface routes now performs full routing policy processing, which
allows transformations (not just filtering).
cc: @corinaminer

ibdp: Allow policies with transformations when applying ribgroups

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Pruner.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/BidirectionalTrace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/BidirectionalTracePruner.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/PrunerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/BidirectionalTracePrunerTest.java

Generalize TracePruner, and then instantiate for a new BidirectionalTrace class. Eventually can migrate the old TracePruner to the new framework too.

Generic Pruner and Pruner for BidirectionalTraces

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4

Keeping the one that allows for `routing-options aggregate route <prefix>` with no `roa_common` token.
cc: @arifogel -- let me know if there's some reason to ever have duplicate definitions.

Remove duplicate definition of roa_route

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RoutingProtocol.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchProtocol.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchProtocolTest.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cisco/IsisRedistributionPolicy.java
projects/question/src/main/java/org/batfish/question/NodesQuestionPlugin.java

Workaround to allow routing policies to match on "isis"

MatchProtocol: expand ISIS_ANY to multiple protocol values

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpProtocol.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpProtocolTest.java

The enum value for `IpProtocol.IPComp` contained lowercase letters making `IpProtocol.fromString` fail to resolve that value since `fromString` converts its input to uppercase before calling `valueOf`

IPComp -> IPCOMP

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java

MED is a non-transitive attribute (for eBGP) and must not be
re-advertised.
Fix to advertise to iBGP peers only.
cc: @haverma

Fix eBGP MED propagation

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/Breadcrumb.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java

Split out HopContext (now FlowTracer) and Breadcrumb from TracerouteEngineImplContext.
Trying to more cleanly define the roles of these classes:
- TEIC provides information about the network needed to run traces.
- FlowTracer does the actual work of tracing the network.
- FlowTracer still needs some refactoring, but it's getting better.
HopContext was a bad name because *Context implies "just data" -- no
methods other than accessor-like things.

refactor traceroute 4/?

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Result.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChain.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/FirstMatchChain.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyReferenceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChainTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/FirstMatchChainTest.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/symbolic/AstVisitor.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/TransferBDD.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/TransferSSA.java
tests/parsing-tests/unit-tests-nodes.ref

DisjunctionChain took a list of routing policies and returned true for a route if any of them matched and accepted (otherwise evaluated default policy and returned that result). That behavior may be useful somewhere, but the only place it was being used was for chained Juniper BGP import and export policies (e.g. `set protocols bgp import [ POLICY-1 POLICY-2 POLICY-3 ]`). In that context, the correct behavior is to return the result of the first policy that matches the route, whether it accepts or rejects (and if none match, return default policy result as before).
This PR turns DisjunctionChain into FirstMatchChain, which matches those semantics.

DisjunctionChain -> FirstMatchChain

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TopologyTest.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/symbolic/Graph.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
tests/aws/topology-example-aws.ref
tests/basic/topology.ref

- Remove _interfaceEdges. All clients actually want interface node/
interface pairs. This change simplifies client code and saves bunch of
useless copying work.
- Make Topology immutable. prune now returns a new topology, rather than
mutating this.
- Move Topology.pruneFailedIpsecSessionEdges to
IpsecUtil.computeFailedIpsecSessionEdges.

Clean up Topology

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/BidirectionalTrace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/BidirectionalTracePrunerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/BidirectionalTraceTest.java
projects/question/src/main/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswerer.java
projects/question/src/test/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswererTest.java

Group bidirectional traces by forward/reverse flow and sessions
(established by the forward flow/used for the reverse flow). This makes
it easier to see range of multipath behavior, including any multipath
inconsistency.

Make multipath in bidirectional traces more apparent.

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/RuleEndpoint.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-groups-nested
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-object-group-inheritance

Dumping Palo Alto configs puts address group/object definitions at the end of the file - after they may have been referenced.
This PR adds support for referencing these groups/objects even if not yet declared.

Palo Alto address obj support

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RouteAdvertisementTest.java

RouteAdvertisement does not have any methods that rely on its generic being an AbstractRoute, so changed it to RouteAdvertisement\<T\> instead of RouteAdvertisement\<R extends AbstractRoute\>. While I was at it, also removed redundant field `_withdraw`.

Untie RouteAdvertisement from AbstractRoute

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/HeaderSpaceMatchesTest.java

- Ensure all the appropriate match conditions in HeaderSpace are actually checked in `matches()`
- Clean up implementation of `matches()` for protocol matching
- Clear out a bunch of white space

Clean up and test HeaderSpace.matches()

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParseTreeWalker.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/ThrowableMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishParseTreeWalkerTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

Before:
```
org.batfish.common.BatfishException: Exiting due to parser errors
at org.batfish.main.Batfish.serializeNetworkConfigs(Batfish.java:3381)
at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:3537)
at org.batfish.main.Batfish.repairVendorConfigurations(Batfish.java:2955)
at org.batfish.main.Batfish.loadParseVendorConfigurationAnswerElement(Batfish.java:1897)
at org.batfish.main.Batfish.loadParseVendorConfigurationAnswerElement(Batfish.java:1882)
at org.batfish.main.Batfish.repairConfigurations(Batfish.java:2836)
at org.batfish.main.Batfish.parseConfigurationsAndApplyEnvironment(Batfish.java:1692)
at org.batfish.main.Batfish.loadConfigurations(Batfish.java:1682)
at org.batfish.main.Batfish.loadConfigurations(Batfish.java:1639)
at …
```

output suppressed exceptions during parse tree walk with haltOnParseError

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetric.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface-delay
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface-speed
tests/aws/nodes-example-aws.ref
tests/parsing-tests/unit-tests-nodes.ref

Fix delay and bandwidth for tunnel interfaces on Cisco and add tests. Add tests for loopback delay and bandwidth.
@dhalperi

Fix and test loopback, tunnel delay and bandwidth

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/FilterStep.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInput.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java
projects/batfish/src/test/java/org/batfish/z3/MockSynthesizerInput.java
projects/batfish/src/test/java/org/batfish/z3/state/visitors/DefaultTransitionGeneratorTest.java

Filters traffic after the incoming transformation, similar to how
preOutgoingTransformationFilter filters traffic before the outgoing
transformation.
Includes support in traceroute, BDD reachability, and NoD reachability.
@dhalperi @anothermattbrown

Add a postIncomingTransformationFilter

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/ModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/ModelingUtilsTest.java

- Creating `NetworkFactory` once and using throughout to prevent name clashes
- Using `BatfishLogger` instead of `Warning` as that is what is used in `Batfish.java`

Model utils fixes 1/2

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java

- Check invariants using checkArgument on public methods and assert on
private methods.
- Rewrite findOrCreateNode, remove findHelper

Simplify PrefixTrieMultiMap and check invariants

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java

- Remove unused public methods
- Do not expose internals (i.e. subtrees). Instead, expose a traversal
method.
- Avoid extra copying in IpWildcardSetIpSpace.Builder
- Avoid extra copying in RibTree:getMatchingIps

more clean up of PrefixTrieMultiMap

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java

This fixes a potential crash, indirectly:
* if a device has no interfaces with IPs, it will not appear in `_interfaceOwnedIps`
* when get the owned IP space for such interfaces, there's a NPE
We could replace the `.get(hostname)` with `.getOrDefault(hostname, Empty)`, but the
proposed change here is probably more efficient. Thoughts?

ForwardingAnalysis: only look for IPs owned by interfaces that have IPs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java

- Now that we don't expose subtries to clients, we can factor out the
nodes as private implementation.
- Follow standard map interface idioms.
- Allow adding new nodes at the root (either directly or indirectly).

Factor out PrefixTrieMultiMap.Node

---

projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddressBookEntry.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddressBookEntry.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-zone-address-book-attach-and-global
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-zone-address-undefined

On encountering undefined address-book entries, warn and handle to prevent undefined references in future processing.

Handle Juniper missing address-book entry

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParseTreeWalker.java

Update `BatfishParseTreeWalker` exception messages to be consistent

Make BatfishParseTreeWalker exceptions consistent

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowHistory.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
projects/question/src/main/java/org/batfish/question/loop/DetectLoopsAnswerer.java
projects/question/src/main/java/org/batfish/question/multipath/MultipathConsistencyAnswerer.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java
projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererTest.java
tests/basic/traceroute-1-2.ref

This reverts #3150 so traceroute trace ordering can be redone more sanely

Revert "Clean up FibImpl methods; add test (#3150)"

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java

`FibImpl.getNextHopInterfaces()` now returns a non-sorted set, but when its return value is used to iterate through interfaces to generate traceroute traces, it gets sorted first. That way the traces are still in order of next hop interface.

FibImpl cleanup (replacing #3150)

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/parsing-tests/unit-tests.ref

This is valid configuration as users may instead set local-as on every BGP session.
If a session has no local AS then we'll show that in other way (like
BgpSessionStatus).
You can also see warnings in the ref file right next to the deleted ones about specific peers without local AS.

Juniper: don't warn if global local-as is not set

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java
projects/coordinator/src/main/java/org/batfish/coordinator/QueuedWork.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkDetails.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/WorkBean.java
projects/coordinator/src/test/java/org/batfish/coordinator/QueuedWorkTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkDetailsTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

- Stop replacing WorkItem names with resolved IDs
- Now only contains user-provided information
- Store ID-based work info in WorkDetails
- Builder-based
- Contains IDs for network, snapshot, referenceSnapshot, analysis,
question
- Now mostly use just IDs in work queue management instead of names

clean up workitem handling and queueing

---

WORKSPACE

After the first commit fixing the omitted line, you'll see the warning mentioned in that commit.
Then resolve the warning, but not by forcing icu4j for antlr4, but actually deleting the antlr4 rule since we don't actually use it. (We just link against runtime)

Fix WORKSPACE

---

README.md

Added 'including' to the sentence `By Batfish in automation workflows, network engineers can close this gap and ensure that only correct changes are deployed.`

Added missing word to sentence

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Anchor.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/CommonParser.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Completion.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/IpWildcardAstNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/PotentialMatch.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/CommonParserTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/TestParser.java

A bunch of things, some trivial some not so trivial:
1/ Rename Completion annotation to Anchor
1/ Rename UsefulPointInPath to PathAnchor
2/ Rename PartialMatch to PotentialMatch
3/ Auto completion now considers only strict prefixes, i.e., "10" is not auto completed to "10"
4/ Put the TestParser defined in two places in its own class that is shared
5/ For error reporting, search for anchors from top to bottom. For auto completion, search for anchors bottom to top. So 
- when `1.1.1` is supplied as input, the error is `Error parsing '1.1.1' as IpSpace after index 5. Valid continuations are IP_PREFIX or IP_WILDCARD or IP_RANGE or IP_ADDRESS.`
- when `1.1.1` is auto completed, we get suggestions as `.` (next char for any prefix), `.1/32` (matching prefix in snapshot) and `.1` (matching ip …

Tweak parser

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoAsaNat.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoAsaNatUtil.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

Adds basic support for ASA object NATs without policy routing. If NAT
rules specify interfaces for packets which differ from the FIB, they
will be transformed but routed incorrectly.
@dhalperi @anothermattbrown

Partial support for ASA Object NAT in VI model

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Nat.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatPool.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NoPortTranslation.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PatPool.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PortAddressTranslation.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-nat-pat

Adds grammar for PAT feature forJuniper.
In the grammar:
1. Changes nat_pool to handle port range definition 
2. Changes natp_addresss to handle port change in dest nat
3. Adds no-translation to support source nat without PAT
VS model
1. Updates Nat and NatPool to support port range

parser for PAT

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-eigrp

EIGRP network masks on ASA are inverted as compared to EIGRP on IOS. Similar to OSPF.
'passive-interface' is configured with interface aliases instead of canonical interface names on ASA.
@dhalperi

Fix EIGRP config on ASA

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/z3/state/PreOutInterfaceDeliveredToSubnet.java
projects/batfish/src/main/java/org/batfish/z3/state/PreOutInterfaceExitsNetwork.java
projects/batfish/src/main/java/org/batfish/z3/state/PreOutInterfaceInsufficientInfo.java
projects/batfish/src/main/java/org/batfish/z3/state/PreOutInterfaceNeighborUnreachable.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/GenericStateExprVisitor.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/Parameterizer.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactorySourcesTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

Create new states for after we determine that a flow will be forwarded
out an interface leading to an ARP failure disposition, but before the
outgoing filters and transformation have been applied.
This is needed for bidirectional reachability, which needs to know the
flows each transformation is applied to.

New BDD reachability states for ARP failure dispositions.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java

Next hop interface was being set incorrectly during propagation and is also unnecessary, since EIGRP routes cannot have an independently configured next hop interface.
@dhalperi @progwriter

Remove next hop interface from EIGRP routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSet.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSetTest.java

The main use of this class right now is in IOS-XR, which according to
docs is a union.
This is for an open source user who is trying to use juniper as-path. The extraction for that
will come in the next PR, but I didn't want to introduce a crash before implementing.

ExplicitAsPathSet: implement

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseTransformationRanges.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseTransformationRangesImpl.java
projects/batfish/src/main/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitor.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseTransformationRangesImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/MockBDDReverseTransformationRanges.java
projects/batfish/src/test/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitorTest.java

When we invert a transformation, we need to constrain its range to be
within the input flows we applied to the original (forward)
transformation. Otherwise, applying the reverse transformation will give
us transformed reverse-direction flows that do not correspond to any
forward flow. BDDReverseTransformationRanges computes the range of each
inverted transformation.

Compute the ranges of reversed transformations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Fib.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibEntry.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FibEntryTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockFib.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java

Benefits:
* Single source of truth
* New saner get + FibEntry API instead of maps
* Support for longest prefix match
* No need to store pointer to RIB
I also need this for FBF, otherwise everything is just too damn coupled to traceroute implementation.
Note:  in the interest of incremental work , I am not touching traceroute or forwarding analysis in this pr.

Implement FIB as a prefix trie

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java

The public longestPrefixMatch method now uses this to ensure that it
returns the elements of the longest matching prefix that has elements.

add findLongestPrefixMatchNonEmptyNode

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactoryImpl.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactoryImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/MockBDDReverseFlowTransformationFactory.java

When we setup a session with NAT, the reverse-flow transformation is
determined by the forward-flow transformation (that was applied to the
initiating flow). BDDReverseFlowTransformationFactory creates
BDD reachability Transitions for reverse flow transformations.

Construct the reverse flow transformations for sessions with NAT.

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MemoizedIpAccessListToBdd.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java

Some devices (e.g. juniper) allow transformation guards to use IpSpaceReferences. They're already supported in traceroute, this PR adds support for them to BDD reachability.

allow IpSpace references in transformation guards

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
questions/stable/routes.json
tests/questions/stable/routes.ref

Since we no longer split bgp best paths and multi-path ribs.

Remove bgpMP as a valid rib parameter in routesQuestion

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/AsPathSetElem.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSet.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSetTest.java

Based on my experience, it's pretty hard to implement regex-based matching on
AS Paths where they are represented as space-separated strings (e.g., `"1 2
3"`).
The reason is optional fields:
- `".* 3"` should match the above but also `"3"`.
- `"1 .*"` should match the above but also `"1"`.
- `".* 2 .*"` should match the above but also `"2"`.
- `"1 2 3"` should match `"1 2 3"`.
and more.
The issue is around leading/trailing space with optional fields. E.g., you want
to translate `"1 .*"` to something like `"1( \d+)*"`, but you also want to
translate `".* 3"` to `"(\d+ )*3"`. In one case, the odd space out is before
the wildcard, in another it's after. Neither `"1"` nor `"3"` need leading
spaces here, but translating the regex `"1 2 3"` to the pattern `"1 2 3"`, we
do need to add spaces. …

ExplicitAsPathSet: fix implementation and add comments

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Action.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/ActionVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/BoolExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/BoolExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Drop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookup.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FlowEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/If.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/PacketMatchExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/PacketPolicy.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Return.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Statement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/StatementVisitor.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/DropTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FibLookupTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/IfTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/PacketMatchExprTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/PacketPolicyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/ReturnTest.java

Implement the datamodel (and simple evaluation) of very basic policy statements needed for Policy-based Routing.
This is intentionally not plugged into anything yet.

PacketPolicy: VI skeleton

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThen.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenAccept.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenDiscard.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenNextIp.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenNextTerm.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenNop.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenRoutingInstance.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwThenVisitor.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatement.java
projects/batfish/src/test/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatementTest.java
tests/parsing-tests/unit-tests-nodes.ref

Updates Configuration and the Interface model to remove RoutingPolicy in favor of a pointer to PacketPolicy.

Plug in packet policy into VI configuration

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

Today, Juniper produces interfaces of type VLAN that are active but have no VLAN ID set. I'm not sure this is right.
The TopologyUtil does not guard against this, so can hit a null pointer exception.
Opening this PR with relevant code changes, need a discussion to see right fix.

Topology: prevent crash on vlan interface with no vlan id

---

projects/allinone/BUILD
projects/allinone/src/test/java/org/batfish/question/traceroute/TraceroutePolicyBasedRoutingTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

* The policy-based pipeline preempts regular ingress filter
* Fib lookups can occur in a different VRF

Policy-based routing in traceroute engine

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java

Support `enter([ref.interfacegroup(sea, host-iface)])`

compat bug fix

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java

Allow the results to be memoized, if a MemoizedIpSpaceToBDD is being used.

IpSpaceToBDD: use visitor for inner conversions

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java
projects/batfish/src/main/java/org/batfish/z3/NodContext.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkNodeRolesResource.java

Remove unnecessary intermediate collections
* `.collect(toSet()).stream()` -> `.distinct()`
* Use `Collectors.joining` where appropriate instead of list and then string utils
* Use `flatMap` where appropriate instead of list and then .stream()
* Use `.count()` instead of `.collect().size()`
And make a double-negative in BgpTopologyUtils much clearer.

Stream cleanups throughout

---

projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersQuestion.java
projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersQuestionTest.java

NodesSpecifier (really old one) is buried deep into our psyche. I'll send a series of small PRs (at least at first) to move us off it.

migrate testfilters to use grammar-based nodes input

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

- Add unsupported warning for `neighbor 1.2.3.4 filter-list ...`. Filter-lists should have an impact on BGP import/export policies and they currently don't.
- Add comment in extraction method for `neighbor 1.2.3.4 distribute-list ...` to ensure that when support is added for distribute-lists, it is correctly implemented to be mutually exclusive with `neighbor 1.2.3.4 prefix-list ...` (see note about distribute-lists [here](https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/5816-bgpfaq-5816.html#anc3); also linked in comment).

 Cisco BGP policy extractions: warning and comment

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/PotentialMatch.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserFilterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserNodeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java

When the autocomplete match is `abc` and the user has already typed `ab`, return `abc` as the suggestion instead of just `c`. In playing around with this stuff, it is more useful for the clients to see this. No other semantic change.

return full token

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Fib.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockFib.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/FibEntryMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/FibEntryMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/ExitPoint.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/ExitPointTest.java

1. Stop using RIBs in traceroute computation, move to FIBs
2. Stop using and deprecate some FIB APIs that use maps of maps of maps
3. Stop doing meet-in-the-middle resolution in traceroute. Just get all FIB entries, then group them as desired (which is by exit point: combination of ARP IP and Interface)

Traceroute: move off of RIB

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java

It was showing up on cpu profiling when creating bgp route builder (which we do a lot) and was a really easy fix.

Make AsPath.empty() a singleton

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDFirewallSessionTraceInfo.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactoryImpl.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseTransformationRanges.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReverseTransformationRangesImpl.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactoryImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseTransformationRangesImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/MockBDDReverseTransformationRanges.java

The ranges of return-pass sessions depend on the session's out interface and next-hop. In particular, the range should be limited to return-pass flows corresponding to forward-pass flows that entered the session node on that interface, coming from that hop.

Separate reverse pass transformation ranges by session out interface and next hop.

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/NatPool.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-nat-vrf

A Juniper nat pool belongs to a routing instance. One can configure it by "et security nat source pool POOL routing-instance R1", otherwise a nat pool belongs to the default routing instance. A nat can use any pools no matter what routing instance it belongs to, so we only need to correctly parse the command and extract the information to vs model. 
1. Add `_owner` to `NatPool`
2. Trace all pools in a `RoutingInstance`
3. Parse the specific command above

Add routing instance as owner to nat pool in vs model

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/srx-testbed.ref

* drop incorrect `+` from grammar
* be consistent: either have subrules or literals, but not both
* add warnings with message for unsupported netscreen options we could/should support
* stop warning about netscreen options related to rate, as Batfish does not model that.

Juniper: cleanup TCP netscreen grammar and warnings

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

They're all statistics-based, and Batfish does not model that.

Juniper: stop warning on UDP netscreen options

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/srx-testbed.ref

Same as #3312 , for ICMP.
Reword the message to include the type (ICMP/TCP/etc.)

Juniper: cleanup ICMP netscreen grammar and warnings

---

WORKSPACE
projects/allinone/pom.xml
projects/batfish-client/pom.xml
projects/batfish-common-protocol/pom.xml
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/pom.xml
projects/coordinator/pom.xml
projects/pom.xml
projects/question/pom.xml

- static varargs methods in org.hamcrest.Matchers now have @SafeVarargs, which
fixes Eclipse warnings
- remove now-unnecessary @SuppressWarnings("unchecked") in
PrefixTrieMultimapTest

upgrade java-hamcrest:2.0.0.0 to hamcrest:2.1

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-list

Generates a BGP import policy for peers with an import prefix-list configured. Until now, those prefix-lists were extracted but ignored.
Follow-up work:
- Get the prefix-list name to appear in the generated import policy's sources
- Support peers that use both an inbound route-map and an inbound prefix-list (right now we use the route-map and ignore the prefix-list)

Cisco prefix-lists for BGP imports -> VI model

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructured_net.g4
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipStructureType.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/Trunk.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_interface_references
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_trunk
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_trunk_references
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_vlan
tests/parsing-tests/networks/unit-tests/configs/f5_bigip_structured_net
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

- fix bug where every vlan's settings was applied to all interfaces

Implement F5 trunks (aggregate interfaces)

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java

This prevents NPE when an interface has no IP.

Juniper: don't try to generate transformations without an interface IP

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsBgpPoliciesTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-list

Adds a MatchPrefixList to BGP export policy for peers with an export prefix-list configured. Until now, those prefix-lists were extracted but ignored.
Follow-up work:
- Get the prefix-list name to appear in the generated export policy's sources
- Support peers that use both an outbound route-map and an outbound prefix-list (right now we use the route-map and ignore the prefix-list)

Cisco prefix-lists for BGP exports -> VI model

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/networks/unit-tests/configs/ios_bgp
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

- fix bug where unhandled dummy peer groups failed to properly maintain
IPv6 context

Fix IPv6 detection for IOS flat BGP neighbors

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-default-originate/configs/originator
tests/aws/nodes-example-aws.ref

For generated routes spawned as a result of `neighbor a.b.c.d default-originate`, we were attaching a generation policy that effectively required the source node to have a default route in order to send the generated default route to its neighbor. In reality, the source node sends the generated default route unconditionally unless there is a route-map explicitly configured for it. Fixed by removing the generation policy we were creating in the absence of a route-map.

Remove default generation policy for default-originate route

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

Stuff I managed not to blob into #3180.
- Delete unused GenericRib method `getPrefixes()`
- Remove `AbstractRoute.getTypedRoutes(Prefix p)` as it was only used once; just use `getTypedRoutes()` and filter instead
- Favor `getTypedRoutes()` over `getRoutes()` in places where it doesn't matter which is used, because typed routes are memoized (`getRoutes()` has to stream and recollect)
- Big pile of test simplification and cleanup

Backlogged cleanup from RIB work

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

Enable conversion of packet policies to BDDs.
Since so far packet policies don't support transformations, we can
efficiently compact them into BDDs corresponding to dropped packets
and packets forwarded per VRF.
not plugged in anywhere yet

Implement PacketPolicyToBDD

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Old warning message was the generic "This feature is not currently supported". Now it will say "Unsupported feature: no-redistribution" to indicate that other features configured on the same line are supported.

Add message to no-redistribution parse warning

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java

Leftover after #3357 
`prefixes` is no longer extractable, so removed from MockRib and the builder.

MockRib cleanup

---

projects/batfish/src/main/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysis.java

was BiMap before. The mapping isn't always injective, and we no longer
need the inverse mapping anyway.

change forward-pass term state to return-pass orig state to Map

---

projects/question/src/main/java/org/batfish/question/lpmroutes/LpmRoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/lpmroutes/LpmRoutesQuestion.java
projects/question/src/main/java/org/batfish/question/lpmroutes/LpmRoutesQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/lpmroutes/LpmRoutesAnswererTest.java
questions/stable/lpmRoutes.json
tests/questions/stable/commands
tests/questions/stable/lpmRoutes.ref

Allows running longest prefix match for a given IP on the main RIBs of
all nodes/vrfs
The `rib` parameter is for now hidden from the template. Needs more changes to DP interface to get the right RIBs.

Add an LpmRoutes question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java

Use static methods to make forwarding analysis more readable. In
particular, this allows us to see the dependencies between all the
methods that make up forwarding analysis. Also let us simplify the test
by passing arguments to the methods under test directly, rather than
creating a dummy forwarding analysis object with the right fields.

Clean up ForwardingAnalysisImpl

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockForwardingAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java

ForwardingAnalysis currently assumes that only the VRF that owns an
interface can forward traffic out that interface. Route-leaking and PBR
violate that assumption. This change (at least partially) removes it.

Prepare ForwardingAnalysis for route-leaking and PBR

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/NssaSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/NssaSettingsMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/NssaSettingsMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ospf-no-redistribution/configs/ios-abr
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ospf-no-redistribution/configs/ios-abr-no-redistribution
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ospf-no-redistribution/configs/ios-area-0
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ospf-no-redistribution/configs/ios-area-1-nssa
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Also adds extraction for Cisco `no-redistribution` to use this new infrastructure.

OSPF NSSA setting to suppress type 7 LSAs

---

projects/question/src/main/java/org/batfish/question/switchedvlanproperties/SwitchedVlanPropertiesAnswerer.java
projects/question/src/test/java/org/batfish/question/switchedvlanproperties/SwitchedVlanPropertiesAnswererTest.java

More efficient and simplifies code.

SwitchedVlanProperties: create NodeInterfacePair only once

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java

Because of VRF leaking (and policy-based routing) compute dispositions
top-down: from the FIBs and the interfaces they point to.

Forwarding analysis: adjust for VRF leaking

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpType.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIpProtocol.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDIntegerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDRepresentativePickerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDRoute.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/TransferBDD.java
projects/batfish/src/main/java/org/batfish/z3/BDDIpAccessListSpecializer.java
projects/batfish/src/test/java/org/batfish/bddreachability/SessionInstrumentationTest.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/TransferBDDTest.java
projects/batfish/src/test/java/org/batfish/z3/BDDIpAccessListSpecializerTest.java
projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswererTest.java

Preconditions on BDDInteger's methods value, leq, and geq were off-by-one. This meant that we were using invalid arguments for several BDDIntegers, causing silent failures. 
To fix BDDRoute.prefixLength, we need to allocate 6 bits instead of 5 (since 32 is a valid value).
To fix BDDPacket.ipProtocol, icmpCode, and icmpType, add a wrapper classes that correctly interpret the special value (outside the valid range of the underlying BDDInteger) for each class corresponding to unconstrained.

Fix BDDInteger preconditions 

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

No functional changes. Confirmed routes results are the same on a large & complex ospf network.

Remove staging RIBs for OSPF

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EdgeMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EdgeMatchersImpl.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java

Robustness in presence of:
- One-sided layer-1 edges
- Inconsistent availability of layer-1 information
- Incorrect/unusable layer-1 information

Incomplete Layer-1 Topology Handling

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

This reverts commit 92237cb98464cac5a8dcdbdd795a3404308ab878.
RIBs aren't synchronized. :facepalm:

Revert "Remove staging RIBs for OSPF (#3398)"

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacePropertySpecifierTest.java

Return the name of the ACL/filter and not the contents

InterfaceProperties: return incoming filter name

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

Fixes a bug where the main RIB could end up with multiple OSPF external routes to the same prefix with different costs to advertiser.
This happened because the OSPF RIB cleared its external routes at the beginning of each new iteration, so when a new external route was merged into the OSPF RIB in `unstageOspfExternalRoutes()`, the resulting delta would never have a `REPLACE` advertisement. That delta is then merged into the main RIB, so if the main RIB already had an OSPF external route that matched the new route's destination and metric, it wouldn't get replaced.

Preserve OspfRib external routes across IBDP iterations

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_eigrp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/networks/unit-tests/configs/cisco_eigrp
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Taking over #3240 that @mkremerbbn was working on.
Same content, with exception of making weights non-optional and linking to a doc. Could not find an example where weights are optional.

Grammar for EIGRP metric weights

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MemoizedIpSpaceToBDDTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceDereferencerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceDescriberTest.java
projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRenamerTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/visitors/IpSpaceBooleanExprTransformerTest.java

AclIpSpace is one source of perf issues. Simplify it during building when
possible -- especially single-entry AclIpSpaces are fairly common.
Secondly, cache the hashCode on demand, as for large AclIpSpaces hashing can
be expensive, and we stick them in maps.

AclIpSpace: simplify input, cache hashCode

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SubRange.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
projects/batfish/src/main/java/org/batfish/datamodel/transformation/TransformationEvaluator.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatRuleSetTest.java
projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswererHelper.java

If the IP Protocol in question does not have them.
FWIW, I ran all unit tests in IntelliJ to make sure no `@Nonnull` annotations collided.

Flow: allow src/dst port to be null

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java

In practice, all JsonCreators should not be publicly accessible, but this is not
always the case. Take the ones where we've abused JsonNode for backwards compat
and ensure they are at least private and deprecated so that we get errors if
anyone tries to call them directly.

Deprecate select JsonCreators

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/AutoAs.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchIp6AccessList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchIpAccessList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedAsPathSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedCommunitySet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedPrefix6Set.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedPrefixSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/CallStatement.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChainTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSetTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/FirstMatchChainTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchProtocolTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/NamedCommunitySetTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassfulTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/PrependAsPathTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/AsPathRegexTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsBgpPoliciesTest.java

Remove Configuration and Vrf from the environment. Instead, store the parts of those that we actually need. Now the Environment builder factory method initializes the builder by setting the properties that come from config and vrf.

cleanup Routing policy environment

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/CommonParser.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/CommonParserTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java

When suggesting names that need escaping (via double quote), make sure that the suggestion includes the quotes.

escape suggested names when needed

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java
tests/aws/nodes-example-aws.ref
tests/parsing-tests/networks/unit-tests/configs/cisco_bgp
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

Currently every BGP peer with default-originate configured gets its own generated default-originate export policy. However, these policies only vary based on address family and configuration format. Now each configuration will have at most two default-originate export policies (one for IPv4 peers and one for IPv6).

Cisco BGP default-originate export policies

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
projects/question/src/test/java/org/batfish/question/ospfproperties/OspfPropertiesAnswererTest.java
tests/parsing-tests/unit-tests-nodes.ref

processId should always be set, as a precursor to supporting multi-ospf-process setups.

OspfProcess: enforce presence of processId

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java

This field is initialized but unused; its setter and getter are also unused. It was originally intended for tracking process-level default-originate routes, but (for Cisco) those are added to each peer's generated routes during conversion rather than modifying the BgpProcess.

Delete unused field BgpProcess._generatedRoutes

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/PotentialMatch.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/TestParser.java

The string literals suggested will be in canonical case independent of what the user entered. 
Before: autocomplete suggestion for 'tc' was 'tcP'
Now: autocomplete suggestion for 'tc' is 'TCP'
Includes #3444 
cc: @arifogel

canonical case for string literal suggestions

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java

Running `del-network` when a network exists returns 200 OK not 204 OK. Thus, an error message should only be printed if the status code is not 200 OK.

Fix handling of successful del-network

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java

- computeArpRepliesByInterface: handle case when nothing is forwarded
out an interface.
- computeInterfaceArpReplies: exclude null_interface from the map.
- interfaceHostSubnetIps: don't group by VRF.
- computeDeliveredToSubnet: base map on arpFalseDestIps; remove
nested-map intersection.
- Delete nested-map intersection; inline merge into union.
- Enforce equal key sets in nested-map union

Clean up forwarding analysis

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java

No functional changes, just a conglomeration of cleanups:
-  In Cisco BGP conversions:
- standardize generation policy names
- rename `generateAggregateConditions` -> `exportAggregateConditions`, as the conditional is a test for whether to export the generated route, not whether to generate/activate it
- use `RoutingPolicy.builder()` to make RoutingPolicy creations more readable
- In BgpProtocolHelper, use BgpRoute builder properly

Cleanup along BGP pipeline

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDRepresentativePicker.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

1. More instrumentation of bdd loop detection;
2. Instead of constructing `BDDFlowConstraintGenerator` each time `BDDPacket.getFlow` is called, add a BDDFlowConstraintGenerator field in `BDDPacket` to reduce overhead.

Optimize get representative flows from bdd

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/BgpGroup.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp_disable
tests/parsing-tests/networks/unit-tests/configs/juniper_bgp_disable
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

For now, disabled BGP processes will be left out of the VI model entirely, as per option 1 in #3443.

Juniper: parse and extract BGP top-level disable

---

projects/batfish/src/main/java/org/batfish/symbolic/smt/EncoderSlice.java

OSPF redistribution variables should only be included in the SMT formulation if OSPF EXPORT variables exist for at least one interface. If OSPF does not export on any interfaces, then the redistribution variables for that interface will not appear in any predicate. Consequently, the solver will produce counterexamples with arbitrary values for the redistribution variables.

Fix OSPF redistribution in SMT formulation

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java

Implemented the same under the hood.
Fewer copies.
Better interface.

BDDReachability: use Table instead of nested Maps for transitions

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/main/java/net/sf/javabdd/MicroFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TestBDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TypedBDDFactory.java

The old code would mysteriously interpret this as a number divided by 100. No idea why.
Caches were starting at size 10000 nodes 1000 cache entries, then being shrunk to 3 at the first resize (20000/6400 = 3).

BDDFactory: fix type signature of setCacheRatio to be less confusing

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-disable
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-interface-disable
tests/parsing-tests/networks/unit-tests/configs/juniper_ospf_disable
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

If `disable` is configured at the process level:
`set protocols ospf disable`
then the OSPF process is not created at all.
If `disable` is configured at the interface level:
`set protocols ospf area 0.0.0.0 interface ge-0/0/1.0 disable`
then the VI model remains the same except the existing field `Interface._ospfEnabled` is set to false. 
This matches the observed behavior documented [here](https://docs.google.com/document/d/1Xzzv579yhB0g-eypep8I8OZSfhhNEKvsRmdpBJ8MbMQ):
>OSPF is disabled on an interface if either the interface or the process has `disable` command configured.
Continues progress on #3443.

Juniper: disable for OSPF process and interface

---

projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

- Add counters for trivial node operations (l==r) that do not touch cache
- Update access to ignore trivial ops, restoring cache hits+missed=total
- Add counter for opCache overwrite, and deploy it
Sample results for building forwarding analysis:
```
Cache statistics
----------------
Unique Trivial: 27705
Unique Access:  572666
Unique Hit:     163143
Unique Miss:    409523
Unique Chain:   331855
=> Hit rate =   0.28488332
Operator Hits:  3454151
Operator Miss:  600069
Operator Overwrite:  580177
=> Hit rate =   0.85198903
Swap count =    0
```

BDDFactory/JFactory: improve caching stats

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraintsUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsUtilTest.java

* Fix bug where we were setting types twice
* Default to ICMP ping when constructing flows.

PHC: fix ICMP codes, add reasonable Flow defaults

---

projects/bdd/BUILD
projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java

* Add simplifications for constant arguments to all the operators, and more simplifications.
* For symmetric binary operators (`and`,`xor`,`or`,`nand`,`biimp`,`nor`), enforce a canonical order to move all equivalent entries into same cache cell.
* For asymmetric binary operators, rewrite inverse (`revimp`, `less`) into forward direction (`imp`, `diff`) to move all equivalent entries into same cache cell.
Minor impact on FA construction, bigger impact on some larger (but nondeterministic right now :/) queries that are hard to compare.

JFactory: some more BDD optimizations

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

We don't use ITE enough for it to merit its own cache. Instead, merge them
together and double the cache size.
Running detectLoops on a large network, this change did not affect results at all
compared to just doubling the cache size but keeping both.

BDD: merge ITE and APPLY caches

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfigId.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfNeighborConfigIdTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswerer.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java

For proper topology establishment in the presence of multiple OSPF processes.

OspfNeighborId: take into account processId

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

Instead, use the operator with internal negation in the two places we referenced this map.
Essentially no impact in BDD state size, but all metrics in the right direction and fewer BDDs created overall. But we get to drop this one entire map from persistent memory.
```
Cache statistics
----------------
Unique Trivial: 14110681 -> 14109414 (smaller <0.01%)
Unique Access:  33620640 -> 33604204 (smaller <0.05%)
Unique Hit:     9540881 -> 9539061 (smaller <0.02%)
Unique Miss:    24079759 -> 24065143 (smaller <0.06%)
Unique Chain:   18707611 -> 18697435 (smaller <0.01%)
=> Hit rate =   0.28378046 -> 0.2838651
Operator Hits:  8024079 -> 8022574 (smaller <0.02%)
Operator Miss:  47399068 -> 47381354 (smaller <0.04%)
Operator Overwrite:  44781680 -> 44763946 (smaller <.04%)
=> Hit rate = …
```

BDDReachabilityAnalysisFactory: delete _vrfNotAcceptBDDs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java

Make fields final and remove setters.
Make fields nonnull and add annotations to getters.
Reorder member variables in semantic groups.
Make hashCode and equals iterate fields in same order.
Simplify hahsCode and equals based on non-nullity.

BDDPacket: minor cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/ModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/ModelingUtilsTest.java

Batfish preserves the Interface name case so that is still case sensitive

Make hostname in Isp conf case-insensitive

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterLine.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/RouteFilterLineTest.java

It's convenient to just have a line that permits all prefixes.
Added some tests while I was at it.

Add PERMIT_ALL to RouteFilterListLine, do minor cleanup

---

projects/question/src/main/java/org/batfish/question/FilterQuestionUtils.java
projects/question/src/main/java/org/batfish/question/comparefilters/CompareFiltersAnswerer.java
projects/question/src/main/java/org/batfish/question/comparefilters/CompareFiltersQuestion.java
questions/experimental/compareFilters.json
tests/questions/experimental/commands
tests/questions/experimental/compareFilters.ref

1. Add ignoreComposites flag, copied from filterLineReachability.json
2. Fix a bug in current/reference configs confusion. The issue stemmed from passing around
redundant sources of truth that could conflict. Rewrote the code to prevent such confusion.

CompareFilters: add ignoreComposites, fix reference bug

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfProcessTest.java
projects/question/src/test/java/org/batfish/question/ospfprocess/OspfProcessConfigAnswererTest.java

Keys must match the area number stored in OspfArea

OspfProcess: enforce correctly initialized areas

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
projects/batfish/src/test/java/org/batfish/job/FlattenVendorConfigurationJobTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/hierarchical
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-brackets

1. Recognize newer RANCID which uses vendor-specific comments.
2. Relax _firstChar=# to mean juniper -- too broad.
3. Update tests to support recognition.

Cleanup juniper format detection

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteUtilsTest.java

When a flow is applied PAT, the session should remember the transformation so that the return flow can be transformed correctly.

Add PAT in session transformation in traceroute for return flows

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/ExtendedAccessList.java
projects/batfish/src/main/java/org/batfish/representation/cisco/StandardAccessList.java

Will make for cleaner code in forthcoming distribute-list PR.

Nonnull annotations for Cisco ACL fields

---

questions/experimental/bidirectionalTraceroute.json
tests/questions/experimental/bidirectionalTraceroute.ref
tests/questions/test_questions.py

This PR adds `orderedVariableNames` to bidirectional traceroute to match the ordering in regular traceroute.

Add ordered variable names to bidirectional traceroute

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

We do not think this is safe and we also think it is unnecessary and
hurts performance.

BDD: disable finalizer

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserErrorListener.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java
projects/batfish-common-protocol/src/test/antlr4/org/batfish/grammar/recovery/RecoveryLexer.g4
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishLexerErrorListenerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishParserErrorListenerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/NonRecoveryCombinedParser.java
projects/batfish-common-protocol/src/test/resources/org/batfish/grammar/non_recovery_lexer_error
projects/batfish-common-protocol/src/test/resources/org/batfish/grammar/non_recovery_parser_error

- Don't silently drop errors when disableUnrecognized is true
- New behavior approximates what recovery does by adding error nodes

Robust parser and lexer non-recovery error behavior

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/bdd/BasicTests.java

This makes replace significantly faster. correctify calls are cached in
the replacecache, so we need to disambiguate with replace calls. Replace
doesn't use the entries' b field, so we mark replace calls by storing -1
in b. Correctify stores a node id in b, which is always >= 0.

cache bdd_correctify.

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Otherwise newly allocated caches will be sized to the initial
cache size until a nodes resize.

JFactory: update cachesize on resize

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java

This should make OSPF process self-contained and prepare us to flip the bit to the new process in ibdp.

OspfProcess: add external route processing

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfRedistributionTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-redistribute-default-route/configs/arista_advertiser
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-redistribute-default-route/configs/ios_receiver

Unlike Cisco, Arista allows redistributing of default routes into OSPF via `redistribute <protocol>` command

Arista OSPF default route redistribution

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java
projects/coordinator/src/main/java/org/batfish/coordinator/ServiceObjectMapper.java

* Update `verboseMapper` to no longer print pretty JSON
* This is used for service v2 APIs
Previously, listing containers would result in:
```
> curl -XGET --header "X-Batfish-Apikey: 00000000000000000000000000000000" --header "X-Batfish-Version: 0.36.0" http://localhost:9996/v2/containers
[ {
"name" : "network",
"testrigs" : [ ],
"analysis" : null
} ]
```
now, it results in:
```
> curl -XGET --header "X-Batfish-Apikey: 00000000000000000000000000000000" --header "X-Batfish-Version: 0.36.0" http://localhost:9996/v2/containers
[{"name":"network","testrigs":[],"analysis":null}]
```
Fixes #3607

Return compact JSON from v2 service

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceTest.java
tests/parsing-tests/unit-tests-nodes.ref

Makes `union(union(a, b), c)` equivalent to `union(a, b, c)` instead of nested.

AclIpSpace: flatten if possible during union

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationIpSpaceSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/LocationIpSpaceSpecifierTest.java
projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswererHelper.java

Necessary protections were already in place it seems for Testfilters and Traceroute. I tinkered with error messages. 
@anothermattbrown - based on a quick look, it seemed that reachability and searchfilters would do the right thing. could you please double check?

do not throw an exception in locationipspecifier

---

projects/coordinator/src/main/java/org/batfish/coordinator/resources/QuestionResource.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/QuestionsResource.java

Split `QuestionResource` into its own class, out of `QuestionsResource` (similar to how we handle network and snapshot resources)

Refactor question resource

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/networks/unit-tests/configs/nxos_interface
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Mark unsupported for now, implementation pending.

Cisco_interface.g4: add parsing for nxos route-pref and tag inline

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ibgp-no-update-source/configs/r1
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ibgp-no-update-source/configs/r2
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java

Allows active peers with null local IPs into the established BGP topology. This fixes a bug where sessions between two active iBGP or eBGP multi-hop peers would not come up if one peer was missing a local IP, even though the other peer should still be able to initiate a session.
This change broke assumptions in BDP that BGP peers' local IPs would be nonnull, so added nonnull head and tail IPs to BgpSessionProperties. BDP now uses BgpSessionProperties as source of truth for endpoint IPs.

Endpoint IPs in BgpSessionProperties

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java

Fixes issue where active peers can appear compatible with active remote peers missing their local IP when the remote peer's node does not own the local peer's remote IP.

BGP topology: cross-check with IP owners consistently

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/parsing/BUILD
projects/batfish/src/main/java/org/batfish/grammar/cisco/parsing/CiscoBaseParser.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa_interface_encapsulation_vlan

Support Cisco ASA subinterface vlan declaration

---

projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/F5BigipImishParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/F5BigipImish_access_list.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/F5BigipImish_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/F5BigipImish_common.g4
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/parsing/BUILD
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/parsing/F5BigipImishBaseParser.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/PrefixList.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/PrefixListEntry.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/RouteMap.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/RouteMapEntry.java
tests/parsing-tests/networks/unit-tests/configs/f5_bigip_imish_malformed
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

- validation for imish parser
- use correct integer sizes
- avoid passing tokens to conversion functions in imish extraction
- remove unnecessary validation during extraction

F5 BIG-IP parsing fixes and validation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java

Doesn't seem important to include `null` in the set of collected cluster IDs, because `ClusterIdsSupplier.get()` is only called once, and that's to check if the set has any cluster ID in common with another set that can't include `null`.

Fix NPE when BGP cluster ID is null

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java

This helps reduce memory pressure when computing dataplane on certain networks

OspfRoutingProcess: collect to set

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java

As far as I know BGP is the only protocol that supports tie breaking based on route arrival order.
Now that there is only one type of BgpRib (see #2596), logical clocks (which are used for tie breaking) do not need to be present in all RIBs.
This reduces the number of hash maps we maintain and bookkeeping we do, thus reducing memory consumption (and possibly giving us a tiny computational speedup)

Ribs: move logical clock to BgpRib only

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-portchannel-subinterface

Give them correct type so that they are not disabled for lack of dependencies.
Note: this does not add a bind dependency to the parent interface (future work)

Cisco: properly identify portchannel subinterfaces

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RoutingProtocol.java

Necessary to successfully generate data plane (no data plane support for BGP unnumbered yet).
Default costs based on https://support.cumulusnetworks.com/hc/en-us/articles/202917918-Routing-Preferences

BGP admin cost defaults for Cumulus

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionAnswerer.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionQuestion.java

No point in converting String to SessionType only to immediately convert back to String. No functional change.

Simplify BgpSessionQuestion.matchesType()

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPassivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java

- Rename `canConnect()` methods to be more obvious
- Move one of them to `BgpPeerConfig` since it's useful for all BGP peers, not just dynamic
- Simplify `BgpTopology.bgpCandidatePassesSanityChecks()`

Small BGP peer config & topology changes

---

projects/coordinator/src/main/java/org/batfish/coordinator/resources/AnswerResource.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/AnswerResourceTest.java

* Update `getAnswer` to use `filterAnswer`-style input validation
* Make error codes consistent (404 for non-existent snapshot)

Make new answer APIs consistent

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsBgpPoliciesTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/arista-originator
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/ios-listener
tests/aws/nodes-example-aws.ref
tests/parsing-tests/unit-tests-nodes.ref

In the line:
`neighbor 10.1.1.2 default-originate route-map ROUTE_MAP`
Cisco uses `ROUTE_MAP` as a generation policy, but Arista instead applies it to the (unconditionally) exported default route (see [Arista's documentation](https://www.arista.com/en/um-eos/eos-section-32-4-bgp-commands#ww1116958) and [notes from GNS3](https://docs.google.com/document/d/1KFCT8ckUYOza4dVFMQ87XutsQWDKT_5UONngfA-eXJw) for details). Currently Batfish always converts the route-map to a generation policy. This PR makes it add the route-map to the default route export policy instead if on an Arista device.
The default route export policy can now vary per peer again, so we're back to creating one default route export policy per default-originating peer, except for NXOS, which still creates one default route …

Arista BGP default-originate route-map

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/arista-originator-undefined-rm

[Confirmed](https://docs.google.com/document/d/1KFCT8ckUYOza4dVFMQ87XutsQWDKT_5UONngfA-eXJw/edit#heading=h.eqvs8hr9omtl) that if the route-map is undefined here, the default route is exported as if no route-map were configured.

Remove TODO after confirming behavior

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_bgp_no_address_family
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

Adds a ref test where `bgpVrf.getIpv4Unicast()` is null, which results in a parse failure due to a null pointer exception on master. Fixes `toBgpProcess()` to avoid the NPE.

 Don't assume Cumulus BGP IPv4 address family is nonnull

---

projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/ParseWarningMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/ParseWarningMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-vs-ios-warnings/configs/arista-ospf-redistribute-bgp
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-vs-ios-warnings/configs/ios-ospf-redistribute-bgp

Creates a separate parse rule for Arista BGP redistribution into OSPF.
Arista syntax for redistributing BGP into OSPF is:
`redistribute bgp`
whereas Cisco vendors require an ASN:
`redistribute bgp 65100`
Both vendors allow configuring an optional route-map for BGP redistribution, but Cisco vendors also allow other options such as setting metric, metric-type, subnets, or tag.

Arista parsing for BGP redistribution into OSPF

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/Community.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/LargeCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/StandardCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/LargeCommunityTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/StandardCommunityTest.java

1. Of course we put communities into a whole bunch of sorted sets, so making comparable.
2. Default JSON parsing to standard communities, to avoid breaking user-facing APIs (e.g., testPolicies question)
3. Add utility methods to StandardCommunities such as getting long/high/low values.

BGP Communities: make comparable, keep backwards-compatible parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseStatus.java
projects/question/src/main/java/org/batfish/question/initialization/InitIssuesAnswerer.java
projects/question/src/main/java/org/batfish/question/initialization/IssueType.java
projects/question/src/test/java/org/batfish/question/initialization/InitIssuesAnswererTest.java

Add issues to `initIssues` question for files with non-passing parse statuses that don't explicitly generate warnings or exceptions (e.g. `UNKNOWN`).
For example:
Fixes #3561

Add parse status issues to initIssues question

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_bgp_no_router_id
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_bgp_no_router_id_or_loopback_ip
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests.ref

If no router ID is explicitly configured for a BGP process, use the address of the loopback interface as the router ID. This only works if the loopback interface has a configured network:
`net add loopback lo ip address 1.2.3.4/32`
It is also possible to configure the loopback without an explicit network, and this PR does not infer a BGP router ID for that case:
`net add loopback lo`

Infer BGP router ID from loopback if present

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/PathElement.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/PotentialMatch.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/PathElementTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/PotentialMatchTest.java

Adding the entire path to the PotentialMatch class, which would (later -- not this PR) enable us to do context-sensitive autocompletion. 
This PR covers the first modification in this doc:
https://docs.google.com/document/d/1h1dGp7fN_4nIfXVxUzCIdB-hvRHeH9oW1poyIc3x-fU/edit#

Track potential match path

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java

For question-specific BGP route, still accept the class field.
And fix a typo

BgpRoute: JSON backwards compatibility

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java

Helps reduce memory pressure in certain scenarios.

Intern OSPF routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java
projects/question/src/main/java/org/batfish/question/bgpproperties/BgpPeerConfigurationAnswerer.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpPeerConfigurationAnswererTest.java

Adds a local interface column. Unnumbered peers have local interface, but null local and remote IP; other peers have null local interface.

Update BgpPeerConfiguration to show unnumbered peers

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpProcessPropertySpecifier.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpProcessConfigurationAnswererTest.java

The `Neighbors` column schema is just a set of strings, so it was straightforward to add the interface names for unnumbered peers.

Unnumbered peers in BgpProcessConfiguration answer

---

projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

While I was at it, also switched the values in the local and remote IP fields to use the `BgpSessionProperties` head and tail IPs instead of the local IPs of the `BgpPeerConfigId`s. Also deleted helper method `getBgpEdgeRow()`, which took in all the exact values that were going to go into the row, so calling it wasn't really shorter than just creating the row in place.

Edges question: include BGP unnumbered edges

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
tests/parsing-tests/unit-tests-nodes.ref

Extract the simplification/finalization logic from Cisco and move it to ConvertConfigurationJob
so that it applies to all vendors.

Configuration: move finalization from VS to CCJ

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java

It's a fairly complex object, no need to create it per-comparison.

AbstractRoute: create the comparator once

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnnotatedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcard.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NodeInterfacePair.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfigId.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopology.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java

* Shortcut expensive comparator for self-comparison.
* `Objects.equals(NotNull, NotNull)` -> `a.equals(b)`
* Box less

Misc simplifications

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java

For geq:
1. Merge the two for loops, which is safe.
2. Inline the acc = greater[i].org(eq[i].and(acc)) line in each branch
3. Replace eq[i] and greater[i] in each branch, then simplify away:
* zero or X -> X
* x or notX and y -> x or y
4. Delete eq[i] and greater[i] collections.
And similar, but different, for leq

BDDInteger: simplify geq, leq

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPrefix.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDIntegerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java
projects/batfish/src/main/java/org/batfish/symbolic/bdd/TransferBDD.java

Adds `bddint.range(a, b)` which is equivalent to `bddint.geq(a).and(bddint.leq(b))`.
Internally, there are two differences:
1. Short-circuit `a == b`
2. Save work in the case where `a` and `b` have a common prefix.

BDDInteger: add range helper and use it

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java

If an error occurs during autocomplete, `WorkMgrService.autoComplete` would catch it and return a `failureResponse` and would fail to capture the validation info (to a user this will look like a valid input). That error is now being handled deeper in the stack so that validation info will still be captured and sent to the user

handle autocomplete parse errors

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java
projects/batfish/BUILD
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TopologyContext.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TopologyContextTest.java

Fixes an NPE when DP is loaded from disk and then we asked for an L3 topology.

Make TopologyContext non-transient in dataplane

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java

This PR limits the number of suggestions per suggestion type to show a variety of different suggestions. For example if a snapshot has a hundred nodes, the node name suggestions will no longer drown out suggestions of other types

limit number of autocomplete suggestions by suggestion type

---

.buildkite/pipeline.sh
projects/BUILD

Use the `manual` tag to make this target only build if you invoke it directly. Gets around the
issue until Bazel has better java11 support.

Bazel: sickbay javadoc for real

---

projects/batfish-common-protocol/pom.xml

Fix a build warning.
Also, use the alphabet so it's less likely we have to do this again.

batfish-common-protocol: remove duplicate commons-lang3

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AnnotatedRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/ConnectedRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EigrpExternalRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EigrpInternalRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EigrpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisLevelRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/KernelRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/LocalRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType2Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfInterAreaRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfIntraAreaRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RipInternalRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RipRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/StaticRib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java

1. Make backup routes manipulation private to the RIB and automatic on merge/remove
2. Do not rely on SortedSet in any way.
Note: This does not attempt to fix any incorrectly-initialized RIBs inside DP. Tested to ensure this has no behavior changes on a large complex network.

RIB: fix backup routes logic

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TopologyContext.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TopologyContextTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

- remove edge blacklist
- only use node and interface blacklists to disable interfaces upon
configuration deserialization

Cleanup blacklists

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteDecorator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnnotatedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/KernelRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LocalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
tests/parsing-tests/unit-tests-vimodel.ref

* Routes across protocols have no meaningful ordering
* Removes confusion as to whether comparator can be used for route preference in RIBs (it cannot).
* Reduce potential bugs where I our comparators where potentially not consistent with equals
* Keep comparators that *are* consistent with equals for route types that we put into the datamodel/refs (static, kernel, generated).
Note: the existing ref change is just an order swap.

Remove comparable from AbstractRoute

---

projects/batfish/src/main/java/org/batfish/representation/host/HostInterface.java
projects/batfish/src/test/java/org/batfish/grammar/host/HostInterfaceTest.java

- useful for modeling VXLAN networks with trunks

Enable setting encapsulation VLAN on host interfaces

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

In the interest of incrementality (and easier review), this is not meant to be a complete overhaul; just moving around some variables to start.
No functionality changes, all logic still lives in VirtualRouter

ibdp: start splitting out BgpRoutingProcess

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java

Undo part of #3864 because apparently that slows things down

RibDelta: skip collectors in favor of performance

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java

1. use Ip as its own cache, so we have fewer boxed longs to keep track of.
key and value will be same object, but that's just fine.
2. delete unused functions.
3. short-circuit getNetworkAddress

Ip: internal cleanups

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsSet.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

- Using an internal array will result in less boxing globally
- Switch to a LoadingCache for simpler code.

AsSet: switch to array internally
