batfish/batfish

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpRange.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpRangeTest.java

IpRange describing IP space between two IPs

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RouteDependencyTracker.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType2Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java

* Favor RibDelta.empty()
* No need to keep pointer to parent RIB
* Note some optimization possibilities for RibDeltas
* Add some tests, cleanup some tests

Move away from nullable RibDeltas in ibdp

---

.buildkite/pipeline.sh

These are all a minute faster than the slow step, so should still not be the critical path

pipeline.sh: combine multiple fast maven steps

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/CrossVrfEdgeId.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/BgpRibGroupsTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/CrossVrfEdgeIdTest.java

* Allow cross-vrf route leaking
* Implement (basic) support for RIB groups applied to BGP neighbors

ibdp: Implement RIB groups for BGP

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/TracerouteEngine.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HopMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HopMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/question/src/test/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswererTest.java

Also factored out duplicated code in traceroute engine, misc cleanup

Use sessions in traceroute engine.

---

projects/batfish/src/main/java/org/batfish/job/BatfishJobResult.java

Still spinning off minor changes from parsing branch.

BatfishJobResult: improve annotations

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

- Removing redundant local variables
- Moving more stuff into TransmissionContext
- Factor forwardOutInterface out of processHop
Coming:
- Move steps into TransmissionContext
- Move methods into TransmissionContext
- Move TransmissionContext to its own file
- ...

refactor traceroute 1/?

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

This one's smaller: rename TransmissionContext, move steps into it

refactor traceroute 2/?

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

refactor traceroute 3/?

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

Since multiple flows are traced in parallel, sharing breadcrumbs among
all flows cause false positives in the loop detection.
Also checked the invariant that the number of breadcrumbs equal the
number of hops when processHop is called.

Move breadcrumbs to HopContext

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Trace.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java

- Made _vrfName a field.
- Move ACCEPT, NO_ROUTE checks before LOOP
- factored out buildRoutingStep
- factored out buildOriginateStep
- ...

Misc FlowTracer refactorings

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/IpProtocolSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpProtocolSpecifierTest.java

Design doc: https://docs.google.com/document/d/13s4kucEC7GqN7bz7DaigPnXr45v2LHQRIH95W4tBGik/edit#

Add insertionIndex to AutocompleteSuggestion

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java

Found this exception in a stack trace:
```
Got exception in checkTasks: java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at org.batfish.coordinator.WorkQueueMgr.getWorkForChecking(WorkQueueMgr.java:354)
at org.batfish.coordinator.WorkMgr.checkTasks(WorkMgr.java:389)
at org.batfish.coordinator.WorkMgr.access$000(WorkMgr.java:167)
at org.batfish.coordinator.WorkMgr$AssignWorkTask.run(WorkMgr.java:200)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at …
```

WorkQueueManager: add guardedby/synchronized

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/Edge.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddSourceConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/EraseAndSet.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveSourceConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactorySourcesTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java

Rebase Edge on Transition, add new transitions for adding/removing source constraints.

clean up bdd reachability analysis factory

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInput.java
projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationExpr.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationStepExpr.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationTransitionGenerator.java
projects/batfish/src/main/java/org/batfish/z3/state/PostInInterfacePostNat.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/GenericStateExprVisitor.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/Parameterizer.java
projects/batfish/src/main/java/org/batfish/z3/state/visitors/StateVisitor.java
projects/batfish/src/test/java/org/batfish/z3/MockSynthesizerInput.java
projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java
projects/batfish/src/test/java/org/batfish/z3/expr/TransformationTransitionGeneratorTest.java
projects/batfish/src/test/java/org/batfish/z3/state/visitors/DefaultTransitionGeneratorTest.java

Support incoming Transformations and preTransformationOutgoingFilter in NoD reachability.
@dhalperi @anothermattbrown

Incoming Transformations in NoD reachability

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifierTest.java

@takmiz this fixes your issue.

InterfaceSpecifierFilterSpecifier: skip null filters

---

projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

- Interfaces are generated from vlan declarations, not from self declarations
- update refs

fix interface generation for F5

---

projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceSpecifierInterfaceLocationSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceWithConnectedIpsSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NodeSpecifierInterfaceLocationSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceInterfaceGroupInterfaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/RoutingProtocolSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ShorthandInterfaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/VrfNameRegexInterfaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ZoneNameRegexInterfaceSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/DispositionSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceAddressGroupIpSpaceSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/RoutingProtocolSpecifierTest.java
projects/batfish/src/test/java/org/batfish/specifier/IpSpaceSpecifierTest.java
projects/batfish/src/test/java/org/batfish/specifier/LocationSpecifierTest.java

The only really crazy one was in RoutingProtocolSpecifier.

Specifiers: apply immutable set

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java

Added `public` accessibility for some of the methods in BfCoordWorkHelper.
@dhalperi

Public accessibility for BfCoordWorkHelper

---

projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java

- rename so it will actually get run
- fix assertions (assertTrue only run if necessary)
- fix types

ParserIpSpaceTest: cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/AssignPortFromPool.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/PortField.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStepVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FlowDiffTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/transformation/AssignPortFromPoolTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java
projects/batfish/src/main/java/org/batfish/datamodel/transformation/TransformationEvaluator.java
projects/batfish/src/main/java/org/batfish/z3/expr/TransformationTransitionGenerator.java
projects/batfish/src/test/java/org/batfish/datamodel/transformation/TransformationEvaluatorTest.java

Adds support for PAT in VI model:
1. Adds a new AssignPortFromPool class and related visitors
2. Updates FlowDiff to include port changes
3. Updates TransformationStep and TransformationEvaluator for PAT

Yifei pat vimodel

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java

- BDDFiniteDomain._varBits should always contain the bits of the
variable if there are any.
- Include all sources in BDDSourceManager.getSourceBDDs()
- Add BDDSourceManager.allSourcesTracked()
- Add LastHopOutgoingInterfaceManager.existsLastHop()

Small tweaks to BDDFiniteDomain and its clients.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Field.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/FieldTest.java
questions/experimental/traceroute.json
tests/questions/experimental/traceroute.ref

In preparation of using the new grammars ....

Field type

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/parsing-tests/unit-tests.ref

Was implemented in batfish/batfish#2770 among others.

Juniper: remove invalid warning about source NAT

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java

Delete unused fields related to BGP advertisements

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfPropertySpecifier.java
projects/question/src/main/java/org/batfish/question/ospfprocess/OspfProcessConfigurationAnswerer.java
projects/question/src/main/java/org/batfish/question/ospfprocess/OspfProcessConfigurationQuestion.java
projects/question/src/main/java/org/batfish/question/ospfprocess/OspfProcessConfigurationQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/ospfprocess/OspfProcessConfigAnswererTest.java
questions/experimental/ospfProcessConfiguration.json
tests/questions/experimental/commands
tests/questions/experimental/ospfProcessConfiguration.ref

Note: (cc @saparikh ) This question almost looks like a subset of the `OspfProperties` question but I guess we are planning to deprecate that.

OSPF process configuration question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplIntegrationTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/aws/nodes-example-aws.ref
tests/basic/neighbors.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/outliers2.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref
tests/roles/perRoleOutliers.ref

Let VI model handle statically configured ARP Ips:
1. Change `_additionalArpIps` to 'IpSpace`
2. Make Ips in `_additionalArpIps` arpable in `ForwardingAnalysisImpl`

Yifei nat arp

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplIntegrationTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/aws/nodes-example-aws.ref
tests/basic/neighbors.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/outliers2.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref
tests/roles/perRoleOutliers.ref

This reverts commit 751fb4077fc02d36fafa5e63bf3bcfb57fcf1b77, because that PR breaks interface properties.

Revert "Yifei nat arp (#3248)"

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/CanonicalAcl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/IpAccessListLineIndex.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/IpAccessListRenamer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ShorthandFilterSpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/FiltersSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ShorthandFilterSpecifierTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/DifferentialIpAccessListTest.java
projects/batfish/src/test/java/org/batfish/datamodel/acl/IpAccessListRenamerTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererTest.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersTest.java

Move off ComparableStructure and unify equals/hashCode.

Fix ip access list equality

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java

While debugging another issue, came across these cleanups.

PropertySpecifier: cleanups from IntelliJ

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java

These uses of `checkArgument` both constructed the error string (expensive!) unconditionally, even if the check passed.
While we're there, go ahead and cache the keys upon creation, make the class and properties final.

Row: remove a lot of stupid performance bugs

---

projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java
projects/batfish/src/main/java/org/batfish/bddreachability/SessionInstrumentation.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddNoLastHopConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Constraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveLastHopConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveSourceConstraint.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
projects/batfish/src/test/java/org/batfish/bddreachability/EdgeMatchers.java
projects/batfish/src/test/java/org/batfish/bddreachability/EdgeMatchersImpl.java
projects/batfish/src/test/java/org/batfish/bddreachability/SessionInstrumentationTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/TransitionMatchers.java
projects/batfish/src/test/java/org/batfish/bddreachability/TransitionMatchersImpl.java

A BDD reachability analysis graph instrumentation for sessions. Adds
new edges and constraints to existing edges to process session flows
correctly.

session instrumentation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java

Use union to simplify the case of 0, 1, or 2 IpSpaces.

ForwardingAnalysisImpl: simplify computeArpTrueEdge

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

In our stress test, this reduces from 47s (your not-yet-merged PR) to 21s

BDDReachabilityAnalysisFactory: memoize

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcard.java

Continuing my crusade to eliminate usages of Pair
Sadly I still had to make IpWildcard comparable because we stick it in sorted sets all over the place

IpWilcard: do not extend Pair

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java

Simplify clear in PrefixTrieMultiMap

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcard.java

Because CiscoConversion does some most bizarre casting and it results in
runtime nulls whre there shouldn't be any. The horror.
This reverts commit 5da1ce9b80cc98f9baa447bc6c0b0f59bcc3bc66.

Revert "IpWildcard: do not extend Pair (#3289)"

---

projects/question/src/main/java/org/batfish/question/ospfarea/OspfAreaConfigurationAnswerer.java
projects/question/src/main/java/org/batfish/question/ospfarea/OspfAreaConfigurationQuestion.java
projects/question/src/main/java/org/batfish/question/ospfarea/OspfAreaConfigurationQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/ospfarea/OspfAreaConfigurationAnswererTest.java
questions/experimental/ospfAreaConfiguration.json
tests/questions/experimental/commands
tests/questions/experimental/ospfAreaConfiguration.ref

- Deliberately leaving out no-summary field from the table as not sure if that is correctly populated in `StubSettings.java` and `NssaSettings.java`

Adding OSPF area configuration question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix6Space.java
projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
projects/pom.xml

Maven: upgrade pmd and checkstyle

---

projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructured_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/BgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_bgp_router_id_auto
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_bgp_router_id_manual
tests/parsing-tests/networks/unit-tests/configs/f5_bigip_structured_net_routing_bgp
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

- Use manually-specified router-id if present
- Otherwise use highest interface IP

F5 BGP router-id computation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnnotatedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprWithProvenance.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresAnswerer.java

- silences eclipse warnings about raw casts

remove raw casts

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java

This reverts commit 4d88a344a8c401d81bf9946536091a0107b77927.
Instead, just default to an empty HashMap.

Revert "Make best paths immutable in BgpRib (#3275)"

---

projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswerer.java
projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityQuestion.java
projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
questions/experimental/ospfSessionCompatibility.json
tests/questions/experimental/commands
tests/questions/experimental/ospfSessionCompatibility.ref

Not including any columns for Session status since table only contains successful sessions for now

Adding OSPF session compatibility question

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java

Check all conditions that prevent a VI BGP peer from being created before generating any policies:
- peer is inactive/shutdown
- peer has no remote AS
- peer is IPv6
Functional changes:
- Import policy and default route export policy were previously generated independent from the conditions listed above
- Export policy and default route generation policy were previously generated as long as the peer was active and not shutdown
- If a peer has a default originate route-map configured...
- ...but that route-map is undefined, we will now generate the default `defaultRouteGenerationPolicy` instead of leaving the default route's generation policy unset
- ...and the peer is IPv6, we will now set that route-map as the generation policy for `defaultRoute6` instead of `defaultRoute`
Since we now …

Cisco: Avoid generating policies for inactive BGP peers

---

projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerer.java
projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestion.java
projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestionPlugin.java

more removals

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/GeneratedRouteHelper.java

No functional changes, just making things more readable.

Generated routes code cleanup

---

projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java
projects/batfish-client/BUILD
projects/batfish-client/pom.xml
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/BaseSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureEquivalenceSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/FileBasedIdResolver.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/job/BatfishJobExecutor.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/symbolic/answers/FlowHistory.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionAnswerer.java
projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java

Suggest reviewing commit-by-commit.

CommonUtil: move code called in only one place out

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledFilterSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledInterfaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledIpSpaceSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledLocationSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledNodeSpecifierFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserFilterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserNodeTest.java

FooExpression/Expr -> FooSpec
FooSpecifier -> FooFunc

bring rule names in line with grammar documentation

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NodeSpecifierInterfaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/AstNodeVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/InterfaceAstNodeVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/InterfaceLocationAstNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/InterfaceWithNodeInterfaceAstNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledInterfaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/NodeSpecifierInterfaceSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledInterfaceSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledIpSpaceSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledLocationSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java

Mini rationale doc: https://docs.google.com/document/d/1qDFRkIszgiCGtFxWQqsvXijJl8Yao8OrLXdhSSV7p1Y/edit#heading=h.ucnywmicjpgf

allow nodes in interface specifier

---

.buildkite/pipeline.sh

Goal: more visibly understandable builds

Buildkite: more emoji

---

projects/batfish/src/main/java/org/batfish/symbolic/bdd/TransferBDD.java
projects/batfish/src/test/java/org/batfish/symbolic/bdd/TransferBDDTest.java

clean up and test TransferBDD::isRelevantFor(BDDRoute, PrefixRange)

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPrefix.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPrefixTest.java

- isPrefix
- inPrefixRange
- permittedByRouteFilterList

BDDPrefix and related operations

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java

To reduce intermediate BDDs that will not be in the final BDD, we should build
BDDs leaf-to-root. Make HeaderSpaceToBDD follow this order.
Also makes the inner TCP flags processor follow this order.

HeaderSpaceToBDD: build BDDs in better order

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java

@VisibleForTesting, unused -> private, no annotation
can be static -> static

HeaderSpaceToBDD: cleanup signatures

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java

We need to rewrite this class entirely, but this is a big improvement for now.

Row: temporarily cache string form

---

projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/BDDBitVector.java
projects/bdd/src/main/java/net/sf/javabdd/BDDDomain.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/main/java/net/sf/javabdd/MicroFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TestBDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TryVarOrder.java
projects/bdd/src/main/java/net/sf/javabdd/TypedBDDFactory.java
projects/bdd/src/test/java/net/sf/javabdd/bdd/BDDTestCase.java
projects/bdd/src/test/java/net/sf/javabdd/bdd/BasicTests.java
projects/bdd/src/test/java/net/sf/javabdd/bdd/IteratorTests.java
projects/bdd/src/test/java/net/sf/javabdd/trace/TraceDriver.java
projects/bdd/src/test/java/net/sf/javabdd/trace/TraceSuite.java

Each commit is pretty minor.
Had to break into two PRs to get reviewable to do commit-at-a-time.

Bdd cleanup 1/2

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

No functional changes, but makes my head hurt less.

ibdp OSPF: Rename things so code is readable 1/?

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AndExprTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/MatchSrcInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/NotExprTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/OrExprTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/PermittedByAclTest.java
projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java
projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java

Use static method variants instead

Flow: fix visibility of new Builder

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructured_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/BgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_bgp_neighbor_update_source
tests/parsing-tests/networks/unit-tests/configs/f5_bigip_structured_net_routing_bgp
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

- try to use interface IP when update-source does not provide usable
information

fix F5 BIG-IP update-source computation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/AbstractionBuilder.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
projects/question/src/test/java/org/batfish/question/ospfproperties/OspfPropertiesAnswererTest.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

In the VI model store the name of the OSPF process in the process itself

OSPF process: store name

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/AbstractionBuilder.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
projects/question/src/test/java/org/batfish/question/ospfproperties/OspfPropertiesAnswererTest.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

This reverts commit 8668e2eba3f757438b6ed53748366eac99d70276.
Because I'm dumb and we already had `processId`

Revert "OSPF process: store name (#3431)"

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

1. it's okay to create an analysis with no actions, no need to throw in ACCEPTED.
2. variable names / comments.

BDDReachabilityAnalysisFactory: simplify loop handling

---

questions/Parameters.md

application, ip-protocol, routing-policy grammar

Update grammar doc

---

projects/question/src/main/java/org/batfish/question/loop/DetectLoopsAnswerer.java

DetectLoopsAnswerer: add determinism using flow min

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java

IpSpaceToBDD: use the new diff operator

---

questions/Parameters.md

Closes #3460 
@anothermattbrown - need your help with the TODO in there. 
(Thank you, @dgarros, for the suggestions.)

mention resolvers and interfacelinklocation-/32 interaction

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java

Add tests and sanity checks, and fix a bug that happens when calling merge with asymmetric maps.

ForwardingAnalysisImpl: document and fix interface inactiveness

---

projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/parsing-tests/networks/unit-tests/configs/juniper_interfaces
tests/parsing-tests/unit-tests-nodes.ref
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

* Active (enable/disable)
* MTU
* Native VLAN ID
Fix #3442

Juniper: add more fields that can be set at the physical level

---

projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserNodeTest.java

picked from old notebook examples:  https://docs.google.com/document/d/1qDFRkIszgiCGtFxWQqsvXijJl8Yao8OrLXdhSSV7p1Y/edit#heading=h.ipo1ak2z15nb

more tests for backward compatibility

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java

IpWildcardSetIpSpace: cache hash code

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

Move Load Configurations to single place, add a few for other heavy ops

Batfish: more spans

---

projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Or.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java

In case they are called recursively.

Transitions: simplify or and compose

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

If If -> If ElseIf
0/1 to BDDZERO/BDDONE

JFactory: style improvements

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Example output:
```
Garbage collection #9: 1280231 nodes / 545615 free / 0.033s / 0.351s total
Garbage collection #10: 1280231 nodes / 0 free / 0.053s / 0.404s total
Resizing node table from 1280231 to 2560457
Cache apply resize: 20011/20011 slots used
Cache ite resize: 0/20011 slots used
Garbage collection #11: 2560457 nodes / 0 free / 0.122s / 0.526s total
Resizing node table from 2560457 to 5120891
Cache apply resize: 40009/40009 slots used
Cache ite resize: 0/40009 slots used
Garbage collection #12: 5120891 nodes / 0 free / 0.298s / 0.824s total
Resizing node table from 5120891 to 10241771
Cache apply resize: 80021/80021 slots used
Cache ite resize: 0/80021 slots used
Cache apply reset: 160031/160031 slots used
Cache ite reset: 68980/160031 slots used
Cache quant reset: 0/157 slots …
```

JFactory: add cache use stats

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/AbstractionBuilder.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

* Trying to reduce dependencies on ConfigurationFormat in DP.
* Despite the general dislike of maps decided to go with that over 4 distinct fields.

Store admin distances in OSPF process

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java

Configuration and VRF: delete unused bgpAdvertisements and routes

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

JFactory: collect and comment flags

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Trace.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/TracePrunerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/TraceTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

Also add sanity checks on building Trace, and fix tests

FlowTracer: fix bug where session matches did not include EnterInputInterfaceStep

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfSessionPropertiesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java
projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java

Makes working with OSPF topology a little easier

Include area in the OSPF session

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfInterAreaRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfIntraAreaRouteTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/OspfProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java

* Do not share builder to avoid casts
* Json annotation cleanup
* Add some equality tests

Cleanup OSPF internal routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfPropertySpecifier.java

Not a property. And the schema as wrong too.

OspfPropertySpecifier: remove neighbors

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfigId.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopology.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfNeighborConfigIdTest.java
projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java

Precursor do updating neighbors and VI model

Make OSPF edgeId json-serializable

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/VendorFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cumulus/CumulusFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cumulus/InterfaceClagSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cumulus/package-info.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cumulus/CumulusFamilyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cumulus/InterfaceClagSettingsTest.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfaceClagSettings.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
tests/parsing-tests/unit-tests-nodes.ref

Cumulus vendor family in data model

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapMatchIpAccessListLine.java

No functional changes. This has been cluttering up my modified files.

Minor cleanup in Cisco files

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/DistributeList.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeList

Implementation based on conclusions drawn [here](https://docs.google.com/document/d/1QbNOZXn0Rk3qQ-J1_d0fN4Zo11ef7QMBjl_7gR0v260/edit?usp=sharing)

OSPF distribute list VS model and test

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/symbolic/abstraction/AbstractionBuilder.java
tests/aws/nodes-example-aws.ref
tests/basic/nodes.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref
tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
tests/parsing-tests/unit-tests-nodes.ref

Follow up to #3506, but for inter-area summary costs.

OSPF process: store IA summary admin cost

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcard.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationIpSpaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceAddressGroupIpSpaceSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/IpSpaceAstNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledIpSpaceSpecifier.java

Do these annotations make sense to you?

nonnull annotations for ip space computations

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

Rename ModelingUtils to IspModelingUtils
Lower case Internet and ISP hostnames

Isp modeling clean up

---

projects/allinone/allinone
projects/coordinator/coordinator
tools/common.sh

use default templatedirs with cli scripts

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java

Fewer intermediate strings, no trim

Hierarchy: cleanup pathString

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

Also avoid needlessly switching to node-serialized schedule

ibdp: simplify convergence conditions

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LongSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java

- needed for generalization of allowed remote-as numbers for peers

Add LongSpace to datamodel

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixList
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixListGlobal
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixListInterface
tests/parsing-tests/unit-tests.ref

- done only for distribute-lists using prefix-lists (considering the common use)

OSPF distribute list VI 

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/DynamicBgpTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

Now any pair of peers with an established session will have edges between them in both directions in the BGP topology.
[Design doc](https://docs.google.com/document/d/1N5-37ecfbHwEGs2qDKesItBptuUpuzcfrhokyaQGlNc)

Symmetric BGP topology

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java

This change was made in #3624, but wasn't necessary because the BGP topology had become symmetric in #3619.

Revert unnecessary change to BgpSessionStatusAnswerer

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
tests/basic/genDp.ref

This reverts commit 1d66cc764c304b87b3b44c78fd2ddf8d4089675e.
Until number of iterations is deterministic

Revert "Flip bit to new OSPF computation (#3616)"

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/MapMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/MapMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java

- allow assignment of address-based peer to peer-group without first specifying remote-as

F5 BIG-IP imish fix bgp peer-group assignment

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Future work to expose this and use it, but seems like a step in the right direction.

JFactory: reimplement count losslessly using BigInteger

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPassivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpUnnumberedPeerConfig.java

No functionality changes. Cleanup:
* remove @JsonPropertyDescription, replace with javadoc
* remove JSON creators from abstract class
* remove unused constants, fix javadoc links
* de-whitespace

Minor BgpPeerConfig cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/RouteDistinguisher.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/RouteDistinguisherTest.java

Add BGP route distinguisher

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpInterface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/eigrp/EigrpInterfaceTest.java

* Add java/json serialization
* Add tests

EigrpInterface: make serializable

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/TraceAndReverseFlow.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/question/src/main/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswerer.java
projects/question/src/test/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswererTest.java

and other misc cleanup in bidir traceroute

bidir tr: include new sessions in denied traces

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java

Reset non forwarding boolean in transform ospf route on import function

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java

Test that output for denied traces include sessions created by the trace

new FlowTracer test

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchSourceVrf.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchSourceVrfTest.java

Add JSON serialization for `MatchSourceVrf`

Add MatchSourceVrf JSON serialization

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AddCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/AddCommunityTest.java

Also do minor cleanup and tests

AddCommunity: do not crash on non-bgp routes

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java

This actually speeds up route merging in some cases.

RibDelta: singleton empty

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnnotatedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibEntry.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/CanonicalAcl.java

Copied the method from String#hashCode, which does not use volatile ints.

Cache more hashCodes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibEntry.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java

None volatile, inline more hashCode where there's lots of primitives, make serialized ones transient.

More hashCode cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType5RouteTest.java

Add EVPN Type 5 route

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType3RouteTest.java

for https://github.com/batfish/batfish/issues/3691

Add type 3 EVPN route

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Anchor.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/CommonParser.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserFilterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserNodeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserRoutingPolicyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java

1. No more suggesting '"' 
2. Updated hints to be more compact and align with documentation
3. Support for '[' (but not set operators yet)

misc improvements

---

WORKSPACE
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-common-protocol/BUILD
projects/batfish-common-protocol/pom.xml
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/AbstractClient.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/AbstractCoordinator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/PluginConsumerTest.java
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/pom.xml

* Delete serializeToText and xstream with it
* Catch more exceptions
* Delete some deprecated, unused helpers that we had for forwards-compat

Batfish: delete serializeToText option

---

WORKSPACE
projects/batfish-common-protocol/BUILD
projects/batfish-common-protocol/pom.xml
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
projects/pom.xml

simple ordering logic

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java

Standardize annotations with child classes as well.

Docs and annotations for AbstractRouteBuilder

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java

BgpTopologyUtils was trying to add self edges on BGP unnumbered peers configured for iBGP.

BGP topology: Prevent BGP unnumbered self-edges

---

projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java
projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

Batfish: load plugins on creation instead of at run

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/IpAccessListToBddTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/IpAccessListToBddVisitorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MemoizedIpAccessListToBddTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclExplainerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/explanation/ConjunctsBuilderTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/explanation/DisjunctsBuilderTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/normalize/AclToAclLineMatchExprTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysis.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseFlowTransformationFactoryImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformationToTransitionTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDAcl.java

Note that there are some semantic changes in this PR: forSources vs forInterfaces are
different with empty input. I believe they are correct.

BDDSourceManager: add empty and use it

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/networks/unit-tests/configs/juniper_security
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

This is for batfish/batfish#1237

Juniper: warn on destination-address-excluded

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

This is for batfish/batfish#1836

Cisco: warn on advertise-map or exist-map in BGP neighbor

---

projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java

Now the VI model edges will include BGP edges between unnumbered peers.

Use layer 2 topology for VI model BGP topology

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/networks/unit-tests/configs/cisco_bgp
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

This is for batfish/batfish#3230

IOS: warn on bgp redistribute-internal

---

projects/question/src/main/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationLoginAnswerer.java
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityRows.java
projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
projects/question/src/main/java/org/batfish/question/mlag/MlagPropertiesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
questions/stable/aaaAuthenticationLogin.json
tests/basic/filterLineReachability.ref
tests/basic/routes-dc-as-reuse.ref
tests/basic/routes.ref
tests/questions/stable/aaaAuthenticationLogin.ref

Still lots to fix, but hopefully this clears up more things that are wrong or hard to understand.

More question/answer metadata tweaks

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/Layer3VniConfig.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/EvpnAddressFamilyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/Layer3VniConfigTest.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
tests/parsing-tests/unit-tests-vimodel.ref

Something I missed in #3714, fixing

Add VNI identifier to L3VniConfig

---

questions/experimental/ospfAreaConfiguration.json
questions/experimental/ospfInterfaceConfiguration.json
questions/experimental/ospfProcessConfiguration.json
questions/experimental/ospfProperties.json
questions/experimental/ospfSessionCompatibility.json
tests/questions/experimental/ospfAreaConfiguration.ref
tests/questions/experimental/ospfInterfaceConfiguration.ref
tests/questions/experimental/ospfProcessConfiguration.ref
tests/questions/experimental/ospfProperties.ref
tests/questions/experimental/ospfSessionCompatibility.ref

along the lines of https://github.com/batfish/batfish/pull/3833/

Update long descriptions for OSPF related questions

---

questions/experimental/switchedVlanProperties.json
questions/experimental/vxlanVniProperties.json
tests/questions/experimental/switchedVlanProperties.ref
tests/questions/experimental/vxlanVniProperties.ref

Update long descriptions for `vxlanProperties` and `switchedVlanProperties` questions

Update descriptions for vxlan and switchedVlan questions

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CollectionUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CollectionUtilTest.java

Guava's ImmutableMap.copyOf() is too conservative for me.

CollectionUtil: start with toImmutableMap

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java

And use it instead of .build().isEmpty()

RibDelta.Builder: add isEmpty

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java

Prefix: get rid of a for loop, reuse some code

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java

In the process, I realized we only ever call `numWildcardBitsToWildcardLong` to
flip prefix length, so I inlined the reverse and renamed to fit.

Prefix: simplify containsIp

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java

Currently we're finding the remote node for compatible active peers in BgpSessionStatus by checking the first adjacent peer in the configured topology. This isn't necessarily correct for peer `X` in the following case:
```
Configured topology: A, B, and C are all compatible
A ---- X ---- C
|
B
Established topology: Only B is reachable
A      X      C
|
B
```
The correct remote node is `B`'s node, but the current approach might yield any of `A`, `B`, or `C`'s nodes (depending on the order of `configuredTopology.adjacentNodes(x).iterator()`).
Changed remote node logic to use the established topology if the status is `ESTABLISHED`, and only use configured topology if the status is `NOT_ESTABLISHED` (which indicates there's exactly one compatible remote peer but it's not reachable). As …

BgpSessionStatus remote node fix

---

projects/checkstyle.xml
projects/pom.xml

Note: the RightCurly rules are redundant with autoformat

Upgrade plugins

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfigId.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/smt/PropertyChecker.java

Only 2 of these were user-facing.

inteface is a common typo

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcard.java

IpWildcard: delete deprecated constructors

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniSettingsMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniSettingsMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_vxlan_vrfs

Convert VXLANs to per-VRF VniSettings

Cumulus: convert VXLANs

---

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswererTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java

Mirrors work done for BgpSessionCompatibility in #3853.

BgpSessionStatus question cleanup

---

projects/checkstyle.xml

Google-java-format does so much work for us now.

checkstyle: check less

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpProcessPropertySpecifierTest.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/abstraction/AbstractionBuilder.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpPeerConfigurationAnswererTest.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpProcessConfigurationAnswererTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswererTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/parsing-tests/unit-tests-vimodel.ref

Ref changes are just field re-orderings.

BgpProcess: enforce presence of router-id

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpFilterInactiveTest.java

* Fix up advertise inactive, re-enable tests
* Remove logic of add-path it's not tested an I'm convinced it's not
correct

BGP: fix up export logic in some corner cases

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4

PaloAlto parser: factor out interfaces into their own file

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java

Don't accumulate edges into a set. Instead create a Layer2Topology
builder that alllows each edge to be GCd after being processed.

optimize Layer2Topology computation

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Edge.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java

noticed some missing annotations and incorporated minor suggestions from Dan.

Small tweaks to layer1/2 classes

---

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Service.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceGroup.java

And fix existing bugs in two places.

 Sanity check maps of named things during conversion

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DecrementLocalPreference.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ExplicitAsPathSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/IncrementLocalPreference.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchCommunitySet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedAsPathSet.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnRib.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java

Make BgpRoute generic as a precursor to simplifying export pipelines.

Generify BgpRoute

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_service.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Service.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceGroup.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceGroupMember.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/service

* Grammar fixes
* Add annotations to Service to aide in building it properly
* Use IntegerSpace instead of SortedSet
* Support and test port ranges.

PaloAlto: support port ranges

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rule.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/applications

No application extraction yet, but at least we get the undefined references now.

PAN: initial support for Application references

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressObject.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rule.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase

* Rule: organize fields, annotate, and add negate-source/destination
* AddressObject: annotations and delete unused constructor
* Simplify Match SrcIp/Match DstIp
* Implement negate-source and negate-destination

Rule,AddressObject: cleanup and support negate-source, negate-destination

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/vsys-zones

PaloAlto: Include units in zone assignment

---

projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswerer.java
projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesPlugin.java
projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesQuestion.java
projects/question/src/test/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswererTest.java
projects/question/src/test/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesQuestionTest.java
questions/experimental/findMatchingFilterLines.json
tests/questions/experimental/commands
tests/questions/experimental/findMatchingFilterLines.ref
tests/questions/experimental/findMatchingFilterLines.ref.testout

New question `findMatchingFilterLines` returns a table of lines in the specified filters that match any packets in common with a given header constraint.

FindMatchingFilterLines question

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase

And a test that failed before.

PAN: rigorous use of getText(t)

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase

Order (and therefore process) rules by declaration order, not alphabetically.

Fix PAN rule ordering

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_bgp
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Including "internal" and explicit

Cumulus: parse more variations of bgp remote-as

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_application.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Application.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/applications

Add initial parsing support for PAN applications.  Also update application reference tracking to use unique name.
No conversion or application details yet.

PAN: application

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java

that's the gist, tweak english as you desire.

Update todo descriptions

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/shared-gateway

Add initial `shared-gateway` extraction for PAN.
No conversion or `shared-gateway` references supported yet.

PAN: Add initial shared-gateway extraction

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_zone.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Zone.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/zone-external

PAN: Add external zone extraction
Just extraction for now - no use in conversion and vsys's are not yet tracked as defined structures.

PAN: Add external zone extraction

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
tests/parsing-tests/unit-tests-vimodel.ref

But do simplify line building.

PAN: don't compute outgoingInterface yet

---

projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java

Unnecessary constraint; this will remove barriers to testing.

Generalize batfish parameter to type IBatfish

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_vsys.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_zone.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Zone.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
tests/parsing-tests/networks/unit-tests/configs/palo_alto/zones
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

To make this work and tests, I had to add interface types and zone import interface.

Palo Alto: add and track zone types

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Application.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationBuiltIn.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/applications-builtin

Add initial builtin application support for PAN (port and protocol info is not supported by the underlying `Application` yet, so this is just for better ref tracking)

PAN: initial builtin application support

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_application.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationGroup.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
tests/parsing-tests/networks/unit-tests/configs/palo_alto/applications
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

* application-group class
* application-group members
* application references (and utility cleanup)

PAN: Initial extraction of application groups

---

projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java

generalize parameter type to IBatfish

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

After #3994
No propagation in this PR.

Initialize EVPN type 3 routes across vrfs

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

ibdp create mappings from import route targets to vrfs

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java

Propagation for type3 routes.
Planning to do a little cleanup/code de-duping in a follow up PR

EVPN: propagate type3 routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
tests/aws/topology-example-aws.ref
tests/aws/vimodel-example-aws.ref

Interface: AWS has many non-VPN interfaces that start with v

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Aggregate.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/BfObject.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/AggregateTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
tests/aws/topology-example-aws.ref

Aggregate: fix id serialization

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnCumulusTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-l2-vnis/configs/Leaf1
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-l2-vnis/configs/Leaf2
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-l2-vnis/configs/Spine
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-l2-vnis/layer1_topology.json

Includes e2e cumulus test on a simple snapshot

Generate type3 routes for l2 VNIs

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-path-warning

They are subsumed by other todos.

Juniper: remove some very spammy todos

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java

PaloAlto Interface: cleanup

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CommunitySetExpr.java

Building streams up for these actually adds a lot of overhead. We may want to be more careful throughout.

Convert small streams to for loops

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios_switchport_mode

This reverts commit 10140a84b06180dab2190e76ce24bc4814472d78.
Another PR in process which will do this in `CiscoControlPlaneExtractor.java`

Revert "set correct switchport mode (#4025)"

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios_switchport_mode

Replacement PR for https://github.com/batfish/batfish/pull/4025 with a better and correct fix.
Setting switch port mode during parsing.
(also, this will not need https://github.com/batfish/batfish/pull/4028)

Correct fix for batfish/batfish#4018

---

projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
tests/parsing-tests/unit-tests-vimodel.ref

This is for #4051 , but does not fully fix.

Cisco: default Vlan interface to 1Gbps

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralCommunitySet.java

* use the newer standard for lazily initialized locals
* fix a typo

CommunityList: bring up to standards

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/CommunityListTest.java

CommunityList: fix propagation of environment

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/question/src/test/java/org/batfish/question/lpmroutes/LpmRoutesAnswererTest.java

so that it is consistent with `Dataplane#getRibs`

Make MockRib take in Annotated route

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/AddressFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/EvpnAddressFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/Ipv4UnicastAddressFamily.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java

Each commit is self-contained.

 Make BgpSessionProperties aware of address families

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluParser.g4
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

For now didn't bother with extraction

Cumulus: add parsing for vlan hwaddress

---

projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
tests/parsing-errors-tests/networks/single-fail/configs/cumulus_nclu_range
tests/parsing-errors-tests/no-verbose.ref
tests/parsing-errors-tests/parsing-error.ref
tests/parsing-errors-tests/recovery-no-verbose.ref
tests/parsing-errors-tests/recovery-parsing-error.ref

Modeled after cisco parser recovery

Cumulus parsing: enable newline-based recovery

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_frr.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu
tests/parsing-tests/unit-tests.ref

Reduces number of parse warnings

FRR: add parsing for exit-vrf

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfaceClagSettings.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_clag_linklocal

Cumulus: parse link-local clag peer ip

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Mlag.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cumulus/InterfaceClagSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cumulus/InterfaceClagSettingsTest.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfaceClagSettings.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/clag-linklocal-peering/configs/n1
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/clag-linklocal-peering/configs/n2
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/clag-linklocal-peering/layer1_topology.json
tests/parsing-tests/unit-tests-vimodel.ref

* Plumb through link-local peer IP to vendor family
* Assign link-local addresses to peer links if necessary

Clag vendor family update

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDFibGenerator.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java
projects/batfish/src/main/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitor.java
projects/batfish/src/main/java/org/batfish/bddreachability/ReversePassOriginationState.java
projects/batfish/src/main/java/org/batfish/bddreachability/SessionCreationNodeVisitor.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDFibGeneratorTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactorySourcesTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java
projects/symbolic/src/main/java/org/batfish/symbolic/state/StateExprVisitor.java
projects/symbolic/src/main/java/org/batfish/symbolic/state/VrfAccept.java

- needed for bidirectional reachability return pass

Insert VrfAccept between PostInVrf and NodeAccept

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4
tests/parsing-tests/networks/unit-tests/configs/nexus_bgp
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

Help us from losing parser context.

NXOS: parse bfd under bgp neighbor

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java

This is kinda crap, got any better advice?

BgpRoute builder: copy-on-write

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java

Seems leftover from really long time ago, no point in keeping it around?

Delete BDD graphviz code

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/VendorFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco_nxos/CiscoNxosFamily.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/ErrorDetailsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishLexerErrorListenerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishParseTreeWalkerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/BatfishParserErrorListenerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/MockGrammarSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/ParseTreePrettyPrinterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/RecoveryGrammarTest.java
projects/batfish/BUILD
projects/batfish/pom.xml
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/parsing/BUILD
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/parsing/CiscoNxosBaseLexer.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/parsing/CiscoNxosBaseParser.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/routing_table/eos/EosRoutingTableExtractorTest.java
projects/batfish/src/test/java/org/batfish/grammar/routing_table/ios/IosRoutingTableExtractorTest.java
projects/batfish/src/test/java/org/batfish/grammar/routing_table/nxos/NxosRoutingTableExtractorTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_hostname

- activate via debug flag: 'newnxos'

Cisco NX-OS parser skeleton

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java

Just came across this during investigation of open source question.

L2Topology: delete unused function

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-xr-prefix-set
tests/parsing-tests/unit-tests-vimodel.ref

IOS-XR: fix the end policy handling

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/package-info.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_bind_dependency
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ip_address
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_range

- interface
- ip address
- ip address secondary
- bind dependency for subinterfaces
- interface ranges

Cisco NX-OS basic interface parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchMetric.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term

Implement MatchMetric, restore juniper tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

I believe the former was a typo, looking at docs.

TopologyProvider: initialRawLayer3 -> RawLayer3

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/bdd/BasicTests.java

Not used much yet, but seems like it could be useful.

bdd: less/diff sat

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborL2vpnEvpnAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamilyTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/BgpNeighborL2vpnEvpnAddressFamilyTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_bgp
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Parsing, and extraction. Holding off on conversion because VI model needs to be tweaked a tiny bit more after #4165

 Cumulus: better support for address families, extract route-reflector-client

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_port_channel
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_port_channel_invalid
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_port_channel_references

- port-channel interfaces
- interface speed and bandwidth computation
- channel-group with and without 'force'
- fix VI port-channel bandwidth computation bug
- filter contributions from inactive members

Cisco NX-OS port-channel support

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Vrf.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf_invalid
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf_references

- declare VRFs
- add interfaces to VRFs
- clear layer-3 settings when doing so
- null VI VRF for interfaces in non-existent VRFs

Cisco NX-OS VRFs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java

Use logical l1 for l3 link-local computation

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ip_access_list.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/IpAccessList.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/IpAccessListLine.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/IpAccessListLineVisitor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RemarkIpAccessListLine.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_access_list
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_access_list_references

- parsing of virtually all ip access-list syntax
- structure definition
- extremely preliminary class hierarchy

Cisco NX-OS ip access-list parsing

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

* Put in more assertions, better error messages
* Rename some functions
* Fix up visibility for some variables

Cleanup some bdp nits

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizer.java

BDDReachabilityGraphOptimizer: list instead of set

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

And test both cisco-xr and cisco-nx.
Fix batfish/batfish#4194

VendorConfigurationFormatDetector: add recognizing rancid cisco-xr

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_stp.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_stp
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Warn globally that anything regarding spanning tree is not supported

Cumulus: flesh out and ignore spanning tree grammar

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

IOS-XR: missing reference for route-policy apply

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_parsing_temporary

- port of NX-OS BGP parsing from unified Cisco-family parser

Cisco NX-OS BGP parsing

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpSessionStatus.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ConfiguredSessionStatus.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserEnumSetTest.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityQuestion.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionQuestion.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusQuestion.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityQuestionTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityStatusQuestionTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionQuestionTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusQuestionTest.java
questions/Parameters.md
questions/experimental/bgpSessionCompatibility.json
questions/experimental/bgpSessionStatus.json
tests/questions/experimental/bgpSessionCompatibility.ref
tests/questions/experimental/bgpSessionStatus.ref

separated out the two types of statuses and moved them to parboiled enumsetspecifier

Bgp session status to parboiled

---

projects/batfish-common-protocol/BUILD
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParseTreeWalker.java
tests/parsing-errors-tests/no-verbose.ref
tests/parsing-errors-tests/parsing-error.ref
tests/parsing-errors-tests/recovery-no-verbose.ref
tests/parsing-errors-tests/recovery-parsing-error.ref

Fix exception being consumed by ParseTreeWalker.

Make WILL_NOT_COMMIT status visible

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
tests/parsing-tests/unit-tests-vimodel.ref

* Cleanup visibility/annotations
* Better immutability (get rid of setVrf on builder)
* Do not do nullable builders

EigrpProcess: cleanup anti-patterns

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java

No functional changes yet, just refactoring and annotations

Small readability improvements to VirtualEigrpProcess

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

Just small automatic refactoring. Preparing to switch internal route propagation to queues as well.

Rename incomingRoutes to incomingExternalRoutes

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

Note: none of the functionality is "hooked up" -- has no impact on route
propagation yet. Just doing incremental PRs so review is easier.

EigrpRoutingProcess: skeleton for implementing RoutingProcess

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java

More bits that follow the new RoutingProcess pattern.
Still not hooked up to real route propagation.
Each commit is self-contained.

EIGRP: continue fleshing out new skeleton

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java

* Do not use staging RIBs
* Switch internal routes to queue-based propagation
After #4320

EigrpRoutingProcess: queue-based route propagation

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

* Gets rid of all old code in ibdp: staging RIBs, reaching into other processes' RIB, IGP propagation loop.
* All route propagation is queue-based
Further cleanup to docs, tests and route propagation funcs will be done in future PRs.
After #4322

 Remove old EIGRP code

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4

Cisco NX-OS format parser imports

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java

Not just the first one where we create the map.

NX-OS: every entry in a route-map is part of its definition

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralEigrpMetric.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetEigrpMetric.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_routemap.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetMetricEigrpLine.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map-set-metric-eigrp

 Cisco routemap support setting EIGRP metrics

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels-eigrp/configs/advertiser
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels-eigrp/configs/receiver

Allows EIGRP route advertisements over tunnels

EIGRP - recompute topology

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Nve.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve

and sanity check nve settings during extraction.

NX-OS: nve extract host-reachability protocol

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-reenter-process
tests/parsing-tests/networks/unit-tests/configs/cisco_bgp
tests/parsing-tests/networks/unit-tests/configs/cisco_misc
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

Functionality is the same as that of #4298 except now I'm making a PR into the correct branch. 🤦‍♂

 Cisco extractor: allow re-entering of BGP process

---

projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface-reenter

The functionality exists, just wanted to codify it in a test

Add a test for re-entering interface stanzas on IOS

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java

- also added one more test to see if the check falls through and rejects the route if nothing matches

Preserving original EIGRP redistribute policy's true statements while merging with distribute-lists

---

projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpIpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_bgp_ip_neighbor
tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_bgp
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

* Add support (extraction/conversion) for bgp neighbors specified by IP
* Do a little refactoring for sanity

Cumulus: support BGP IP neighbors

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_object_group.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/ObjectGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/ObjectGroupIpAddress.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/ObjectGroupIpAddressLine.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/ObjectGroupVisitor.java
projects/batfish/src/test/java/org/batfish/datamodel/BddTestbed.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_access_list
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_object_group_ip_address
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_object_group_ip_address_references

- also support references via ip access-list addrgroup

Cisco NX-OS object-group ip address support

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java

Prerequisite to more general routing policy expressions (and more generic metric handling as well).

EigrpRoute: pull up common builder

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
tests/aws/topology-example-aws.ref
tests/basic/topology.ref

a number of `UNKNOWN` interfaces in POJO topology ref changed to a known type

Fix batfish/batfish#3904

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpInterfaceSettings.java

* Fix up the builder pattern
* Better annotations

Cleanup EIGRP interface settings

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

was running into a "Too many open files" exception

close inputStream in getSnapshotInputObject after use

---

questions/experimental/searchFilters.json
tests/questions/experimental/searchfilters.ref
tests/questions/test_questions.py

 Enforce which characters are allowed in question templates

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java

Add some initial tests of OSPF session compatibility checks

OSPF: Add session compatibility tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/IbgpTopology.java

Remove (unused) ibgptopology

---

projects/batfish/src/main/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/concatenation

moving interfaces before ports so ports extractor can just populate existing VS model

reorder cumulus concatenation

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ip_policy

Incremental progress towards PBR support on NXOS

NXOS: extraction for interface PBR policies

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityList.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchCommunity.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchCommunityTest.java

Add RouteMapMatchCommunity class

route map match community

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_switchport

Cisco NX-OS various interface ignores

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_switchname

Cisco NX-OS switchname

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_routemap.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java

Parse cumulus frr route map match interface

cumulus frr route map match interface

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetMetric.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapSetMetricTest.java

constructs for route map set metric

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_policy_map

- police misc syntax
- interface no ipv6 redirects

Cisco NX-OS various ignores

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfNetworkType.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ospf-network-types

Track OSPF network type in Cisco VS model.

Cisco OSPF: Track network type

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties

- delay
- ip flow
- ip unreachables
- snmp

Cisco NX-OS more interface ignores

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ip_policy

Cisco NX-OS fix interface ip policy grammar

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/LiteralVrfName.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Return.java

Make more packet policy classes final

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/AssignIpAddressFromPool.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/Transformation.java

Split off of another PR with actual functional changes.

misc: a few useful builder functions and toString

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosDynamicNatTest.java

No functional changes intended.
Reduce code reuse across incoming/outgoing, factor out utility methods, add comments.

CiscoIosDynamicNat: refactor a bit

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_policy_map

- fix lexing and parsing of system qos service-policy, policy-maps in
general

Cisco NX-OS interface service-policy qos parsing

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_hsrp_ipv6
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties

- no lldp
- no vtp
- hsrp group ipv6 ip autoconfig

Cisco NX-OS interface ignore more

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_policy_map.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_policy_map

- policy-map type queuing
- interface service-policy type queuing
- system service-policy type queuing

Cisco NX-OS queuing parsing

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_route_map.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapEntry.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchIpAddressPrefixList.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchIpv6Address.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchIpv6AddressPrefixList.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchVisitor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map

- ipv6 prefix-list
- route-map match ipv6 address
- route-map match ipv6 address prefix-list
- route-map set ipv6 next-hop unchanged

Cisco NX-OS parsing and mostly ignoring various ipv6 constructs

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-rip-passive

Fix RIP passive setting for Cisco interfaces.

Cisco: Fix RIP passive

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_route_map.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapEntry.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchVisitor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchVlan.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map

Cisco NX-OS route-map match vlan

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java

It's already the package default.

NxosConfiguration: remove unnecessary Nonnulls

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_snmp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_tacacs_server.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_snmp_server
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_tacacs_server

- logging
- ntp
- snmp-server traps
- tacacs

Cisco NX-OS various server source-interface commands

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_eigrp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpProcessConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp

NX-OS: eigrp extraction of VRF, ASN, isolate

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRouteMetadata.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

BDP will use it to make connected routes (per address)

Store metadata for connected routes in Interface

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_crypto.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_crypto

I anticipate more stuff will need to be parsed, so I just went ahead and split into a new file to setup for the future.

NXOS: parse and ignore some crypto lines

---

projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_interfaces/Converter.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_interfaces/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_interfaces/Interfaces.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_interfaces/ConverterTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_interfaces/InterfaceTest.java

Cumulus interfaces: convert bonds to VS model correctly

---

projects/batfish/src/main/java/org/batfish/representation/cumulus_interfaces/Converter.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_interfaces/ConverterTest.java

A subinterface is one with name of the form `<iface>.<number>`.
A physical subinterface is one where `<iface>` is a physical interface.
A bond subinterface is one where `<iface>` is a bond.

fix cumulus subinterface type definition

---

WORKSPACE
projects/pom.xml

Fixes ASM bugs reported all over the place.

Upgrade to parboiled 1.3.1

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java

Enforce non-null check for OSPF passive setting.

OSPF: make passive setting non-null

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp_double

Still need to figure out how to fix.

NX-OS: don't crash on two EIGRP processes sharing an ASN

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ntp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/NtpServer.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ntp

- authenticate
- authentication-key
- server prefer

Cisco NX-OS ntp constructs

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnType5CumulusTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Internet
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Leaf1
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Leaf2
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Leaf3
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Leaf4
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Spine1
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/Spine2
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/configs/exitgateway
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testrigs/evpn-type5-routes/layer1_topology.json

Tests and code changes are in separate commits.
cc @arifogel If you get a chance PTAL to have an extra sanity check.

Support for EVPN type 5 routes in BDP

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4

(There is already parsing test)

NX-OS: remove parse ambiguity with s_boot vs s_null

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/HsrpGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceHsrp.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_parsing_temporary
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_hsrp
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties

Some missing tokens in null rules, some HSRP improvements (also tested)

NX-OS: a number of interface parsing fixes

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_mac.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_mac

Including many grammar updates

NX-OS: flesh out mac access-list

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_snmp.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_snmp_server

NX-OS: allow inform as variant of informs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetNextHop.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/SetNextHopTest.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetNextHopLine.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetNextHopPeerAddress.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicySetNextHop.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetIpNextHopLiteral.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenNextHopIp.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenNextHopSelf.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusNcluConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapSetIpNextHopLiteralTest.java
tests/aws/vimodel-example-aws.ref
tests/parsing-tests/unit-tests-vimodel.ref

* Get rid of "destinationVrf" -- never used, could not find docs
* Scope to BGP routes

NextHopExpr: cleanup code, add some tests

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

So we get line numbers and more parser context.

Cisco-multi: convert to warn from redFlag

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/grammar/MockGrammarSettings.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
projects/batfish/src/main/java/org/batfish/config/Settings.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoCombinedParser.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp

Scaffolding only, hidden by debug flag.

Begin splitting BGP grammar for Arista

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java

The newer NX-OS devices appear to be deterministic, and anyway these router IDs are
now surfaced prominently in facts and status questions.

NX-OS: don't warn about router-id as much

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/UnchangedNextHop.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nh_unchanged

- also adds `UnchangedNextHop` routing policy expr

NXOS: next-hop unchanged conversion

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ospf.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ospfv3.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ospfv3

 NX-OS: flesh out ospfv3 grammar and reference tracking

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_monitor.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_route_map.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vlan.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java

And update all grammar that uses them.

NX-OS: separate VLAN into unreserved or any

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp

Pulling out common parts for the parse tree that work globally and inside a VRF.

Arista BGP: move to VRF config

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpAggregateNetwork.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_aggregate_address

Only for v4, but support parsing for v6

Arista BGP: extraction for aggregate-address

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpHasPeerGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpPeerGroupNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpV4DynamicNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpV4Neighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

Flesh out some rules fully, keep others commented so we can flesh them out later.

Arista BGP: begin neighbor extractions

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_vrf

Local AS, route distinguishers and route targets for a BGP VRF.

Arista bgp: handle more VRF config

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

And maximum-accepted-routes
Not bothering with extraction, yet.

Arista bgp: parsing for maximum routes

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighbor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

Just `send-community` is most common
but apparently one can do crazy stuff.

Arista BGP: minimal extractions for send-community

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp

Arista BGP: parsing for 'additional paths' and 'listen' commands

---

projects/batfish/src/test/java/org/batfish/grammar/arista/BUILD
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/BUILD

`bazel test //projects/batfish/src/test/java/org/batfish/grammar/arista/...`

Arista: simpler bazel tests

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpVrf.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_bgp

Allows ECMP with eBGP.
Both NCLU and FRR support is included.

Cumulus: support for 'as-path multipath-relax'

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

Arista BGP: no neighbor enforce-first-as

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpHasPeerGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighborAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpV4DynamicNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpV4Neighbor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

I forked from NX-OS conversions and built it up. Lots of commented-out code, comments that need updating, and TODOs.

Arista: Initial BGP conversion for IPv4 address families

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighbor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

Arista: move route-map to address family configuration

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface

Handle both versions of syntax, add tests

Arista: fix interface VRF extraction

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java

Easiest for now, considering we don't have a *local* bgp rib

Fix in bdp if ipv4 unicast AF not present

---

projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_vxlan

VNISettings shouldn't blindly go into one VRF.
Figure out the right VRF by looking up Vlan ifaces for L2 VNIs

Arista: put VNIs in the correct VRF

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

Essentially support for BGP overlay atop BGP underlay

Send EVPN routes to newly established BGP sessions.

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

- remove communities v1 code
- update conversion tests for communities v2

Cisco NX-OS communities v2 cleanup

---

projects/batfish/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto_nested/BUILD
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto_nested/PaloAltoNestedLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto_nested/PaloAltoNestedParser.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto_nested/PaloAltoNestedCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/palo_alto_nested/PaloAltoNestedFlattener.java
projects/batfish/src/main/java/org/batfish/grammar/palo_alto_nested/SetStatementTree.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/resources/org/batfish/job/palo_alto/nested-config
projects/batfish/src/test/resources/org/batfish/job/palo_alto/nested-config-flattened

@arifogel cc: @sfraint 
can you take a look at the flattening issue here? Why does Batfish add an extra space?

Flattening issue

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/applications

And flesh it out in a url-like way.

PAN: add M_Url for links

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4

Unused in:
* modes
* grammar
* refs

Hybrid parser: remove lexer tokens that are unused

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java

Use in a way that line numbers are tracked.

PAN: improve warnings

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/Graph.java

Let `InterfaceType` be the source of truth.

Rewrite Interface isLoopback

---

projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/community

Juniper communities v2 policy-statement match community test

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
tests/parsing-tests/unit-tests-vimodel.ref

* Record encapsulation VLAN for tagged L3 interface on PaloAlto devices
* Also add some clarifying comments in VI model

PAN: handle L3 interface tag

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_routemap.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapCall.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusNcluConfigurationTest.java

1. Parsing for `on-match next`
2. Rudimentary support for call statements

FRR: improve routemap support

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java

Fix some minor annoyances:
1. Re-alphabetize some grammar rules.
2. Parse `password ...` and `enable password ...`

FRR: parse some password lines

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_tag.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Tag.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/tags

Parse and extract tags, setting up for more `address` and `address-group` related work in the future, using tags

PAN: extract tags

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java

No conversion for any vendor yet

BgpProcess: placeholder for confederation config

---

projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/F5BigipStructured_common.g4
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredCombinedParser.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java

- wraps unrecognized when we don't care about its content

F5 BIG-IP structured ignored rule and parsing updates

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4

Make PAN lexer format more consistent
* Regroup tokens
* Make indentation uniform

PAN: lexer consistency

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java

1. Cleaner AS checks
2. Take confederations into account

BgpTopology: better computation for local/remote AS

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/UnchangedNextHop.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

Ignore next hop IP if UNSET

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java

Add placeholder BGP export policy, exporting eBGP and iBGP.

PAN: initial BGP export policy

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
tests/parsing-tests/unit-tests-vimodel.ref

NX-OS: apply BGP remote AS as tag on BGP import

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/external-list

For now only doing a structure definition, no extraction.

PAN: parsing for external lists

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java

Pre-req to making sessions confed-aware

AsPair: Also keep track of confed session type

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java

Instead of reaching into peer configs, use session props.

BDP: use session prop ASes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/ApplyTransformation.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FlowEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/StatementVisitor.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/ApplyTransformationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java

Implemented in FlowEvaluator, not yet in BDD land.

Packet policy: statement to apply a transformation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/ApplyTransformation.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/ApplyTransformationTest.java

ApplyTransformation: minor fixups

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java

But support old path for backwards compatibility.
cc: @saparikh

FileBasedStorage: prefer batfish data inside batfish folder

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/BoolExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookupOutgoingInterfaceIsOneOf.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FlowEvaluator.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

Three commits:
1. plumb through srcInterfaceVrf to FlowEvaluator
2. Add FIBs to FlowEvaluator
3. Implement the actual expr semantics

FlowEvaluator: implement FibLookupOutgoingInterfaceIsOneOf

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

Hopefully that's sufficient (?)

PacketPolicyToBdd: handle ApplyTransform

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/NatRule.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java

Also fixes an incorrect Nonnull annotation in NatRule

PAN: Method to check if NAT rule is valid

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

Fix bug where transformed flow is not used after PBR is applied.

Save transformed flow after PBR is applied

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/ApplyTransformation.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookupOutgoingInterfaceIsOneOf.java

Packet policy: add toString() to some statements

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/BoolExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/Conjunction.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FlowEvaluator.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/ConjunctionTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

Packet policy: add conjunction

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/PolicyStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Step.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/PolicyStepTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

Since now not all packet policies are filters.

Make a new traceroute step for policies

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/HierarchyTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/GroupWildcardTest.java

For #2128 Doesn't handle all cases, but a step in the right direction.

Towards better wildcard support in Juniper apply-path

---

projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/HierarchyTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/GroupWildcardTest.java

For apply path/groups
I believe this fixes #2128

Juniper: continue fleshing out wildcard support

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java

One passive interface should not stop all route propagation :)

Fix isis route propagation

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java

Co-authored-by: Ari Fogel <ari@intentionet.com>
Co-authored-by: Victor Heorhiadi <victor@intentionet.com>

Fix up BGP tie breaking for ibgp

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpGlobalConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfNeighborAddressFamilyConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_peer_template

NX-OS: add extraction test for #5081

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsApplicator.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/coordinator/src/main/java/org/batfish/coordinator/QueuedWork.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

1. Add a span for the part of the init task where we make the jobs.
2. Fix the name of a span.
3. Move all the post-assignment tasks (like checking the status of a job) into their own span. Makes the overall organization better.

Tracing: a number of small fixes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfaces_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java

CumulusInterfaces: accept range syntax for bridge vids

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4

CumulusInterfaces: parse and ignore bond-lacp-rate

---

projects/batfish/src/main/java/org/batfish/main/Flatten.java
projects/batfish/src/main/java/org/batfish/main/PreprocessJuniper.java

tools: relative paths to execution directory

---

projects/checkstyle.xml

- e.g. org.glassfish.jersey.internal.guava.*

Blacklist jersey internal classes

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/community

Juniper: add back support for invert-match

---

projects/batfish-common-protocol/src/test/java/org/batfish/version/BatfishVersionTest.java

Add test to make sure service loader finds `BatfishVersion`

Add service loader test

---

projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
projects/batfish/src/main/java/org/batfish/representation/aws/IcmpTypeCode.java
projects/batfish/src/main/java/org/batfish/representation/aws/NetworkAcl.java
projects/batfish/src/main/java/org/batfish/representation/aws/NetworkAclEntry.java
projects/batfish/src/test/java/org/batfish/representation/aws/NetworkAclTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/NetworkAclIcmpTest.json

Add support for IcmpTypeCodes in AWS NetworkAcls

support for icmp and tests

---

projects/question/src/main/java/org/batfish/question/prefixtracer/PrefixTracerAnswerer.java
projects/question/src/main/java/org/batfish/question/prefixtracer/PrefixTracerQuestion.java
projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java
projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerQuestionTest.java

Make consistent with other questions

PrefixTracer: flip to new node specifier

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-failover

this is `@eidorb`'s issue on Slack. Likely introduced by batfish/batfish#4915

ASA: fix failover grammar, add tests

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-reentrant-vrf
tests/parsing-tests/unit-tests-vimodel.ref

And fix a re-entrant bug in vrf block, and add test/update existing ref test.

Cisco: handle vrf declared in address-family line

---

.buildkite/pipeline.sh

* Make the extensive static analysis tests depend on templates and formatting, but not on the jar. This gives them a ~3.5m head start.
* Make the ref_tests depend only on the jar, instead of also on formatting and templates. This means they will run even if formatting is bad, as long as the jar builds.

Buildkite: dagify to see if its faster

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/interface_test

add rules to parse the following commands:
```
auto swp1
iface swp1 inet static
link-autoneg on
link-speed 1000
```

new cumulus interface syntax

---

projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

Verify ARISTA format, stop throwing unnecessary assertion

AristaGrammarTest: cleanup

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/GeneratedRouteHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java

bdp: minor cleanup

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/static_route

1. grammar to parse command like `ip route 0.0.0.0/0 10.3.0.129 vrf vrf02` (#5164)
2. to vs conversion (vs to vi conversions is already there)

cumulus frr static route

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java

Followup to #5182 on the dataplane side

BDP: process attribute maps for generated routes

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighbor.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/BgpNeighborTest.java

- inherit ebgp-multihop
- inherit update-source

Fix Cumlus BGP peer group inheritance

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListLineMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java
projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
tests/aws/vimodel-example-aws.ref

Plus, add entry name to ACL term.

IpPermissions: rewrite and comment

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json

Also plumb warnings in and test a bit.

IpPermissions: handle ICMP type and code

---

projects/allinone/BUILD
tests/java-smt/BUILD

```diff
8473a8474,8604
>    1 com/microsoft/
>    1 com/microsoft/z3/
>    1 com/microsoft/z3/AST$1.class
>    1 com/microsoft/z3/AST.class
>    1 com/microsoft/z3/ASTDecRefQueue.class
>    1 com/microsoft/z3/ASTMap.class
>    1 com/microsoft/z3/ASTMapDecRefQueue.class
>    1 com/microsoft/z3/ASTVector.class
>    1 com/microsoft/z3/ASTVectorDecRefQueue.class
>    1 com/microsoft/z3/AlgebraicNum.class
>    1 com/microsoft/z3/ApplyResult.class
>    1 com/microsoft/z3/ApplyResultDecRefQueue.class
>    1 com/microsoft/z3/ArithExpr.class
>    1 com/microsoft/z3/ArithSort.class
>    1 com/microsoft/z3/ArrayExpr.class
>    1 com/microsoft/z3/ArraySort.class
>    1 com/microsoft/z3/BitVecExpr.class
>    1 com/microsoft/z3/BitVecNum.class
>    1 com/microsoft/z3/BitVecSort.class
>    1 …
```

allinone: do not include minesweeper by default

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer3Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Vni.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
projects/question/src/main/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswerer.java

Followup to #5198 at dataplane level.

Dataplane: separate L2 and L3 VNIs

---

projects/question/src/main/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswerer.java
projects/question/src/test/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswererTest.java

Makes it easier to identify what VRF each L2 VNI is in.

Add a VRF column to VxlanVniProperties

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlagsMatchConditions.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclLineMatchExprsTest.java

Adding centralized definition of new/established flows.

new AclLineMatchExprs for new/established flows

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer3Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Vni.java

Flood lists do not apply to L3 VNIs

Cleanup the datamodel VNI API a little bit

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_logging.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_logging

NX-OS: fix logging server parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/question/src/main/java/org/batfish/question/evpnl3vniproperties/EvpnL3VniPropertiesAnswerer.java
projects/question/src/main/java/org/batfish/question/evpnl3vniproperties/EvpnL3VniPropertiesQuestion.java
projects/question/src/main/java/org/batfish/question/evpnl3vniproperties/EvpnL3VniPropertiesQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/evpnl3vniproperties/package-info.java
projects/question/src/test/java/org/batfish/question/evpnl3vniproperties/EvpnL3VniPropertiesAnswererTest.java
questions/experimental/evpnL3VniProperties.json
tests/questions/experimental/commands
tests/questions/experimental/evpnL3VniProperties.ref
tests/questions/test_questions.py

First pass.
Allows validation of RD/RT mappings for L3 VNIs.

Add an EVPN L3 VNI question

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java
tests/basic/routes-dc-as-reuse.ref
tests/basic/routes-diff.ref
tests/basic/routes.ref
tests/basic/testfilters.ref

Row: revert hashCode improvement

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/ArpErrorStep.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/DeliveredStep.java

following the convention of naming

renaming JsonTypeNames for ArpErrorStep and DeliveredStep

---

projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java

I assume no longer used because #5182 did the more correct thing.

AristaConverions: delete unused code

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp

No support for this in VI so leave as todo

Arista BGP: parse always-compare-med

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/FirewallSessionTraceInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/MatchSessionStep.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/MatchSessionStepTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

This PR depends on #5275, which depends on #5274. To review this PR before #5274 merged, please see 7ac7470.

Include match criteria in MatchSessionStep

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp

No effect on analysis. I just needed a break from routing 😛

Arista BGP: flesh out more of the parse tree

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java

1. backup ip setting without explicit vrf 
`clagd-backup-ip 10.0.0.12`
2. priority setting `clagd-priority 100`

two interface clagd changes

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusNcluConfigurationTest.java

There was a lot of duplicate code, making extensions (coming) and testing hard.

frr: refactor bgp peer generation

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfaces_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java

1) parse and ignore link promiscusous 
2) warn for "no ip forwarding" -- seems like an important command to not silently ignore

Frr two changes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/HeaderSpaceConverter.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java

No point in implementing it because only ExprAclLine will be supported.

HeaderSpaceConverter doesn't implement GenericAclLineVisitor

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowDiff.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FlowDiffTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java

This PR is based on #5294, this PR's changes are in f0df45c

Include transformation behaviour in SetupSessionStep in traceroute

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_nexthop_unchanged

At multiple levels (top, vrf, and AF)

Arista BGP: support for nexthop-unchanged

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_nexthop_unchanged

Also, plumb through more next-hop unchanged (follow up to #5350)

Arista BGP: flesh out more grammar for ipv4 address family

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

These do not impact analysis, but are somewhat likely to occur in production configs.

Arista BGP: parse common supplemental commands

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ExprAclLine.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclAclLineTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ExprAclLineTest.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
tests/parsing-tests/unit-tests-vimodel.ref

Adding @sfraint to review `JuniperConfiguration` and `PaloAltoConfiguration` -- in particular, you might have suggestions to improve the new line descriptions.

Use AclAclLine in place of takingExplicitActionsOf

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_confederations

Followup to #5356 
Doing space enumeration at conversion (see #5357 for discussion)

Arista BGP: convert confederation config

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpActivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPassivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpUnnumberedPeerConfig.java

Well, nothing bad happened .... the peer shows up in other questions as expected

remove the check for existense of at least one address  family

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaRedistributeType.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_redistribute_ospf

To the best of our current ability in VI, handle the variants of 'redistrite ospf' command

Arista BGP: handle redistribute ospf

---

projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java

While flipping the bit to new parser (#5376), found test failures. Turns out VI
pipeline is a little incorrect (see #5375)  so doing the fix in conversion for now.

Arista BGP: fix neighbor default-originate

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java

A few behavior-preserving refactorings to simplify AclTracer

refactor AclTracer

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/ActionGetter.java
projects/question/src/main/java/org/batfish/question/comparefilters/CompareFiltersAnswerer.java
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityRows.java
projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswerer.java
projects/question/src/test/java/org/batfish/question/comparefilters/CompareFiltersAnswererTest.java
projects/question/src/test/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswererTest.java

Simple change to remove unused parameter and make ActionGetter a singleton.

Clean up ActionGetter

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/Tracer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/trace/TracerTest.java

discardSubTrace no longer creates a new subtrace after discarding the
current one.

Fix Tracer::discardSubTrace, add Tracer tests

---

questions/Parameters.md

Be consistent about heading levels.
Will also help when inlining the file in other docs

Parameters.md: update title and headings

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/EbgpPeerGroupType.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp

PAN: add parsing and extraction for EBGP options

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/TraceNode.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/trace/TraceNodeTest.java

This will eventually be the new trace output format for testFilters

Jackson serialization for TraceNode

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/EbgpPeerGroupType.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java

PAN: fix a typo

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNodeConfiguration.java

FRR: Merge the two variants of convertVxlan

---

projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
tests/aws/vimodel-example-aws.ref

Add back batfish/batfish#5424 with updated tests (tests are now expecting non-empty children list)

Add back batfish/batfish#5424 with updated tests 

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TraceElement.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TraceEvent.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorStructureId.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TraceElementTest.java

Make toString developer facing, add getText as the alternative and port
callers over to it.

TraceElement/Fragment toString

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java

We were inferring router id for OSPF, but not BGP. Generalize and use the inference for BGP as well.

Juniper: fix BGP router id inference

---

projects/pom.xml

pom.xml: upgrade checkstyle

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4
tests/parsing-tests/networks/unit-tests/configs/nxos/nxos_bgp
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

* Log neighbor changes
* Advertisement interval
Keeps us in the right parser context.

NXOS: parsing enhancement for bgp template-peer

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

VendorConfigurationFormatDetector: don't trust rancid type cisco

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NoApplicationsApplicationSpecifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierFactories.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/SpecifierFactoriesTest.java

that'll make it usable from other places

plug the new app specifier into the specifier factory

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/AllSources.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContext.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContextImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledInputValidator.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/AllSourcesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/InterfaceLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/MockSpecifierContext.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/TestSpecifierContext.java
projects/question/src/test/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswererTest.java

Resolves to all Locations marked as sources in LocationInfo

new AllSources LocationSpecifier

---

projects/batfish/src/main/java/org/batfish/representation/aws/AwsLocationInfoUtils.java
projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsLocationInfoUtilsTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/InstanceTest.java

AWS: vendor-specific LocationInfo for instance locations

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DeviceModel.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DeviceType.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/NodeTest.java
projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
projects/batfish/src/main/java/org/batfish/representation/aws/Vpc.java
projects/batfish/src/test/java/org/batfish/representation/aws/InstanceTest.java
tests/aws/topology-example-aws.ref
tests/aws/vimodel-example-aws.ref

E.g., Juniper SRX340 or AWS EC2 Instance.

Configuration: add DeviceModel for vendor-specific device information

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
tests/aws/vimodel-example-aws.ref

Internet: set LocationInfo to use any unowned IP as a source IP

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowBuilderTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TypedRowBuilderTest.java

This actually runs the inner tests.
No other changes

De-nest RowTest

---

projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java

cc: @anothermattbrown 
Issue reported on slack: https://batfish-org.slack.com/archives/C8XKQNHAQ/p1581541649139200

SearchFilters: return proper schema in differential mode

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-reth
tests/parsing-tests/unit-tests-vimodel.ref

- set type of  juniper reth units as REDUNDANT_CHILD
- remove unnecessary datamodel additions from #5542

Fix broken Juniper reth following #5542

---

projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java

comments for clarity

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilHybridCloudTest.java

IPSec topology: skip edges to inactive interfaces

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/OspfInterface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ospf

FWICT this has no mapping in VI right now.

NX-OS: parse and extract interface ospf priority

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ExprAclLine.java
projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationNatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTestUtils.java
projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/InternetGateways.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/NatGateways.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/NetworkAcls.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/NetworkInterfaces.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/Reservations.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/RouteTables.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/SecurityGroups.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/Subnets.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/aws_configs/Vpcs.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test-nat-gateway/nat-gateway-test.tf
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

Design doc: https://docs.google.com/document/d/1QzwRM6XmTGQcJkmcbDfxSgNDGDIAhC7_B3w-JQy6RMM/edit#

AWS: Support for NAT gateways

---

projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationLoadBalancerTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationNatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPrivateSubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicPrivateSubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicSubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationSubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTestUtils.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTransitGatewayMultiTableTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTransitGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationVpcPeeringTest.java

(no change in what is being tested)

AWS tests: Refactor e2e tests

---

.idea/vcs.xml
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/Driver.java
projects/batfish/src/main/java/org/batfish/main/Flatten.java
projects/batfish/src/main/java/org/batfish/main/PreprocessJuniper.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/NetworkAcls.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/NetworkInterfaces.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/Reservations.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/RouteTables.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/SecurityGroups.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/Subnets.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/aws_configs/Vpcs.json
projects/batfish/src/test/resources/org/batfish/main/snapshots/load_vendor_configurations/configs/rtr1

This functionality will help build questions/answers that operate over vendor configs.

Add a method to IBatfish to load vendor configurations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IcmpType.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/applications/IcmpTypeCodesApplication.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/applications/IcmpTypeCodesApplicationTest.java

1. add a new icmp type/code validity checking function
2. next to remove the old one

new test icmp type/code validity function

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/applications/IcmpTypeCodesApplication.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/applications/IcmpTypeCodesApplicationTest.java

update isValidTypeCode with a simpler implementation

clean IcmpTypeCodesApplication::isValidTypeCode

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java

Queries like "8.8" and "Google" will show 8.8.8.8 as a suggestion.

Add well-known ips to autocomplete

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
tests/aws/vimodel-example-aws.ref

"Internet_out_interface" --> "out". (internet and interface were redundant)

Shorter name for the Internet interface

---

projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/test/java/org/batfish/representation/aws/CustomerGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpnConnectionTest.java
projects/batfish/src/test/resources/org/batfish/representation/aws/CustomerGatewayTest.json
projects/batfish/src/test/resources/org/batfish/representation/aws/NatGatewayTest.json
projects/batfish/src/test/resources/org/batfish/representation/aws/VpnConnectionTest.json

In some (legacy) cases we were not ignoring unavailable resources.

Only parse available resources

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsTest.java

Wasn't catching conflicts between applications and tcp flags.

PHC: fix bug in resolveIpProtocols

---

projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java

Tweak AWS lb filter names

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModel.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java

Too many constructor arguments to handle.

IspModel: switch to builder

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDFlowConstraintGeneratorTest.java

The upper bound of 172.16.0.0/12 was wrong. Rewrote to use IpSpaceToBDD

BDDFlowConstraintGenerator: fix isPrivateIps

---

projects/batfish/src/main/java/org/batfish/representation/aws/Vpc.java
projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/UtilsTest.java
tests/aws/vimodel-example-aws.ref

@ratulm - can you make a new lab for this or point me at the instructions?

AWS: Handle case where entire VPC is owned by one covering subnet

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface

It's subinterface 21, not interface 21.
https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClssCAC

PAN: fix 10GbE interface bandwidths

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-agg

PAN: support aggregate-ethernet interfaces

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpAdditionalPathsConfig.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpNeighborAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpNeighborDefaultOriginate.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpVrfAddressFamily.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all

Arista: show run all bgp 2/?

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpDefaultOriginate.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpVrf.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all

Arista: show run all bgp 4/?

---

projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all_2

This one is from a different chassis and a different version of EOS.

Arista: show run all bgp (EOS-4.22.3M)

---

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

WorkMgr.{getTestrigObject,putObject} canonicalize earlier in function

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpNeighbor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all_3

* limit vrf address families
* a couple of more generic AF properties

Arista: add and support show run all bgp for vEOS 4.23

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/application-group

Outside of Vsys or shared context

PAN: support application-groups at top level

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/InputValidationUtilsTest.java

single-application specifier validation

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface
tests/parsing-tests/networks/unit-tests/configs/arista_ospf
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

Flesh out grammar and fix up a parsing test

Arista: interface ip ospf priority

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface_show_run_all

Arista: interface ip pim flesh out

---

projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests.ref

Just use markConcreteStructure where we can. Caught several
missing usages.

F5: fix structure tracking

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java

Let the moves be atomic where possible.

FileBasedStorage: simplify and use move-with-overwrite

---

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

- remove v1 API call
- remove client support
- remove backend support

Remove get-object

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SnapshotMetadata.java
projects/coordinator/src/main/java/org/batfish/coordinator/SnapshotMetadataMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java
projects/coordinator/src/test/java/org/batfish/coordinator/SnapshotMetadataMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java

Disk is not atomic, but the cache can be.

SnapshotMetadataMgr: guard against concurrent reads and writes

---

library_deps.bzl
maven_install.json
projects/pom.xml

httpclient: bump version again to 4.3.6

---

projects/pom.xml

It's really slow, so off always for now.

maven: add OWASP dependency-check to build

---

projects/pom.xml

Fixes behavior with newer JDKs

maven: update maven-dependency-plugin

---

projects/allinone/BUILD
projects/batfish-client/BUILD
projects/batfish/BUILD
projects/coordinator/BUILD

was missing in https://github.com/batfish/batfish/pull/5742 and maven and bazel were not in sync

bazel: add runtime dependency for jaeger-thrift

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

- L2 self-edges do not contribute to broadcast domains for nodes without
L1 edges.

Optimzation: skip computing L2 self edges for nodes without L1 or VXLAN

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/AwsFamily.java

Not populated yet, but will be in future PRs.

AWS vendor family: add account id

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDTracer.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDTracerTest.java

For debugging bdd reachability analysis. Generates all paths from a start location / BDD.

bdd tracer

---

projects/batfish/src/main/java/org/batfish/representation/aws/TransitGateway.java
projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayTest.java

Transit gateways: fix up equals

---

projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

It's unused and untested, and some tools started warning on it.

BDD: delete save/load

---

projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/RdsInstanceMatchers.java
projects/batfish/src/test/java/org/batfish/representation/aws/matchers/RdsInstanceMatchersImpl.java

* Handle `backing-up` status ([RDS instance is available during backup state](https://aws.amazon.com/rds/faqs/))
* Add `isUp()` method to determine if RDS instance is up and should be added to region

RDS instance: handle additional status

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java

- move related constant to FileBasedStorage

WorkMgr forkSnapshot unzip directly instead of creating file

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

- stop storing unused DataPlaneAnswerElement
- move related constant to FileBasedStorageProvider

Move data plane I/O to StorageProvider

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableJob.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/job/ParseEnvironmentBgpTableResultTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/main/TestrigText.java

- move related constants
- remove unused test code

Move environment BGP table I/O to StorageProvider

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableJob.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/job/ParseEnvironmentBgpTableResultTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/main/TestrigText.java

This reverts commit e5c186279755ae522ef34d65294b0c0cc942488f
which breaks snapshot init w/ bgp tables.

Revert "Move environment BGP table I/O to StorageProvider (#5802)"

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/BgpAdvertisementsByVrf.java
projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BgpTableFormat.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/grammar/BgpTableFormatDetector.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableJob.java
projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/job/ParseEnvironmentBgpTableResultTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
projects/batfish/src/test/java/org/batfish/main/TestrigText.java
projects/batfish/src/test/resources/org/batfish/main/snapshots/env_bgp/bgp/rtr1.bgp
projects/batfish/src/test/resources/org/batfish/main/snapshots/env_bgp/configs/rtr1

- actually use test utilities
- add test that initializes snapshot with environment bgp tables
- atomicity for FileBasedStorage.serializeObject

Resubmission of batfish/batfish#5802 with fixes

---

projects/batfish-client/BUILD
projects/batfish-client/pom.xml
projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-client/src/main/java/org/batfish/client/Command.java
projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java
projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java

Things never called in tests, things that only happen at loglevels we don't set
in tests, etc.

Client: delete unused calls

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

- move related constant to FileBasedStorage

Move external BGP announcements I/O to StorageProvider

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

- move related constant to FileBasedStorage

Move ParseVendorConfigurationAnswerElement I/O to StorageProvider

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/CliUtils.java
projects/batfish/src/main/java/org/batfish/main/Flatten.java
projects/batfish/src/main/java/org/batfish/main/PreprocessJuniper.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/CliUtilsTest.java
projects/batfish/src/test/java/org/batfish/main/FlattenTest.java
projects/batfish/src/test/java/org/batfish/main/PreprocessJuniperTest.java

- move utility functions only used by internal CLI tools to another
class
- clean up CLI tools so they no longer reference Batfish
- move some static functions as necessary

Remove all file I/O from Batfish.java

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
tests/basic/testfilters.ref

Whoops, we were leaving flags all zero in lots of cases.

BDDFlowConstraintGenerator: add TCP flag preferences

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/BgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-confed
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

IOS: implement bgp confederations

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_vrf.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/StaticRoute.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusNcluConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/InterfaceConverterTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/StaticRouteTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/static_route

Adding distance support to static routes in FRR.

Static route distance support to FRR

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/main/BatchManager.java
projects/batfish/src/main/java/org/batfish/main/Service.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java

Remove remainders of killwork api

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java

BgpRib: fix another Ip.AUTO comparison

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

Had this sitting around from last week. No functional changes, just factoring out the return value for `processPBR` from the anonymous `ActionVisitor` it uses. Previously, `processPBR` returned the boolean produced by applying the `ActionVisitor`, but the `ActionVisitor` always returned true. Now it's an `ActionVisitor<Void>` and `processPBR` just returns true after applying it.

FlowTracer: Make anonymous ActionVisitor return null

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

L2 is a broadcast domain. For a complete graph, we only need to add a spanning
tree to get the same effect. We also do not need to add edges symmetrically.

TopologyUtil: optimize L2 self edges

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_template.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Template.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/template

Add support for Palo Alto `template` in VS model.
`template-stack`s and conversion will come in subsequent PRs.

PAN: VS template

---

projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java

Implement this behavior: 
If there are no enabled Availability Zones with a healthy target in each target group, requests are routed to targets in all enabled Availability Zones.
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
Earlier, Batfish was ignoring target groups where all targets were unhealthy.

AWS NLB: fix handling of case where all targets are unhealthy

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines

PAN: ignore admin-role

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_snmp.g4
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_snmp

Arista: add a variant of snmp server configuration

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java

* Fix security rule test to properly test rule order
* Fix rule ordering
* Attach to correct vsys

PAN: Panorama rulebase fix

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java

Set configuration format for Palo Alto managed devices.

PAN: set configuration format for managed devices

---

projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTransitGatewayAsymmetricPathsTest.java

AwsConfigurationTransitGatewayAsymmetricPathsTest: fix filename

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationBuiltIn.java

Add a few more builtin applications.

PAN: add more builtin apps

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

I was debugging an unrelated issue and found this code confusing. Clean it up
and unify it, removing parallel BDD edges in the process.

BDDReachabilityAnalysisFactory: delete parallel edges

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/runtime/InterfaceRuntimeData.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/runtime/InterfaceRuntimeDataTest.java

Add address to interface runtime data structure.

Interface Runtime Data: add address

---

projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java

Previously the network ACL was uniformly applied to all subnet interfaces except the one interface that faces all the attached instances. However, this wasn't correct after #5957 because the network ACL also shouldn't be applied to other interfaces the subnet may have that face target instances or NLBs.
Now network ACL is applied to subnet interfaces on a case-by-case basis. This includes all subnet interfaces facing the VPC.

Apply network ACL to subnet node more correctly

---

projects/batfish/src/main/java/org/batfish/representation/aws/ElasticsearchDomain.java
projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java
projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
tests/aws/topology-example-aws.ref
tests/aws/vimodel-example-aws.ref

Taking over #5959, which slightly different behavior on RDS.

AWS: fix subnet attachments for RDS and ESD instances

---

projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java

Need return flows to the load balancers to match sessions on the VPCs.

Session info on VPC interfaces to subnets with instances

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/DestinationTranslation.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-nat

Parse and extract destination port translation for Palo Alto devices (this PR does not handle conversion).

PAN: parse and extract destination port translation

---

.pre-commit-config.yaml
tests/questions/test_questions.py

Taking pity on @anothermattbrown

pre-commit: setup java and python checks

---

networks/hybrid-cloud-aws/aws_configs/us-west-2/Vpcs.json
projects/batfish/src/main/java/org/batfish/representation/aws/Vpc.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationErrorTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTestUtils.java
projects/batfish/src/test/java/org/batfish/representation/aws/InstanceWithMultipleInterfacesTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/UtilsTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpcEndpointGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpcPeeringConnectionTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpcTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/VpnGatewayTest.java
projects/batfish/src/test/resources/org/batfish/grammar/aws/testrigs/ipsec-vpn-host-aws-cisco/aws_configs/Vpcs-us-west-2.json
projects/batfish/src/test/resources/org/batfish/representation/aws/VpcTest.json
projects/batfish/src/test/resources/org/batfish/representation/aws/test/aws_configs/Vpcs.json

Prep for other features. No functional changes in this PR.

Parse vpc owner

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/WellKnownCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/StandardCommunity.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java

And fix a bug in WellKnownCommunity constants.

StandardCommunity: add well-known community shortcuts
