- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
The return value of RibDelta#Builder#build is immediately sorted.
Just build it sorted in the first place, and add (private)
type signature that enforces this.
> RibDelta: omit a copy

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
There seem to be other bugs here, which I'm not fixing in this PR.
> BgpSessionProperties: fix arg permutation bug

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Topology.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer1TopologyTest.java
Since we don't allow self-loops or parallel (duplicate) edges in the graph representing `Layer1Topology`, we currently ignore any provided L1 topology file that contains such edges. In the interest of flexibility, this PR modifies the behavior to accept those topology files. Self-loops are now ignored and parallel edges are included in the `Layer1Topology` only once; other edges are added to the topology as usual.
> Layer1Topology: Ignore self-loops and parallel edges

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Pair.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/PairTest.java
The thing that can be null is `Pair::getSecond`, not `rhs`.
> Move nullsFirst comparator to right place

- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
For `BgpRib.comparePreference(R lhs, R rhs)`, the parameters can't be null, but their `receivedFromIp` can.
> Fix & test nullsFirst in BGP best path comparator

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
Gives portchannel subinterfaces a `BIND` dependency on their parent portchannels, so that they will inherit bandwidth from their parents.
In the process, fixed a couple bugs in bandwidth calculation for aggregate interfaces and their children:
- There was only one loop through interfaces to calculate their bandwidths. Split into two loops to calculate first aggregate interface bandwidths, then aggregate child interface bandwidths (since an aggregate child interface's bandwidth depends on its parent's bandwidth).
- Aggregate interface bandwidths were calculated from channel group members, then recalculated from dependencies if they had dependencies. This would be okay except that aggregate child interface bandwidths were calculated in between those two calculations, so if a parent …
> Portchannel subinterface dependency on parent

- projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java
- projects/question/src/test/java/org/batfish/question/VIModelAnswererTest.java
The head and tail IPs in `BgpSessionProperties` are guaranteed to be nonnull, whereas BGP peer config IDs can have null local IPs even if they have edges in the BGP topology.
Separation of `getBgpEdges()` methods is solely for easier testing and should not affect functionality.
> Use BgpSessionProperties IPs instead peers' local IPs

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecSession.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilTest.java
We need to be able to identify if any of the peers for an IPsec session was a cloud configuration (like AWS). This will be later used to decide if we can verify reachability for that IPsec session: we will not verify reachability for IPsec sessions with the flag `cloud` set to true.
> Identifying IPsec sessions between cloud type configurations

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Our tests and also docs, indirectly (https://docs.cumulusnetworks.com/display/DOCS/Border+Gateway+Protocol+-+BGP#BorderGatewayProtocol-BGP-BGPCommunityLists) indicate that this is the case
> Cumulus: bgp send community is true by default

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
When no sources are referenced, we don't need a representative of the
active but unreferenced sources. Not having one makes the manager
trivial, which makes source tracking more efficient.
> optimize BDDSourceManager

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_evpn
- tests/parsing-tests/unit-tests-vimodel.ref
1. Simpler logic: no need to check that a VXLAN config is valid, conversion takes care of that.
2. This uncovered:
1.  `cumulus_nclu_evpn` test file had missing data 
2.  I had unintentionally been creating duplicate L3-VNI to VRF mappings, which is incorrect. Fixed now.
Any one reviewer will do.
> Cumulus: use VI repr of VXLAN for EVPN conversions

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface
The command is link-state, not link-status.
E.g., see: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClZQCA0
searching for "palo alto" "link-status down" only found things about `show`, not `set`.
> PaloAlto: fix parser for link-state

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/AnnotatedRib.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/AnnotatedRibTest.java
* No functional changes intended
* Differentiate AbstractRoute exports and BgpRoute exports
This simplifies transformation logic; Sets up possibility of
generifying BGP route exports
* Do not treat new BGP session establishment differently from message
propagation -- call into the same functions (e.g.,
queueOutgoingRoutes)
> BGP: decouple export transformations

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
We use `IsBgpRouteThat` only when we really mean `Bgpv4RouteThat`.
Rename to reflect that.
This also eases making `BgpRoute` generic.
> Specialize a BgpRoute matcher

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
Also, they are not composites so do not add preceding `~`
> PAN: namespace user-defined objects with the user name first

- skylark/junit.bzl
> junit: use newer bazel syntax

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkeAuthenticationMethod.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-crypto
parsing RSA encryption authentication method in Cisco IOS's ISAKMP policy
ISAKMP policy is stored in VI model's `IkePhase1Proposal`
> Parsing rsa-encr authentication method in IKE

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkFactory.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
Remove builder as parameter from transformation functions, simplify import
of BGP routes, add tests for import.
Side effect: cleanup the builder pattern for BgpProcess a little.
> BGP: simplify transformations 1

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/Layer3VniConfig.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/EvpnAddressFamilyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/Layer3VniConfigTest.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
For eBGP, import RT must differ from export RT because remote as is not
known ahead of time.
Also, switch to builder pattern.
Any one reviewer will do.
>  L3 VNI config: differentiate between import and export route targets

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
Some internal functionality relies on it. It also is somewhat useful, I'd say.
> Restore primary network to interface prop specifier

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_vsys.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/vsys-import
PAN: Support importing other `vsys`'s into a `vsys`.
Just extraction for now - no use in conversion and `vsys`'s are not yet tracked as defined structures.
> PAN: Support vsys importing

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpProcessPropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java
Tweaks are mainly:
- increasing self-consistency
- using "peer" in lieu of "peering"; to me "peering" implies two peers, but the properties in `BgpPeerPropertySpecifier` only apply to one peer
- other tweaks to move focus onto the peer and away from the session(s) it might establish.
>  Property specifier descriptions: tweaks and todos

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
Add check to make sure all attached ACLs (e.g. interface's outgoing filter) exist in the config's `IpAccessList` map.
> Add ACL checks in config finalizer

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
Take in `Node` so we have access to other VRFs during initialization.
> Small tweaks to routing process initialization

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceBuiltIn.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceGroup.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-service
Extract `application-default` service builtin and treat `any` as a service builtin instead of catchall service for PAN
`application-default` has no effect until applications are added (https://github.com/batfish/batfish/issues/2097)
> PAN: extract more service builtins

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfPropertySpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/VxlanVniPropertySpecifier.java
These examples will actually work if used for the `properties` parameter in questions that use these specifiers.
> Fix specifier Javadocs to have correct examples

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
If an interface is used for an unnumbered peer in cumulus, assign it a link-local IPv4 address.
Not a perfect solution, but enables creation of l3 edges so that traceroute/reachability will work.
> Cumulus: assign distinct link-local addresses

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/eos-allowed-vlans
We were incorrectly setting allowed vlans for a configuration like below:
```
interface Port-Channel1
switchport trunk allowed vlan 1,2
switchport mode trunk
!
```
the first line would set the allowed vlans to `[1,2]` but the second line would reset it to `[1, 4094]`, which would cause the layer 2 topology self edges computation to blow up (because we were not able to honor allowed vlans even when the configuration said `allowed vlan none`). This was happening because we assumed that we will always see `switchport mode trunk` before `switchport trunk allowed vlan <none|x,y>`.
This PR addresses the above and also adds handling of:
`switchport trunk allowed vlan none`
> Fix allowed VLANs in Interfaces

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios_switchport_mode
fixes https://github.com/batfish/batfish/issues/4018
DOT1Q and ISIL are VLAN trunk encapsulation mode with DOT1Q being the latest and more popular one.
https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst6500/ios/12-2SX/configuration/guide/book/layer2.html#42266
> Set correct switchport mode for DOT1Q and ISL encapsulation

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- tests/parsing-tests/unit-tests.ref
Interfaces have a delay configured by default; but many devices do not use EIGRP.
Drop this spammy warning.
> Cisco: delete spammy eigrp warning

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
1. Drop Objects.equals for nonnull fields
2. Reorder things likely to return false to the top.
3. Reorder == above .equals for the remainder.
> BgpRoute: minor fixups to equals

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManagerTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
Instead, ensure at conversion time that these structures are ordered by key.
This leads to much faster lookups by key.
> Configuration: remove NavigableMap from several key structures

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpEdge.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetric.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcessMode.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EigrpMetricMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EigrpMetricMatchersImpl.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
> Eigrp: only compute metrics in the given mode

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
In most cases, the list is optional. Add a utility to simplify null checks.
> PaloAlto: use utility for internal robustness improvements

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoBidirectionalBehaviorTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/allow-inter-sg
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/allow-intra-sg
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/allow-sg-to-vsys
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/allow-vsys-to-sg
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/allow-vsys-to-sg-next-vr
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/drop-vsys-to-sg-misconfigured-external
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/drop-vsys-to-sg-missing-external
- unconditionally allow inter- and intra-shared-gateway traffic
- don't generate rules guarded by empty set of source interfaces
- ignore zones entirely for shared-gateways
- Add sg-sg tests
- Remove unnecessary sg zones
> Fix shared-gateway traffic semantics

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- remove attempts to retrieve shared and panorama vsys namespace via `_virtualSystems`
- use `_shared` and `_panorama` instead
> Palo Alto fix special vsys references

- skylark/junit.bzl
```
Starting local Bazel server and connecting to it...
INFO: Invocation ID: ac6c8092-b332-42cd-94d6-372727ceb39a
ERROR: /Users/dan/git-workspace/batfish/projects/allinone/BUILD:68:1: in _GenSuite rule //projects/allinone:DetectLoopsTestTestSuite:
Traceback (most recent call last):
File "/Users/dan/git-workspace/batfish/projects/allinone/BUILD", line 68
_GenSuite(name = 'DetectLoopsTestTestSuite')
File "/Users/dan/git-workspace/batfish/skylark/junit.bzl", line 55, in _impl
",".join([_AsClassName(x) for x in ctx.at...])
File "/Users/dan/git-workspace/batfish/skylark/junit.bzl", line 56, in ",".join
_AsClassName(x)
File "/Users/dan/git-workspace/batfish/skylark/junit.bzl", line 38, in _AsClassName
[x.path for x in fname.files]
type 'depset' is not iterable. Use the `to_list()` method to get …
```
> Bazel: fix for skylark breaking change

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_evpn_4byte_as
Says to use lower two bytes only:
https://docs.cumulusnetworks.com/display/DOCS/Ethernet+Virtual+Private+Network+-+EVPN#EthernetVirtualPrivateNetwork-EVPN-RD-auto-derivationAuto-derivationofRDsandRTs
> Cumulus: fix route target derivation for 4-byte ASNs

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-interface-ospf
Not null, which breaks downstream pipeline.
Fix batfish/batfish#4124
> Batfish: aggregate with no bound interfaces has bandwidth 0

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- tests/parsing-tests/networks/unit-tests/configs/cisco_interface
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
Saves us from loosing the right parser context.
By default changes nothing. Warn if it disables forwarding (which we currently don't handle).
> Interface: parse "ip forward"

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MultipliedAs.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicyPrependAsPath.java
Hacky fix, but save us from NPEs/random jackson errors.
> RoutePolicyPrependAsPath: stop crashing by choosing default number

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
Handle the case where address families are not equal between peers.
Also as a side effect, start fleshing out `BgpProcess.Builder`
> BgpRouting process: fix queue initialization

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/AddressFamily.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/EvpnAddressFamily.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/EvpnAddressFamilyTest.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
1. Add `propagateUnmatched` to EVPN address family
2. Setup for more complicated builders, since a bunch of common settings will have to be migrated from `BgpPeerConfig` to `AddressFamily`
> EvpnAddressFamily: add setting for unmatched route propagation

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VerboseEdgeTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/PropertySpecifierTest.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Route.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpnGateway.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/Graph.java
- projects/question/src/test/java/org/batfish/question/interfaceproperties/InterfacePropertiesAnswererTest.java
I wanted to get rid of some setters (namely `setAddress`, `setAllAddresses`). That proved to be too much of a burden to not break a lot of conversion code, but at least I got this minor cleanup out of it. Might revisit getting rid of setters later.
Each commit can be viewed separately for clarity.
> Minor cleanups to Interface

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
The culprit here was `UseOutputAttributes` which is true for juniper so the tag had to be read from the output route builder, not original route. 
Fix: Make BDP copy the tag to the output builder when export non-bgp routes. 
need to design a saner pipeline here, not clear at all which attributes can/should be read from where and thus copied or not copied.
Fixes #4169
> Bgp export: fix juniper "from tag"

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosInterfaceType.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_switchport
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_switchport_invalid
- default switchport mode for interface type
- default shutdown for switchport mode and interface type
- access mode
- access vlan
- trunk mode
- native vlan
- allowed vlans
- fix interface name processing
> Cisco NX-OS interface switchport settings

- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
It's okay to run an algorithm on an empty set. If the caller wants to ensure
that something matches the filter, they should probably resolve the specifier
first.
> FilterLineReachability: stop rejecting empty filter sets

- projects/batfish-common-protocol/src/main/java/org/batfish/common/WillNotCommitException.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseStatus.java
- projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
- projects/question/src/main/java/org/batfish/question/initialization/InitIssuesAnswerer.java
Identifies files that would be rejected by the device because they
contain invalid config.
lmk if I missed special handling in other parts of the stack.
> Add a WillNotCommit parse status

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_interface
> Cumulus: support for interface aliases

- projects/bdd/pom.xml
It doesn't inherit compiler config since we the code has very different style
> BDD: fix pom to not warn on serial

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNcluParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_frr.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/CumulusNclu_routing.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
- tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu
- tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_routing
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
* agentx -- related to SNMP, can ignore
* always-compare-med -- make explicit we don't support that
* Eat more FRR lines
> Cumulus: kill more parse warnings

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
1. Be more concervative in link-local edge establishment. Choose
candidates only if L1 topology is present
2. Special case subinterfaces of aggregate interfaces (they will not
appear in L1, lorical or physical).
3. Fix setting interface types for aggregate subinterfaces on Cumulus
> Link-local topology fixes

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDLoopDetectionAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizer.java
As I mentioned in review for batfish/batfish#3948, iterating over columns in a Table is prohibitively slow. Add the bookkeeping (and accompanying assertions) for incoming and outgoing edges for faster iteration.
The code as implemented with Streams also crashed routinely with ConcurrentModificationException -- because we were keeping a stream alive over a changing collection. Got rid of all that stuff.
To test performance in reality, I connected the optimizer into Loop Detection. On a ~1000 node graph, the optimization time went from > 15m to 2.5seconds.
> BDDReachabilityGraphOptimizer: rewrite for performance

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizer.java
This pruning operation is much faster (does not require merging constraints) so
is good to do as a prefilter.
Also modified some logic to not enqueue states that have disappeared from the graph.
This reduces suspiciously-high counts of roots pruned.
> BDDReachabilityGraphOptimizer: prune first

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
Slowly moving more functionality from VirtualRouter into BgpRoutingProcess. 
Also, finally generalizing export function to take in the proper address family type.
> Add prefix tracer to BgpRoutingProcess, generalize export function

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
Makes all of the following parse correctly:
```
vrf context foo
interface bar
vrf member foo
router bgp 1
vrf foo
```
Before, the last one did not parse because we only allowed names without member
or context when vrf was not first on the line. (adding support in subsequent PR)
Luckily, NX-OS disallows context or member as vrf names.
> NX-OS: refine M_Vrf

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/VrrpComputationTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockForwardingAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/main/java/org/batfish/grammar/routing_table/eos/EosRoutingTableExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/routing_table/ios/IosRoutingTableExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/routing_table/nxos/NxosRoutingTableExtractor.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java
- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
* Move a bunch of logic away from TopologyUtil to IpOwners
* Setup FA to compute VRF-owned IPs spaces, prep for additionalAcceptIps in a VRF
* Use the map returned by FA in Reachability and traceroute
* Cleanup DP interface -- no more ipVrfOwners
Just FYI this work was kicked off because of #4231
> Forwarding analysis: compute VRF owned IPs

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/CommonParser.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/IpProtocolIpProtocolAstNode.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ValueEnumSetAstNode.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/CommonParserTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserEnumSetTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpProtocolTest.java
pushing enum values into parser rules was generating a lot of pain, e.g., couldn't autocomplete bgp to ibgp. new strategy is to match all names in the parser, and then separately judge if the name is from the expected set.
> don't push enums into the parser rules

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfig.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfNeighborConfigTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
- projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/viModel.ref
- tests/parsing-tests/unit-tests-vimodel.ref
not modified `OspfNeighborConfigId` because one interface can only give rise to one `OspfNeighborConfig` so hostname, interface and vrf are enough to identify the OSPF neighbor config
> Add IPs in OSPF neighbor configs

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/RangeNetworkObject.java
- tests/parsing-tests/networks/unit-tests/configs/asa_object_groups
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
We already had the power, no idea why it wasn't plugged in...
> ASA: implement network-object range

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-service-object
- tests/parsing-tests/networks/unit-tests/configs/asa_object_groups
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Though it will show with "definition", ASA at least 9.7(1) allows you to skip
that clause when defining service objects:
If you enter this:
object-group service service-ssh
service-object tcp eq ssh
service-object tcp source eq www eq ftp
It will be acceped and show as this:
object-group service service-ssh
service-object tcp destination eq ssh
service-object tcp source eq www destination eq ftp
> ASA: allow service-object with implicit destination

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TunnelConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TunnelConfigurationTest.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
> Cisco: convert src/dst addresses for tunnel interfaces

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyContainer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TunnelTopology.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TopologyContext.java
- projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TopologyContextTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels/configs/n1-no-static-route
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels/configs/n1-static-route
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels/configs/n2-no-static-route
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-tunnels/configs/n2-static-route
Keep a topology of non-IPsec tunnels, re-add edges during dataplane
computation.
> Re-add "plain" tunnels in post-DP L3 topology

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/bddreachability/LocationToOriginationStateExpr.java
Previously would crash if final nodes or start locations contained
missing devices. This can happen in differential analysis.
> handle missing devices in reachability analysis

- projects/pom.xml
> move maven-dependency-plugin version to pluginManagement

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_evpn
- tests/parsing-tests/unit-tests-vimodel.ref
1. We have to care about L3 VNIs that are attached to VRFs which do not
appear in BGP config
2. As a consequence, creating dud BGP processes so we can properly do
cross-VRF BGP rib merging
> Cumulus EVPN: handle conversion corner cases

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/IncrementalBdpAnswerElement.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- tests/basic/genDp.ref
In preparation to moving EIGRP fully into dependent routes computation,
no need to separately keep track of EIGRP internal iterations.
> Remove EIGRP internal iterations from DP answer element

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-reenter-process
- tests/parsing-tests/networks/unit-tests/configs/cisco_bgp
- tests/parsing-tests/networks/unit-tests/configs/cisco_misc
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
For your consideration: do not erase previous BGP processes upon encountering another `router bgp` line.
Helps process hand-written configs (or appends to the end of the file).
Big ref changes are in Cadant files. Not sure if correct, but erring on the side of Cisco correctness.
> Cisco extractor: allow re-entering of BGP process

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
This flips the computation (calls in `VirtualRouter`, `IncrementalBdpEngine`) to the new route propagation, meaning tests like `EigrpTest` now use the new code.
After #4321
> EIGRP:  Flip to new EIGRP queue-based computation

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpNeighborConfig.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
* Don't bother with _interfaces
* Initialize message queues based on interfaces
After #4323
>  EIGRP: use topology as ground truth for computation

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf
and lay infra for other case-insensitive structures
> NX-OS: preserve original VRF name 

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceGroup.java
Seems like someone decided that all structures we used should be `Tree`-based? This is a weird one though IMO.
> Batfish: stop using TreeList

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
- tests/parsing-tests/networks/unit-tests/configs/ios_interface_ip_autentication
- tests/parsing-tests/networks/unit-tests/configs/ios_interface_ip_tcp
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
* Parse "ip authentication..."
* Parse "ip tcp ..."
> Cisco: more parsing under interface

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
when we are redistributing routes into individual routing processes (OSPF and EIGRP)
> Use main RIB delta instead of entire main RIB except in the first dataplane iteration

- README.md
Removed Vyatta, Quanta and Quagga
Created limited support list and moved Arub, Dell, Foundry to it.
> Update supported platforms list

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
- tests/parsing-tests/networks/unit-tests/configs/ios_xe_bgp
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Helps us not leave router bgp context.
> IOS: more permissive names for bgp templates (peer/session)

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve_vnis
NXOS also uses the same default UDP port 4789 for VXLan, [here](https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html).
> NXOS: Convert NVE and NVE VNI to VniSettings

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- tests/parsing-tests/networks/unit-tests/configs/cumulus_nclu_bgp_no_remote_as
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Instead of failing the whole file, resorting to ignoring invalid peers during conversion.
> Cumulus: gracefully ignore peers with no remote AS

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
- tests/aws/topology-example-aws.ref
- tests/basic/topology.ref
Bug was that nodeEdges() has a node's edges both where the node is the head and where the node is the tail. The buggy code was assuming that only head edges are present.
@haverma - this explains the oddity you noticed in the topology generated in #4359
> fix bug in pojo topology creation

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
- tests/parsing-errors-tests/networks/single-fail/configs/cumulus_nclu_invalid_bonds
- tests/parsing-errors-tests/no-verbose.ref
- tests/parsing-errors-tests/parsing-error.ref
- tests/parsing-errors-tests/recovery-no-verbose.ref
- tests/parsing-errors-tests/recovery-parsing-error.ref
Since our glob parsing is subpar, try to be graceful on "invalid" bond
combinations instead for filing the file
> Cumulus: Do not fail the file on invalid bonds

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
This lets us figure out what type of metric needs to be used in the `set metric` statement of a routemap.
> Routing policy environment: include EIGRP process

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkFactoryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfProcessTest.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-area-default-metric
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
- tests/parsing-tests/networks/unit-tests/configs/juniper_ospf
- tests/parsing-tests/networks/unit-tests/configs/juniper_ospf_stub_areas
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
Pre-req for having originator ID in routes, doing proper router-id checks during bdp and topology establishment.
> OSPF process: enforce non-null router-id

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
- tests/parsing-tests/networks/unit-tests/configs/ios_interface_eigrp_settings
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Prevents us from jumping out of interface context.
Fixes #4048
> IOS: parse EIGRP hello/hold timers

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
Use `.equals` instead of `==` for `Ip` comparison
> Fix router ID comparison in OSPF session compatibility check

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/eigrp-distribute-lists/configs/advertiser
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/eigrp-distribute-lists/configs/farlistener
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/eigrp-distribute-lists/configs/listener
Filter routes that we are re-propagating in addition to ones we are redistributing.
Fixes #4392
> EIGRP distribute lists: improve filtering

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Confirmed on nxos `match ip address` in route maps only applies to PBR.
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/unicast/configuration/guide/b-7k-Cisco-Nexus-7000-Series-NX-OS-Unicast-Routing-Configuration-Guide-Release/n7k_unicast_config_pbr.pdf
> NXOS: Remove unneeded todos

- projects/allinone/src/test/java/org/batfish/question/traceroute/TraceroutePolicyBasedRoutingTest.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/IngressInterfaceVrf.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/LiteralVrfName.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/VrfExpr.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/VrfExprVisitor.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FibLookupTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/IngressInterfaceVrfTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/LiteralVrfNameTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/PacketPolicyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/ReturnTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatement.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatementTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
FibLookup now returns not just a hardcoded VRF name but a VRF expression that can be evaluated to resolve to a concrete VRF name.
Part of incremental progress towards PBR on Cisco NXOS
> FibLookup: expand to VrfExpr

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- tests/parsing-tests/networks/unit-tests/configs/cisco_crypto
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
Found some variants of crypto commands in AWS's auto-generated IOS conf:
1/ `crypto ipsec fragmentation before-encryption` is a valid command. parsing and ignoring.
2/ `encryption` is valid under
```
crypto isakmp policy 1
encryption 3des
```
earlier, batfish only supported `encr`
3/ netmask is optional for identity address as below
```
crypto isakmp profile myprofile
match identity address 1.2.3.4
```
https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-2/security/command/reference/b_syssec_cr41crs_chapter_011.html
> minor crypto variants

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Stop perpetuating the pattern where we store complex objects inside interface when they really belong somewhere else (in this case, OspfProcess)
Name/number of the area still remains in interface
> Remove OspfArea from interface

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
builder attempts to modify configuration so we crashed with unsupported operation exception.
FYI the fact that new NXOS converter doesn't set export policy in all cases triggered this.
> OspfRoutingProcess: do not use builder for export policy

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/BoolExprVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FalseExpr.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FlowEvaluator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/TrueExpr.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FalseExprTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FlowEvaluatorTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/TrueExprTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
Still incremental progress towards NXOS PBR.
Need to be able to fail close/open in different scenarios to having these identities to use inside `If` statements is helpful.
> PacketPolicy: add True and False expressions

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_evpn.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EvpnVni.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/ExtendedCommunityOrAuto.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/VrfAddressFamily.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- since it is not possible to get an extended community back from a route distinguisher as type information is lost (- not retrievable from a route distinguisher)
- only parsing and extracting type 0 and type 2 route targets, since VI support is currently for these two types through `ExtendedCommunity` and type 1 is rare as route-targets.
> Storing route-targets as extended community instead of route distinguisher

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
- tests/parsing-tests/networks/unit-tests/configs/cisco_interface
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Open source user submitted parse warnings:
- Invalid interface name prefix: 'Wlan-GigabitEthernet'
- Invalid interface name prefix: 'wlan-ap'
These are on Cisco 881w-type WAP+routers.
> Cisco: add support for Wlan- interfaces

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_as_path_access_list_invalid
- fixes issue where large parts of file get thrown away in absence of
terminating double-quote
> Cisco NX-OS stop lexing double-quoted text at newline

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ospf-intervals
Improved VS model support for [OSPF hello and dead intervals](https://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/13689-17.html):
* Extract hello intervals
* Update dead intervals to be `null`able
* Add a basic test
> Cisco: OSPF intervals

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-intervals
Improved VS model support for [OSPF hello](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/hello-interval-edit-protocols-ospf.html) and [dead intervals](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/dead-interval-edit-protocols-ospf.html):
* Extract hello intervals
* Update dead intervals to be `null`able
* Add a basic test
> Juniper: OSPF intervals

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
- allow zero or tokens after 'no bfd'
> Cisco NX-OS relax interface no bfd parsing

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookupOverrideLookupIp.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FibLookupOverrideLookupIpTest.java
This is meant to support Cisco's `set ip next-hop` (and a similar concept on Juniper `then next-ip`)
Not plugged in anywhere yet, those PRs are in the queue.
> PacketPolicy: add action for overriding lookup IP

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Vrf.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis
- this was done to make the RouteDistinguisher in converted VNIs follow the convention used by Cisco. Cisco uses IP VRF-IDs to set the route distinguisher in VNIs where `rd auto ` is used.
[Cisco doc](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/vxlan/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x_chapter_0100.html#ariaid-title14)
> Setting VRF ID in VRFs and in converted L2 VNI's RDs

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ip_policy
1. Convert all route maps that are used for PBR into packet policies
2. Warn if route maps do not conform to ones supported by PBR
3. Attach appropriate names of packet policies to `Interface` in VI
> NXOS: conversion of PBR policies

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ipv6_dhcp_relay
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_ipv6_nd
- dhcp
- nd (neighbor-discovery)
> Cisco NX-OS interface ipv6 ignores

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ospf
- prevent NPE when adding interface without explicit OSPF settings to an
OSPF area via network statement
> Cisco NX-OS fix interface ospf cost conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/ActionVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookupOverrideLookupIp.java
- projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/PbrWithTracerouteTest.java
Plumb through the `FibLookupOverrideLookupIp` action into traceroute.
Includes a tiny bit of refactoring inside `FlowTracer`s `ActionVisitor` to reduce redundancy
> Traceroute: support for FibLookupOverrideLookupIp

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixList
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixListGlobal
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosOspfDistributeListPrefixListInterface
Only apply distribute lists to ifaces in the same process.
This also required updating test configs to associate interfaces with the correct OSPF process.
> Cisco OSPF: better distribute list association

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-eigrp-match-acl
If EIGRP process has a redistribution route-map, scan it for ACLs and
make those into route filter lists.
> IOS: Make route filter lists from ACLs used in EIGRP redistribution

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetOrigin.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/SetOriginTest.java
Helps prevent dataplane crashes
> SetOrigin: ignore non-BGP routes.

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
This is a vendor-specific concept, start using a vendor-specific constant (even though its value is the same).
> NX-OS: has its own default vrf

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_snmp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_snmp_server
- abbreviation appears to survive in NX-OS v6
> Cisco NX-OS allow abbreviation of 'traps' to 'trap' in some cases

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve_vnis
all VNI settings were being put into default VRF and also VRF in L2 and L3 VNI configs was being set to default VRF. 
This was not consistent with the actual behavior where the VRF association should be done keeping in mind the tenant VRF to which the VNI belongs to
> Associating VNI settings, L2 and L3 VNI configs with the correct VRF

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/NxosRoutingProtocol.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchSourceProtocol.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Note normally I would not add the Nxos prefix, but so many files use both it
seems worth keeping.
> NX-OS: add NxosRoutingProtocol

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
For local and connected routes use the metadata to set the correct tags.
Also, remove NXOS warning that tags on addresses not supported.
> Dataplane: use connected route meatadata

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
Add conversion helpers for Juniper OSPF hello and dead intervals.
VI model doesn't yet support hello intervals, so actual conversion will come in a subsequent PR.
> Juniper: OSPF interval conversion helpers

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java
Add conversion helpers for Cisco OSPF hello and dead intervals.
VI model doesn't yet support hello intervals, so actual conversion will come in a subsequent PR.
> Cisco: OSPF interval conversion helpers

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
If the BGP process is missing, tell us on which node.
> More useful crash messages

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis
This way we will actually propagate routes for those VRFs/VNIs and not crash in dataplane.
> Make dummy BGP processes for VRFs with L3 VNIs

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Both are enabled by default, so parse without extraction.
> cumulus: recognize send-community (extended)

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_eigrp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfIpAddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfIpv4AddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfIpv6AddressFamilyConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp
* Default VRF V4 address-family
* Configuration under `address-family ipv4 unicast`
* Configuration under `address-family ipv6 unicast`
Have not yet addressed conflicts between configuration in the VRF and V4
families.
> NX-OS: add EIGRP address-families focusing on redistribution

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/OspfInterface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco_nxos/CiscoNxosConfigurationTest.java
Add conversion helpers for Cisco NXOS OSPF hello and dead intervals.  In the process, also:
* Update VS model to allow/return `null` for intervals and just ensure non-`null` values in conversion helpers
* Update logic to allow [inferring `dead-interval` from `hello-interval`](https://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/13689-17.html)
VI model doesn't yet support hello intervals, so actual conversion will come in a subsequent PR.
> Cisco NXOS: OSPF interval conversion helpers

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_default_originate
1. Keeps us in the right parser context
2. Actually important for route propagation
> NXOS: handle no default-originate

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkFactoryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfInterfaceSettingsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfProcessTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TestUtils.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
- projects/question/src/test/java/org/batfish/question/ospfarea/OspfAreaConfigurationAnswererTest.java
- projects/question/src/test/java/org/batfish/question/ospfinterface/OspfInterfaceConfigAnswererTest.java
- projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
Move off of legacy OSPF settings setters and instead use new OSPF settings builder in tests.  Also, remove the legacy setters now that they are unused.
This should make it easier to enforce non-null values for `OspfInterfaceSettings` in the future.
> Use OSPF settings builder in tests

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
because NXOS always propagates EVPN type 5 routes for all neighbors in non-default VRFs
> NXOS: setting ipv4 unicast to always true for L3 VNIs

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map_multiple_chained_continue_entries
- use CallExpr instead of CallStatement for continue statements and
subordinated policies (e.g. redistribution)
- test ip community-list expanded semantics
- add end-to-end test involving complicated route-map with multiple
continues and expanded community-list
> Cisco NX-OS fix RoutingPolicy conversion

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusNcluConfigurationTest.java
To determine an active peer's local IP, we currently look for interfaces whose subnet includes its remote IP (that therefore could connect with the intended remote peer), then assign the first such interface's IP as the peer's local IP. This PR improves the process by ruling out an interface whose address *is* the peer's remote IP.
> Cumulus: Improve local IP inference for BGP peers

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
Update preprocessor for renamed rules.
> NX-OS: no switchport grammar

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Vrf.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Cisco says ([here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/vxlan/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x_chapter_0100.html)) that route distinguisher for L2 VNIs should be a combination of Router ID and `32767 + VLAN number for the VNI` (and not the VRF ID)
> NXOS: Fix RDs for L2 VNIs

- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/CandidateOspfTopology.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserEnumSetTest.java
- projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityQuestion.java
- projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityQuestionPlugin.java
- projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
- questions/experimental/ospfSessionCompatibility.json
- tests/questions/experimental/commands
- tests/questions/experimental/ospfSessionCompatibility.ref
Update `ospfSessionCompatibility` to include unestablished/incompatible sessions, with a new `Session_Status` column.
> Ospf session compat q

- questions/Parameters.md
OSPF session status spec was added in https://github.com/batfish/batfish/pull/4694, update `Parameters.md` documentation to reference this.
> Update specifier documentation to reference OSPF session status spec

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
As before,
a b?
| a? b
replaced with
a b?
| b
> NX-OS: remove adaptive prediction from i_bandwidth

- projects/batfish/src/main/java/org/batfish/config/Settings.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosCombinedParser.java
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
> NX-OS: flip new parser on by default

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_vrf
- tests/parsing-tests/unit-tests-vimodel.ref
Note: made a change to init the VRFs upon their definition.
The only ref change is for a cadant file (!)
> Arista EOS 4.23 update VRF definition syntax

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpProcess.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
On a real device, this will cause them to be created at the appropriate vrf/global level.
> Arista: create BGP peers/neighbors declared inside address-family

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyTest.java
1. Don't assume ipv4 unicast is set.
2. Store settings per AF -- no functionality changes, just add a level of indirection.
This still doesn't do full computation of addpath, etc. for other AFs --
that's not supported in BDP either.
> BgpSession: better support for AFs

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_vxlan
Unless multicast is specified, no need to assume that's the default.
> Arista vxlan: do not default to multicast

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_line.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_line
`exec-timeout` is an optional statement after `line console` ([Cisco ref](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus5000/sw/fundamentals/521n11/b_5k_Fund_Config_521N11/b_5k_Fund_Config_521N11_chapter_0110.html))
> NXOS: More permissive  line console stanza

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
`variable` rule matches any token but newline.
`VARIABLE` token matches only things that are not otherwise keywords.
E.g., `12345` (a legal VRF name) matches `variable` but not `VARIABLE`.
> Arista BGP: use variable parser rule

- projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors
Fix a crash in that case.
Had to move a bunch of code around and update test substantially to get the coverage I needed.
> Arista BGP: route map is not mandatory

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
Arista does not require L3 VNI -> VLAN mapping (unlike previous vendors) so need VI model changes. However, since we currently
do not do type5 routes for arista, hostfix until we tweak the VI model
> Hotfix L3 VNI crash

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_evpn
Because you can say EVPN. Or skip it. You know, it's like, whatever. ❄️
> Arista: more alternative syntax for EVPN

- projects/question/src/main/java/org/batfish/question/routes/RouteRowAttribute.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
- this will avoid collapsing attribute changes when the only change is for next hop interface
> Add next hop interface in route row attribute

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-units
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Parents are left up but have L2/L3 data cleared.
Children are just shut down.
> PAN: distinguish interfaces in no virtual-router

- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
We were checking if input files were env files but not doing anything different if they were.
@dhalperi any idea if we had some reason for retaining this structure?
> No more designated env files

- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
- projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
* Fewer passes over the entire file.
* One source of truth.
* More tests.
> VendorConfigurationFormatDetector: unify rancid code

- projects/batfish/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/BUILD
Unless we change grammar (which changes public APIs of the PaloAltoConfigurationBuilder), don't need to rebuild core Batfish module.
Ever closer to proper modularity.
> Palo Alto: separate into its own bazel completely

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/OspfProcess.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-ospf-cost-loopback
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos-ospf-cost-loopback
As per Cisco forum (https://community.cisco.com/t5/switching/ospf-cost-calculation/td-p/2917356) and GNS3 emulation results, the default OSPF cost for Loopback interfaces should be 1.
> IOS & NXOS: Correct OSPF cost for loopback interfaces

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRouteMetadata.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
- a related required change was introduction of a flag `generateLocalRoutes` in `ConnectedRouteMetadata.java` which can be set to `true` for vendors like NXOS. If set then dataplane will generate local routes even for prefix lengths < 32
> NXOS: Always generate local routes irrespective of prefix lengths

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Seeing this in some configs, and it worries me. 
1) normally this type of command is not under address family, but at process level 
2) Docs say Cumulus/FRR has multipath enabled by default, so not sure why this is necessary. 
For this reason, did not bother with extraction
Let me know if you have ideas on how to best to document this.
> FRR max-paths within address-family

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testrigs/multipath-multiple-as/configs/multiple_as_mixed_conflict
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
It seems to be common for users to not configure it for iBGP-only neighbors or peer groups.
> Juniper: ignore multipath multiple-as for iBGP

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsSet.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AsSetTest.java
Former implementation with `StringUtils.join(_value, ", ")` was using method `<T> String join(@Nullable T... elements)`, where `T` was inferred to be `Object`, so the result was just the default toString() for long[] `_value` with a comma at the end.
> Fix buggy toString method in AsSet

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
It doesn't make sense to return `true` from `hasCompatibleRemoteAsns()` if the ASN being tested is `null`, even if the peer's remote ASNs are `ALL_AS_NUMBERS`, because a session can't come up with a peer with no local AS configured.
> ALL_AS_NUMBERS only compatible with nonnull local AS

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address_group.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressGroup.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressObject.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-groups
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-objects
Attach tags to `address` and `address-group` objects for PAN.
[Tags are used to reference `address` or `address-group` objects in `dynamic` `address-groups`](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-admin/policy/monitor-changes-in-the-virtual-environment/use-dynamic-address-groups-in-policy).
> PAN: extract tags for address and address-group

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
Create dummy `address`/`address-group` to simplify their use in PAN configuration builder.
> PAN: create dummy address objects

- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-group-hybrid
Add test for hybrid `address-group`, testing behavior where an `address-group` contains addresses from different namespaces.
Test does not pass yet, see https://github.com/batfish/batfish/issues/4921.
> PAN: add test for hybrid address-group

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsSet.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AsPathTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AsSetTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- tests/parsing-tests/unit-tests-vimodel.ref
* Went with boolean instead of subclassing to:
* avoid JsonTypeInfo
* easier caching
* Added new logic to purge confederation AsSets from AsPath
> Allow AsSets to be of confederation type.

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
First commit adds `_bgpSessionProperties` field to `Environment`.
Second commit adds a `processBgpRoute()` method in `RoutingPolicy` that populates the `_bgpSessionProperties` field, and uses that method for routing policy processing in `BgpRoutingProcess`.
So far no routing policy exprs/statements use `_bgpSessionProperties` for anything, so no behavior should be changed.
> BGP session props in Environment

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/CompositeFirewallFilter.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/ConcreteFirewallFilter.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Zone.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/CompositeFirewallFilterTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-filters
* separate FirewallFilter into Concrete and Composite
* adapt extraction, vs model, conversion for these
* implement composite versions of access list and packet policy conversion
* add test
> Juniper: implement filter input-list and output-list

- projects/batfish/src/main/java/org/batfish/representation/juniper/IcmpLarge.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IpUnknownProtocol.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleThenInterface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NoPortTranslation.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/TcpFinNoAck.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/TcpNoFlag.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/TcpSynFin.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosOspfTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_ports/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_ports/CumulusPortsGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
Catch potential serialization issues early.
Everything was easy except for Cumulus FRR stuff, which seems to be not actually
testing extraction very well because it's reaching into the extractor instead of the
VS model. @anothermattbrown should take a look at that part.
> Parsing tests should clone before testing

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address_group.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressGroup.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/AddressGroupTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-group-dynamic
Add support for basic dynamic `address-group` filters (just filters expressing conjuncts for now).
Also in this PR:
* Update some type annotations for `AddressGroup`
* Add `Type` (`STATIC`, `DYNAMIC`, `EMPTY`) to `AddressGroup`
* Move from `getMembers().add(...)` to `addMember(...)` to help enforce address-group typing
> PaloAlto: dynamic address-group filters

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
Since ISPs are external to any network, prefer confederation remote ASes over the peer's local AS.
> ISPs: prefer confederation ASNs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
This is to hotfix the crash of `viModel`
Going to write some serialization tests for peer configs later.
> BgpPeerConfig: add forgotten JsonProp annotation

- README.md
Added `--name batfish` to the docker run command. Users can then do `docker stop batfish` or `docker restart batfish`, etc... without having to first find the container ID or the SLUG that docker automatically assigns.
> Assign name to container

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Parse PAN `profiles` and `profile-group` ([which allow for traffic content inspection](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-admin/policy/security-profiles.html)).
In the process, moved the `ss_null` rule under the `ss_common` rule to catch the null rules in all contexts that use `ss_common`.
> PAN: add profiles to null rule

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_log_settings.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
- tests/parsing-tests/unit-tests.ref
Parse more PAN `log-settings`.
In the process, made a few tokens case-insensitive (to work with capitalized auto-complete values) and fixed a NPE.
> PAN: add log-settings null rules

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Vlan.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-vlan
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Fix #4985
* Add support for interfaces declared inside of vlan, like `set vlans LAB-3 interface ge-0/0/20.0`. On an interface in `ACCESS` mode, this sets the (vendor-specific) access vlan name. On an interface in `TRUNK` mode, this adds the vlan to the trunk members.
* Set switchport mode `ACCESS` when interface is added to `family ethernet-switching` for the first time.
* Move setting of VI allowed vlans into the trunk handling conversion code.
* Fix native vlan-id for trunks (1 -> drop untagged frames by default).
* Fix reference tracking for vlan l3-interface
> Juniper: support for interfaces inside vlan definition

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- tests/aws/vimodel-example-aws.ref
Support multiple, equal-length paths in internet-node BGP process.
Fixes an issue where the internet node only support a single route through a single ISP when multiple, equivalent routes exist through multiple ISPs.
> Improve internet-node multipath support

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkConfigurations.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighborConfigId.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopology.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/CandidateOspfTopologyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfNeighborConfigIdTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TopologyContextTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/topology/OspfTopologyTest.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswerer.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/ospfsession/OspfSessionCompatibilityAnswererTest.java
- Key OSPF sessions additionally on ConcreteInterfaceAddress
- Check compatibility of addresses
- Consider all addresses instead of just primary
> Fix OSPF session semantics for interfaces with multiple addresses

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressObject.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/AddressObjectTest.java
Address object can only contain IP, prefix, or IP range, not an arbitrary IP space.
> PAN: More specific address in AddressObject

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
Since the RFC language is vague on whether next hop *must* be preserved
over eBGP within a confederation, align to GNS3 observations (at least
for juniper) and revert to overriding the next hop
> Update BGP next hop propagation

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoNatTest.java
- tests/parsing-tests/networks/unit-tests/configs/palo_alto/nat
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
- Removes redundant match src/dst IP guard from dest NAT transformations
- Filters out invalid NAT rules earlier in dest translation pipeline
- Adds warnings for invalid NAT rules and updates ref test to exercise those warnings
- Makes packet policies per zone, not per interface, because policies for any two interfaces in the same zone are currently identical
> PAN: Further NAT conversion cleanup

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/NatRule.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoNatTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nat-match-noop-rules
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nat-rules-empty-pool
Currently during dest NAT we only allow packets to match NAT rules that apply a destination transformation, and during source NAT we only allow matching rules that apply a source transformation. With this PR, those limitations will no longer exist; packets can match NAT rules that do not perform a transformation.
After #5046.
> PAN: Match NAT rules even if they don't transform

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/security-no-explicit-match
- tests/parsing-tests/unit-tests-vimodel.ref
If interfaces belong to a shared gateway or zone, flows leaving that interface that are denied by the gateway or zone outgoing filter must be dropped. However, `PermittedByAcl` falls through on explicit denies in the referenced filter. This PR modifies how the interface outgoing filter references its gateway/zone's outgoing filter so that explicit denies are no longer ignored.
> PAN interface outgoing filter fix

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
> for p2mp interfaces, the initial routes are interface IPs instead of

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-wildcards
To clarify. Before #5061 we only handled `<*>` as the wildcard so existing apply-path code worked without uncovering this bug. Terminal wildcard nodes in the apply-path should be executing matching logic on candidate child hierarchy nodes.
> Juniper: apply-path should match terminal wildcards too

- projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java
Consume `!` in Juniper wildcard expressions.
Still need to actually handle grammar, but this hot fix gets around crashes when `!` are encountered.
> Hot fix unsupported Juniper wildcard

- projects/batfish/src/main/java/org/batfish/representation/juniper/IsisLevelSettings.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-minimal
Unless you explicitly `set protocols isis level (1|2) disable`, the level is enabled.
> JNPR: IS-IS enabled unless explicitly disabled

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceLevelSettings.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceSettings.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-disabled-l1
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-interface-and-level-disable
Despite Batfish's support for it, there is no `enable` option at either [`[edit protocols isis level <level-number>]`](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/level-edit-protocols-isis.html) or [`[edit protocols isis interface <iface-name> level <level-number>]`](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/level-edit-protocols-isis-interface.html).
All IS-IS levels are enabled unless explicitly disabled in the process or interface. If `level <level-number> disable` is configured for either the process or the interface, the level is always disabled, regardless of what else is configured for the process or interface.
> JNPR IS-IS: Enable levels by default; no "enable" command

- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromProtocol.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/from-protocols
May need to eventually add an OSPF_ANY hack if Juniper allows you to match only OSPF intra-area routes (which is the route type for which we use `RoutingProtocols.OSPF`).
> JNPR: All OSPF routes match "from protocol ospf"

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/RoutingProtocolSpecifier.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/RoutingProtocolSpecifierTest.java
This way IS-IS external routes show up in `Routes` output when `protocols='isis'`.
> RoutingProtocolSpecifiers for external IS-IS protocols

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testrigs/isis-redist/configs/r1
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testrigs/isis-redist/configs/r2
- JNPR: Convert IS-IS export policy
- Apply IS-IS export policies in IBDP
> IS-IS redistribution

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/QualifiedNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
[juniper doc](https://www.juniper.net/documentation/en_US/junos/topics/concept/routing-protocol-static-security-route-preference-and-qualified-next-hop-understanding.html)
Qualified next-hop let's a user define multiple next-hops with different properties for a single static route.
> Juniper: Support qualified next hop

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospfInterfaceAreaAssignment
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
This PR is a stopgap solution to stop creating false interfaces in VI model when they are just referred in a configuration but not actually defined anywhere. 
It also gets rid of false warning `Cannot assign interface %s to area %s because it has no IP address.`
> Referred interfaces in JNPR: Don't create interfaces if not defined

- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
Still running all the same tests, but now more of the IPs and prefixes exist as named static variables and there are additional comments covering setup and expectations, so it's easier to tell what is being tested.
> IsisTest cleanup (no functional changes)

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-isis-passive
As per the note in documentation [here](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/passive-edit-protocols-isis.html):
> Configuring IS-IS on a loopback interface automatically renders it as a passive interface, irrespective of whether the passive statement was used in the configuration of the interface.
> JNPR: Loopbacks running IS-IS always passive

- WORKSPACE
- maven_install.json
See: https://github.com/bazelbuild/rules_jvm_external#pinning-artifacts-and-integration-with-bazels-downloader
Also add global exclusion for hamcrest version 1, which was missed earlier.
> bazel: pin maven deps

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisInterfaceSettings.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-disabled-l1
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-minimal
IS-IS processes generally have both level 1 and level 2 enabled if neither is explicitly disabled in the config. However, if either level is disabled on all interfaces in the IS-IS process (not counting loopbacks), then the process should also have that level disabled. This can affect routing; for instance, L1 routers should install an IS-IS default route to L1/L2 neighbors, which won't happen if we incorrectly designate the L1 router as L1/L2.
> JNPR IS-IS: Only enable level if enabled on interface

- WORKSPACE
They fixed buildozer auto-suggestions, likely.
https://github.com/bazelbuild/rules_jvm_external/issues/283
https://github.com/bazelbuild/rules_jvm_external/pull/285
https://github.com/bazelbuild/rules_jvm_external/commit/e62e81becc7a560e4cf8f606de1372162466e92c
> bazel: upgrade rules_jvm_external

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
Didn't seem to matter, but it's practice.
> Flow: use ordinal in hashCode

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
- projects/batfish/src/main/java/org/batfish/representation/aws/NetworkAcl.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/NetworkAclTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
and warn instead of throwing a batfishexception
> fix logic for identifying the subnet acl

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
1. Fix configuration format identification bug for juniper
2. Aggregate routes should become bgp when transiting nodes.
This is a stop-gap.
> Juniper: fix BGP aggregate export

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors
Only parsing, no extraction. Prevents NPEs in the extractor if a peer group is assigned to a IPv6 neighbor.
> Arista BGP: handle parsing of IPV6 neighbors

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/BgpProcess.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-multiple-routers
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-undeclared-peer
Diagnostics have reported some BGP extractor crashes in the old parser (we need to kill it off).
As a stopgap, I looked through for places invariants seemed violated, fixed them, and added some tests. Also rewrote the addFooGroup pattern to one that's more obviously correct.
> Cisco: a little more defensive programming on BGP peers

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/shutdown-switchport-inference-defaultl2
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/shutdown-switchport-inference-defaultl3
- consider occurrences of 'switchport' and 'no switchport' as evidence
the first time they appear in an interface definition
- actually track whether interface has been explicitly shut down
> Fix NX-OS default switchport inference

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4
- tests/parsing-tests/networks/unit-tests/configs/vxlan
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Goal: not have vxlan lines silently eaten (messes up initIssues for Arista in some cases)
Since we have recover, this should be fine.
Test removal: Doesn't seem like a valid command on cisco. Closes thing I found is this: https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/cether/configuration/xe-16/ce-xe-16-book/vxlan-gpe-tunnel.html
For which we currently have no support anyway.
Thoughts?
> Cisco: do not ignore vxlan commands

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VniSettings.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VniSettingsTest.java
- projects/question/src/main/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswerer.java
- tests/parsing-tests/unit-tests-vimodel.ref
Working towards splitting L2 VNI settings from L3 VNI settings, don't really want the JSON/comparable overhead here.
> Stop Json-serializing VNI settings

- projects/batfish/BUILD
- projects/batfish/src/main/java/org/batfish/representation/aws/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/matchers/BUILD
- projects/batfish/src/test/resources/org/batfish/representation/aws/BUILD
Enabled testing AWS in isolation:
```
bazel test //projects/batfish/src/test/java/org/batfish/representation/aws/...
```
Can also add `//tests/aws/...` if you like.
> aws: separate out bazel

- skylark/pmd_test.bzl
They can now be skipped with --test_tag_filters=-pmd_test
> bazel: add tag pmd_test to pmd tests

- projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
- projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java
- projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRoleDimension.java
- projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java
- projects/batfish-common-protocol/src/main/java/org/batfish/role/RoleDimensionMapping.java
- projects/batfish-common-protocol/src/main/java/org/batfish/role/RoleMapping.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/role/InferRolesTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/role/NodeRoleDimensionTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/role/RoleDimensionMappingTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/RoleNameNodeSpecifierTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledNodeSpecifierTest.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/specifier/LocationSpecifierTest.java
- projects/batfish/src/test/java/org/batfish/specifier/NodeSpecifierTest.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkNodeRoleDimensionResource.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/RoleDimensionMappingBean.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/RoleMappingBean.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/NetworkNodeRolesResourceTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRolesDataBeanTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/RoleDimensionMappingBeanTest.java
- projects/question/src/main/java/org/batfish/question/InferRolesQuestionPlugin.java
- tests/roles/inferRoles.ref
- tests/roles/roles.ref
Updates role inference to the new roles format.
Also simplifies roles inference -- it no longer tries to automatically combine parts of a node name to identify the "one true role" but instead simply records each of the different parts as distinct role dimensions.
Also removed the case-sensitive flag from role specifications and questions, since it is not applicable to role names that are derived from node names (as those are always case-insensitive).
> Update role inference to the new roles format

- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionAnswererUtils.java
- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
- projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswererTest.java
Adding common address families between the two peers for successful sessions of status unique match. 
For other sessions (where remote was not uniquely found) leaving the address family empty, because we cannot say anything about the session which exists in that case.
> Adding address families to BGP Session Compatibility question

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
Fixes some issues uncovered by our validation.
Flood lists (and thus Type 3 routes) only apply to L2 VNIs.
> Make EVPN Type 3 routes for L2 VNIs only

- projects/question/src/main/java/org/batfish/question/specifiers/PathConstraintsUtil.java
- projects/question/src/test/java/org/batfish/question/specifiers/PathConstraintsUtilTest.java
For reachability, this means that the results for any constrained
startLocation will be a subset of the results for unconstrained.
> use ALL_LOCATIONS by default for startLocation

- projects/question/src/main/java/org/batfish/question/specifiers/PathConstraintsUtil.java
- projects/question/src/test/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswererTest.java
- projects/question/src/test/java/org/batfish/question/specifiers/PathConstraintsUtilTest.java
For reachability, this means that the results for any constrained
startLocation will be a subset of the results for unconstrained.
> use ALL_LOCATIONS by default for startLocation 

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer3Vni.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Vni.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Layer2VniTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesTest.java
- projects/question/src/test/java/org/batfish/question/switchedvlanproperties/SwitchedVlanPropertiesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswererTest.java
Tunnels are established in default VRF on most vendors, while VNIs are placed in tenant VRFs in batfish.
To have traceroutes succeed, add a srcVrf field to correctly source "tunnel" packets for traceroute
> Fix VXLAN edge establishment

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/MatchSessionStep.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/MatchSessionStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- Rewrite `MatchSessionStep` and `MatchSessionStepDetail`
- New field in `MatchSessionStepDetail`: `incomingInterfaces`
- Use new `MatchSessionStep` and its detail class in `FlowTracer`
- Tests:
- JSON serialization of `MatchSessionStep`
- Adapt `MatchSessionStep` in `TracerouteEngineImplTest`, make assertions for existence of `MatchSessionStep` in traces
> Include incoming interfaces in MatchSessionStepDetail

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/EvpnCumulusTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
Type 3 routes should not be merged into main RIBs. They are only used to
update L2 VNI's flood lists.
> Make EVPN type-3 routes non-routing

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Accept.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/FibLookup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/ForwardOutInterface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/MatchSessionStep.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/SessionAction.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/AcceptTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/FibLookupTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/ForwardOutInterfaceTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/MatchSessionStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- Make `SessionAction` JSON serialisable
- e.g. `{"type": "Accept"}`, `{"type": "FibLookup"}`
- e.g. `{"type": "ForwardOutInterface", "nextHop": {"hostname": "a", "interface": "b"}, "outgoingInterface": "a"}`
- Add `sessionAction` field in `MatchSessionStepDetail`
- Include session action when constructing `MatchSessionStep` in `FlowTracer`
- Test JSON serialisation for all `SessionAction`s
- Test construction and JSON serialisation of `MatchSessionStep`
- Test match session in traceroute implementation
> Include forwarding behaviour in MatchSessionStep

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusNcluConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
In line with what we do for other vendors (NXOS and Arista)
> Cumulus: convert L2 and L3 VNIs to separate structures

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- it does not serve any purpose to have an exit output Interface step like
`NULL_ROUTED(null_interface)`
as Routing step already has enough information.
> Don't add exit output interface step for null routed trace

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_evpn_l2_vni_only
Stop crashing DP if BGP VRF or L3 VNI is not defined.
ADR for context: https://docs.google.com/document/d/18-MeALfC2-XBkp-jo8k-c7kDxA8VrRt2Axn9stOvSBg/
> Arista: workaround for pure L2 VNIs

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_address_group.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_application.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_policy_rule.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_service.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/parsing/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/parsing/PaloAltoBaseLexer.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/quoted-values
Palo Alto item values containing special characters (including quotes) are enclosed in quotes in `show` output, e.g. consider a named structure `named struct`, whose description is `foo "inner ' text' ". Newline:\nSecond line.`:
```
"named struct" {
description "foo "inner ' text' ". Newline:
Second line.";
}
```
or
```
set "named struct" description "foo "inner ' text' ". Newline:
Second line."
```
Note the ambiguous syntax since inner quotes are unescaped.
This was causing issues where structures like this would end up consuming following config lines due to "unterminated" quotes.
-----
This PR updates lexing logic for PAN to terminate quoted strings when encountering the first appropriate end-quote character immediately followed by a newline.
> PAN: Support quoted values containing quotes

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDOps.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBddImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MemoizedIpAccessListToBdd.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PermitAndDenyBdds.java
- projects/batfish/src/test/java/org/batfish/datamodel/BddTestbed.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswerer.java
Introduces new class `PermitAndDenyBdds`, containing two BDDs representing an explicitly matched set of flows and an explicitly denied set of flows respectively. This paves the way for simplifications in `IpAccessListToBdd` that also make it flexible to types of ACL line with no concrete action.
> Introduce PermitAndDenyBdds

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/SessionMatchExpr.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/SessionMatchExprTest.java
This will be replacing the type of `sessionFlows` in `FirewallSessionTraceInfo` from `AclLineMatchExpr`.
> Add SessionMatchExpr as a simpler structure to represent session match criteria

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineEvaluator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
Hierarchy is now:
```
Evaluator implements GenericAclLineMatchExprVisitor<Boolean>
|
--- AclLineEvaluator implements GenericAclLineVisitor<LineAction>
|
--- AclTracer
```
So `AclTracer` still overrides the same match expr visit methods, and can freely override ACL line visit methods once there are line types for which separate tracing is desired.
> Make AclTracer go through AclLineEvaluator

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpNeighborAddressFamily.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbor_prefix_list
Support prefix lists in both directions.
Currently continuing to perpetuate the behavior where route map + prefix list defined at the same time is not supported.
> Arista BGP: prefix-lists as method of filtering on neighbors

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto_nested/PaloAltoNestedFlattener.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/multiline-token
During flattening, some tokens may span multiple lines (e.g. quoted strings: `"something\nsomething"`).  Currently, when the line map is being updated, these multiline tokens are not taken into account, so mapping for any line after a multiline token is shifted and incorrect.
-----
This PR takes into account multiline tokens when populating the line map.  After this PR, all lines in the output text corresponding to the multiline token are mapped back to the original config line containing the token start.
> PAN: handle multiline tokens better during flattening

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/MatchSessionStep.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/MatchSessionStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- Added new nullable field `transformation` in `MatchSessionStepDetail` as a set of `FlowDiff`s
- Rearranged transformation part of `processSessions` in `FlowTracer` in order to capture transformation behaviour before it's applied and before incoming ACL is applied.
> Include transformation behaviour in MatchSessionStepDetail

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
This is a bit of a stop-gap. Working on removing two (or three, depending on how you count) sources of truth for interfaces in VRFs.
> Remove interfaces from VRF as well as configuration

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/SetupSessionStep.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/SetupSessionStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- `SetupSessionStep` / `SetupSessionStepDetail` - Exactly the same as `MatchSessionStep` / `MatchSessionStepDetail`
- `FlowTracer` - Construct `SetupSessionStepDetail` with the session's incoming interfaces, forwarding behaviour and match criteria (not including transformation behaviour)
- Tests
- `SetupSessionStep`: constructor and JSON serialisation
- `TracerouteEngineImplTest`
- Add assertions in `testNewSessionsSingleHop` and `testNewSessionsMultiHop` that traceroute captures `SetupSessionStep` with correct details
> Add interfaces, forwarding behaviour and match criteria to SetupSessionStep detail

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlaneSettings.java
The two settings removed effectively are (and should be) always true.
> DataPlane settings: remove unused settings/code

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_af
Was missing a token and therefore was kicking us up to parent context/default vrf
> Arista BGP: fix address family rule inside VRF

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedByIpAccessLists.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/SourcesReferencedByIpAccessListsTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseTransformationRangesImplTest.java
Also some cleanup in the test class. The new method is not particularly needed at the moment, but will be useful in some forthcoming work.
> referencedSources method for multiple ACLs

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
when converting ospf settings for interfaces in cumulus, we currently need to skip interfaces like bonds to avoid null pointer failures.
> handle the case where vsInterfaces do not exists

- projects/batfish-common-protocol/src/main/java/org/batfish/question/searchfilters/DenyQuery.java
- projects/batfish-common-protocol/src/main/java/org/batfish/question/searchfilters/MatchLineQuery.java
- projects/batfish-common-protocol/src/main/java/org/batfish/question/searchfilters/PermitQuery.java
- projects/batfish-common-protocol/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuery.java
- projects/batfish-common-protocol/src/test/java/org/batfish/question/searchfilters/MatchLineQueryTest.java
- projects/question/src/main/java/org/batfish/question/FilterQuestionUtils.java
- projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java
- projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererDifferentialTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersQuestionTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersTest.java
- tests/questions/experimental/searchfilters.ref
Previously, SearchFiltersAnswerer processed ACLs of interest into modified intermediate ACLs, converted those to single AclLineMatchExprs, and from there converted to BDDs to find matching flows. This was only necessary in order to derive ACL explanations. As of #5334, ACL explanations are gone and we can now convert the original ACLs directly to BDDs without losing required information.
Recommend reviewing commit by commit. Second commit is a dummy to hopefully get the diffs to work better, but the third commit is a relatively independent refactoring of SearchFiltersQuestion to use a new class (SearchFiltersQuery) to represent its action (permit/deny/matchLine). Included it in this PR to avoid really sketchy tests where there were two conflicting sources of truth for …
> Refactor SearchFilters to use BDDs

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_network
Stay within ipv4 address family context
> Arista BGP: correct parse tree for network statements

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/eos/AristaBgpVrf.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_confederations
Will do conversion separately; Need to tweak VI to have a space instead of enumerations of peer ASes.
> Arista BGP: extraction for confederations

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/Evaluator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/IpAccessListRenamer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/IpAccessListToBddTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/PermittedByAclTest.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Now that #5355 is in, `defaultAccept` is never true. Also removed the IpAccessList `filter()` method that accepts a custom default action, as that argument was always `DENY` after removing `defaultAccept`.
> Remove defaultAccept field from PermittedByAcl

- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java
- projects/batfish/src/main/java/org/batfish/config/Settings.java
- projects/batfish/src/main/java/org/batfish/main/Driver.java
- projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
Remove a bunch of unused functionality in the logger for a clearer migration path forward to a real logger.
1. Remove log rotation
2. Remove `tee` flag, as far as I can tell no client is actually using it
> BatfishLogger: minor cleanup and simplification

- projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
- projects/batfish/src/main/java/org/batfish/config/Settings.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
> Batfish: delete unused warning suppression arguments

- projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
Should always be set to true, just like for IPv4 AF
> Arista BGP: evpn AF allow-remote-as-out

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TraceElement.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TraceElementTest.java
TraceElements are strings where substrings can be annotated with vendor
structure ids. They will be used for generating better filter traces.
They support two operations: serialization to JSON (preserving
annotations), and conversion to a string (discarding annotations).
> Introduce TraceElement

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Arista_bgp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_network
Missed the 'mask' keyword originally.
It won't appear in this format in show run, but you can type it (for
backwards compatibility, presumably).
> Arista BGP: fix grammar for legacy network specification

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java
- projects/question/src/main/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswerer.java
- projects/question/src/test/java/org/batfish/question/findmatchingfilterlines/FindMatchingFilterLinesAnswererTest.java
ADR on how AclAclLine actions are reported, and why we chose that pattern, [here](https://docs.google.com/document/d/13su6BNBAchEjZW2iqQV3sVZea2a4fm7dGazxlgigrjo).
> FindMatchingFilterLines: Stop using ActionGetter

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
If the peer group is referred to under address-family block, count the reference.
> Arista BGP: add number of references to peer groups

- projects/batfish/src/main/java/org/batfish/config/Settings.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoCombinedParser.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaRouterIdTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-filter-inactive/configs/as1
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-filter-inactive/configs/as2-advertise-inactive
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-filter-inactive/configs/as2-no-advertise-inactive
- projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-filter-inactive/configs/as3
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session-misconfigured/configs/r2
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session-no-update-source/configs/r1
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session-no-update-source/configs/r2
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session-no-update-source/configs/r3
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session-no-update-source/configs/r4
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/bgp-dynamic-session/configs/r2
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/arista-originator
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/arista-originator-undefined-rm
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
* `aristabgp` debug flag is now a noop
* `noaristabgp` debug flag now allows reverting to the old hybrid parser
* Fix up syntax in some of our older tests that use EOS configs
> Arista BGP: flip bit to new bgp parser

- projects/bdd/pom.xml
- projects/pom.xml
1. Improve name normalization
2. Document the BDD license as separate from project license.
> maven: update license mergers and document BDD licenses

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Fixes parser crash when we have to infer the sequence number for a route map for which no sequence numbers currently exist.
> FRR: assume zero for first unsequenced line

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_frr/snapshots/default-originate/configs/frr-originator
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_frr/snapshots/default-originate/configs/frr-propagator
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_frr/snapshots/default-originate/configs/frr-reoriginator
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_frr/snapshots/default-originate/configs/ios-listener
- tests/parsing-tests/unit-tests-vimodel.ref
Vagrant tests showed the following about FRR semantics
- if `default-originate` is present, a new default to sent toward the neighbor, irrespective of whether there is another default route in the RIB. (That is, other defaults are ignored.)
- default-originated routes do not go through the neighbor-level route map. (there can be a separate route map attached to default-originate command, but we don't support that yet.)
- without the default-originate, default is treated like any other route (i.e., propagated per policy).
> Frr fix default originate

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PermitAndDenyBdds.java
- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityRows.java
- projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswererTest.java
Previously, we were conservatively setting `diffAction` to `true` if the blocked line or any blocking line was an `AclAclLine`. This PR updates the answerer to more carefully examine blocking lines' `PermitAndDenyBdds`. Now `diffAction` is only true if there is a packet permitted by the blocked line that would be denied by one of its blocking lines or vice versa.
> FilterLineReachability: Better diffAction metric

- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpVrf.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
Add VI conversion for BGP VRF level network statements (not inside v4 address family stanza). If the address family is active, the prefixes in these statements are advertised like those inside the v4 address family. They are ignored if the v4 address family is not active.
> FRR: export networks at VRF level

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PermitAndDenyBdds.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/IpAccessListToBddTest.java
- projects/question/src/main/java/org/batfish/question/comparefilters/CompareFiltersAnswerer.java
- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
- projects/question/src/test/java/org/batfish/question/comparefilters/CompareFiltersAnswererTest.java
CompareFilters now uses the same metric for whether lines take different actions as FilterLineReachability.
> Clean up CompareFilters

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
Migrating to CumulusConversions introduced a bug where we were assigning an LLA to interfaces that didn't have address in interfaces file but had one in frr file. The older NCLU-based semantics were that LLA should be assigned only if there is no address in both files.
> FRR: assign LLA only after processing interfaces and frr files

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
ignore all interfaces that show up in cumulus interfaces configuration that should not interfaces in the VI model.
> FRR: fix NPE because of missing interface names

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusInterfacesConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfaceClagSettings.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfacesInterface.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
NCLU heritage meant that parsing and post-processing of loopback ("lo") being special-cased. We keep seeing more properties that are shared and the separation does not make sense. No functional change in this PR.
> FRR: merge loopback parsing with other interfaces

- projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererDifferentialTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersQuestionTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersTest.java
Previously, default start location was `AllInterfacesLocationSpecifier`, which limits flows to those originating on the device. Fixes #5342.
> SearchFilters default start location ALL_LOCATIONS

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
In BDP code, do not export routes with no-export community to external peers
https://tools.ietf.org/html/rfc1997
> BGP: honor no-export community

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractIpSpaceContainsIp.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EmptyIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpaceContainsIp.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpaceReference.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UniverseIpSpace.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AbstractIpSpaceContainsIpTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpSpaceContainsIpTest.java
This is to prepare for an IpSpace tracer implemented by extending the
visitor.
> Convert IpSpace::containsIp to a visitor

- projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- clean up repetitious code in CiscoNxosControlPlaneExtractor
> Factor out common listener methods from NX-OS extractor

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
No knob to turn it off. Behavior confirmed with GNS3
> Cumulus FRR: allow-remote-as-out is always true

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/TraceNode.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/TraceNodeMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/TraceNodeMatchersImpl.java
- projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
No user-visible changes, but is another step toward returning the trace trees produced by AclTracer to the user. In particular, it allows us to test the trace trees directly.
> AclTracer: return trace trees

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkFactory.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfArea.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfProcessTest.java
- projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpnGateway.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
Only remaining use is in `IspModelingUtils`, but deferring to when it can be analyzed on its own.
> NetworkFactory: remove almost all uses in production code

- projects/batfish/src/main/java/org/batfish/representation/cisco/AristaConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/arista-bgp-default-originate/configs/arista-originator
Fix a bug where all non-default routes would be blocked due to a bad routing policy If statement
> Arista BGP: fix routing policy for default-originate

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- tests/aws/vimodel-example-aws.ref
This change allows users to use @enter(internet) as a valid specifier, which also helps other analysis that wants to analyze traffic coming from "outside".
> Internet modeling: Use /29 instead of /30 for internet interface

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/FibLookupOutgoingInterfaceIsOneOf.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/FibLookupOutgoingInterfaceIsOneOfTest.java
Stops us from crashing viModel in networks where FLOIIOO is used
> FibLookupOutgoingInterfaceIsOneOf: fix buggy Json deserialization

- projects/batfish-common-protocol/.externalToolBuilders/org.eclipse.xtext.ui.shared.xtextBuilder.launch
- projects/batfish-common-protocol/.project
- should always disable xtext builder
- xtext builder causes bug where clean triggers rebuild regardless of
build-after-clean setting
> Eclipse disable bcp xtext builder

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TraceElement.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TraceElements.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/TraceTree.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/Tracer.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/trace/TracerTest.java
1. Don't toString lines ACL in traces
2. Make Tracer a bit smarter to ensure TraceTrees have a TraceElement at each node. When a subtree is missing a TraceElement, the root node is deleted. This means we can have multiple top-level trace trees.
> Simplify AclTracer

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TraceElements.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/Tracer.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
The goal of a filter trace should be to explain why the filter matched.
When the filter does not match, there's no need to generate a trace node
saying so. It's redundant with the testFilters answer row.
> AclTracer: don't trace default deny

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
By creating extra dummy BGP processes during conversion.
Fixes a dataplane crash. Follow-up to #5443
> Cumulus: fix conversion when only L2 VNIs are present

- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
- tests/aws/vimodel-example-aws.ref
The current `TraceTree` will look like 
```
Matched security group sg-1
Matched rule 0 within security group
```
I also added trace elements within `MatchHeaderSpace` for the acl lines generated for a single rule, but it seems `AclTracer` does not pick them up yet.
> Add trace elements in AWS security groups

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TraceElements.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
- tests/basic/testfilters.ref
Exclude the filter name and action, since they're clear from context.
Only show the index if there's no name.
> AclTracer: simplify default ACL line TraceElements

- questions/Parameters.md
some users are getting confused and forget to use // around the regex. hoping that the separation of examples helps.
> separate name and regex examples

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/trace/Tracer.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/TraceTreeMatchers.java
Makes AclTracer include TraceElements from AclLineMatchExprs in the generated trace.
> AclTracer: trace AclLineMatchExprs

- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
This would help us to provide more meta-data in the traces produced  by testFilters.
so a sample trace which is using this description would look like:
```
Matched security group SG-1
Matched source-address 1.2.3.0/24 (allow HTTP traffic 1) . 
Matched protocol TCP 
Matched source port 80
Matched destination port 80
```
Prioritizing IpRanges for now, can extend this to (source security groups or prefix list IDs) if we see more examples
> AWS IpPermissions: Storing description for IpRanges

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
IOS has security zones, and ASA has security levels. Previously both were converted to VI by a single method. This PR splits into two methods and simplifies the one for IOS. In future, we will change how we model ASA security levels in order to produce better testFilters traces
> cisco conversion: separate ASA and IOS zone conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ExprAclLine.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TraceElements.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
- projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/outliers.ref
- tests/basic/testfilters.ref
- tests/basic/viModel.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/roles/perRoleOutliers.ref
Not all lines should have trace nodes, e.g. lines batfish constructs to
encode vendor semantics but that do not correspond to the configuration
file in a meaningful way.
To preserve legacy traces, ExprAclLine.Builder will create a default
TraceElement from the line name if there is one and the TraceElement was
not manually set. To build a line with a name but no TraceElement, we can 
explicitly call `setTraceElement(null)`.
TestFilters can now return a list of ACL traces when the matched line
does not create a trace node but does create multiple subtraces.
> AclTracer: dont trace acl lines without a TraceElement

- .bazelignore
Comments break IDE integrations
> .bazelignore: remove comment, add new paths

- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
- tests/aws/vimodel-example-aws.ref
contents:
1. Refactored `IpPermissions.toIpAccessListLine` to generate one `ExprAclLine` per `IpRange`, per `SecurityGroup` and per `PrefixListId`. So now an `IpPermission` object can generate multiple `ExprAclLine`s. This was done to get desired form of traces and to also use the user-specified description at the rule level. Also the match condition for every line is an `and` of smaller `MatchHeaderSpace`s. 
2. Tried to get rid of obsolete `IpWildCard`s from `IpPermissions`
3. The name of an `ExprAclLine` will be duplicated if an IpPermission generates multiple `ExprAclLine`, but since now we don't use that name anywhere, it should not have any side-effect. Making it unique will make the code unnecessarily convoluted.
Testfilters trace using this PR looks like below:
> Adding traceElements to MatchConditions generated by IpPermissions + Refactoring

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpnGateway.java
- tests/aws/vimodel-example-aws.ref
No reason I can see to use two different IPs.
> AWS: Use the same link local IP on both ends

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
Add `LinkFragment` to `TraceElement` of "permitted by output filter" and "denied by output filter" lines.
> ASA: Add vendor structure link for "permitted/denied by output filter"

- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/IpPermissionsTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
- tests/aws/vimodel-example-aws.ref
- also does some refactoring to pass rule description to line's traceelement
NB (fixes a bug in https://github.com/batfish/batfish/pull/5471, where a security group used by multiple instances would only contain reference to the last one, if used as a source in IpPermissions)
> AWS Tracing: Extract and add rule description for rules with UserIdGroupPairs

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/EvpnType5CumulusTest.java
Type5 routes generate problems downstream (in Forwarding analysis) when we do vrf leaking
> Stop evpn type 5 route propagation

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Before, we always marked them as firewall filters/terms in the trace.
To do this better, make a trivial start at separating these in the VS.
* Security policies moved to their own structure
* Security policy terms are always concrete
* Plumb types down into the functions that make the ultimate ACL lines
> JunOS: trace firewall filters and security policies separately

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-class-of-service
- don't trip up on interface wildcards after `set class-of-service interfaces`
> Juniper class-of-service parsing

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacketLength.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpaceToFlow.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraintsUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketLengthTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/HeaderSpaceToFlowTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsUtilTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
PacketHeaderConstraints currently converts to HeaderSpace, which has limited expressiveness (e.g. you can't express "SSH or DNS"). These changes pave the way for us to convert PHCs to AclLineMatchExprs, which can express anything.
cc @yifeiyuan
> Some fixes to ease converting PacketHeaderConstraints to AclLineMatchExpr

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceLinkLocation.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceLocation.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/Location.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationVisitor.java
- projects/question/src/main/java/org/batfish/question/FilterQuestionUtils.java
- projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
Allows for easy removal of `LocationVisitor` method `onNode`.
> Add getNodeName to Location

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_ip_community_list.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_routemap.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityListExpanded.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityListExpandedLine.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityListStandard.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityListStandardLine.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/IpCommunityListVisitor.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetCommListDelete.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchCommunityTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/set_comm_list_delete_test
Fix Cumulus model for extended community-lists. A community list should be a collection of lines, each with an action and set of communities.
Add support for "set comm-list delete" with expanded community-lists.
Add VI conversion for standard community-lists.
Minor refactor in UTs.
> Fix Cumulus model for extended community-lists & add support for "set comm-list delete".

- projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InferFromLocationIpSpaceSpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/Location.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfo.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContext.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContextImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledInputValidator.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/MockSpecifierContext.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/TestSpecifierContext.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledIpSpaceSpecifierTest.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/specifier/IpSpaceSpecifierTest.java
- projects/question/src/test/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswererTest.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesTest.java
- projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityTest.java
- projects/question/src/test/java/org/batfish/question/searchfilters/MockBatfish.java
- projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersAnswererTest.java
- projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
- projects/question/src/test/java/org/batfish/question/testroutepolicies/MockBatfish.java
- projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererHelperTest.java
- projects/question/src/test/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswererTest.java
LocationInfo defines how a location should be used in batfish analyses:
whether a location should be used as an endpoint by default, the source
IPs to use for it when sourcing traffic, and (specifically for
InterfaceLinkLocation) the IPs of external devices (not modeled by
batfish) the link would get an ARP reply from.
This is a first integration step: only the source IPs of a LocationInfo
are used, and the generation of LocationInfo objects is only temporary.
Batfish is creating them for now; in a future PR they will be generated
by VendorConfiguration and/or external input. Also, in a future PR we
will serialize them to disk; for now we recreate each time they are
needed.
> introduce LocationInfo

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/Location.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfo.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/LocationInfoUtilsTest.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Adds a map Location -> LocationInfo to VI Configuration that conversion
code can populate. Overrides the default VI LocationInfo definition.
Snapshot owned IPs are subtracted from the source IPs specified in the
vendor-supplied LocationInfo.
> LocationInfo: infrastructure for VendorConfiguration to override

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsLocationInfoUtils.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPrivateSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationVpcPeeringTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsLocationInfoUtilsTest.java
LocationInfo for AWS Subnet locations (interfaces and interface links). Departures from VI behavior:
- InterfaceLocation:
- not a source
- InterfaceLinkLocation:
- not a source
- no external ARP IPs
> AWS: vendor-specific LocationInfo for subnet locations

- projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java
* only resolve the full list of all locations in the query once
* don't produce flows for all node locations unless there's a filter to
test
* a little bit of code and comment cleanup/addition.
> TestFiltersAnswerer: minor performance improvements

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/LocationInfoUtilsTest.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsLocationInfoUtils.java
- projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java
Default (VI) LocationInfo should not consider InterfaceLocations to be traffic sources. InterfaceLocations on hosts should be considered sources.
> Set LocationInfo for Hosts

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Task.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SnmpCommunity.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SnmpHost.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/NtpServer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/SntpServer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco_xr/NtpServer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco_xr/SntpServer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/FilterGroup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ServiceEndpoint.java
- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ServiceObject.java
- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ServiceObjectGroup.java
- projects/question/src/main/java/org/batfish/question/ospfarea/OspfAreaConfigurationQuestion.java
- projects/question/src/main/java/org/batfish/question/ospfsession/OspfSessionCompatibilityQuestion.java
Require explicit @JsonCreator annotation, even on constructors. Add a bunch that were missing.
> BatfishObjectMapper: disable inferring creators

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockForwardingAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDFibGenerator.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitor.java
- projects/batfish/src/main/java/org/batfish/bddreachability/ReversePassOriginationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/SessionCreationNodeVisitor.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFibGeneratorTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/InterfaceAccept.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/OriginateInterface.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/StateExprVisitor.java
New states are `OriginateInterface` and `AcceptInterface`. They have been integrated into the reachability graph as follows:
Replace the existing `OriginateVrf -> PostInVrf` edge with:
- Edge from `OriginateVrf` to each corresponding `OriginateInterface` state, with `srcIp` constraint to specify each interface
- Edge from each `OriginateInterface` to `PostInVrf`
Replace the existing `PostInVrf -> VrfAccept` edge with:
- Edge from `PostInVrf` to each corresponding `InterfaceAccept`, with `dstIp` constraint
- Edge from each `InterfaceAccept` to `VrfAccept`
For more details, see [design doc](https://docs.google.com/document/d/1iQB939MxY4cAsbZta3R-j47MCZAj7d4UEuppOYVnwvI).
> Reachability states for originate/accept at interface

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAppSpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserAppTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserEnumSetTest.java
Reclaim the old name since it was more consistent with our naming pattern.
> Remove duplicate app specifiers

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/LocationToOriginationStateExpr.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateExprToLocation.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisTest.java
- Adds BDDReachabilityAnalysis method `getSrcLocBdds()` to return a mapping of source `Location` to reachability BDD
- Adds version of `BDDReachabilityAnalysisFactory.bddReachabilityAnalysis()` that takes in a boolean `useInterfaceRoots`, which when set causes the analysis to use `OriginateInterface` roots instead of `OriginateVrf` roots
After #5566.
> BDD reachability: new methods/parameters for more flexibility

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/EdgeMatchers.java
And add comments to code, plus simplify with branch.
> BDDReachabilityAnalysisFactory: fix denied out

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddress.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddressExcept.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddress.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddressExcept.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDestinationAddressExceptTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDestinationAddressTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromSourceAddressExceptTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromSourceAddressTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/networks/unit-tests/configs/juniper_firewall
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
Use the actual text in the config instead of re-string-ifying the wildcard.
Additionally, track the any and any-ipv4 lines.
> Juniper: better traces for matching source-address,destination-address

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteDecoratorMatchers.java
- projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
This enables it to advertise those public IPs without preventing instance-instance traffic
on them.
> AWS: IGW should use non-forwarding routes for public IPs

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_community_list
This was parsed, but crashed in extraction.
> Arista: allow standard community-list without standard keyword

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
This option is already exposed in the main `bddReachabilityAnalysis()` method that takes all options as parameters. The new method is just for convenience when `useInterfaceRoots` is the only option for which you want to use a non-default value.
> Option to use interface roots in reachability analysis

- projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicPrivateSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
- tests/aws/vimodel-example-aws.ref
Before this PR, if a packet with an invalid private IP would show up at the IGW, it wouldn't be NAT'd (since there is no mapping) and would be sent to the Internet.
> AWS IGW: Deny invalid private IPs

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/test/java/org/batfish/dataplane/BUILD
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- tests/basic/traceroute-2-1.ref
The prior implementation unconditionally used _ingressInterface. This was bad for many reasons:
1. The interface on which a packet was received is not necessarily the interface
that owns the destination IP. In fact, this is common: e.g., for loopback
IPs.
2. Packets originating on a device and destined to that device have no ingress
interface. This was even worse: caused a crash because passing a null value
to the InboundStepDetail is an API violation.
> FlowTracer: record the correct interface for InboundStep

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
- tests/aws/topology-example-aws.ref
Ensures that disconnected nodes are placed into aggregates.
> AWS aggregates: use nodes (not edges) for computation

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStep.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
FlowTracer's originalFlow field is used to compute FlowDiffs and set up sessions
after transformations.  "Original" should mean "the flow that entered the hop".
Previously it meant "the flow at the beginning of the trace", which caused
incorrect diffs and sessions when there are more than one transformation in the
trace.
> FlowTracer: forkTracerFollowEdge should use currentFlow as next-hop's  originalFlow

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_rpl.g4
The code needs reworking: it's never safe for a parent to recurse into its child's context
if recovery is enabled.
For now, this works around a crash when recovery kicked in.
See https://github.com/batfish/batfish/issues/5625
> IOS-XR: work around a crash in route policy evaluation

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModel.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- tests/aws/init-example-aws.ref
- tests/aws/vimodel-example-aws.ref
- tests/basic/example-iptables-init.ref
- tests/basic/init-candidate.ref
- tests/basic/init-with-ba.ref
- tests/basic/init.ref
- tests/parsing-errors-tests/invalid-ip-no-verbose.ref
- tests/parsing-errors-tests/no-verbose.ref
- tests/parsing-errors-tests/recovery-invalid-ip-no-verbose.ref
- tests/parsing-errors-tests/recovery-no-verbose.ref
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/srx-testbed.ref
- tests/parsing-tests/unit-tests.ref
To prevent users from picking those modeled IP addresses. 
1. Moved what used to be the inner IspInfo class to its own IspModel class
2. Added an inner class (ModeledNodes) that contains both generated configs and layer1Edges.  (Earlier only configs were being generated, so we didn't a separate class.)
3. Changes to the IspModel class and ISP node generation to enable generation of Layer1 edges
4. Some variable renaming to make code easier to follow
> ISP modeling: Use LLA for Internet-ISP edges

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModel.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IspModelingUtilsTest.java
- projects/batfish/src/main/java/org/batfish/representation/aws/ConvertedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
- projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
- tests/aws/vimodel-example-aws.ref
And move the AWS border (IGW) to this version.
> ISP modeling: Support Border-ISP peering over unnumbered

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IspModelingUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ToSpecifierString.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Anchor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/AstNodeVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/InternetLocationAstNode.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/LocationAstNodeVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledLocationSpecifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ToSpecifierStringTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledLocationSpecifierTest.java
add `internet` as a shorthand for `@enter(internet[out])` to the location specifier grammar.
no tests yet -- seeking feedback on this approach first
> syntactic sugar for the internet source location

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/MatchHeaderSpace.java
- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
Before they would just be squished together:
* Matched ICMP type 8 Matched ICMP Code 0
Now they are separate.
> AWS: split match ICMP type and code

- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java
Earlier, we had a binary filter that dropped all untransformed packets for any reason. So, it was hard for users to tell why the packet got dropped. Now, they can tell if the packet got dropped because it didn't match a configured listener or because no valid target was found behind the listener.
> Granular filters for AWS LB

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDRepresentativePicker.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/HeaderSpaceToFlowTest.java
Previous algorithm: picked flows from BDDs by taking a list of constraints and
keeping the first match. The constraints were either very simple ("ICMP
echo-request") or fairly complex ("well-known source IPs to private IPs using
UDP traceroute"). After finding the first matching constraint, we'd fill in the
unconstrainted bits. For simple constraints, we ended up with a lot of "source
IP 0", "source port 0", etc. For complex constraints, the barrier was an
exponential explosion of simple constraints.
Instead, use a long list of "simple" constraints, which need not be related in
any way except that more preferred ones come earlier. This allows us to home in
on a good representative -- we can put very general nudges like "if possible,
exactly one of src and dst port should be ephemeral" …
> BDDFlowConstraintGenerator: change the algorithm

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/BlockReservedAddressesAtInternet.java
- tests/aws/vimodel-example-aws.ref
This is crucial to keeping examples working. Instead, nudge away from the doc subnets
when picking flows. TBD how we'll resolve permanently, but this is a good middle.
> BlockReservedAddressesAtInternet: allow documentation IPs

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDUtilsTest.java
- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/bdd/BasicTests.java
No need to materialize the inner nodes as BDD objects, reducing overhead
and making free on the outer BDDs effective.
> BDDUtils: move isAssignment internally

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
This follows our usual pattern that lets us preserve spaces/hidden chars.
> Frr: correctly extract text from parser context for warnings/todos

- projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
Do not assume that all file names must be directly under a top level folder like `configs` or `aws_configs`
> BatfishTestUtils: allow nested dirs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Anchor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserOneAppTest.java
The existing application specifier specifies sets of applications. This simpler one specifies a single application. Excludes set operations, port ranges, and partial specifications (e.g. "tcp" without a port).
> new single-application specifier grammar

- .gitignore
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_vrf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/StaticRoute.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/static_route
Previous pull request: https://github.com/batfish/batfish/pull/5691
This adds support for syntax such as:
ip route x.x.x.x/x Null0
ip route x.x.x.x/x eth0
ip route x.x.x.x/x blackhole
ip route x.x.x.x/x Eth0
Does NOT support `ip route x.x.x.x/x y.y.y.y/y Null0` although that is valid syntax, the parser will continue to error out on that as it did previously.
> Adding next-hop interface support to static routes for FRR

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
Remove `acceptingInterface` parameter; determine accepting interface inside `buildAcceptTrace()` based on flow's dst IP. Also forces `_vrfName` to be nonnull, which seems to already be guaranteed. Only impact on functionality should be for matched sessions with Accept action, where we will now choose the interface that owns the flow's dst IP as the accepting interface, rather than using the ingress interface.
> FlowTracer: Clean up buildAcceptTrace

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Anchor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserOneAppTest.java
Now:
`tcp` suggests `tcp/port number`
`udp` suggests `udp/port number`
`icmp` suggests `icmp/type/code`
`icmp/0` suggests `.../code`
I couldn't get the trailing space to work on longer strings like "tcp/ ", so I just removed the interleaving whitespace.
> improved autocomplete suggestions for single-application specifier

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpcPeeringConnection.java
- projects/batfish/src/test/java/org/batfish/representation/aws/VpcPeeringConnectionTest.java
Fixes a crash when peering VPCs across accounts. The original root cause was
using _accepterVpcId instead of _requesterVpcId in a check, but the check was also
checking the wrong property (VS checked, VI used). I rewrote the code entirely and
added a test.
> AWS: handle the case where vpc is in a different account

- projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
- switch client to use new call instead of get-object
- only store and load work json answer file through StorageProvider
- only one remaining use of v1 get-object after this
> Add v2 call to get work json answer file

- projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/FileBasedIdResolver.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/identifiers/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/identifiers/FileBasedIdResolverTest.java
- projects/batfish/BUILD
- supports relaxed restrictions on entity names
- prevents malicious path injection
> sanitize id paths via base64 encoding

- projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Vpc.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicPrivateSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTransitGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/UtilsTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/VpcTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/VpnGatewayTest.java
- tests/aws/topology-example-aws.ref
- tests/aws/vimodel-example-aws.ref
This PR fixes a behavioral bug where, for traffic coming in from entities such as TGW, VGWs, NGW, etc., VPCs would provide connectivity only to subnets that uses those entities for outgoing traffic. So, if traffic reached a VPC from a TGW for a subnet that did not use that TGW, that traffic would be dropped. Testing shows that such symmetry is not required and this PR fixes that. 
From a code perspective, two changes were made get the right behavior:
- proactively create VRFs on the VPC node for all entities such as TGWs that it connects to. Earlier, these VRFs were being created on demand when relevant routing table entries were encountered. 
- connect Subnets to these VRFs independent of whether they use that entity for its outgoing traffic.
> Asymmetric forwarding via VPC connections

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Account.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
This does not fix any bugs yet, but sets up infrastructure to do so. Goal here not to break any existing functionality.
> AWS: parse multi-account setups as one vendor configuration

- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
- projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/UtilsTest.java
Instead of crashing, log a warning and create an interface with no address
> AWS interfaces without valid address in the subnet

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/ConvertedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGateway.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpcPeeringConnection.java
- projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
Maps are painful to work with. So cleanup to 
1. return collection of configurations, which is what we want most of the time anyway
2. Introduce `get` and `add` helpers so we can easily track read/write access.
No functionality changes
> AWS: Cleanup ConvertedConfiguration

- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancerListener.java
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerListenerTest.java
- projects/batfish/src/test/resources/org/batfish/representation/aws/DefaultAction.json
This fixes a bug introduced in #5756
> AWS NLB: Fix the type in the constructor of default action

- library_deps.bzl
- maven_install.json
- projects/batfish/pom.xml
- projects/batfish/src/main/java/org/batfish/representation/aws/Account.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationErrorTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
- projects/pom.xml
This is not perfect, but lets us crash less at, a high level (still need smaller granularity). The issues should end up in initIssues.
cc @dhalperi I've caved and decided to bring in a mocking library so I can write more concise tests. Let me know if you think this is overkill (but I do see potential uses for it in other places).
> AWS: if region conversion crashes, continue processing

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationVpcPeeringCrossAccountTest.java
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/NetworkInterfaces.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/Reservations.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/RouteTables.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/SecurityGroups.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/Subnets.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/VpcPeeringConnections.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789012/us-east-1/Vpcs.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/NetworkInterfaces.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/Reservations.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/RouteTables.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/SecurityGroups.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/Subnets.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/VpcPeeringConnections.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/test-vpc-peering-multi-account/aws_configs/accounts/123456789013/us-east-1/Vpcs.json
Generalize peering creation logic to be cross-account.
> AWS: support cross-account VPC peerings

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
For some use cases, the table directly is better than the map.
> BDDReachabilityAnalysis: expose a (readonly) copy of the forward edge table

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGateway.java
- projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayTest.java
This will help choose an "authoritative" TGW in the future when we correctly convert 1-out-of-many TGWs when they are shared across accounts.
> AWS tgw: parse owner id

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledAutoComplete.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledAutoCompleteReferenceBookEntityTest.java
Clearer code, and eliminates a static analysis tool error about mutable final objects.
The error may have been a false positive, or you may be able to mess with
lambdas in ways you can't mess with functions.
> Parboiled: convert from Function to function and update references

- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ReferenceLibrary.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/referencelibrary/ReferenceLibraryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/ReferenceBookResource.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/ReferenceLibraryResource.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/ReferenceBookResourceTest.java
- remove IO from ReferenceLibrary class
- add load and store methods for ReferenceLibrary to StorageProvider
- update callers
> Move all ReferenceLibrary IO to StorageProvider

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/UnzipUtility.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorageDirectoryProvider.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/UnzipUtilityTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- Add StorageProvider methods for:
- loading and storing original snapshot zip
- storing individual snapshot input objects
- Update UnzipUtility to support unzipping from streams
- Follow-on work: similarly update forkSnapshot
> WorkMgr snapshot initialization move persistent I/O to StorageProvider

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModel.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/InternetGateway.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationNatGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicPrivateSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationPublicSubnetTest.java
- tests/aws/topology-example-aws.ref
- tests/aws/vimodel-example-aws.ref
* Eliminates a class of ISP bugs.
* Guarantees stability of names.
* Relaxes name requirements to any valid human name.
* Changes behavior of AWS (backbone -> isp).
> ISP Modeling: use Configuration#humanName instead of #hostname for name

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- canonicalize base dir on construction
- canonicalize all input and output paths
- throw if canonicalized input/output path is not subpath of base dir
> FileBasedStorage canonicalize base dir and validate input/output paths

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFirewallSessionTraceInfoMatchers.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFirewallSessionTraceInfoMatchersImpl.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java
After #5771. Creates VRF-scoped `BDDFirewallSessionTraceInfo` based on reachability graph. Fixes bidirectional reachability for inbound sessions.
Still to do:
- A visitor for identifying states that should cause a VRF-scoped session to be established
- Refactoring (lot of shared code between `computeInitializedIncomingSessions()` and `computeInitializedOriginatingSessions`)
- Tests
> Create VRF-scoped BDD firewall sessions

- projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/test/java/org/batfish/main/AwsParseWarningsTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
- remove poorly structured AWS tests
- pick a default region when AWS files provided in flat structure
- fix bug treating arbitrary path data as region name
- fix AWS test refs
- move related constants to FileBasedStorage
> Move vendor configuration parsing I/O to StorageProvider

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Answerer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
- remove TestrigSettings class
- replace with SnapshotId at client sitesd, since name is only field still
used
- remove extraneous Path logic from from {I,}Batfish
- delete checkSnapshotOutputReady
- move some constants previously used by TestrigSettings to FileBasedStorage
- use StorageProvider instead of TestrigSettings to write temporary
input files for tests
> Remove TestrigSettings and clean up unnecessary Path logic

- projects/batfish/src/main/java/org/batfish/bddreachability/SessionScopeFibLookupSessionEdges.java
- projects/batfish/src/test/java/org/batfish/bddreachability/SessionInstrumentationTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/SessionScopeFibLookupSessionEdgesTest.java
`PreInInterface` -> `PostInVrfSession` edges, which represent matching a firewall session with action `FibLookup`, now apply the transformation for that session. This won't change behavior because none of the currently-supported types of firewall sessions do a FibLookup with a transformation.
> Apply transformation in FibLookup incoming session edges

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
Fixes bug where for regions with only VPCs present (but no gateways, for example) we missed the correct placement of region into AWS aggregate
> AWS: fix aggregate generation for VPCs

- projects/allinone/src/test/java/org/batfish/question/traceroute/TraceroutePolicyBasedRoutingTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HopMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HopMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceMatchers.java
- projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java
Adds tests that:
- Flows destined for the ingress VRF will be accepted iff the packet policy does not reject them
- Flows that match a packet policy rule to do a FIB lookup in a second VRF won't be *accepted* into that second VRF, even if it owns their dst IP
Also refactored the test a bit:
- The test PBR policy's rules now match on protocols instead of dst IPs (specifically, TCP instead of 9.9.9.9 and UDP instead of 10.10.10.10). This was necessary to experiment with flows with different dst IPs.
- The `TracerouteAnswerer` method `getTraces` is now visible for testing, so this test doesn't have to extract traces from tables. The `TracerouteAnswerer` infrastructure that converts the result of `getTraces` into table answers is already tested separately.
> More traceroute tests for PBR

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/packet_policy/VrfExprNameExtractor.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDFibGenerator.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateExprToLocation.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitor.java
- projects/batfish/src/main/java/org/batfish/bddreachability/ReversePassOriginationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/SessionCreationNodeVisitor.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFibGeneratorTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/PbrFibLookup.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/StateExprVisitor.java
Replaces `PreInInterface -> PostInVrf` PBR edge with three new edges including a new state:
- `PreInInterface -> PbrFibLookup`
- `PbrFibLookup -> InterfaceAccept`, one per interface in the ingress VRF
- `PbrFibLookup -> PreOutVrf`, where the `PreOutVrf` VRF is the one referred to by the PBR FIB lookup
This setup allows flows destined for the ingress VRF to get accepted in that VRF after matching the PBR policy.
> Reachability: Let PBR flows get accepted

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
Reorder UDP (which includes UDP traceroute to the top) when in traceroute mode,
but otherwise continue to use flow constraints. This restores ICMP defaulting to
ECHO_REQUEST, and a few other similar improvements.
> BDDFlowConstraintGenerator: use flow constraints

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_line.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-line
- fix batfish/batfish#5831
- warn instead of crash for unsupported line ranges, i.e. where last
number of range end is smaller than last number of range start
- parse and ignore some other constructs
> Cisco IOS line parsing improvements

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/FilterStep.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
New VI filter is applied to outgoing flows, but matches on the original flow even if a transformation has occurred.
> VI infrastructure to filter on original flow

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacePropertySpecifierTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/InternetGatewayTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
They are for JSON only and should not be used other than implicitly by Jackson.
It wasn't hard to move all the callers off. I also added a missing convert check for the new filter.
> Interface: hide the fooFilterName setters and getters

- projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/IdResolver.java
- projects/batfish-common-protocol/src/main/java/org/batfish/identifiers/StorageBasedIdResolver.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/identifiers/TestIdResolver.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
- projects/coordinator/src/main/java/org/batfish/coordinator/id/IdManager.java
- projects/coordinator/src/main/java/org/batfish/coordinator/id/StorageBasedIdManager.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/LocalIdManager.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/QuestionSettingsJsonPathResourceTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/QuestionSettingsResourceTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java
- rewrite `getXXXId` APIs to return `Optional<XXXId>`
- return `Optional.empty()` instead of throwing when ID does not exist
- replace pairs of calls to `hasXXX`+`getXXXId` with single call to `getXXXId`
- add a ton of `checkArgument` calls to result of `getXXXId` to provide better error traces
- rewrite `deleteXXX` (mapping of name to ID) APIs to return boolean
indicating whether name was previously mapped (and successfully deleted)
- replace pairs of calls to `hasXXX`+`deleteXXX` with single call to `deleteXXX`
> Mitigate TOCTOU bugs related to IDs

- projects/batfish/src/main/java/org/batfish/job/BatfishJobExecutor.java
- projects/batfish/src/main/java/org/batfish/main/BatchManager.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/main/CoordinatorClient.java
- projects/batfish/src/main/java/org/batfish/main/Driver.java
- projects/batfish/src/main/java/org/batfish/main/Service.java
`Batfish` had pointers back to static `Driver` functions. This is a problem if there were to be another entry point that starts worker(s). Broke the cycle by factoring out helper classes that Batfish can depend on.
There is still too much `static`-ness going on (that's why `BatchManager` is a singleton) but can tackle that later if needed. 
No intended functionality changes.
> Break dependency cycle between Batfish and Driver

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
Bad equality check means route propagation (no next hop IP) was busted in some cases.
> Fix bug in IP computation for bgp dynamic sessions

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkePhase1Policy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-ipsec-gh-5849
- tests/parsing-tests/unit-tests-vimodel.ref
> IOS: fix a crash in malformed isakmp profiles

- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
Mild follow-up to review in #5842.
Most of the diff is just using the new `bdd_makesatnode` function.
> bdd: rewrite ref tracking and sat node creation

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDIntegerTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java
project() is similar to exist(), but existentially quantifies all variables not in the input var set. Simpler and more maintainable when you want to project a BDD onto a set of vars.
Using project() in session factory will clear the way for @corinaminer to add support for original-flow filters in reachability. In particular, she shouldn't need to touch the session factory again.
> Add BDD::project and use it in session factory

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/AllVlans.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/EthernetSwitching.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/VlanMember.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/VlanRange.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/VlanReference.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-vlan-access
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-vlan-all
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
- support access vlan specified as integer
- change VS model to look more like configs
- move guts of switching conversion to JuniperConfiguration
> Fix Juniper ethernet switching parsing

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
Do not crash conversion entirely if TGWs can't be converted. Missed this earlier.
> AWS: catch transit gateway conversion errors

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
Likely no effect in practice, but computing topologies in dependency order reduces
likelihood of recomputation due to cache clearing.
> computeDataPlane: compute L3 inline

- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGatewayRoute.java
- projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayStaticRoutesTest.java
- projects/batfish/src/test/resources/org/batfish/representation/aws/TransitGatewayStaticRoutesTest.json
TGW static routes are valid without defined attachments
> TGW static routes don't need an attachment

- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGatewayAttachment.java
Leads to a slightly better error message.
> AWS TGW: add enum for peering resource type

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/ServiceObject.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-gh-5875
> ASA: support service-object ip

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_virtual_wire.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_vlan.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Handle some more Palo Alto "empty" structure syntax
> PAN: handle more 'empty' syntax

- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/EdgeMatchers.java
- projects/batfish/src/test/java/org/batfish/bddreachability/SessionInstrumentationTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/SessionScopeFibLookupSessionEdgesTest.java
No functional changes, just cleanup from the stash.
* Factor out factory creation in BDDReachabilityAnalysisFactoryTest
* Make better use of EdgeMatchers#edge and remove other edge matchers
> Clean up reachability tests

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_log_settings.g4
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/template
Handle more `log-settings` syntax:
* More child-syntax: `config` and `userid`
* In an additional context: under `device-group` config
> PAN: handle more log-settings syntax

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Ignore `readonly` lines for now; these appear on Panorama devices, are related to managed firewall devices, and contain mostly redundant information we parse from the actual configuration.
> PAN: ignore readonly lines

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
If the source manager for the RemoveSourceConstraint has a nontrivial
isValueValue constraint (i.e. not the one bdd), it is not safe to merge.
Merging in that case would not impose that constraint in the reverse
direction of the edge.
> reachability: only merge RemoveSourceConstraint/AddSourceConstraint when safe

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-warning
For now, add panorama conversion warnings to main warnings object.
Note: we will likely need to rethink how we process conversion warnings for single-config-multi-device configs in the near future.
> PAN: add panorama convert warnings

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
Two fixes:
- On edges entering a node (starting at `PreInInterface`), the outgoing original flow filter constraint was added incorrectly such that transiting it backwards did not clear the outgoing interface constraint. Fixed by correctly using `Transitions.addOutgoingOriginalFlowFiltersConstraint`.
- On root edges starting with an originate state (`OriginateVrf` or `OriginateInterface`), we neglected to add the outgoing original flow filter constraint.
> Reachability: Outgoing original flow filter fixes

- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGatewayAttachment.java
- projects/batfish/src/main/java/org/batfish/representation/aws/TransitGatewayPropagations.java
- projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayAttachmentTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/TransitGatewayPropagationsTest.java
- projects/batfish/src/test/resources/org/batfish/representation/aws/TransitGatewayAttachmentTest.json
- projects/batfish/src/test/resources/org/batfish/representation/aws/TransitGatewayPropagationsTest.json
nothing deeper than parsing. prevents deserialization from barfing.
> Add another tgw attachment type (direct-connect)

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_device_group.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/DeviceGroup.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/device-group-attach-multi-vsys
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/device-group-attach-vsys
* Extract `vsys` - `device-group` association
* Handle simplest case where firewall is only associated with a single `device-group`
Cannot yet handle associating different `vsys` on the same firewall with different `device-group`s (see #5910).
> PAN: extract vsys device-group association

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/GeneratedRefBookUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- tests/aws/vimodel-example-aws.ref
1. Add a representative IP for Route53 that can be used by anyone to check connectivity to AWS 
2. Add generated ref books for prefix lists for AWS services that appear in snapshot data
> AWS service IPs

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
In some contexts, i.e. inside `template`s, there may not be a current vsys but there may be references to objects (not yet supported, but will be in the future).
This PR helps set up for tracking object references when there is no current vsys / avoids NPEs when there is no current vsys.
> PAN: avoid NPEs in template ref tracking

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressObject.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/IpPrefix.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/AddressGroupTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/AddressObjectTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/IpPrefixTest.java
Palo Alto devices support setting interface addresses from `address` objects. Therefore, `address` objects need to preserve the pre-canonicalized form of the prefix (e.g. `1.2.3.4/24` needs to be stored as such and not canonicalized to `1.2.3.0/24` at configuration-build time).
This PR adds a Palo Alto-specific structure that preserves pre-canonicalized ip prefix info and updates `address` objects to use it.
> PAN: preserve ip address for prefix objects

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpcEndpointGateway.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManagerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/VpcEndpointGatewayTest.java
Until now, we've required all interfaces on a given device to have nonnull `FirewallSessionInterfaceInfo` if the device can create sessions. Now we want some interfaces to be unable to create sessions for exiting flows. This change makes that possible.
Also properly enforces the invariant that a `FirewallSessionInterfaceInfo` can't have an empty list of session interfaces, and stops creating a `FirewallSessionInterfaceInfo` for an interface on AWS service gateways that surfaced this issue.
> Allow some ifaces on device to have null firewall info

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationSubnetTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- tests/aws/vimodel-example-aws.ref
Missed in #5902.
Also fix the conversion finalization code to have caught this bug retroactively.
> AWS: add interface name to security group ingress ACLs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractIpSpaceContainsIp.java
On a test using a large number of bulk traceroutes, most of the CPU time was going into
these two functions. Rewriting as for loops sped up the bulk traceroutes by between
1.2x and 4x.
This may be a java8 only thing, but the code is nearly as easy to read and faster.
> AbstractIpSpaceContainsIp: rewrite using for loops

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpPeerFilter.java
- projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpPeerFilterLine.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/arista/AristaConversionsTest.java
- projects/batfish/src/test/java/org/batfish/representation/arista/BUILD
- projects/batfish/src/test/java/org/batfish/representation/arista/eos/AristaBgpPeerFilterTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_peer_filter
Fist pass at implementing BGP peer-filters for dynamic neighbors.
> Arista: implement peer-filters

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/UnzipUtility.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/UnzipUtilityTest.java
If file entries appeared before directory entries, we would crash claiming we cannot make a directory.
This fixes that by only creating parent directories if they don't
already exist.
Note there is nothing in zip spec that says entries need to be ordered
in any way.
> UnzipUtility: do not assume specific order of zip entries

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/Breadcrumb.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
In some cases, flows that would be dropped by ACLs would be prematurely declared as looping.
> FlowTracer: refine loop detection to prevent false positives

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/AddressObject.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/InterfaceAddress.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/AddressObjectTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/address-objects
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-bad-loopback-addr
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-loopback-ref
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-loopback-ref-invalid
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-loopback-ref-invalid-range
Palo Alto devices let you specify a named address object instead of explicitly specifying an address for an L3 ethernet interface. This PR adds support for that.
Reference tracking PR will follow.
> PAN: support interface address from objects

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
Large, sparse Tables have poor performance on column-oriented operations:
e.g., get the "column vector" for a given column key is O(#rows) since
it involves one lookup in each row's hashMap.
Since fixpoint does continual row-oriented operations, backwards fixpoint does
continual column-oriented operations (as seen in the forward edge table).
Merely transposing the input table leads to poor performance, instead we should also
materialize the transposed table. This is most important in cases that run many
backwards fixpoints over the same table.
> BDD reachability analysis: materialize the transposed table for fixpoint

- projects/batfish-common-protocol/src/main/java/org/batfish/common/runtime/SnapshotRuntimeData.java
- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/runtime/SnapshotRuntimeDataTest.java
- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/snapshots/runtime_data/runtime_data.json
Pass `SnapshotRuntimeData` into `VendorConfiguration` so it has access to runtime data for all devices, not just its own.
This is needed for devices like Palo Alto Panorama (which configure multiple VI devices in a single VS config) to pull in runtime data for its child devices.
> Support runtime data for multi-device configs

- projects/batfish-common-protocol/src/main/java/org/batfish/common/runtime/SnapshotRuntimeData.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/runtime/SnapshotRuntimeDataTest.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
Enforce non-null hostname again for `getRuntimeData`, improve calling code.
> Cleanup after #5953

- projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/GroupWildcardTest.java
Juniper example:
interfaces {
"<ge-1/2/[5-8]>" {
description "These interfaces reserved for Customer ABC";
}
}
Siva example on Batfish SLack: dd.d[dd]d.*.*/d[dd] where d is a digit
> Juniper: add support for more characters in GroupWildcard

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_device_group.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Ignore profiles within device-groups on Palo Alto devices.
> PAN: ignore device-group profiles

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTest.java
Excludes application load balancers (which are unsupported) and their corresponding subnets, instance targets, and VPCs from the precomputed maps in AwsConfiguration. This will avoid setting up instance target interfaces/VRFs/routes for application load balancers' instance targets, subnets, and VPCs.
> Exclude application LBs from AWS precomputed maps

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_device_group.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Similar to https://github.com/batfish/batfish/pull/5961, ignore profile-groups within device-groups on Palo Alto devices.
> PAN: ignore device-group profile-group

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Parse and ignore security rule logging settings for Palo Alto devices.
> PAN: parse security rule log settings

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines
Ignore log-collector configuration on Palo Alto devices.
> PAN: ignore log-collector lines

- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
In every subnet with target instances and/or NLBs, adds static routes to every instance used as a target in that subnet's VPC. 
- For instance targets connected to the subnet, the static route forwards out the subnet's interface to that instance
- For other instance targets, the static route forwards out the subnet's interface to the VPC
- All have next hop IP AwsConfiguration.LINK_LOCAL_IP
> Static routes on subnet to instance targets

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/LoopStep.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Step.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/StepAction.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/LoopStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
Previously, looping traces ended abruptly without a step reflecting the
disposition. This was inconsistent with other dispositions (e.g.
InboundStep for ACCEPTED).
> traceroute: create a loop step

- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
Creates static routes in VPCs to instances within that VPC used as NLB targets. Static routes' next hops are the subnets connected to the target instances.
> VPC static routes to target instances via subnets

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsVpcEntity.java
- projects/batfish/src/main/java/org/batfish/representation/aws/ElasticsearchDomain.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- tests/aws/init-example-aws.ref
- tests/aws/topology-example-aws.ref
- tests/aws/vimodel-example-aws.ref
1. Earlier, Batfish was generating one node for an ES domain and connecting it to all the subnets. This was inconsistent with how Batfish models other multi-instance resources (RDS, LBs). 
2. Earlier, Batfish was not accounting for the fact that the number of ESD instances can be greater the number of subnets. 
3. Earlier, the domain name was being used as node name, which is not unique enough. An ESD in another region may have the same name.
> AWS ESD modeling fixes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionVrfInfo.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FirewallSessionVrfInfoTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationSubnetTest.java
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/viModel.ref
- tests/parsing-tests/unit-tests-vimodel.ref
Add a new FirewallSessionVrfInfo class with a single boolean field
fibLookup that determines whether the return flow should be forwarded
based on a FIB lookup.
Old behavior corresponds to fibLookup=true. Traceroute supports both
values, reachability support for fibLookup=false will be in a future
PR.
> generalize sessions created for flows accepted at a vrf

- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
These subnets need session info on their instance targets interfaces to the NLBs, but not the instance target interface to the VPC.
> AWS subnets with NLB but no instance target: remove session info

- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationLoadBalancerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java
- tests/aws/vimodel-example-aws.ref
- Gives NLBs static routes to their instance targets
- Makes load balancers do dst NAT only for instance targets, not src NAT (cherry-picked from #5982)
- Makes instances' originating sessions forward out interface instead of doing FIB lookups
> AWS NLB static routes to instance targets

- projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RegionTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
Note first commit message is inaccurate; it adds security groups on instance targets' interfaces, not NLBs'.
> AWS: Apply security groups to instance targets' new interfaces

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/ConvertedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
After #5992 (not because of dependency, just because of merge conflicts otherwise).
- Switch `_subnetsToInstanceTargets` and `_subnetsToNlbs` to key on subnet IDs instead of `Subnet` objects
- Switch `_nlbsToInstanceTargets` to key on load balancer ARNs instead of `LoadBalancer` objects
- Remove `_vpcsWithInstanceTargets` as it is unused
> AWS: simplify precomputed instance target maps

- projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
We use sessions to bring traffic from a target instance back to a load balancer, but we still need to apply network ACLs when crossing from subnets to VPCs or VPCs to subnets. Therefore a subnet's interface to its VPC needs session info with:
- the outgoing network ACL if the subnet has instance targets
- the incoming network ACL if the subnet has NLBs
- both if the subnet has both
To make life easier, just use both network ACLs in subnets' VPC ifaces session info.
> Fix subnet firewall session interface info

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/GitHub6004Test.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/gh6004
Fix #6004 - UDFs are not supported but they are warned on. cc: @SivaKesava1
> XR: parse and warn on ACL udf statements

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/GitHub6018Test.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/gh6018
> XR: basic support for bundle interfaces

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityContext.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySet.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchCommunitySet.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/SetCommunitiesTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
- CommunitySet has interning and jsonification already
- Compute standard and extended community sets on demand; we could memoize later
- Fixup callers
> BgpRoute: use CommunitySet instead of Set<Community>

- projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/aws/LoadBalancer.java
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java
Fixes a modeling bug, where Batfish assumed that cross zone meant that all AZs were fair game, when in fact only enabled AZs are fair game.
> NLB sends packets to enabled zones only

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java
Only actually used for IS-IS codepath right now.
> RouteAdvertisement: elide a copy when rewriting REPLACE for export

- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
The RibDelta already only returns one advertisement for each Route,
so the distinct is unnecessary. No stream, simpler code.
> RibDelta: skip an unnecessary distinct operation

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
1. Because it was not immutable, it was being copied ALL THE TIME.
On one firewall with a ton of named address objects, there was
a large performance hit.
2. Move sorting to the API.
> Configuration.ipSpaces: make immutable, sort only for API

- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
If we add a route and then immediately replace it, don't send a
withdrawal to our neighbors, and vice versa.
Before this PR, we sent the last action per route no matter what.
> RibDelta: compress canceling updates in the same round

- projects/allinone/BUILD
- projects/minesweeper/BUILD
- tests/java-smt/BUILD
This makes it easier to not run any tests that use z3
--test_tag_filters=-z3
I don't install z3 on my machines anymore now that no
core code uses it.
> bazel: add a z3 tag to tests that require it

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-gh-6042
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
> ASA: track ACLs used in crypto map matching address

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests.ref
No need to explicitly list the set of reference types.
> Arista: switch to exhaustive structure reference marking

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- tests/parsing-tests/networks/unit-tests/configs/arista_bgp_asn
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
> Arista: fix float in lexer

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpType.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIpProtocol.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacketLength.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPrefix.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDUtils.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
Fewer direct accesses to the underlying array.
> BDDInteger: introduce size()

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
Callers use fullSatOne only to bias towards a lower value. Move this bias into the satAssignmentToLong
function and let callers pass in simpler BDDs.
> BDDInteger#satAssignmentToLong: reduce requirement for fullSat

- projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/ICoordinator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- coordinator runs garbage collection by default every 10 minutes
- Implement garbage collection for FileBasedStorage
- delete files older than the oldest snapshot's creation time,
minus an extra skew allowance of 10 minutes
- delete:
- snapshot folders
- upload/fork zips
- answers
> Implement garbage collection for old orphaned data

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
With a little pre-work and moving the Host/VRF check up, we can
reduce from quadratic to linear complexity.
> BgpTopologyUtils: only check valid candidates for BGP peers

- projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
- projects/batfish/src/main/java/org/batfish/config/Settings.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/main/CoordinatorClient.java
- projects/batfish/src/main/java/org/batfish/main/Driver.java
- projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
This is not tested nor used. Additionally, it has some bad coding
practices like putting passwords in Strings instead of byte[]. Easier
to delete than maintain.
> coordinator: delete ssl support

- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- truncate test values of Instant.now() to seconds
- setLastModifiedTimemacos on APFS only supports granularity of
seconds
- fixes macOS bugs where same Instant was used for expungeBeforeTime and
setLastModifiedTime, yet subsequenet file last modified time preceded
expungeBeforeTime
> Fix FBS GC tests on macos

- projects/minesweeper/src/main/java/org/batfish/minesweeper/CommunityVar.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/Graph.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/abstraction/Roles.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDNetwork.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/PolicyQuotient.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/CommunityVarTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
When producing atomic predicates for community regexes as part of the Graph object, we intersect each one with a regex representing the language of community literals supported by Batfish. Doing so serves two purposes. First, it is necessary for correctness of the route analysis. For example, a regex like .* does not actually match any possible string since communities cannot be arbitrary strings. Second, it ensures that when we solve for community literals that match regexes, we will get examples that are sensible and also able to be parsed by Batfish.
This update broke some of the SMT-based minesweeper code, which also relies on the Graph, since community atomic predicates impose some new restrictons on community regexes.  Therefore we've also introduced a flag in Graph to cleanly …
> Graph: more correct community regexes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
IOS and IOS-XE, at least recent releases, normalize this way.
Arista is Port-Channel, but has been factored out.
NX-OS is port-channel.
Since we've moved those out, we can do this change.
Fixes a user complaint from `Marek Zbroch` of NTC on Slack.
> CiscoGenericParser: normalize to Port-channel

- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
Add a Difference column to the answers for SearchRoutePolicies, so that its answers have the same format as those of TestRoutePolicies.  The Difference column shows the differences between the input and output routes.
> SearchRoutePolicies: add a Difference column to the output

- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraintsTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
In BgpRouteConstraints, we now use a LongSpace rather than IntegerSpace to represent constraints on the local preference and the MED, since they are each unsigned 32-bit integers, which goes beyond the range of Java integers.  We also allow the constructor to pass in LongSpace.Builders instead of LongSpaces, and we add the range 0...(2^32-1) to the space if the builder only contains exclusions so the user doesn't have to explicitly do that.
> BgpRouteConstraints: replace IntegerSpace with LongSpace

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_device_group.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/DeviceGroup.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/device-group
Plus minor cleanup in testing:
* missing annotations
* not using getOrCreate outside of parsing.
> PAN: parse and extract device-group parent-dg

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
The process of exporting a BGP route changes the properties, so routes
that are distinct going in may be identical coming out. Before queueing
the routes for import on the neighbor, uniquify them.
On some large networks, this results in up to 100x fewer queued routes.
> VirtualRouter: uniquify export BGP Routes

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
Instead of doing a lookup once per exported route.
> VirtualRouter: compute neighbor process only once

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_routemap.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapSetDistanceLine.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaRouteMapTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map
1. start leaving a path to convert route-map to Arista format
2. implement route-map set distance
> Arista: route-map set distance

- projects/minesweeper/src/main/java/org/batfish/minesweeper/CommunityVar.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/CommunityVarTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/GraphTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
Community regexes in configurations need only match a portion of a community.  For example, the regex "^40:" matches any community of the form 40:N where N is a number.  Previously the symbolic route analysis required regexes to match entire communities, e.g. we would require "^40:.*" instead of "^40:".  Now we've lifted that restriction.
> Support partial-match community regexes in symbolic route analysis

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- fixes opaque exception when snapshot has no files but is otherwise packaged correctly
- leave decision whether to reject snapshot to higher level code
> Fix FileBasedStorage exception when uploading snapshot with no files

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationBuiltIn.java
Add `boxnet` and `traceroute` built-in PAN apps.
> PAN: add boxnet and traceroute built-in PAN apps

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_response.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-managed-device-hostname
This PR adds support for specifying Panorama-managed-device hostnames - from the output of the `show devices <connected|all>` command.
----
For example, using the Palo Alto [`pan-python` module](http://api-lab.paloaltonetworks.com/pan-python.html), you can pull managed device hostnames as follows (assuming your `.panrc` file is setup with connection info for `panorama`):
```
panxapi.py -t panorama -Xxo 'show devices connected' > tmp_file
panconf.py --config tmp_file --set  > show_devices_connected
```
This will produce a text file `show_devices_connected` containing something like this:
```
...
set response result devices 00000001 hostname firewall-1-hostname
...
```
The contents of this file can be appended to you Panorama configuration and fed into Batfish, which will apply hostnames …
> PAN: support specifying managed device hostnames

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
Need the original filename during conversion to populate trace elements.
> PaloAltoConfiguration: set filename in derived devices

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_concatenated/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_ports/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatvyos/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/iptables/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/mrv/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto_nested/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/eos/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/ios/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/nxos/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/vyos/BUILD
Error Prone will respect the `@Generated` annotation, but
ANTLR4 does not add it to generated classes:
https://github.com/antlr/antlr4/issues/2568
For now, manually tell error prone to ignore all such files.
> bazel: disable error-prone on generated ANTLR4 grammar

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
* Generate IA routes on initialization and import, as opposed to on export. This allows for better loop prevention by having a non-routing version of intra-area route as IA route in IA RIB.
* Implement split horizon rules for IA route propagation. Also helps loop prevention
> OSPF: improvements to inter-area route propagation

- library_deps.bzl
- maven_install.json
- projects/pom.xml
https://buildkite.com/batfish/batfish-vulnerability-scan/builds/133#04badada-83a6-45b2-8807-0088b5e11db5
vulnerable: jackson-databind-2.9.10.5.jar: CVE-2020-24616
upgrading to 2.9.10.6
> jackson: upgrade after CVE-2020-24616

- projects/bdd/BUILD
- projects/bdd/pom.xml
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java
Checking the lowest bit of a PRNG-generated integer does not work well with the
Linear congruential generatoras (LCGs) that are standard in Java. For the
original implementation, it resulted in only two different random assignments.
Check the middle of the int instead, and add a simple (deterministic) test of
the entropy.
> BDD: fix randomFullSatOne entropy

- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
Replace usage of deprecated Long(String) constructor with Long.valueOf(String).
> SearchRoutePolicies: remove use of deprecated Long constructor

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/FrrInterface.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
Behavior tested is that if you issue shutdown in Zebra, the interface is admin down.  If you configure "no shut" it just deletes the command - similar to unconfigured.  For that reason I made it non-null and initialized to false as default.  /etc/network/interfaces state parsing happens prior and also controls (hence I do not have a no-shut force admin up for Zebra)
> FRR: Adding support for interface shutdown command

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/HopInfo.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/LegacyTraceRecorder.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TraceRecorder.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
This is a behavior-preserving PR that lays the foundation for saving time and space usage in traceroute, by reusing previously-computed hops and (partial traces).
It introduces the `TraceRecorder` interface, which allows `FlowTracer` to stop tracing early if a previously-recorder trace suffix (or set of suffixes) can be reused. `TraceRecorder` takes as input a list of `HopInfo`, which augments the usual `Hop` with some extra metadata needed to determine when a trace suffix is compatible with a trace prefix, and to reconstruct concrete traces later. Most of that will show up in the next PR.
The big change in this PR is to FlowTracer, adapting it to `TraceRecorder` and building `HopInfo`. In particular, it needs to track which breadcrumb or new session was created for the current hop (if …
> introduce TraceRecorder interface

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/TraceAndReverseFlow.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/TraceAndReverseFlowTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/DagTraceRecorder.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TraceDag.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/BUILD
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/DagTraceRecorderTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/HopTestUtils.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TraceDagTest.java
`DagTraceRecorder` is a `TraceRecorder` that stores recorded traces in a DAG (`TraceDag`). This allows common subtraces to be shared, reducing time and space usage of traceroute.
This PR only adds the classes and tests. They are not being used yet.
> TraceDag and DagTraceRecorder

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
Use `DagTraceRecorder` to reuse work and previously-constructed `Hop`s when computing traces. Can be significantly more efficient for networks with high ECMP.
Note: I had previously proposed plumbing through a parameter or using a debug flag to control which `TraceRecorder` is used. I have not done that yet because I'm now unsure it's worth the trouble/mess.
> use DagTraceRecorder

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/FalseExpr.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TrueExpr.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
- projects/batfish/src/test/java/org/batfish/datamodel/acl/FalseExprTest.java
- projects/batfish/src/test/java/org/batfish/datamodel/acl/TrueExprTest.java
Add trace elements to `TrueExpr` and `FalseExpr` and update `AclTracer` to trace these.
> ACL Tracing: add trace elements to trivial exprs

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
- tests/basic/genDp.ref
Cleanup and comment the topology iteration code.
Fixed at least one bug: IsisTopology was not being updated every
iteration.
Moving topology iteration to after the dataplane, and pulling one out of
the while loop, also save one iteration of dataplane when the topology
doesn't change.
> IBDP: skip an unnecessary extra iteration and cleanup

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-vlan
Fixes #6183 
We were parsing, but ignoring the `vlan-id` statement for L3 subinterfaces. 
Docs: https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/vlan-id-edit-vlans-qfx-series.html
> Juniper: process subinterface vlan config

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassfulTest.java
Apparently Cisco IOS will redistribute short prefixes, too.
Fix batfish/batfish#6066
> RouteIsClassful: adjust for #6066

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
We disabled EVPN Type 5, but not this code. This results in a memory leak, as the
storage of the redistributed routes was never cleared.
> IBDP: skip main rib route distribution for EVPN Type 5

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoTraceElementCreators.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceBuiltIn.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-tracing
Add some shallow trace details for Palo Alto security rules. Specifically, adding basic info on first source address, first destination address, and first service matched for a given rule.
----
Some example traces for cross-zone policies might look like this:
```
Matched security rule RULE1
Matched source address
Matched address-group addr_group1
Matched destination address
Matched address object addr2
Matched a service
```
```
Matched security rule RULE2
Matched source address
Matched address value 10.10.10.10
Matched destination address
Matched address value 10.11.12.0/24
Matched service application-default
```
```
Matched security rule RULE3
Matched source address
Matched address any
Matched destination address
Matched address any
Matched service any
```
> PAN: trace details for security rules

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationGroup.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoTraceElementCreators.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/ApplicationGroupTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-tracing
Add top-level application tracing for Palo Alto security rules.
There is no recursive tracing for applications yet (similar to addresses and services).
----
For example, traces for rules matching an `application` might look something like this:
If the rule specifies an application group and a descendant of that group is matched:
```
Matched security rule RULE2
Matched source address
Matched address object addr2
Matched destination address
Matched address-group addr_group1
Matched service application-default
Matched application-group app_group1
```
or if the rule specifies an application directly, which is matched:
```
Matched security rule RULE2
Matched source address
Matched address object addr2
Matched destination address
Matched address-group addr_group1
Matched service …
```
> PAN: add application trace details for security rules

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
When initializing the BGP iteration:
1. parallelize over nodes
2. For N virtual routers on a node, call `mergeBgpRoutesToMainRib` N times instead of N^2 times.
> ibdp: optimize computeIterationOfBgpRoutes

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PrefixTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- tests/basic/genDp.ref
Try 2! This time, with a thread-safe `PrefixTracer`.
> bdp: remove queues for sending BGP messages

- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java
- projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/IpPermissionsTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java
- tests/aws/vimodel-example-aws.ref
ACLs representing a security group's ingress permissions has 1 line per ingress rule; same idea for egress permissions.
> AWS: ACLs representing security groups have 1 line per rule

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LongSpace.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_route_map.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapEntry.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchAsNumber.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapMatchVisitor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map
https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/nxos/commands/bgp/match-as-number.html
This is used
>  to provide a list of AS numbers or an AS-path access list using a regular
>  expression. BGP uses this match criteria to determine which BGP peers to
>  create a BGP session with.
> NX-OS: route-map match as-number

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
The code was matching not only files in the `configs` directory but also other files that started with `configs`.
> FileBasedStorage: Only match files in directory

- projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
The memoized _allRoutes can be computed on demand.
> AbstractRib: slightly smaller serialized size

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnRib.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
This way it is far less likely that BGP/EVPN rib (or other code) can modify the main RIB w/o going through proper channels
> Rib: factor out a read-only interface.

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
two versions: 
1. global init, local to the VR
2. topology-dependent init, called each time new topologies are computed.
> BDP: Split VR initialization into two steps

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CollectionUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CollectionUtilTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTreeTest.java
1. flatten actions
Previously RibDelta._actions was a sorted map from Prefix to list of
advertisements for that prefix. The only use of the map was to
efficiently retrieve the keyset for getPrefixes. However, getPrefixes
is called at most once, and often 0 times. So we should only pay to
collect and dedup the prefixes if it's called.
2. avoid using Builders when possible 
Particularly in hot code. The builder allocates a linked hash map,
copies all the advertisements in, and then copies them out to a list
on build.
> RibDelta optimizations

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Since Java parallel streams are not self-balancing, it pays to randomize files.
It is common that
filename -> device role
and it is almost certain that
device role -> configuration complexity -> parsing work
so not grouping by name is likely to pay off.
> Parsing: shuffle jobs

- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/arista/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
- projects/batfish/src/test/resources/BUILD
- projects/batfish/src/test/resources/log4j2.properties
For some batfish package tests, quite useful to enable logs in tests. Helped me debug a whole bunch. By default log level error, but folks can change locally as required.
> Some tests: print logs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ConvertConfigurationAnswerElement.java
- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java
- projects/question/src/main/java/org/batfish/question/UnusedStructuresQuestionPlugin.java
- projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerer.java
- projects/question/src/main/java/org/batfish/question/referencedstructures/ReferencedStructuresAnswerer.java
- projects/question/src/test/java/org/batfish/question/UndefinedReferencesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/UnusedStructuresAnswererTest.java
- projects/question/src/test/java/org/batfish/question/definedstructures/DefinedStructuresAnswererTest.java
- tests/aws/init-example-aws.ref
- tests/basic/example-iptables-init.ref
- tests/basic/init-candidate.ref
- tests/basic/init-with-ba.ref
- tests/basic/init.ref
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/srx-testbed.ref
- tests/parsing-tests/unit-tests.ref
Changing from `SortedSet<Integer>` to `IntegerSpace` is a dramatic reduction in storage, especially for definition lines. In one large network, halfway through parsing there were about 60M objects in memory, of which 34M were in `DefinedStructureInfo`.
By using `IntegerSpace` instead, we reduce sets to ranges and dramatically cut down on the number of objects maintained. Only internal storage changes - see ViModel diffs. Question answers stay the same.
> Defintion/Reference: Reduce space used

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoBidirectionalBehaviorTest.java
- projects/question/src/test/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswererTest.java
DP should not be the source of truth for configurations.
This also should unblock some follow-up optimizations where we do not serialize Nodes to disk
> Dataplane: remove configurations

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PrefixTracer.java
* a class that is static does not keep a pointer to its parent, using much less storage
* simplify the equals function
> PrefixTracer: fix Neighbor inner class

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PrefixTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/PrefixTracerTest.java
Defaults to empty.
For now, developers who want to trace prefixes have to change the code.
Future work for plumbing this through for users to control.
> PrefixTracer: add ability to trace only a certain space

- questions/experimental/searchRoutePolicies.json
- tests/questions/experimental/searchRoutePolicies.ref
Updates the long description of the searchRoutePolicies JSON question to describe the current status in terms of feature support.
> Search route policies: document the current status

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
I have convinced myself type5 route propagation cannot work correctly until we implement local bgp ribs. Removing broken (and commented out) code
> bdp: remove broken code

- projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IbdpResult.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PartialDataplane.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/PrefixTracerTest.java
Trying to optimize space used by final DP by removing all nodes and prefix tracer info from it.
Also, instead of mucking with suppliers, trying to materialize all data in DP on creation. 
This means, to speed up partial DP construction during DP computation, factor out a partial DP class that only does portion of the work.
> Dataplane: materialize on creation, separate full and partial DPs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ConvertConfigurationAnswerElement.java
- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java
- projects/question/src/main/java/org/batfish/question/referencedstructures/ReferencedStructuresAnswerer.java
- projects/question/src/test/java/org/batfish/question/UndefinedReferencesAnswererTest.java
- tests/aws/init-example-aws.ref
- tests/basic/example-iptables-init.ref
- tests/basic/init-candidate.ref
- tests/basic/init-with-ba.ref
- tests/basic/init.ref
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/srx-testbed.ref
- tests/parsing-tests/unit-tests.ref
It's expensive in rare cases, and also significantly more expensive to turn into
IntegerSpace dynamically (deep in a nested map).
> Revert the referenced structures part of batfish/batfish#6249

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
Note that the builder has no context that it needs to preserve between
loops. By moving the builder into the loop, the memory it uses can be
freed when the loop ends.
> IBDPE: keep partial dataplane entirely in the loop

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
No need for it, since DP no longer keeps `Node`s (after #6257)
> DP: make core classes not serializable

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceLinkLocation.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceLocation.java
This is basically similar to batfish/batfish#3855: hash codes should not be the same even if the two fields are.
> Location: subclasses should have different hashes

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- tests/parsing-tests/unit-tests.ref
This is apparently really common behavior - show run all on many vendors
will include OSPF defaults. So this is not an indication of a likely
misconfiguration.
> Cisco-style: stop warning about OSPF settings on interface not in an area

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrfd-address-family-export-map
Fixes https://github.com/batfish/batfish/issues/6235
> Parsing for vrfd address-family export map

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
Listing reference types explicitly is important for structures that can be used
with abstract references, aka, ip access-list which can often refer to one of
half a dozen types. It's not necessary for things like route-map or crypto
constructs that are not referenced in an ambiguous way.
Remove this listing, and hey, find a bug or two on the way.
> IOS: stop explicitly listing reference types for concrete structures

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
Minor cleanup, since we have the ability to log well with log4j now.
> ibdp: stop using batfish logger

- projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpNextHopUnchangedTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
Because that's how BGP actually works.
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-3s/irg-xe-3s-book/bgp-support-for-next-hop-address-tracking.html
> BGP ribs: do not merge routes with unreachable next hops

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchExprEvaluator.java
Streams are actually fairly expensive over small sets, as is the common
case for these use cases.
> CommunityMatchExprEvaluators: rewrite streams as loops

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
Enabling backup routes helps us handle networks where there is temporary flap and best routes get withdrawn (and thus must be replaced by previously-seen not-withdrawn routes)
> BGP RIBs: enable backup routes

- skylark/ref_tests.bzl
This tells Bazel that the test requires 4 CPUs to run. On enormous machines,
tests will run in parallel, on laptops tests will run serially or maybe 2 at a
time. This strikes a better balance than exclusive tags.
> ref_tests: switch to cpu:4 from exclusive

- .pre-commit-config.yaml
Otherwise, pre-commit will take the list of changed files and try to run
multiple invocations in parallel, which will be doing redundant work.
> pre-commit: use pass_filenames false on global checks

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
- tests/basic/genDp.ref
No need to run extra routing iterations if the topology didn't change.
> bdp: optimize to run fewer topology iterations

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
Instead of making a singleton RibDelta and flattening it, make a RouteAdvertisement
and flatten only when we already have a RibDelta.
> BgpRoutingProcess: simplify isNewSession handling

- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/destination-nat-panorama
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/device-group-shared-inheritance
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/source-nat-panorama
Palo Alto devices don't allow rule names to be reused across pre- and post-rulebase, so don't do that in our test configs.
No functional change in this PR.
> PAN test configs: don't reuse rule names

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
* In `Node` have `getVirtualRouters` (collection) and `getVirtualRouter(name)`
to avoid iterating over maps where we don't need them. Makes the code simpler to read, IMO.
* Introduce  `getVirtualRouterOrThrow(name)` any time we expect VR to
exist that throws with a meaningful message instead of an NPE
No DP functionality changes.
> bdp: stop exposing map of virtual routers

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_extcommunity_set.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/ExtcommunitySetRt.java
As always, parents should almost never call into their children's context.
Fixes batfish/batfish#6302. Note that the actual code inside that issue is wrong, the second number
has to be between 1 and 65535.
> XR: fix a crash in ExtcommunitySetRt

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- tests/parsing-tests/unit-tests-vimodel.ref
This should be determined (and possibly overridden) in parsing/conversion stages
> EIGRP: move admin cost computation out of dataplane

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_virtual_router.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-ecmp
ECMP being on is very common, and is our default. So do not warn to reduce
user confusion.
Only warn if ECMP is explicitly disabled for IGP, which we do not support in VI.
> PAN: parse virtual router ECMP, stop warning

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- tests/parsing-tests/unit-tests.ref
We've learned that because the lexer uses semantic predicates in the `VARIABLE` token,
such lexing decisions are not cached. To improve on this, add back many of the most
common lexer tokens (in `show run all`) to the grammar.
> Arista: add more commonly-used lexer tokens

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
1M is only 8MB of pointers, and even our example network gets there
for some questions.
> BDDPacket: increase the size of the initial number of nodes

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
- tests/parsing-tests/networks/unit-tests/configs/cisco_misc
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
> Cisco: parse and track refs in ip[v6] local policy route-map

- projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/GroupWildcardTest.java
Juniper documentation says that ! means character class negation and does not mention ^,
but open sources users have used ^ successfully.
Fix #6059.
> Juniper GroupWildcard: treat carat like ! in a character class

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- tests/parsing-tests/networks/unit-tests/configs/ios_standby
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3750x_3560x/software/release/12-2_55_se/configuration/guide/3750xscg/swhsrp.html
> All Layer 3 interfaces must have IP addresses assigned to them.
Downstream code in IpOwners chooses an HSRP master with tiebreak
based on L3 IPs, which could crash in some scenarios (multiple
interfaces with equal priority, at least one of which had no
IP.)
> IpOwners: only consider HSRP interfaces with L3 addresses

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/collections/InsertOrderedMapTest.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java
* Implement a LinkedHashMap-like Map with extra APIs for reordering keys
* Use it in PAN configuration. Lays groundwork for supporting moving of security rules
> PAN: switch to custom insert-order data structure for security rules

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_vsys.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/move-rulebase-security
Allows moving security rules to top/bottom or before/after a specific rule
Also supports pre/post rulebases
> PAN: support for "move rulebase security" commands

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/security-rule-tag
While not strictly necessary for analysis, this is QOL improvement that trims down potentially hundreds of parse warnings.
Docs:
https://knowledgebase.paloaltonetworks.com/KCSArticleDetail\?id\=kA10g000000ClEnCAK\#:\~:text\=Creating%20Tags,inbound%20rule%20and%20click%20OK.
> PAN: parse and extract security group tags

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
This make sure that tracing and source metadata are correct even when
producing an ACL with a different output name,
> JunOS: keep the original filter and term names during conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/question/src/main/java/org/batfish/question/FilterQuestionUtils.java
- projects/question/src/test/java/org/batfish/question/FilterQuestionUtilsTest.java
Before it was only using fullSatOne, which leads to all zero bits.
To make this work I had to add a new API that preserves the BDD post-restriction, so that
caller can set the interface from the same assignment as the flow builder.
> FilterQuestionUtils: make it use TEST_FILTERS FlowPreference

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_application.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/application-ignored
Parses and ignores the following statements in the `s_application_definition` context:
- `default port tcp/1025`
- `category foo`
- `subcategory bar`
- `technology baz`
- `risk 1`
If any such statements appear anywhere in a config, a single umbrella parse warning will be generated (rather than a warning for every such line).
> PAN: Parse and ignore application statements

- projects/batfish/BUILD
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/main/VlanInterfacesTest.java
- projects/batfish/src/test/resources/org/batfish/main/testconfigs/vlan
If an interface is shutdown, it will not keep a Vlan up. (The autostate flag is
still supported below).
> Batfish: unusableVlanShutdown should only count active interfaces

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_service.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Service.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/service
This does not affect analysis, but is a QOL improvement that can trim down a number of parse warnings
> PAN: parse and extract service tags

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/BgpPeer.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp-multihop
Parsing, extraction, conversion.
The semantics are a bit unusual compared to other vendors: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClKkCAK
> PAN: support for BGP multihop

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-area-interface-all
Previously we did not correctly inherit from the routing instance's master interface.
This inserts that interface into the inheritance tree.
Note this does not attempt to fix inheritance for fields that should be
inherited, but are not.
> Juniper: fix handling of "all" interface in OSPF area config

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosxe-vasi-interface
Used for cross-vrf nat on IOS XE: https://www.cisco.com/c/en/us/support/docs/ip/network-address-translation-nat/200255-Configure-VRF-Aware-Software-Infrastruct.html
> IOSXE: recognize vasi left/right as valid interface prefixes

- .buildkite/pipeline.sh
Over the weekend, codecov was down and all our builds failed. Let this step
soft-fail.
```
+ bash /dev/fd/63 -t 59baa5fe-139e-4aef-80a7-b40bfaa3fc67
++ curl -s https://codecov.io/bash
/dev/fd/63: line 2: syntax error near unexpected token `<'
/dev/fd/63: line 2: `<html><head>'
```
> CI: don't fail build if codecov is down

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_sla
The "vrf x" was really tripping up our parser; Added other keywords while at it
> NXOS: parse more ip sla constructs

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrf-definition
* Remove old unused grammar
* Parse RD/RT with custom rules instead of null rules
`vfc_*` rules (I believe) were left over from pre-NXOS split days.
No conversion necessary (yet) since we do not support VPNv4/MPLS address family.
> IOS: better parsing for VRF definition

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfNeighborAddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_allowas_in
Stop warning that the feature is unsupported; plumb though full extraction, convert to the best of VI abilities
> NXOS: fixup bgp allowas-in extraction

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_routemap.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapClause.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/route_map
As reported by @dannypetrov, EOS 4.20.7 does not include action/line number
in output (in at least some cases). The new tests are based on behavior during
that discussion.
> Arista: improve route-map parsing on older EOS

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-track
> IOS: Parsing for track ip command

- projects/batfish/BUILD
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/arista/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/aws/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/juniper/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
This will hopefully prevent timeouts when running many intensive
tests in parallel.
Also run buildifier.
> bazel: annotate some of the larger test suites as high-cpu

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/NameServer.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Vrf.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_name_server
Main goal: keep parser context. Secondary goal: actually plumb through so that DNS sever verification works
> NXOS: support VRF nameservers

- projects/batfish/src/main/java/org/batfish/representation/cisco/BgpRedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/EigrpRedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/IsisRedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/OspfRedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/RipRedistributionPolicy.java
Destination protocol doesn't serve any purpose, that's already encoded in the type of policy.
> Cisco: cleanup unused code in redistribution policy

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/BgpRedistributionPolicy.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-redistribute-ospf
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-redistribute-ospf-match-internal
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-redistribute-ospf-match-various
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
This fixes 3 bugs:
1. A spurious warning since `ctx.MATCH()` is a list and always non-null
2. Adds support for matching specific route types in redistribute statement
3. Not specifying match types means redistributing both OSPF and OSPF_IA, not just OSPF (intra-area)
I'm aware this is a subpar solution and we need to make VS datamodel for redistribution more NXOS-like, but wasn't going to overhaul a lot of the VS model to unblock this bug fix.
> Cisco IOS: improve ospf->bgp redistribution, support matching on route types

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_eigrp
At this time only hello-interval and hold-time and leave placeholder tests for proper extraction and conversion of other properties
> NXOS: parse more EIGRP interface properties

- projects/batfish/src/main/java/org/batfish/representation/juniper/BgpGroup.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-confederation
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-description
1. Add a VI test
2. Set them in VI
3. Stop inheriting description
> Juniper: bgp descriptions

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcess.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/eigrp/EigrpTopologyUtilsTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
Switch from a per-neighbor redistribution to a global redistribution model.
Goal: stop "baking in" the EIGRP process _redistribution_ policy into a per-neighbor _filtering_ policy. This is/was a legacy way of doing things, and in this case we can easily fix it for one vendor before propagating the pattern to other vendors (like NXOS).
In dataplane code: execute redistribution policy on redistribution and keep the resulting routes (both in the the RIB and as a delta). Per neighbor policies now only execute the filtering (e.g., defined via distribute lists). This is a potential speedup because we do not process the same route N times (where N is number of neighbors)
In vendor code (Cisco IOS specifically): stop inlining export policy into neighbor policies. We already had infrastructure for …
> IOS: update EIGRP redistribution policies

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapConvertor.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapConvertorTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/set_community_additive_continue
- tests/parsing-tests/unit-tests-vimodel.ref
In FRR, matching/setting is done on the "in-flight" intermediate route, not the original route. Update route map conversion accordingly
> FRR: update routemap semantics

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpTopologyUtils.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
* Allow portchannel subinterfaces to have null EIGRP bandwidth
* Prevent creation of EIGRP neighbors for interfaces with null EIGRP bandwidth
Work is in progress to correctly set EIGRP bandwidth for portchannel subinterfaces, at which point we will once again have the invariant that all interfaces with EIGRP have nonnull EIGRP bandwidths, so we'll be able to undo the second bullet point.
> Fix error initing EIGRP for portchannel subinterfaces

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/port_channel_subinterface
Port-channel subinterface dependencies were accidentally getting overwritten in conversion code intended to apply only to port-channels (not subinterfaces).
> NXOS port-channel subinterfaces: bind correctly

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpTopologyUtils.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Depends on the invariant that portchannel subinterfaces all have nonnull bandwidths after `Batfish.postProcessAggregatedInterfaces()`, so this shouldn't be merged until after #6417.
> Set portchannel subinterfaces' EIGRP bandwidths

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
IP packets and L4 protocols have some constraints. E.g., all IP packets are at
least 20 bytes. Enforce these constraints.
> BDDPacket: when converting to Flow, constrain to sane packets

- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
- projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
'boot nxos' ought to be a dead giveaway
for a 'bootflash:' line, there may be a '/' before the filename
> VendorFormatConfigDetector: tweak NX-OS boot related lines

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpInterfaceSettings.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_eigrp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/EigrpProcess.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-eigrp-distribute-list-prefix-list
Support both inbound/outbound, both global/per interface
Support distribute lists that reference prefix lists in addition to ACLs
Note: EIGRP import policies not yet plumbed through to dataplane
> IOS: better support for EIGRP distribute-lists

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
In very long routing policies, especially when they have lots of
continue statements, we might compile them into fairly complicated
structures with Call statements. Sets.union is a shallow operation that
never coalesces, so it seems plausible that building a deep union will
cause stack overflows on containment checks.
To fix this, materialize the sets as we go. This should not in practice
be very expensive unless we are in a case that would cause a stack
overflow with the prior approach.
> RoutingPolicy: don't build deep unions

- projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/TracerouteEngine.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/traceroute/TraceDag.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/traceroute/TraceDagImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/traceroute/TraceDagImplTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/traceroute/TraceDagTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/HopTestUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/DagTraceRecorder.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/HopInfo.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/BUILD
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/DagTraceRecorderTest.java
- projects/question/src/test/java/org/batfish/question/traceroute/MockTracerouteEngine.java
Not all users want the full list of traces. We may want to do other things, such as looking for any path, or randomly sampling the paths, or looking for a particular hop.
* Convert TraceDag into an interface
* Move it to common, along with tests and some utilities that are of common code.
* Add an interface to expose TraceDag in TracerouteEngine
* As an example, update one caller and its tests.
> TracerouteEngine: add an interface that exposes the TraceDag

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_qos.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/policy-map
Fixes #6348 
Looks like we had copied over qos parsing from uber-cisco-parser to the xr-parser. The syntax in the two worlds appear quite different (and there were no tests for qos parsing in XR).  This PR 1) adds parsing for the policy-map syntax in the issue and fleshes out the neighborhood, and 2) removes the `s_policy_map_ios_inspect` which doesn't appear valid for XR.
> IOS XR: policy map parsing

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpRoutingProcessTest.java
Execute neighbor import policies during dataplane computation.
Among other things a I tried to clean up things a little bit (and standardize external/internal route processing) but I tried not to go too far so deferring any additional/larger cleanup.
> Support for EIGRP inbound filtering in dataplane

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
Setting up a stream is slow compared to checking a collection for emptiness.
> HeaderSpace: streamline computation

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
Just construct the multimap manually, no copy needed. In all likelihood, there
will only be one FibAction anyway.
> FlowTracer: get rid of a stream and a copy

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
We forgot to scale down to kbps when inheriting.
> EIGRP portchannel bandwidth: fixup scaling

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
* Fix the order of magnitute delay bug. ten million is 1e7
* Switch to classic metric, remove todo. Wide metrics require a special command `metrics version 64bit`, we can add support for that later
> NXOS EIGRP conversion tweaks

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface-delay
Handle the most common portchannel cases. Not a perfect solution (we may need to move this to snapshot post-processing as well) but a good enough stop-gap fix.
> IOS: tweak default interface delay inference

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/frr-match-tag-non-bgp
This is unlikely to correctly capture FRR semantics until we overhaul routing policy, but at least will prevent crashes.
> FRR: fix NPE in routemaps for non-bgp routes

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParboiledEnumSetSpecifier.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodePropertySpecifierTest.java
We have documented `properties='/no-such-property/'` as a way to get just
the key of the properties. However, we broke this when we reimplemented
the EnumSetSpecifier. Add a test, then fix it by making EnumSetValues
understand the difference between unspecified and empty. Only
unspecified should default to everything.
> EnumSetSpecifier: distinguish between unspecified and empty

- networks/example/live-with-bgp-announcements/external_bgp_announcements.json
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpAdvertisementTest.java
- projects/batfish-common-protocol/src/test/resources/org/batfish/datamodel/bgp-advertisement-missing-fields.json
https://github.com/batfish/batfish/pull/6373 enforced all fields in the class to be non-empty (as expected by the compareTo/equals) implementations. That broke users who were relying on not requiring specification of unnecessary fields. This PR relaxes the non-null checks for some fields by filling in defaults and makes compareTo/equals handle null values where they may appear.
> BgpAdvertisements: Tolerant to missing values

- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Handle case where after listing snapshots of a network but before
fetching snapshot metadata, network or snapshot has been removed.
> fix npe due to stale listing during GC: computeExpungeBeforeDate

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map
- tests/parsing-tests/unit-tests-vimodel.ref
On NX-OS, falling off the end of a route-map is not always a denial;
continuing from a permit statement changes this to a permit.
Fixing this was non-trivial: we need to properly exit/return based on the
caller context of the original route-map, we need to properly model the
"implicit permit/deny" state of the route-map, and we use CallExpr to model the
basic blocks of the routing policy. The easiest thing to do was to add a call
to the very first route-map statement, so that all route-map statements are
known to be in a CallExpr context and can always use return. Then we can use
Local Default Action to model the implicit state.
I also updated the tests (and the test configs) for these semantics.
> NX-OS: tweak route-map conversion for continue and fall-through

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map_exhaustive
- tests/parsing-tests/unit-tests-vimodel.ref
Non-continue terms need to terminate, not change default action.
Otherwise, a subsequent match could mess things up.
Add an exhaust~ing~ive test. Note I had to mix the actions, so decided
that it's okay that half the tests don't really test pre-matches.
> NX-OS: fixup to #6462

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Prior to this PR, Arista modeled route-maps as nested structures, so that if
there were N terms, those terms would go into a recursive structure that was N
terms deep. For large N (hundreds+) this can cause recursion limits in Java,
e.g., in walking the route-map or in serializing it to disk.
Fix this by adopting (nearly verbatim) the logic from NX-OS.
Validated by existing unit tests + Batfish Enterprise compare view: routes are
the same before and after in many real networks.
> Arista: port NX-OS route-map logic

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_naked_continue
> Arista: fixup #6465 with support for naked continue

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
It was already handled right above.
> Cumulus: remove redundant localAS setters

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_bgp_invalid_interface_neighbor
By creating a dummy neighbor, we prevent crashes handling the rest of the line.
> CumulusNclu: be robust to bad interface neighbor

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_acl.g4
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_acl_show_run_all
Both standard and extended ACLs, in some versions of EOS, will show lines like
`[no] statistics per-entry` or its version-dependent counter-part `counters`.
> Arista: don't bail on miscellaneous extra output

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpIpNeighbor.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighbor.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/BgpNeighborTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_evpn
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
* Create one class to encapsulate the different types of remote-as configuration
* Simplify conversion code
* Fix a few places that vrf local-as was used as local-as (it can be overridden per neighbor)
* Don't convert neighbors where remote-as set is empty, and fix a test that needed it
* BgpIpNeighbor: make the IP mandatory
* Improve and centralize warnings (removing the invalid peerIp warning)
> FRR: BgpNeighbor RemoteAs fixup

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_eigrp_redistribution
The resulting BGP routes do not yet have the correct metric (should be copied from EIGRP route's metric).
> NXOS: Redistribute EIGRP into BGP

- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- tests/basic/genDp.ref
In the fullness of time this would be probably be done by routing policy because vendors may have knobs to control this behavior, but for now this is a default that seems to apply to big vendors
> BGP redistribution: set MED to IGP metric

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_eigrp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/EigrpVrfIpAddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp_network_statements
Supports (largely undocumented) NX-OS EIGRP network statement syntax for adding interfaces to an EIGRP process. The standard way is to declare EIGRP process in the interface stanza:
```
interface Ethernet1/1
ip address 1.1.1.1/24
ip router eigrp 1
```
But it can alternatively be done from the EIGRP stanza using a network statement:
```
router eigrp 1
network 1.1.1.0/30
```
Network statements will add all interfaces with interface addresses in the network into the EIGRP process. They can appear at the top level of `config-router` (implying default VRF), within a VRF stanza (`config-router-vrf`), or in either of those places within an address-family stanza (`config-router-af`).
> NXOS: Support EIGRP network statements

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_eigrp
An EIGRP process configuration can specify its ASN in two ways. It can be set directly in the router EIGRP line:
```
! ASN is 1
router eigrp 1
```
Or it can be set on a per-VRF basis using `autonomous-system` (no VRF specified means default VRF):
```
! ASN is 2 for default VRF
router eigrp EIGRP_PROC
autonomous-system 2
```
In the latter case, we were failing to propagate the ASN to EIGRP interfaces during conversion, which meant those interfaces didn't have EIGRP in the VI model and thus couldn't establish EIGRP edges.
With this PR, the sample configs in #4684 establish an EIGRP edge.
> NXOS iface conversion: Use EIGRP VRF ASN if process ASN not present

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
Some interfaces are purely virtual and will not appear in L1. We still should keep those edges, e.g., Cisco has Vasi interfaces.
> L3 topology: keep virtual edges when L1 is present

- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-type5-routes/layer1_topology.json
The test where this topology is being used is not cleaning the topology, which creates NPEs downstream.
> Remove spurious node from L1 topology in test

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
If an interface is configured to match a given EIGRP process (with `ip router eigrp TAG`) and that same EIGRP process is also configured to include the interface (via a network statement), we were generating a spurious warning that the interface matches multiple EIGRP processes.
> NXOS EIGRP: Avoid spurious warning

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Both of these route-map statements were incorrectly implemented.
- match interface should [match any routes that have their next hop out one of the configured interfaces](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_rpm.html)
- match vlan is [PBR-specific and has no effect on route import/export](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/unicast/configuration/guide/b-7k-Cisco-Nexus-7000-Series-NX-OS-Unicast-Routing-Configuration-Guide-Release/n7k_unicast_config_pbr.html)
> NXOS route-maps: match interface and match vlan

- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
> Cisco/Arista: stop warning on unsupported ipv6 clauses

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Edge.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer2TopologyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
Compute the topology vertices based on ranges of VLANs instead of
individual VLANs. This trims a pretty significant constant factor off of
the complexity and lets L2 computation scale to larger networks.
As an additional optimization, I also removed Comparable implementation
from L2 nodes and edges
> Speed up Layer 2 topology computation

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpRoutingProcessTest.java
See sections 5.4.1.1 and 5.4.1.2 in RFC 7868:
https://tools.ietf.org/html/rfc7868#section-5.4.1.1
Tested on NXOS that these routes keep their tags after export (i.e. still have the same tag on the device to which they were exported):
- Tagged static route redistributed into EIGRP
- BGP route redistributed into EIGRP; its tag is its original BGP ASN
- BGP route that goes through a redistribution policy with `set tag`
Concluded that it is always correct to preserve external EIGRP routes' tags.
> EIGRP external routes: Maintain tag across nodes

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RoutingPolicies.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpRoutingProcessTest.java
Gets us a slightly cleaner APIs over just maps.
Helps us migrate towards better patterns: individual routing processes should not have direct access to configuration (in the long term)
> BDP: factor out wrapper around routing policies for each node

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
* Avoid materializing an entire set just to throw it away. (`getRoutes` vs `getTypedRoutes`)
* Shortcut combining sets when one is empty.
* When combining, pre-allocate new set with guaranteed enough space.
> Fib: minor memory allocation optimizations

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrfLeakingConfig.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfLeakingConfigTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- tests/parsing-tests/networks/unit-tests/configs/juniper_routing_options
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
Encapsulate in a separate object, allow leaking as BGP.
No new functionality in this PR, just prepping for future work.
>  Generalize VRF leaking datamodel

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TunnelTopologyTest.java
The flow construction todo fell through the cracks. Not using GRE protocol means interface ACLs would prevent tunnel edges from coming up
> Traceroute between tunnels: use GRE ip protocol

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
This can be expensive to compute, and is based on immutable values.
> BDDOutgoingOriginalFlowFilterManager: memoize the total constraint

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
- tests/parsing-tests/networks/unit-tests/configs/ios-xe/ios-xe-bgp-vrf
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests.ref
This is for BGP Event-based VPN Import, which affects convergence but not our
modeling.
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-16-8/irg-xe-16-8-book/irg-event-vpn-import.html
Keeps parser properly in context.
> IOS-XE: bgp address-family import path

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_nat.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosDynamicNatTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-dynamic
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-parsed-variants
We support dynamic NAT rules of this form:
`ip nat inside source list 1 pool pool1`
But it is possible to use an interface in place of a pool. This causes the interface's address to be the sole member of the pool (IOS console automatically adds `overload` to this line to allow for more than one NAT entry):
`ip nat inside source list 1 interface Ethernet1/1`
Still to do: This PR does not support NAT rules of the above form where the interface is inactive or has no address; such rules will be ignored. However, on real IOS devices, these rules still match traffic, and matched traffic is dropped.
After #6524 and #6527 (which impacts test).
> IOS NAT rules with interface instead of pool

- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/ClassicMetric.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetric.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetricVersion.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcess.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/WideMetric.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EigrpExternalRouteTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EigrpInternalRouteTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EigrpRouteTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/eigrp/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/eigrp/ClassicMetricTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/eigrp/EigrpTopologyUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EigrpMetricMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EigrpMetricMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Different implementations of EIGRP compute the cost with greater and lesser
degrees of precision. Add a setting to each EIGRP process to indicate which
cost implementation it uses, and add the classic metric computations for NX-OS.
> EIGRP: add metric version and plumb throughout

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/eigrp-distribute-list-wildcard/configs/receiver
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/eigrp-distribute-list-wildcard/configs/sender
Rather than being interpreted as a prefix, the ACL wildcard is used as a pure
wildcard against the network address. This means, for example:
permit 10.0.0.0 0.255.255.255
permits 10.0.0.0/7, since its network address is 10.0.0.0, and permits
10.1.0.0/16, since its network address is 10.1.0.0 and masked to 10.0.0.0, in
addition to simply 10.0.0.0/8.
It also means that non-prefix wildcards are allowed.
Fix #5997 and fix #4683.
> IOS: fix interpretation of standard access-list when matching routes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Trace.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/TraceTest.java
Coverage on master is flaky since this is not covered by unit tests.
> Trace: add missing equals test

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
* TCP/UDP port 0 are actually invalid, should not be used for picking representative flows
* Expose the constraint so it can be used in other places than just picking flows
> BDDPacket: enhance and expose sane flow constraint

- projects/pom.xml
I grabbed the value of 8 from some example, but since medium issues start
at 4, that's a better default.
https://nvd.nist.gov/vuln-metrics/cvss
> dependency-check: lower CVSS for failure to 4

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
Implements cisco-style VRF leaking using BGP routes in our dataplane. 
To do so, we
1. Create local BGP ribs and allow BDP to redistribute BGP routes into a local RIB even when BGP neighbors are not defined. (long time coming, this is the "classic" mode of operation for BGP across many vendors w/ exception being juniper). Currently this will only be used for VRF leaking.
2. Use these local RIBs (or more precisely, updates to these ribs from the previous round) as well as regular BGP rib deltas to leak BGP routes into neighboring `BgpRoutingProcess`es (if configured, of course)
3. The leaking process updates next hops of leaked routes to the special `NextHopVrf` next hop to ensure that FIBs are built correctly and packets hop VRFs during forwarding.
> BDP: implement BGP route VRF leaking

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrf-leaking
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/viModel.ref
- tests/parsing-tests/unit-tests-vimodel.ref
Convert the VS model to VI VRF leaking config. Resolve import/export route targets to setup VI `VrfLeakingConfig`
This required creating a new policy purely for redistribution.
After #6554
> Cisco IOS: convert VRF leaking config to VI model

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp-export-import-policies
If no export policy rules are defined, default is allow-BGP, not
deny-BGP (which is what previous list of empty statements was doing)
> PAN: fix default BGP export policy

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
This fixes a bug where a flow destined to the node (but in the next vrf) was erroneously forwarded instead of accepted
> Traceroute: check for flow acceptance in the case of next-vrf FIB action

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/BgpPeer.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp
AllowRemoteAsOut is true; Warn in the case where we do not support correct enable-sender-side-loop-detection semantics.
> PAN: fix up default BGP AF capabilities

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosNatTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosStaticNatTest.java
`Comparator.thenComparing` takes a key function or a comparator, not a comparator function.
> Fix IOS NAT compareTo bug

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_nat.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosDynamicNatTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-dynamic-route-maps
Not yet converted; route-map-based rules will be considered malformed and skipped for now
> IOS: Extract route-map-based dynamic NAT rules

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
Passing a 1-arg member function as a class function makes it a 2-arg static function,
which is correctly interpreted as a Comparator
> CiscoIosNat: simplify comparator

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-malformed-pool
In some cases (like anonymized configs) we were crashing the whole node conversion on malformed NAT pools. This change simply skips pool creation, and warns that the pool is malformed. The transformation referencing the pool will not match.
> Cisco IOS: do not crash on malformed pool

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoIosNatUtilTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-dynamic-route-maps
Same basic idea as ACL-based NAT rules. So far, only limited support for content of route-maps that are used in NAT rules. The rule will be ignored if the route-map has:
- deny clauses
- set lines
- match lines other than matching IPv4 ACLs
- references to undefined ACLs
> IOS: Convert route-map-based NAT rules

- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
This implements the more correct behavior for nxos as a stop-gap. 
https://www.cisco.com/c/en/us/support/docs/ios-nx-os-software/nx-os-software/214619-configure-disable-peer-as-check-in-bgp-o.html
Looks at last AS in the AS path, instead of the entire AS path.
We need to do more vendor tests, and likely we will need to expand our VI model to support more variations on eBGP loop prevention
> Hotfix disable-peer-as-check for nxos

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrfLeakingConfig.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfLeakingConfigTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
Show data indicates that route target communities persist on the route after leaking
> IOS VRF leaking: keep track of route targets

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrf-leaking
Make dummy processes to ensure we can leak BGP routes even if the VRF is missing a definition under router bgp
> IOS: support VRF leaking for vrfs not defined under router bgp

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
Keep local state such that BGP routes imported from other vrfs are not considered for later export to leak to other VRFs
> BDP: do not chain leak bgp routes

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_ospf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
Nothing special here.  Should generally align with FRR documentation and is setup similar to Cisco's implementation.
> FRR: Adding max-metric router-lsa administrative support

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPeerConfig.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilHybridCloudTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilTest.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/Conversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
Building the IPsec topology can fail if we create peer configs with invalid (`Ip.AUTO`) local addresses.
> IpsecPeerConfig: Require valid local address

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
Stream.of(streams) just creates a stream of streams, which we then hashed.
We need to hash the stream contents.
> RoutingProcess: fix iterationHashCode

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_routemap.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpIpv6Neighbor.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
> FRR: Parse IPv6 BGP neighbors

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
The Apache Commons FileUtils encodes the full string in memory as a byte array before saving it.
Guava's version is more space efficient.
> FileBasedStorage: switch to guava string to file

- projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-with-multiline-comment
- hierarchical juniper can have multiline comments generated via the
`annotate` command
- fix regression caused by batfish/batfish#6598
> fix hierarchical juniper multiline comments

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_policy_rule.g4
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
We still need to implement `update community` and `update extended-community`
variants that aren't `none`, but this gets us going.
> PaloAlto: BGP peers send communities unconditionally

- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
- tests/basic/routes.ref
E.g., multiple owners of that next-hop IP.
This is for #1862.
> Routes: do not populate Next_Hop (node) column if it  may be wrong

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
Most FRR parse warnings were showing up as "Word1Word2Word3" instead of "Word1 Word2 Word3"
> FRR: Don't eat spaces in parse warning details

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
> FRR: Parse route map in l2vpn evpn address family

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/BgpPeerGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/MasterBgpPeerGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/BgpPeerGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/MasterBgpPeerGroup.java
- tests/parsing-errors-tests/networks/all-fail/configs/as2r1.cfg
- tests/parsing-errors-tests/networks/single-fail/configs/as2r1.cfg
This is leftover from before we split out NX-OS.
> cisco: remove disable-peer-as-check from non-NX-OS parsers

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Node.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
And other similar storage issues.
> general: add warnings when Layer1 topology is invalid

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/AddressFamilyCapabilities.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/AllowRemoteAsOutMode.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/AddressFamilyCapabilitiesTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AddressFamilyCapabilitiesMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AddressFamilyCapabilitiesMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosBgpTest.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/viModel.ref
- tests/parsing-tests/unit-tests-vimodel.ref
Support 3 behaviors for allowRemoteAsOut via `AllowRemoteAsOutMode`:
Break `false` down into:
- `AllowRemoteAsOutMode.NEVER`: never send adverts whose as-path contains peer as
- `AllowRemoteAsOutMode.EXCEPT_FIRST` do not send adverts whose as-path's most recent as-set contains peer as
Change `true` to:
- `AllowRemoteAsOutMode.ALWAYS`: do not filter outgoing adverts based on presence of peer as in as-path
> granular allowRemoteAsOut behavior

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- tests/parsing-tests/unit-tests-vimodel.ref
It actually only checks the most recent ASN, not the entire AS Path.
Fixup batfish/batfish#6613
> JunOS: fix default BGP loop AS Path check

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfaces_common.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
1. add toIp, toPrefix, and use throughout. Standard stuff so we don't reinvent the wheel.
2. interface address commands all default to /32 (v4) or /128 (v6) if the prefix is not given.
> CumulusInterfaces: cleanup and add automatic /32, /128 for addresses

- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/LoadBalancerTest.java
The code coverage changes randomly for this class, because of e2e tests.
Fix with unit test coverage that should have been there anyway.
> AWS: test LoadBalancer equality

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface
And those units can have IP addresses.
I did confirm that the same interface can have both main loopback and
loopback.123, and both can be active and with L3 config.
> PAN: loopback interfaces can have units

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
Decvices like PAN will setup sessions with FibLookup action, but they may also be
accepted.
> FlowTracer: packets matching a session may be accepted

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java
Add vendor-specific class for Palo Alto `application-override` configuration.
Note: parsing, extraction, conversion to follow in separate PRs.
> PAN: add VS application-override class

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_application_override.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/application-override-rule
`application-override rules` allow you to specify more than one port for the `port` parameter,  this PR adds support for that
> PAN: support multiple ports in application-override rules

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
A misconfigured IBGP peer could result in Batfish thinking that it could peer with
itself (local,remote AS the same, local,remote IP the same).
Fix this by skipping self-loops during topology computation.
> BgpTopologyUtils: prevent crash on misconfigured IBGP peer

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenLocalPreference.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsThenLocalPreferenceTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-then
This is for batfish/batfish#6637.
> JunOS: support for then local-preference (add|substract)

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchColor.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromColor.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromTag.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenTag.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromColorTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromTagTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsThenTagTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-from
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-then
- tests/parsing-tests/unit-tests.ref
This is for #6335
Note that there does not appear to be a `from color2`. Add warnings where appropriate.
> JunOS: fix parsing range of from-color, then-tag, from-tag, then-color

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
The right self-reference was there, we just didn't actually ever count them.
This is for #6637
> JunOS: fix reference tacking for as-path-group as-path

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfArea.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfAreaRange.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfVrf.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Better than sticking per-area configs in the Vrf itself.
> FRR: introduce ospf area intermediate representation

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasRoute.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Condition.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCondition.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- parse, convert policy-statement from condition
- parse, partially convert policy-options condition if-route-exists
- TODO: VI design and implementation for checking route existence in RP
- just return false for if-route-exists for now
> juniper parse and partially convert condition

- projects/batfish-common-protocol/pom.xml
- projects/coordinator/pom.xml
Remove tons of warnings about missing native libs.
> batfish-common-protocol/pom.xml: add java9+ deps

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
Need to use the summarization filter from the source area,
not the destination area.
> OspfRoutingProcess: fix redistribution of inter-area routes

- projects/batfish-common-protocol/src/main/java/org/batfish/common/runtime/InterfaceRuntimeData.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
Generally, FRR boxes do not have bandwidth configured in the config, so it will need
to be provided via runtime data.
> FRR: use interface runtime data if provides

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosDynamicNat.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosStaticNat.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
IOS inside NAT rules will be applied to traffic that originates on the NAT device, if it is forwarded out an `outside` interface.
> IOS: Transform originating flows to outside interfaces

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_eigrp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-eigrp-address-family
- tests/parsing-tests/networks/unit-tests/configs/cisco_eigrp
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
- copy some tokens from re_null to rec_address_family_null
- prevents dropping out early from rec_address_family
> cisco eigrp null rule fixes

- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java
Add support for renaming structures (definitions and references) in `VendorConfiguration`.
> Vendor Configuration: support structure renaming

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRouteMetadata.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
Requires changes to ConnectedRouteMetadata as well.
> PAN: loopback routes are local

- projects/batfish-common-protocol/src/main/java/org/batfish/common/traceroute/TraceDagImpl.java
1. Add a new invariant to the TraceDagImpl, reflecting relationship between successors and disposition
2. Expose the fields in Node.
> TraceDagImpl: add invariant, expose node fields

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/EdgeMatchers.java
Previously we incorrectly skipped creating edges to NodeDropAclOut if there was no outgoing filter, even if there was an outgoing original-flow filter.
> Reachability: always apply outgoing original-flow filter

- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface
Use `M_Str` in more places to better capture structure names.
> FortiOS: better name handling

- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4
Currently the `str` rule will accept empty strings.
This PR requires it to match at least one token. No functional change yet, but this means we will be able to use it in list rules going forward, e.g. `string_list_rule: str+;`
> FortiOS: fix str rule

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
Addresses comments in https://github.com/batfish/batfish/pull/6689 except for the older placement of sbafi_neighbor stanza.
> FRR BGP: Clean up no-neighbor-activate grammar

- projects/allinone/BUILD
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDFibGenerator.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFibGeneratorTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManagerTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BUILD
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/BUILD
In some parts of the reachability graph, we are "leaking" flows that are
internal to a node too far, to a node where these flows have no outlet.
For example, flows that are only valid if sent out interface i1 were making it
to i2-related states, and flows that are only valid in vrf A were making it to
vrf B.
This is safe -- no wrong results are generated, the flows will just die, but
it is better to explicitly exclude such flows rather than having them "disappear"
in the middle of the reachability graph. This makes invariant checking easier.
> Reachability engine: explicitly filter rather than deadend

- projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/BUILD
- projects/batfish/src/test/java/org/batfish/representation/fortios/ServiceTest.java
This will not affect the VI model yet, because each service converts to an ACL line rather than a full-fledged ACL. They will be embedded in VI ACLs once we implement policy conversion.
> FortiOS: Conversion logic for services

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDFibGenerator.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateExprToLocation.java
- projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/PreOutgoingTransformationNodeVisitor.java
- projects/batfish/src/main/java/org/batfish/bddreachability/ReversePassOriginationState.java
- projects/batfish/src/main/java/org/batfish/bddreachability/SessionCreationNodeVisitor.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDFibGeneratorTest.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/BlackHole.java
- projects/symbolic/src/main/java/org/batfish/symbolic/state/StateExprVisitor.java
There are some impossible flows generated in the BDD Reachability engine, e.g.,
flows that are only valid if they exit a specific interface. This is safe (no
wrong results are generated), but it is better to specifically blackhole such
flows rather than having them "disappear "in the middle of the reachability
graph. This makes invariant checking easier.
Not plugged in anywhere yet.
> Reachability: add Blackhole state

- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Address.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/BatfishUUID.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRenameableObject.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/AddressTest.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/BUILD
- projects/batfish/src/test/java/org/batfish/representation/fortios/BatfishUUIDTest.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/ServiceTest.java
This PR changes how we track renamable structure references. Instead of keeping track of object references, we now track a Batfish-specific UUID for each object, which is converted to a name at the end of extraction (when rename operations are complete).
This allows us to still rename structures without affecting references, correctly clone and replace objects (i.e. speculatively build a modified object before we know if a config block is value), avoid serializing graphs, etc.
> FortiOS: fix stale references / track UUIDs

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BgpGroup.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-routing-options-as-gh-6710
- tests/parsing-tests/unit-tests.ref
Add missing warnings for related constructs.
This is for batfish/batfish#6710.
> JunOS: parse and warn on no-prepend-global-as

- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- tests/aws/init-example-aws.ref
- tests/basic/example-iptables-init.ref
- tests/basic/init-candidate.ref
- tests/basic/init-with-ba.ref
- tests/basic/init.ref
- tests/logging/init.ref
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/srx-testbed.ref
- tests/parsing-tests/unit-tests.ref
This PR adds undefined reference tracking directly in `VendorConfiguration`, similar to how we handle defined structure and structure reference tracking already.
This will enable future configuration builders to mark undefined references as they are encountered (in parsing/extraction) instead of having to wait until after an answer element is assigned to the vendor configuration. This helps unblock FortiOS undefined reference tracking.
This has a side-effect of slightly changing how hosts/files with no undefined references are represented. Instead of being missing from the root undefined references map in `ConvertConfigurationAnswerElement`, now they will be present but with an empty sub-map (e.g. see ref file changes).
> Undefined reference tracking refactor
