batfish/batfish

projects/batfish/src/org/batfish/logic/nxtnet/common.pl
This includes a few misc simplifications plus a signficiant (an order of magnitude) speedup for large IS-IS networks.
=> nxtnet logic: simplifications & perf

projects/batfish/.project, projects/batfish/src/org/batfish/grammar/cisco/CiscoParser.g4, projects/batfish/src/org/batfish/grammar/cisco/Cisco_aaa.g4, projects/batfish/src/org/batfish/grammar/cisco/Cisco_ignored.g4
ignore "switchport xxx xxx xxx xxx" in cisco config.
=> ignore switchport

tools/install_z3_osx.sh, tools/install_z3_rhel_x86_64.sh, tools/install_z3_ubuntu_14.04.sh, tools/install_z3_ubuntu_16.04.sh
Minor changes to z3 install scripts.
=> Save umask before install, install with 0022 and restore old umask

projects/batfish-client/src/org/batfish/client/Client.java, projects/batfish-client/test/org/batfish/client/ClientTest.java
Add validation to Protocol Type, this closes #100
=> add validation for Protocol

projects/batfish-client/src/org/batfish/client/Client.java, projects/batfish-client/test/org/batfish/client/ClientTest.java
Used existing constructor to validate an IP address.
=> fix validation for IP address

projects/batfish/src/org/batfish/main/Batfish.java
This is for batfish/batfish#172
=> Batfish: fix leak in checkConfiguration

projects/batfish-common-protocol/src/org/batfish/common/Version.java, test_rigs/parsing-tests/dc-as-reuse.ref, test_rigs/parsing-tests/disable-as-suppression.ref, test_rigs/parsing-tests/example-juniper.ref, test_rigs/parsing-tests/example.ref, test_rigs/parsing-tests/indirection.ref, test_rigs/parsing-tests/isis.ref, test_rigs/parsing-tests/policy-routing.ref, test_rigs/parsing-tests/snat.ref, test_rigs/parsing-tests/srx-testbed.ref, test_rigs/parsing-tests/unit-tests.ref, tests/basic/genDp-delta.ref, tests/basic/genDp.ref, tests/basic/init-dc-as-reuse.ref, tests/basic/init-delta.ref, tests/basic/init-snat.ref, tests/basic/init-unit-tests.ref, tests/basic/init.ref, tests/ui-focused/init0.ref, tests/ui-focused/init1.ref
- merged in fix for file handle leak
=> prepare for 0.28.1

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This is for batfish/batfish#172
This goes on top of #157
=> Batfish: a few more try-with-resources on streams

.gitignore, projects/allinone/allinone.iml, projects/batfish-client/batfish-client.iml, projects/batfish-common-protocol/batfish-common-protocol.iml, projects/batfish-parent.iml, projects/batfish/batfish.iml, projects/coordinator/coordinator.iml, projects/question/question.iml
We actually should version the iml files or opening projects is painful.
=> Fix versioning of IDEA files

.idea/inspectionProfiles/Project_Default.xml, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/pom.xml
unused import, incorrect version management.
=> fix some warnings

.gitignore, projects/batfish/src/main/java/org/batfish/main/Batfish.java
A few miscelleneous fixes or improvements... deleting dead code or variables or javadoc; simplifying a bunch of code with modern Java collections-isms; and .gitignore.
=> Random fixups

projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java, projects/coordinator/src/test/java/org/batfish/coordinator/config/SettingsTest.java
This for #200 
Any suggestions for how to test it? I am not sure how to add coordinator arguments and how to check the output. (I can't find any exiting tests for coordinator parameters)
=> split coordinator servicehost into poolhost and workhost

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
=> Issue212 list questions

projects/question/src/main/java/org/batfish/question/RoutesQuestionPlugin.java
=> fix prefixSpace not applied to Routes environmentRoutes

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
Allow client side to initialize a container with specific container name instead of providing prefix.
=> Allow init container with name

.gitignore, projects/allinone/pom.xml, projects/batfish-client/pom.xml, projects/batfish-common-protocol/pom.xml, projects/batfish/pom.xml, projects/coordinator/pom.xml, projects/pom.xml, projects/question/pom.xml, test_rigs/parsing-tests/dc-as-reuse.ref, test_rigs/parsing-tests/disable-as-suppression.ref, test_rigs/parsing-tests/example-juniper.ref, test_rigs/parsing-tests/example.ref, test_rigs/parsing-tests/indirection.ref, test_rigs/parsing-tests/isis.ref, test_rigs/parsing-tests/policy-routing.ref, test_rigs/parsing-tests/snat.ref, test_rigs/parsing-tests/srx-testbed.ref, test_rigs/parsing-tests/unit-tests.ref, tests/basic/genDp-delta.ref, tests/basic/genDp.ref, tests/basic/init-dc-as-reuse.ref, tests/basic/init-delta.ref, tests/basic/init-snat.ref, tests/basic/init-unit-tests.ref, tests/basic/init.ref, tests/ui-focused/init0.ref, tests/ui-focused/init1.ref
- ignore pom.xml.versionsBackup
- update poms
- update refs
=> prepare for 0.29.0

projects/allinone/pom.xml, projects/batfish-client/pom.xml, projects/batfish-common-protocol/pom.xml, projects/batfish/pom.xml, projects/coordinator/pom.xml, projects/pom.xml, projects/question/pom.xml, test_rigs/parsing-tests/dc-as-reuse.ref, test_rigs/parsing-tests/disable-as-suppression.ref, test_rigs/parsing-tests/example-juniper.ref, test_rigs/parsing-tests/example.ref, test_rigs/parsing-tests/indirection.ref, test_rigs/parsing-tests/isis.ref, test_rigs/parsing-tests/policy-routing.ref, test_rigs/parsing-tests/snat.ref, test_rigs/parsing-tests/srx-testbed.ref, test_rigs/parsing-tests/unit-tests.ref, tests/basic/genDp-delta.ref, tests/basic/genDp.ref, tests/basic/init-dc-as-reuse.ref, tests/basic/init-delta.ref, tests/basic/init-snat.ref, tests/basic/init-unit-tests.ref, tests/basic/init.ref, tests/ui-focused/init0.ref, tests/ui-focused/init1.ref
=> prepare for 0.29.3

.idea/google-java-format.xml, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/pom.xml
Separate commits to confirm it actually works.
=> Force failure on checkstyle warning; fix checkstyle

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/question/src/main/java/org/batfish/question/BgpLoopbacksQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/BgpSessionCheckQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/CompareSameNameQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/IpsecVpnCheckQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/IsisLoopbacksQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/NodesQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/OspfLoopbacksQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/OspfSessionCheckQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/PairwiseVpnConnectivityQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/ParseTreesQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/PerRoleQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/SelfAdjacenciesQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/UniqueBgpPrefixOriginationQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/UnusedStructuresQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/assertion/AssertQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java
The configuration folder is actually checked inside answer() function. (loadConfiguration() call)
This closes #260
=> remove checkConfiguration function

test_rigs/example-parsing-error/all-fail/configs/as1r1.cfg, test_rigs/example-parsing-error/all-fail/configs/as1r2.cfg, test_rigs/example-parsing-error/all-fail/configs/as2r1.cfg, test_rigs/parsing-errors-tests/all-parsing-failed.ref, test_rigs/parsing-errors-tests/commands
=> add test for all parsing failed case

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
For #269.
this should solve the persistent "NOT FOUND" that alb was experiencing. he was submitting an invalid question because mandatory parameters were not filled. the code now generates an answer object that shows the problem with the question.
=> generating answer objects for bad questions

.idea/codeStyleSettings.xml, .idea/misc.xml, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
* Enable nullable analysis
* update intellij defaults to be closer to google-java-format, since the editor seems to be getting confused sometimes.
* minor autoformat to BatfishTest.
=> Intellij defaults

.idea/codeStyleSettings.xml, .idea/inspectionProfiles/Project_Default.xml
Default wrapping @100
Enable a few inspection warnings
=> Intellij: more defaults

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
After enabling the google-java-format plugin.
I think this is missed b/c checkstyle isn't perfect and not everyone
is using the plugin yet.
=> autoformat BfCoordWorkHelper

.idea/misc.xml, projects/batfish-common-protocol/pom.xml, projects/batfish-common-protocol/src/main/java/org/batfish/common/Container.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/ContainerTest.java, projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/ExceptionMapper.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java, projects/pom.xml
Two example calls, to get information about all containers or a single
container.
Also adds a default exception mapper to return stack traces on failures, a redirect, and testing.
=> RESTful API based on Jersey and Jackson

projects/batfish/src/main/java/org/batfish/main/Driver.java
=> driver thread should catch throwable so it can report all errors

projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/FileAuthorizer.java
This fixes the clutter we saw in the perms.json file today. (It wouldn't have happened normally but was happening because we were deleting the container without clearing the perms file.)
=> check if perms exist before adding another entry

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/GroupPruner.java, projects/batfish/src/main/java/org/batfish/smt/Graph.java, projects/batfish/src/main/java/org/batfish/smt/collections/PList.java
=> Automated add missing @Override in IntelliJ

projects/batfish-client/src/main/java/org/batfish/client/Client.java
=> capture contol-c

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
Since these are so complex to review, I separated each removal into its own commit for clarity.
Note that there are two nested redundant checks in Batfish.java in the same function.
=> Findbugs: remove redundant != null checks

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java
After discussion, we agree these are correct.
=> Remove TODOs

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
Fixes #339
*  true: container dir was deleted
* false: container dir does not exist
From @jkhourybbn
=> del-container return status of operation without throwing exception

demos/example/commands, demos/example/commands.ref, demos/example2/commands, demos/example2/commands.ref, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/QuestionHelper.java
remove the hack that was macros like #reachability and #protection. question templates should be used instead.
=> Remove macros

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
It's a reimplementation of Objects.equals, can just use that.
=> CommonUtil: delete bothNullOrEqual

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
This time, we did an extra audit that ClientBuilder is only getting created
in one place.
=> WorkMgr: Connect to the client via the pool manager settings again

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcConfiguration.java
keySet -> get ; should just iterate over values.
=> [Findbugs] Simplify use of iterators in AwsVpcConfiguration

projects/allinone/pom.xml, projects/batfish-client/pom.xml, projects/batfish-common-protocol/pom.xml, projects/batfish/pom.xml, projects/coordinator/pom.xml, projects/pom.xml, projects/question/pom.xml, test_rigs/parsing-tests/dc-as-reuse.ref, test_rigs/parsing-tests/disable-as-suppression.ref, test_rigs/parsing-tests/example-juniper.ref, test_rigs/parsing-tests/example.ref, test_rigs/parsing-tests/indirection.ref, test_rigs/parsing-tests/isis.ref, test_rigs/parsing-tests/policy-routing.ref, test_rigs/parsing-tests/snat.ref, test_rigs/parsing-tests/srx-testbed.ref, test_rigs/parsing-tests/unit-tests.ref, tests/basic/genDp-delta.ref, tests/basic/genDp.ref, tests/basic/init-dc-as-reuse.ref, tests/basic/init-delta.ref, tests/basic/init-example2.ref, tests/basic/init-snat.ref, tests/basic/init-unit-tests.ref, tests/basic/init.ref, tests/ui-focused/init0.ref, tests/ui-focused/init1.ref
=> prepare for 0.30.0

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Answer.java
Add toString function for Answer. This change is used to support toString function for other Object that contains an Answer as a field. e.g. AnalysisAnswer uses MoreObjects.toStringHelper(), which involves each class field's toString function.
=> add toString for Answer

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java
The Findbugs issue was using keySet when really we were just iterating
over the values.
In making that switch, I found the existing code hard to read; so I
reimplemented it in terms of Stream API, and made the error handling a
little more explicit.
=> [Findbugs] Subnet: fix wrong Map iterator bugs

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_snmp.g4, test_rigs/parsing-tests/unit-tests.ref, test_rigs/unit-tests/configs/cisco_snmp, tests/basic/init-unit-tests.ref, tests/basic/nodes-unit-tests.ref
=> Fix cisco snmp community parsing

tests/basic/nodes-unit-tests.ref
Cross-talk between parsing new community names and fixing handling of RW
=> nodes-unit-tests: fix after merge

projects/batfish/src/main/java/org/batfish/main/Driver.java, projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Close Jersey client in finally block.
=> close Jersey client

projects/allinone/pom.xml, projects/batfish-client/pom.xml, projects/batfish-common-protocol/pom.xml, projects/batfish/pom.xml, projects/coordinator/pom.xml, projects/pom.xml, projects/question/pom.xml, test_rigs/parsing-tests/dc-as-reuse.ref, test_rigs/parsing-tests/disable-as-suppression.ref, test_rigs/parsing-tests/example-juniper.ref, test_rigs/parsing-tests/example.ref, test_rigs/parsing-tests/indirection.ref, test_rigs/parsing-tests/isis.ref, test_rigs/parsing-tests/policy-routing.ref, test_rigs/parsing-tests/snat.ref, test_rigs/parsing-tests/srx-testbed.ref, test_rigs/parsing-tests/unit-tests.ref, tests/basic/genDp-delta.ref, tests/basic/genDp.ref, tests/basic/init-dc-as-reuse.ref, tests/basic/init-delta.ref, tests/basic/init-example2.ref, tests/basic/init-snat.ref, tests/basic/init-unit-tests.ref, tests/basic/init.ref, tests/ui-focused/init0.ref, tests/ui-focused/init1.ref
=> prepare for 0.30.1

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/smt/EncoderSlice.java
=> Use foreach style where available

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationResult.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java
when we iterate over keySet and then immediately get the value corresponding to the key, it's more efficient to simply iterate over the entrySet.
This optimization found by Findbugs.
=> [Findbugs] switch from keySet+get to entrySet

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
* Delete some unused code
* Fix a likely bug in juniper metrics b/c of improper reference equality
* make inner functions static where they can be
=> [Findbugs] a few minor fixes

projects/batfish/src/main/java/org/batfish/smt/TransferFunctionResult.java, projects/batfish/src/main/java/org/batfish/smt/TransferFunctionSSA.java
@rabeckett, any thoughts on this one?
From what both Findbugs and I can tell, neither of the two functions on the RHS here have side effects.
=> [Findbugs] possible SMT bugfix where variables were not being modified correctly

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NodeRoleSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/question/src/main/java/org/batfish/question/RolesQuestionPlugin.java, tests/basic/commands, tests/basic/roles.ref, tests/basic/roles2.ref
A new question to get the current roles of each node -- this question supercedes the inferRoles question, which will be removed in a future PR (need to first remove the corresponding template question).
=> question to get the current roles

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
Rather than serializing to RAM first.
This is a follow-on to #422, but on the write side.
=> PluginConsumer: when writing to files, serialize directly

projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/pom.xml
=> [Findbugs] some fixes to batfish-common-protocol

projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
Register two custom filters to WorkMgrServiceV2.
=> register filters to WorkMgrServiceV2

projects/batfish/src/main/java/org/batfish/main/Batfish.java, tests/basic/commands, tests/basic/reachability-pathdiff.ref
=> making pathdiff work again and added a test

projects/batfish/src/main/java/org/batfish/smt/PropertyChecker.java
=> Fixes null pointer exception in equivalence checking

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NodeType.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/util/BatfishObjectMapperTest.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathExtractionHint.java
There's more to do, but this is a small sanity check for review.
=> Turn on Jackson case-insensitive enums, remove a bunch of useless code

projects/batfish-common-protocol/.classpath, projects/batfish-common-protocol/.settings/org.eclipse.core.resources.prefs, projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java, projects/batfish/src/main/java/org/batfish/smt/Encoder.java, projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java
- Fix dead code warning due to Eclipse handling of boolean vs Boolean constants
- Remove unused local variables
- fix resource leak
- add Eclipse project metadata due to addition of test resources to batfish-common-protocol
=> fix various eclipse-visible warnings

projects/batfish-client/.project, projects/batfish-common-protocol/.project, projects/batfish/.project, projects/coordinator/.project, projects/question/.externalToolBuilders/mvn package.launch, projects/question/.project
- fix builder ordering
- build question jar when building question project
=> eclipse maven fixes

projects/question/src/main/java/org/batfish/question/CompositeQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java, test_rigs/example2-with-delta/node_roles.json
=> returning getDataPlane() value based on innerquestions

projects/batfish/src/main/java/org/batfish/smt/PropertyChecker.java, tests/java-smt/acl1-differential1.ref, tests/java-smt/acl1-differential2.ref, tests/java-smt/acl1-differential3.ref, tests/java-smt/differential2.ref
Renamed "DIFF" to "DELTA" to simplify tooling around answer processing. I assume its a harmless change from the core logic.
=> Diff delta

projects/question/.externalToolBuilders/mvn package.launch, projects/question/.project
- step was launching regardlesss of changes
- using (untracked) mvn package launch configuration is cleaner
=> remove buggy eclipse question project package step

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
getQuestionTemplates was also not checking apikey
=> Removing global questions and testing getQuestionTemplates

projects/batfish/src/main/java/org/batfish/grammar/routing_table/ios/IosRoutingTableExtractor.java, projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, projects/batfish/src/test/java/org/batfish/bdp/RipAndBgpTest.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-rt-static-ad/configs/r1, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/ios-rt-static-ad/rt/r1
- Fix #535 
- Generalize and clean up testrig junit tests
=> Fix IOS routing table static route attributes

projects/batfish/src/main/java/org/batfish/main/Batfish.java, tests/ui-focused/run-analysis.ref
=> Analysis answer now has a combined summary

tools/common.sh
This is like `batfish_build_all` but with a clean built in.
=> Add batfish_rebuild_all alias

projects/batfish/src/main/java/org/batfish/smt/EncoderSlice.java, projects/batfish/src/main/java/org/batfish/smt/Optimizations.java, projects/batfish/src/main/java/org/batfish/smt/PropertyChecker.java
should work for the examples you had.
=> fix environment logic

projects/batfish/src/main/java/org/batfish/smt/PropertyChecker.java
The reachability query should now populate the environment external bgp advertisements.
=> Smt environment redo

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, test_rigs/parsing-tests/unit-tests.ref, test_rigs/unit-tests/configs/cisco_hsrp, test_rigs/unit-tests/configs/cisco_interface, tests/basic/init-unit-tests.ref
- Allow `no` variant of Cisco interface hsrp lines.
- unit tests with various Cisco interface lines
=> misc cisco hsrp parsing, assorted unit tests

projects/batfish-common-protocol/src/main/java/org/batfish/common/BdpOscillationException.java, projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-oscillation/configs/r1, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-oscillation/configs/r2, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-oscillation/configs/r3
- Test rig that oscillates with current version of BDP
- Throw more specific `BdpOscillationException` rather than general `BatfishException` when oscillation occurs
- Oscillation test case
=> bdp oscillation exception and test

projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java
PR #602 depends on this change
=> Making Log Level strings public to enable use as constants globally

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/AsPathSetExpr.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchAsPath.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedAsPathSet.java
`MatchAsPath@6f` -> `MatchAsPath{expr=NamedAsPathSet{name=1}}`
=> Improve toString for a few classes

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
=> Load questions lowercase answer element fix 

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java, projects/batfish/src/main/java/org/batfish/symbolic/CommunityVar.java, projects/batfish/src/main/java/org/batfish/symbolic/GraphEdge.java, projects/batfish/src/main/java/org/batfish/symbolic/abstraction/UnionSplit.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDInteger.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/VerificationStats.java
@progwriter -- having you review b/c you introduced some of these. Have you set up the plugins according to the IntelliJ setup instructions yet??
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/619)
=> Misc cleanups

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/620)
=> fixing format for lower case question names fix

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/FunctionSet.java
next installment of #559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/631)
=> removed functionset

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/635)
=> relax LinkedHashSet<Edge> to Set<Edge>

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/FibMap.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/FibSet.java, projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java
second installment of #559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/627)
=> removed fib set and fib map

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcEntity.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/637)
=> small changes to get aws parsing

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixSpace.java
- similar to Juniper `through` semantics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/652)
=> allow prefixRange with start length < match length

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralAsList.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MultipliedAs.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/658)
=> fix handling of (im)mutable as-paths

projects/allinone/pom.xml, projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java, projects/batfish-client/pom.xml, projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/batfish/pom.xml, projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/main/java/org/batfish/main/Driver.java, projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java, projects/pom.xml
1. The client side operations are being named by Http method names(GET, POST) since I am not creating any named active parent spans for them
2. Inittracer takes 11-12sec to return because of latency in some network operation during Jaeger Tracer initialization
3. The code only contains traces by jax-rs endpoints,
4. Had to format the whole file for AllInOne.java, coordinator/Main.java, Client.java, client/Settings.java and Driver.java to pass through google-java-format check in travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/659)
=> changes for tracing in coordinator, allinone, worker and client

projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/663)
=> fixing passing of parameters to coord and client

projects/batfish-client/pom.xml, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/pom.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/664)
=> client: add tracing to link RPCs across the execution of one command

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java, projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/ApiKeyAuthenticationFilter.java, projects/coordinator/src/main/java/org/batfish/coordinator/CrossDomainFilter.java, projects/coordinator/src/main/java/org/batfish/coordinator/VersionCompatibilityFilter.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java, projects/coordinator/src/test/java/org/batfish/coordinator/ApiKeyAuthenticationFilterTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/VersionCompatibilityFilterTest.java, projects/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/666)
=> Updates to API v2 CORS and related for better browser integration

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpTest.java
This function is showing up on profiles. Replace for loop with equivalent
bit-twiddling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/672)
=> Ip: improve and test numSubnetBitsToSubnetLong

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/PluginConsumer.java
For a sizeable data plane this reduced serialization time on-disk (SSD, lots of RAM)
from ~6minutes to 1 minute.
It does not seem to significantly affect deserialization time.
I did not think we would need buffering at either place because GZIP has buffers.
However, it appears that the buffer does really matter on the write side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/673)
=> PluginConsumer: Add buffered reader/writer to ser/de code

.travis/check_java_format.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/676)
=> fix output

.idea/compiler.xml, .idea/encodings.xml, projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, projects/batfish/src/main/java/org/batfish/symbolic/GraphEdge.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/SymbolicFailures.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/TransferSSA.java
Fixes a bug in an optimization used for iBGP that appeared in the updated demo code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/677)
=> SMT Demo fixes

projects/batfish/src/test/java/org/batfish/bdp/OspfTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/688)
=> remove console output from ospf test

projects/checkstyle.xml, projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/FileAuthorizer.java, projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/FileAuthorizerTest.java
Let libraries (Jackson) do the work for us. Also add tests that it's correct.
First step in significantly better testing of authorization and permissions generally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/691)
=> File authorizer cleanup and testing

projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/FileAuthorizer.java, projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/NoneAuthorizer.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java
Also implement a naive toString() for the existing authorizers.
I figure logging filenames is okay. I didn't log anything from the database because I don't know what's sensitive and what isn't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/692)
=> Coordinator: log the authorizer being used on startup

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserATNSimulator.java
This has performance and possibly correctness implications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/699)
=> BatfishParserATNSimulator: preserve prediction mode

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserATNSimulator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/700)
=> BatfishParserATNSimulator: fix javadoc links

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInternalRoute.java, projects/batfish/src/test/java/org/batfish/bdp/BgpAdvertisementMatchUtils.java, projects/batfish/src/test/java/org/batfish/bdp/VirtualRouterTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/694)
=> Testing computeBgpAdvertisementsSentToOutside

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java
That file is long enough already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/710)
=> Topology: move construction code out of Batfish

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Node.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/713)
=> remove interfaces list from node

projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/712)
=> allow getting answer status without workid

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcEntity.java, projects/batfish/src/test/java/org/batfish/grammar/aws/AwsVpcConfigurationTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, projects/batfish/src/test/java/org/batfish/main/TestrigText.java, projects/batfish/src/test/resources/org/batfish/grammar/aws/testrigs/vpc_peering_connections/aws_configs/VpcPeeringConnections.json
Fixes #705
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/707)
=> ignore deleted aws vpc peering connections, add test

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java, projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java, projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java
- fix bug where static next-hop-interface-only routes never made it to
FIB
- don't crash when static route with next-hop-interface refers to
interface not on any edge
- add tests for fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/708)
=> fix issues with static interface routes

projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/716)
=> fix BdpDatPlane:importConnectedRoutes set contains arg type

projects/batfish/src/main/java/org/batfish/main/Batfish.java
A step on the way to rationalizing the output code that @corinaminer worked on earlier this week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/711)
=> Batfish: minor cleanup / code deduplication

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Instance.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Route.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnConnection.java, projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnGateway.java, tests/basic/nodes-example-aws.ref, tests/basic/topology-example-aws.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/722)
=> fix aws interface instantiation, refactor using builders

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/720)
=> better status for analysis

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/VpnConnection.java, tests/basic/nodes-example-aws.ref
- origin type
- multipathEquivalentAsPathMatchMode
- router-id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/726)
=> for AWS BGP, set the following

projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/DbAuthorizerTest.java, projects/pom.xml
- Tests for DB authorizer
- Small style/constructor changes for easier testing
- Less reliance of MySQL-specific syntax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/703)
=> Improvements and tests for DB authorizer

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/BfObject.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/BfObjectTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/732)
=> BfObject: fix and test a bug in equality check

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java
By no means a complete solution, but useful.
For #736 #317.
Dan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/738)
=> Reachability: honor ingressNodeRegex in multipath and reduced modes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Disjunction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statement.java
Fix explosion during simplify of `RoutingPolicy`-related classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/739)
=> cache rp simplifications

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Disjunction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statement.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/740)
=> Patch release 0.33

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NatGateway.java
Comment this loop to prevent unused variable warnings until the `TODO `is resolved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/744)
=> comment unused for loop

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/InlineCommunitySet.java
stupid stupid stupid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/745)
=> fix stupid unchecked cast warning with stupid change stupid

projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java
#703 over-tuned cursor behavior to the sqlite tests. And we weren't moving the cursor to the first row of results, as required for mysql. Fixed and tested manually with a mysql db.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/746)
=> Fixing dbauthorizer cursor behavior with mysql

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/AwsVpcConfiguration.java, tests/basic/nodes-example-aws.ref, tests/basic/topology-example-aws.ref
Fixes #733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/747)
=> mark AWS instances as hosts

projects/batfish/src/main/java/org/batfish/symbolic/abstraction/Abstraction.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDRoute.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/743)
=> remove unused bdd code

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Instance.java, tests/basic/nodes-example-aws.ref, tests/basic/topology-example-aws.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/749)
=> instance hostname from tags

projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, projects/batfish/src/test/java/org/batfish/bdp/RipAndBgpTest.java, projects/batfish/src/test/java/org/batfish/grammar/aws/AwsVpcConfigurationTest.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, projects/batfish/src/test/java/org/batfish/main/TestrigText.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/715)
=> refactor junit testrig initialization

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedCommunitySet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/757)
=> remove unused var

projects/batfish-client/pom.xml, projects/batfish-common-protocol/pom.xml, projects/batfish/pom.xml, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/TransferBDD.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/Optimizations.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyAdder.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/SymbolicRoute.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/TransferSSA.java, projects/build-tools/src/main/resources/org/batfish/pmd/pmd-ruleset.xml
- make PMD checks (not including CPD) mandatory on all projects
- ignore static imports
- ignore inconsistent override of `equals` and `hashCode`
- remove unnecessary `final` modifiers
- collapse collapsible if statements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/759)
=> Make PMD checks mandatory

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Keeping the exact data around in its original form will help us iterate
on issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/766)
=> Save the original zip file uploaded by the user

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkAcl.java, tests/basic/nodes-example-aws.ref
Fixes #763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/768)
=> update names of AWS acl lines

.gitignore, projects/.settings/org.eclipse.core.resources.prefs, projects/allinone/.settings/org.eclipse.core.resources.prefs, projects/batfish-client/.settings/org.eclipse.core.resources.prefs, projects/batfish-common-protocol/.settings/org.eclipse.core.resources.prefs, projects/coordinator/.settings/org.eclipse.core.resources.prefs, projects/question/.settings/org.eclipse.core.resources.prefs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/770)
=> untrack and ignore org.eclipse.core.resources.prefs

projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkInterface.java, projects/batfish/src/test/java/org/batfish/representation/aws/NetworkInterfaceTest.java, projects/batfish/src/test/resources/org/batfish/representation/aws/NetworkInterfaceTest.json
Fix parsing for the case where network interface was "attaching" (not attached).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/771)
=> ignore non-attached interface

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java, tests/basic/topology-example-aws.ref
Fixes #769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/774)
=> recursive, not flattened, containment

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Partial "fix" for #785; information instead of NPE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/788)
=> check if metadata is present before queuing work; better error message

projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java
Fixes #758 
(To protect against clients sending empty strings instead of null.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/790)
=> Protect against empty ingressnode

projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java
It's unimplemented and we are likely to take a different approach to
anonymization when needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/796)
=> [cleanup] Delete anonymization configuration

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/symbolic/Graph.java
Fixes #794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/799)
=> fix the bug introduced while using pre-computed topology in smt

test_rigs/example-with-delta/configs/as1border1.cfg, test_rigs/example-with-delta/configs/as3border1.cfg, tests/basic/init-delta.ref, tests/basic/nodes-diff.ref
Fixes #767 
Left alone files that exist in one and not others. At least some of them are for a reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/803)
=> fix example drift

.gitignore, .idea/saveactions_settings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/807)
=> add one; ignore one

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java
the design carries forward a weakness from other places that 'questionName' cannot be a parameter in the template itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/806)
=> allowing questionName to specified for templates

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
Changed format to be consistent with PR #801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/811)
=> Consistent log formatting

projects/batfish-client/src/main/java/org/batfish/client/Client.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/810)
=> another exception can show when comparing tests

.idea/saveactions_settings.xml
the flag needs to be explicitly turned on for imports to be automatically organizes upon save
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/814)
=> organize imports needs to be for save actions

README.md
1) Added hyperlink to point to Intentionet website
2) Added mailto: hyperlink for info@intentionet.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/815)
=> Minor edits to the Readme

projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/817)
=> bug that shows up with 2 dp dependent works show up for a new testrig

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/823)
=> remove unused function

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/824)
=> move up late null check (dead code)

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, projects/batfish/pom.xml, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, projects/batfish/src/main/java/org/batfish/representation/host/HostInterface.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/interface-names/configs/ios, projects/pom.xml, tests/aws/nodes-example-aws.ref, tests/basic/nodes-unit-tests.ref, tests/basic/nodes.ref, tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref, tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/821)
=> Save declared interface names

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/833)
=> remove pretty printing stuff from the backend

.idea/runConfigurations/Allinone.xml, .travis/build.sh, projects/batfish/src/main/java/org/batfish/symbolic/TransferResult.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/EncoderSlice.java
Fixes #829. 
- Enable assertions in travis and idea's run configuration.
- Removed two failing assertions from Minesweeper code that didn't need to be there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/835)
=> Enable assertions

projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpProtocol.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisInterfaceMode.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NeighborType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OriginType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Protocol.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ReachabilityType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RoutingProtocol.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/State.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/DisplayHints.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/smt/DiffType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/smt/EnvironmentType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/smt/EquivalenceType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedCommunitySet.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteType.java, projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BgpTableFormat.java, projects/batfish-common-protocol/src/main/java/org/batfish/grammar/RoutingTableFormat.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/OutliersHypothesis.java, projects/batfish/src/main/java/org/batfish/main/Driver.java, projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java, projects/batfish/src/main/java/org/batfish/symbolic/OspfType.java, projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathAssertionType.java
Consistent way to build these static structures.
* need not be `synchronized`
* Immutable simpler than wrapping with unmodifiable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/832)
=> Convert from Collections.unmodifiedMap to ImmutableMap

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrie.java, projects/batfish/src/main/java/org/batfish/bdp/AbstractRib.java, projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java, projects/question/src/main/java/org/batfish/question/OspfSessionCheckQuestionPlugin.java
Essentially making things memory-efficient immutable data structures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/840)
=> Memory improvements for data plane computation

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/DisplayHints.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/836)
=> displayhints fixes, refactoring

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/DisplayHints.java, projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/z3/ConcretizerQuery.java, projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java
Done automatically via IntelliJ inspection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/844)
=> Replace iteration+add with addAll

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixRange.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixSpaceTest.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
Stop extending Pair; the cleanliness in the constructor alone is worth it.
Fixes #728
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/846)
=> PrefixRange: canonicalize in constructor, cleanup

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixRangeTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/848)
=> fix build in last commit I accidentally pushed to master

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/857)
=> More spans for init-testrig and run analysis questions

projects/batfish-client/pom.xml, projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-common-protocol/pom.xml, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/859)
=> Linking checktask span to worker rest service span

tools/install_z3_rhel_x86_64.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/860)
=> install_z3_rhel_x86_64.sh: fix bash bug

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, projects/coordinator/src/main/java/org/batfish/coordinator/QueuedWork.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/864)
=> Cleanup workitem

projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, projects/batfish/src/main/java/org/batfish/bdp/BdpSettings.java, projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/test/java/org/batfish/bdp/TestBdpSettings.java
The goal is to have less coupled BDP implementation:
- Moved `BdpSettings` to `batfish-common-protocol` to avoid BDP's dependency on classes in the `batfish` module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/861)
=> Minimal refactoring to support more self-contained BDP

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/smt/HeaderLocationQuestion.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/CounterExample.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/LogicalEdge.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/SymbolicDecisions.java, tests/java-smt/acl1-differential1.ref, tests/java-smt/acl1-differential2.ref, tests/java-smt/acl1-differential3.ref, tests/java-smt/bgp1-bounded-len-negate.ref, tests/java-smt/bgp1-reachability-negate.ref, tests/java-smt/commands
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/852)
=> Add a negate flag to HeaderLocationQuestions #831

projects/coordinator/src/main/java/org/batfish/coordinator/TestrigMetadataMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/870)
=> Sort testrigs

projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java
Fixes #868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/869)
=> cleanup testrig metadata if needed

projects/coordinator/src/main/java/org/batfish/coordinator/TestrigMetadataMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/871)
=> sort by name if timestamps are equal

projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, projects/batfish/src/main/java/org/batfish/representation/aws/Region.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/878)
=> fixing sort order of class members and add missing annotation

projects/batfish/src/main/java/org/batfish/main/Batfish.java, tools/install_z3_osx.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/879)
=> Enable Z3 parallelism for OSX

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, projects/batfish/src/main/java/org/batfish/job/FlattenVendorConfigurationJob.java, projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentBgpTableJob.java, projects/batfish/src/main/java/org/batfish/job/ParseEnvironmentRoutingTableJob.java, projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/main/Service.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/PoolMgrService.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
Use formatting instead of string concatenation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/881)
=> Logger improvements

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/CommandCompleter.java
* Don't show exception on CTRL-D
* Only look at current word when autocompleting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/882)
=> Fix jline usage

projects/batfish/src/main/java/org/batfish/main/Driver.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/889)
=> suppress eclipse restriction warning in Driver

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/question/pom.xml, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathAssertion.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathAssertionType.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathException.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuery.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathResult.java, projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathAssertionTest.java, projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathDisplayHintsTest.java, projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathQuestionPluginTest.java, tests/jsonpath-addons/add-exceptions-assertions.ref, tests/jsonpath-addons/commands, tests/jsonpath-addons/remove-assertions.ref, tests/jsonpath-addons/remove-exceptions.ref, tests/jsonpath-addons/templates/aaaaccountingcommands.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/888)
=> configure exception/assertions for a question; cleanup of related classes

projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/898)
=> update users table for Django schema 

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish/src/main/java/org/batfish/main/Driver.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/901)
=> fix restricted warnings for eclipse

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/905)
=> refactor reachability functions to use Java 8 Streams

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/907)
=> remove ancient LogicBlox cruft

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, test_rigs/parsing-tests/unit-tests.ref, tests/basic/init-unit-tests.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/916)
=> remove nonsense pim ssm acl

projects/coordinator/src/main/java/org/batfish/coordinator/QueuedWork.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/923)
=> allow terminated work to be terminated again

projects/coordinator/src/main/java/org/batfish/coordinator/TestrigMetadataMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/924)
=> Better error handling in coordinator

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/UnzipUtility.java
Also checked the results of `mkdirs` and used `mkdirs` in all cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/930)
=> UnzipUtility: cleanup and use more libraries

projects/batfish-common-protocol/src/test/java/org/batfish/common/util/UnzipUtilityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/933)
=> UnzipUtility: test

projects/question/src/main/java/org/batfish/question/RolesQuestionPlugin.java, tests/basic/roles.ref
Include the complete map from roles to nodes in the answer to the Roles question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/934)
=> Roles question produces a complete role map

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/nxos-ospf/configs/nxos-ospf-area
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/935)
=> test for nxos ospf parameters, some infrastructure

projects/batfish-client/src/main/java/org/batfish/client/Client.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/937)
=> catch and ignore sigint only when running in interactive mode

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- Move originals to container-level
- Move testrig folder creation as late as possible, so that it happens
after other failures would have been detected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/939)
=> WorkMgr: simplify upload

.travis/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/941)
=> tweak for when findutils on OSX is installed --with-default-names option

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishANTLRErrorStrategy.java, projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishParserATNSimulator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/942)
=> cleaner break from adaptive prediction at EOF

projects/batfish-common-protocol/pom.xml, projects/batfish-common-protocol/src/main/java/org/batfish/common/Directory.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/pom.xml
Trying out the new build tool, has already caught a bunch of issues via its better inspection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/957)
=> A few bugfixes caught by bazel

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/958)
=> Batfish: annotation cleanups

projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, tests/basic/uniqueIpAssignments.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/962)
=> clean up unique ip assignments

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDPacket.java
This snuck in during #890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/964)
=> Remove println

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, projects/batfish/src/main/java/org/batfish/bgp/JsonExternalBgpAdvertisementPlugin.java, projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, tests/basic/bgpadvertisements.ref
Also removed the override answerDiff(). With the new structure, the default diff should be good enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/963)
=> simplify the answer for bgpadvertisements question, and remove jackson ids

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacesSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacesSpecifierTest.java, projects/question/src/main/java/org/batfish/question/OspfStatusQuestionPlugin.java, tests/basic/commands, tests/basic/ospfStatus.ref
a new question that is more general and has simpler json output than ospfloopbacks (which can now be deprecated without loss of functionality).
also moved toward a general way to specify interfaces
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/965)
=> Ospf status

projects/batfish/pom.xml, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, projects/batfish/src/main/java/org/batfish/symbolic/abstraction/DestinationClasses.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/EncoderSlice.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java, projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/966)
=> Compression/Graph: clone via serialization rather than clearing cache

tests/java-smt/commands, tests/java-smt/compressed-reachability1.ref
Quick-fix to improve the stability of the compressed reachability test. Specifically, we want fewer correct answers (preferably only 1).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/969)
=> fix unstable test

projects/question/src/main/java/org/batfish/question/OspfStatusQuestionPlugin.java, tests/basic/commands, tests/basic/ospfStatus.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/970)
=> Ospf status tweaks

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
Add some missing property annotations.
Delete some unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/972)
=> Configuration: minor cleanup

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cisco/CiscoFamilyMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cisco/CiscoFamilyMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cisco/LoggingMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/cisco/LoggingMatchersImpl.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/iosLoggingOnOmitted, tests/aws/nodes-example-aws.ref, tests/basic/nodes-unit-tests.ref, tests/basic/nodes.ref, tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref, tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/batfish/973)
=> ios default logging on

projects/question/src/main/java/org/batfish/question/RoutesQuestionPlugin.java
Pending https://github.com/batfish/batfish/issues/719, this code currently makes some
advanced compilation tools refuse to compile.
=> RoutesQuestionPlugin: comment invalid code

test_rigs/parsing-tests/commands, test_rigs/parsing-tests/unit-tests-unused.ref
So we can confirm in parsing tests that things are referenced properly
=> parsing-tests: track unused structures also

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishANTLRErrorStrategy.java, projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/RecoveryExtractor.java, projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/RecoveryGrammarTest.java, projects/batfish-common-protocol/src/test/resources/org/batfish/grammar/recovery/recovery_text, test_rigs/parsing-errors-tests/recovery-no-verbose.ref
=> BatfishANTLRErrorStrategy: Fix obiwan in unrecognized lines

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTest.java
JUnit test files should end in Test.java
=> ConfigurationTests: fix name

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, tests/aws/nodes-example-aws.ref, tests/basic/nodes-unit-tests.ref, tests/basic/nodes.ref, tests/basic/outliers-verbose.ref, tests/jsonpath-addons/jsonpath-display-hints-prefixofsuffix.ref, tests/jsonpath-addons/jsonpath-display-hints-suffixofsuffix.ref
Fix #925 
(may be some refs that need tending to)
=> Process numbers

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfProcessMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospfInterfaceAreaAssignment, test_rigs/parsing-tests/unit-tests.ref, tests/basic/init-unit-tests.ref, tests/basic/nodes-unit-tests.ref
=> juniper don't add interface with no ip to ospf area

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- Pass analysis type to listAnalysis instead of null for auto-analyze
- separating out auto work queue generation from init-testrig to enable testing
=> Fix analysistype for auto analyze, refactor to enable testing

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
=> log error instead of barfing when queuing a work item fails during autoanalyze

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfArea.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaSummary.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchersImpl.java, projects/batfish/src/main/java/org/batfish/bdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- various updates to related matchers
- some steps towards immutability in related data model classes
- update affected tests
- update code previously relying on references
=> remove Interface references from OspfArea

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java
=> fix improper equals comparison of unrelated classes

tests/watchdog/commands
=> making the second task last longer to avoid the race condition

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowTrace.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java
Incorporate some IntelliJ-suggested simplifications and annotations to `Ip` and `FlowTrace`
=> Intellij-driven simplifications to Ip and FlowTrace

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
Log a warning and skip instead of just crashing.
=> WorkMgrService: better handling for invalid testrigs

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/AutoAs.java, projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, projects/batfish/src/test/java/org/batfish/grammar/host/HostInterfaceTest.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathAssertion.java
Decided to take 10 min a day to start chipping away at the issues found by Findbugs.
Here is a first pass consisting of trivial fixes e.g., don't call `toString` on a string, equality checking, style fixes.
=> Trivial FindBugs fixes

projects/question/src/main/java/org/batfish/question/RoutesQuestionPlugin.java
- Do a cleanup of `RoutesQuestionPlugin`: easier to read code, fix some bugs found by FindBugs
- Fix #719
=> Cleanup routesQuestion plugin

tools/package_rpm.sh, tools/package_ubuntu.sh
Missed from d46fef2bab18c8c9db608ef261e300064acc1133 and #866
Will test manually before merging
=> Update -servicemode to -runmode workservice

projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java
- Needed so we can extend the NoD logic
- Recent NoD refactor broke several of our tests
- these visibility changes seem very simple and benign
=> Change visibility of key NoD methods

projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java, projects/batfish/src/main/java/org/batfish/z3/ReachabilityQuerySynthesizer.java, projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java
Speeds reachability queries up significantly.
=> Matt move sane

projects/batfish-client/src/main/java/org/batfish/client/Client.java
Produce a testout file if a command that is supposed to fail does not fail.
Update the logic to properly detect failures -- either the command itself fails,
or the answer indicates failure.
=> Client: actually detect failing error tests

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_snmp.g4, test_rigs/parsing-tests/unit-tests-undefined.ref, test_rigs/parsing-tests/unit-tests.ref, test_rigs/unit-tests/configs/cisco_snmp
https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/n5k/commands/snmp-server-mib-community-map.html
=> Cisco: add parsing for snmp-server mib community-map

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java, projects/batfish/src/main/java/org/batfish/z3/NodJob.java, projects/batfish/src/main/java/org/batfish/z3/ReachabilityQuerySynthesizer.java, projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java, projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java
- If `srcNatted == true `, then final header must have different source IP than original header.
- If `srcNatted == false `, then final header must have same source IP as original header.
- If `srcNatted == null `, then no additional constraints are imposed on the header.
=> Add ReachabilityQuestion constraining whether result must be srcNatted

projects/batfish/src/main/java/org/batfish/symbolic/Graph.java
This will prevent the same element from being queued and processed multiple times.
=> Add to the domain when enqueuing rather than dequeuing

projects/question/src/main/java/org/batfish/question/RoutesQuestionPlugin.java
that way users are warned earlier in the pipeline (while submitting the question and not while viewing the answer)
=> move sanity checking to question constructor

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, test_rigs/parsing-tests/unit-tests-undefined.ref, test_rigs/parsing-tests/unit-tests.ref, test_rigs/unit-tests/configs/cisco_interface
Add parsing tests for it and proxy-arp.
=> Cisco: parsing support for ip sticky-arp

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerRecoveryStrategy.java, projects/batfish-common-protocol/src/test/antlr4/org/batfish/grammar/recovery/RecoveryLexer.g4, projects/batfish-common-protocol/src/test/java/org/batfish/grammar/recovery/RecoveryGrammarTest.java, projects/batfish-common-protocol/src/test/resources/org/batfish/grammar/recovery/recovery_badmode
The given unit test does loop forever without the fix.
=>  BatfishLexerRecoveryStrategy: fix infinite loop in alternate mode

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassfulTest.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/OspfRedistributionPolicy.java, projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java, test_rigs/parsing-tests/unit-tests-nodes.ref, test_rigs/smt-examples/REDISTRIBUTE1/configs/R2.cfg
=> Cisco: support ospf redistribute without subnets set

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java, projects/checkstyle.xml, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathAssertion.java
Objects -> java.util.Objects
Files
Fix #1140
=> Blacklist deprecated Guava classes

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, test_rigs/parsing-tests/unit-tests-nodes.ref, test_rigs/parsing-tests/unit-tests-undefined.ref, test_rigs/parsing-tests/unit-tests-unused.ref, test_rigs/parsing-tests/unit-tests.ref, test_rigs/unit-tests/configs/cisco_crypto, test_rigs/unit-tests/configs/cisco_enable, test_rigs/unit-tests/configs/cisco_interface, test_rigs/unit-tests/configs/cisco_ip
Most of the new constructs are parsed, but ignored. Added parsing tests
and a few extractor changes for constructs that are used.
=> Cisco: miscellaneous new parsing

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/FlowProcessor.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, tests/basic/commands, tests/basic/traceroute-1-2-ignoreAcls.ref
debugging routing will be easier if we can ask the analysis to ignore acls while tracing packets
=> facility to ignore acls while tracing  packet

projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles2.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRoleDimension.java
Inferred roles are stored under the name ".auto1" in the new format (map from name to NodeRoleDimension).
=> migrated inferred roles to the new format

projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRoleDimension.java, tests/roles/inferRoles.ref
Inferred role dimensions now populate the new format (no more static field hack).
=> moving inferred role dimensions to the new format

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/MultipathEquivalentAsPathMatchMode.java
cc @progwriter to review if this is clear enough.
=> MultipathEquivalentAsPathMatchMode: add javadoc

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/main/Driver.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
- more info to exceptions
- more tags to some traces
=> Adding misc logging and tracing info

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java, projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
Also added @Nullable and @Nonnull annotations.
Fixes #1249
=> Add null-check in initialization of `SynthesizerInputImpl._specializationIpSpace`

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DeviceType.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/BfObject.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Node.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/NodeTest.java, projects/batfish/src/main/java/org/batfish/dataplane/bdp/BdpDataPlanePlugin.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionInfo.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusPlugin.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusQuestion.java, projects/question/src/main/java/org/batfish/question/tracefilters/TraceFiltersAnswerElement.java, tests/aws/topology-example-aws.ref, tests/basic/bgpSessionStatusNew.ref, tests/basic/commands, tests/basic/topology.ref, tests/basic/tracefilters.ref
did a completely new plugin so we could use a simpler output format and not break old stuff. 
@progwriter - most stuff is old so perhaps OK, but i am particularly curious if i used the initBgpTopology API properly. thanks.
=> a new implementation of bgp session status that tracks dynamic neighbors

projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, projects/batfish/src/test/java/org/batfish/symbolic/bdd/IpSpaceToBDDTest.java
=> add support for arbitrary IpWildcards in IpSpaceToBDD

projects/pom.xml
=> pom.xml: enforce that javac in 1.8.X is used.

projects/checkstyle.xml, projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, projects/question/src/main/java/org/batfish/question/tracefilters/TraceFiltersAnswerElement.java
=> fix checkstyle package/class blacklists, remove violations

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java, projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java, projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixListExcept.java, projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPrefixList.java, projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourcePrefixList.java, projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourcePrefixListExcept.java, projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromPrefixListTest.java
Added null check for IpSpace in FwFromPrefixList
=> Added IpSpace null check

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
=> Remove unused summaryOnlyIpv6Networks

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java
Simplifications to make downstream use easier.
=> Conjunction: minor improvements

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
- Fix typo that caused generated routes not to be merged into mainRib
- Add test
=> ibdp: fix generated routes not present in the main Rib

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicyDispositionStatement.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RoutePolicySetStatement.java, projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAccept.java, projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenReject.java, projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/EncoderSlice.java
=> Simplify If construction and apply in easy cases

projects/allinone/pom.xml, projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/pom.xml
- revert #1272 
- add test that fails before revert
=>  Revert "Refactor answerAclReachability and avoid encoding extra ACLs"

projects/question/src/main/java/org/batfish/question/AclReachabilityQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/CompareSameNameQuestionPlugin.java
- aclreachability runs on generated structures now
=> add ability to run comparesamename on generated structures

projects/batfish/src/main/java/org/batfish/main/Batfish.java
This PR contains the refactoring I did for #1272 without any of the modifications to which ACLs are encoded. Shouldn't introduce any changes to functionality.
=> Refactor acl reachability

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrApplicationSetReference.java, projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrSetReference.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/application-set-nested
Added support for referencing application-sets in additional configuration contexts
Fixes #1340
=> Support more Juniper application-set references

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Disjunction.java
Added tests and updated code based on the definition you told me yesterday.
=> Disjunction: fix simplify with at least one true

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/BfObject.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Interface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Node.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/InterfaceTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/LinkTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/NodeTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, tests/aws/topology-example-aws.ref, tests/basic/topology.ref
Basic logic; scaffolding coming. 
(merging into non-master because of some stupidity. i'll clean up things later.)
=> auto completing nodes

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/BfObject.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Interface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Node.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/InterfaceTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/LinkTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/NodeTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, tests/aws/topology-example-aws.ref, tests/basic/topology.ref
[cherry picked this commit from an unrelated branch.]
* auto completing nodes
* autocomplete v0 complete
* update refs
* review comments
* update comment
=> auto completing nodes (#1323)

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
Comments, variable names, logical organization.
=> CiscoConfiguration#toBgpProcess: cleanup

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableAnswerElement.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableMetadata.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableAnswerElementTest.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerElement.java, projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerer.java, projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerer.java, projects/question/src/main/java/org/batfish/question/tracefilters/TraceFiltersAnswerElement.java, projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElementTest.java, tests/basic/bgpSessionStatusNew.ref, tests/basic/tracefilters.ref, tests/jsonpathtotable/ntpservers.ref
1/ get rid of toRow and fromRow; postProcessing operates on Row's
2/ column meta data is now a list, so we have ordering information
=> two changes to table answers

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java
Some small changes overlap with #1395
=> usability changes to Row class

projects/batfish/src/main/java/org/batfish/z3/NodJob.java
It also seems buggy, (for loop but return) so I don't feel bad.
=> NodJob: remove unused function

projects/batfish/src/main/java/org/batfish/z3/NodJob.java
No value in a protected function for a final class
=> NodJob: remove unnecessary protected

projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java
Huge performance win for complicated ACLs. In one simple reachability query, with a fixed
destination IP, `grep ACL nodProgram` went from 5679 to 154 occurrences.
=> SynthesizerInputImpl: specialize ACLs even if we're not filtering them

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionInfo.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
=> session type should always exist in bgp session info

projects/allinone/pom.xml, projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java, projects/batfish-common-protocol/pom.xml, projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, projects/batfish/src/main/java/org/batfish/config/Settings.java
* Added `-version` arg for `batfish`
* Added z3 version to `allinone` `-version`
=> Added version arg for batfish

projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
- Since `.getRemoteAs()`, add a new SessionType, UNKNOWN in case we don't know what the remote AS is.
- Do some minor cleanup.
=> Fix NPE in BgpSessionStatusAnswerer

projects/batfish/src/main/java/org/batfish/symbolic/smt/Encoder.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/SymbolicRoute.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/TransferSSA.java, projects/batfish/src/main/java/org/batfish/symbolic/smt/UnsatCore.java
I suspect these came from a too-smart IntelliJ find and replace
=> smt: fix some mkIf typos

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java
For easier building, mainly in tests
=> Row: add of with list of arguments

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
- Add a static wrapper around the tail recursion for route resolution, no functionality changes.
- Will come in handy for upcoming dataplane work.
=> Add static wrapper for Fib route resolution

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/NamedStructureRoleConsistencyQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/NeighborsQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/PerRoleOutliersQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/PerRoleQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/RoleConsistencyQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/RolesQuestionPlugin.java
Per discussion to improve usability.
=> Default role dimension

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java, projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java
Supersedes #1348 
Fixes #1375 
Implementation & tests for static route logic in ibdp.
=> Cleanly rewrite static route handling for ibdp

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
That's just a quick fix, ideally we'd have warnings in place.
=> Try not to crash in FibImpl

projects/allinone/src/test/java/org/batfish/allinone/AclReachability2Test.java
Refactored and improved comments to make tests more concise and readable.
=> Simplify structure of tests

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertiesAnswerer.java
- remove unused functions and associated imports
- remove raw typecast
=> Miscellaneous cleanup

projects/batfish-common-protocol/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/flatvyos/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/iptables/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/mrv/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/eos/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/ios/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/nxos/BUILD, projects/batfish/src/main/antlr4/org/batfish/grammar/vyos/BUILD
Yes I need to extract this out to a rule. Ugh.
=> Bazel: fix antlr rule to error on warnings

test_rigs/unit-tests/configs/cisco_interface, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
=> add missing unit test

projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpBestPathRibTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
=> Add some tests for Rib class, move some tests around

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
=> fix APIs usage for del and get container

.travis/build.sh
Like a recent PR that Victor made in another project.
cc: @ratulm
=> build: now that cmdfiles can fail, exit gently

.travis.yml, WORKSPACE
* WORKSPACE: no tabs
* Get test output on failures
* Upgrade to bazel 13.1
=> Bazel fixes

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDUtils.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, projects/batfish/src/main/java/org/batfish/z3/BDDIpSpaceSpecializer.java, projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java, projects/batfish/src/main/java/org/batfish/z3/IpSpaceIpSpaceSpecializer.java, projects/batfish/src/main/java/org/batfish/z3/IpSpaceSpecializer.java, projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, projects/batfish/src/test/java/org/batfish/symbolic/bdd/IpSpaceToBDDTest.java, projects/batfish/src/test/java/org/batfish/z3/BDDIpSpaceSpecializerTest.java, projects/batfish/src/test/java/org/batfish/z3/IpSpaceIpSpaceSpecializerTest.java
Introduces `BDDIpSpaceSpecializer` making it easier and more efficient to specialize networks to more complex IpSpaces.
=> New IpSpaceSpecializer using BDDS.

projects/allinone/BUILD, projects/batfish-client/BUILD, projects/batfish-common-protocol/BUILD, projects/batfish/BUILD, projects/coordinator/BUILD, projects/question/BUILD
Seems like this is a standard workaround:
https://github.com/bazelbuild/bazel/issues/3115\#issuecomment-392072493
=> BUILD: use absolute load statements

projects/allinone/src/test/java/org/batfish/allinone/AclReachability2Test.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/Evaluator.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/PermittedByAclTest.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-combined-policies
* Fixed explicit deny behavior for security policies
* Updated IpAccessList and PermittedByAcl to support different default actions
* Update global policy definition tracking
=> Update SRX policy encoding and interaction

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_routemap.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
And warn for unimplemented directive
=> Cisco: clean up RPL set next-hop

projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
Replaced by new reference tracking
=> VendorConfiguration: delete unused markStructure

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/IpsecProfile.java, projects/batfish/src/main/java/org/batfish/representation/cisco/IpsecTransformSet.java, projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java
For Cisco ipsec profile and transformset reference checking: As the defineStructure and referenceStructure along with the markConcreteStructure are already present in the code. It is just matter of updating the DefinedStructure -> ComparableStructure and updating the definition Line calculation.
=> ipsec proposal and transformset reference check

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionInfo.java, projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElementTest.java, tests/basic/bgpSessionStatusNew.ref
Aids downstream analysis and more useful information to keep in this Table. 
It is a breaking change in that I removed the onLoopback column; I am not aware of any dependencies on this question.
=> Local interface in bgp session status

projects/question/BUILD
(As I expect you know, I sent you these PRs only so you start to see what kinds of things need doing over time...)
=> question: fix bazel build after new autoservice question

projects/coordinator/pom.xml, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRoleBean.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRoleDimensionBean.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRolesDataBean.java
=> use proper annotation for jackson instead of comment

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsApplicator.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/GroupTreeBuilder.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-apply-groups-node, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-apply-groups-node-no-hostname
- apply both node0 and node1 groups
- don't inherit hostname from node0 nor node1 groups
=> Juniper support apply-groups "${node}" for clusters

projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java, projects/batfish-common-protocol/pom.xml, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BindPortFutures.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/main/java/org/batfish/main/Driver.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
- fixes #1626
- ports specified as 0 use ephemeral port
- use ephemeral ports for all services when using allinone with command file
=> add ability to use ephemeral bind ports

projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/config/Settings.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BindPortFutures.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
=> Coordinator: finish ephemeral ports

projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java, projects/question/src/main/java/org/batfish/question/traceroute/TraceroutePlugin.java, projects/question/src/main/java/org/batfish/question/traceroute/TracerouteQuestion.java, projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererTest.java, tests/basic/commands, tests/basic/traceroute2-1-2-ignoreAcls.ref, tests/basic/traceroute2-1-2.ref, tests/basic/traceroute2-2-1.ref
Code copied from the old traceroute, which will eventually be deleted. Most functionality is being tested via ref tests; one junit test on Row construction. (Ideas/contributions on improving testing of this type of code welcome.)
=> Traceroute2

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface
Add initial Palo Alto Networks interface extractions
=> Add PAN interface extractions

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowsTest.java
=> Delete empty test file

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/BgpPeerGroup.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, tests/aws/init-example-aws.ref, tests/basic/init-delta.ref, tests/basic/init.ref, tests/parsing-tests/example-juniper.ref, tests/parsing-tests/example.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
Dramatic improvement to reference count and new uncaught undefined refs.
=> Cisco: proper ref tracking of interfaces

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapMatchAsPathAccessListLine.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapMatchCommunityListLine.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAdditiveCommunityListLine.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetCommunityListLine.java, projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetDeleteCommunityLine.java, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests.ref
=> Cisco: update references to community-lists in route-maps

projects/batfish/src/main/java/org/batfish/main/Batfish.java
- make sure `_settings.getDiffQuestion()` is true, because otherwise we get no results.
- rename query variables and add comments
=> small reduced reachability fixes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LocalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipInternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AbstractRouteTest.java
- Simplify comparators
- Be more stringent with annotations
=> Cleanup abstract route

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/StaticRouteTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java, projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java, tests/aws/nodes-example-aws.ref, tests/basic/nodes.ref, tests/basic/routes.ref, tests/parsing-tests/unit-tests-nodes.ref
Add metric for static routes in vendor independent model.
=> Add metric for static routes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IsisRouteTest.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
Each commit separate: 
- Fix route equality
- ibdp terminating conditions/iteration hashcode
- Fix typo on where routes get merged
=> Isis fixes

projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java, projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java, projects/allinone/src/test/java/org/batfish/symbolic/smt/TwoNodeNetworkWithTwoLinks.java, projects/batfish/src/test/java/org/batfish/symbolic/smt/matchers/SmtReachabilityAnswerElementMatchers.java, projects/batfish/src/test/java/org/batfish/symbolic/smt/matchers/SmtReachabilityAnswerElementMatchersImpl.java, projects/batfish/src/test/java/org/batfish/symbolic/smt/matchers/VerificationResultMatchers.java, projects/batfish/src/test/java/org/batfish/symbolic/smt/matchers/VerificationResultMatchersImpl.java
Some are currently failing and marked `@Ignore`.  Need to either fix them or understand and document why that behavior is intended.
=> New smt-reachability junit tests

projects/batfish-common-protocol/BUILD, projects/question/BUILD, tests/aws/BUILD, tests/basic/BUILD, tests/java-smt/BUILD, tests/jsonpath-addons/BUILD, tests/jsonpathtotable/BUILD, tests/parsing-errors-tests/BUILD, tests/parsing-tests/BUILD, tests/roles/BUILD, tests/ui-focused/BUILD
* fix build of grammar common after line flattening
* fix build of question tests after adding mock
* fix a double-compile when running ref tests.
=> Three Bazel fixes

skylark/ref_tests.bzl, tests/aws/BUILD, tests/basic/BUILD, tests/java-smt/BUILD, tests/jsonpath-addons/BUILD, tests/jsonpathtotable/BUILD, tests/parsing-errors-tests/BUILD, tests/parsing-tests/BUILD, tests/roles/BUILD, tests/ui-focused/BUILD
=> Bazel: create a skylark macro for ref tests

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospfInterfaceAreaAssignment, tests/parsing-tests/unit-tests.ref
- don't allow multiple passive areas for an interface
- make sure interface area is reflected for passive interfaces
=> fix juniper ospf passive area handling

projects/allinone/pom.xml, projects/allinone/src/test/java/org/batfish/allinone/AclReachability2Test.java, projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java, projects/allinone/src/test/java/org/batfish/allinone/SpecifiersReachabilityQuestionTest.java
- remove unused fields, local variables
=> run pmd for allinone, fix violations

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces
* Add extraction and VI model conversion for interfaces associated with virtual routers
* Add support for parsing lists of variables for PAN configs
=> Add PAN virtual router interface extraction

WORKSPACE, projects/pom.xml
Minor bug fixes, not sure if any matter but it's best to stay up to date.
A few CVEs that probably don't affect us.
=> batfish: update jackson to 2.9.6

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
* Update Juniper format detection to use RANCID header
* Add Juniper format detection tests
=> Use RANCID header in Juniper format detection

projects/coordinator/src/main/java/org/batfish/coordinator/CrossDomainFilter.java, projects/coordinator/src/main/java/org/batfish/coordinator/ExceptionMapper.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2TestBase.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/ContainerResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRoleDimensionResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/NodeRolesResourceTest.java
Should make it easier to debug issues in future.
=> WorkMgrServiceV2: better tests, error handling, output

WORKSPACE, projects/batfish-client/BUILD, projects/batfish-common-protocol/BUILD, projects/batfish/BUILD, projects/coordinator/BUILD, skylark/junit.bzl, skylark/ref_tests.bzl
`buildifier -showlog -mode=diff $(find . -type f \( -iname BUILD -or -iname BUILD.bazel -or -iname \*.bzl -or -iname WORKSPACE \))`
=> Run buildifer on all bazel files

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkeHashingAlgorithm.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkePhase1Proposal.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IkeProposal.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IkePhase1ProposalMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IkePhase1ProposalMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IkeProposalMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IkeProposalMatchersImpl.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java, projects/batfish/src/main/java/org/batfish/representation/vyos/HashAlgorithm.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- Follow-up PR from [IPSec data-model doc](https://docs.google.com/document/d/1EEpYPXGPaqD44b5v3_3gPFifl9gl3HAWAkihV71qQLw/edit?usp=sharing)
- Changed the name of IkeAuthenticationAlgorithm to IkeHashingAlgorithm
=> POJO for IKE phase 1 proposal

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AaaAuthenticationLoginListMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/aaaAuthenticationAsa, tests/parsing-tests/unit-tests-nodes.ref
if serial line not found in config, serial line wouldn't be added to data model
=> fix bug where serial line missing from data model for ASA devices

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/arista100gfull
Support specifier, remove SPEED from cisco_ignored as it was hiding this error.
=> Arista: support 100gfull bandwidth specifier

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
Really trying to cut down on the number of variations of ipOwners we have :)
=> ibdp: Remove ipOwners simple, not used.

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityListLine.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/CommunityListTest.java
- Remove `comparableStructure`
- Stream-ify and document line matching
- Switch to guava caches
=> Cleanup CommunityList

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-units
Add support for PAN interface units.
=> Add support for PAN subinterfaces

projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeImpl.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDInteger.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDPacket.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, projects/batfish/src/test/java/org/batfish/symbolic/bdd/BDDIntegerTest.java
- factor out BDDInteger.getValue(s)Satisfying from IpSpaceRepresentativeImpl
- generalize int methods to long to prevent overflow
=> BDDInteger improvements

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpProcessMatchersImpl.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- Alphabetize methods in BgpProcess
- Fix BgpProcessMatcher messages
=> BGP datamodel: style tweaks

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
- Add tag and admin distance to the columns
- Be explicit about which values are keys and/or values in the table answer.
=> Small expansions to routes2 question

.travis/build.sh
Sickbayed until rewritten to avoid batfish/batfish#999
=> disable watchdog tests

projects/allinone/src/test/java/org/batfish/allinone/SpecifiersReachabilityQuestionTest.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java
...  with separate header field fields.
=>  SpecifiersReachabilityQuestion: replace single headerspace field

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java, projects/batfish/src/main/java/org/batfish/z3/BDDIpAccessListSpecializer.java, projects/batfish/src/test/java/org/batfish/z3/BDDIpAccessListSpecializerTest.java
New IpAccessListSpecializer using a BDD to represent the headerspace.
=> BDDIpAccessListSpecializer

projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java
Better user feedback if batches can be completed.
=> BatfishStorage: no empty batches

projects/allinone/src/test/java/org/batfish/question/reachfilter/ReachFilterAnswererTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDAcl.java, projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterAnswerer.java, projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterPlugin.java, projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterQuestion.java, projects/question/src/test/java/org/batfish/question/reachfilter/ReachFilterAnswererTest.java, projects/question/src/test/java/org/batfish/question/reachfilter/ReachFilterQuestionTest.java
New question that finds packets that exhibit different behaviors of
specified ACL(s). Implemented behaviors are: permitted by the ACL,
denied by the ACL, or reaches and is matched by the condition of a
particular line.
=> reachfilter question

projects/pom.xml
Don't spit out the names of all the files it generates. Still shows errors and warnings.
=> javadoc: quiet

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EigrpProcessMatchers.java
Couple of non-standard annotations slipped by.
=> Fix nullable annotations

projects/batfish-common-protocol/src/main/java/org/batfish/role/addressbook/AddressBook.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/AddressBookIpSpaceSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/AddressBookIpSpaceSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContext.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/AddressBookIpSpaceSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/AddressBookIpSpaceSpecifierTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/MockSpecifierContext.java, projects/batfish/src/main/java/org/batfish/specifier/SpecifierContextImpl.java, projects/batfish/src/test/java/org/batfish/specifier/MockSpecifierContext.java
@anothermattbrown  - not complete yet, but want to check with you if this is all the right way to use things. should i have made a factory class too?
=> first cut at a specifier that is based on address books

.travis.yml, .travis/build.sh, .travis/install.sh, questions/experimental/interfaceMtu.json, tests/questions/experimental/commands, tests/questions/test_questions.py
Add test checking question template formatting, naming, and variables.
Also corrected `interfaceMtu` question name.
=> Add question template tests

projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/AddressGroup.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceAddressGroupIpSpaceSpecifier.java
This started small (fixing a compile-issue identified by bazel) and ended up big. There were *lots* of mistakes in the code here.
Please review in detail (I created separate commits for each bug) to see what I fixed.
=> AddressGroup and ReferenceAddressGroupIpSpaceSpecifier fixes

.gitignore
Since python is used to validate question templates now
=> Ignore python cache

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/AltFlexibleLocationSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/DifferenceLocationSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ToInterfaceLinkLocationSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/AltFlexibleLocationSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/MockLocationSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ToInterfaceLinkLocationSpecifierTest.java
=> Alt flexible location specifier

.travis/build.sh
Run pytest only on files in `tests/` dir since that is the only place python tests will be.
=> Run pytest only on tests directory

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, test_rigs/unit-tests/configs/cisco_interface, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
interface > ip vrf {autoclassify,forwarding,receive,select,sitemap}.
Fix #1971 
CC @jlmcgraw
=> Cisco: add IOS PBR parsing and ref tracking

questions/experimental/interfaceProperties.json, tests/questions/experimental/commands, tests/questions/experimental/interfaceProperties.ref
Add `interfaceProperties` question for querying an interface's data-model.
=> Add interfaceProperties question

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java
Couldn't figure out why it wasn't. Rows is, and Rows contains Row...
=> Row: be Serializable

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warning.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java, tests/basic/example-iptables-init.ref, tests/basic/init-delta.ref, tests/basic/init.ref, tests/parsing-errors-tests/recovery-no-verbose.ref, tests/parsing-tests/example-juniper.ref, tests/parsing-tests/example.ref, tests/parsing-tests/ios_rt.ref, tests/parsing-tests/unit-tests.ref
=> Warnings: use traditional Jackson serialization

projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ReferenceBook.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FilterSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FilterSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleFilterSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ShorthandFilterSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ShorthandFilterSpecifierFactory.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FilterSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleFilterSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ShorthandFactorySpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ShorthandFilterSpecifierTest.java
following the specifier(factory) pattern for filters. does this seem right? 
if so, i'll move tracefilters and reachfilters to these classes in another PR.
=> factories and specifiers for filters

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
currently can only ask for all of the answers in the analysis. Want to be able to get the answer to a single question in an analysis
=> add ability to get answer to specific question in an analysis

projects/allinone/src/test/java/org/batfish/question/reducedreachability/ReducedReachabilityQuestionTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java, projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/z3/ReducedReachabilityTest.java, projects/question/src/main/java/org/batfish/question/reducedreachability/ReducedReachabilityAnswerer.java, projects/question/src/main/java/org/batfish/question/reducedreachability/ReducedReachabilityPlugin.java, projects/question/src/main/java/org/batfish/question/reducedreachability/ReducedReachabilityQuestion.java
Produces a table answer similar to what the new traceroute question produces, except for the addition of an environment column.
=> New zero-input reduced reachability question using BDD reachability analysis

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SelfDescribingObject.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/SelfDescribingObjectTest.java
useful for tables where objects within a column need to be of different types. (not just using Object lets the clients better interpret things.)
cc: @erikljungman, @alb-17la
=> a class with objects that describe their own schema

README.md
Add Palo Alto Networks to supported device list
=> Add PAN to supported device list

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, tests/parsing-tests/unit-tests.ref
If you have better suggestions for warning messages, LMK.
=> Remove requireNonNull from parsing code

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDAcl.java, projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDSourceManager.java, projects/batfish/src/test/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDDTest.java, projects/batfish/src/test/java/org/batfish/symbolic/bdd/BDDSourceManagerTest.java
=> rename BDDSrcManager -> BDDSourceManager

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/zones
Add zones to interfaces in PAN data model and VI model for PAN devices.
=> Add zones to interfaces for PAN devices

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, tests/parsing-tests/unit-tests-nodes.ref
This should improve the tracefilters output for juniper devices
=> Juniper: compute IpSpaceMetadata for address books during conversion

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java, projects/question/src/test/java/org/batfish/question/routes/RoutesQuestionTest.java, questions/stable/routes.json, tests/questions/stable/commands, tests/questions/stable/routes.ref
- Replace *all* with *main* to clarify meaning (main rib routes)
- Add "bgpmp" to allowed values in the template (for BGP multi-path)
=> Update route question constants: all->main

projects/allinone/src/test/java/org/batfish/allinone/SpecifiersReachabilityQuestionTest.java, projects/allinone/src/test/java/org/batfish/main/SpecifiersQuestionTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleLocationSpecifierFactory.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersQuestion.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersQuestionPlugin.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersQuestionTest.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, questions/experimental/specifiers.json, tests/questions/experimental/commands, tests/questions/experimental/specifiers.ref
This PR also includes a change to the locationspecifier to use when input to the flexiblelocationspecifier is null.
=> getting the specifiers question ready for resolving other specifiers

questions/experimental/bgpProperties.json, questions/experimental/interfaceProperties.json, questions/experimental/nodeProperties.json, questions/experimental/ospfProperties.json, tests/questions/test_questions.py
* test some JSON types of instance variables
* questions: fix type errors in optional field
=> questions: fix type errors in templates and add tests

projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationResult.java, projects/question/src/main/java/org/batfish/question/initialization/FileParseStatusAnswerer.java, projects/question/src/test/java/org/batfish/question/initialization/FileParseStatusAnswererTest.java, tests/basic/commands, tests/basic/parse-status.ref
It's host -> file, not file -> host
=> FileParseStatus: parse fileMap in the correct order

questions/stable/aaaAuthenticationLogin.json, tests/questions/stable/aaaAuthenticationLogin.ref, tests/questions/stable/commands
Add aaaAuthenticationLogin question and template validation
=> Add aaaAuthenticationLogin question

tools/common.sh
Update test_rig path export in common script
=> Update test_rig path export in common script

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseStatus.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/ParseStatusTest.java
If we combine two files with different status, what status should the result have?
=> ParseStatus: add resolution between different values

projects/batfish/src/main/java/org/batfish/main/Batfish.java
Rather than adding to maps that already exist outside of parallel streams, we now collect our parallel streams into new maps.
=> Fix nondeterminism in ACL reachability

projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDAcl.java
- Fix copy constructor
- Add annotations
- A little more javadoc
=> Cleanup BDDAcl

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IcmpType.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
=> Add ICMP types to CiscoControlPlaneExtractor

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java, projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java, projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/default-applications, tests/parsing-tests/example-juniper.ref, tests/parsing-tests/networks/unit-tests/configs/juniper_interfaces, tests/parsing-tests/srx-testbed.ref, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests.ref
* Juniper: basic support for interface self reference
* Juniper: remove definitionLine from interface
* Juniper: define instances only in s_interfaces
=> Juniper: improve interface reference tracking

projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImplContext.java
Return early where possible, and add some comments.
This may look big, but it's really just unwrapping
```
if (..) {
..
} else {
..
}
<return>
```
into
```
if (..) {
..
return
}
..
```
a few times since we had multiple of these nested. Note that if the else was super short, I swapped the `if` around also.
=> Traceroute: simplify code

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, tests/parsing-tests/networks/unit-tests/configs/cisco_interface, tests/parsing-tests/unit-tests.ref
=> ASA: parsing support for no nameif

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ConstantIpSpaceSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleIpSpaceSpecifierFactory.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleIpSpaceSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleLocationSpecifierFactoryTest.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java
Four small changes, in separate commits. Happy to separate as you see fit.
* FlexibleIpSpaceSpecifierFactory: add ofLocation() for flexible locati…
* ConstantIpSpaceSpecifier: add toString
* FlexibleLocationSpecifierTest: add javadoc and annotation
* SpecifiersReachabilityQuestion: use FlexibleUniverseIpSpaceSpecifierF…
cc: @saparikh try this out.
=> Specifier flexible dst ip

projects/allinone/src/test/java/org/batfish/question/reachfilter/ReachFilterAnswererDifferentialTest.java, projects/allinone/src/test/java/org/batfish/question/reachfilter/ReachFilterAnswererTest.java, projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterAnswerer.java, projects/question/src/main/java/org/batfish/question/tracefilters/TraceFiltersAnswerer.java, tests/basic/tracefilters.ref
1) Will produce one row per flow (not two)
2) Use Table diffs to generate the final table
3) Post processes the rows (for diff and non-diff) to attach summary and process assertions/exclusions
=> Use table diffing and other infra for reachfilters

projects/batfish-common-protocol/src/main/java/org/batfish/common/AnalysisAnswerOptions.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/ColumnFilter.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/ColumnSortOption.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/AnalysisAnswerOptionsTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/ColumnFilterTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/ColumnSortOptionTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AnswerMetadataTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/ColumnAggregationResultTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/ColumnAggregationTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/GetAnalysisAnswerMetricsAnswerTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/MetricsTest.java
- add missing `final` annotations
- implement missing `equals` and `hashCode`
=> equals tests for recent api updates

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SubRange.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/SubRangeTest.java
Side effect of me working on packet header constraints.
- Delete unused code
- Document and test the behavior of SubRange
=> Document and test SubRange

projects/batfish-common-protocol/src/main/java/org/batfish/common/AnalysisAnswerOptions.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/AnalysisAnswerOptionsTest.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- move truncate after uniquification
=> getAnalysisAnswersRows option to return unique rows

projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java
I learned about Stream#limit today.
=> Specialization: a few IntelliJ auto-fixes

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java, projects/question/src/test/java/org/batfish/question/routes/RoutesQuestionTest.java, questions/stable/routes.json, tests/questions/stable/commands, tests/questions/stable/routes.ref
=> add network and protocols filter to Routes; rename earlier protocol filter to rib

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SubRange.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/SubRangeTest.java
- Add if empty
- Add if contains another subrange
=> More subrange functionality

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
IDE-driven annotation and unused code improvements.
=> Datamodel: misc cleanup

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, tests/basic/bgpSessionStatusNew.ref
To be consistent with other occurrences of VRF
=> Fix VRF column name for bgp session status

tests/roles/commands, tests/roles/inferRoles.ref
- excluding example2 from roles testing 
- testting inferRoles on example network instead.
=> Don't test roles for example2

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntersectHeaderSpaces.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SubRange.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntersectHeaderSpacesTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/SubRangeTest.java
Compute the intersection of HeaderSpaces, punting on some complicated corner cases.
cc @dhalperi
=> Intersect two HeaderSpace objects

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/test/java/org/batfish/client/ClientTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/AllowedValue.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, tests/questions/experimental/neighbors.ref, tests/questions/experimental/traceroute.ref, tests/questions/stable/edges.ref, tests/questions/stable/routes.ref, tests/questions/stable/testfilters.ref
Makes it possible to add descriptions for allowed parameter values. See [design doc](https://docs.google.com/document/d/1Zef2e695DvwhlFPtKO-_GHrnZ_JOmerDzn1CDFyh0bg) for details.
=> Allowed value descriptions

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceWithConnectedIpsSpecifier.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ToInterfaceLinkLocationSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/InterfaceWithConnectedIpsSpecifierTest.java
@anothermattbrown -- maybe we should wrap some of the utilities for detecting empty IP spaces, etc, in an IP utils library?
=> InterfaceWithConnectedIpsSpecifier: add

projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterQuestion.java, projects/question/src/test/java/org/batfish/question/reachfilter/ReachFilterQuestionTest.java, questions/experimental/reachfilter.json, tests/questions/experimental/commands, tests/questions/experimental/reachfilter.ref
1/ removed factory inputs from the template
2/ changes the parameter names to nodes and filters
=> Simplify reachfilters

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactory.java, projects/question/src/main/java/org/batfish/question/reachfilter/ReachFilterQuestion.java, projects/question/src/test/java/org/batfish/question/reachfilter/ReachFilterQuestionTest.java, questions/experimental/reachfilter.json, tests/questions/experimental/commands, tests/questions/experimental/reachfilter.ref
also reordered fields/parameters and added nullness annotations
=> add ipProtocols parameter to reachfilter question

projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
=> Update IPOwners answer column names

questions/experimental/reachability.json, tests/questions/experimental/commands, tests/questions/experimental/reachability.ref
Breaking change for users .... I send a warning on Slack before merging.
=> rename specifiersReachability to reachability and simplify parameter names

.travis.yml, WORKSPACE
1. upgrade
2. fix sha. still investigating how the old build passed. was this the bug you ran into?
=> Bazel upgrade

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableDiffTest.java
That feature just seems to get in the way more than it helps.
=> Remove diff column from Table diffing

projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, projects/question/src/main/java/org/batfish/question/traceroute/TracerouteQuestion.java, tests/basic/commands, tests/basic/oldtraceroute-1-2-ignoreAcls.ref, tests/basic/oldtraceroute-1-2.ref, tests/basic/oldtraceroute-2-1.ref, tests/basic/traceroute-1-2.ref, tests/basic/traceroute-2-1.ref, tests/questions/experimental/commands
* traceroute -> oldtraceroute
* traceroute2 -> traceroute.
* deprecate old traceroute
=> Rename java traceroute questions

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleFilterSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleFilterSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/InterfaceSpecifierFilterSpecifierTest.java
Added support for {in,out}FilterOf(<InterfaceSpecifier>)
=> Easy selection of filters

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
Rename `variable_service_protocol` rule since it is not a variable rule.
=> Rename variable_service_protocol rule

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Interface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/InterfaceTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/LinkTest.java, tests/aws/topology-example-aws.ref, tests/basic/topology.ref
Also removed the separate InterfaceType enum in the pojo package.
=> Adding link types for pojo topologies

projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java, projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java, tests/questions/experimental/searchfilters.ref
1/ Add HeaderSpace field only when the flag is on
2/ HeaderSpace -> Header_Space
3/ No need to check if the question is differential in answer(). Batfish will route properly to answer to answerDiff
=> Small cleanups to searchfilters

README.md
=> Add Docker pointer to readme

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
* Use TCP flags
* Sane comparator implementation
* Delete newly unused code :) 
cc @haverma if you're going to wade into this code
=> Flow cleanup:

questions/Parameters.md
cc'ed three likely stakeholders, but anyone can comment.
also, still working out which of the many markdown comment styles github supports, so ignore that for now.
=> questions: begin Parameters.md

projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityTest.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntersectHeaderSpaces.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PathConstraints.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsTest.java, projects/question/src/main/java/org/batfish/question/specifiers/PathConstraintsInput.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityAnswerer.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/PathConstraintsInputTest.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, questions/experimental/reachability.json, tests/questions/experimental/commands, tests/questions/experimental/reachability.ref
* Use new parameters - packet header constraint, path constraints
* Produce table answers by leveraging traceroute table answer logic.
=> Update the new reachability question

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
=> Delete unused code in CommonUtil

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_acl.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, tests/parsing-tests/networks/unit-tests/configs/cisco_acl, tests/parsing-tests/networks/unit-tests/configs/cisco_misc, tests/parsing-tests/networks/unit-tests/configs/cisco_system, tests/parsing-tests/networks/unit-tests/configs/cisco_vrf, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests-warnings.ref, tests/parsing-tests/unit-tests.ref
The HSRP hold time change is a bug fix: hold time is required to be at least 3x hello time.
=> New Cisco parser constructs

projects/question/src/main/java/org/batfish/question/bgpproperties/BgpProcessConfigurationAnswerer.java, projects/question/src/main/java/org/batfish/question/bgpproperties/BgpProcessConfigurationPlugin.java, projects/question/src/main/java/org/batfish/question/bgpproperties/BgpProcessConfigurationQuestion.java, projects/question/src/test/java/org/batfish/question/bgpproperties/BgpProcessConfigurationAnswererTest.java, questions/experimental/bgpProcessConfiguration.json, tests/questions/experimental/bgpProcessConfiguration.ref, tests/questions/experimental/commands
No other changes yet, just renamed.
=> Rename BgpProperties to BgpProcessConfiguration

README.md
* Move getting started earlier in readme
* Bypass docker hub links and go straight to docker readmes
=> Readme Update - Getting Started

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Move load plugin out of `WorkMgr` constructor.
=> Move load plugin

projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
Update `WorkMgrTest` snapshot-creating-helpers to no longer use `Paths`.
=> Update WorkMgr Tests

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
Made redundant by new reference tracking
=> Cisco: delete some useless line tracking

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
=> Cisco: move conversion utilities out of CiscoConfiguration

projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityTest.java, projects/question/src/main/java/org/batfish/question/specifiers/DispositionSpecifier.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/DispositionSpecifierTest.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, questions/experimental/reachability.json, tests/questions/experimental/commands, tests/questions/experimental/reachability.ref
Wraps existing dispositions with new inputs "success" and "failure"
=> Add disposition specifier, switch new reachability to use it

projects/batfish/src/main/java/org/batfish/main/Batfish.java, tests/basic/commands, tests/java-smt/compressed-reachability1.ref
Added a debugflag `useNodReachability` to use the old NOD engine.
=> Use BDD reachability engine for specifiers reachability question

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockForwardingAnalysis.java, projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/z3/state/DeliveredToSubnet.java, projects/batfish/src/main/java/org/batfish/z3/state/ExitNetwork.java, projects/batfish/src/main/java/org/batfish/z3/state/ExitsNetwork.java, projects/batfish/src/main/java/org/batfish/z3/state/NodeInterfaceDeliveredToSubnet.java, projects/batfish/src/main/java/org/batfish/z3/state/NodeInterfaceExitsNetwork.java, projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, projects/batfish/src/main/java/org/batfish/z3/state/visitors/GenericStateExprVisitor.java, projects/batfish/src/main/java/org/batfish/z3/state/visitors/Parameterizer.java, projects/batfish/src/main/java/org/batfish/z3/state/visitors/StateVisitor.java, projects/batfish/src/test/java/org/batfish/bddreachability/BDDMultipathInconsistencyTest.java, projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactorySourcesTest.java, projects/batfish/src/test/java/org/batfish/main/BatfishBDDReducedReachabilityTest.java
Split neighbor unreach or exits network disposition in BDD reachability analysis
=> Reachability disposition

projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java, projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-client/src/main/java/org/batfish/client/Command.java
- delete
- get
- put
- takes file or literal JSON
- post
- takes file or literal JSON
=> Java-client HTTP debug commands for work manager v2

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SelfDescribingObject.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/SelfDescribingObjectTest.java
and that missing apostrophe in the error message has been bothering me for months
=> Add some missing stuff to SelfDescribingObject

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
- Singleton checks & getter
- Difference computation
- Better comments
=> Expand functionality of IntegerSpace

projects/batfish-common-protocol/src/main/java/org/batfish/common/BaseSettings.java
Would have been useful earlier.
=> Illegal argument: better error

projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java, projects/question/src/main/java/org/batfish/question/reducedreachability/ReducedReachabilityAnswerer.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java
Done at the question level for both regular and differential reachabilities
=> Reachabilities: ignore loops when specifying failure

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java, projects/coordinator/src/main/java/org/batfish/coordinator/Main.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java, projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/AnalysesResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/AnalysisResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkNodeRolesResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkSettingsResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/QuestionsResource.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/ReferenceLibraryResource.java, projects/coordinator/src/test/java/org/batfish/coordinator/MainTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/AnalysesResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/AnalysisResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/NetworkResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/QuestionsResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotsResourceTest.java
- `AnalysisResource`
- `AnalysesResource`
- `QuestionsResource`
- More consistent behavior of `WorkMgr` API calls
=> More V2 API calls

projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
This tests both fixes
* batfish/batfish#2468 (would fail on accepted)
* batfish/batfish#2475 (would fail on no traces computed)
=> Traceroute: add test for denied_in

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Line.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureEquivalenceSet.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/FiltersSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java, projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/representation/juniper/BaseApplication.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java, projects/build-tools/src/main/resources/org/batfish/pmd/pmd-ruleset.xml, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/question/src/main/java/org/batfish/question/namedstructures/NamedStructuresAnswerer.java, projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java
- remove unnecessary annotations
- remove unused functions and fields
- clean up some stream logic for legibility and to make Eclipse happy
=> remove unused code identified by Eclipse

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RouteInfo.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java, tests/questions/experimental/tracerouteListHops.ref
=> Make RouteInfo of Traceroute consistent with Routes' protocol

projects/batfish/src/main/java/org/batfish/main/Batfish.java
=> Saner flow for identifying device types

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java
=> Simplify code and add clarifying comments in Topology

projects/batfish-common-protocol/src/main/java/org/batfish/common/Pair.java
- Better annotations
- Cleaner comparator and hashcode
=> Cleanup Pair class a little

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralAsList.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java
Fewer array lists, more immutable objects
=> Batfish: random hacks of memory

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NodeInterfacePair.java
* Do not extend from Pair
* Annotations
* Json creator null checks
=> Cleanup NodeInterfacePair class a little

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkFactory.java
* Nullable annotations
* Javadoc
=> Cleanup NetworkFactory class a little

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, tests/parsing-tests/networks/unit-tests/configs/cisco_additional_paths, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
Parse it, clean up grammar, do nothing else.
=> Cisco; bgp additional-paths install

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RoutingStep.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- only add unique `RouteInfo` objects
=> Revert to using a list for routes in RoutingStep

projects/batfish-client/src/main/java/org/batfish/client/Client.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java, questions/Parameters.md, questions/experimental/reachability.json, questions/experimental/reducedReachability.json, tests/questions/experimental/reachability.ref, tests/questions/experimental/reducedReachability.ref
=> Add disposition parameter type and document it

projects/question/src/main/java/org/batfish/question/specifiers/DispositionSpecifier.java, projects/question/src/test/java/org/batfish/question/specifiers/DispositionSpecifierTest.java
Since it's no longer supported by the engine.
=> Remove NUOEN disposition from set of failure dispositions

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
Incremental progress towards cleaning up of what's stored in the DP.
=> Delete getIpOwners from DataPlane

projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/InterfaceGroup.java, projects/batfish-common-protocol/src/main/java/org/batfish/referencelibrary/ReferenceBook.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactory.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ReferenceInterfaceGroupInterfaceSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/referencelibrary/ReferenceBookTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/referencelibrary/ReferenceLibraryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleInterfaceSpecifierFactoryTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceAddressGroupIpSpaceSpecifierTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceInterfaceGroupInterfaceSpecifierTest.java, projects/batfish-common-protocol/src/test/resources/org/batfish/referencelibrary/bookBasic.json, projects/coordinator/src/main/java/org/batfish/coordinator/resources/InterfaceGroupBean.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/ReferenceBookBean.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/ReferenceBookBeanTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/ReferenceBookResourceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/ReferenceLibraryBeanTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/ReferenceLibraryResourceTest.java
1/ Added interface groups
2/ Built a builder
=> Modifications to reference library

projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java, projects/question/pom.xml, projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java, tests/basic/commands
cc: @anothermattbrown @progwriter
=> Swap the default on traceroute output

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/resources/ForkSnapshotBean.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/resources/NetworkResourceTest.java
Add ability to restore previously failed interfaces, edges, nodes via fork snapshot
=> Add ability to restore failed interfaces, edges, nodes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/StepAction.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java, projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
Fixes [2545](https://github.com/batfish/batfish/issues/2545)
using stepaction names = dispositions for actions which will be terminal in a trace
=> Better step actions names for new dispositions

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DeniedByIpAccessListLine.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByIpAccessListLine.java, tests/basic/testfilters.ref
=> Cleanup ACL Trace permit/deny

projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, projects/batfish/src/main/java/org/batfish/symbolic/collections/Table2.java, projects/batfish/src/test/java/org/batfish/symbolic/GraphTest.java
Taking over #2550 
cc @SliencerX 
- Did some refactoring for cleaner and testable code
- Tests are minimal but at least set an example
=> SMT: handle iBGP neighbors with different local IPs

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java, projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisIgnoreAclsTest.java
This is just for the backend; new parameter in questions will come later.
=> add support for ignoreAcls to BDDReachabilityAnalysis

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
=> RoutesAnswerer: fix handling for BGPMP

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java
=> Cleanup in question class

projects/allinone/src/test/java/org/batfish/question/differentialreachability/DifferentialReachabilityTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/question/differentialreachability/DifferentialReachabilityParameters.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/main/BatfishBDDDifferentialReachabilityTest.java, projects/batfish/src/test/java/org/batfish/z3/ReducedReachabilityTest.java, projects/question/src/main/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswerer.java, projects/question/src/main/java/org/batfish/question/differentialreachability/DifferentialReachabilityQuestion.java, questions/experimental/differentialReachability.json, tests/questions/experimental/commands, tests/questions/experimental/differentialReachability.ref
=> add invertSearch parameter to differentialReachabilityQuestion

projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteTest.java
Removed broken test cases in TracerouteTest.
=> remove broken test cases in TracerouteTest

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/FlexibleNodeSpecifierFactory.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/FlexibleNodeSpecifierFactoryTest.java
Based on what we have in `FlexibleLocationSpecifierFactory`
=> add syntax for DifferenceNodeSpecifier to FlexibleNodeSpecifier

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
Missing include/exclude
Missing unionOf
Missing Serializable
Inability to survive serialization
=> IntegerSpace: fix some missing APIs/features

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkConfigurations.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpInterface.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isis/IsisNode.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NetworkConfigurationsTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchersImpl.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java, projects/question/src/main/java/org/batfish/question/ipsecsessionstatus/IpsecSessionStatusAnswerer.java
* Optional makes it easier to chain method calls
* Fix typo (IPSec)
=> NetworkConfigurations helper: move towards Optional

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
Follow up to #2393 
Ignore non-forwarding routes when computing FIBs. 
This means: 
- don't install non-forwarding routes in the fib
- do not consider non-forwarding routes valid when resolving next hop IPs
=> Support non-forwarding routes in the FIB

README.md
=> First pass update for README

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
Wanted to play around with some prefix-tracer optimizations; needed to ensure Prefixes can't be modified. Ended up doing minor cleanup.
=> Prefix: ensure immutability, add clarifying annotations and docs

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
- send network name instead of ID to authorizer
=> fix WorkMgr.getWorkStatus

projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- `.DS_STORE`
- `__MACOSX`
- `.git`
- `.svn`
=> allow cruft dirs at top level of snapshot zips

projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionAnswerer.java
*I would have been more critical in my commit message if I hadn't written the original*
=> Fix weirdly constructed getInterface method

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SelfDescribingObject.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/SelfDescribingObjectTest.java
=> add a name field to self describing objects

projects/question/src/main/java/org/batfish/question/testfilters/TestFiltersAnswerer.java, projects/question/src/test/java/org/batfish/question/testfilters/TestFiltersAnswererTest.java
Modeled behavior after that of `searchFilters`. Fixes #2696.
=> testFilters: Better error when params don't match any filters

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObjectAddressSpecifier.java, projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObjectGroupAddressSpecifier.java, tests/parsing-tests/networks/unit-tests/configs/asa_object_groups, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests.ref
Partially address batfish/batfish#2701
=> ASA: better support for matching network objects in ACLs

projects/allinone/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityTest.java, projects/batfish-common-protocol/src/main/java/org/batfish/question/ReachabilityParameters.java, projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java, projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, questions/experimental/reachability.json, tests/questions/experimental/commands, tests/questions/experimental/reachability.ref
this is to prepare for merging differential reachability and specifiers reachability
=> add invertSearch parameter to specifiers reachability question

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
Fix part 1 of batfish/batfish#2704
=> Cisco: start if ipv6 and reference tracking for traffic-filter

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, tests/parsing-tests/networks/unit-tests/configs/cisco_control_plane, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests.ref
Fix part 2 of batfish/batfish#2704
=> Cisco: reference tracking for control-plane service policy

projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConsts.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableView.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableViewRow.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableViewTest.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- rows with IDs
- include AnswerRowsOptions in response
=> getAnswerRows2 call that returns TableView instead of TableAnswerElement

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InterfaceType.java
=> Document InterfaceType

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/AggregateRoute.java, projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathGroup.java, projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java, projects/batfish/src/main/java/org/batfish/representation/juniper/NamedAsPath.java, projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java, tests/parsing-tests/networks/unit-tests/configs/juniper_as_path_group, tests/parsing-tests/networks/unit-tests/configs/juniper_interfaces, tests/parsing-tests/networks/unit-tests/configs/juniper_routing_options, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests-warnings.ref, tests/parsing-tests/unit-tests.ref
- aggregate route with policy
- as-path-group
- interface tcp-mss
- BGP confederation and members
=> assorted juniper parsing

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java
Create dependency class so that dependencies can be tracked between interfaces.
=> Precursor to tracking interface dependencies in VI model

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/aggregate-routes, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/generated-routes, tests/parsing-tests/unit-tests-nodes.ref
~- If no policy takes an action, accept.~
~- If a policy accepts, accept.~
~- If at least one policy rejects and no policy accepts, reject.~
Evaluate policies in order:
- If a policy accepts, stop evaluation and accept.
- If a policy rejects, stop evaulation and reject.
- If no policy takes an action, take default action.
- Initially, default action is accept.
- Policy can change default action and fall through.
=> fix juniper aggregate policy semantics

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecAuthenticationAlgorithm.java, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/CryptoProfile.java, projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/global-protect-app-crypto-profiles, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ike-crypto-profiles, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ipsec-crypto-profiles, projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/mgmt-iface
1/ a bunch of stuff is parsed and ignored (see ignored-lines file)
2/ ike and ipsec profiles are pushed to vendor configuration (not to vi model yet)
3/ management interface details are pushed to vendor model
=> Misc PAN parsing

projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java, projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersQuestion.java
Expose the ability to programmatically create searchFilters questions and manipulate their answers.
=> Make SearchFiltersQuestion externally creatable

projects/batfish/flatten, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/main/Flatten.java, projects/batfish/src/test/java/org/batfish/main/BatfishTest.java, projects/batfish/src/test/java/org/batfish/main/FlattenTest.java, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/flat, projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/hierarchical, tools/common.sh
- accessible via bash flatten function
=> add flatten command-line utility

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/StepAction.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java, projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
1. add a new StepAction PERMITTED
2. use PERMITTED for PreSourceNatOutgoingFilterStep
=> Use PERMITTED instead of RECEIVED for filter StepAction

projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierContextImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java, projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java, projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswererTest.java, projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityTest.java
* Add IpOwners class to start encapsulating some of the Ip owners functionality
* Add TopologyProvider to cache IpOwners
* Make specifierContext aware of NetworkSnapshot
* Expose loadConfigurations(NetworkSnapshot) API call in IBatfish
=> First pass on topology provider

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_acl.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/StaticRoute.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-interface, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/asa-security-level, tests/parsing-tests/networks/unit-tests/configs/asa_interface, tests/parsing-tests/networks/unit-tests/configs/cisco_acl, tests/parsing-tests/networks/unit-tests/configs/cisco_misc, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests-undefined.ref, tests/parsing-tests/unit-tests-unused.ref, tests/parsing-tests/unit-tests.ref
Fixed some parsing details and added MTU parsing.
=> ASA parsing fixes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/ExitOutputIfaceStep.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Step.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/StepAction.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/TransformationStep.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java, projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java, projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
Create a new step for transformations (currently source and destination nat).
cc @yifeiyuan @progwriter
=> TransformationStep

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
fix typos in forwardinganalysis
=> fix typos in forwardinganalysis

projects/question/src/main/java/org/batfish/question/initialization/ConversionStatusAnswerer.java, projects/question/src/main/java/org/batfish/question/initialization/ConversionStatusQuestion.java, projects/question/src/main/java/org/batfish/question/initialization/ConversionStatusQuestionPlugin.java, projects/question/src/test/java/org/batfish/question/initialization/ConversionStatusAnswererTest.java, questions/stable/viConversionStatus.json, tests/questions/stable/commands, tests/questions/stable/viConversionStatus.ref
Add conversion status question for surfacing result of vendor specific to vendor independent conversions.
=> Add conversion status question

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/LinkTest.java
=>  Link: handle new AGGREGATE_CHILD interface type

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
Fixing the immediate bug only.
=> Fix hashcode for BgpRoute

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
=> IBDP: add one more span for each iteration

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
=> Using new traceroute in BGP topology generation

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LocalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType1Route.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalType2Route.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInterAreaRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfInternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfIntraAreaRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipInternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfMetricType.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/RipInternalRouteTest.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
* Make AbstractRoute fields final
* BgpRoute: cache hashcode
* Cleanup other routes' hashcode/equals
* Javadoc in places
* Remove unused code (`protocolRouteString`)
=> Towards immutable routes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpExternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetric.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EigrpRouteTest.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualEigrpProcess.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
* Builder now cannot return nulls
* Additional annotations and arg checking in places
=> Cleanup pass on EIGRP routes

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NamedPort.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/NamedPortTest.java, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4, projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/HostProtocol.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java
```
localhost(config-acl-300)#permit tcp any any eq ?
acap            Application Configuration Access Protocol (674) 
acr-nema        ACR-NEMA Digital Imaging and Communications in Medicine (104) 
afpovertcp      Apple Filing Protocol Over TCP (548) 
arns            A Remote Network Server System (384) 
asip-webadmin   AppleShare IP Web Administration (311) 
at-rtmp         AppleTalk Routing Maintenance (201) 
aurp            Appletalk Update-Based Routing Protocol (387) 
bftp            Background File Transfer Program (152) 
bgmp            Border Gateway Multicast Protocol (264) 
bgp             Border Gateway Protocol (179) 
chargen         Character Generator (19) 
cisco-tdp       Cisco Tag Distribution Protocol (711) 
citadel         Citadel (504) 
clearcase       Clearcase albd …
```
=> Arista: add NamedPort for TCP ports A-G

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java, projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, tests/parsing-tests/networks/unit-tests/configs/switchport_range, tests/parsing-tests/unit-tests-nodes.ref, tests/parsing-tests/unit-tests.ref
A small first step. Thoughts on what is minimal todo here?
=> Cisco: trunk ports allow all vlans by default

tools/BUILD
Example: `bazel run //tools:flatten --  ~/networks/foo ~/networks/foo-flat`
=> tools: add flatten

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
Get rid of copy, use Stream::max instead
=> BgpRib: minor tweak

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BumTransportMethod.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VniSettings.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VniSettingsTest.java
Add VXLAN (VNI settings) to VI model
=> Add VXLAN to VI model

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java
No real fix, just found the old code convoluted.
=> CommunityList: cleanup computeIfMatches

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java
Second verse, same as the first.
(I didn't find a third version.)
=> CommunityList: cleanup again

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniSettingsMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniSettingsMatchersImpl.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/eos-vxlan, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/eos-vxlan-no-loopback-address, projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/eos-vxlan-no-source-interface, tests/parsing-tests/unit-tests-nodes.ref
Add VXLAN VI model conversion for Arista EOS
=> Arista EOS VXLAN VI model conversion

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java, projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, tests/basic/routes-dc-as-reuse.ref, tests/basic/routes-diff.ref, tests/basic/routes.ref
- based on @saparikh's feedback, removing column for `Network Presence`(can be inferred by post-processing) and swapping `Metric` and `Admin Distance`
=> Route diff columns reorganization

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisProcessMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisRouteMatchers.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IsisRouteMatchersImpl.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java, projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisLevelRib.java, projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TestUtils.java, projects/batfish/src/test/java/org/batfish/dataplane/rib/IsisRibTest.java
Resolves #1609.
Also fixes bug where IS-IS default route's next hop was incorrectly set due to reused builder.
=> IS-IS overload

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CommonUtilTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfNeighborTest.java, projects/batfish/src/main/java/org/batfish/main/Batfish.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java, projects/batfish/src/test/java/org/batfish/dataplane/topology/IsisEdgeTest.java, projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java, projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java
Move tests too.
Aside: I'm not sure why on earth all those places depend on this function. Ought to be called once and once only ...
=> synthesizeTopology: move to TopologyUtil, rename

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Mlag.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkConfigurations.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MlagTest.java, projects/batfish/src/main/java/org/batfish/representation/cisco/MlagConfiguration.java, projects/question/src/main/java/org/batfish/question/mlag/MlagPropertiesAnswerer.java, projects/question/src/main/java/org/batfish/question/mlag/MlagPropertiesQuestion.java, projects/question/src/main/java/org/batfish/question/mlag/MlagPropertiesQuestionPlugin.java, projects/question/src/test/java/org/batfish/question/mlag/MlagProperitesAnswererTest.java, projects/question/src/test/java/org/batfish/question/mlag/MlagPropertiesAnswererTest.java, projects/question/src/test/java/org/batfish/question/mlag/MlagPropertiesQuestionTest.java
* Minor doc cleanup
* Marking many classes final
* Add MLAG to NetworkConfigurations
=> Mlag classes cleanup

projects/lib/bdd/LICENSE, projects/lib/bdd/LICENSE.email
Including the email exchange in response from a request from a user.
=> Email exchange for BDD license

projects/question/src/main/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswerer.java, projects/question/src/main/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesQuestion.java
Make VXLAN VNI properties question accessible (now it can be used in other questions)
=> Vxlan props public

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
Cleaning up my previous sloppiness
=> BgpRoute: make cached hashcode volatile and transient

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Result.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChain.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DisjunctionChain.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/ResultTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ConjunctionChainTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/DisjunctionChainTest.java
Shaving yaks while working on rib groups 🙂
=> Cleanup and minimal tests for policy chains

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java, projects/batfish-common-protocol/src/main/java/org/batfish/specifier/IpProtocolSpecifier.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PacketHeaderConstraintsTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/specifier/IpProtocolSpecifierTest.java, projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
implements IpProtocolSpecifier according to https://docs.google.com/document/d/1sc687Ovu8Vt9SNq54iUi-wDxIN7aa6z-gxU3PnSVoLI/edit?ts=5c33dded#heading=h.s5nt7cwz7s4t
=> add IpProtocolSpecifier

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultPolicy.java
* Routing policy: expose a non-test builder, allow immutable list of
statements
* Code style tweaks, javadoc
=> Minor cleanup to RoutingPolicy and SetDefaultPolicy

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTest.java, projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/GeneratedRouteTest.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java, projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java
* Javadoc, annotations, comments
* Equals, hashcode, comparator implemented sanely
* Cache hashcode
=> Cleanup GeneratedRoute

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java
Also mark RouteAdvertisement fields final.
=> Clean up objectionable code in VirtualRouter

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
=> Correct token alphabetization

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java, projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java, projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java, projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java, projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- make all topology getters in layer-1 and layer-2 return Optional
- expose broadcast domains via getter in Layer2Topology
- update javadocs
=> expose layer-2 broadcast domains and clean up topology provider API

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java, projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
`setDrop(boolean drop)` only gets called with `drop == true`, so this shouldn't affect anything.
=> Random cleanup

projects/batfish/src/main/java/org/batfish/config/Settings.java, projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
This is robust enough and always on.
=> Batfish: delete -flattenonthefly

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
* Move process null checks inside VR itself
* Inline method calls where applicable
=> Small cleanup to ibdp engine

.buildkite/pipeline.sh
Idea: we can use manually triggered builds to test out container or plugin upgrades.
=> buildkite/pipeline.sh: make vars overridable via env variables
