- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
> ipowners: add processing for HSRP

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
- tests/aws/topology-example-aws.ref
- tests/aws/vimodel-example-aws.ref
- tests/parsing-tests/unit-tests-vimodel.ref
Handles the case of multiple ISP uplinks on the same node.
> IspModelingUtils: take interface name into account

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDIntegerTest.java
And add assertions to APIs that can only be used with makeFromIndex BDDIntegers.
> BDDInteger: only use fastpath for makeFromIndex results

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_multicast
- tests/parsing-tests/networks/unit-tests/configs/arista_interface
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
This is for batfish/batfish#6054.
> Arista: track references in interface ip multicast boundary

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_aaa.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- tests/parsing-tests/networks/unit-tests/configs/arista_acl
- tests/parsing-tests/networks/unit-tests/configs/arista_bgp
- tests/parsing-tests/networks/unit-tests/configs/arista_bgp_asn
- tests/parsing-tests/networks/unit-tests/configs/arista_dhcp_relay
- tests/parsing-tests/networks/unit-tests/configs/arista_ip_route
- tests/parsing-tests/networks/unit-tests/configs/arista_nat
- tests/parsing-tests/networks/unit-tests/configs/arista_queue_monitor
- tests/parsing-tests/networks/unit-tests/configs/arista_username
- tests/parsing-tests/networks/unit-tests/configs/arista_vrf
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
And fix a few minor parsing gaps.
> parsing-tests: add arista line to all files

- projects/batfish-common-protocol/BUILD
- projects/batfish-common-protocol/pom.xml
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/GrammarTest.java
> Grammar: update link to point to readthedocs

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- NOP when directories to clean do not exist
> Fix exceptions running GC on fresh storage

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
Use the utility function we wrote
> Transitions: trivial fix

- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_nat
> Arista: support nat pools with broadcast IP if single IP address

- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
https://buildkite.com/batfish/batfish-vulnerability-scan/builds/117#f9b63676-bff3-458d-9d34-fb63fce82ff1
> SearchRoutePoliciesAnswerTest: fix deprecated API use

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface_show_run_all
speed auto does not require a bandwidth specifier
> Arista: interface speed cleanup

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface_show_run_all
> Arista: interface ip arp inspection

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
Previously we had only two edges out from `PbrFibLookup`:
- `PbrFibLookup` -> `InterfaceAccept` for flows destined to IPs owned by the ingress VRF
- `PbrFibLookup` -> `PreOutVrf` (where the pre-out VRF is the lookup VRF) for all other flows
This was incorrect because the `PreOutVrf` state should only be reached by flows routable in that VRF. This PR splits the second edge accordingly:
- `PbrFibLookup` -> `PreOutVrf` (where the pre-out VRF is the lookup VRF) for flows that are routable in the lookup VRF and not accepted in the ingress VRF
- `PbrFibLookup` -> `NodeDropNoRoute` for flows that are neither routable in the lookup VRF nor accepted in the ingress VRF
> Create PbrFibLookup -> NodeDropNoRoute edge

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/Interface.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface_show_run_all_3
Extract it, but don't yet support it.
This is for batfish/batfish#6128
> Arista: parse interface ip local-proxy-arp

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
> PAN: deprecate defineStructure, link to defineFlattenedStructure

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
Factor out common managed-configuration-creation code.
No functional change.
> PAN: factor out managed config creation

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/isp_configuration/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/isp_configuration/IspConfigurationTest.java
- projects/batfish-common-protocol/src/test/resources/org/batfish/datamodel/isp_configuration/BUILD
- projects/batfish-common-protocol/src/test/resources/org/batfish/datamodel/isp_configuration/isp_configuration.json
> IspConfiguration: add a deserialization test

- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
It's know to be unsafe, we won't use it again.
> JFactory: delete BDDWImplWithFinalizer

- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/OspfRedistributionPolicy.java
> Arista: remove classful handling.

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/FalseExpr.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/TrueExpr.java
- projects/batfish/src/test/java/org/batfish/datamodel/acl/FalseExprTest.java
- projects/batfish/src/test/java/org/batfish/datamodel/acl/TrueExprTest.java
Introduced in batfish/batfish#6188
> False/TrueExpr: add json test and fix serialization bug

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosBgpTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/bgp/nxos-bgp-update-source-shutdown
> NX-OS: consider all interfaces for BGP update-source

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- tests/basic/genDp.ref
> Revert "bdp: remove queues for sending BGP messages"

- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
- projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
- projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesQuestion.java
- projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java
- questions/experimental/searchRoutePolicies.json
- questions/experimental/testRoutePolicies.json
- tests/questions/experimental/searchRoutePolicies.ref
- tests/questions/experimental/testRoutePolicies.ref
1. Fix type information in templates for policies parameter
2. Make nodes and policies optional parameters in question constructor
3. Some cleanup
No functional change
> fix the type information for routing policies in templates

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
Trying to simplify, w/o deleting which code we need to care about vs ignore.
> BDP: Comment out stale code

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
cleaning up bits and pieces as I'm debugging :)
> bdp minor cleanup: remove stale todo and unused queues

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
Generally more memory and otherwise efficient.
> DataplaneUtil: build immutable structures

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-ospf-prefix-priority
Fixes https://github.com/batfish/batfish/issues/6238
> Parsing for OSPF prefix priority

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
Rather than building two filtered maps that are only used once, filter on-the-fly.
> ForwardingAnalysisImpl: inline two intermediate collections

- projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
- projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
> AWS NGW: Tweak NGW filtering criteria

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlaneSettings.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PrefixTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RouteDependencyTracker.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/schedule/MaxParallelSchedule.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/schedule/NodeColoredSchedule.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/schedule/NodeSerializedSchedule.java
> ibdp cleanup: make classes final, add javadocs, fix some typos

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
In particular:
1) don't assert that PBR and incomingFilter are mutually exclusive
2) give priority to PBR over incomingFilter
> reachability: handle PBR the same way FlowTracer does

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nat-iprange
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-iprange
Add validity checks for Palo Alto NAT ip-ranges.
> PAN: validity checks for NAT ip-ranges

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNetwork.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpVrf.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
* Parsing, extraction
* Conversion
> Cumulus FRR: support route maps for BGP network statements

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
Want to be able to use the tracing results downstream instead of just the binary logic.
> Widen BgpTopologyUtils interface to make the session initiation results available

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationBuiltIn.java
* bfd
* gre
* pim
* snmp-trap
* syslog
* tacacs
* tacacs-plus
> PAN: add more built-in applications

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_show_run_all_4
The test checks the overwriting-route-map bug we hit in BGP weight.
> Arista: add another show run all for bgp

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
> PAN ConfigurationBuilder: common code for determining rulebase

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_interface.g4
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/interface-units
adjust-tcp-mss, netflow profile
These do not affect our analysis in any way
> PAN: parse and ignore irreleveant interface lines

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpAdvertisementTest.java
1/ separate json creator and constructor
2/ canonicalize node names (a slack user tripped up, the impetus of going into this file).
> Minor clean up of external bgp advertisement parsing

- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-area-interface-all
> Juniper interfaces: inherit more OSPF settings from parents

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_hsrp
Help parser stay in interface context
> NXOS: parse hsrp bfd

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java
> PAN security rule tags: switch to Set

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_route_map.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapEntry.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapSetMetricEigrp.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapSetVisitor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_route_map
Docs https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/nxos/commands/bgp/set-metric.html
> NXOS route-map: support setting of EIGRP metric

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpProcess.java
We should (and are) setting EIGRP admin costs in conversion.
> EigrpProcess: remove unused code

- .idea/vcs.xml
- projects/batfish-common-protocol/src/main/java/org/batfish/common/CompletionMetadata.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/CompletionMetadataTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/autocomplete/LocationCompletionMetadataTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/InputValidationUtilsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- projects/batfish-common-protocol/src/test/resources/org/batfish/common/util/deprecated_source_location.json
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Reviewing the first commit (which has no functional changes) might help.
> Autocompletion for TR sources

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EigrpRoutingProcessTest.java
> EIGRP: guard against redistribution NPE

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TraceDag.java
A little less computation, a little less Array allocation.
> TraceDag: minor improvements

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
Do not need to use concurrency,  just collectors.
> TracerouteEngine: simpler way of building result map

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/Breadcrumb.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/DagTraceRecorder.java
These classes have many fields and are hashed often during traceroute
> traceroute: memoize some hash codes

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-eigrp-distribute-list-routemap
Hopefully the final nail in this coffin for the foreseeable future
> IOS: support EIGRP distribute lists with route maps

- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
Log did not match function name
> WMS: fix a log message

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/parsing/AristaBaseLexer.java
_inAccessList is only written, never read.
> Arista: delete unused lexer state

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteDecoratorMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteDecoratorMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/StaticRouteMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/StaticRouteMatchersImpl.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
It's not StaticRoute specific.
> Matchers: move hasTag to AbstractRouteDecorator

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetTagLine.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map-set-tag
> Cisco/IOS: implement set tag

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-vtnet
These are virtualized physical interfaces.
> Juniper: add parsing support for vtnet interfaces

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
At some point we introduced ability to connect subinterfaces of aggregate interfaces via link-local addresses.
But the code had a bug where we would connect such interfaces even if they had non-LLA, concrete IP addresses.
This fixes that bug.
> L3 topology inference: fix a bug with aggregate subinterfaces and LLAs

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Deleter.java
- projects/batfish/src/main/java/org/batfish/grammar/hierarchical/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/hierarchical/StatementTree.java
- projects/batfish/src/main/java/org/batfish/grammar/hierarchical/package-info.java
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PreprocessPaloAltoExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/delete-and-move-lines
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/delete-line
Implement a pre-processor for delete lines, similar to that used for Juniper
> PAN: support for delete lines

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios_bgp_show_run_all
> IOS: add a bgp show run all

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RouteMapSetMetricEigrp.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
Also improve documentation to reduce chances of this happening again.
> NXOS EIGRP metric: fix delay conversion

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
Do not create an EIGRP redistribution policy if none of the redistributed protocols are supported (doesn't make a practical difference, but the policy is pointless if created because it will reject everything).
> NXOS EIGRP redist: No policy if no supported protocols

- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/AddressFamilyType.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Vrf.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/VrfAddressFamily.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrf-definition
Keep track of address family config
Make route targets a set
Fix up reference tracking for import map
> IOS XE: improve vrf definition extraction

- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp_redist
Note that redistributed routes will not have correct tags until #6512 is merged.
> NXOS: Redistribute BGP into EIGRP

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Per lab validation, these are not generated.
> FRR: do not generate local routes

- projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/f5_bigip/PoolMember.java
- projects/batfish/src/test/java/org/batfish/representation/f5_bigip/F5BigipConfigurationTest.java
> F5: reject PoolMember on port 0

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
Minor nits, but reduces confusion
> Routing policy: more annotations

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-multipath-none
- tests/parsing-tests/unit-tests-vimodel.ref
🤦 
Good thing no one ever runs non-multipath except in small labs :)
> Juniper: fix default multipath setting when not configured

- projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Parsing for the following in router bgp
```
address-family l2vpn evpn
advertise ipv4 unicast route-map storage-map1
advertise ipv6 unicast route-map storage-map1
exit-address-family
```
> FRR parsing for advertise unicast

- projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
Cumulus VM merges the commands within multiple paras of the same address family.
> FRR: Merge commands in multiple AF stanzas

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
Understandability, readability, and reusability.
> BgpAdvertisement: cleanup, comment, factor out main code

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
Code coverage is changing randomly for this class based on e2e tests.
Improve code mildly, removing two unused functions.
> AclTracer: cleanup a little

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/WarningsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/WarningMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/WarningMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/WarningsMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers/WarningsMatchersImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationErrorTest.java
- projects/batfish/src/test/java/org/batfish/representation/aws/BUILD
- projects/batfish/src/test/java/org/batfish/representation/aws/UtilsTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco/BUILD
- projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsBgpPoliciesTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/BUILD
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/NatRuleThenPoolTest.java
- projects/question/src/main/java/org/batfish/question/initialization/IssueAggregation.java
- tests/parsing-tests/unit-tests.ref
Prevent duplicate unimplemented, pedantic, and redFlag warnings.
> Warnings: dedupe

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IntegerSpace.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
> Add a method to IntegerSpace builder that helps compute difference

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ospf-network-area
Follow-up to batfish/batfish#6612
> FRR: convert OSPF network area

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchLocalPreference.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
> RoutingPolicy: implement MatchLocalPreference

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java
- projects/batfish/BUILD
- projects/batfish/pom.xml
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/BUILD
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_system.g4
- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosCombinedParser.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosPreprocessor.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/package-info.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/parsing/BUILD
- projects/batfish/src/main/java/org/batfish/grammar/fortios/parsing/FortiosBaseLexer.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/parsing/FortiosBaseParser.java
- projects/batfish/src/main/java/org/batfish/grammar/fortios/parsing/package-info.java
- projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/BUILD
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/package-info.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/package-info.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/BUILD
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/fortios_hostname
- projects/pom.xml
- detect FortiOS configs
- parse hostname
- basic grammar, tests
> FortiOS grammar skeleton

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/domain
Fix batfish/batfish#6676, thanks @kmjmartin!
> PAN: extract system domain name

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/IfTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
- unsound if guard has side-effects
- currently no way to determine this
> disable simplification of If with no branch statements

- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_system.g4
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/fortios_system_recovery
- recover immediately after unrecognized line in system
- don't throw away subsequent interface
> fortios fix system parsing for better recovery

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
To reuse the logic in other places
> Make BGP peer compatibility checking public

- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_address.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_system.g4
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy
Add support for lists of object names as well as fix a couple problems that surfaced from this:
* Support `str` lists
* Fix/improve `toXInSpace`
* Add missing `pushMode`
* Use a `newline` rule
> FortiOS: support lists of object names

- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/InterfaceAny.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/InterfaceOrZone.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy_warn
* Correct policy command enforcement w/ `any`/`all` references
* Add support for `any` interface
> FortiOS: policy: support for any/all

- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_address.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4
- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/rename
Add support for renaming `address` and `service custom` structures.
> FortiOS: support rename

- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/PolicyTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/edit_recovery
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy_warn
Fyi, I didn't find any invalid lines you can enter in the CLI that will pop you out of the policy edit block.
> FortiOS: Policy edit block validation

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java
* Move service `toMatchExpr` into `FortiosConfiguration`
* Add vendor structure info to service `TraceElement`
> FortiOS: service conversion update

- tools/BUILD
The path changed in batfish/batfish#6642.
> tools: fix preprocess

- projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/edit_recovery
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/service_custom
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/service_warnings
Also minor extraction improvement for services: can't set ICMP code before type.
> FortiOS: Service edit block validation

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- replace SetCommunity with SetCommunities and related new classes
> juniper use new community api

- projects/batfish/src/main/java/org/batfish/representation/f5_bigip/RouteMapSetCommunity.java
- tests/parsing-tests/unit-tests-vimodel.ref
- port RouteMapSetCommunity to new community API
> f5 use new community api

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java
- populate NodeProperties facts for the 4 new community processing structures
> Update NodeProperties for new community structures

- projects/allinone/BUILD
- projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteTest.java
And fix #3588
This has been fixed for a while.
> TracerouteTest: unskip route-after-nat test

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java
Update address `TraceElement`s to match style of other `TE`s in FortiOS
> FortiOS: update `TraceElement`s for addresses

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
Also sets VI interfaces' zone names.
> FortiOS: Convert zones

- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_aspath.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_acl.g4
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/IpAsPathAccessList.java
- projects/batfish/src/main/java/org/batfish/representation/arista/IpAsPathAccessListLine.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/as-path-access-list
* Delete old generic code, add new file
* Fix modes to properly extract words
* Add extraction tests
* Add warnings
Fix #6758
> Arista: redo parsing for ip access-list stanza

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
Adds support for handling route suppression / unsuppression to the symbolic route policy analysis.
> TransferBDD: Support route (un)suppression

- questions/stable/bgpRib.json
- questions/stable/evpnRib.json
- tests/questions/stable/bgpRib.ref
- tests/questions/stable/evpnRib.ref
To be removed after the next Batfish release.
> Insert a note about the availability of specialized RIB questions

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/parsing/CiscoBaseLexer.java
> IOS: delete _enableIpAddress predicate

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/name
> JunOS: enhance characters allowed in names

- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/RouteMapMatchCommunityListLine.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_asa/CiscoAsaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_asa/testconfigs/asa-community-route-map
- add route-map community tests
> Cisco ASA port match community to new API

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
> VI Interface: dependency type doc update

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/route_map
Still not yet attached to anything (BGP processes/neighbors)
> FortiOS: Convert route-maps

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_policy_map.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_policy_map
logging drop threshold
policy with more units and types of matching
> NX-OS: more parsing for policy-map

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_class_map.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_class_map
> NX-OS: more class-map matching

- questions/Parameters.md
- follows batfish/batfish#6853
> Refer to new community API in Parameters.md

- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java
Add support for deleting a structure's references and definitions.
> Reference & Definition tracking: support delete

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpaceMetadata.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpSpaceMetadataTest.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosPolicyConversionsTest.java
Example trace: <img width="434" alt="Screen Shot 2021-04-08 at 4 31 10 PM" src="https://user-images.githubusercontent.com/526415/114108400-e1b9f700-9887-11eb-916a-56f368a671d4.png">
> FortiOS: provide metadata for converted address and groups

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp
Working on fleshing out the test to examine the generated routing policies, but opening PR now to allow review to start.
> FortiOS: Convert BGP network statements

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Icmp6Code.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Icmp6Type.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-ipv6-access-list
- create Icmp6Type and Icmp6Code data model classes
> IOS-XR parse and ignore ipv6 access-list icmpv6 address-unreachable

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_interface.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-interface-address
- update ipv4 address parsing for XR syntax
- parse and ignore ipv6 address
> IOS-XR interface ipv4/6 address parsing

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties
> NX-OS: parse interface no ip port-unreachable

- projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java
- projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/iptables/IpTablesVendorConfigurationTest.java
> Don't crash for unsupported IpTables actions

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_mpls.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-mpls
- parse mpls oam
- refactor mpls grammar
> IOS-XR parse and ignore mpls oam

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_interface.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_qos.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_tftp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/SimpleExtendedAccessListServiceSpecifier.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-dscp
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-ethernet-services
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-tftp
- tests/parsing-tests/unit-tests-unused.ref
- tests/parsing-tests/unit-tests.ref
- parse tftp
- make `access-list` push into M_Word for all instances (including tftp)
> IOS-XR tftp parsing and access-list name refactor

- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- tests/parsing-tests/unit-tests-vimodel.ref
Mimicking #6748 for IOS-XR (cc: @sfraint)
> XR: Mark generated routes' origin type IGP

- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/bgp-redist-policy
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-vimodel.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
Add support for route-policies in BGP redistribution
> XR: Support route-policies in BGP redistribution

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/ConjunctionTest.java
- tests/parsing-tests/unit-tests-vimodel.ref
Looks like @dhalperi did something very similar with `Disjunction`, almost 3 years ago.
> Fix simplify logic for Conjunction

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
> IOS-XR: simplify VARIABLE lexer rule

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_rpl.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanValidationStateIs.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cisco_xr/BUILD
- projects/batfish/src/test/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanValidationStateIsTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/rp-validation-state
Extract, and assume that RPKI advertisements are always valid.
> IOS-XR: handle route-policy validation-state is

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureUsage.java
This is not valid syntax (router ospfv3)
> IOS-XR: remove 'ipv6 router ospf'

- projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/BUILD
- projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/BUILD
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/batfish-missing-loop/layer1_topology.json
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/batfish/layer1_topology.json
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/configs/fw-1.cfg
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/configs/rtr-1.cfg
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/configs/rtr-isp-1.cfg
- projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/configs/sw-1.cfg
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer2NodeTest.java
Otherwise equivalent nodes will not be considered the same.
> Layer2Node: canonicalize ranges

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java
Wrong variable used in checkArgument
> Layer2Node: fix variable type

- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Grammar.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/ParserUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserUtilsTest.java
Multiple users didn't realize that the notes at the top were relevant to them.
> Add URL for general grammar notes

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
> Convert: finalize AsPathExprs during conversion

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv4AccessListLine.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv4Nexthop.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv6AccessListLine.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv6Nexthop.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/BUILD
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/abf
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/abf_extraction
Parse and extract ACL based forwarding constructs for XR.
> XR: VS support for ABF constructs

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
Known issue in FRR: https://github.com/FRRouting/frr/issues/2922
> FRR: OSPF loopbacks have cost 0 always

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-hostname.domain
XR allows you to put part of the domain name in the hostname.
> IOS-XR: allow period in hostname

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDDState.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferParam.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
Updates the symbolic route analysis to track a BDD representing the conditions under which the default action is true, rather than just a boolean as previously done, and similarly for the default local action.  This allows us to properly handle updates to the default action that occur within conditional statements.
> SearchRoutePolicies: Proper handling of updates to the default actions

- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RouteAdvertisementTest.java
Sick of test coverage being randomized based on e2e tests.
> RouteAdvertisement: add missing unit test coverage

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DeliverFromVlan.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DeliverTaggedFrames.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DeviceBroadcastDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DomainToL2Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/Edge.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/Edges.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/EthernetHub.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/EthernetTag.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3Interface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/Node.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/NodeAndData.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/OriginateInVlan.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/OriginateWithTag.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/PhysicalInterface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/Preserve.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/package-info.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/BUILD
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/DeliverFromVlanTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/DeliverTaggedFramesTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/DeviceBroadcastDomainTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/DomainToL2InterfaceTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/EthernetHubTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/EthernetTagTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/L3InterfaceTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/NodeAndDataTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/OriginateInVlanTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/OriginateWithTagTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/PhysicalInterfaceTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/PreserveTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/TraversalTest.java
Create a heterogenous graph of nodes and edges, and traverse it to discover L3
interfaces in the same domain.
> topology: ground work for new L3 adjacency algorithm

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NodeInterfacePair.java
As far as I know, this is only developer facing. But it's so much easier to read.
> NodeInterfacePair: modernize toString

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
#7082 added TraceableStatement which is a statement that wraps a list of other statements.
> Add support for TraceableStatement in SRP

- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-access-vlan
It defaults to 1, not nothing.
> IOS: fix access vlan default

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisArpFailureDispositionsTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java
This reverts commit 631c313e9d7b113dcb841ffc63c4d8a33667a833.
We're still thinking.
> Revert "Insufficient Info: consider network/broadcast IPs to be internal (#7118)"

- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
Cleanup the vendor format detection code a bit. No functional change.
> Vendor Format Detection: cleanup

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/PhysicalInterface.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/TraversalTest.java
Standard configuration to have more than one unit.
> PhysicalInterface: allow multiple L3 subinterfaces

- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayParser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGateway_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGateway_interface.g4
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/Interface.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/package-info.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/interface
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/interface_warn
Add initial interface parsing and extraction for Check Point Gateways.
Also updated lexing to support quoted strings.
> Check Point: initial interface extraction

- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
- projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
Batfish has historically used RANCID headers as a foolproof way to allow users
to identify the format of a given file. However, this approach is limited:
1. RANCID's database is incomplete: https://www.shrubbery.net/rancid/man/router.db.5.html
has no entry for things like A10 or Check Point.
2. In general, the RANCID classifications are not at the same granularity as
Batfish. This impedance match can be confusing for users.
Instead, introduce a similar new header:
#BATFISH-FORMAT: <any Configuration_Format enum value>
This lets users exactly specify the precise Configuration Format they want
Batfish to use.
I also made it a bit more generous than RANCID:
- allow any number of spaces between any of the parts
- allow - or _
Since I've seen users make these mistakes.
> Introduce #BATFISH-FORMAT header

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/interface_conversion
Only handling physical L3 and loopback interfaces so far.
> Check Point Gateway: initial iface conversion

- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
Need access to the two workhorse functions individually, not the end-to-end wrapper. Reverted the earlier API change.
> Filter line API change

- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayParser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGateway_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGateway_static_route.g4
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/Nexthop.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/NexthopAddress.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/NexthopBlackhole.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/NexthopLogical.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/NexthopReject.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/NexthopTarget.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/StaticRoute.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/BUILD
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/NexthopTargetTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/static_route
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/static_route_warn
Add initial parsing and extraction for Check Point gateway static routes
> Check Point gateway: static route extraction

- projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
This helps with testing of downstream usage
> More public-ness in filter line classes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableMetadata.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/TableDiffTest.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java
And fix up existing answerers and tests
> TableAnswer: require at least one key column

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
ForwardingAnalysis distinguishes between ARP errors for owned vs unowned IPs for the purposes of assigning FlowDisposition. Previously we checked whether the top-level route's next-hop IP was owned, instead of the resolved ARP IP. This change fixes that, and also rewrites the classification logic to make clear that a single route can resolve to both an owned and an unowned  ARP IP (also a bit more efficient).
> ForwardingAnalysis: use ARP IP instead of top-level route's next-hop IP

- projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_show_all_2
Add another interface show run all and fix mixed switchport mode commands.
> NX-OS: retain switchport mode if set

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/InterfaceNameComparator.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/InterfaceNameComparatorTest.java
Test serialization, and some more corner cases directly.
> InterfaceNameComparator: flesh out tests a bit

- projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
- fix nonrecursive static route changes not being processed for side effects
- fix crash on demotion of nhip route to backup
> Fix various main RIB resolvability backup route bug

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
In VI, channel group is an interface name.
> CP: Fix channel group conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java
- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Nothing in ConversionContext class yet, just a placeholder.
> Create ConversionContext and make accessible in conversion

- skylark/junit.bzl
We need a java_library of the tests in order to run PMD. Previously,
we compiled the sources twice: once in the java_test (passing sources as sources)
and once in the java_library for pmdlib.
Now, generate the testlib first and use the same lib for both java_tests (deps)
and pmd_test (lib). This saves a compilation.
> junit.bzl: compile test sources only once

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AllNatInstallTarget.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListNatInstallTarget.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatInstallTarget.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatMethod.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRule.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRuleOrSection.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRulebase.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatSection.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Package.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/TypedManagementObject.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Uid.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AllNatInstallTargetTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ListNatInstallTargetTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ManagementPackageTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRuleTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRulebaseTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatSectionTest.java
> checkpoint vs model add nat rules

- projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Domain.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServerPolicy.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRulebase.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Package.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/SimpleGateway.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
- projects/batfish/src/test/java/org/batfish/main/TestrigText.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/BUILD
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/gw_package_selection_1
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/gw_package_selection_2
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/gw_package_selection_3
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/gw_package_selection_4
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/gw_package_selection_5
- add test infrastructure to use pre-populated ConversionContext
> Checkpoint gateway conversion use correct package

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/TypedManagementObject.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AccessRulebaseTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/RulebaseActionTest.java
Add VS model support for `RulebaseAction` object type.
> CheckPoint: `RulebaseAction` object type

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceTcp.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRulebaseTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceTcpTest.java
Add a `port` number to `ServiceTcp` VS class and add a basic test.
> CheckPoint: add ServiceTcp port

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RoutingStep.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/traceroute/TraceDagImplTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/HopTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/HopTestUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/RoutingStepTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/DagTraceRecorderTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
- tests/basic/traceroute-1-2.ref
- tests/basic/traceroute-2-1.ref
With next-vrf routes, the same hop can route in multiple VRFs.
Add this information to RoutingStepDetail.
> RoutingStepDetail: add vrf information

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Group.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/GroupTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRulebaseTest.java
Add `members` field for CheckPoint `Group` objects
> CheckPoint: `Group` `members`

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/SrcOrDstToIpSpace.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/SrcOrDstToIpSpaceTest.java
Adds visitor to generate `IpSpace`s for `SrcOrDst` objects
> CheckPoint: implement `SrcOrDestVisitor` for to-`IpSpace`

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRule.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRuleOrSection.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRuleOrSectionVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatSection.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedAddress.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedAddressVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedService.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedServiceVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Original.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceVisitor.java
- interfaces and visitors for NAT rule concepts
- partial conversion, but not applied to any interfaces
> Checkpoint NAT conversion skeleton

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- TODO: support more than one page
> Checkpoint read gateways-and-servers as list of pages

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- refactor warning logic for checkpoint parsing
- warn for all exceptions, and do not rethrow
> Checkpoint better parse warnings

- projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/CheckPointGateway_static_route.g4
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/static_route_off
Add support for removing static routes and static route nexthops
> CheckPoint: support static route `off`

- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewaysAndServers.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRulebase.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java
- slight refactor of other merge code
- documentation
> Checkpoint mgmt merge show-gateways-and-servers pages

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceIcmp.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceIcmpTest.java
> Checkpoint mgmt service-icmp allow no icmp-code

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- prevent multithreaded access
> Checkpoint mgmt fix visitor service converter race

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceVisitor.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceToMatchExprTest.java
Merge conflict re-introduced bugs.
> Checkpoint: restore use of correct port string converter

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
* Add some informative VI model constructs for bad IpSpace references
* Add warnings for bad IpSpaces and Actions
> CheckPoint: better handling of bad IpSpace and Action references

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpace.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Host.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Machine.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedAddress.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedAddressVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSource.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Original.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java
- fix hierarchy
- allow AddressRange
- disallow IPv6 entities
> Checkpoint fix manual hide translated source handling

- projects/question/src/main/java/org/batfish/question/routes/RouteRowAttribute.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/BUILD
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
> BgpRib: add weight column

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadataTest.java
This will help make address-based traces better.
> CheckPoint: add IpSpaceMetadata

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToMatchExpr.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CheckPointManagementTraceElementCreators.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToMatchExprTest.java
Add tracing for `AddressSpace` objects.
> CheckPoint: `AddressSpace` Tracing

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/Interface.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface
> Arista: reorganize L2/L3 settings

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
1. don't use `ComparableStructure` for anything :shudder:
2. https://buildkite.com/batfish/pybatfish-pre-commit/builds/24803#56cb55af-058a-4c58-8128-381dccb93119
3. Simple, existing logic.
> IpOwners: fix comparator

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
No functional change yet, but this setup makes it much easier to create and apply different NAT transformations per interface.
> CP: Refactor NAT conversion to after iface conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/VrrpComputationTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PartialDataplane.java
- projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
- projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
This reverts commit 86ed1033f935765a63e49f2ebfd0d9cb67e51312.
There are some mysterious test failures downstream, which might take me some time to debug. This revert will unblock other PRs.
> Revert "IpOwners: VRRP IP disambiguation (#7416)"

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/VrrpComputationTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PartialDataplane.java
- projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
- projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
- projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
This reverts commit e2be9c4c3eef17473a92b773096dc08cb7b9262c.
> Revert "Revert "IpOwners: VRRP IP disambiguation (#7416)" (#7421)"

- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressRangeTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadataTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToMatchExprTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/BUILD
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/HostTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatSettingsTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NetworkTest.java
- projects/batfish/src/test/java/org/batfish/vendor/check_point_management/TestSharedInstances.java
- move NatSettings.TEST_INSTANCE to new class without junit tests
- update BUILD file, remove unnecessary deps
> Remove junit tests from cpm vs shared module

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspConfigurationException.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
(A user and I ran into this problem within an hour of each other today.)
> User-facing warning for bad ISP files

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/interface_dependencies/InterfaceDependenciesTest.java
Generally, don't crash if the topology includes a non-existent node; just skip it.
> InterfaceDependencies: be robust to INVALID_INTERFACE in the l1 topology

- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
Mainly pulled out common setup/boilerplate to make it easier to add more variants of tests.
> Refactor tests for ISP modeling utils

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EmptyIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UniverseIpSpace.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpWildcardSetIpSpaceTest.java
1. No functional changes
2. Changes to IpWildcardSetIpSpace
> IpSpace: let implementations provide their own complement 

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDIntegerTest.java
There is no need to construct the BDDs for lower or upper bounds
when they are equivalent to true.
> BDDInteger: optimize #range

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
> TracerouteUtils: reorder sorting and uniquifying

- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip_route.g4
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/StaticRouteManager.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/static_route
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/static_route_delete
Add support for `no ip route ...`
> A10: support deleting static routes

- projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
The TracerouteEngine can be asked to trace arbitarily many flows,
but tracing flows can actually take quite a bit of working memory.
Make the engine robust to these cases by chunking the flow requests.
Observable overhead should be negligible in both memory and CPU.
> TracerouteEngineImpl: add internal batching

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/IncomingSessionScopeTest.java
Sick of fraudulent coverage changes on PRs
> IncomingSessionScope: test

- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip_nat.g4
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/NatPool.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/nat_pool
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/nat_pool_warn
NAT pool parsing and extraction.
> A10: NAT pool extraction

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
Use running LongSpace instead of iterating over other pools each time.
> A10: better NAT pool overlap detection

- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_slb_server.g4
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10StructureType.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Server.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServerPort.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServerTarget.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServerTargetAddress.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/representation/ServerPortTest.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/representation/ServerTargetAddressTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server_warn
Parse and extract `server` and it's `port` object configuration.
> A10: initial `Server` extraction

- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
A SortedSet or SortedMultiset requires a comparator that is consistent with equals,
aka, it cannot compare objects that aren't equal equally.
> RoutesAnswerer: can't use sorted multiset

- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_virtual_router.g4
- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/static-route-misc
* BFD
* Path Monitor (and warn if enabled)
* route-table (and warn if not unicast)
> PAN: more parsing for static routes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableAnswerElement.java
Now that Rows is insert-ordered, it should be just as good.
> TableAnswerElement: delete rowsList

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizer.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizerTest.java
follow-up for https://github.com/batfish/batfish/pull/7638
> BDDReachabilityGraphOptimizer: handle self-loops, fix stats

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyProvider.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/main/java/org/batfish/question/edges/EdgesQuestion.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
Returns the canonicalized user-provided layer1 topology.
> Edges: add EdgeType.USER_PROVIDED_LAYER1

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapConvertor.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatch.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchAsPath.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchCommunity.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchInterface.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchIpAddressPrefixLen.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchIpAddressPrefixList.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocol.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapMatchTag.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSet.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetCommListDelete.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetCommunity.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetExcludeAsPath.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetIpNextHopLiteral.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetLocalPreference.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetMetric.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetMetricType.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetPrependAsPath.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetTag.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetWeight.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapConvertorTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchIpAddressPrefixLenTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchIpAddressPrefixListTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java
Use FrrConfiguration instead of CumulusConcatenatedConfiguration for route map conversion.
> Frr: Liberation step 1: Routemap conversion

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OutOfBandConfiguration.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
> Frr: Liberation step 3: Liberate OSPF conversion

- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cumulus/OutOfBandConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
> Frr: Liberation step 4: Liberate BGP conversion

- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-rulebase-mixed-namespace
Add example test for https://github.com/batfish/batfish/issues/7698
> PAN: add test for application mixed-namespace-issue

- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
be robust to rib tables missing entries for matching node/vrf keys. also some minor cleanup
> fixup #7701

- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_routemap.g4
- projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
Fixes https://github.com/batfish/batfish/issues/7673
Via https://docs.frrouting.org/en/latest/routemap.html
> Frr: Parsing for route-map set ipv6

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
Use a separate helper function and guard statements behind an "any-automatic-rule-matches" condition.
No functional change in this PR, but setting up for handling low-priority manual NAT rules.
> CheckPoint: refactor Automatic NAT

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
CheckPoint NAT cleanup after #7718
> CheckPoint NAT: cleanup after #7718

- projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/frr/FrrConversionsTest.java
- put `Layer2Vni`s in default VRF following batfish/batfish#7731
> FRR fix Layer2 VNIs

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
Helps communicate the configuration of new Warnings objects  without having to pass three booleans.
> Add Warnings.Settings class

- projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
- projects/batfish/src/main/java/org/batfish/job/ParseResult.java
- projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
- projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationResult.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/main/java/org/batfish/main/annotate/Annotate.java
- projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationJobTest.java
- projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationResultTest.java
- tests/basic/example-iptables-init.ref
- tests/parsing-tests/unit-tests.ref
@arifogel - new changes are in the second commit
> Multifile parsing jobs 2

- projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusConversions.java
- projects/batfish/src/test/java/org/batfish/representation/cumulus_nclu/CumulusConversionsTest.java
Put `Layer2Vni`s in default VRF following batfish/batfish#7731
> Cumulus NCLU fix Layer2 VNIs (#7737)

- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/service_group
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/service_group_warn
* Fix crash
* Allow re-entry w/o protocol
* Disallow definition w/o protocol
> A10: handle omitted protocol for `service-group`s

- projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/StorageProvider.java
- projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java
- projects/batfish/src/main/java/org/batfish/main/Batfish.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
SONiC packaging will be `sonic_configs` -> `dir(s)` -> {`frr.conf`, `configdb.json`}. This PR unwraps this packaging to create parsing jobs. No actual handling of SONiC jobs here.
> Sonic: Make parsing jobs

- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_routemap.g4
- projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
The feature is described here (separately from other route map statements): http://docs.frrouting.org/en/stable-8.0/zebra.html#clicmd-set-src-ADDRESS
> Frr: Parse route-map set src

- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
Fixes https://github.com/batfish/batfish/issues/7677
> Frr: Some more IPv6 parsing

- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
Rather than creating one statement per internal traffic object,
create one overall.
> CheckPoint: simplify produced PacketPolicy for untranslated internal packets

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
It is useful to have a single place we define the set of valid flows, so that
we can post-process, pre-process, or otherwise filter sets of flows down to
sets of valid flows.
Move to AclLineMatchExprs from private inside BDDPacket, and move BDDPacket
onto it.
> AclLineMatchExprs: add VALID_FLOWS, port BDDRepresentativePicker on it

- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/L3Interface.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/MgmtVrf.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/BUILD
- projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/MgmtVrfTest.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/basic/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/mgmt/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/mgmt/sonic_configs/device/frr.conf
Note that management interface are not being turned off like for other vendors (because we cannot tell from their name (eth0) that it is a management interface. I'll figure out a way to do that later.
> Sonic: Parse and convert management configuration

- projects/symbolic/src/main/java/org/batfish/symbolic/state/PacketPolicyAction.java
> PacketPolicyAction: fix toString

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HopMatchers.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
- projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r2
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/hosts/h1.json
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/hosts/h2.json
- projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/layer1_topology.json
- evpn -> bgpv4
- bgpv4 -> evpn
- add e2e tests of NX-OS L3 VNI connectivity
> Cisco NX-OS BGP leak configs

- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
The old version added unnecessary/unproductive overloads that
messed up other things.
> BDD: clean up equals and hashCode

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
Simple heuristic to minimize the number of times we visit the same state.
> BDD fixpoint: visit dirty states in order of increasing number of previous visits

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Using parallelStream with LinkedList is not thread safe (`forEach(jobs::add)`). So, made it sequential stream. The perf gain of parallel stream is unclear in this context.
> Don't use parallel stream with LinkedList

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
- projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Identity.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java
- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDBitVector.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/highlevel/NQueensTest.java
Reverts batfish/batfish#7831
Some downstream tests are double-freeing. That may be downstream
caller error; but reverting to investigate.
> Revert "BDD: progress towards less garbage"

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
- projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/EraseAndSet.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Identity.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveLastHopConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveOutgoingInterfaceConstraints.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java
- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDBitVector.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/highlevel/NQueensTest.java
Everything from #7831, with bugfixes.
> BDD: progress towards less garbage

- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/loopback/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/loopback/sonic_configs/device/frr.conf
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/ntp_server/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/ntp_server/sonic_configs/device/frr.conf
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/syslog_server/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/syslog_server/sonic_configs/device/frr.conf
1. Mark structures. (ConfigDb structures are still not being tracked.)
2. Convert loopback (fix parsing bug there), ntp, and syslog. Add tests. 
3. Call FRR conversion.
> Sonic: v0 of full conversion

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
1. Introduce BDDFactory#andAll, essentially an exact copy of #orAll.
2. Use it in a few places to reduce BDD garbage.
> BDDFactory: introduce andAll and use it a bit

- projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusConcatenatedConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/community_list_reference_tracking
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/community_list_reference_tracking/sonic_configs/device/config_db.json
- projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/community_list_reference_tracking/sonic_configs/device/frr.conf
Neither Cumulus nor Sonic were marking BGP community list as abstract.
> FRR: BGP community list is abstract structure

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
- projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddSourceConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Or.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
1. Add tracking for the number of allocated vs freed BDDs.
2. Add invariants to fixpoint.
3. Add utilities to make it easier to orAllAndFree/andAllAndFree.
4. Fix a leak in the Or transition.
> BDDFactory: add utilities to decrease garbage, use them

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
Use `andAllAndFree` to be more efficient and produce less garbage.
Do not defer computation.
> BDDOutgoingOriginalFlowFilterManager: improve computeOutgoingOriginalFlowFiltersConstraint

- projects/allinone/BUILD
- projects/allinone/pom.xml
- projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/BaseSettings.java
Useful when callers want to add their own settings.
> Settings: allow callers to provide Options

- projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesQuestion.java
- projects/question/src/test/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswererTest.java
And make tests e2e to catch such things.
> VRRP question: Fix virtual address filtering bug

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HmmRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RoutingProtocol.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/HmmRouteTest.java
- New NX-OS Host Mobility Manager (hmm_ route type
> Add HmmRoute to datamodel routes

- WORKSPACE
- maven_install.json
Enabled proper review of changed dependencies.
> rules_jvm_external: upgrade to latest, which sorts by coord

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
1. Fixes a bug in EIGRP
2. Moves common logic
3. Improves hash by including keys
> ibdp: redo messageQueueStream

- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
Traffic destined to a VIP should only be accepted by the load balancer if it is a ping.
> A10: Drop non-matching traffic to VIPs, except pings

- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
Reverts batfish/batfish#7937
This requires a nontrivial update to the chaos monkey notebook.
> Revert "Edges answerer: sort l3 edges"

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromAddress.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-address
This is a match on either src or destination IP addresses.
> JunOS: implement 'from address'

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_class_of_service.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/DscpUtil.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDscpTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/class-of-service-code-point-aliases
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-filter-dscp
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service
1. Definition of custom code-point aliases for DSCP under class-of-service
2. Using constants or custom/builtin aliases in firewall filters
> Junos firewall DSCP

- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/Breadcrumb.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
Only include ingressInterface in breadcrumb if it matters.
> FlowTracer: faster loop detection

- projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
- projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java
This reverts commit e314b0885795649a428ae706223abcb6238eca2f.
> Revert "Revert "Edges answerer: sort l3 edges" (#7938)"

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/hsrp/HsrpGroup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/hsrp/package-info.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/hsrp/HsrpGroupTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HsrpGroupMatchers.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
- projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java
- projects/question/src/test/java/org/batfish/question/interfaceproperties/InterfacePropertiesAnswererTest.java
- apply relevant fixes to VRRP model and implementation to HSRP
- stop using Identity collections
- only compete in same broadcast domain
- add sourceAddress to model
- remove redundant group number from model
Follow-on work: HSRP properties question
> Fix HSRP model and implementation

- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_slb_server.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_slb_service_group.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_slb_template.g4
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServiceGroup.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server-v2
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/service_group
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/slb_template_port
slb template port
extended-stats
more methods
ipv6 servers
etc.
> A10: handle more parsing in slb server and service-group

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceToRangeSetTest.java
convert (some) IpSpaces to equivalent RangeSets.
> IpSpaceToRangeSet

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/hsrp/HsrpGroup.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_hsrp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/hsrp
Lots of TODOs, but this moves in the right direction
> XR: partial conversion of HSRP

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrrpGroup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/PriorityEvaluatorTest.java
- factor out common bits of HSRP tracking
> Add VI VRRP priority tracking

- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- decrement priority when reachability fails, not when it succeeds
> A10 fix vrrp-a and ha check gateway semantics

- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_access_list.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4
- projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip_access_list.g4
- projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListAddressPrefix.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListAddressVisitor.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListAddressWildcard.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleToMatchExpr.java
- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
- projects/batfish/src/test/java/org/batfish/vendor/a10/representation/AccessListRuleToMatchExprTest.java
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/access_list
- projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/access_list_ref
Supports extended access lists such as:
```
access-list 100 permit ip host 1.1.1.1 any
```
> A10: Support extended access lists

- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/unit-tests.ref
> Revert "Revert "Junos: Check VRF when using lo0-based BGP local IP (#7961)""

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspBgpActivePeer.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
Plus, a little method renaming for clarity.
> IspModeling: Fix another place that assumes explicit local IP

- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- tests/parsing-tests/example-juniper.ref
- tests/parsing-tests/unit-tests.ref
> Revert "Revert "Revert "Revert "Junos: Check VRF when using lo0-based BGP local IP (#7961)""""

- projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/bdd/BDDTestCase.java
- projects/bdd/src/test/java/net/sf/javabdd/bdd/CallbackTest.java
- projects/bdd/src/test/java/net/sf/javabdd/bdd/IteratorTest.java
- Update javadoc
- Delete revision, we're not tracking it
- Delete reset, done, and callers
> BDD: cleanup some older code and comments

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
Standalone part of cleaning up some related APIs.
> AutoComplete utils: move test code

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
Exposes additional parallelism and granularity.
Additionally, shuffles the VRFs to hopefully balance asymmetric task sizes.
> ForwardingAnalysisImpl: parallelize across VRFs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
We do not need all unique networks, just all networks not
covered by a shorter network.
> ForwardingAnalysisImpl: simplify routable IPs

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
Neither the stream nor the copy is necessary.
> FibImpl: remove unnecessary overhead

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpaceLine.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceLineTest.java
In one medium-sized network, this reduced the number of distinct objects by
more than a factor of 10. (4.3M->330k)
> AclIpSpaceLine: intern

- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/BroadcastL3Adjacencies.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DeviceBroadcastDomain.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/Edges.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L2VNI.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L2VNIHub.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L2VniToVlan.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/L3AdjacencyComputerTest.java
For new L3 adjacencies algorithm, generate additional adjacencies based on VxLAN topology
Co-authored-by: Daniel Halperin <dan@intentionet.com>
Co-authored-by: Ari Fogel <ari@fogelti.me>
> L3AdjacencyComputer: add VxLAN

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-interface-all
Follows what was done in https://github.com/batfish/batfish/pull/7946 for ospf.
> Junos: Implement isis interface all

- projects/batfish/src/main/java/org/batfish/grammar/cisco_asa/AsaControlPlaneExtractor.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_asa/CiscoAsaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco_asa/testconfigs/asa-gh-8134
> ASA: handle next-hop interface routes

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/pre-defined-junos-applications
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/pre-defined-junos-applications-converted
> Junos apps: add rdp, imap, pop3

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddNoLastHopConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddOutgoingOriginalFlowFiltersConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddSourceConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Constraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/EraseAndSet.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Identity.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Or.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveLastHopConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveOutgoingInterfaceConstraints.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/RemoveSourceConstraint.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Reverse.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransitionVisitor.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Zero.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizerTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java
Adds visitor interface and makes a few constructors/getters public for later accessibility.
> Visitor interface for reachability graph Transitions

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NamedPort.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/pre-defined-junos-applications
Fixes https://github.com/batfish/batfish/issues/8128
> Junos: Add definition for junos-smtps

- projects/batfish-client/src/main/java/org/batfish/client/BfCoordWorkHelper.java
- projects/batfish-client/src/main/java/org/batfish/client/Client.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java
- projects/batfish/src/main/java/org/batfish/main/CoordinatorClient.java
> BatfishLogger: add `@FormatMethod` annotation

- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/Service.java
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/BUILD
- projects/batfish/src/test/java/org/batfish/representation/palo_alto/ServiceTest.java
* Add icmp type to `Service`
* Rename `Service` -> `MatchExpr` function
* Add tests
> PAN: add icmp type to Service

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bridge_domains.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomain.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanId.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdAll.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdNone.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdNumber.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdVoidVisitor.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bridge-domains
- tests/parsing-tests/unit-tests-undefined.ref
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
- parsing, some extraction and conversion
- set vlan and disable autostate on vlan of IRB in a bridge-domain
- some structure defs and refs
> Juniper partial handling of bridge-domains

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PrimedBDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPairingFactoryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/PrimedBDDIntegerTest.java
Introduce two new classes for encoding relations over BDDIntegers.
> BDDPairingFactory and PrimedBDDInteger

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDUtils.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDUtilsTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransitionVisitor.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java
A reachability graph transition that transforms a variable number of variables by applying a relation over those variables and their primes.
> New Transform reachability graph Transition using primed BDD variable encoding

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpType.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIpProtocol.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacketLength.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
Max value is 255
commit-id:63458a00
---
**Stack**:
- #8224
- #8223
- #8222 ⬅
> BDDRoute: admin dist is only 8 bits (unsigned)

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDDomain.java
> BDDInteger: don't box longs

- projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/profiles-reference
Don't add references for the special-case / keyword custom URL category `any`.
> PAN: handle `any` custom URL category

- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
These are reported by undefined references, BGP Session compat/status, etc.
commit-id:2017f3fd
> BGP: remove some unnecessary warnings

- .spr.yml
> batfish: check in default git spr configuration

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-vrfd-address-family-export-map
Fix batfish/batfish#8276 (cause is not visible there, but I have the data).
commit-id:9d604b44
- Fix batfish/batfish#8276
> IOS: fix lexing of export map lines

- projects/batfish/src/main/java/org/batfish/bgp/JsonExternalBgpAdvertisementPlugin.java
> JsonExternalBgpAdvertisementPlugin: use Jackson instead of Jettison

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPairingFactoryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/PrimedBDDIntegerTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
Rules to merge Constraint and Transform Transitions in either order.
> Transitions: mergeComposed rules for Transform 

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PrimedBDDInteger.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java
- projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java
> TransformationToTransition: use Transform transitions

- projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
> A10Conversion: expose isIpv4VirtualServer

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
Merge an Or composed with a Constraint by composing each disjunct with the Constraint. Limit to Ors with 10 or fewer disjuncts.
> Transitions: mergeComposed rule for Or . Constraint

- projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
- projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java
Rewrite PacketPolicyToBDD to create fewer BDD graph states (nodes) to allow more edges to be merged. The new strategy is to only create a new state when fanning in from multiple pre-states, or when we'd have to use a `Composite` transition otherwise.  The new `Transform` transition merges better than `EraseAndSet`, allowing us to merge more transitions without introducing `Composite` transitions. 
To facilitate this, `mergeComposed` now tries to merge `Or` followed by `Constraint` when the `Or` is small enough. It does this by composing each disjunct with the constraint.
> PacketPolicyToBDD: create fewer BDD graph states

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDOps.java
1. Optimize for blocks of lines with the same action, using orAll to union each block of lines.
2. Compute the result bottom-up, which removes the alreadyMatched variable (and the operations required to maintain it).
3. Free intermediate BDDs.
> Optimize BDDOps::bddAclLines

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
Merge a Constraint composed with an Or by composing the constraint with each disjunct. Limit to Ors with 10 or fewer disjuncts.
> Transitions: mergeComposed rule for Constraint . Or

- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
Now that we are cleaning and reusing cache entries, ite's abuse of applycache is not safe.
commit-id:3b05f809
> JFactory: switch ite to multiopcache

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPairingFactoryTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformationToTransitionTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
Merge Or . Transform and Transform . Or. This is important for port transformations, since we case split on whether the protocol has ports: if yes, do the transformation; if no, don't.
> mergeComposed: Or with Transform (either order)

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/BgpPeerGroup.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-bgp-peer-session-inheritance
Fixes https://github.com/batfish/batfish/issues/8275
> IOS: indirect inheritance for peer sessions

- projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
- projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteEngineImplContext.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
> Traceroute: reuse SourcesReferenedOnDevice across multiple traces

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-area-interface-all-crash
> JunOS: fix a crash when using ospf area interface all

- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_asa/AsaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
> Cisco-like: fix warning text

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibForward.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibNextVrf.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FibEntryTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FibForwardTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/PacketPolicyEvaluatorTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/IpsRoutedOutInterfacesFactoryTest.java
- projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
> FibAction: intern

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsSet.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibForward.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibNextVrf.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/StandardCommunity.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NodeInterfacePair.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopIp.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySet.java
commit-id:ed14d77a
---
**Stack**:
- #8341
- #8340
- #8339
- #8338 ⬅
> Re-intern cached objects on deserialization

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTest.java
commit-id:a4b22b63
---
**Stack**:
- #8341
- #8340
- #8339 ⬅
> Prefix: improve serialized form

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AnnotatedRoute.java
> AnnotatedRoute: make the hashCode transient

- projects/question/src/main/java/org/batfish/question/lpmroutes/LpmRoutesAnswerer.java
Prior implementation was relying on sorted maps; should actually
enforce the order as it is not part of the contract.
> LpmRoutesAnswerer: sort results

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
No functional changes, just clarification and cleanup.
> Document + minor refactor of getOutgoingRoutesForEdge

- projects/pom.xml
Close batfish/batfish#8384
commit-id:0d1dbc0f
- Close batfish/batfish#8384
> pom.xml: remove old kotlin dep

- projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
BDDSourceManager vs BDDFiniteDomain
commit-id:510c1633
---
**Stack**:
- #8386
- #8385 ⬅
> Transitions: rewrite code for clarity

- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
- prefer no path ID
- then prefer lowest path ID
> BGP bestpath compare path-id after receivedFrom

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathDuplicateTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathUniqueNextHopTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpBestPathExportTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
- tests/basic/genDp.ref
- tests/basic/routes.ref
This reverts commit 120b42a2e38fd9c91b8bf97a11755020cd17e8d0.
> Revert "BGP always use bestpath comparison between routes with same next hop (#8406)"

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
Profiling showed that queue containment and fetching were slow because
of SortedMap's log(n), comparison-heavy lookup. Switch to ImmutableMap
copying from SortedMap since the former preserves order but is hash-based.
commit-id:407ffa20
> OspfRoutingProcess: use ordered but not sorted maps for hot lookups

- projects/question/src/main/java/org/batfish/question/routes/EvpnRouteRowSecondaryKey.java
- projects/question/src/main/java/org/batfish/question/routes/RouteRowSecondaryKeyVisitor.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
Mostly copied existing BGP RIB logic.
> EVPN RIB differential question

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
Think we're beyond the point where this comment is useful or accurate.
> Clear add-path todo

- docs/README.md
- docs/dataplane-computation.md
- docs/parsing-and-conversion.md
- docs/question-development.md
- docs/topology.md
Introduce basic docs tree skeleton with no content.
> Docs tree skeleton

- .trivyignore
> .trivyignore: ignore mistune for now

- projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkResource.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/WorkResource.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/WorkResourceTest.java
- prep for adding V2 queueWork call
- Return 404 if requested network does not match network of requested workitem
- gives feature parity with V1 call
> Fix up WorkMgrV2 getWorkStatus call

- projects/coordinator/src/main/java/org/batfish/coordinator/resources/WorkResource.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/WorkResourceTest.java
- POST WorkItem to `/v2/networks/networkname/work`
- returns 201 with location `/v2/networks/networkname/work/workid`
> Add WorkMgrV2 call for queuing work

- projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/NetworkResource.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/WorkResource.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/WorkResourceTest.java
- GET `/v2/networks/networkname/work?type=worktype`
- GET `/v2/networks/networkname/snapshots/snapshotname/work?type=worktype`
- returns list of matching `WorkStatus`es
> Add WorkMgrV2 call for listing incomplete work

- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
- projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java
- projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java
- POST application/octet-stream to `/v2/networks/networkname/snapshots/snapshotname`
> Add WorkMgrV2 call for uploading a snapshot

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
- projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java
Fix batfish/batfish#8388
commit-id:c107d2f9
- Fix batfish/batfish#8388
> FortiOS: stop modeling ICMP6 as v4 protocol

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/TracingFactory.java
commit-id:d9f60d58
---
**Stack**:
- #8392
- #8469
- #8468 ⬅
> BDD: add notEq

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
Like ImmutableBDDInteger#getVars, but for TCP Flags.
---
**Stack**:
- #8392
- #8469 ⬅
> BDDPacket: add getTcpFlagsVars

- projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
- projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
> Add constant to control whether to start WorkMgrV1

- projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
- projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2TestBase.java
- move features used by `WorkMgrService{,V2}` to constant lists.
- reference constant lists when initializing `WorkMgrService{,V2}` and
test base
> Refactor resource features

- projects/batfish/pom.xml
> batfish/pom.xml: remove duplicate dependency declaration

- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_bgp.g4
- projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
Fix batfish/batfish#8471
- Fix batfish/batfish#8471
> FRR: parse and ignore bgp max-med on-startup

- projects/allinone/pom.xml
- projects/bdd/pom.xml
- projects/coordinator/pom.xml
- projects/pom.xml
commit-id:7bc19de6
---
**Stack**:
- #8480
- #8478 ⬅
> maven: upgrade plugin versions

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/applications/PortsApplication.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/packet_policy/PacketPolicyEvaluatorTest.java
- projects/checkstyle.xml
Use Guava's.
commit-id:30811b27
---
**Stack**:
- #8480
- #8481 ⬅
> parboiled.common.ImmutableList: don't use it

- .buildkite/jacoco_report.sh
- .buildkite/ref_test.sh
- projects/pom.xml
> jacoco: upgrade to 0.8.8

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDOps.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedOnDevice.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
- projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java
- projects/batfish/src/test/java/org/batfish/main/TestrigText.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/TracingFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java
- tools/benchmarks/BUILD
- tools/benchmarks/BenchmarkOrAll.java
- tools/benchmarks/SnapshotBddBenchmarks.java
- tools/stress_tests/BUILD
- tools/stress_tests/SnapshotBddStressTests.java
Added new benchmarks, notably some that use real data (building the reachability graph for an input snapshot, and converting all ACLs to BDDs). Did some simple optimizations based profiling on the ACL benchmark, resulting in a 1.5x speedup on one large network.
> BDD benchmarks, stress tests, and some simple optimizations

- projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java
- projects/coordinator/src/main/java/org/batfish/coordinator/Main.java
- projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
- add arg `-uselegacyworkmgrv1`
> Control WorkMgrV1 with coordinator arg instead of constant

- projects/coordinator/src/main/java/org/batfish/coordinator/config/Settings.java
- forgot to commit in batfish/batfish#8489
> Add missing cli arg for workmgrv1 cli option

- README.md
> README: remove ga-beacon

- .github/workflows/reusable-vulnerability-scan.yml
- .github/workflows/vulnerability-scan.yml
Add vulnerability scan workflow to check container vulnerabilities.
> CI: vulnerability scan workflow

- WORKSPACE
> rules_python: upgrade

- .pre-commit-config.yaml
> pre-commit: add buildifier

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/TraceAndReverseFlow.java
commit-id:86642ba4
---
**Stack**:
- #8515
- #8516
- #8514 ⬅
> TraceAndReverseFlow: remove unneeded specifier import

- projects/batfish-common-protocol/BUILD
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspBgpActivePeer.java
Fix dependence on checkArgument
commit-id:7abf8a7c
---
**Stack**:
- #8518
- #8517 ⬅
> common_lib: remove parboiled

- .github/workflows/pre-commit.yml
> gha: cache bazelisk downloads

- .github/workflows/pre-commit.yml
- tools/fix_java_format.sh
> gha: swap google-java-format off of Maven for downloading

- .github/workflows/pre-commit.yml
- tools/run_checkstyle.sh
> CI: swap checkstyle to simple jar-based version

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
- fix accidental non-determinism in batfish/batfish#8523
- iterate through config-specific warnings in config-specific hostname order instead of
`toVendorIndepentConfigurations()` result order
> Fix accidental non-determinism in batfish/batfish#8523

- .github/workflows/owasp-scan.yml
- tools/run_owasp.sh
> add OWASP workflow

- .github/workflows/owasp-scan.yml
- projects/build-tools/src/main/resources/org/batfish/owasp/suppressions.xml
> OWASP: suppress junit cves that don't apply to released artifacts

- projects/build-tools/src/main/resources/org/batfish/owasp/suppressions.xml
> OWASP: remove outdated suppressions

- tools/run_owasp.sh
**Stack**:
- #8532
- #8531
- #8530
- #8529 ⬅
> OWASP: overwrite any existing source release

- tools/run_owasp.sh
**Stack**:
- #8531
- #8532
- #8530 ⬅
> OWASP: allow overriding filename to scan

- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
> FileBasedStorage: readability cleanup

- docs/example_code/new_vendor/src/main/antlr4/org/batfish/grammar/cool_nos/CoolNosLexer.g4
- docs/example_code/new_vendor/src/main/antlr4/org/batfish/grammar/cool_nos/CoolNos_static_routes.g4
- docs/example_code/new_vendor/src/main/java/org/batfish/grammar/cool_nos/CoolNosConfigurationBuilder.java
- docs/example_code/new_vendor/src/main/java/org/batfish/vendor/cool_nos/StaticRoute.java
- docs/extraction/README.md
- docs/parsing/README.md
- update example code to justify some patterns
- flesh out section on multiple files -> one VendorConfiguration
- add section on writing ControlPlaneExtractor
> Add documentation on extraction

- docs/proposals/extensible_l3_adjacencies/README.md
- docs/proposals/extensible_l3_adjacencies/resources/broadcast_domain_discovery/README.md
- docs/proposals/extensible_l3_adjacencies/resources/l3_edge_establishment_and_relation_to_l1_l2/README.md
Add proposal for new l3 adjacencies algorithm and older resources
Co-authored-by: Ari Fogel <ari@fogelti.me>
Co-authored-by: Dan Halperin <dan@intentionet.com>
> Docs: proposal for new l3 adjacencies algorithm

- projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java
Reported by Ryan Harden on Batfish Slack.
commit-id:1a76e968
> JunosApplication: implement junos-telnet

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
> PTMM: remove an expensive stream

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/InterfaceNameComparator.java
InterfaceNameComparator does a ton of work to attempt to sort interface names
correctly. Caching that work improves performance by 4x-5x of some of the big
sorted structures.
> InterfaceNameComparator: cache expensive comparisons

- projects/batfish/src/main/java/org/batfish/bddreachability/BDDLoopDetectionAnalysis.java
- projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
- projects/batfish/src/test/java/org/batfish/bddreachability/BDDLoopDetectionAnalysisTest.java
Support searching for loops within a particular headerspace
> BDDLoopDetectionAnalysis: support header constraints per ingress location

- projects/batfish/src/test/java/BUILD
> batfish_tests: fix glob

- docs/parsing/README.md
> BUILD.bazel: one more doc

- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
And add tests
commit-id:1e5531bf
> BgpRib: sort communities in output

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
> ExtendedCommunity: add missing tests and fix bug

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchExprEvaluator.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchExprVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/HasSize.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchExprEvaluatorTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/HasSizeTest.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCommunityCount.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromCommunityCountTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDD.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/CommunitySetMatchExprVarCollector.java
To implement this, I had to add a CommunitySetMatchExpr to match against
CommunitySet size.
commit-id:1728e706
---
**Stack**:
- #8603
- #8602 ⬅
> VI,JunOS: add support for from community-count

- WORKSPACE
> WORKSPACE: upgrade libraries

- docs/parsing/README.md
Adds _null and a pattern to avoid.
> Docs: Update parser documentation

- projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/Gh8588AdvertiseInactiveTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/bgp_advertise_inactive
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testrigs/gh_8588_advertise_inactive/configs/s0.cfg
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testrigs/gh_8588_advertise_inactive/configs/s1.cfg
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testrigs/gh_8588_advertise_inactive/configs/s2.cfg
- projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testrigs/gh_8588_advertise_inactive/hosts/d1.json
> FRR set advertise-inactive for IPv4 sessions

- projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
- projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java
And add test
---
**Stack**:
- #8652
- #8651
- #8650
- #8649 ⬅
> TestRoutePolicies: fix invalid assertion

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathMatchRegex.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/MatchAsPath.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExpr.java
**Stack**:
- #8652
- #8651
- #8650 ⬅
> BooleanExpr: fix some toString functions

- projects/minesweeper/src/main/java/org/batfish/minesweeper/RegexAtomicPredicates.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/AsPathRegexAtomicPredicatesTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/RegexAtomicPredicatesTest.java
Optimizes the creation of atomic predicates for the symbolic route analysis by reducing the number of calls to the Automaton library, which can be slow for large/complex automata.
> TransferBDD: More efficient AP creation

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
This becomes an error in newer JDKs
> Juniper: remove recursive modification during screens

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
And fix a bunch of things that became obvious as a result.
> RibDelta: reduce unnecessary use of streams

- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/ExpandedCommunityListLine.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_community_list_421
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_community_list_423
Fix batfish/batfish#8693
commit-id:4207c69f
> Arista: reject and warn on invalid expanded community-list regexes

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetMetric.java
commit-id:732194b1
---
**Stack**:
- #8711
- #8710
- #8709 ⬅
> SetMetric: fix toString

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralLong.java
> LiteralLong: implement toString

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfInterfaceSettingsTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
Adds the ability to filter type 5 OSPF LSAs.
> Add ospf type 5 filtering

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_asa/AsaLegacy_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_asa/AsaLexer.g4
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpVrf.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
- projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_reflection
- tests/aws/vimodel-example-aws.ref
- tests/basic/outliers-verbose.ref
- tests/basic/viModel.ref
Finish implementation for Arista and NX-OS
Fix NX-OS default
> IBGP: support disabling client-to-client reflection

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-nat-pat
New syntax variant seen in configs from Burak Yavuz on Slack.
> Junos: allow prefix with port variant

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleMatchProtocol.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleMatchToHeaderSpace.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/NatRuleMatchVisitor.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/ReverseStaticNat.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nat-dest
New syntax variant seen in configs from Burak Yavuz on Slack.
> Junos: match protocol in nat rule-set rules

- projects/coordinator/src/main/java/org/batfish/coordinator/ApiKeyAuthenticationFilter.java
- projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java
> Allow access to version info without an API key

- projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
- projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java
If an active peer does not have a configured local IP, use it (on both sides
of the session) in the answer when the session is established.
---
**Stack**:
- #8784
- #8783 ⬅
> BgpSessionStatusAnswerer: fill in values for established sessions

- projects/checkstyle.xml
> checkstyle: partial enforcement of nullity annotations on types

- tools/bazel_run.sh
> bazel_run.sh: add -d flag for debugging, including assertions

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRouteDiff.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
Adds support for SetAdminCost in TransferBDD/SRP/CRP.
> Add SetAdminCost support to SRP/CRP.

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
SetOrigin is already implemented, removing some dead code.
> Minor refactoring in SRP removing some dead code.

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_snmp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/snmp
Added to existing config snippet and relying on existing tests.
> Add SNMP v3 configuration to the null filler to silence parser warnings

- projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
- projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
* already done for communities
> Sort cluster list in bgp rib answer output for determinism

- docs/building_and_running/README.md
> Remove instruction to install Xcode

- tools/bazel_run.sh
- tools/log4j2.yaml
Contains useful logs, rather than silence.
---
**Stack**:
- #8868
- #8867 ⬅
> tools/bazel_run.sh: add log4j2.yaml

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
We stopped serializing RIBs a while back
> GenericRibReadOnly: remove Serializable

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
hard to type NAT DESTINATION I guess.
> Junos: fix usage name

- WORKSPACE
**Stack**:
- #8902
- #8901
- #8900
- #8899 ⬅
> rules_python: upgrade to 0.27.1

- WORKSPACE
**Stack**:
- #8902
- #8901
- #8900 ⬅
> bazel_skylib: upgrade to 1.5.0

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
**Stack**:
- #8907
- #8906
- #8905 ⬅
> IBDP: do less work by directly computing size

- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
Don't need to sort all routes, just to know the best one.
---
**Stack**:
- #8907
- #8906 ⬅
> BgpRib: optimize multipath bestpaths

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bmp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
No functional change, just readability / maintainability
> Junos: factor out routing-options bmp to its own file

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
- projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java
This helps users in understanding dataplane convergence behavior.
> Dataplane: log which parts of the dataplane changed across topology iterations

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-filters
Add parsing and `todo` for firewall `ipv4` filter commands.
> Junos: Add parsing for firewall ipv4 filter commands

- tools/fix_java_format.sh
**Stack**:
- #8919
- #8918
- #8917
- #8916
- #8915
- #8914 ⬅
> fix_java_format: upgrade to latest

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPath.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-as-path-exclamation-regex
Added special cased support for the as-path regex !.*
> Junos: support as-path-group as-path regex `!.*`

- .github/workflows/bazel-steward.yml
This reverts commit 3c7b38b30bcb0a78bb41b18794262dd2cbdd184c.
> Reapply "bazel-steward: try adding (#8890)"

- .bazel-steward.yaml
This reverts commit 3c7b38b30bcb0a78bb41b18794262dd2cbdd184c.
> Reapply "bazel-steward: try adding (#8890)" (#8929)

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/HierarchyTest.java
Many fewer regex compilations.
> Junos: slightly more efficient wildcard matching

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
`BDD saneBDD = bdd.and(getSaneFlowConstraint());`
compute saneBDD twice
> duplicate: bdd.and() the same bdd

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
- projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
- projects/client/src/main/java/org/batfish/client/Client.java
**Stack**:
- #8942
- #8941
- #8940 ⬅
> FileBasedStorage: create temp files in the output directory

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java
- projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java
> WorkMgr: inline utility to create temp directory

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteCommunityDiff.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffs.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteCommunityDiffTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffsTest.java
Mostly sending this CR for educational purposes.
> CompareRoutePolicies: minor Java improvements

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
This makes a big difference (minutes to tends of seconds) for large files with very large apply groups.
> Hierarchy: optimize apply-groups application by tracking separate types

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix6.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixIp6SpaceTest.java
Remove all the BatfishException nonsense and just use
IllegalArgumentException. Add tests.
> Prefix6: fix tryParse

- projects/batfish/src/main/java/org/batfish/main/Batfish.java
Don't log for nothing to report.
> ConversionContext: less spammy logs

- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
Setup/teardown overheard is too much.
> BgpRib: remove a wasteful stream

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
We only use this if add-path is on, so let's save that RAM and CPU if not used.
> BgpRoutingProcess: optimize away full RIB copy when add-path is not on

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
**Stack**:
- #9032
- #9031
- #9030 ⬅
> GeneratedRoutes: skip materializing the unannotated routes set

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
**Stack**:
- #9032
- #9031 ⬅
- #9030
> BgpProtocolHelper: stop using Ip.AUTO, just use NextHop directly

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BgpPeerAddressNextHop.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DiscardNextHop.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/UnchangedNextHop.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/BgpPeerAddressNextHopTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/DiscardNextHopTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/SelfNextHopTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/UnchangedNextHopTest.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
- projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
- projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
**Stack**:
- #9032 ⬅
- #9031
- #9030
> NextHops: actually be singletons

- projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java
- projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/EvpnMasterRibTest.java
TypedRoutes -> Routes
---
**Stack**:
- #9034
- #9033 ⬅
> Rib: a few missed renamings

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
Save array creation.
Also, put the highest entropy part in the most significant bit.
---
**Stack**:
- #9037
- #9036
- #9035 ⬅
> ExtendedCommunity: inline hashCode

- projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
- projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
> BgpRib: ensure removed backup routes are removed from arrival time

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/HasSize.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/IntComparison.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/IntMatchAll.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralInt.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralTunnelEncapsulationAttribute.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/VarInt.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetTunnelEncapsulationAttribute.java
> SetTunnelEncapsulationAttribute: add toString

- .github/workflows/pre-commit.yml
This is clearly not useful, but trying to get towards java17
> github: try matrix pre-commits

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java
> ModelGeneration: improve logging on failure

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
commit-id:0676131f
---
**Stack**:
- #9075
- #9074 ⬅
> TransferBDD: nit optimization

- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
Implements the described optimization, with very little overhead.
---
**Stack**:
- #9089
- #9088
- #9087
- #9086 ⬅
> CompareRoutePolicies: optimize iteration when routes are similar

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
No functional changes intended; just making the control flow cleaner with helper methods.
---
**Stack**:
- #9089
- #9088 ⬅
> CompareRoutePoliciesUtils: refactoring for clarity

- projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/AsPathRegex.java
**Stack**:
- #9106
- #9105
- #9104 ⬅
> Junos parboiled: continue improving debuggability

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/CommunityVar.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/OspfType.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
We do not attribute authorship to individual files.
https://github.com/batfish/batfish/graphs/contributors has the data.
> minesweeper: cleanup Javadoc

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchAny.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetMatchExprReference.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/InputCommunities.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/MatchCommunities.java
Makes debugging and analyzing easier.
> Communities: more printable exprs

- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCommunity.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromCommunityTest.java
commit-id:cc98197d
---
**Stack**:
- #9134
- #9133
- #9132 ⬅
> Junos: improve PsFromCommunity conversion

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java
> CommunityAPDispositions: more efficient use of IntegerSpace

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java
> SetCommunitiesVisitor: use static method via class, not instance, reference

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
Steal the logic from IpAccessListToBdd that combines lines with the same action. This results
in many fewer BDD operations.
---
**Stack**:
- #9143
- #9142
- #9141
- #9140
- #9139
- #9138
- #9136 ⬅
> TransferBDD: optimize matchFilterList

- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPrefixTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/comparepeergrouppolicies/ComparePeerGroupPoliciesAnswererTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
Show the easier path.
---
**Stack**:
- #9143
- #9142
- #9141
- #9140
- #9139
- #9138 ⬅
> PrefixRange: streamline construction in tests

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
**Stack**:
- #9143
- #9142
- #9141
- #9140
- #9139 ⬅
> TransferBDD: more efficient conversion for PrefixSets

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDDState.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferParam.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDStateTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferParamTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferResultTest.java
**Stack**:
- #9143
- #9142
- #9141
- #9140 ⬅
- #9139
> TransferResult,TransferParam,TransferBDDState: equals and testing

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java
Basically, a copy of addClipping.
---
**Stack**:
- #9143
- #9142
- #9141 ⬅
> MutableBDDInteger: add subClipping function

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
**Stack**:
- #9143
- #9142 ⬅
- #9141
> TransferBDD: implement Increment/Decrement Metric/LocalPreference

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDDTest.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
Add a test for the subtle corner case that breaks in some incorrect optimizations.
---
**Stack**:
- #9143 ⬅
- #9142
- #9141
> CommunitySetMatchExprToBDDTest: add a test of CommunityNot

- projects/minesweeper/BUILD.bazel
- projects/minesweeper/src/main/java/org/batfish/minesweeper/BUILD.bazel
Enable finer granularity so it's easier to develop and test modules
> minesweeper: minor future-proofing bazel refactor

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
**Stack**:
- #9148
- #9147
- #9146 ⬅
> TransferBDD: a few frees

- projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
- projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
> TransferBDD: optionally combine paths with equal results on the fly

- projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java
**Stack**:
- #9156
- #9159
- #9155
- #9154 ⬅
> Junos: convert as-path-length

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/HasAsPathLength.java
**Stack**:
- #9156
- #9159
- #9155 ⬅
> HasAsPathLength: add toString

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
Also fix and test the size of tag to u32 as it is in from_tag and then_tag.
---
**Stack**:
- #9184
- #9180
- #9179
- #9178 ⬅
> Junos: extraction and todo for static route tag2

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
**Stack**:
- #9184
- #9180
- #9179 ⬅
> Junos: add support for positive versions of no-install and no-advertise

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
> Junos: fles out rest of static route grammar with todos

- projects/batfish/src/main/java/org/batfish/representation/juniper/RegexCommunityMember.java
It's expensive, and there's usually relatively few regexes per snapshot that
are used all over the place.
> Junos: cache risky community regexes

- projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
1. Using `firstNonNull` forced us to run all of them every time
2. Small regex optimizations
> VendorConfigurationFormatDetector: minor optimizations

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-output-queue-priority
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-validation
**Stack**:
- #9197
- #9196
- #9195
- #9194 ⬅
> Junos: parse and todo bgp-output-queue-priority

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-then
**Stack**:
- #9197
- #9196
- #9195 ⬅
> Junos: parse and todo then tag2

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-bgp-add-path
> Junos: parsing inet6 unicast add-path

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-mpls
**Stack**:
- #9203
- #9202
- #9201
- #9200 ⬅
> Junos: parse some MPLS-related configuration

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-vpn
**Stack**:
- #9203
- #9202
- #9201 ⬅
> Junos: some vpn-related parsing

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-misc
> Junos: some misc top-level BGP config

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
**Stack**:
- #9212
- #9211
- #9210
- #9209
- #9208
- #9207
- #9206 ⬅
> Junos: implement from next-hop

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
**Stack**:
- #9212
- #9211
- #9210
- #9209
- #9208
- #9207 ⬅
- #9206
> Junos: extract route conditions for IPv6 prefixes

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ipsec-vpn
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-security-misc
**Stack**:
- #9212
- #9211
- #9210
- #9209 ⬅
- #9208
- #9207
- #9206
> Junos: add misc security parsing

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ipsec-vpn
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-security-misc
**Stack**:
- #9212
- #9211
- #9210 ⬅
- #9209
- #9208
- #9207
- #9206
> Junos: misc IPsec parsing

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-filter-from-port
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ipsec-vpn
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-security-misc
**Stack**:
- #9212
- #9211 ⬅
- #9210
- #9209
- #9208
- #9207
- #9206
> Junos: firewall term (source|destination)-port-range-optimize

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/IfRouteExists.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNextHop.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/BUILD.bazel
- projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromNextHopTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-filter-from-port
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ipsec-vpn
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-bgp-bmp
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-security-misc
**Stack**:
- #9212 ⬅
- #9211
- #9210
- #9209
- #9208
- #9207
- #9206
> Junos: misc bgp bmp

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/dataplane/rib/RibGroup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralLong.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/dataplane/rib/RibGroupTest.java
> LiteralLong: cleanup expr

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
Causes problems upgrading to latest jackson
> AbstractRoute: delete an unnecessary JsonCreator

- .github/workflows/pre-commit.yml
> pre-commit: save yaml changes

- .github/workflows/pre-commit.yml
> try fixing get-date

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-intervals
**Stack**:
- #9240
- #9239
- #9238
- #9237 ⬅
> Junos: add retransmit-interval and fix ranges for hello- and dead-interval

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper_fti
**Stack**:
- #9240
- #9239
- #9238 ⬅
> Junos: flesh out more tunnel grammar, specifically destination-udp-port

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6Wildcard.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix6.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AbstractIp6SpaceContainsIpTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6Test.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixIp6SpaceTest.java
- projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/Ipv6BgpPeerGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/Ipv6BgpPeerGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv6BgpPeerGroup.java
Now that we're starting to get a bit into IPv6, time to start SLOWLY bringing
in all the great work we did for V4 in .. 2017?
---
**Stack**:
- #9248
- #9247
- #9246
- #9245 ⬅
> Ip6,Prefix6: add caching

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
> Ip6: delete unused getAddressBits and the scary (unbounded) cache it has

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
Convert to true false, and use AclLineMatchExprs to future proof some
improvements and decouple fields.
> Fortios: improved conversions

- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
- projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
**Stack**:
- #9284
- #9283
- #9282 ⬅
> Header/ACL to BDD: cache conversions

- projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
It can be very expensive.
---
**Stack**:
- #9284
- #9283 ⬅
> finalizeConfiguration: only verify ACL invariants for developers/when assertions enabled

- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java
- projects/batfish/src/main/java/org/batfish/representation/arista/Conversions.java
- projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/IcmpTypeObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/ProtocolObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/ServiceObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConversions.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/IcmpTypeObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/ProtocolObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_asa/ServiceObjectGroup.java
- projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSet.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/BaseApplication.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/HostProtocol.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/HostSystemService.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
- projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco_asa/CiscoAsaGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/ApplicationSetTest.java
- projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
> AclLineMatchExprs: use and/or helpers more

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_mpls.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/LogicalSystem.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/Srlg.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/junos-srlg
> Junos: parse, extract, reference srlgs

- projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java
make sure they work with our CI
> Demo of java17 block strings

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
https://datatracker.ietf.org/doc/html/rfc8097.html#section-2
> ExtendedCommunity: add BGP RPKI well-known extended communities

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
- projects/batfish/src/main/java/org/batfish/representation/aws/NatGateway.java
**Stack**:
- #9316
- #9315
- #9314 ⬅
> NGW: streamline AclLineMatchExprs

- projects/batfish/src/main/java/org/batfish/allinone/bdd/main/ReplayBDDTrace.java
- projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
- projects/bdd/src/main/java/net/sf/javabdd/TracingFactory.java
> Revert "JFactory: increase cache unit size"

- projects/bdd/src/main/java/net/sf/javabdd/BDD.java
- projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
- projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java
Shortcut for isZero() or isOne().
> BDD: add isConstant

- docs/building_and_running/README.md
Build docs were stale, we updated to JDK 17.
Fixes #9350
> Update build docs to point to java 17

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
Co-authored-by: SirasornT <SirasornT@users.noreply.github.com>
---
**Stack**:
- #9363 ⬅
- #9362
> ExtendedCommunity: add support for encapsulation communities

- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- tests/parsing-tests/unit-tests-warnings.ref
- tests/parsing-tests/unit-tests.ref
> Junos: flesh out policy-statement from <> extraction with todos

- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExprVisitor.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchPeerAddress.java
- projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromNeighbor.java
- projects/batfish/src/main/java/org/batfish/representation/juniper/PsFroms.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-policy-from-neighbor
- projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java
- projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java
Stop treating the construct as unsupported
Add VI expr and conversion
> Junos: support from neighbor in import policy

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_mpls.g4
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/JunosMplsLspTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/mpls-lsp-comprehensive
Implemented grammar rules for Junos MPLS Label-Switched Path (LSP) configuration.
> Junos: improved MPLS LSP grammar

- projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DiffieHellmanGroup.java
- projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPhase2Policy.java
- projects/batfish-common-protocol/src/test/java/org/batfish/common/util/IpsecUtilMultipleKeyGroupsTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IpsecPhase2PolicyTest.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPhase2PolicyMatchers.java
- projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPhase2PolicyMatchersImpl.java
- projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
- projects/batfish/src/test/java/org/batfish/grammar/aws/AwsHostTest.java
- projects/batfish/src/test/java/org/batfish/grammar/aws/AwsIpsecTest.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
- tests/aws/vimodel-example-aws.ref
Doing the VI negotiation seems like a better UX to me.
> IPsec: add multiple DH groups in phase 2, switch back to 1 session for AWS

- projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_mpls.g4
- projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-mpls
> Junos: add missing apply for protocols mpls

- .roo/rules-mode-updater/01-rules.md
- .roo/rules-orchestrator/01-main.md
- .roo/rules/git-command-execution.md
- .roomodes
1. Add mode edit file restrictions
2. Refine orchestrator docs
3. Refine orchestrator git reference
commit-id:46253e37
---
**Stack**:
- #9433
- #9432 ⬅
> .roo: add ModeUpdater and start implementing its recommendations

- .roo/rules-mode-updater/01-rules.md
- .roo/rules-orchestrator/01-main.md
- .roo/rules/git-command-execution.md
- .roomodes
- docs/parsing/README.md
- docs/parsing/parser_rule_conventions.md
> parsing: improve docs on how we name parser rules

- docs/parsing/parser_rule_conventions.md
> parsing: improve docs on single-token rules

- projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
- projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
Follow up to batfish/batfish#9445
> FortiOS: add bandwidth conversion and tests

- .roomodes
Will be easier for maintenance
> Convert .roomodes to yaml format

- .roomodes
> .roomodes: fix icons

- projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4
- projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/IcmpServiceObjectGroupLine.java
- projects/batfish/src/main/java/org/batfish/representation/cisco/IcmpTypeObjectGroup.java
- projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
- projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-object-group-service
> IOS: add some more specific ICMP features for use in object-group service

- BUILD.bazel
> buildifier: ignore new .bazelbsp folder

- docs/example_code/new_vendor/src/main/antlr4/org/batfish/grammar/cool_nos/BUILD.bazel
- projects/batfish-common-protocol/src/test/antlr4/org/batfish/grammar/recovery/BUILD.bazel
- projects/batfish-common-protocol/src/test/antlr4/org/batfish/grammar/recovery_inline_alts/BUILD.bazel
- projects/batfish-common-protocol/src/test/antlr4/org/batfish/grammar/recovery_rule_alts/BUILD.bazel
Converted 3 test grammars and 1 example grammar that were missed in
the initial refactoring.
> Convert remaining ANTLR grammars to use antlr_grammar rule
