batfish/batfish

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java

Rather than putting all intra-area routes into the inter-area RIB and then not
sending them if they are summarized, just don't put them in the inter-area RIB
in the first place.

OspfRoutingProcess: filter summarized routes earlier

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfAreaSummary.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/OspfAreaSummaryMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfAreaSummaryTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_asa/AsaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
tests/parsing-tests/unit-tests-vimodel.ref

Since the summary isn't advertised, there's no need to install this discard route to
prevent a loop that can't happen.

OSPF: not-advertised summaries do not install a discard route

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
tests/basic/viModel.ref
tests/parsing-tests/unit-tests-vimodel.ref

Also modify the BgpProtocolHelper to preserve this routing type.

IOS: BGP aggregates have origin type IGP

---

projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java

Add clarifying comment about zone-interface specification mismatch with device behavior.

FortiOS: interface extraction clarifying comment

---

projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface_warn
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/rename
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone_warn

Handle (prevent) conflicting names between interfaces and zones.

FortiOS: handle zone-interface name conflicts

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/CommunitySetMatchExprVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/CommunitySetMatchExprVarCollectorTest.java

Instead, defer that crashing to validation time. This enables SearchRoutePolicies to
run on devices where only some of the route policies can be successfully analyzed.

CommunitySetMatchExprVarCollector: do not crash on collecting unsupported structures

---

projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4
projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy_warn
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_vi_policy
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/policy
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/policy_defs_refs

Policy action uses `accept` not `allow` (unlike intrazone action, which does use `allow`)

FortiOS: fix policy action

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/CommunityVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/CommunityVarCollectorTest.java

It's easy to collect communities from a conjunction, it's just all the communities.

CommunityVarCollector: support LiteralCommunityConjunction

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/parsing/AristaBaseLexer.java

None of the places that RULE were used are valid in EOS. Delete the `_enableRegex` predicate.

Arista: delete RULE (mainly, voice stanzas)

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/IpAsPathAccessListLine.java
projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConversionsTest.java
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref

When converting IOS community-set regexes to the VI model, if a regex only requires that some community matching a particular format exists, then we represent it as a community regex rather than a community-set regex.  Community regexes have a simpler semantics, and some questions (e.g., SearchRoutePolicies) don't handle community-set regexes.

IOS: Use regexes on individual communities where possible

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java

This ensure that the ErrorNodes make it as warnings to the output.

JunOS: retain error nodes after preprocessing insert/delete/etc

---

questions/stable/bgpRib.json
questions/stable/evpnRib.json
tests/questions/stable/bgpRib.ref
tests/questions/stable/commands
tests/questions/stable/evpnRib.ref

Specialize the routes question for BGP and EVPN ribs. The questions have different columns in the answer tables, which are otherwise not visible in the documentation and left users wondering how they get BGP-specific fields.

Specialize bgp and evpn rib questions

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ResolutionRestriction.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Resolution.java
projects/batfish/src/main/java/org/batfish/representation/juniper/ResolutionRib.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-resolution
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
projects/question/src/main/java/org/batfish/question/lpmroutes/LpmRoutesAnswerer.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

- iBDP implement resolution policy
- distinguish between recursive and non-recursive static routes
- use resolution policy to filter which routes can be used to resolve
next hops, activate static routes
- Juniper implement `static route resolve` and `resolution rib import`

Implement recursive static routes and resolution policy

---

projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/fortios/Addrgrp.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/address_warnings

In some situations, address types cannot be changed.
This is likely an uncommon occurrence, but add a warning if it is possible this has occurred.

FortiOS: addr type warning

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureType.java
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

It's never referenced, so always shows as unused.

NX-OS: stop defining OSPF area

---

projects/batfish/src/main/java/org/batfish/representation/juniper/NatPacketLocation.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Zone.java
projects/batfish/src/test/java/org/batfish/representation/juniper/NatPacketLocationTest.java

Some misconfigured NAT rules can be missing fromLocation or toLocation. Fix comparator not to
crash in these cases, improve annotations.

JunOS: robustness to misconfigured NAT rules

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java

Interface priority changing during dataplane run doesn't happen in our model.

NX-OS: stop warning on hsrp priority forwarding-threshold

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVarCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/SetCommunitiesVarCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Updates the `TransferBDD` symbolic route analysis to identify `SetCommunities` expressions that are simply community deletions or additions, and treats them as such.  Previously they were not being handled properly, because the `InputCommunities` expression is not currently being modeled symbolically.

TransferBDD: Handle community deletion/addition properly

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_properties

NX-OS accepts a vlan ID, though it is ignored.

NX-OS: no switchport access vlan optional id

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/SetCommunitiesVarCollectorTest.java

Identifies expressions of the form (InputCommunities - E), which is common in the translation of config commands to set communities, and ignores them rather than crashing.

TransferBDD: Avoid crashing on common idioms for setting communities

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests.ref

Also fixup a very small number of getLine mixups.

JunOS: routing-instance should never be unused

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RoutingProtocol.java
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/fortios/BgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/fortios/BgpProcess.java
projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java
projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp_conversion_warnings
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp_invalid_as
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp_no_as
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp_no_router_id

For now, the conversion process is fairly limited. It:
- Requires BGP router-id to be set (otherwise no BGP will convert)
- Ignores filtering (route-maps) and redistribution
- Will attempt to infer neighbors' update sources if not explicitly configured by finding an interface whose address includes the neighbor ID

FortiOS: Convert bgp

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java

- if a static route matches its own next-hop, a matching route must be
more specific

fix static route activation condition

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java

We warn at parent context, no need to warn for inner children.

NX-OS: don't double warn for track

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java

> Integer community values must be split in half and expressed as two unsigned
> decimal integers in the range from 0 to 65535, separated by a colon. Single
> 32-bit community values are not allowed.
https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/configuration/guide/rc40xr12k_chapter7.html#con_1115490

IOS-XR: remove u32 alternative for community-set

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclTracerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/BUILD
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoTraceElementCreators.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java

Tracing does not make sense through Not, since the subtracers are not
aware that they have been negated. While we work out a better solution,
discard the child subtraces unconditionally.
Traces on the NotMatchExpr itself are still preserved.
Minor updates to the Palo Alto modeling for filters as a result.

AclTracer: do not include subtraces for NotMatchExpr

---

projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java

Setting AS to 0 is the standard way to disable BGP in FortiOS (and it is set to 0 by default, so `show full-configuration` will often show `set as 0`).

FortiOS: Remove warning for BGP AS 0

---

projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_route_map.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/service_custom

Does not extract unset, but saves the parser from losing context.

FortiOS: Anticipate unset lines in route-maps, services

---

projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_address.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_addrgrp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_static.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_system.g4
projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java

Make main FortiOS grammar rules generally follow the pattern where rules ending in `_set`,  `_config`, `_rename` etc correspond to rules that start with the token `SET`,  `CONFIG`, `RENAME`
Also, inline a bit less.
No functional changes in this PR.

FortiOS grammar: make rules more consistent

---

projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/fortios_UPPER_hostname

Like we do for other vendors, save a lowercase version of hostname to the vendor configuration for FortiOS.

FortiOS: canonicalize hostname

---

projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/fortios/Address.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/address
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/address_warnings

Under `address` objects, `associated-interface` can also point to zones. This PR adds support for that.

FortiOS: support address associated zones

---

projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java

Not clear that this is correct, but there's at least evidence that outgoing traffic shouldn't be unconditionally denied.

FortiOS: Default permit outgoing originated traffic

---

projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_firewall.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_system.g4
projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/fortios_ignored

And ignore a few places.
Also fix modes in existing config system replacemsg.
The way this mode works is that it recursively ignores
all single lines (set and unset for now), and nested edit or config
blocks.
It emites all of the ignored text in the final END token.
It needs enhancement for multiline strings, so we can't yet handle
things like VPN certificates in here. It also also in general be less sloppy
about edit strings as well. But it gets us going for now.

FortiOS: add lexer for entirely ignored configuration blocks

---

projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors_no_v4

Otherwise the attached config throws an NPE while processing neighbor 10.0.0.32.
[spine01.txt](https://github.com/batfish/batfish/files/6293034/spine01.txt)

Arista BGP neighbor: Check null before using the address family variable

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java

- extended community is transitive when second-highest-order type bit is
UNSET, not when it is set
- see https://tools.ietf.org/html/rfc4360 Page 3

extended communitities fix transitive check

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/Trace.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/TracePrunerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/BidirectionalTracePrunerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/TraceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererTest.java

Iterables.getLast is an iteration, but since we have a list we can just get
the index.
Notice this only affects development runs or runs with `-ea` set.

Trace: improve performance in sanity checks

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ignored.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-bgp

- warn on `router bgp vrf rd`
- ignore `router bgp vrf address-family ipv4 label mode`
- add parsing test

IOS-XR various BGP parsing

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/DagTraceRecorder.java

They are never used in order, and they have containment checked often.

DagTraceRecorder: use sets instead of lists for breadcrumbs

---

projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java

Under ECMP, the same breadcrumb may be generated many times. TraceDAG
compressions makes the redundancy less, but interning Breadcrumbs is still
faster and uses less RAM.
We only intern at the FlowTracer level, so that the reference dies after the
traces are completed.

FlowTracer: intern Breadcrumbs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FlowToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/FlowToBDDTest.java

At some earlier time, the packet length field was not modeled in BDD. When
we added it, we forgot to update this class.

FlowToBDD: include Packet Length in modeling

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/aws/VpnConnection.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java

Semantics change is only for active peers. 
Real-networks and labs pass with this change.

Map null remote AS to EMPTY, not ALL

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_nclu/CumulusNcluConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatvyos/FlatVyosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/mrv/MrvControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java

- Make final-stage xxxExtractor / xxxConfigurationBuilder
consistently implement BatfishListener
- remove duplicate code
- prerequisite for planned warning functionality

Make extractors consistently implement BatfishListener

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_vrf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/AddressFamilyType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Vrf.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/VrfAddressFamily.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-vrf-route-policy
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-vrf-route-target

- create VrfAddressFamily for address-family-specific information
- move route-target import/export configuration under VrfAddressFamily
- update vrf address-family parsing

IOS-XR extract and refactor af-specific vrf configuration

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MemoizedIpSpaceToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BUILD
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MemoizedIpSpaceToBDDTest.java

Complex IpSpace objects (Acl, IpWildcardSet) have an expensive equals method,
which can cause problems for memoization: we have seen cases where converting
ForwardingAnalysis into BDDs took 10s pre-caching, and then a (cloned via
serialization) copy of the same objects took nearly 15m.
However, avoiding memoizing IpSpace -> BDD conversions altogether also causes
performance problems.
Instead, cache IpSpace objects with identity equality, so that multiple
conversions of the same object are remembered, but different equal objects are
converted redundantly.
Note that most IpSpace types are interned, so that `a != b` should imply
`!a.equals(b)` anyway.

MemoizedIpSpaceToBDD: use identity equality for IpSpace equality

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyPrependAsPath.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicySetIsisMetricType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicySetOspfMetricType.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicySetVarMetricType.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/route-policy-implicit-actions
tests/parsing-tests/unit-tests-vimodel.ref

Routes that are modified in route-policies are treated as default-pass instead of default-drop. From [Cisco docs](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/configuration/guide/rc40xr12k_chapter7.html#con_1118699):
> Default Drop Disposition
> All route policies have a default action to drop the route under evaluation unless the route has been modified by a policy action or explicitly passed. Applied (nested) policies implement this disposition as though the applied policy were pasted into the point where it is applied.

IOS XR: update route-policy default action

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java

This should not have any e2e functional changes, but it sure makes the output
easier to understand. It also makes the intersection operation never produce an
empty intersection, since two closedOpen ranges cannot produce one.

InterfacesByVlanRange: canonicalize on the way in

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrfLeakingConfig.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfLeakingConfigTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java

- do not adjust admin distance nor weight for leaked BGP routes

Support setting admin/weight for bgp-vrf-leaked IGP routes

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

cc: @chiragvyas50
Lab tests found that this route-map would permit all routes:
```
route-map RM permit 10
match ip address prefix-list UNDEFINED
```
Batfish's behavior in this situation was for the route-map to match nothing, and thus default deny all routes.

NXOS route-map: match undefined prefix-list matches all

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/resolution_policy
tests/parsing-tests/unit-tests-vimodel.ref

Similar to https://github.com/batfish/batfish/issues/6785, NXOS doesn't permit resolving next hop interfaces through default-routes.
This PR adds a fixed resolution policy for NXOS VRFs that prevents this.

NXOS: exclude default-routes as in NHI resolution process

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java

Current `setOrigin` clause was left over from copying the IOS parser.

XR BGP default-originate route: set origin-type IGP

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java

* Generate one default-originate policy per config (technically up to 2, for IPv4 & IPv6)
* Use standard default-originate policy name from `Names`

Clean up XR BGP default originate policy

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/ospf_max_metric_on_startup
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/ospf_max_metric_transient
tests/parsing-tests/unit-tests-vimodel.ref

Don't apply `max-metric` when transient option `on-startup` is specified.

NXOS: handle transient max-metric

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/resolution_policy
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/parsing-tests/unit-tests-vimodel.ref

IOS doesn't permit resolving next hop interfaces through default-routes. This PR adds a fixed resolution policy for IOS VRFs that prevents this.
Fixes #6785

IOS: exclude default-routes as valid steps in resolution process

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/resolution_policy
tests/parsing-tests/unit-tests-vimodel.ref

Similar to #6785, XR doesn't permit resolving next hop interfaces through default-routes. This PR adds a fixed resolution policy for XR VRFs that prevents this.

XR: exclude default-routes as valid steps in resolution process

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override

Handle setting OSPF network type at OSPF router level. This value is used when no network type is set at the OSPF interface level.

IOS XR: handle setting OSPF router network type

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java
tests/questions/experimental/testRoutePolicies.ref

Add the tag field to the class that we use to display answers to questions about BGP route announcements.

questions.BgpRoute: add the tag field

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override

https://github.com/batfish/batfish/pull/7016 incorrectly set the process-level network type for area-level settings. This PR correctly handles setting network type at the top OSPF router/process level.
Area-level network type settings are not included in this PR and will require a bit more work.

IOS XR: fix OSPF router network type

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-interface-cost

For XR loopback interfaces, the OSPF cost is set to `1` unless explicitly configured. This also applies with set network type / `loopback stub-network enable`.

IOS XR: fix loopback OSPF cost calculation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySet.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java

BGP: use CommunitySet for intermediate state and parameters

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type

Remove parsing/extraction support for OSPF configuration under top-level interfaces. On XR, this syntax isn't supported and this kind of configuration is done under the `router ospf ...` context.

XR: remove impossible OSPF configuration syntax

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfSessionProperties.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfInterAreaRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfIntraAreaRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AbstractRouteDecoratorMatchers.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
tests/basic/routes.ref

- iBDP add next-hop interface to `OspfRoute`s
- require next-hop interface for `OspfRoute`s except when non-routing bit is set
- next-hop interface not required for staging and export
- set next-hop interface when imported

Make OSPF routes non-recursive by including next-hop interface

---

projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusInterfacesConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConcatenatedConfigurationTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse

- First assign addresses from interfaces file
- interface init order is from top to bottom, considering only first declaration of each interface
- all of an interface's addresses are assigned on init
- previously assigned addresses in the same VRF are skipped
- Now assign addresses from frr file
- interface init order is from bottom to top, considering only last declaration of each interface
- all of an interface's addresses are assigned on init
- previously assigned addresses in the same VRF are skipped,
including those from interfaces file

Cumulus FRR only assign duplicated addresses to single interface per vrf

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfAddresses.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfAddressesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfInterfaceSettingsTest.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse

- add getOspfAddresses() to OspfInterfaceSettings
intent:
- if non-null, gives list of addresses to be used for establishing
OSPF sessions
- if null, should use Interface::getAllAddresses
- follow-on: actually use getOspfAddresses when establishing sessions
- populate ospfAddresses for Cumulus FRR
- also populate additionalArpIps for FRR using the difference between
ospfAddresses and surviving addresses assigned to Interface allAddresses

OSPF addresses datamodel and FRR conversion

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/loopback
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ospf_link_local

- enables forwarding across unnumbered links

Cumulus FRR assign LLAs to point-to-point OSPF interfaces without addresses

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ospf/OspfTopologyUtilsTest.java

- point-to-point links need not be on the same prefix
- use ospfAddresses to determine possible OspfConfigId source addresses
over getAllConcreteAddresses when ospfAddresses is present, e.g. for
unnumbered interfaces

OSPF topology compute unnumbered sessions

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/NodeTest.java

We accidentally made an `Optional<Optional<Rib>>` that could be absent, or
present with a Rib, or present with an absent Rib. We meant to chain the
optionality, which is done with `flatMap`.

ibdp/Node: use Optional#flatMap correctly

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/transformation/TransformationStep.java
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AnyAddressSpecifier.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaDynamicSourceNat.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaStaticSourceNat.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/arista/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/arista/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/arista/AristaStaticSourceNatTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/ip-nat-source-static
projects/batfish/src/test/resources/org/batfish/grammar/arista/testrigs/nat-source-static/configs/r1
projects/batfish/src/test/resources/org/batfish/grammar/arista/testrigs/nat-source-static/configs/r2
tests/parsing-tests/unit-tests-vimodel.ref

* Make extended ACLs distinguish between ANY and 0.0.0.0/0.
* Parse and extract AristaStaticSourceNat
* Extract IPs used for source NAT from an extended ACL. Since the IPs must be
destination IPs, only extended ACLs can be used. Include some of the expected
error handling during conversion.
* Install forward and reverse static rules on the interfaces.
* Tests.
Fix #7032 .

Arista: implement interface ip nat source static

---

projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureType.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapContinue.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaRouteMapTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_misconfigured
tests/parsing-tests/unit-tests.ref

* If continue target is undefined, the continue line is ignored
* If the continue target is before this term, then the continue line is ignored
* Also move reference tracking to parser, and add warnings

Arista: fix handling of undefined continue targets

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/StreamUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/StreamUtilTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java

1. Streaming `nodes.values()` will always chunk similar nodes together.
This means imbalanced work, as in the common case nodes with similar
names have similar complexity (number of routes, etc).
2. `parallelStream().flatMap()` does not parallelize over the flat-mapped
things.
To improve both of these, materialize a randomized list of all virtual
routers. This means that we can parallelize over the entire list, and
remove the name-based locality during parallelization.
After #7053

dataplane: parallelize across virtual routers, not nodes

---

projects/allinone/src/test/java/org/batfish/question/traceroute/TraceroutePolicyBasedRoutingTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/dataplane/PbrWithTracerouteTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoNatTest.java

Use a less ambiguous name for PBR/forwarding policies attached to interfaces.

Interface: rename routing policy to packet policy

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Interface.java

Routing policy attached to XR interfaces isn't populated anywhere, I suspect it was just copied from IOS.
Remove it since it is unused (and if it were used in the future, it would conflict with ACL based forwarding policies).

XR: remove unused routing policy from VS ifaces

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/TransferParam.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Updates the handling of if statements in the symbolic route-map analysis so that it only analyzes feasible branches.  Some guards are statically resolved (notably CallExprContext and CallStatementContext), so analyzing both branches is unnecessary.  Skipping analysis of the infeasible branch also avoids a possible failure to answer the question due to reaching route-map features not currently supported.  Further, it allows us to properly account for updates to things like the default action within the one feasible branch, which previously were being ignored.

SearchRoutePolicies: Better handling of conditionals

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/DecrementPriority.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackActionVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackMethodVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackInterface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluatorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluatorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/TrackInterfaceTest.java

Add initial VI support for updating Hot Standby Router Protocol (HSRP) priority based on tracking interface active status.

HSRP: priority-update support

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_conversion
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_conversion_warn

Convert NXOS track objects into VI model (currently, only interface line-protocol tracking is supported in the VI model).

NXOS: track object conversion

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_hsrp_warn
tests/parsing-tests/unit-tests-vimodel.ref

Support converting HSRP group secondary IPs and also enforce device's restrictions on what IPs can be used for HSRP groups.

NXOS: HSRP secondary ip

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Common.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConversions.java

No real need to have separate generated deny-all policies for separate contexts that need them. This PR utilizes the new function in one context; can update more contexts to use it as we find/create them.

Move deny-all BGP redistribution policy init function to common

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BgpPeerAddressNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DiscardNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Ip6NextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/IpNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NextHopExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/UnchangedNextHop.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetNextHop.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/BgpPeerAddressNextHopTest.java

- Make each NextHopExpr evaluate the environment itself
- Make SetNextHop modify intermediate BGP attributes if appropriate
- Update incorrect comment on NextHop legacy converter method
Inspired by an observation that the old version of `SetNextHop` fails to return [here](https://github.com/batfish/batfish/blob/161bb0fa512846d58ecfe6fdf745ac3835701c6c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetNextHop.java#L50) (confirmed as bug by ari).

Clean up SetNextHop and next hop exprs

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraints.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraintsTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraintTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraintsTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestionTest.java

Updated SearchRoutePolicies to signal an error if the question is using the action DENY but also specifies constraints on the expected output route.  There are no output routes when the goal is to find input routes that are denied, so specifying both is likely an error on the part of the user.  Previously we silently ignored the output route constraints.

SearchRoutePolicies: Output route constraints are incompatible with the DENY action

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_conversion
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_refs
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn

Add parsing and reference tracking for other `track` methods.
We still don't support really extracting these into the VS model but this replaces false-positive undefined references to these structures with parse warnings (indicating the track method isn't supported and ignored).

NXOS: parse unsupported track methods

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfAddressFamilyAggregateNetworkConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos-aggregate-address

- fix lexing for aggregate-address route-map keywords
- use BGP process-level aggregates instead of vrf-level following batfish/batfish#7067

NXOS fix aggregate-address implementation

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_nclu/CumulusConversionsTest.java

- Create at most 1 default-route export policy per config (as javadocs incorrectly already claimed)
- Use `Names` for policy name functions

Clean up FRR BGP conversion

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpVrfAddressFamilyAggregateNetworkConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/bgp_aggregate_address
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/frr-aggregate-address

- flesh out aggregate-address parsing
- use BGP process-level aggregates instead of vrf-level following batfish/batfish#7067

FRR fix aggregate-address implementation

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/bgp_vnis

Two changes:
1. FRR and NCLU: Fix a bug in the condition for generating a dummy BGP process. Needed more parentheses.
2. FRR only: Include a reject-all redistribution policy in dummy BGP processes (this was already done for NCLU).

Cumulus: Fix incorrect VNI condition

---

projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_nclu/CumulusConversionsTest.java
tests/parsing-tests/unit-tests-vimodel.ref

BGP aggregates are now activated based on routes in the BGP RIB instead of the main RIB. (However, there's still no parsing or extraction of any aggregate-related grammar in NCLU.)

NCLU: Fix BGP aggregate route conversion

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GeneratedRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/KernelRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/LocalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RipRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java

getMetric used to return a Long, but implementations never return null, and clients don't null-check. Now it returns a long.

AbstractRoute: unbox metric

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/RouteInfo.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/RouteInfoTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/RoutingStepTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
tests/basic/traceroute-1-2.ref
tests/basic/traceroute-2-1.ref

Include the administrative distance and metric route fields in the RouteInfo objects embedded in traceroute traces.

Traceroute: include admin and metric in RouteInfo 

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Interface.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/TagRewritePolicy.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/TagRewritePop.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/interface_l2transport
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/interface_l2transport_warning

Parse and extract interface `l2transport` and related properties; these can be used in conjunction with `bridge-domain`s (see [docs](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r6-1/interfaces/configuration/guide/b-interfaces-cg-asr9k-61x/b-interfaces-cg-asr9k-61x_chapter_0111.html) and [related PR](https://github.com/batfish/batfish/pull/7106)).

XR: parse and extract `l2transport` interfaces

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/BridgeDomain.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/BridgeGroup.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/l2vpn
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-vimodel.ref
tests/parsing-tests/unit-tests.ref

See [here for some details on BVI/l2vpn configuration](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r6-1/interfaces/configuration/guide/b-interfaces-cg-asr9k-61x/b-interfaces-cg-asr9k-61x_chapter_0111.html).
Quick summary:
* `bridge group` is just a grouping of `bridge-domain`s within `l2vpn`
* `bridge-domain` defines a "switch" that bridges all `interfaces` in that domain
* `routed interface` is the L3 `BVI` interface that is used to route interfaces in the `bridge-domain`

XR: parse and extract `l2vpn`

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisArpFailureDispositionsTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java

The INSUFFICIENT_INFO disposition is assigned to destination IPs that are considered internal to the network, but terminate away from the location where it is configured. Previously insufficient info excluded network and broadcast IPs of connected networks, and those IPs were given the EXITS_NETWORK (which is a success disposition, while INSUFFICIENT_INFO is a failure).

Insufficient Info: consider network/broadcast IPs to be internal

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DomainToL2Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/DomainToL2InterfaceTest.java

1. A native vlan must still be included in allowed vlans.
2. Tagged frames in the native vlan are rejected.

Trunk: native vlan must be allowed, tagged rejected

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-misc-ignored

Ignore `storm-control` within `bridge-domain` interface configuration, otherwise parser loses context and assumes interface config is top-level.

XR: ignore bridge interface storm-control

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/IpPrefix.java

ConcreteInterfaceAddress now requires the IP to be a host IP, while IpPrefix does not.

PaloAlto/IpPrefix: don't parse via ConcreteInterfaceAddress

---

projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java

Allows route-maps that are used as export filters (i.e., the direction parameter has value OUT) to be simulated with TestRoutePolicies.

TestRoutePolicies: Support simulation of OUT route-maps

---

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/roles/perRoleOutliers.ref

With routing policy tracing in place, we can turn on routing policy simplification. Since simplification is statement-by-statement, and traceable wraps statements, there is no interference between the simplification and tracing. 
(A separate PR will push simplification deeper within the traceable statement.)

Turn on routing policy simplification

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilIspTest.java
projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java
projects/batfish/src/test/java/org/batfish/representation/aws/AwsConfigurationVpcEndpointGatewayTest.java
tests/aws/topology-example-aws.ref
tests/aws/vimodel-example-aws.ref
tests/parsing-tests/unit-tests-vimodel.ref

Interfaces that correspond to physical interfaces should have type physical.
VPNs, Tunnels, etc. in AWS stay the same.

ISPs,Amazon: use physical interfaces where appropriate

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_hsrp

BFD isn't handled yet, but make sure Batfish doesn't lose context when encountering it under HSRP.

NXOS: ignore HSRP BFD

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

XR: remove todos for implemented as-path constructs

---

projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java

Without key columns, the difference view is just the cross-product of all rows.

VxlanEdges: add key columns

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/BroadcastL3Adjacencies.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/DeviceBroadcastDomain.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/EthernetHub.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/PhysicalInterface.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/BroadcastL3AdjacenciesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/L3AdjacencyComputerTest.java

An L3Adjacencies implementation that models all interfaces' L1, L2, L3
configuration. This differs from `GlobalBroadcastNoPointToPoint` in that
interfaces with incompatible L2 configuration are not considered connected.
This differs from `HybridL3Adjacencies` in that it models every interface as
being connected to some Ethernet hub, whether or not it appears in the L1
topology. By using a flood-fill-style algorithm, performance is also greatly
improved.
This algorithm is not yet plumbed into any accessible path, as it cannot handle
all networks.
* Does not handle VxLAN or multiple L2 subinterfaces yet

BroadcastL3Adjacencies: initial draft

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Updates the symbolic route analysis to properly handle configuration formats that use output attributes for matching, rather than the attributes of the original route.

TransferBDD: Support formats that use output attributes

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java

We don't yet support NXOS route tracking, and warn when it is configured. Previously the warning generated was for the entire ip_route_network rule. Now it's specific to the `track` option.

nxos: improve todo warnings for route tracking

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java

When computing differences of BGP RIBs, we were incorrectly filtering routes by applying the input vrf regex to routing protocols. Now we use the input RoutingProtocolSpecifier.

routes question: filter by protocol correctly in BGP differential mode

---

projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java

Make the core logic available to outsiders. Earlier, one had to construct a question object to get the answer.

FilterLineReachability: Factor out answering logic

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_eigrp
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_port_channel

1. Bandwidth can exceed int32_max, even though it is in kbps.
2. Physical interfaces and port-channel interfaces have different maximum bandwidths.
3. Fix EIGRP bandwidth parsing as well.
and tests.

NX-OS: fix bandwidth parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationInfoUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisArpFailureDispositionsTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BidirectionalReachabilityAnalysisTest.java

Reverts batfish/batfish#7127
This broke some pybf notebooks: https://github.com/batfish/pybatfish/compare/matt-updrefs
The problematic change is the forwarding analysis notebook, where we check that a particular change has no unintended effects. The goal is for differential reachability to identify one such unintended effect, where a host becomes reachable. With this PR, we're seeing that traffic to the network IP becomes reachable.

Revert "Improve flow dispositions for network/broadcast IPs"

---

projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java

Keys allow us to diff the answer table (i.e. see added/removed edges across snapshots).

Edges question: add keys for l1 mode

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/DistributeList.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco_xr/CiscoXrConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-distribute-list

Adds parsing and extraction for `distribute-list prefix-list FOO in` and `distribute-list prefix-list BAR out`, and adds conversion for the inbound direction (we do not currently convert outbound OSPF distribute-lists of any type on XR).

XR: Support OSPF distribute-list prefix-list in

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/AnnotatedRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java

- prevent loss of routes when a better route is installed and later
withdrawn
- enables experimental merge and rollback needed for planned loop checking implementation

Enable backup routes in main RIB

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4

There is no address-family mode under router ospf; the address-family line is stand-alone.

XR OSPF: No address-family stanza

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibResolutionTrie.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibResolutionTrieTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java

- add support for enforcing resolvability of routes in main RIB
- to be resolvable, a route must:
- have at least one route of a different prefix on its resolution path
- have no loops on its resolution path
- unresolvable routes are deactivated in the main RIB until they become resolvable again

Support enforcing resolvability of routes in main RIB

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfaceUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfaceUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

1. Introduce `InterfaceUtil` to be a single place to handle logic
2. Plumb it into cleanLayer1Topology. The raw Layer1Topology is the only one
that should contain non-canonical names.

Layer1Topology: flexible matching for interfaces

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
tests/aws/vimodel-example-aws.ref
tests/basic/viModel.ref

- apply vrf-level resolution restriction when finding LPM routes
- connected routes always get a pass
- skip loop checking for routes that fail resolution restriction
- skip resolvability check for non-recursive static routes
- update Configuration data model to support enabling main rib resolvability check

main rib resolver non-recursive static routes and resolution restriction

---

projects/question/src/main/java/org/batfish/question/filterlinereachability/AclEraser.java
projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java
projects/question/src/test/java/org/batfish/question/filterlinereachability/AclEraserTest.java
projects/question/src/test/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswererTest.java

This will allow acls with TraceElements and VendorStructureIds on different devices to be considered equal.

FilterLineReachability: erase TraceElements and VendorStructureIds from ACLs for CanonicalAcl

---

projects/build-tools/src/main/resources/org/batfish/pmd/pmd-ruleset.xml
projects/checkstyle.xml

The more we can move in from checkstyle, the less will only be caught in CI.

pmd: move NeedBraces in from Checkstyle

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/L3AdjacencyComputerTest.java

The activeLogicalL1Topology does not include edges where one or both sides are
inactive or not present in the snapshot. For deciding whether an interface is
attached to the global hub, however, we need to consider these removed edges.
Fall back to the logicalL1Topology, which does include all (logical) interfaces
mentioned in any L1 topology and present in the snapshot.

L3AdjacencyComputer: do not connect interfaces with L1 to global hub

---

projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/broadcast/L3AdjacencyComputerTest.java

It's just bad practice to have them all together. Especially as I just
accidentally let state leak (encapsulation vlan 4) from one test into another.

L3AdjacenciesComputerTest: split e2e tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Node.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ebgp-dynamic-local-ips/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ebgp-dynamic-local-ips/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ebgp-dynamic-local-ips/configs/r3
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ibgp-dynamic-local-ips/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ibgp-dynamic-local-ips/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/ibgp-dynamic-local-ips/configs/r3
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java

Allows BGP peers with no configured local IP to initiate BGP sessions during dataplane computation using dynamically inferred local IPs. The inferred local IPs are determined by finding LPM routes for the peer's peer address (i.e. remote IP) and taking the interface IPs of those routes' forwarding interfaces as potential local IPs for the peer.
Does not yet remove any local IP inference done during conversion (this will go in a follow-up PR). This could cause a bug if the connected route that was used for inference in conversion:
- is not an LPM route for the peer address
- is one of multiple LPM routes for the peer address (unlikely since it will be the only connected route for the peer address)
Ultimately, even peers whose peer address is contained in a connected route ought to …

BGP: Infer local IPs dynamically

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java

Seems to be completely unreferenced

Delete unused field in BgpPeerConfig builder

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfaceUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfaceUtilTest.java

InterfaceUtil: infrastructure for canonicalizing interfaces

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

Some newer configurations have all the config in one file. For these, we may
not have a TMSH header, but we will have sys and ltm settings combined.

F5: improved detection for newer configs

---

projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-with-secret-data

JunOS: handle ## SECRET-DATA after semicolon

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfDefaultInformationOriginate.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-default-information
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref
tests/parsing-tests/unit-tests-vimodel.ref

This PR is a bit overloaded, but the most important change is that Cisco vendors and Arista were using the same name for all OSPF export policies in a given VRF, so the export policy was only accurate for the last OSPF process converted. Updated to use different export policy names for each process.
Other changes consist of XR OSPF cleanup:
* Test OSPF `default-information originate` and add support for `no default-information originate`
* Clear out invalid grammar from null block

Cisco and Arista: OSPF export policies per process

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/DistributeList.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco_xr/CiscoXrConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-distribute-list

Delete grammar that would have parsed `distribute-list prefix-list` outside of v3.

XR: OSPF distribute lists only use prefix-lists in v3

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/Interface.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/bond_interface_conversion
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/interface_conversion
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface

Since there is no explicit `set interface IFACE_NAME bandwidth` command, I think interface bandwidths are equivalent ot their speeds.

CP: Convert link-speed to interface speed and bandwidth

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java

Like unimplemented and pedantic, these should not be surfaced this way.

BatfishLogger: demote passthrough log4j for redFlag

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java

Remove unnecessary prefix
Rwmove unnecessary newline
Print the interface name canonically using NodeInterfacePair

Batfish: improve message when disabling unusable vlan interface

---

projects/allinone/src/test/java/org/batfish/e2e/l1/asymmetric/BUILD
projects/allinone/src/test/java/org/batfish/e2e/l1/asymmetric/L1AsymmetricTest.java
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/BUILD
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/batfish/layer1_topology.json
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/configs/a1
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/configs/a2
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/configs/b1
projects/allinone/src/test/resources/org/batfish/e2e/l1/asymmetric/configs/b2
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/HybridL3Adjacencies.java

Some user-provided layer1 topologies are asymmetric. While behavior has always
been best-effort in these scenarios, it has changed since the last release.
Switch back to the behavior before batfish/batfish#7207.

HybridL3Adjacencies: fix behavior under incomplete L1 topology

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/bond_interface_conversion
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/bond_interface_warn

Previously thought that adding an otherwise-unconfigured interface to a bonding group was invalid, but in fact it's not necessary for there to be any other mention of the added interface.

CP: Adding interface to bonding group can create it

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Global.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Group.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Host.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRulebase.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Original.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PolicyTargets.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceGroup.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceTcp.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Uid.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/UnhandledGlobal.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRulebaseTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/OriginalTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/PolicyTargetsTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/UnhandledGlobalTest.java

- just serialize objects-dictionary directly
- flesh out special objects like Globals and CpmiAnyObject

Checkpoint vs fix up nat rulebase objects

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

Afaict, CheckPoint static routes must resolve via a connected route, so make sure they're marked as non-recursive

CheckPoint: make static routes non-recursive

---

projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanDestination.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanNextHopIn.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRibHasRoute.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyInlinePrefix6Set.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyPrefixSet.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyPrefixSetName.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/route-policy-done

1. Add null annotations, so we get warnings in users.
2. Make the visitor more readable, and fix a bug where mixed prefix-sets would
not get converted.
3. Add a test that v4 addresses in combo prefix-sets are permitted.

IOS-XR: fix some issues with prefix-sets

---

projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessRule.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessRuleOrSection.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessSection.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AccessLayerTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ManagementPackageTest.java

Rename to class to `AccessLayer` and remove redundant annotation.
Follow-up to https://github.com/batfish/batfish/pull/7279 and https://github.com/batfish/batfish/pull/7272

CheckPoint: Access Layer cleanup

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpace.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ConcreteService.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ConcreteServiceVisitor.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ConcreteSrcOrDst.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ConcreteSrcOrDstVisitor.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiGatewayCluster.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Group.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Host.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Network.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Service.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceGroup.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceTcp.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceVisitor.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/SrcOrDst.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/SrcOrDstVisitor.java

These interfaces should be useful at least for NAT and filter rules. If we find that they're useful more generally, we may want to rename the `SrcAndDst` ones. The new hierarchies (with new interfaces in bold+italics):
- ***Service***
- CpmiAnyObject
- ***ConcreteService***
- ServiceTcp
- ServiceGroup
- ***SrcOrDst***
- CpmiAnyObject
- ***ConcreteSrcOrDst***
- AddressSpace
- AddressRange
- Host
- Network
- CpmiGatewayCluster
- Group
It's possible that the pre-existing `AddressSpace` interface was meant to be `SrcOrDst` (@arifogel?), in which case that adjustment could be made to the PR.
It's useful to separate `CpmiAnyObject` from the concrete types because `CpmiAnyObject` is not valid as a NAT translated src/dst/service, while I believe all the concrete types are.

Checkpoint MGMT VS: Visitors for address spaces and services

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java

- network dir is created right before ID is assigned
- if GC runs in between dir creation and ID assignment, it considers the
network dir orphaned and expunges it
- we avoid this condition generally by requiring dirs to be a certain
age before deletion, but we improperly neglected to check age of network
dir itself
- fix is to check age of network dir before deleting it

Fix GC race condition causing improper deletion of network dir

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

Names are unique, even across object types, so use names instead of Uids for converted `IpSpaces`.

CheckPoint: use names instead of Uids for VI model IpSpaces

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java

Don't rely on VI model being populated yet, to determine domain to gateway association.
Also, go ahead and convert management config earlier in the pipeline, so we can use that information for converting other datamodel classes in the future.

CheckPoint: use VS model to determine domain -> gateway association

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchBgpSessionType.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/BUILD
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchBgpSessionTypeTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/BooleanExprAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java

Returns true only when being evaluated in the context of a specific type of BGP Session.

MatchBgpSessionType: a new routing policy BooleanExpr

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Interface.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/InterfaceTopology.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiClusterMemberTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsClusterNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterMemberTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTopologyTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/SimpleGatewayTest.java

Parse `Interface` addresses and mask lengths.
Also, add `TEST_INSTANCE` to use in most tests, instead of manually constructing objects everywhere (with frequently changing params).

CheckPoint: parse Interface addresses

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosBgpTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/bgp/nxos-bgp-network-redistribute

If a route is both redistributed and generated by a network statement, the
network statement version wins.
Also added modeling of the local weight 32768 for these routes.

NX-OS: bgp network statement preferred over redistribution

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/GatewaysAndServersTest.java

`CpmiHostCkp` can contain `interfaces`

CheckPoint: Support `interfaces` in `CpmiHostCkp`

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/NamedAsPathSet.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/NamedAsPathSetTest.java

Also, relax from BGP to HasReadableAsPath.

NamedAsPathSet: treat non-BGP routes as having empty as path

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementDomain.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Network.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ObjectPage.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ManagementDomainTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ManagementServerTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NetworkTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ObjectPageTest.java

This PR adds initial parsing of object JSON files for CheckPoint management data. This is required to resolve object references for things like NAT and Access Rulebases.
So far, only `show-networks.json` is supported.
Also in this PR:
* Tweak to `Network`, to allow parsing of Ipv6 networks
* Small reorg of existing CheckPoint management data parsing
* Adding these parsed objects to the `ManagementDomain` (not yet actually used in conversion)

CheckPoint: initial parsing of `<object>.json` files

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

In addition to converting objects embedded in rulebases, convert ManagementDomain objects.

CheckPoint: Convert `objects` from ManagementDomain

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiGatewayCluster.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiVsClusterNetobj.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobj.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsClusterNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobjTest.java

- use ImmutableList for cluster member names
- allow cluster member names to be absent on all cluster subclasses

Checkpoint cluster class cleanup

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpace.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpace.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Group.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasName.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Host.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NamedManagementObject.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Network.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceTest.java

- yet another hierarchy reorganization
- assume gateway as IpSpace means its IPv4 mgmt address, since other
ata does not appear in show-objects schema.

Checkpoint mgmt convert show-gateways-and-servers data to IpSpace

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceTcp.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java

This hotfix assumes that IntegerSpace parse just works.
We should probably have VS special handling, unless we can
confirm that the syntax used on device always confirms to
that accepted by IntegerSpace.

Checkpoint: fix handling of ServiceTcp port ranges

---

projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AccessRuleTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AccessSectionTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/AddressRangeTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiClusterMemberTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsClusterNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterMemberTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxNetobjTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/GroupTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/HostTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatRuleTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NatSectionTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/NetworkTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/OriginalTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/PackageTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/PolicyTargetsTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/RulebaseActionTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceTcpTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceUdpTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/SimpleGatewayTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/UnhandledGlobalTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/UnknownTypedManagementObjectTest.java

JSON serialization tests should always test the class with @JsonTypeInfo on it.
This is because that is what the known type will be when deserializing these
fields as part of another object.

Checkpoint: test type hierarchy

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java

Use all objects during conversion, not just the ones directly attached to the rulebase.

CheckPoint: Use all objects during Access/NAT rule conversion

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceGroup.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/BUILD
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceToMatchExprTest.java

Revamp `Service` conversion, NAT original-matching, and related tests.
----
* Return `AclLineMatchExpr` instead of `HeaderSpace` in a couple places
* Not implemented yet, but sets up for resolving `ServiceGroup`
* Add some direct tests of the visitor
* Consolidate some more conversion test constructs

CheckPoint: revamp service conversion

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrrpGroup.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ClusterMember.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiClusterMember.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiGatewayCluster.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiVsxClusterMember.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/cluster_member

- create a VRRP group for each participating cluster member interface
- assign priority that is higher the lower the member's index in
cluster's cluster-member-names

Checkpoint implement cluster virtual IP assignment

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessSection.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversionsTest.java

Add the object name (if it exists) to the VI model construct.
e.g. a named AccessLayer would now be named something like `uid123456 (Layer Name)` and an unnamed AccessLayer would still be named `uid123456`.

CheckPoint: better Access Layer/Section naming

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/BUILD
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java

Handle merging `AccessLayer` pages in access-rulebase json input files.
----
Handles merging both:
1. top-level rulebase split across pages
2. rulebase within `AccessSection`s under the top-level rulebase

CheckPoint: merge `AccessLayer` pages

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchInterface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchInterfaceTest.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/BooleanExprAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java

Interface routes (OSPF, Connected, Local, Static) will be matched, but not
resolved routes that happen to use those interface. Probably on most vendors
the latter is actually the correct semantics; however this route-map is most
often used to match local routes so it should get us going in the right
direction.
This is for batfish/batfish#6502

MatchInterface: implement simple version

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BUILD
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpBestPathExportTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/BUILD
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/new-session/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/new-session/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/new-session/configs/r3
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/new-session/configs/r4
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/new-session/configs/r5
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/old-session/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/old-session/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/old-session/configs/r3
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/old-session/configs/r4
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/withdrawal/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/withdrawal/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/withdrawal/configs/r3
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/withdrawal/configs/r4
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/bgp-best-path-export/withdrawal/configs/r5

Under best path:
- To advertise an ADD, a route must currently be best
- To advertise a WITHDDRAW, a route must previously have been best

BGP only export best-path routes when not using add-path

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CheckPointManagementTraceElementCreators.java

* Enclose object names in `'`
* Remove stale `TODO`
* Fix `CpmiAnyObject` name in trace

CheckPoint: minor cleanup for traces

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasUid.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementObject.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatRuleOrSection.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatSection.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java

Handle merging NAT rulebases even when NatSections are split across pages. Similar to what we're doing for `AccessLayer` page merging https://github.com/batfish/batfish/pull/7370

CheckPoint: better NAT rulebase merging

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceToMatchExprTest.java

Now, a service trace might look like this:
```
* Matched service-group 'group1'
* Matched service-group 'group2'
* Matched service-icmp 'icmp'
* Matched IP protocol ICMP
* Matched ICMP type 1
* Matched ICMP code 2
```
or
```
* Matched service-tcp 'tcp'
* Matched IP protocol TCP
* Matched destination port '100-105,300'
```

CheckPoint: add more details for `Service` tracing

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_next_hop_self

- do not apply next-hop-self when exporting iBGP route to a route-reflector client

NX-OS fix next-hop-self for route-reflector clients

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CheckPointManagementTraceElementCreators.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceOther.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceVisitor.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/TypedManagementObject.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceOtherTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceToMatchExprTest.java

Very basic, initial handling of `service-other`. Will need to do a lot more work around actually parsing the `match` strings.
Based on https://github.com/batfish/batfish/pull/7353

CheckPoint: v0 `service-other` support

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/arista/StaticRoute.java
tests/parsing-tests/unit-tests.ref

Delete several unused options, make sure NexHop is required, remove legacy s_route.

Arista: redo ip route grammar

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/DependencyEdge.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/interface_dependencies/InterfaceDependenciesTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

Previously, we tracked _local_ interface dependencies: e.g. a portchannel depends on at least one of its members interfaces being active, a subinterface depends on its superinterface being active, etc. This PR adds _non-local_ interface dependency tracking: for physical or LACP interfaces, if the `Layer1Topology` identifies a neighbor interface, depend on that neighbor being active.

Track non-local interface dependencies

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_interface.g4
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/package-info.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/package-info.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConfigurationTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/BUILD
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/interface_warn
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/interfaces

* Add support for extracting `ethernet` and `loopback` interfaces as well as a few common properties
* Add support for some class of string quoting in names (e.g. `"foo "and' bar'` == `"foo and bar"`)

A10: initial `interface` VS model

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java

Use a regular expression to match AS_PATH in access-list instead of converting a single integer to a regular expression.
- update lexer / parser
- update conversion
- update tests

feat: add regex to as path access lists

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java

A hotfix to make VRRP winner deterministic. 
Non-determinism can happen if interfaces from separate groups get combined together because they have the same group Id. Will send a proper fix later that distinguishes different groups.

Pick the VRRP winner deterministically

---

projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java

Convert `Interface`s into the VI model.
Only `ethernet` and `loopback` interfaces are extracted so far, so those are the only types we convert at this point.

A10: convert `Interface`s

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java

Automatic hide NAT rules that hide behind gateways need to transform src IP to egress interface IP, which means outgoing transformations on external interfaces need to vary by interface. This PR modifies the existing method `automaticHideRuleTransformation` into `automaticHideRuleTransformationFunction`, which now instead of creating a `Transformation` creates a `Function<Ip, Transformation>` that takes in an external interface's IP and generates the correct `Transformation`. The resulting functions are used to generate unique transformations for each external interface.

CP: Convert automatic hide rules per external iface

---

projects/allinone/src/test/java/org/batfish/e2e/l1/asymmetric/L1AsymmetricTest.java
projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

A variant of Batfish::loadConfiguration that will not parse uninitialized snapshots. Call it from topology provider, which helps make sure that topology provider does not try to initialize snapshots. Topology provider is not expected to work for uninitialized snapshots.

IBatfish: Another load config that refuses to initialize snapshot

---

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java

Transformations can be very deep, so recursion can cause stack overflow. Use the heap (via work queue) instead.

CollectIpSpaceReferences: avoid recursion for traversing Transformations

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/interface_dependencies/InterfaceDependenciesTest.java

We don't model virtual port-channels (VPCs), and our dependency tracker can't express their dependencies. So if we encounter a portchannel that looks like a VPC (i.e. it has two neighbor interfaces, on different devices, and its members have neighbors on those same devices), don't track the dependencies on the neighbor portchannels.

Skip nonlocal interface dependency tracking for likely VPCs

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDLoopDetectionAnalysis.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java

- Expose a version of `detectLoops` with results keyed by `StateExpr` instead of `IngressLocation`
- Implement of version of `transposeAndMaterialize` that takes a `Collection<Edge>` as input

Minor reachability API tweaks

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/interface_dependencies/InterfaceDependenciesTest.java

We use the logical L1 topology for AGGREGATED/REDUNDANT interfaces, which includes edges to physical nodes (i.e. the
neighbors of their member interfaces). Exclude those when looking for a unique neighbor.
After #7435

Interface dependencies: for AGGREGATED/REDUNDANT interfaces, exclude neighbors of other types

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java

Applies automatic static NAT rules on external interfaces:
- Outgoing transformation applies source NAT to matching outbound traffic
- Incoming transformation applies dest NAT to matching inbound traffic
Automatic static NAT, as currently implemented, does not impact transformations on non-external interfaces.
In theory, there is be a bug where static NAT rules could get applied to external-to-external traffic. Unlikely to affect any traffic in practice because external-to-external traffic isn't likely to have an internal source IP or a dest IP matching a static rule's translated IP.
Still to do:
- Support automatic static NAT rules on objects other than hosts
- Support `install-on` values other than `"All"`

CP: Automatic static NAT rule support

---

projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java

Set the VLAN ID for `VLAN` `router-interface`s (`VirtualEthernet` interfaces).

A10: set `ve` interface VLAN

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_trunk.g4
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10StructureUsage.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2_convert_warn

Add support for ACOS v2 trunk definitions.
Also, update interface conversion to use trunks as source of truth for aggregate membership, to make conversion compatible with v2 datamodel (which _only_ populates default trunk information in the trunk itself, not in the interfaces).

A10: Support ACOS v2 trunk definition

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasNatSettings.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasNatSettingsVisitor.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Host.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Network.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java

Automatic hide NAT rules configured on `AddressRange` and `Network` objects should match all traffic whose source IP is in that object's IP space, but should only transform traffic destined outside that IP space.

CP auto hide NAT: Match internal traffic without transforming

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConfigurationTest.java

* Remove space from VI interface names for A10 devices to make using them w/ Batfish/Pybatfish slightly easier
* Use the original format as the human name
* Use A10 interface "name" as VI interface description, since that appears to be the intended use-case

A10: better VI interface names

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/WarningsTest.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java

Makes it slightly easier to use redFlag. 
The method with the tag removed in this PR was being used only in two places, and incorrectly in both (as `(format, args)` instead of `(msg, tag)`).

Tweak redflag APIs

---

projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2_convert
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2_convert_warn
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_convert_warn
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_vlan_acos2_convert
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_vlan_convert

`trunk`s appear to be a distinct object type, different from `interface`s.
`show config` prints `trunk` configuration, followed by `vlan` config, and finally `interface` config.
A `vlan` which applies to a trunk is configured by applying to each trunk member, e.g.:
```
trunk 1
ethernet 1 ethernet 2
!
vlan 2
tagged ethernet 1 ethernet 2
!
interface ethernet 1
!
interface ethernet 2
!
```
`trunk`s appear to just be a type of `interface`.
`show config` prints `vlan` config, followed by `interface` config (including `trunk` interfaces).
A `vlan` which applies to a trunk is configured simply by associating with the trunk itself, not its members:
```
vlan 2
tagged trunk 1
!
interface ethernet 1
trunk-group 1
!
interface ethernet 2
trunk-group 1
!
interface trunk 1
!
```
----
In this PR:
* Add …

A10: inherit `trunk` `VLAN` settings from its `members`

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/IpsecUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpWildcardSetIpSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AbstractIpSpaceContainsIpTest.java

1. Intern equivalent instances.
2. Only sort on JSON where it is needed.
3. Skip builders in simple cases, as this elides a copy.

IpWildcardSetIpSpace: improve efficiency

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java

We already have an Ip with value l1, and picking the minimum is more likely to
be the base of the returned prefix.

Prefix: elide copy in longestCommonPrefix

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPath.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsSet.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ExcludeAsPath.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/StatementVisitor.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/ExcludeAsPathTest.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_routemap.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetExcludeAsPath.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapSetPrependAsPath.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/GeneratedRouteHelperTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapSetExcludeAsPathTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapSetPrependAsPathTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus_nclu/RouteMapSetPrependAsPathTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollectorTest.java
projects/question/src/main/java/org/batfish/question/TracingHintsStripper.java
projects/question/src/test/java/org/batfish/question/TracingHintsStripperTest.java

Add exclude option to modify AS_PATH in route map. 
See [bgp_routemap.c](https://github.com/FRRouting/frr/blob/master/bgpd/bgp_routemap.c)
- update grammar
- update representation
- add test

FRR: support route map set as-path exclude

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_vlan.g4
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/vlan_acos2

Handle `vlan` syntax where interfaces are referenced by a list and range on the same line, which appears to be allowed in `acos v2`. Note: list and range references were previously allowed, but only on separate lines.
e.g.
```
vlan 3
untagged ethernet 1 ethernet 3 to 4
!
```
(which corresponds to `Ethernet 1`, `Ethernet 3`, and `Ethernet 4`)

A10: handle hybrid vlan syntax

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AclIpSpaceTest.java

Because AclIpSpace#intersection and AclIpSpace#difference both use complement,
it's not uncommon that we complement a complement. Optimize in this case to
the original AclIpSpace.

AclIpSpace: optimize complement of complement

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/BooleanExprAstNodeToAclLineMatchExpr.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CheckPointManagementTraceElementCreators.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/DportAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/HasInspectText.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/IncomingAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/OutgoingAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExpr.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/TcpAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/UdpAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/UnhandledAstNode.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/VariableInspectTextBooleanExprAstNode.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/BooleanExprAstNodeToAclLineMatchExprTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/ServiceToMatchExprTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/DportAstNodeTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/IncomingAstNodeTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/OutgoingAstNodeTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExprTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNodeTest.java

- store exact INSPECT text in `AstNode`s for which there are multiple equivalent inputs
- implement tracing of service-other, with element structure:
- service-other name
- protocol
- match expression
- leaf boolean expressions

CheckPoint service-other tracing

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Many/most uses of ite are for constructing BDDs bottom up: the condition BDD is a single variable whose level is less than that of either branch BDD. These are inexpensive operations so don't cache them.

BDD.ite: skip the operator cache when we're building the BDD bottom-up

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/SnapshotConnection.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/SnapshotConnectionTest.java

The field doesn't make sense anymore since there can be two different snapshot hosts involved, and it was not being used anyway.

IspModeling: Remove hostname from SnapshotConnection

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpRange.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java

- Specific simple AclIpSpaces can be IpWildcardSetIpSpace instead
- Create fewer IpWildcardSetIpSpaces of size 1

Batfish: simplify some IpSpaces

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java

In master, there is currently a bug where a flow can match a manual rule at ingress and then match an automatic rule at egress. This was incorrect for multiple reasons:
- Once a manual rule has been matched, no automatic rules are applicable
- All rules should match on the original packet fields, but the egress transformation could have matched fields that were translated at ingress
This PR fixes the problem by converting all rules into a `PacketPolicy` that is applied on ingress. One wrinkle is that some automatic rules use a `hide-behind gateway` functionality to translate the source IP to the IP of the egress interface, which is unknown at ingress. To get around this, when such rules are matched at ingress, we translate the source IP to `0.0.0.0`. Then all interfaces have an outgoing …

CP NAT: Move to PacketPolicy

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/IntegerSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java

Replace with a straightforward complement-within-bounds function.

NumberSpace: remove dangerous and misleading not methods

---

projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java

Add higher-level context for parse warnings in `toInteger` helpers.

A10: better parse-warning context

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PartialDataplane.java

We can instead reuse the forwarding analysis used to build topologies.
Since the topologies haven't changed, and no route exchange has been
done, the FIBs and Forwarding Analysis cannot have changed.

IBDP: do not recompute fibs and forwarding analysis at the end

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/Layer2VniConfigTest.java

Sick of fraudulent coverage diffs on unrelated PRs.

Layer2VniConfig: improve unit test coverage

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java

1. VirtualRouter#getBgpRoutes/getEvpnRoutes can be expensive.
(The result is recomputed in most cases.) So only call it once,
and use the prior result.
2. The Bgp/Evpn routes tables do not need empty cells.
3. Parallelize computation of tables, especially when the
"cell value" function can be expensive.

DataplaneUtil: parallelism and redundancy improvements

---

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
tests/aws/vimodel-example-aws.ref

That way, e.g., swp10 is after swp2, not before it.

Configuration: order interfaces by InterfaceNameComparator

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowsTest.java
projects/question/src/main/java/org/batfish/question/ipsecsessionstatus/IpsecSessionStatusAnswerer.java

Prior to this PR, Rows was sorted for determinism, using a completely
arbitrary sort.
Preserving insertion order enables answerers to provide a better,
useful default result order.

Rows: preserve insertion order

---

projects/question/src/main/java/org/batfish/question/interfaceproperties/InterfacePropertiesAnswerer.java

The code will already iterate over nodes and interfaces in sorted order,
we just need to use an insert-ordered data structure to preserve it.

InterfaceProperties: sort well by default

---

projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java

It does not depend on whether the session is eBGP

BgpProtocolHelper: tags are non-transitive

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizer.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityGraphOptimizerTest.java

Nodes that have only one in/out edge are identical to their predecessor/successor if that edge is IDENTITY. In that case, merge the two nodes.

BDDReachabilityGraphOptimizer: remove nodes with a single IDENTITY in/out edge

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

1. Missing default action because we used _edges.add instead of addEdge
2. Update tests to check both edges and actions.
3. Add invariant assertion (not in production)

PacketPolicyToBdd: fix missing default state

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibEntry.java
projects/batfish/src/main/java/org/batfish/bddreachability/IpsRoutedOutInterfacesFactory.java
projects/batfish/src/test/java/org/batfish/bddreachability/IpsRoutedOutInterfacesFactoryTest.java

The only use was in IpsRoutedOutInterfacesFactory, and this is actually
redundant with information already in the FibAction.

FibEntry: remove getResolvedToRoute

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibEntry.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java

The resolution steps will likely be needed later, but right now only the top
level route is used.

FibEntry: only track top level route for now

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java

Prior to this PR, communities would be dropped from an outgoing
route advertisement when preparing the route for export from the
BGP RIB, and before running it through export policy.
That meant that an export policy could add communities, and they
would get transmitted.
Instead, clear communities as needed when sending the route
(after export).

BGP: apply send-community only when sending route advertisements

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java

1. sbafi_route_map was missing a null check
2. The BGP grammar was not written well to work with recovery,
so an unrecognized line early in router bgp might take out all the
rest of the lines. This exposed (1) and triggered a crash for an
unrelated line.
3. Improve error messages.
4. Reorder rules alphabetically when safe.

FRR: rewrite BGP grammar for recovery, fix crash

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java

- needed to remove kernel route hack for A10 nat pool addresses

ARP replies include all vrf-owned IPs under proxy-arp

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/HighAvailability.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/NatRule.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoNatTest.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/high-availability
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/nat-high-availability
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/rulebase-warning
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/source-nat-high-availability
tests/parsing-tests/networks/unit-tests/configs/palo_alto/nat
tests/parsing-tests/unit-tests-undefined.ref
tests/parsing-tests/unit-tests-unused.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

* Track `high-availability` device id for PA devices
* Track device binding in PA NAT rules, and filter out inapplicable rules

Palo Alto: filter NAT rules on HA devices

---

projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConversionTest.java

- no longer necessary with batfish/batfish#7648
- also make all A10 kernel routes non-forwarding
- unclutters FIB

A10 remove hack kernel routes for nat pool ips

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

Add a couple more warnings when there is no domain or management configuration.

CheckPoint: add warning for missing management config

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

Allow different types of newline chars in CheckPoint format detection logic.

CheckPoint: better format detection

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

For cluster members, apply the policy from the cluster.

CheckPoint: cluster member policy inheritance

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

On some device type (e.g. A10, FRR, NXOS), BGP `network` statements
redistribute routes into BGP independently of `redistribute` statements.
This means an IGP route could result in up to two BGP entries if it is
matched by both a `network` statement and a `redistribute` statement.
This PR adds datamodel and iBDP support for such independent policies.
Previously, you could only get up to one BGP entry for an IGP route.

BGP support network policy independent of redistribution policy

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_network_and_redistribute

- use indendependent network policy for `network` statements instead of
combined redistribution policy
- allows multiple BGP RIB entries to be produced from single route
applicable to both a `network` and a `redistribute` statement per
device behavior

NXOS BGP use independent network policy

---

projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/arista/BUILD
projects/batfish/src/main/java/org/batfish/representation/arista/IsisProcess.java
projects/batfish/src/main/java/org/batfish/representation/arista/IsisRedistributionPolicy.java
projects/batfish/src/main/java/org/batfish/representation/arista/OspfProcess.java
projects/batfish/src/main/java/org/batfish/representation/arista/OspfRedistributionPolicy.java
projects/batfish/src/main/java/org/batfish/representation/arista/RedistributionPolicy.java
projects/batfish/src/main/java/org/batfish/representation/arista/RedistributionSourceProtocol.java
projects/batfish/src/main/java/org/batfish/representation/arista/RipRedistributionPolicy.java
projects/batfish/src/test/java/org/batfish/representation/arista/AristaConversionsTest.java

Also fix a bug along the way. When redistribution source is VS BGP, then VI sources can be BGP, iBGP, or AGGREGATE.

Arista: Use a VS redistribution source enum

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_trunk.g4
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2_warn

Like for `VLAN` interface references, you can list interfaces or use the `ethernet # to #` syntax, or a combination of both when specifying `trunk` members.

A10: alternate trunk member syntax

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4
projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java

```
3  configs/leaf1.cfg  305             maximum-paths 64  [sbaf_ipv6_unicast sbaf sb_address_family bgp_...  This syntax is unrecognized
```
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

FRR: `maximum-paths` fixes

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_no_redistribute

1. "no redistribute" syntax permits route-map specification (which is ignored by the box). 
2. add tests
3. add missing extractor logic for "no redistribute attached-host"

Arista: BGP no redistribute, route-map variant

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java

It's a valid command like:
```
address-virtual 44:38:39:ff:ff:c8 10.0.0.254/24 10.0.1.254/24
```
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

FRR: Allow more IPv4/IPv6 addresses to be specified for address-virtual

---

projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java

FRR accepts this command without a number as well.
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>
Closes https://github.com/batfish/batfish/issues/7680

FRR: Make `allowas-in <num>` to be optional

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InputValidationUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/InputValidationUtilsTest.java

Previously, all queries for NODE_NAME were considered VALID. Now only matching names are valid, all other queries are NO_MATCH. We could/should distinguish between NO_MATCH and INVALID, but punting on that for now.

validation for NODE_NAME variable type

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Reference.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ReferenceVisitor.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceOrServiceGroupReference.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-namespace
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-rulebase-tracing

* Update security rule conversion to permit references to shared and panorama applications and services
* Split up panorama and shared objects in VS representation (rather than putting all objects in panorama)
* Change ordering of shared and panorama data in many places to prefer panorama
* (Not really an issue until this PR split panorama and shared objects)

PAN: fix application and service references outside current `vsys`

---

projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamilyTest.java
projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java

Fixes #7679 
Added at `router bgp 1` -> `address-family` -> `neighbor ... remove-private-AS`

FRR: Remove private AS support

---

projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/InterfacesInterface.java
projects/batfish/src/main/java/org/batfish/representation/cumulus/OutOfBandConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java

Earlier the address list could be null or empty (which mean the same thing), needlessly forcing a null-check everywhere.

CumulusInterfaces: Make address list non-null

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OriginMechanism.java

- OK to use REDISTRIBUTE for network statements on vendors without an
independent network policy

Update OriginMechanism javadoc

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

No reason to have type 3 and type 5 routes in the same RIB. Also:
- Split combined EVPN delta builder into type 3 and type 5 delta builders
- Remove remaining code queueing EVPN routes for main RIB

Remove combined EVPN RIB

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType2RouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType3RouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType5RouteTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnType5AristaTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

EVPN routes never go in main RIBs, so they should all be nonrouting and
nonforwarding by definition. Hardcoded this in EvpnRoute and disabled
the setters in the builder. Also disabled the admin setter (EvpnRoute
admin was already hardcoded).

EVPN route cleanup: nonrouting/nonforwarding always true

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnType5AristaTest.java

Not sure how we both missed this, but this is why the EVPN route in the test supposedly had originator IP `Ip.AUTO`.

Copy originator IP to EVPN route correctly

---

projects/allinone/src/test/java/org/batfish/question/routes/Bgpv4RoutesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
questions/stable/bgpRib.json
questions/stable/evpnRib.json
questions/stable/routes.json
tests/questions/stable/bgpRib.ref
tests/questions/stable/commands
tests/questions/stable/evpnRib.ref
tests/questions/stable/routes.ref
tests/questions/test_questions.py

RoutesQuestion: Add more match criteria

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java

EVPN import route targets are for importing other VRFs' EVPN routes to the importer's BGPv4 RIB. This code was handling that completely wrong by importing EVPN into the importer's EVPN RIB.

Delete defunct EVPN code

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnToBgpv4VrfLeakConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrfLeakConfig.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnToBgpv4VrfLeakConfigTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrfLeakConfigTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AnnotatedRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AnnotatedRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/BUILD
projects/batfish/src/test/java/org/batfish/dataplane/EvpnType5AristaTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/testconfigs/evpn-type5-arista

Supports EVPN import route targets.
Still to do: Examine and remove infrastructure that leaks EVPN to EVPN via import route targets, which is orthogonal.

Support EVPN to BGPv4 VRF leaking

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java

For some not-completely-understood reason, EVPN backup routes no longer include best routes as of recent PRs. Therefore the question should now include both best and backup routes by default to get the same results.

Include best routes in EVPN routes question

---

projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/bgp_redistribution

We were previously leaving `OriginType.INCOMPLETE` as the origin type for local routes that originated from a `redistribute` statement.

Arista local BGP route origin types based on source protocol

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

- fixes issue where vxlan flood lists are not updated due to missing
`Layer2Vni`s on default VRF.
- always put Layer2Vnis in default vrf
- fix conversion for EOS
- fix enum hashing in Layer2Vni hashCode

Fix Layer2Vni creation and usage

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/EvpnAddressFamily.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

Local EVPN routes don't appear to have any NHIP attached, but when they're sent out, the sender sets their NHIP to the IP of the NVE (Network Virtualization Edge): https://datatracker.ietf.org/doc/html/rfc8365#section-5.1.3
In this PR we add the NVE IP as an attribute of `EvpnAddressFamily`, so every peer sending EVPN routes has an IP to use as NHIP for its local EVPN routes.

EVPN: Use NVE IP as NHIP for originated routes

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

- put `Layer2Vni`s in default VRF following batfish/batfish#7731

Cisco NX-OS fix layer 2 VNIs

---

projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiGatewayCluster.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobj.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiVsxClusterNetobjTest.java

Make `interfaces` optional for other cluster classes

CheckPoint: make cluster interfaces optional

---

projects/batfish/src/main/java/org/batfish/job/ParseResult.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/annotate/Annotate.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationJobTest.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationResultTest.java
tests/basic/example-iptables-init.ref
tests/parsing-tests/unit-tests.ref

For some vendors, configuration information for a device is spread across multiple files. Batfish has used concatenation as a means to turn them into single-file vendors, but concatenation is not a viable strategy for some vendors like SONiC with different file formats (JSON, text). 
This PR extends ParseVendorConfigurationJob to multi-file parsing. It logs file-specific warnings where applicable (e.g., parse warnings). File-agnostic warnings and the overall status is associated with the concatenation of the filenames.  
There is one unresolved gap: VendorConfiguration expects one filename. Here, a "representative" filename is used in this PR. The thinking is that the main file of the vendor will be used for the time being. This will be addressed in a future PR, along with making defined …

Multifile parsing jobs

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server

Support – (`\u2013`) in names.

A10: support unicode dashes

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

For now, assuming that devices only have one NVE, as that seems to be the common case and it is unclear which NVE's source interface address should be used for EVPN NHIPs if there are multiple.

NX-OS: Set NVE IP for EVPN address families

---

projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/trunk_acos2

Static trunk member interfaces may not show up later in configs, at least for acosv2 devices.
So, create them at reference time.

A10: create interfaces that are static trunk members

---

projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/vlan_acos2

Vlan member interfaces may not show up later in configs. So, create them at reference time.
This should only apply to `ethernet` interfaces, `trunk` interfaces will have other configuration that is required to occur elsewhere.

A10: create interfaces that are vlan members

---

projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/server_ref
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/service_group_ref

Reference tracking was already supported; this PR just adds tests for it

A10: test `server` and `service-group` references

---

projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/nat_pool_ref

Reference tracking was already supported; this PR just adds tests for it

A10: test `nat pool` references

---

projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

user-provided layer1 edges do not support filtering by node.
the only use case we care about is getting the entire (canonicalized) layer1 topology,
which can include non-existent nodes. we don't want to filter them out, so the simplest
thing to do is disable filtering.
this is a short-term fix -- may be better to split this out as a separate question

EdgesAnswerer: don't filter user-provided l1 edges 

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java

reachableEdge runs 2 traceroutes. when there are many edges, parallelizing can give a significant speedup

Parallelize prunedVxlanTopology

---

projects/question/src/main/java/org/batfish/question/VIModelQuestionPlugin.java
projects/question/src/test/java/org/batfish/question/VIModelQuestionPluginTest.java
questions/experimental/viModel.json
tests/questions/experimental/commands
tests/questions/experimental/viModel.ref

Developer convenience: when playing with large networks, it is useful to fetch and examine the model for just one node.
Cc: @saparikh

Add a node filter to the viModel question

---

projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPacketLength.java

This effectively only matters for changes to packet-length except, so
really affected nothing. But I noticed.

JunOS: fix typo in FwFromPacketLength

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseStatus.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/ParseResult.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationResult.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/main/annotate/Annotate.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationResultTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
tests/basic/example-iptables-init.ref
tests/parsing-tests/unit-tests.ref

In #7742, ParseStatus was a job-level, not file-level. That has some undesirable side-effects for multi-file jobs, such as, parseStatus question not returning the nodes produces by the file and not being able to report the status separately for files. 
This PR makes ParseStatus file-level. It also make VendorConfiguration class aware of any other files that went into its production, which makes for accurate file to node mapping.

Granular status for multifile parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HasWritableOspfMetricType.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetOspfMetricType.java

- nop if output route has no OSPF metric-type

Fix SetOspfMetric crash on inapplicable routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Names.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java

- each layer-3 VNI results in an interface in the associated VRF
- generated interface:
- responds to ARPs for VTEP address
- has link-local address
Follow-on work: add l3 edges between these generated interfaces based on
VxlanTopology

Add VNI interfaces to tenant VRFs

---

projects/allinone/src/test/java/org/batfish/question/traceroute/TracerouteAnswererHelperTest.java
projects/allinone/src/test/java/org/batfish/question/traceroute/TraceroutePolicyBasedRoutingTest.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/DirectionFilterAstNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ReferenceFilterGroupFilterSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserFilterTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserInterfaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserIpSpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserNodeTest.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersDifferentialTest.java
projects/question/src/test/java/org/batfish/question/traceroute/TracerouteAnswererHelperTest.java
questions/experimental/loopbackMultipathConsistency.json
questions/experimental/subnetMultipathConsistency.json
tests/basic/commands
tests/questions/experimental/loopbackMultipathConsistency.ref
tests/questions/experimental/subnetMultipathConsistency.ref

This is very old, and we don't need to support it anymore.

SpecifierGrammar: Remove some deprecated syntax

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlagsMatchConditions.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/AclLineMatchExprsTest.java

1. Instead of not established, make it affirmatively syn
2. Make it use all tcp bits, so that reachability and other headerspace searches
do not turn other bits on.

AclLineMatchExprs: switch new tcp flows to syn-only

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/flow/BidirectionalTrace.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/flow/BidirectionalTraceTest.java
projects/question/src/main/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswerer.java
projects/question/src/test/java/org/batfish/question/traceroute/BidirectionalTracerouteAnswererTest.java

Sick of fraudulent coverage diffs on unrelated PRs.
Moved the answerer-specific Key into its user rather than leaving it in the
datamodel itself.

BidirectionalTrace: add test coverage

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java

- `next-vrf` -> `vrf`
- matches pattern of other `NextHop` type fields

Fix NextHopVrf serialization type field

---

projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java

Move most FRR-related conversion to its own method (so, it can be shared), and document what should have been done before that method is called. 
Also fix method annotations along the way.

FRR: Factor out conversion

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis

- remove requirement for l2/l3 VNIs to be mapped to some IRB (Vlan)
interface
- remove requirement for layer3-vnis to be associated with a vlan

Cisco NX-OS fix layer-2 and layer-3 VNI instantiation requirements

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv4AccessList.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Ipv4AccessListLine.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco_xr/CiscoXrConfigurationTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/abf_extraction
projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/acl

Supports differential changes to ACLs.

IOS-XR: honor ipv4 acl sequence numbers out of order

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve_vnis

Correction to batfish/batfish#7797
- Layer-3 VNIs *do* need to ba associated with a VLAN
- There also must be an IRB (Vlan) interface for that VLAN in the tenant VRF

Cisco NX-OS fix layer-2 and layer-3 VNI instantiation correction

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java

- remove Layer-3-VNI-associated VLANs from "normal" vlan range on NX-OS
- prevent IRBs associated with Layer-3 VNIs from being shut down for
lack of associated switchports

Cisco NX-OS never disable IRB associated with L3 VNI

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VniLayer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanNode.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopology.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanNodeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TopologyContextTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

- add VniLayer enum to VxlanNode
- only check edges between l2 VNI VxlanNodes when deciding whether to recompute l3 adjacencies
- only use l2 VNI VxlanNodes within computation of l3 adjacencies
- only use l3 VNI edges for computation of l3 edges between generated nve interfaces
- creation of l3 VxlanNodes during data plane computation
- create flood lists for L3 VNIs
- fix flood list calculation for L2 VNIs (remove inapplicable VTEPs)
- surfacing VNI layer in VXLAN topology answer

Split VxlanTopology into layer2 and layer3 VNI nodes

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java

There is no use for equals on this uber structure. Only leads to maintenance overhead each time something is added to the model.

Remove equals from configdb

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java

... from 32. i.e. use 4x more cache than before

BDDPacket: reduce JFACTORY_CACHE_RATIO to 8

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java

This is two changes that can be separated out if desired.
1. Rather than "pushing BDDs to neighbor states" one at a time, instead we stage all the BDDs and `orAll` them into a single new BDD to unioned with the existing reachable set for a state. Using `orAll` saves in computation. It can also push BDDs farther in fewer iterations (if A and B are both dirty, and A->B, and A is processed first, then processing B will handle A's output in this same iteration).
2. Since the newly-learned reachability (overapproximation, since some may be contained in `prior`) is "free", switch to an incremental traversal algorithm. Instead of feeding everything reachable in a state forward, feed only the learned reachability. This seems to converge faster, but induces more garbage collection than 1.

BDDReachabilityUtils: use orAll and traverse incrementally

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Instead, walk over the cache and delete entries for freed BDDs. This is safe since we do it as part of GC, i.e. before any new BDDs are allocate: we know which BDDs are freed vs not.

JFactory: don't flush cache when GC frees BDDs

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/MgmtVrf.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/DeviceMetadataTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/MgmtVrfTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/PortTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java
projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/mgmt/sonic_configs/device/config_db.json

Let child classes decide how they want to handle unknown keys.

Sonic ConfigDb: don't blanket ignore all keys

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer3Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Vni.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VrfMatchersImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/Layer3VniTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusConcatenatedConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java

- remove BUM fields, which are only applicable to `Layer2Vni`s
- add `learnedNexthopVtepIps`, which during dp computation should
contain all next hop vtep ips for the same VNI in the tenant VRF

Fix Layer3Vni datamodel

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NetworkConfigurations.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/PartialDataplane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java
projects/question/src/test/java/org/batfish/question/vxlanproperties/VxlanVniPropertiesAnswererTest.java

- each iteration, update `Layer3Vni`s' learned VTEP IPs based on next
hop VTEP routes in the main RIB with the same VNI
- construct VXLAN edges between for each Layer3Vni pair containing each
other's source IP in their learned VTEP IPs

Produce VXLAN edges from type-5 routes

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/NextHopComparator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/NextHopComparatorTest.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowSecondaryKey.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
tests/basic/routes-dc-as-reuse.ref
tests/basic/routes-diff.ref
tests/basic/routes.ref

- add `Schema.NEXT_HOP`
- populate `COL_NEXT_HOP` using modern `NextHop` route attribute

Add NextHop column to Routes answerer

---

projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/frr/Frr_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java

Because `bgp` can occur at the top-level (not just under router bgp), and brings things in like with frr/ospf from a naming standpoint. 
No functional change.

Frr: Rename router bgp rules

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Sets dedupe equal BDDs, so do not free if alternate paths produce the same BDD
twice. ECMP, for example.

BDDReachabilityUtils: correctly free duplicated intermediate BDDs during traversal

---

projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrParser.g4
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Tacplus.java

1. Add more ignored tables
2. Allow for FRR files starting with newlines
3. Ignore unknown properties in TACPLUS
4. Catch deserialization failures of a TABLE; log warning and do the rest.

Sonic: Reduce warnings

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/LegacyNextHops.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowAttribute.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowSecondaryKey.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java

1. Move the ability to get legacy next hops from NextHop out into a common
utility.
2. Remove redundant information in RouteRowSecondaryKey.
3. Fixups.
Note no refs changed.

Routes: cleanup internal state

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclTable.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/AclTableTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java

Based on new data:
- Add support for LOOPBACK table
- New `type` in ACL_TABLE
- Add two new fields in ACL_TABLE (ignored for now)
- Add more ignored top-level configdb fields

Sonic: More parsing

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vrf_invalid

Adds support for both `no vrf member FOO` and `no vrf member` in interface context. The former will generate a warning if the current interface is not in the specified VRF (in which case the command has no effect).

NXOS: Support unsetting VRF in interface

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDDState.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferParam.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/AsPathMatchExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunityAPDispositionsTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Previously there was one statically created BDDFactory shared across all uses of SearchRoutePolicies.  If many route policies are analyzed this could eventually cause Batfish to run out of memory.  Now we create a separate BDDFactory instance for the analysis of each routing policy, which is done by instantiating the factory inside the constructor for TransferBDD.

SearchRoutePolicies: Don't share a single BDDFactory

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor

Adds support for removal of BGP neighbors via `no neighbor` command, including all permutations of:
- Active or passive
- IPv4 or IPv6
- Inside or outside of VRF context
- With or without remote AS specified

NXOS: Support removing BGP neighbors

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_nve_vnis

- relax condition for VXLAN autostate whitelist for vlans to any vlan
associated with a vn-segment
- previously, vlan had to be associated with layer-3 VNI

Cisco NX-OS IRB associated with vn-segment should be up via autostate

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route

This was already supported for static routes in the default VRF, and the extraction method used for the `no_ip_route` rule already removes from `_currentVrf` rather than the default VRF, so all that was needed was to add that rule in the `no ip` rule for VRFs.

NXOS: Support removing static routes in VRF context

---

projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java
projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesQuestion.java
projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/vrrpproperties/package-info.java
projects/question/src/test/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswererTest.java
questions/experimental/vrrpProperties.json
tests/questions/experimental/commands
tests/questions/experimental/vrrpProperties.ref

And add active interface column and improve column descriptions.

VRRP question: Filtering by address

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Also fix a variety of small things:
* remove ability to control max number of nodes or maximum node increase
* don't resize if requesting same number of nodes as before
* delete some old debugging code
* remove unused and undefined return codes for resize-related functions

BDDFactory: cap resizing at maximum allocatable

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Vrf.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/cisco_nxos/StaticRouteTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_static_route

In NX-OS, two static route definition lines will only result in different routes if key properties (prefix or next hop info) differ. For example, these two lines will create different routes:
```
ip route 10.0.1.0/24 10.0.1.1
ip route 10.0.1.0/24 Ethernet1/1 10.0.1.1
```
But these two lines will result in one route with the properties listed in the second line:
```
ip route 10.0.15.0/24 10.0.1.1
ip route 10.0.15.0/24 10.0.1.1 track 500 name foo tag 1000 5
```
Additionally, a `no ip route` command will remove the route with the specified key properties, ignoring any other properties on the route or in the `no` command, so the second line here will work:
```
ip route 10.0.1.0/24 10.0.1.1 track 500 tag 10
no ip route 10.0.1.0/24 10.0.1.1 name foo tag 1000 5
```
Batfish currently creates a …

NX-OS: better handling for `[no] ip route`

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ospf

Adds support for OSPF `no redistribute`. On NX-OS, `redistribute` commands must specify a route-map. The `no redistribute` version does not have to specify a route-map, but if it does, the route-map has to match the redistribution policy being removed.

NX-OS OSPF: Support `no redistribute` commands

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

- do not consider an open brace following a quote to be evidence for nested
- use case: string literal of flat JSON object

Palo Alto format detector add brace ignore heuristic

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/VrrpGroup.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/VrrpComputationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VrrpGroupTest.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/job/BUILD
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConversionTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/cluster_member
projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java
projects/question/src/test/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswererTest.java

- add support for separate VRRP over sync interface
- Sync interface participates in election
- When the sync interface is elected, IPs are assigned to one or more
interfaces
- Implement VRRP over sync interface for CheckPoint
- On all vendors that use real VRRP, each interface that receives IPs
is its own sync interface
- refactor VRRP computation in `IpOwners` to remove `IdenityHash{MapSet}` usage.
Follow-on work: Convert A10 to use sync interface for VRRP(-A)

Support VRRP over sync interface, and implement for Checkpoint

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

These are unique to EOS after being required to differentiate from Cisco.

VendorConfigurationFormatDetector: detect new Arista syntax

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackMethodVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackRoute.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/TrackRouteTest.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/TrackIpRoute.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_static_route_track
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_conversion
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn

- add `TrackRoute` `TrackMethod` to datamodel
- supports matching a route in a main RIB based on:
- prefix
- vrf
- optionally, matching one of a set of protocols

Cisco NX-OS parse and convert track ip route

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java

Incoming filter is applied to traffic that arrives at the interface, while inbound filter is (supposed to be) applied to traffic destined for an address owned by the interface.

Sonic: Set incoming filter, not inbound filter

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/implicit-init-interface

Under some conditions (see test file) BF automatically creates interfaces. Prior to this PR, when such an interface was a sub-interface, it was not being properly linked to its parent. In particular, the parent's units map had the sub-interface but the sub-interface did not have the parent configured. The partial linking was later preventing the parent from being set and then causing an NPE.

Junos: Proper linking of implicitly created interfaces

---

projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_switchport

Previously, if no allowed VLANs were specified for an interface in trunk mode, we allowed the full valid range (1-4094). Actually it should default to all active declared VLANs.
Similarly, if allowed VLANs are specified, any that are not active declared VLANs should be ignored.

NX-OS: Trunk interfaces' allowed VLANs must be active

---

projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPort.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourcePort.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromDestinationPortTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromSourcePortTest.java

For Junos firewall conversions, BF was assuming TCP/UDP when source/destination port filters were used. But SCTP has ports too, so expanding the set of possibilities.

SCTP has ports too

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDOps.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDFlowConstraintGeneratorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDOpsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/HeaderSpaceToBDDTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java

* Kill andNull: all users of it were using it for the "I don't need a Factory" reason,
not the "I want null returned" reason.
* Move null-handling into HeaderSpaceToBDD, the only user
* Move all and- and or- operations on to andAll or orAll respectively

BDDOps: cleanup and make efficient

---

projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_show_all_2
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_interface_switchport

The CLI will allow you to configure access VLANs that are inactive or not configured.

NXOS: access VLANs must be configured & active

---

projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java

In large networks, the gains from parallelism are likely much larger
than the gains from BDD Reuse.

FilterLineReachabilityAnswer: parallelize

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/hsrp/HsrpGroup.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackMethodVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackTrue.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/StaticRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluatorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/tracking/TrackTrueTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluatorTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_conversion

- remove references to undefined tracks in:
- HsrpGroup
- StaticRoute
- fixes NPEs on evaluation of undefined tracks
- add TrackTrue as placeholder implementation for unsupported tracks
- use in NX-OS to avoid extra warning for removal of undefined track
- use TrackTrue to simplify existing evaluator tests

Remove references to undefined tracks in post-processing

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedByIpAccessLists.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedOnDevice.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/SourcesReferencedOnDeviceTest.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java

SourcesReferencedByIpAccessLists does not capture packet policy or transformation.
Sometimes, we need everything.

SourcesReferencedOnDevice: a variant of SourcesReferencedByIpAccessLists for the device

---

projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConversionTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/vrrp_e2e/A10HaTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/vrrp_e2e/A10VrrpATest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/vrrp_e2e/BUILD
projects/batfish/src/test/java/org/batfish/vendor/a10/vrrp_e2e/package-info.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/ha_acos2
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/vrrp-a-enabled
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/BUILD
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/ha/batfish/layer1_topology.json
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/ha/configs/r1
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/ha/configs/r2
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/vrrp_a/batfish/layer1_topology.json
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/vrrp_a/configs/r1
projects/batfish/src/test/resources/org/batfish/vendor/a10/vrrp_e2e/snapshots/vrrp_a/configs/r2

- Install `VrrpGroup`s only on sync interfaces
- Winner should install IPs on all other L3 interfaces

A10 fix VRRP conversion between sync and IP owner interfaces

---

projects/question/src/main/java/org/batfish/question/hsrpproperties/HsrpPropertiesAnswerer.java
projects/question/src/main/java/org/batfish/question/hsrpproperties/HsrpPropertiesQuestion.java
projects/question/src/main/java/org/batfish/question/hsrpproperties/HsrpPropertiesQuestionPlugin.java
projects/question/src/main/java/org/batfish/question/hsrpproperties/package-info.java
projects/question/src/test/java/org/batfish/question/hsrpproperties/HsrpPropertiesAnswererTest.java
questions/experimental/hsrpProperties.json
tests/questions/experimental/commands
tests/questions/experimental/hsrpProperties.ref
tests/questions/test_questions.py

- copied from VRRP properties question, except:
- slightly simpler implementation for populating virtual addresses in answer due to simpler model
of HsrpGroup vs VrrpGroup

Add HSRP properties question

---

projects/batfish-common-protocol/BUILD

Fixes warnings about java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

common_tests: add missing dependency

---

projects/batfish-common-protocol/src/test/java/org/batfish/storage/TestStorageProvider.java

- allow subclasses in tests to throw exceptions from StorageProvider signatures

Fix exception signatures in TestStorageProvider

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1TopologiesFactory.java

This removes logspam in the common case of case corrections.

canonicalizeLayer1TopologyNodes: reduce log level on case fix

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java

New method that returns a stream of entries matching an input RangeSet of IPs.

PrefixTrieMultiMap: getOverlappingEntries

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/SymbolicAsPathRegex.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/SymbolicRegex.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/RegexAtomicPredicatesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/SymbolicAsPathRegexTest.java

Addresses two problems in SearchRoutePolicies for handling AS-path regexes from Juniper devices:
* Previously the \d character class for digits was not handled properly.
* A recent update to parsing for Juniper AS-path regexes introduces the possibility of having two start-of-string ^ characters in a row, which requires special handling.

SearchRoutePolicies: handle the Java regex format for Juniper AS-path regexes

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/CompletionMetadata.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/answers/AutoCompleteUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java

This will allow us to support sets of Ips (within a prefix) efficiently.

CompletionMetadata: migrate Ip completion metadata onto PrefixTrieMultiMap

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1TopologiesFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer1TopologiesFactoryTest.java

This resolves fake ambiguity when the same unknown external interface
is present in L1 with different case.

Layer1TopologiesFactory: canonicalize unknown nodes to lowercase

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-crypto-map-pfs-dh-group

Cisco IOS Fix missing extraction case for pfs group20

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/IpCompletionMetadata.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/autocomplete/IpCompletionMetadataTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

For subnets, add IpCompletionMetadata for the subnet's prefix to the trie. To handle excluded IPs (i.e. network/broadcast and owned IPs), add a RangeSet of the IPs within the prefix that share the relevances.

IpCompletionMetadata: add connected subnet IPs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/visitors/IpSpaceToRangeSetTest.java

We sometimes use IpWildcards and IpWildcardSets that are/contain prefixes. Add support for converting these to RangeSets.

IpSpaceToRangeSet: support IpWildcards that are prefixes

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java

- recompute HMM routes each dataplane iteration to reflect the result of mid-dataplane changes in VRRP winners
- only use initial L3 topology to avoid creating HMM routes from neighbors over VXLAN tunnel

Recompute HMM routes each dataplane iteration

---

projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ha.g4
projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Ha.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConversionTest.java
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/ha_acos2
projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/vrrp-a-enabled

- create `TrackMethods` for server health-check pointing to valid health monitor
- create `TrackActions` in generated `VrrpGroup`s
- from ha check gateway
- decrement 255 from priority
- from vrrp-a fail-over-policy-template check gateway
- applied to vrrp-a vrid referencing fail-over-policy-template
- decrement VRRP priority as indicated
- Should have a way of disabling VRRP participation entirely rather than
just decrementing priority. This makes a difference when there is only
one candidate to begin with in the election.

A10 support check gateway for ha and vrrp-a

---

projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

Introduce exist_rec, a version of quant_rec specialized to existential
quantification that uses orAll_rec to save intermediate work.
Also plug exist_rec into braindead places in appex (relprod_rec /
appquant_rec).

JFactory: rewrite BDD#exist using orAll

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

Observationally, this speeds up graph construction dramatically and
does not negatively impact traversal.

PacketPolicyToBdd: break up long policies

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java
projects/batfish/src/test/java/org/batfish/dataplane/BUILD
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/a10-kernel-routes/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/a10-kernel-routes/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/a10-kernel-routes/layer1_topology.json

- fix but where kernel routes depending on ip ownership do not take into account IpOwners changing mid dataplane

Recompute kernel routes every dataplane iteration

---

projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
tests/parsing-tests/example-juniper.ref
tests/parsing-tests/unit-tests.ref

This PR makes two small changes to inferring local Ip for BGP neighbors:
1. Make sure that the neighbor is in the same VRF as lo0 (default)
2. Do not pick 127.0.01

Junos: Check VRF when using lo0-based BGP local IP

---

projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/Parser.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledLocationSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParserLocationTest.java

Previously we were not returning the correct Ast type, causing parse errors for these valid specifiers.

ParboiledLocationSpecifier: handle internet[iface] locations correctly.

---

projects/question/src/main/java/org/batfish/question/filterlinereachability/FilterLineReachabilityAnswerer.java

Parallelizing the computation of unreachable lines is enough, and this prevents
an apparent non-determinism in the output when multiple row additions were
called in parallel.

FilterLineReachabilityAnswerer: only add to answer sequentially

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer2Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Layer3Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/Vni.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/topology/TopologyProviderImpl.java
projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosOneSidedTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis-one-sided/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis-one-sided/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis-one-sided/hosts/h1.json
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis-one-sided/hosts/h2.json
projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis-one-sided/layer1_topology.json
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

- consider pair of `Layer3Vni`s compatible if either has learned the source IP of the other
- no longer require both
- if we really want to implement unidirectional tunnels, it must involve more than one generated
interface per (vrf,vni) (or modeling encapsulation. etc.)
- move computation of learned IPs to topology scope right before computation of next partial data
plane
- ensures main RIB has settled and all vrf leaking is complete
- only compute once per topology iteration rather than once per dependent routes iteration
- clean up API and documentation of `VxlanTopologyUtils`

Fix computation of Layer3Vni tunnels for one-sided routes

---

projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java

BDD library instrumentations need to be able to accurately distinguish public
and internal API calls. `BDD#free`, since it changes the BDD object rather than
library internal state, seems to be the unique public API called internally
during the evaluation of other operations (specifically `opWith` or
`opAndFree`).

BDD: add an internal implementation of free

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibForward.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockFib.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java
projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java
tests/basic/traceroute-1-2.ref

- Fix bug where dest IP showed up as arp IP for neighbor unreachable
when the interface had no neighbors.
- To ensure we always display real arp IP, remove pathways for `Route.UNSET_NEXT_HOP_IP` to make it
into `FibForward.getArpIp`.
- make `FibForward.getArpIp` optional, and disallow `Route.UNSET_NEXT_HOP_IP`.
- Fix bugs and cruft encountered while updating `FibImpl` to use new `FibForward` API
- Ensure every `Rib` entry results in at least one `FibAction`
- Make sure unresolvable or looping NextHopIp routes result in `FibNullRoute`, instead of
silent missing `FibEntry`s
- Remove unnecessary loop duplicating `Rib.longestPrefixMatch` filtering of non-forwarding routes
- Ensure non-forwarding routes are never part of the resolution chain
- Remove unused parameters not caught because the …

Fix arpFailureTrace IPs, plus FibImpl and ForwardingAnalysis fallout

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/CompletionMetadataUtilsTest.java

For consistency with source IP specifiers.

CompletionMetadata: exclude p2p prefixes for @enter locations

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java

- Allow `DELIVERED_TO_SUBNET` and `EXITS_NETWORK` dispostions for forward flow in addition to
existing allowed disposition `ACCEPTED`

Allow all success dispositions for reachability track forward flow

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java

So that clearing it in VirtualRouter can do the right thing.

IBDP: also free handle to Fib

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java

If many routes are received from the same neighbor,
all of them will share the same attributes.
Save (possibly a lot of) RAM in such cases.
On one smallish network, results after computing the dataplane:
Before:
1250631 BgpRoute objects, 104 bytes each, 130M RAM
After:
1250631 BgpRoute objects, 48 bytes each, 60M RAM
148124 BgpRouteAttribute objects, 80 bytes each, 11.M RAM
This seems like the sweet spot, at least in this network. If we move
receivedFromIp up to BgpRoute, it reduces to about 117K BgpRouteAttribute
objects, but the additional overhead on BgpRoute is not worth it.
1250631 BgpRoute objects, 56 bytes each, 70M RAM
117000 BgpRouteAttribute objects, 72 bytes each, 8.4M RAM
There may be networks where this additional move is beneficial, e.g.,
high ECMP and ASN reuse (so AS Paths …

BgpRoute: move properties into interned class

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequence.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/StatementVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequenceTest.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_routemap.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java
projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceSequenceLine.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/route-map-set-as-path-replace
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java
projects/question/src/main/java/org/batfish/question/TracingHintsStripper.java

Fixes batfish/batfish#8059
- parse and convert route-map statement `set as-path replace`
- add new VI Statement for replacing elements of an as-path
- for now, just support replacing with local-as
- On IOS, should use confed insetad of local-as if in confed and neighbor is not in the confed

Cisco IOS implement route-map set as-path replace

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/VniMatchersImpl.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java

- Fixes batfish/batfish#8061
- Multicast-groups are not supported for BUM traffic on EOS up to at least 4.23
- They are only for BM traffic, and should not displace unicast VTEPs
- Even on 4.25 which apparently allows multicast VTEPs, they are not configured
via the `multicast-group` command.

Arista EOS do not treat vxlan multicast-groups as VTEPs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/plugin/IBatfishTestAdapter.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/IpOwnersBaseImplTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/VrrpComputationTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataPlaneIpOwners.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackRouteUtils.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/topology/PreDataPlaneIpOwners.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/FixedPointTopologyTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/RouteReflectionTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/schedule/NodeColoredScheduleTest.java

- add APIs and implementation for recording of detailed HSRP/VRRP election data
- factor out route and reachability tracking code so it may be used by post-dataplane clients
- remove VRRP references to undefined track methods in post-processing

Add support for recording HSRP/VRRP election data

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/static-route-convert-warnings

Fix an issue where a `static-route` missing a `nexthop` would cause conversion crash.

PAN: fix `static-route` conversion crash

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java

- no longer needed since downstream usages have been removed

Remove IpOwnersBaseImpl extra constructor

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ip_access_list.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_access_list_invalid

- make `acl_action` choice LL(1)
- fixes recovery failure when adaptive prediction fails deeper than `acl_action`

Cisco NX-OS fix recovery issue with ACL parsing

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_interface_show_run_all

EOS: extract 25gfull

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_device_group.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_profiles.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_shared.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/CustomUrlCategory.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoStructureType.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Vsys.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/panorama-profiles
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/profiles
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/profiles-reference
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/profiles-warning

`custom-url-category` can be applied to security rules or url-filtering profiles. Neither of those are supported yet, but will add support for attaching to security rules in a subsequent PR.
----
Note: there are some other `profiles` that are no longer parsed and ignored, which may result in more unrecognized-line parse warnings.

PAN: parse and extract `custom-url-category`

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/IpCompletionMetadata.java

Building a set via a list is very expensive - quadratic containment check.
Using a LinkedHashSet gives us list order and set semantics cheaply.

IpCompletionMetadata: quadratic to linear

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java

TreeRangeSet::removeAll does not optimize for the span() of the set
from which elements are being removed. Simplify the code and reduce
runtime. This basically turns O(n) into O(log n) work, where n can
be very large (# owned IPs in the network).

CompletionMetadataUtils: remove performance bottleneck

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/profiles-warning

URL category wildcards have an unexpected behavior where a wildcard URL like `*.github.com` will match `www.github.com` as well as something like `www.github.com.malicious.example.com`.
Add parse warning when URL categories like this are encountered.

PAN: detect and warn about potentially unintended URL wildcard behavior

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java

1. Don't expose internal nodes (nodes for branching, but with no data)
2. Don't let users initialize an internal node
3. Clean up all the tests.
I was unable to come up with a reason internal nodes need to be visible to
callers, and it seems confusing -- otherwise, naive users will think that
internal nodes always have data.

PrefixTreeMultiMap: sensible public API

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish/src/main/java/org/batfish/allinone/bdd/main/ReplayBDDTrace.java
projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TracingFactory.java
tools/BUILD

TracingFactory is an adapter to JFactory that traces its
operations, and then is able to save and replay these traces.
This enables, e.g., reproducible experimentation on BDD engine
changes and accurate identification of performance bottlenecks
and workload characteristics.

BDD: introduce TracingFactory

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/firewall-application-services

Juniper SRX parse and warn security policy then permit application-services

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_profiles.g4
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines

Ignore more unused `profiles`; cuts down on the number of parse warnings.

PAN: ignore more profiles

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java

This was introduced in batfish/batfish#7741 to replace 3 transient booleans.
The problem: transient boolean almost certainly deserializes as false,
while transient class deserializes as null. So before we were not crashing
because values were just false; now they are null and crashing is happening.
Easiest fix seems to be to simply keep the settings around.

Warnings: remove transient from Settings, fix possible NPE

---

projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationJobTest.java

Add it to the unsupported list, and add a test that would have caught this.

ParseVendorConfigurationJob: do not crash on unsupported configuration format

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedByIpAccessLists.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/SourcesReferencedOnDevice.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/SpecifierUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDSourceManagerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/acl/SourcesReferencedOnDeviceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/SpecifierUtilsTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactory.java
projects/batfish/src/main/java/org/batfish/main/ReachabilityParametersResolver.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisSessionFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseTransformationRangesImplTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/main/ReachabilityParametersResolverTest.java
projects/question/src/main/java/org/batfish/question/FilterQuestionUtils.java
projects/question/src/main/java/org/batfish/question/differentialreachability/DifferentialReachabilityAnswerer.java
projects/question/src/main/java/org/batfish/question/searchfilters/SearchFiltersAnswerer.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererDifferentialTest.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersDifferentialTest.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersTest.java

It is common in Batfish to want to distinguish whether an interface
* is active and L3
* can originate IP (v4) traffic
* can receive IP (v4) traffic
* can send IP (v4) traffic
However, the various logic around this is scattered and inconsistent. For example, traceroute would not let flows
enter L2 interfaces, but reachability and searchFilters would if they were active.
1. Create `Interface` helpers `isActiveL3`, `canOriginateIpTraffic`, `canReceiveIpTraffic`, `canSendIpTraffic`, with
our current rules.
2. Reify Enter/SourceInterfaces with only interfaces that can receive traffic
3. Reify ExitInterfaces with only interfaces that can send traffic
4. Ensure that only interfaces that `canOriginateIpTraffic` are used as origination points.
and fix up some tests.

Unify and standarize enter/exit/l3 interface configuration

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java

Fix a bug where categories weren't copied during vsys inheritance (e.g. for Panorama managed firewalls).

PAN: fix Panorama categories

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_rulebase.g4
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ignored-lines

Parse and ignore `source-hip any` and `destination-hip any`, like we do already for `hip-profiles`.
[HIP profiles](https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-web-interface-help/policies/policies-security/building-blocks-in-a-security-policy-rule.html) aren't used in Batfish's model.

PAN: parse `source-hip` and `destination-hip`

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/ColumnFilter.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/AnswerRowsOptionsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/ColumnFilterTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java

The default behavor of substring matching is preserved.
Some use cases, however, call for exact matching. Enable this, and additionally
be graceful in whether the user is supposed to know exactly how JSON strings are
stringified.

ColumnFilter: allow exact matching

---

projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java

Downstream code generates spurious warnings when addNeighbor is called for peerGroup neighbors.

Frr: Do not call addNeighbor on peer group neighbors

---

projects/allinone/BUILD

Now that most of the unmaintained and untested bits have been excised,
we can take a real dependence on it.

bazel: include minesweeper in default target

---

projects/build-tools/src/main/resources/org/batfish/owasp/suppressions.xml

This is not an issue to be concerned about. The current supposed fix is worse
than the issue itself. (Fixed limit that can't be overridden!)

owasp: suppress CVE-2020-36518

---

projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/test/java/net/sf/javabdd/regression/R3.java

The default toString implementation is slow and can take arbitrary amounts of RAM.
Rename it to toReprString() and add a simplifed toString.

BDD: simplify toString

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/BUILD
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinitions.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/BUILD
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Port.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/UseApplications.java
projects/batfish/src/main/resources/org/batfish/representation/palo_alto/application_definitions/BUILD
projects/batfish/src/test/java/org/batfish/representation/palo_alto/BUILD
projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinitionTest.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/BUILD

Add new VS datamodel representation for Palo Alto applications.
----
Will separately:
1. plumb the new representation into conversion & remove the old representation
2. add a script / instructions for updating these.

PAN: revamp application definitions

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java
projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinitionTest.java

Add icmp type field under `default` for application definitions in the updated Palo Alto application datamodel.

PAN: icmp type in new application datamodel

---

projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cumulus_nclu/CumulusNcluConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_nclu/CumulusNcluGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_structured/F5BigipStructuredGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/eos-port-channel
projects/batfish/src/test/resources/org/batfish/grammar/cumulus_nclu/testconfigs/cumulus_nclu_vrf_references
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_imish/testconfigs/f5_bigip_imish_ospf
projects/batfish/src/test/resources/org/batfish/grammar/f5_bigip_structured/testconfigs/f5_bigip_structured_vlan
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-range
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/paloalto_vlan_tunnel_units
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

- Update verifyInterfaces to:
- disable VLAN interfaces without vlan set
- disable members or children of members of an aggregate/redundant interface that have L3 settings
- remove undefined aggregate dependencies
- remove interfaces with undefined bind dependencies
- Fix conversion on various vendors to avoid interfaces being disabled in verifyInterfaces
Differences from original PR batfish/batfish#8174:
- `CumulusNcluConfiguration`:
- Instead of removing bonds with invalid slaves, just don't add invalid slaves
- prevents undefined BIND dependency on bond subinterfaces
- Also consider slave used for BGP unnumbered as invalid slave
- Remove accidental extraneous interface disabling code

Enforce more interface invariants (attempt 2)

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDDomain.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

BDDRoute was using BDDDomain and BDDFiniteDomain, which are currently similar but will soon diverge. Standardize on BDDDomain.

Migrate BDDRoute off BDDFiniteDomain

---

projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/main/java/org/batfish/main/Batfish.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationJobTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java

Prep for supporting more SONiC file types (snmp.yml, resolve.conf)
1. Batfish allows more than two files in the SONiC device bundle
2. Parser detects the type of each file based on filename, which should end with the well-known name string (config_db.json, snmp.yml,...). For backward compatibility, the old content-based detection is used as a fallback when there are only two files present. 
No processing of additional files is added in this PR.

SONiC: Setup for more file types

---

projects/batfish/src/main/java/org/batfish/representation/frr/FrrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java

DNS servers cannot be configured in FRR. Batfish had vestiges probably from Cumulus NCLU.

Frr: Remove DNS servers

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyPathApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/GroupTreeBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InitialTreeBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/PreprocessJuniperExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/WildcardApplicator.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-groups-chain
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-wildcards

Downstream processing distinguishes between wildcards and text, and
e.g., only allows apply-path to expand text. Since wildcards are only valid
inside `set groups` (or nested inside `policy-options prefix-list PL apply-path`,
but that is handled elsewhere) we can treat them as text everywhere else.

JunOS: only allow wildcards inside of groups

---

projects/batfish-common-protocol/src/main/java/org/batfish/grammar/FileParseResult.java
projects/batfish/src/main/java/org/batfish/job/ParseResult.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationResult.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationJobTest.java
projects/batfish/src/test/java/org/batfish/job/ParseVendorConfigurationResultTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractorTest.java

Following up to #8180, this PR moves most sonic-specific parsing logic to its extractor and changes its interface to be independent of number and types of files. This required moving the previously-internal FileResult class to outside of ParseVendorConfigurationJob. 
No functional change in this PR.

Sonic: Move parsing logic inside its extractor

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java

- Use the field rather than re-calling it.
- Fix caching with MemoizedIpSpaceToBDD (needs to go through visit)

BDDReachabilityAnalysisFactory: minor cleanup

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ResolveConfTest.java
projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/resolve_conf/sonic_configs/device/config_db.json
projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/resolve_conf/sonic_configs/device/frr.conf
projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/resolve_conf/sonic_configs/device/resolve.conf

Sonic: Deserialize and convert resolve.conf

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfArea.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java

- remove references to undefined interfaces in OSPF areas during `finalizeConfiguration`

Verify interface references in OSPF areas

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-path-from-apply-groups-no-match
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-path-mixed-ip-and-not-ip-or-prefix
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-path-no-match
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-path-no-match-not-ip-or-prefix

- only generate lines for matches that end in IP or Prefix
- don't crash otherwise

Juniper fix apply-path

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java

Enables outsiders to get the potential source interfaces used to establish BGP sessions.

BgpTopoUtils: Split source IP inference

---

projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java
projects/batfish/src/test/java/org/batfish/vendor/a10/representation/A10ConversionTest.java
tests/basic/init-candidate.ref
tests/basic/init-with-ba.ref
tests/basic/init.ref
tests/parsing-errors-tests/recovery-no-verbose.ref
tests/parsing-tests/unit-tests.ref

After batfish/batfish#7217, this can be inferred dynamically. May not be a bug.
- batfish/batfish#7217

BGP: remove warning about static update-source inference

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MemoizedIpSpaceToBDD.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceCanContainReferences.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MemoizedIpSpaceToBDDTest.java

BDDPacket has MemoizedIpSpaceToBDD instances for src/dst IpSpaces that have no IpSpaceReferences. With this PR, the
per-node instances will delegate to those for IpSpaces that cannot contain references (recursively). This will reduce RAM
usage caused by caching IpSpaces multiple times and improve performance by using cached results more.

MemoizedIpSpaceToBDD chaining

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_acl.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_no_ip_prefix_list

Also rewrite grammar a little bit
commit-id:f8a1c497

Arista: support deleting individual prefix-list seqs

---

projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpProcess.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

Arista: support deleting BGP peer groups

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Arista_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/eos/AristaBgpV6Neighbor.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_bgp_neighbors

1. Implement delete neighbor for IPv4 neighbors.
2. Add warnings around improper deletions.

Arista: implement neighbor deletion and add warnings

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceKeyProperties.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/L3Interface.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/InterfaceKeyPropertiesTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/L3InterfaceTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java

Before this PR, Batfish was 
1/ ignoring all properties associated with interface keys like 'Ethernet|1.1.1.1/24'
2/ recording only one address per interface
This PR fixes these issues and removes special handling of properties inside MGMT_INTERFACE table.

Sonic: Support for secondary interface addresses

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_ip_access_list.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_ip_access_list

Fixes https://github.com/batfish/batfish/issues/8264

NXOS: Allow ICMP ACL lines without l4 options

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map-set-extcommunity-rt

Both GA and LA can be 16-bit or 32-bit, as long as they aren't both 32-bit.
See ExtendedCommunity#target for how this is signaled on the wire.
Fix batfish/batfish#8266.
commit-id:4d8b2632
- Fix batfish/batfish#8266

IOS: fix parsing of rt extended communities

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_mpls.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/mpls_references

Though MPLS is not supported at all, it's worth getting reference tracking
correct.
Fix batfish/batfish#8274
commit-id:e63b9eb0
- Fix batfish/batfish#8274

IOS: parse and reference standard ACLS in mpls ldp password required for

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPairingFactoryTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BUILD
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/BUILD
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java

Transitions.or is a smart factory method that simplifies/optimizes the input set of disjuncts. Add a case for the Transform transitions, merging any that transform the same set of variables.

Transitions.or: merge Transforms when possible

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/test/java/org/batfish/bddreachability/PacketPolicyToBddTest.java

We insert extra states to break up long chains of packet policy statements, which improves graph building time, but adding too many extra states can slow down traversal time.  Converting individual statements may insert new statements anyway. When that happens, restart the count so we don't insert more states than necessary.

PacketPolicyToBdd: improve statement chunking logic

---

projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java

PacketPolicyToBdd now creates many parallel edges, which previously were being returned directly, and later merged by repeatedly merging two edges using Transitions::or in BDDReaachabilityUtils::computeForwardEdgeTable. Now it accumulates all parallel edges into lists and makes one call to Transitions::or, which is more efficient.
We could do the same thing in computeForwardEdgeTable, but parallel edges are rare outside of PacketPolicyToBdd, so that might not be a win.

PacketPolicyToBdd: merge parallel edges

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpActivePeerConfig.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java

Help users debug ISP configuration, and also document current gaps, which
we are in the process of fixing.

IspModelingUtils: add explanations when ISP-side generation fails

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/PrimedBDDInteger.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPairingFactoryTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java

getPair caches the BDDPairings it creates to improve cache performance of BDD::replace. Previously, this cache was sensitive to the order of the oldvars/newvars arrays, which is sensitive to the order in which BDDPairingFactory objects are composed.
We now use an unordered set of BDDVarPair objects as the cache key. This allows us to simplify BDDPairingFactory and Transform.

BDDFactory: make getPair cache insensitive to order of variables

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java
projects/bdd/src/main/java/net/sf/javabdd/BDD.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/main/java/net/sf/javabdd/TracingFactory.java

Shorthand for x.applyEx(rel, BDDFactory.and, vars).replace(pair), where
1. vars is a varset BDD representation of the codomain of pair
2. pair maps each variable in its domain to the variable one level higher.
Use case: rel represents a relation (multi-valued or nondeterministic function) as a constraint over unprimed and and primed variables (unprimed variables represent inputs and primed variables represent outputs), x represents a set of values as a constraint over unprimed variables, and pair maps the primed variables to their corresponding unprimed variables. x.transform(rel, pair) returns the image of x under rel, i.e. the set containing all possible results of apply rel to a value in x, represented as a constraint over unprimed variables.

BDDFactory: add transform operator

---

projects/allinone/src/test/java/org/batfish/e2e/isp/IspModelingTest.java
projects/allinone/src/test/resources/org/batfish/e2e/isp/basic-bgppeerinfo-implicit/batfish/isp_config.json
projects/allinone/src/test/resources/org/batfish/e2e/isp/basic-bgppeerinfo-implicit/configs/border1.cfg
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/BgpPeerInfo.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/isp_configuration/BgpPeerInfoTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/isp_configuration/IspConfigurationTest.java

During ISP modeling, we need to generate correct ISP-side BGP configuration.
This requires, in particular, specifying the neighbor on that side -- aka,
the local IP on the node in the snapshot. This is usually configured via
an explicit update source or local address command, but may not always be.
To support ISP modeling for these cases, we:
1. provide a way to force local IP in the BgpPeerInfo
2. improve default local IP inference to include local
connected routes (same VRF) for eBGP singlehop sessions.

IspModeling: enable not-configured local IP for BgpPeerInfo

---

projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaDynamicSourceNat.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista-dynamic-source-nat

Arista: handle undefined references in dynamic source nat

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDSourceManager.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDFiniteDomainTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java

BDD performance is sensitive to variable order, so allowing variables to be allocated
before packet header variables can be important. In particular, the finite domains used
by BDDSourceManager and BDDOutgoingOriginalFlowFilterManager should be before the header
variables (if possible).

BDDPacket: support allocating variables before packet header variables

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFiniteDomain.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpAccessListToBdd.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/IpAccessListToBddTest.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManager.java
projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactory.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDMultipathInconsistencyTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDOutgoingOriginalFlowFilterManagerTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/SessionInstrumentationTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/AddOutgoingOriginalFlowFiltersConstraintTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/RemoveOutgoingInterfaceConstraintsTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_asa/CiscoAsaGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishGrammarTest.java
projects/question/src/test/java/org/batfish/question/searchfilters/SearchFiltersAnswererDifferentialTest.java

1. Use the cache in `IpAccessToBdd::toBdd(IpAccessList)`. This requires updating some tests to ensure ACLs are in their configuration's map
2. `BDDOutgoingOriginalFlowFilterManager::forNetwork`: use `IpAccessToBdd` infra from caller, rather than creating new instances (with separate caches).
Also added some logging to see where time is being spent.

BDD ACL caching improvements

---

projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/frr/BgpIpv4UnicastAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/frr/BgpL2vpnEvpnAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/frr/BgpNeighbor.java
projects/batfish/src/main/java/org/batfish/representation/frr/BgpNeighborIpv4UnicastAddressFamily.java
projects/batfish/src/main/java/org/batfish/representation/frr/BgpVrf.java
projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/frr/BgpNeighborTest.java
projects/batfish/src/test/java/org/batfish/representation/frr/FrrConversionsTest.java

It seems that FRR does not apply address-family configuration until after all
top-level neighbors are defined, even if those declarations come after the
address-family section.
Support this, and also no longer warn at parsing time for such cases.
commit-id:fac91090

FRR: allow neighbors to be defined out of order

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDUtils.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java
projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformationToTransitionTest.java
projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransitionsTest.java

Identity functions are encoded as a relation between unprimed and primed variables by `unprimedVar.biimp(primedVar)` (biimp is "if and only if").
We use them to merge two Transform transitions that operate on different domains: we use identity relations to expand each transition to operate on the union of the two domains.

Transform: use identity relations to merge more

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/static-routes-warn

* Enforce more constraints on when qualified-next-hop is allowed
* Allow routes with only qualified-next-hops
* Minor cleanup along the way
Fixes https://github.com/batfish/batfish/issues/8298

JunOS: fix static route qualified-next-hop logic

---

projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_asa/AsaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

A more targeted warning when ttl appears in ACLs. Meant to reduce user confusion like that in https://github.com/batfish/batfish/issues/8232

Warning for the use of ttl in ACLs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDRepresentativePicker.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDFlowConstraintGeneratorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDRepresentativePickerTest.java

Preferences are now encoded using a tree structure that allows us to skip applying preferences that are guaranteed to fail. There are two types of nodes: `RefineFirst`, which stops after the of its (ordered) children successfully refines the input, and which is useful for encoding mutually-exclusive lists of preferences, and `RefineAll`, which attempts to refine with each of its children, keeping any successful refinements. `RefineAll` is useful for non-mutually-exclusive preferences. Each node can optionally have a guard that refines the input before considering children.

BDDRepresentativePicker: more efficient encoding of preferences

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysis.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/PerHostDataPlane.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/SimpleFieldsDataPlane.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java

DataPlane is one big ball of complexity which takes a long time to serialize
and deserialize. To improve on this, stripe it by host. This enables less work
by the Java serialization framework (which keeps all serialized objects in an
identity hashmap) and by also enables use of many cores (CPU overhead for
serializing objects) and better pipelining of CPU with I/O.
Note that Java serialization will only serialize pointed-to objects once no
matter how many times they are referenced. Striping means that each object
is now serialized many times, increasing both a) on-disk storage (after
serialization) and b) in-memory storage (after de-serialization of the same
object used in different devices).
These penalties are overcome via the followng insights:
a) in practice, the largest objects are …

FileBasedStorage: stripe dataplane by host

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java

In a simple unit test, this saves 14%: 881 bytes to 762.
In a larger network, this reduces serialized dataplane size by about 12%:
* 40928 kB to 35980 kB (compressed size on disk)
* largest file 624992 bytes to 545781 bytes (decompressed size)
commit-id:b13b4e71
---
**Stack**:
- #8345
- #8344 ⬅

PrefixTreeMultiMap: reduce serialized size

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EvpnType2RouteTest.java

One of the equality groups in this test wasn't building the route, so it was comparing other routes to a builder.

Fix bug in EvpnType2Route equals test

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Bgpv4Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType2Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType3Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EvpnType5Route.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/TunnelEncapsulationAttribute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/LiteralTunnelEncapsulationAttribute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/TunnelEncapsulationAttributeExpr.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/RemoveTunnelEncapsulationAttribute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetTunnelEncapsulationAttribute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/StatementVisitor.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpRouteTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/TunnelEncapsulationAttributeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/RemoveTunnelEncapsulationAttributeTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/SetTunnelEncapsulationAttributeTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java
projects/question/src/main/java/org/batfish/question/TracingHintsStripper.java

Adds a tunnel attribute field in `BgpRoute` and routing policy statements to set and clear it. No vendors currently create these statements in conversion.
After #8350, just because it relies on the `TunnelAttribute` class existing.

Add tunnel attribute in BgpRoute

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java

This was an existing inefficiency made easier to see and fix by
batfish/batfish#8354. No reason to scan the entire RIB to get matching routes.
commit-id:2d938ad2
- batfish/batfish#8354

RoutesAnswerer: faster main rib exact match

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenTunnelAttributeRemove.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenTunnelAttributeSet.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/PsThenTunnelAttributeRemoveTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/PsThenTunnelAttributeSetTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-then
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-references-in-policy

Adds support for the following `then` statements (inside or outside of a term):
```
set policy-options policy-statement PNAME then tunnel-attribute set TUNNEL_ATTR_NAME
set policy-options policy-statement PNAME then tunnel-attribute remove all
```
Not yet supported, but also valid:
```
set policy-options policy-statement PNAME then tunnel-attribute remove TUNNEL_ATTR_NAME
set policy-options policy-statement PNAME then tunnel-attribute TUNNEL_ATTR_NAME set
set policy-options policy-statement PNAME then tunnel-attribute TUNNEL_ATTR_NAME remove
```
After #8352.

Juniper: Convert set/remove tunnel attrs in policy

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_common.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_template.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/template-variable
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/template-variable-reference
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/template-variable-warn

Add support for address-object-like template variables (`ip-netmask` and `ip-range`).
For now, these are treated like `address` objects in the VS model. This is mostly correct but is too permissive of references, as you cannot reference template variables outside of a template on a real device.

PAN: support for template variables

---

projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathDuplicateTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathNonEcmpBestTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathUniqueNextHopTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/duplicate/configs/as1r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/duplicate/configs/as1r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/duplicate/configs/as2border
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/duplicate/configs/as2leaf
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/non-ecmp-best/configs/as1r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/non-ecmp-best/configs/as1r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/non-ecmp-best/configs/as2border
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/non-ecmp-best/configs/as2leaf
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as1r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as1r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as1r3
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as2border1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as2border2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as2leaf
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/add-path/unique-next-hop/configs/as2rr

IOS-based e2e add-path tests:
- Test that a router that sends all additional-paths will advertise multiple routes that are
duplicate post-export, and that both will be present in the BGP RIB on the receiver
- Test that a router that sends all additional-paths will advertise routes that are not ECMP-best,
and that both will be present in the BGP RIB on a receiver
- Test that a router with multiple routes for a prefix will advertise only one route per
unique next hop for that given prefix
Tests will pass without xfail when add-path is implemented properly

Add xfail BGP additional-paths tests

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacePropertySpecifierTest.java
projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDReverseTransformationRangesImplTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/TunnelTopologyTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/FlowTracerTest.java
projects/batfish/src/test/java/org/batfish/dataplane/traceroute/TracerouteEngineImplTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/NatGatewayTest.java
projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java
projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java

After this PR, interfaces' `IpAccessList`s must exist in their owner `Configuration` (this should already be the case, except in some tests that had to be updated in this PR).
This means that we can now, e.g. overwrite `IpAccessList`s during `finalizeConfiguration` and the updated ACL would take effect as desired.

VI Interfaces: store `IpAccessList` names instead of references

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-neighbor
tests/parsing-tests/example-juniper.ref
tests/parsing-tests/srx-testbed.ref
tests/parsing-tests/unit-tests.ref

Helps pull out the neighbor definitions in the config file. 
(If this makes sense, will do other vendors in separate PRs.)

Junos: Define a structure type for BGP neighbor

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPacket.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java

Setting fields not related to the IP Protocol can be
confusing for downstream users of the Flow.
commit-id:64681fe7

BDDPacket.getFlow: don't set irrelevant fields

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-bgp-add-path

- initial add-path conversion given limited VI model
- Finer grained add-path control once VI model is updated

Juniper basic add-path conversion

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpProtocol.java

Part of batfish/batfish#8388 related fixes
- batfish/batfish#8388

IpProtocol: move two IPv6-only values to unnamed

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpProtocol.java
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

ip_protocol is used for identifying IPv4 protocols in family inet
firewall-filter.
The same rule is abused for family inet6 as well as family inet, but fixing
that is a bigger journey I'm punting for now.

JunOS: remove IPv6 options from ip_protocol

---

projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_eigrp

The referenced route-maps need to exist for the code to trigger.
commit-id:30d2293e

NX-OS: fix configuration for a test

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java

- Previously, non-arrival-order best-path comparator preferred lowest
receivedFromIp
- Update comparator to compare across all three new ReceivedFrom
subtypes
- first prefer lowest equivalent receivedFromIp
- then prefer best ReceivedFrom subtype:
- ReceivedFromSelf (best)
- ReceivedFromIp
- ReceivedFromInterface (worst)
- then if both are ReceivedFromInterface, prefer highest interface
name (string comparison)

BGP fix best-path received-from comparison

---

projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/StandardAccessListActionLine.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
tests/parsing-tests/unit-tests.ref

Fix Standard ACL line conversion/naming to line up with structure definition; fixes VSIDs based on that conversion.

Arista: fix ACL line VSIDs

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathDuplicateTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpAddPathUniqueNextHopTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpBestPathExportTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
tests/basic/genDp.ref
tests/basic/routes.ref

- Routes with the same prefix (NLRI) and next-hop may not be
ECMP-equivalent
- So if multipath compare considers them equal, pick one to be better
using bestpath comparison regardless of whether RIB is multipath

BGP always use bestpath comparison between routes with same next hop

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java

This greatly reduces route churn in differential BGP RIB outputs when a route has been added or removed between snapshots.

Generate path IDs independently per prefix

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSet.java
projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSetMember.java
projects/batfish/src/main/java/org/batfish/representation/juniper/BaseApplication.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java
projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromJunosApplicationSet.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplicationSet.java
projects/batfish/src/test/java/org/batfish/representation/juniper/ApplicationSetTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/BaseApplicationTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSetTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JunosApplicationSetTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JunosApplicationTest.java

* Don't add `TraceElements` for undefined/unmatchable apps
* Add `builtIn` bool for apps to indicate if they're user-defined or built-in
* Generate different `TraceElements` for built-in apps

Juniper: fix application TraceElements/VendorStructureIds

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/ImmutableBDDIntegerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java

The MutableBDDInteger has the previous implementation based on orAll and andAll. This makes sense since the bit BDDs can be arbitrarily large. The ImmutableBDDInteger implementation simply builds the result bottom up, which is more efficient since the bit BDDs are single variables and the order is guaranteed.

BDDInteger: make conversion methods from Ip/Prefix/value to BDD abstract

---

projects/pom.xml

We've added a few new libraries. While we did check they were all safe to use,
we did not keep the merges up to date. I did a manual inspection to confirm
the merges and continued safety.
To use: mvn license:aggregate-add-third-party.

license: upgrade plugin, tweak merges

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java
projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java

Introduce a new operation that computes the logical AND of some number of literals (constraints on exactly one variable -- i.e. the variable must be true or must be false), and use it in `ImmutableBDDInteger#firstBitsEqual`. 
The `andLiterals` implementation does the same bottom-up construction we were doing in `firstBitsEqual`, but without caching in the operator cache. This avoids evicting more valuable entries (i.e. expensive operations) for these low-value ones (adding a node to the root of a BDD is very cheap).
We could consider caching the entire `andLiterals` operations in the multi-op cache, but that would be redundant with the cache in IpSpaceToBDD.

BDDFactory: introduce andLiterals operation

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-ospf-interface-after-ospf

Before: While parsing `router ospf` stanza, the set of OSPF networks were being computed based on the interfaces defined at the time. This meant that any interfaces defined after the OSPF stanza were ignored. This PR changes that behavior. 
A user reported that when they defined interface after router OSPF, as in append to the original config, OSPF is enabled on that interface. This behavior is consistent with what Batfish does for other vendors. 
No other change in this PR.

IOS: Enable OSPF for interfaces defined after router OSPF

---

projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java

* Fix bug where input route's tunnel encapsulation attribute was ignored
* Beef up test to check that all input route attributes are honored
* Cleanup: Avoid converting the same `datamodel.BgpRoute` to `questions.BgpRoute` multiple times

Fix up TestRoutePoliciesAnswerer

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
projects/question/src/main/java/org/batfish/question/routes/BgpRouteRowSecondaryKey.java
projects/question/src/main/java/org/batfish/question/routes/MainRibRouteRowSecondaryKey.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowAttribute.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowSecondaryKey.java
projects/question/src/main/java/org/batfish/question/routes/RouteRowSecondaryKeyVisitor.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java

Makes `receivedFromIp` part of the `RouteRowSecondaryKey` for differential BGP RIB, so that if there is a similar route across two snapshots with different `receivedFromIp`, they will be considered different routes for diffing purposes. Paving the way for a received path ID column, which will also be a key.
Also added `receivedFromIp` to the comparator that sorts BGP RIB rows. The sort order is now: node, VRF, network, next hop, receivedFromIp. Once the received path ID column is added, that will go into the sort order after receivedFromIp.
Because `receivedFromIp` isn't an attribute of main RIB routes (and path ID won't be either), made `RouteRowSecondaryKey` abstract with separate implementations to represent a main RIB key and a BGP RIB key.

Differential BGP RIB: Make receivedFromIp a key

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Zone.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/security-zone-term-refs
tests/parsing-tests/srx-testbed.ref
tests/parsing-tests/unit-tests.ref

In Juniper VS -> VI conversion, `VendorStructureIds` are created for each firewall filter term.
This PR just adds definitions for firewall filter terms for zone inbound filters, so the VSIDs no longer point to non-existent structure definitions.

Juniper: fix firewall filter VSIDs

---

projects/question/src/main/java/org/batfish/question/routes/RouteRowAttribute.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java
projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java
tests/basic/routes-diff.ref

- Test that differential and non-differential result tables contain the same basic columns, in the same order. Related fixes:
- Add `originatorIp`, `clusterList` to `RouteRowAttribute` and differential BGP result
- Flip order of next hop interface and protocol columns in main RIB differential result
- Test that differential questions populate all expected fields. Related fix:
- Populate weight column
- Test that all relevant attributes are populated when converting a `Bgpv4Route` to `RouteRowAttribute`. Related fixes:
- Copy over cluster list, origin mechanism, originator IP, and weight
- Stop copying over admin distance. There is no admin distance column in BGP RIB answers; it is only relevant in `RouteRowAttribute` for main RIB routes.

BGP RIB question: fix bugs, improve tests

---

projects/build-tools/src/main/resources/org/batfish/owasp/suppressions.xml
projects/pom.xml

1. upgrade OWASP to latest. Noticed when I ran manually, seems to improve
reliability if downloads fail.
2. Suppress this false-positive CVE-2022-31569. Tl;dr: the CVE is in Flask (python),
and this is a Java project. The author of the CVE appears to have filed CVEs for
all artifacts produced by any organization that used Flask improperly in their
GitHub repo, regardless of what it actually affects.
commit-id:51c92d56

OWASP: upgrade and suppress false positive

---

projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTest.java
projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java

For a single-file snapshot, we don't need all that machinery to handle
folders, etc., we can just directly write a single file zip.
commit-id:f4c0125e
---
**Stack**:
- #8435
- #8434 ⬅

WorkMgrTestUtils: simplify zip creation

---

projects/batfish-client/src/main/java/org/batfish/client/Client.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/ZipUtility.java
projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java

The old ZipUtility used ancient code from StackOverflow.
Rewrite it using the nice clean FileVisitor API.
commit-id:6727282e

ZipUtility: rewrite using newer APIs

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/pre-defined-junos-applications-converted

Without junos-rdp in the list, it was lexing as NAME and resulting
in an undefined reference.
This fix also caught the improper use of junos-host, which is not
an application but rather a zone.
commit-id:e99ff3ec

JunOS: add app junos-rdp, remove invalid test for app junos-host

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoTraceElementCreators.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java

Before this PR, `shared` rules were shoved into the `panorama` vsys. After this PR, they're kept in the `shared` vsys, which also fixes some broken VSIDs.

PAN: fix rulebase `VendorStructureId`s

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/application-override-diff-vsys-vsids

Before this PR, `application-override rule` VSIDs used the vsys for the current zone-pair/flattened security rule.
This isn't correct for `application-override rule`s defined in the Panorama vsys; this PR fixes this and fixes broken TraceElements/VSIDs for these rules.

PAN: fix `application-override rule` TraceElements/VendorStructureIDs

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/util/UnzipUtility.java
projects/coordinator/src/main/java/org/batfish/coordinator/resources/SnapshotResource.java
projects/coordinator/src/test/java/org/batfish/coordinator/resources/SnapshotResourceTest.java

- return 400 so client of v2 uploadSnapshot does not attempt to retry

Return 400 on error uploading snapshot via v2 API

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/util/AclPacketMatchValidityChecker.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/util/AclPacketMatchValidityCheckerTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/util/BUILD
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/IcmpTypeGroupTypeLine.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java

We have had a number of issues (see batfish/batfish#8388 for example)
where an ACL checks a protocol-specific property but does not actually
restrict to packets of the correct protocol. This can lead to strange
behavior, such as allowing flows that have ICMP Type 128 but are not
ICMP packets - mainly in symbolic tools like reachability.
Check converted ACLs when assertions are enabled. Note that we only check ACLs,
rather than individual MatchExprs -- because the latter can be composed and
it's difficult to tell when we're at an abstraction boundary when these
invariants should be enforced.
ASA's object groups are not that well formed, so skip this validation
on ASA for now.
commit-id:aca59b81
- batfish/batfish#8388

finalizeConfiguration: check invariants on converted ACLs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java

PrefixTrieMultiMap#longestPrefixMatch(ip, int) is used on the hotpath during dataplane,
and it immediately converts its arguments into a Prefix. That involves allocation and
locking (interning prefixes), that is essentially unused later - the two components
of the Prefix are decoupled in trie traversal.
Change the relevant internal APIs to work on the component parts, saving allocations.
commit-id:6a7eec28

PrefixTrieMultiMap: reduce allocations in hotpath

---

projects/coordinator/src/main/java/org/batfish/coordinator/Main.java

- disable unused jersey wadl feature to remove warnings like:
```
Aug 16, 2022 1:25:07 PM org.glassfish.jersey.server.wadl.WadlFeature configure
WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
```

Disable wadl to remove warning

---

projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java

When called with a single literal, return a copy of it. Otherwise freeing the result is unsafe in general

andLiterals: always return a fresh BDD

---

projects/batfish/src/main/java/org/batfish/bddreachability/BDDLoopDetectionAnalysis.java
projects/batfish/src/test/java/org/batfish/bddreachability/BDDLoopDetectionAnalysisTest.java

Previously, confirmLoop would fail to confirm a self-loop on the input start state.

BDDLoopDetectionAnalysis: fix self-loop bug

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDFlowConstraintGenerator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraintsUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/BDDPacketTest.java

HeaderSpace is much closer to being a 'core' datamodel class; it does not have
gross dependencies like on specifiers.
This makes some downstream work much easier.
commit-id:52cd4284
---
**Stack**:
- #8517
- #8515
- #8516 ⬅

DEFAULT_PACKET_LENGTH: move from PHC to HeaderSpace

---

projects/batfish-common-protocol/BUILD

Since the parboiled parser does not play nice with Bazel code coverage,
pull it into its own library. Much like parser_common, I had a huge
challenge with modularity as the existing code doesn't really have
any.
Related work: removing the parser_common files from being compiled
twice, adding the missing dependency, adding missing pmd_test,
and making a "virtual :common" target to ensure that no existing
code has to be changed (even downstream).
commit-id:d4ccf516
---
**Stack**:
- #8518
- #8517
- #8515 ⬅

common: separate specifier/parboiled code out

---

.github/workflows/pre-commit.yml

* Build JAR with Bazel
* Run unit tests with coverage with Bazel
* Just remove ref test coverage
The only remaining pieces using Maven are the format and checkstyle jobs

CI: use Bazel instead of Maven

---

projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java

- saves time for `VendorConfiguration`s that produce a lot of `Configuration`s
- e.g. CheckPoint mgmt, Panorama
- saves 25-33% of snapshot init time on some networks of interest

Parallelize convert job calls to finalizeConfiguration

---

docs/data_plane/README.md

Could use a supporting doc covering what a routing iteration looks like for a particular protocol, including redistribution, exports, queues, etc. Probably BGP is the prime candidate for deeper documentation.

Fill in dataplane doc

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/app-id

If Palo Alto's "App-ID" has to be used, it is possible there is a flow it will match, and it is possible there is a flow it will not match. So a permit rule should be permitted ("something is allowed") but a deny rule should not be denied ("something is not matched").
Previously we were only applying this logic for application-default - this PR does it for any service.

PAN: revisit permit/deny logic when Palo Alto's "App-ID" has to be used

---

.github/workflows/pre-commit.yml

The bash upload has been deprecated for half a year,
and is not working today.
commit-id:9873150c

codecov: switch to github action

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java
projects/batfish-common-protocol/src/test/java/org/batfish/storage/FileBasedStorageTest.java

- fixes batfish/batfish#8546
- during network GC, fetch oldest last modified time of all extant snapshot files
- delete network blobs older than that time, or now minus GC skew allowance if earlier

Garbage collect network blobs older than oldest snapshot

---

projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java
projects/batfish/src/test/resources/org/batfish/vendor/sonic/grammar/snapshots/snmp_yml/sonic_configs/device/snmp.yml

Special characters mess up Jackson, but are allowed
on-device.

SONiC: trim YAML file before parsing

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HasReadableClusterList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HasWritableClusterList.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/BooleanExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchClusterListLength.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/expr/MatchClusterListLengthTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/BooleanExprAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java

- match via IntComparator against rhs IntExpr
- treat routes/builders without cluster list as having list of length 0

Add routing policy expr for matching BGP cluster list length

---

.pre-commit-config.yaml

- removes need for github-known SSH key to run pre-commit

Use https instead of git (ssh) protocol to fetch autoflake

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/StandardCommunity.java

There's no need to include memoized string representations in serialized
output. Also fix the CASE_FORMAT of a private static final variable.
commit-id:3623fb62

Community: make memoized strings transient, fix style

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java

See https://tools.ietf.org/html/rfc4360 section 3.3 - opaque extended communities can not necessarily be split into local and global administrators in the way that other extended community types can. To enable more use cases of the 6 byte value field, change the internals to work in terms of the entire value rather than administrators, and convert the value into ga/la as needed. Also, add a method to create a new opaque community, that is decoupled from ga/la.

ExtendedCommunity: make internals more generic to support opaque ECs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/OpaqueExtendedCommunities.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluatorTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/CommunityMatchExprVarCollector.java

Parametrized to allow it to match on more specific types of opaque ECs as needed. 
hasSubtype() trivially returns true right now as none of the supported ECs lack a subtype (see ExtendedCommunity's VALID_TYPES).

Extended Communities: Add a CommunityMatchExpr for opaque extended communities

---

.bazelignore

.bazelignore: remove unneeded maven state

---

projects/batfish/src/main/java/org/batfish/representation/frr/RouteMapConvertor.java
projects/batfish/src/test/java/org/batfish/representation/frr/RouteMapConvertorTest.java

Adjusts the VI generation for FRR route-map `on-match next/goto`. This closely follows the fixes for [NX-OS: tweak route-map conversion for continue and fall-through](https://github.com/batfish/batfish/pull/6462) and [fixup to #6462](https://github.com/batfish/batfish/pull/6464).
Fixes issue:
https://github.com/batfish/batfish/issues/8593

Fixes #8593

---

.pre-commit-config.yaml

Work around a Python 3.9 issue with click. For more info, see
https://github.com/psf/black/issues/2964
commit-id:f2ffb26c

black: upgrade to latest

---

projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios_svi

#8569
PR for the above issues.

Cisco IOS enable autostate for extended VLANs

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/name

E.g., policy-statements with IPv6 addresses in the name.

JunOS: allow colon in names

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java

Prevents
2022-12-06 07:11:43,019 ERROR storage.FileBasedStorage Failed to expunge blobs from networkId 'b5146401-c0a3-4419-9594-4103a92800da'
java.nio.file.NoSuchFileException: /data/containers/networks/b5146401-c0a3-4419-9594-4103a92800da/blobs
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
at …

FileBasedStorage: don't throw if no blobs written yet

---

docs/example_code/new_vendor/src/main/antlr4/org/batfish/grammar/cool_nos/CoolNosLexer.g4
docs/example_code/new_vendor/src/main/antlr4/org/batfish/grammar/cool_nos/CoolNosParser.g4
docs/example_code/new_vendor/src/main/java/org/batfish/grammar/cool_nos/CoolNosConfigurationBuilder.java
docs/extraction/README.md
docs/parsing/README.md

The fourth state could use some more context, but this can be added when we circle back to flesh out the Conversion documentation.

Docs: Add config states to parser documentation

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java

Fix #8623
Update `BgpProcess` and `BgpRoutingProcess` to support announcing prefixes from network statements to neighbors regardless of if they have that neighbor in their main RIB. 
This is implemented by adding a list of networks into BgpProcess as well as a new policy, mainRibIndependentNetworkPolicy. On initialization in BgpRoutingProcess, a RibDelta is populated, which is then used in the next iteration to redistribute these routes to BGP.

Implement network statement advertisement to bgp rib

---

projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/frr/FrrConversionsTest.java
projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/main-rib-independent-network-statement/configs/frr-network
projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/ospf-bgp-redist-set-metric/configs/frr-redistributor

Fix #8623
This will by default announce routes from network statements regardless of if they are in the main rib, according to http://docs.frrouting.org/en/latest/bgp.html#clicmd-network-A.B.C.D-M.
Note that the frr-redistributor change fixes a now-failing test, and a quick lab validated that this change results in expected behavior.

FRR: Add network statement policy in frr

---

docs/building_and_running/README.md

- curl command was broken in at least two ways
- did not follow redirects
- binary output also sent to console
- use wget instead
- avoids any potential issue with spurious output, redirects
- simpler

Fix Ubuntu instructions for installing bazelisk

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/Graph.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/BooleanExprAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/ConfigAtomicPredicatesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/aspath/BooleanExprAsPathCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/aspath/RoutePolicyStatementAsPathCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/BooleanExprVarCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollectorTest.java

Updates the SearchRoutePolicies/CompareRoutePolicies questions to only compute the AtomicPredicates for the set of policies that are used in the question instead of the whole file. This is done for performance reasons; computing APs in configs with multiple regex based AS-path/community definitions can be very expensive.
Updates community/AS visitors to recursively visit called policies. This assumes routing policies do not include mutual recursion (a valid assumption AFAIK), otherwise the visitors would loop forever.

SearchRoutePolicies - only build AtomicPredicates for relevant policies.

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java

Instead of returning a set of empty results, reject policy specifier that could not be resolved with an exception. This prevents users from experiencing false negative results.

CompareRoutePolicies: reject unresolved policies

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/HybridL3Adjacencies.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Topologies.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1TopologiesFactory.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Topology.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/PointToPointComputer.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/Layer1TopologyTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/main/BatfishTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java
projects/question/src/main/java/org/batfish/question/edges/EdgesAnswerer.java

Guava Network has data-typed edges, where as Graph just has node pairs. We only
need the latter.
To improve maintainability, stop exposing internal implementation details and
create only-Batfish-typed accessors.
commit-id:c2478701

Layer1Topology: reduce internal memory use and complexity

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConnectedRouteMetadata.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route

https://www.juniper.net/documentation/us/en/software/junos/interfaces-fundamentals/topics/topic-map/logical-interface-properties.html#id-disabling-a-logical-interface

Junos: Create a /32 discard route for inactive interfaces

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Adds support for `match metric`/`match metric ge` in symbolic evaluation of route-maps.

SRP: add support for match metric

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/references/StructureManager.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java
projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/f5_bigip/F5BigipConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_asa/CiscoAsaGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoSecurityRuleTest.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java
projects/batfish/src/test/java/org/batfish/job/InvalidVendorStructureIdEraserTest.java
projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java
projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java

We wanted sorted structures for deterministic and readable references, but this
hurts us during building/tracking.
Introduce a new class to encpsulate all the definition/reference/undefined
logic and layer in hash-based building phase with a save phase that produce
sorted objects.

Add StructureManager to improve performance and encapsulate logic

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperParser.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ActivationLinePruner.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/DeactivateTreeBuilder.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/PreprocessJuniperExtractor.java
projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java
projects/batfish/src/test/java/org/batfish/main/FlattenTest.java
projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java
projects/batfish/src/test/resources/org/batfish/main/testconfigs/active_only
projects/batfish/src/test/resources/org/batfish/main/testconfigs/active_only_flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/multiple_tags
projects/batfish/src/test/resources/org/batfish/main/testconfigs/multiple_tags_flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-juniper-activation-after
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-juniper-activation-before

* Support 'active:' tag in hierarchical Juniper syntax
* Implement by inserting 'activate' line before deeper 'set' elements
* Support multiple tags in hierarchical Juniper syntax
* e.g. both 'replace:' and 'active:' at the same hierarchy level
* Support 'activate' command in flat Juniper syntax
* Undoes 'deactivate'
* Fix Juniper deactivate semantics
* Allow deactivating/reactivating  multiple subpaths of a path independently

Juniper support flat 'activate' and hierarchical 'active:' tag

---

tools/fix_java_format.sh

It's now the default for the IDEs
commit-id:e9dbb3c4

google-java-format: upgrade to new release

---

tools/fix_java_format.sh

Without quotes, the if seems to return true even if the command does not exist

fix_java_format.sh: fix missing command detection

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/EvpnMasterRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java

* evict existing distinct routes with same prefix, receivedFrom, and pathId
* skip tracked local routes, for which there is existing intricate logic for this purpose

Evict existing related BGP routes when  merging UPDATE-like route

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsApplicator.java
projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-after
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-juniper-apply-groups-order-after
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-juniper-apply-groups-order-before
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-after

* Insert inherited lines for each applied group at the top so that:
* Non-inherited lines take precedence (appear later) over inherited lines
* Groups earlier in the apply-groups list value take precedence over later ones
* See https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/apply-groups.html#apply-groups__d65612e42

Fix Juniper apply-groups processing order

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java

1. getRoutes was sorting unnecessarily, can simply keep the maximum
2. multipath code to update best routes was pre-emptively sorting
even though it might not be necessary.
Changing it to sort lazily cut bestPathComparator time by more than
a factor of 10 on one large network.

BgpRib: sort lazily

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java

Enables support for `set metric +d` in stanzas.
If an overflow occurs, the value is set to the max value of the given field (in case of metric, 2^32-1).

Add support for IncrementMetric in TransferBDD.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpActivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPassivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpUnnumberedPeerConfig.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpUnnumberedPeerConfigTest.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTest.java
projects/batfish/src/test/java/org/batfish/dataplane/protocols/BgpProtocolHelperTransformBgpRouteOnExportTest.java
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref

* Add BgpPeerConfig/BgpSessionProperties field `replaceNonLocalAsesOnExport`
* When true, and session is eBGP, the final step in transformation of a BGP route post export is to replace every element of the AS path with the singleton as-set of the local AS

Add VI support for replacing all AS-path elements with local AS

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface-cts
tests/parsing-tests/unit-tests.ref

Cisco IOS: Parse and ignore cts substanzas under interface

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/rr-rib-failure-client-non-client/configs/r1
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/rr-rib-failure-client-non-client/configs/r2
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/testrigs/rr-rib-failure-client-non-client/configs/r3

Route reflection criteria was applied in two places, but one location was incomplete. Specifically, we have a check `isReflectable` that was used for advertising BGP routes that are not installed in the main RIB if they are a result of route reflection. Moved this logic into a shared method used for both the RIB failure spot and the BgpProtocolHelper spot. 
Functionally, this changes a single case: in the event of RIB failure, client-to-client and non-client-to-client cases were already covered, and this CR adds client-to-non-client.
Does not effect anything eBGP-related.

Move route reflection logic to a shared method

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java

1. Dedup reverse traceroutes. Previously, if there are multiple forward paths with the same traceroute parameters (return flow and established firewwall sessions), we would repeat the reverse traceroute for each forward trace.
2. Short-circuit. Stream traces directly from the TraceDag instead of first collecting them into a list, and stop as soon as we find one successful bidrectional trace.
3. Don't collect all the traces. Just return the successful initiator local IPs.
On one snapshot containing many BGP multihop sessions (with ECMP paths), this reduced BGP topology computation time from 90s to 25s (total over 4 computations while dataplaning).

Optimize initiateBgpSessions

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

vrf-import
vrf-export
vtep-source-interface

Junos: add some missing todos for commands that only track references

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpConfederation.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpProcessPropertySpecifier.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/question/src/test/java/org/batfish/question/bgpproperties/BgpProcessConfigurationAnswererTest.java

Several vendors allow a range of peers which makes enumerating them all
prohibitively expensive.

BgpConfederation: swap members to a LongSpace

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
projects/question/src/test/java/org/batfish/question/edges/EdgesAnswererTest.java

* When a node is in a confederation and has a neighbor configuration with remote AS equal to the confederation AS, the session should be iBGP and considered to be across confederations.
* Determine and apply the correct AS-path modifying behavior when routes with subconfederation ASes are passed across confederation boundaries via iBGP

Support iBGP across BGP confederations

---

projects/question/src/main/java/org/batfish/question/snmpcommunityclients/SnmpCommunityClientsAnswerer.java
projects/question/src/main/java/org/batfish/question/snmpcommunityclients/SnmpCommunityClientsPlugin.java
projects/question/src/main/java/org/batfish/question/snmpcommunityclients/SnmpCommunityClientsQuestion.java
projects/question/src/test/java/org/batfish/question/snmpcommunityclients/BUILD.bazel
projects/question/src/test/java/org/batfish/question/snmpcommunityclients/SnmpCommunityClientsAnswererTest.java
projects/question/src/test/resources/org/batfish/question/snmpcommunityclients/BUILD.bazel
projects/question/src/test/resources/org/batfish/question/snmpcommunityclients/configs/arista
projects/question/src/test/resources/org/batfish/question/snmpcommunityclients/configs/ios
projects/question/src/test/resources/org/batfish/question/snmpcommunityclients/configs/juniper
projects/question/src/test/resources/org/batfish/question/snmpcommunityclients/configs/nxos
questions/experimental/snmpCommunityClients.json

The question checks if the specified SNMP community permits clients (specified as IpSpace). The check fails if the SNMP community does not exist or if the ipspace permitted for the community does not exactly match the specified client space. 
The question only supports Arista, Juniper, and SONiC devices at the moment, and if the check  It reports UNSUPPORTED_DEVICE status for others. 
This PR has Batifsh side changes. Pybatfish and docs changes will follow.

Question for checking if an SNMP community supports clients

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteCommunityDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffs.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteCommunityDiffTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteDiffTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffsTest.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java

Computes the set of added/removed communities in BgpRouteDiff.
Should not change the behavior of BgpRouteDiff at all.

Compute added/removed set for communities in BgpRouteDiff.

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/gh-8744
tests/parsing-tests/unit-tests.ref

Junos: handle quoted as-path-regex in hierarchical configs

---

projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/AsPathRegex.java
projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/BUILD.bazel

**Stack**:
- #8756
- #8755
- #8754
- #8753 ⬅

Junos: cache regex conversions if referenced more than once

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromInstance.java
projects/batfish/src/main/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatement.java
projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/AsPathRegex.java
projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/BUILD.bazel
projects/batfish/src/test/java/org/batfish/representation/juniper/PsFromInstanceTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatementTest.java
tests/parsing-tests/example-juniper.ref
tests/parsing-tests/srx-testbed.ref
tests/parsing-tests/unit-tests.ref

**Stack**:
- #8756
- #8755
- #8754 ⬅
- #8753

Junos: predefine 'master' routing instance and translate during VI conversion

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

The field is extracted but not used.
---
**Stack**:
- #8756
- #8755 ⬅

Junos: add missing nat pool owner instance todo

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/OspfInterfacePropertySpecifier.java
projects/question/src/test/java/org/batfish/question/ospfinterface/OspfInterfaceConfigAnswererTest.java

* OSPF Area number is a 32 bit unsigned integer, isomorphic to an IPv4 address
* internally, we use `Long` to represent 32 bit unsigned integer, i.e. `OspfInterfaceSettings.getAreaName()` returns a `Long`
* fixes crash answering OSPF interface properties when area is above java `Integer.MAX_VALUE`

Change OSPF interface property OSPF_Area_Name schema to use Schema.LONG

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteCommunityDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffs.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteCommunityDiffTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffsTest.java

Adds a getter for 2 fields in `BgpRouteCommunityDiff` and a `hasDifference` method in `StructuredBgpRouteDiffs`.

Extend BgpRouteCommunityDiff and StructuredBgpRouteDiffs public interface.

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchMetric.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchTag.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java

Check for usage of output/intermediate route attributes when matching on the metric, similar to how matching is done for other attributes; reorder the existing checks when matching on the tag to be consistent with how it's done elsewhere.

Bugfix: Consider using the output/intermediate route when matching on the metric

---

projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vlan.g4
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_vlan_service_policy

Fixes #8760 
Believe the necessary test were added to validate this, didn't see any `hasUnusedStructure` type methods that could validate one is used vs unused for a new structure usage.

NXOS: Add structure usage for service-policy under vlan configuration

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpRouteMatchersImpl.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/protocols/BgpProtocolHelper.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/ReceivedFromRouteReflectorTest.java
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/configs/nrrcb
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/configs/nrrcm
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/configs/rr
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/configs/rrcb
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/configs/rrcm
projects/batfish/src/test/resources/org/batfish/dataplane/ibdp/route-reflection/rrrc/external_bgp_announcements.json

* receivedFromRouteReflectorCllent bit was not being set in multiple cases  for routes being originated into BGP RIB
* move bit setting from postExport to preImport transformation, which makes better sense semantically and covers all gaps

Fix receivedFromRouteReflectorClient not set for main rib exports

---

projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPath.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java
projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java

Performance optimization for some of Junos AS path regex patterns by converting them to existing VI construct `AsSetsMatchingRanges` . This bypasses converting these junos specific regular expression to java regular expression.  
Following Junos AS Path regex patterns are included : 
- ".\* N .\*" : "AS Path contains N"
- ".\* N" or ".\* N$" : "AS Path ends with N"
- "N .\*" or "^N .\*" : "AS Path starts with N".
- ".\* [start-end] .\*" OR ".\* start-end .\*" : "AS Path contains an ASN in range between start and end included"
- "[start-end]" or "start-end" : "AS Path matches single ASN number in range between start and end included
- "N": "AS Path matches single ASN number"
If one of the above patterns don't match, then fallback to the existing solution of converting to java regex using …

Recognize certain Junos AS Path regexes and convert them to VI construct

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco_nxos/NxosMajorVersion.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessorTest.java

hitting this error when I init with this config from a Cisco NX-OS device:
`java.lang.IllegalArgumentException: Unsupported major version: UNKNOWN`
It looks like this is the line the error is happening on?
```
!Command: show running-config
!Running configuration last done at: Wed Jun 28 10:02:27 2023
!Time: Wed Aug  9 18:25:19 2023
version 10.1(1) Bios:version 05.43 
```

add support for nxos major 10

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java

Previously, if an L1 node has children interfaces, only children nodes are included in L2 topology, but the parent node may also be important (e.g. handling the untagged frames). This change makes sure both parent interface and subinterfaces are included in L2 topology.

TopologyUtil: include parent interface with subinterfaces in L2 topology

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/BgpSessionPropertiesTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/BgpTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_asa/AsaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java
projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java
projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswererTest.java
projects/question/src/test/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswererTest.java

Some vendors use Ip.AUTO to indicate that the local IP is chosen dynamically,
but this usage is inconsistent and makes it hard to consume this code downstream.
Instead, ensure that the value of _localIp is null for dynamic IP selection,
update callers, and update presentation code that wants to use Ip.AUTO to
explain to users.
---
**Stack**:
- #8781
- #8780 ⬅

BgpPeerConfig: _localIp should be valid or null

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InferFromFib.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/SourceIpInference.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UseConstantIp.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InferFromFibTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/UseConstantIpTest.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-default-address-selection

Previously, when default-address-selection is enabled and BGP peer local-address is unconfigured, Junos picks the loopback IP (based on the [default-address-selection spec](https://www.juniper.net/documentation/us/en/software/junos/transport-ip/topics/ref/statement/default-address-selection-edit-system.html)) as the local IP of the outgoing BGP establishment.  Batfish modeled this behavior at _conversion_ time and used the loopback IP as the local IP of the BGP _peer config_ -- this means the _incoming_ BGP establishments would be rejected unless the remote IP is set to loopback IP, whereas in the real world the BGP establishment would be accepted because local-address is unconfigured.
This commit fixes the problem by not setting local IP in the BGP peer config, but instead applying the …

Junos: Move default address selection for BGP local IP to runtime rather than conversion time

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpActivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPassivePeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpUnnumberedPeerConfig.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java
projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePluginTest.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
tests/aws/vimodel-example-aws.ref
tests/basic/outliers-verbose.ref
tests/basic/viModel.ref

In https://github.com/batfish/batfish/pull/8781 I made BGP listeners reject incoming
connections that aren't to a configured local IP (update source, in Cisco terms).
Turns out not all vendors do this, in particular FRR does not seem to have this check.
Extend BGP config to handle that, and set for FRR.

BgpTopologyUtils: allow for vendors that don't check local IP on connection

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/Community.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityRenderingVisitor.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySetExprs.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityToRegexInputString.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/SpecialCasesRendering.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/CommunitySetExprsTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/CommunityToRegexInputStringTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/communities/SpecialCasesRenderingTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/CommunityMatchExprVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/CommunityMatchExprVarCollectorTest.java

* accepts an explicit list of Community->String mappings
* falls back to a specified alternate rendering for keys not provided

Add VI special case community rendering customizable by vendor

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteDiff.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteDiffTest.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java
tests/questions/experimental/testRoutePolicies.ref

Adds `PROP_ADMINISTRATIVE_DISTANCE` to BgpRoute, to allow modeling the effect of `SetAdministrativeCost` in TRP/SRP.

Add AdministrativeCost in BgpRoute, and in extension for SetAdministrativeCost in TRP.

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/CommunityVar.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/RegexAtomicPredicates.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/SymbolicAsPathRegex.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/AsPathRegexAtomicPredicatesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/CommunityVarTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/RegexAtomicPredicatesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/SymbolicAsPathRegexTest.java

This PR updates the symbolic route analysis to properly account for the ranges of numbers that can appear in communities and in AS-paths.  Otherwise the analysis can provide spurious results, for example a community that is ill-formed because one half is a number that is out of range.

TransferBDD: Precise Number Regexes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/SymbolicAsPathRegex.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/SymbolicAsPathRegexTest.java

SymbolicAsPathRegex: use long math, skip doubles

---

projects/checkstyle.xml

1. Escape '.' in regex.
2. Remove unnecessary leading/trailing '.*'
3. Combine rules that are easy to combine.
Saves about 10%-15% runtime.

checkstyle: small optimizations

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/vlan-forwarding-options

A 'Parse warning' is being triggered by the following configuration:
```
set vlans <name> forwarding-options dhcp-security
```
The `dhcp-security` configuration is valid only under the ‘forwarding-options’ inside the vlans stanza.
This PR addresses the parse warning by extending the lexer/parser.
The configuration statement is documented [here](https://www.juniper.net/documentation/us/en/software/junos/security-services/topics/ref/statement/dhcp-security-edit-vlans.html)

Fix 'forwarding-options dhcp-security' parse warning for Juniper

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_snmp.g4
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/snmp

Parse and ignore snmp endinge-id
Received a `Parse warning` saying `This syntax is unrecognized` for the following valid syntax:
```
set snmp engine-id local NAME
```
Added the configuration to the existing SNMP configuration sample. The SNMP test that is in place at the moment now passes with this additional line of config. 
Let me know if it is more appropriate to add a new config sample together with a new test and I will add it.
For reference:
https://www.juniper.net/documentation/us/en/software/junos/network-mgmt/topics/ref/statement/engine-id-edit-snmp.html

JunOS: parse and ignore snmp engine-id

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-ignore-attached-bit

Parse `set protocols isis ignore-attached-bit`
Relevant docs for this: https://www.juniper.net/documentation/us/en/software/junos/is-is/topics/ref/statement/ignore-attached-bit-edit-protocols-isis.html

Junos: parse set protocols isis ignore-attached-bit

---

projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java

* Fix bug where a dependent route is removed from the resolution tracker if it is determined not to be resolvable during updateActiveRoutes
* With fix, such a dependent route can now be (re-)activated when a suitable main RIB route is added in the delta supplied o a subsequent call to updateActiveRoutes

Fix BGP route resolution tracker losing routes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDDomain.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

Updates the symbolic route analysis to represent "at-most-one" route attributes, namely the next-hop interface name and the source VRF, using a BDDDomain.  This has the effect of requiring only a logarithmic number of BDD variables in the number of options, whereas before we were using a linear number of BDD variables. It also simplifies some of the code since the "at-most-one" constraint is now enforced implicitly through the representation.

TransferBDD: Model "at-most-one" route attributes using BDDDomain

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpResolutionConditionTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
projects/batfish/src/test/java/org/batfish/job/ConvertConfigurationJobTest.java

* add BGPv4 RIB support for conditioning resolvability not just on the presence of one or more resolving routes, but also predicates on such resolving routes
* unlike main RIB resolvability conditions, more general routes are not checked if the LPM routes are not matched by the predicate
* add ability to specify a routing policy for a BgpProcess used to check resolving routes from the main RIB

Add VI support for BGP resolving route conditions

---

projects/checkstyle.xml

The autoformatter will put @Nullable on its own line if it starts the line, but
we can require it to be moved if there's a modifier it will stay after.

checkstyle: one more nullity pattern to catch

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractIp6SpaceContainsIp.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6Space.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6SpaceContainsIp.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6SpaceReference.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6Wildcard.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6WildcardSetIp6Space.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Prefix6.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixIp6Space.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/GenericIp6SpaceVisitor.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/AbstractIp6SpaceContainsIpTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6SpaceContainsIpTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6SpaceReferenceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6SpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6WildcardSetIp6SpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixIp6SpaceTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/Ip6SpaceMatchers.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/Ip6SpaceMatchersImpl.java
projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceIpv6AddressWithAttributes.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java

#8706 
I try to implement minor ipv6 support.

Add Ipv6 version of IpSpace

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-groups-lists

When the 'empty list' variant is not recognized, the parser crashes when
creating new syntax.
commit-id:476d1827

Junos: test JuniperListPaths and fix unrecognized lines

---

tools/bazel_run.sh

The modern recommendation (and what happens by default usually) is to have bazel
just be an alias for bazelisk.

bazel_run.sh: remove warning about bazelisk

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/BgpTopologyUtils.java

Parallelize edge creation in initBgpTopology, which involves runnning bidirectional traceroutes to check if sessions can be established. In a 4000+ node network, this speeds up dataplane time by ~8m.

Parallelize BgpTopologyUtils#initBgpTopology

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/gh-8876

User @racsoce shared a lab config with incomplete OSPF configurations,
it appears that our assertions based on old Palo Alto are no longer true.
Given that interfaces can appear with absolutely no settings, error on the
side of ignoring their OSPF configuration so as not to crash.
Fix batfish/batfish#8876

PaloAlto: gracefully handle partially configured OSPF settings

---

projects/batfish/src/main/java/org/batfish/representation/juniper/BUILD.bazel
projects/batfish/src/main/java/org/batfish/representation/juniper/GroupWildcard.java

This is typically fast, but may appear thousands of times. Caching makes one
problematic file faster by minutes.

Junos: cache GroupWildcard regex conversions

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-set-interface-damping

The `suppress` command never needs to be extracted, so ignored silently

Junos: add parsing for  `set interfaces damping suppress` command

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-set-interface-damping

The damping commands never needs to be extracted, so ignored silently

Junos: add parsing for `set interfaces damping` commands

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_protocols.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/set-partial

support a standalone `set protocols`. Note that my commit message is missing `set protocols`; somehow it got removed because of backticks

Junos: parse standalone set protocols

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper_delete_protocols_on_interface
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper_fti_interface_type

Add support for  `fti` interface type.
Flexible tunnel interface (FTI) is a type of logical tunnel interface that uses static routing and BGP protocols to exchange routes over a tunnel that connects endpoints to routers.
JunOS documentation for [FTI interfaces](https://www.juniper.net/documentation/us/en/software/junos/interfaces-encryption/topics/topic-map/configuring-flexible-tunnel-interfaces.html)

Junos: add parsing for  `fti` interface type

---

WORKSPACE

With sha256, I'm not worried but this feels better.
---
**Stack**:
- #8890
- #8889 ⬅

WORKSPACE: upgrade to https for buildifier-prebuilt

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-bgp-family-route-target

Juniper docs on [family route-target](https://www.juniper.net/documentation/us/en/software/junos/vpn-l2/topics/ref/statement/family-edit-protocols-bgp-route-target-vp.html) command. 
```
The family route-target statement is useful for filtering VPN routes before they are sent. Provider edge (PE) routers inform the route reflector (RR) which routes to send, using family route-target to provide the route-target-interest information. The RR then sends to the PE router only the advertisements containing the specified route target.
```
Add parsing support for the `route-target` command and `warn`. We still need to look into fully supporting this command in Batfish.

Junos: Add parsing support for bgp `family route-target` command

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureType.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/isis-import

This parses previously unsupported statements like
`set protocols isis import ISIS-ROUTE`
and
`set policy-options policy-statement ISIS-ROUTE term ISIS-TERM from tag2 1000`.
I tried to add reference tracking based on looking at other code but am not sure I did it right, because it wasn't exactly parallel to the example code.

Junos: parse and warn on `isis import` and `tag2`

---

projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java

Easier to use, compare, etc.
No functional changes for now, but unblocks follow-up work improving
logging during dataplane reconvergence.
---
**Stack**:
- #8911
- #8910 ⬅

TrackResults: change interface to Table

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4
projects/batfish/src/main/java/org/batfish/grammar/arista/AristaControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/arista/AristaDestinationStaticNat.java
projects/batfish/src/main/java/org/batfish/representation/arista/Interface.java
projects/batfish/src/main/java/org/batfish/representation/arista/NatProtocol.java
projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/arista/AristaStaticSourceNatTest.java
projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/ip-nat-destination

Fix batfish/batfish#8923.
Arista destination NAT was never implemented. While there are many variants,
implement the lowest hanging fruit of IP-only, IP-and-port, and/or IP Protocol.
This covers the user bug report, retains reference tracking, and adds a missing
warning for unsupported use cases.

Arista: partial implementation of ip nat destination

---

WORKSPACE

buildifier: use HTTPS not HTTP

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java

VendorConfiguration: speed up collecting definition lines

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/multipath-resolve

Add parse and warning for ` policy-options multipath-resolve` command.

Junos: Add parse and warning for policy-options multipath-resolve command

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/traceroute/TraceDag.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/traceroute/TraceDagImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/common/util/FlatMapIterator.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/util/FlatMapIteratorTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vxlan/VxlanTopologyUtilsTest.java
projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java

TraceDags have been observed to contain huge numbers of traces, too many to materialize into a list. Limiting to 10k for now. Rewrote TraceDagImpl to use iterators internally, as limit() wasn't working on the previous implementation based on recursive streams flattened with flatMap. Something about the stream implementation materializes many more traces than the limit, which wastes compute time and risks OOM. Rewriting using the same style of code but based on iterators solved the problem.

TracerouteEngineImpl: limit number of traces materialized from TraceDag.

---

projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java

We already sort cluster lists in single-snapshot answers, do the same in differential mode too.

Routes question: sort cluster lists in diff tables

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRouteCommunityDiff.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffs.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpRouteCommunityDiffTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/StructuredBgpRouteDiffsTest.java

Makes the objects that represent structured route map differences Comparable, so they can be compared to one another for purposes of deduplication and ordering.

CompareRoutePolicies: Allow structured route map differences to be compared to one another

---

projects/batfish-common-protocol/BUILD.bazel
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java

Unioning a small set and a large set is much faster than
unioning many singleton sets into a large set.

VendorConfiguration: improve performance for flattened configs

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpSessionProperties.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Variable.java
projects/client/src/main/java/org/batfish/client/Client.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesQuestion.java
projects/question/src/test/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswererTest.java
questions/experimental/testRoutePolicies.json
tests/questions/experimental/commands
tests/questions/experimental/testRoutePolicies.ref

Adds an optional parameter to the TestRoutePolicies question for specifying properties of the BGP session that can be needed in order to properly simulate a route map's behavior.

TestRoutePolicies: Add optional parameter for BGP session properties

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java

In all but two cases, the else was fraudulent: couldn't happen in grammar.
In the last two, there were what I believe are likely fraudulent applys (from
2015). It doesn't make sense to expand apply-groups there IMO, tho I could of
course be wrong.

Junos: remove convError

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ip_address

Juniper allows leading 0s in numbers, generally, including IP addresses. We already handle
this in F_Uint8, but somehow we had a nearly-equivalent F_DecByte that was only used
in IP address that did not allow zeros. Fix this last case, add a test, and delete
the now unused fragment.

Junos: convert last F_DecByte to F_Uint8

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/question/comparepeergrouppolicies/ComparePeerGroupPoliciesUtils.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/comparepeergrouppolicies/RoutingPolicyContextDiff.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/comparepeergrouppolicies/SyntacticDifference.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/comparepeergrouppolicies/ComparePeerGroupPoliciesAnswererTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/comparepeergrouppolicies/SyntacticDifferenceTest.java

The goal of this CR is for ComparePeerGroupPolicies to dedup differences across devices even if the devices have different context (e.g., different prefix-lists or community-lists). Initially, the thinking was that completeness (do not miss a difference in any device) was very important, but using the question I realize that this approach produces a lot of redundant information, for example when two devices have slightly different definitions of a prefix-list or a community-list. 
Perhaps the best approach to finding erroneous differences is another question to do a direct comparison of those definitions instead.
Changes:
1. `SyntacticDifference` the class that determines whether two pairs of current/reference routing policy are the same, no longer compares the list definitions (context). …

ComparePeerGroupPolicies: deduplicate context differences.

---

projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java

User reports that on a very large snapshot this causes a 2GiB limit to be hit.

FileBasedStorage: skip string when writing pojo topology

---

projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_ospf.g4
projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/ospf

There are two types of OSPF metrics with different bounds. Separate them
grammatically and make the interface metric one correctly u16. Improve testing
for new behavior including both 16 bit support and using the PAN default when
metric is not configured in configs.
Fix batfish/batfish#9013, thanks @netops501!

PAN: fix OSPF metric grammar and values

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java

PrefixTreeMultiMap: add function to get the numner of elements without materializing it

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/PrefixTrieMultiMapTest.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTree.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTreeTest.java

RibTree: add function to get the number of routes without materializing it

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java
projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/AbstractRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java
projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java
projects/batfish/src/test/java/org/batfish/dataplane/BgpRibGroupsTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/EvpnTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java
projects/batfish/src/test/java/org/batfish/dataplane/ibdp/VirtualRouterTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/AbstractRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/BgpRibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibDeltaTest.java
projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererTest.java

Rather than calling out (some of the) typed functions, call out the untyped ones.
Note that the old getRoutes(Prefix) was typed, but not named so.

GenericRibReadOnly: rename functions for clarity

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySet.java

We have previously thought that we needed to memoize the
hash code because ImmutableSet does not, but RegularImmutableSet
does, and this covers all practical cases.
---
**Stack**:
- #9037
- #9036 ⬅
- #9035

CommunitySet: stop memoizing hashCode

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunitySet.java

Still only 128 MiB of (soft) space, but increases hit rate in networks that put
put ASNs in communities.
---
**Stack**:
- #9037 ⬅
- #9036
- #9035

CommunitySet: bump cache up to 16M values

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/BUILD.bazel
projects/minesweeper/src/test/java/org/batfish/minesweeper/ConfigAtomicPredicatesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/ConfigAtomicPredicatesTestUtils.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/AsPathMatchExprToRegexesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

The old implementation felt very overfit to the two existing callers, with new
constructors being added for every new use case.
Replace this with basically one API, which takes in a list of
<Configuration,RoutingPolicy[]> pairs and optional extras, then port all the
other creation methods onto it.
Move all the magic device loading from snapshot into testing utilities which is
the only place it's used. (With minor cleanup that simplifies the real question anyway).

ConfigAtomicPredicates: simplify API and refactor test code to testlib

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/interface-vlan
tests/parsing-tests/unit-tests.ref

From [junos docs](https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/topic-map/bridging-and-vlans.html#:~:text=A%20Default%20VLAN%20Is%20Configured%20on%20Most%20Switches,-Some%20switches%20running&text=On%20these%20switches%2C%20each%20interface,not%20support%20a%20default%20VLAN):
> Some switches running Junos OS that do not support the ELS configuration style are preconfigured with a VLAN named default that does not tag packets and operates only with untagged packets. On these switches, each interface already belongs to the VLAN named default and all traffic uses this VLAN until you configure more VLANs and assign traffic to those VLANs.
Parse and ignore the `default` vlan, and don't count it as a reference to a vlan variable.

Junos: parse and ignore vlan "default"

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifierTest.java

BgpPeerProperty: fallback to EVPN address family if IPv4 Unicast not enabled

---

.github/workflows/pre-commit.yml

https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
Seeing transient errors in other builds, and this upgrade from December
appears to look like it could address it.

pre-commit: upgrade to artifacts v4

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java

There were no tests of MutableBDDInteger#sub or #toBDD(IpWildcard), or #and, so
I implemented minimal versions of those as well.

MutableBDDInteger: internal leak checking and fixes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDD.java
projects/minesweeper/src/test/java/BUILD.bazel
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDDTest.java

Filtering on community set size is an extremely fragile capability. The primary
way we've seen it used is as a safeguard against, say, 1000 communities on a route.
In practical networks, we rarely see more than a dozen communities.
Make minesweeper approximate HasSize in a way that lines up with that use case,
which may need adaptation if we learn of others. This improves behavior
in a common case.

minesweeper: handwavy implementation of CommunitySet HasSize

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDDomain.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDDomainTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDRouteTest.java

Only protocols were validated for well-formedness; extend this to all the others such as
origin type, source VRFs, and more.
commit-id:87938a12
---
**Stack**:
- #9082
- #9081
- #9079 ⬅

BDDRoute: expand well formedness to include all finite domains

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java

We likely never use this because it ends up with quadratic results, but
it would crash deterministically if we did.
---
**Stack**:
- #9089
- #9088
- #9087 ⬅

CompareRoutePoliciesUtils: fix a crash when given more than one routing policy

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDDState.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/ModelGenerationTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

1. Add fields and named getters, get rid of Tuple
2. Inline a few non-obvious defaults especially if used in only one place.
3. Improve comments mildly.
---
**Stack**:
- #9096
- #9095
- #9094
- #9093
- #9092 ⬅

TransferReturn: improve readability

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDRouteTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferReturnTest.java

And implement hashCode to honor Java contracts.
---
**Stack**:
- #9096
- #9095
- #9094
- #9093 ⬅

minesweeper: implement equals

---

.github/workflows/pre-commit.yml

See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

github workflows: upgrade from set-output to GITHUB_OUTPUT

---

projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/AsPathRegex.java
projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/GroupWildcard.java

See: https://github.com/sirthias/parboiled/issues/203
For some reason, when upgrading beyond Java 8 something about String concatenation optimizations
breaks Parboiled. This is a workaround to let us keep moving forward despite using this unmaintained
library.
---
**Stack**:
- #9106
- #9105 ⬅
- #9104

parboiled: convert from + to String.format

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java

This improves performance by allowing simplification to FALSE if family is not supported.
---
**Stack**:
- #9134
- #9133
- #9132
- #9130 ⬅

JuniperConfiguration: move address family first in conjuncts

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java
projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDDomain.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDTunnelEncapsulationAttribute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDDomainTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDTunnelEncapsulationAttributeTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java

For each difference returned by CompareRoutePolicies, compute the set of attributes on the input route that are relevant. The key property is that for any attribute that is deemed irrelevant, any concrete value can be used for that attribute without affecting the behavior of the route policies on the input route.

CompareRoutePolicies: Compute relevant route attributes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java

Avoid traversing the given BDD multiple times when computing the relevant route attributes.

CompareRoutePolicies: Optimize computation of relevant attributes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java

Prefer to only hash fixed-work fields. Community APs can get *big*.
---
**Stack**:
- #9156
- #9159 ⬅

BDDRoute: remove communityAPs from hashCode

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunitySetMatchExprToBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java

1. Add a cache
2. Short-circuit single exact communities
3. Exit early when constraint is proven
4. Less garbage in allNegativeLiterals
---
**Stack**:
- #9161
- #9160
- #9156 ⬅

CommunitySetMatchExprToBDD: streamline community constraints

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java

IntegerSpace#contains for every integer in the set is expensive, instead just
enumerate the (sparse) sets.
---
**Stack**:
- #9161
- #9160 ⬅

TransferBDD: optimize SetCommunities

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/BUILD.bazel
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RegexCommunityMember.java
projects/batfish/src/test/java/org/batfish/representation/juniper/RegexCommunityMemberTest.java
tests/parsing-tests/example-juniper.ref
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

Junos community regexes are not implicitly truncated so can match longer
strings in many cases. This is risky, as unintended community matches can lead
to unexpected bad routing behaviors. Add a warning for these regexes.
Do not warn in common cases that do work even though the regex is not
truncated: as of modern Junos releases, the regex is not matched against
non-standard communities so 12345:3$, for example, is fine as no standard
community has 6 digits in the first half.
---
**Stack**:
- #9168
- #9167 ⬅

Junos: warn if a standard community regex is used that can match longer strings

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/SymbolicRegex.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/CommunityVarTest.java

The automaton library that we use treats ^ and $ as ordinary characters, but they should not be allowed to match against the . regex, or else for instance we'd allow "^5:5$" as a valid instance of the community regex "..:..".

SymbolicRegex: Dot should not match the start-of-string or end-of-string characters

---

projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperLexer.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/nested-config-with-quote-bug

Junos requires quoted strings to be on one line anyway, as far as I can tell online and in configs.

Junos: reduce blast radius of missing quote in hierarchical configs

---

docs/question_development/README.md

Move over content from https://github.com/batfish/batfish/wiki/Developer-notes. Something is better than nothing.

Question development documentation

---

WORKSPACE

Had to resolve a diamond dependency for rules_license: see https://github.com/bazelbuild/rules_jvm_external/issues/1244

bazel: manage up rules_license and upgrade rules_jvm_external

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/dataplane/rib/RibGroup.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/dataplane/rib/RibGroupTest.java

RibGroup: fix a deserialization error if there are no supported ribs in the group

---

projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java

This commit adds support for the route reflector configuration in the EVPN neighbor conversion process for Arista. Without this configuration, the spine cannot reflect EVPN routes in the iBGP VXLAN configuration.

bugfix: add route reflector configuration for Arista EVPN neighbors

---

projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/JuniperParser.g4
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper_nested_multiline_comments

Avoids flattening issues when there's a bare semicolon after a comment.

Junos: add empty lines

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bmp.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bmp-station
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper_fti

Handle lines with multiple final commands on the same line
---
**Stack**:
- #9240
- #9239 ⬅
- #9238

Junos: slightly more generous BMP station logic

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/QualifiedNextHop.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInformationBase.java
projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRouteV4.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java

Just a quick rename CR, next CR will add a StaticRoute base class and StaticRouteV6 class and renaming in the same CR seemed noisy.

Rename junos StaticRoute class to StaticRouteV4

---

.pre-commit-config.yaml
tools/fix_java_format.sh

1. Pass filenames in and use it.
2. Run serially, as google-java-format already parallelizes internally. This
means that pre-commit will run all files in batches, with size controlled by
pre-commit. It would actually be ideal if it was only one batch, but the hit
is not so bad.

fix_java_format.sh: redo to work better with pre-commit

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6Test.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Prefix6Test.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/grammar/frr/FrrGrammarTest.java
tests/parsing-tests/unit-tests.ref

**Stack**:
- #9248
- #9247
- #9246 ⬅

IPv6: fix toString

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/rib-name-misc

No extraction - just parsing more rib names in Junos:
rib bgp.l2vpn.0
rib bgp.l3vpn-inet6.0
rib bgp.l3vpn.0
rib :vxlan.inet.0
https://www.juniper.net/documentation/us/en/software/junos/static-routing/topics/topic-map/config_junos_routing_table.html#id-example-exporting-specific-routes-from-one-routing-table-into-another-routing-table

Support more rib names in Junos parser

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
tests/parsing-tests/example-juniper.ref
tests/parsing-tests/srx-testbed.ref
tests/parsing-tests/unit-tests.ref

Hard to read when they're just concatenated like this. This is different from Cisco/Arista where the
second thing is just a number.

Junos: improve presentation of defined structure names

---

projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/DataModelMatchers.java

It was hostname, but is actually a filename.
---
**Stack**:
- #9288
- #9287 ⬅

hasDefinedStructureWithDefinitionLines: fix argument name

---

projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java
projects/batfish/src/test/java/BUILD.bazel
projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java

The recognition is shaky and those strings may appear in files
from any configuration language.

VendorConfigurationFormatDetector: lower iptables priority

---

WORKSPACE
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VerboseEdgeTest.java

```
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VerboseEdgeTest.java:20: error: [SelfAssertion] You are passing identical arguments to the assertEquals method, so this assertion always passes. THIS IS LIKELY A BUG! If you are trying to test the correctness of an equals() implementation, use EqualsTester instead.
assertEquals(edge1, edge1);
^
(see https://errorprone.info/bugpattern/SelfAssertion)
```

rules_jvm_external: upgrade to 6.6 and fix new compiler error

---

projects/bdd/src/main/java/net/sf/javabdd/BDDFactory.java
projects/bdd/src/main/java/net/sf/javabdd/JFactory.java
projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java
tools/benchmarks/BUILD.bazel
tools/benchmarks/BenchmarkOnehot.java

This generic version is not specialized to variables. In a quick benchmark, it
is a little worse than 2x the in-library version for equivalent input.
```
Benchmark                        (_numDisjuncts)   Mode  Cnt       Score       Error  Units
BenchmarkOnehot.benchOnehot                   32  thrpt   25  152720.567 ±  7480.285  ops/s
BenchmarkOnehot.benchOnehot                  128  thrpt   25   38162.239 ±  2804.592  ops/s
BenchmarkOnehot.benchOnehot                  512  thrpt   25    9086.845 ±   405.937  ops/s
BenchmarkOnehot.benchOnehotVars               32  thrpt   25  346198.834 ± 24806.409  ops/s
BenchmarkOnehot.benchOnehotVars              128  thrpt   25   82864.962 ±  1937.790  ops/s
BenchmarkOnehot.benchOnehotVars              512  thrpt   25   20393.980 ±   218.186  ops/s …
```

BDD: rename onehot to onehotVars and add a generic version

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsTerm.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenCommunityAdd.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenCommunitySet.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsThens.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route4FilterLine.java
projects/batfish/src/main/java/org/batfish/representation/juniper/Route6FilterLine.java
projects/batfish/src/main/java/org/batfish/representation/juniper/RouteFilterLine.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/PsThensTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-ps-then-community
tests/parsing-tests/unit-tests-warnings.ref
tests/parsing-tests/unit-tests.ref

For many properties, repeated sets or adds clear each other. We did this
refactoring for PsFrom, but not yet for PsThen.  Starting it here, and adding
useful errors, with more to come.
This also opens up more efficient conversion in future: for example,
CommunitySet+Add can be combined into one community mutation set, rather than a
set and then a bunch of unions.

Junos: start implementing policy-statement term then correctly with overrides

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/AsPathMatchExprAsPathCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/AsPathMatchExprToRegexes.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/aspath/AsPathMatchExprAsPathCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/AsPathMatchExprToRegexesTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java

This is in the same spirit as batfish/batfish#9069 for symbolic modeling of
community set size. Since this construct is likely only used to reject routes
that may overflow some resource limit, model it as true as long as it is only
matching 'all reasonable' AS paths. As for communities, semi-arbitrarily used
64 as the limit -- 'all reasonable AS Paths' have fewer than 64 entries.

Add support for symbolic modeling of HasAsPathLength

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java
projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp-redistribute

Parsing and extraction were there, but conversion only for static routes.
This adds support for redistributing more protocols.

PaloAlto: support redistribution of more protocols into BGP

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-missing-prefix-condition

Juniper requires that `if-route-exist` have a prefix defined or else deployment would fail.

Warn when if-route-exist has no prefix

---

projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java
projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp-redistribute

Previously code assumed that destination prefixes are required and empty set meant no match. In practice, empty set means "any prefix"

PaloAlto: destination prefixes optional during redistribution

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4
projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-apply-groups-static-route-after
projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-apply-groups-static-route-before

Allowing static route prefixes to be wildcarded in an apply group.

Junos: support apply group wildcards on static route prefixes

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-condition
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-missing-prefix-condition

This PR modifies the Junos parser grammar so that `if-route-exists` can parse IPv4 and IPv6 addresses, following the documentation https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/if-route-exists-edit-policy-options-condition.html.
The test file uses IPv4 and IPv6 prefix reserved for documentation and testing ([RFC5737](https://tools.ietf.org/html/rfc5737) and [RFC3849](https://tools.ietf.org/html/rfc3849))

Junos: parse if-route-exists ip address

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java

`@JsonIgnore` was added due to the error `Caused by: java.lang.UnsupportedOperationException: Should never call set() on setterless property ('fatalRedFlagWarnings')` because Jackson marks fatalRedFlagWarnings as a property.

Make Jackson ignore fatal red flag warnings

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java

Move lowercase to the top and add a test that failed before.
---
**Stack**:
- #9363
- #9362 ⬅

ExtendedCommunity: fix case awareness

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/BDDRouteTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java
projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java

Adds support to the symbolic route-policy analysis (TransferBDD) for analyzing paths through a route policy that require an input route that is a static route (as opposed to a BGP route).

TransferBDD: Support for static routes

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-groups-routing-instances

This creates false recursion that doesn't happen on-box.

Junos: don't match apply-groups or apply-path when expanding groups wildcards

---

projects/batfish-common-protocol/src/main/java/org/batfish/role/InferRoles.java
projects/batfish-common-protocol/src/test/java/org/batfish/role/InferRolesTest.java
tests/roles/inferRoles.ref

This seems to be a bottleneck in some cases. Drop in re2j, which required
rewriting the patterns into generic regex patterns to work.
This rewrite exactly matches the documented meanings of these cute names:
https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html

InferRoles: use re2j for performance

---

projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/GroupWildcard.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/apply-groups-routing-instances

Empty wildcards doesn't apply any configuration but is syntactically valid in Juniper configurations.

Junos: Allow empty regex in wildcard

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java
projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java

Without using the canonical range `closedOpen(a, a+1)` we were not able to
combine `a` and `a+1`. This is because `[a,a] union [a+1,a+1]` is not `[a,a+1]`
in a number line. You need `[a,a+1) union [a+1, a+2)` which does become `[a, a+2)`.
We handled this inside `IntegerSpace`, but since there's no mutable version we
did it again.
---
**Stack**:
- #9373
- #9372 ⬅

DefinedStructureInfo: canonicalize ranges

---

projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/GroupWildcard.java

Was hard to debug when empty string was not supported (batfish/batfish#9371).

GroupWildcard: slightly better error message

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatement.java
projects/batfish/src/test/java/org/batfish/representation/juniper/TermFwThenToPacketPolicyStatementTest.java

The 'default vrf' should be the routing-instance that we're already in. Otherwise, we
switch back to the master RI if the PBR policy is just 'accept'.

Juniper: remove default vrf for PBR

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Ip6Test.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/Prefix6Test.java

Previously parsing them resulted in incorrect high-order bits, and also confusing toString (using all hex chars)

Ip6: parse/stringify ipv4-mapped addresses

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyPathApplicator.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-wildcards

Juniper allows statements like 
```
set policy-options prefix-list FOO apply-path "protocols bgp group BAR neighbor <*>;" 
```
and even things like
```
set policy-options prefix-list FOO apply-path "protocols bgp group <*>a neighbor <*>b" 
```
These cases would not expand but will also not cause commit error so Batfish should not crash on them.

Junos: Don't crash on invalid wildcard in apply-path

---

projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled/GroupWildcard.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-wildcards

Batfish is throwing exceptions when creating groups with `,` inside `<>` for lines such as `set groups g4 interfaces "<em[0,1]>" unit <*> family inet filter input FILTER`. This is valid syntax.

Junos: Support group wildcard with comma

---

projects/batfish/src/main/java/org/batfish/representation/juniper/CommunityMemberParseResult.java
projects/batfish/src/test/java/org/batfish/representation/juniper/CommunityMemberParseResultTest.java

Adding more special case handling for standard and large communities.
For standard and large community, all the values are allowed to be 0. For extended community, only local admin (string after last colon) is allowed to be 0.
```
origin:111: -> origin:111:0
large:111:222: -> large:111:222:0
large:111:: -> large:111:0:0
large::: -> large:0:0:0
```
I approached this by constructing a new community string to fill the 0 before passing it to the existing `tryParse` function in the respective Community classes.

Junos: Support incomplete extended and large community

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bgp.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/BgpGroup.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bgp-keep

Add parsing and extraction for Junos' BGP group keep all/none configuration.
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/basic-routing-policies.html

Junos: BGP group keep all/none extraction

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InterfaceType.java
projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Link.java
projects/batfish-common-protocol/src/main/java/org/batfish/specifier/parboiled/TypeInterfaceAstNode.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/pojo/TopologyTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/TypesInterfaceSpecifierTest.java
projects/batfish-common-protocol/src/test/java/org/batfish/specifier/parboiled/ParboiledInterfaceSpecifierTest.java
tests/aws/vimodel-example-aws.ref

We never used VPN intentionally and we can't think of a reason to keep it. In the meantime, VPN processing
has bitrotted compared to TUNNEL processing.

InterfaceType: remove VPN in favor of TUNNEL

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java

Also keeps it consistent with export policy name computation

JuniperConfiguration: small helper for naming bgp import policies

---

projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/ExtendedCommunity.java
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/bgp/community/ExtendedCommunityTest.java
projects/batfish/src/test/java/org/batfish/representation/juniper/CommunityMemberParseResultTest.java

Add support for bandwidth, bandwidth-transitive, and bandwidth-non-transitive.
Source 
https://www.juniper.net/documentation/us/en/software/junos/ai-ml-evo/topics/topic-map/bgp-link-bandwidth.html for types of bandwidth community and default transitive behavior
https://community.juniper.net/blogs/moshiko-nayman/2024/05/13/bgp-link-bandwidth-with-junos for confirming that bandwidth value is in bytes
https://datatracker.ietf.org/doc/html/draft-ietf-idr-link-bandwidth-11#name-link-bandwidth-extended-com for parsing guideline regarding type, subtype, and value.

Add support for bandwidth extended community

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/BooleanExprVarCollector.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/aspath/RoutingPolicyCollectorTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/communities/BooleanExprVarCollectorTest.java

Not all callexprs are guaranteed to be well-formed

BooleanExprVarCollector: handle missing policies in CallExpr

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/recovery-timeout

Implements the Juniper recovery-timeout command as a null rule under the family
ethernet-switching context. This command is used to specify the recovery
timeout for interfaces with ethernet-switching enabled.

Add support for Juniper recovery-timeout command

---

docs/parsing/README.md
docs/parsing/vendors/ios_xr.md

Add comprehensive documentation for IOS-XR parsing, focusing on:
- Common parsing patterns specific to IOS-XR
- Handling of single-line vs multi-line syntax variations
- Implementation guidance for grammar structure

docs: Add IOS-XR vendor-specific parsing documentation

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-area-interface-ip-missing

When the interface that has an IP isn't found, we should just stop rather than
continue trying to look for bugs.
---
**Stack**:
- #9425
- #9424
- #9423 ⬅

Junos: fix incorrect fatal warning on missing interface

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/transferbddvalidation/TransferBDDValidationAnswerer.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/transferbddvalidation/TransferBDDValidationQuestion.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/transferbddvalidation/TransferBDDValidationAnswererTest.java
questions/experimental/transferBDDValidation.json

Updates TransferBDD validation to only validate route policies that appear on peer groups. Otherwise we can get false positives by considering route policies that are only ever used as subroutines and not intended to be valid policies on their own.  This PR also includes one small bug fix (missing bounds check) and some minor performance improvements.

TransferBDDValidation: Only validate peer groups

---

projects/batfish-common-protocol/src/main/java/org/batfish/common/Warnings.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/risky-terminal-actions

This provides a special risky warning if a term in the middle of a policy statement matches everything AND has a terminal action (reject or accept). This makes all subsequent terms in the policy statement unreachable.

Add risky warning for juniper policy statements with terminal terms that result in unreachable subsequent terms

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/juniper/PsTerm.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/risky-terminal-actions

- Add todo's for further extraction
- Otherwise just add a flag to track if there are any "to"'s, to enable proper logging of risky terminal actions.

Basic tracking of "to" conditions in Junos policy-statement terms

---

projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/risky-terminal-actions

Make a special case for terminal term warnings - don't worry if there is exactly one terminal term that is unreachable, as long as it's "simple" - ie, has only one "then". 
Default `reject` or `next policy` is common at the end of a policy statement - but if that `reject` is coupled with something mutating, it is more likely to be an accidentally unreachable term.

Don't warn for an unreachable terminal term if there is exactly one simple terminal term

---

.roomodes

1. Allow src/main or src/test anywhere
2. Fix quoting that was either broken all along or not fixed when converting from JSON to YAML.

.roomodes: fix file restrictions

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/rtf-prefix-lists

Looking at the docs https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/rtf-prefix-list-edit-policy-options.html the syntax here is AS number:route target extended community/length. Also removed apply-path, which is not an option for rtf-prefix-list.

Fixup allowed rtf-prefix-list definitions

---

projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4
projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java
projects/batfish/src/main/java/org/batfish/grammar/hierarchical/StatementTree.java
projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java
projects/batfish/src/test/java/org/batfish/main/FlattenTest.java
projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java
projects/batfish/src/test/resources/org/batfish/main/testconfigs/junos-order-sensitive-replace-before
projects/batfish/src/test/resources/org/batfish/main/testconfigs/junos-order-sensitive-replace-flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/junos-order-sensitive-replace-preprocessed
projects/batfish/src/test/resources/org/batfish/main/testconfigs/multiple_tags_flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/replace_filter_flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/replace_flat_mix_flattened
projects/batfish/src/test/resources/org/batfish/main/testconfigs/replace_only_flattened

We were treating it like delete, but this meant that the order
of terms in a sequence would be lost.
```
set policy-options policy-statement PS term T1
set policy-options policy-statement PS term T2
replace: T1 {
...
}
```
Should keep T1 before T2, but delete would move the new T1 below T2.
Instead, add replace handling to InsertDeleteApplicator that
preserves the order.

Junos: make replace preserve order

---

.github/workflows/pre-commit.yml

Change scheduled runs from every hour to daily at 5am Seattle time (12 UTC).
Pull request and push triggers remain unchanged.

Reduce pre-commit workflow schedule from hourly to daily

---

.github/workflows/lab-validation-pr.yml

Adds a workflow that triggers lab validation when the `lab-validation` label is applied to PRs.
Add the `lab-validation` label to a PR. Lab validation will run and rerun automatically on new commits until the label is removed.
- **Trigger**: PR label events and commit pushes
- **Behavior**: Runs when `lab-validation` label is added or when commits are pushed to PRs with the label
- **Testing**: Builds Batfish JAR from PR branch and runs all available lab scenarios
- **Results**: Posts status comments to PR with workflow links
1. Apply `lab-validation` label to PR
2. Workflow builds Batfish JAR from PR branch
3. Runs lab validation using reusable workflow from lab-validation repository
4. Posts results as PR comment
5. Reruns steps 2-4 on new commits while label is present
6. Remove label …

Add label-triggered lab validation for PRs

---

.github/workflows/lab-validation-pr.yml
projects/batfish/src/main/java/org/batfish/representation/arista/AristaConfiguration.java

The lab validation workflow was failing with a 404 error when trying to check PR labels on synchronize events.
**Issue:** The workflow was using  which doesn't exist in GitHub's API.
**Fix:** Changed to  which is the correct endpoint, as PRs are treated as issues for label operations in GitHub's REST API.
**Testing:** Verified the API call works locally:
```bash
gh api repos/batfish/batfish/issues/9494/labels --jq '.[].name'
```
This should resolve the 404 errors when the workflow runs on PR synchronize events.

Fix GitHub API endpoint for PR labels

---

projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java
projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/description-validation

Junos rejects descriptions outside the range (1..255). This change makes Batfish generate fatal errors for invalid descriptions to match Junos behavior.
- Centralized description validation in `toString(DescriptionContext)` method
- Generate fatal errors for empty and overly long descriptions
- Applies to both BGP neighbor and interface descriptions
Fixes configurations being accepted by Batfish that would be rejected by actual Junos devices.

Junos: Add fatal error validation for description length

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDDState.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferParam.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDStateTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferParamTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferResultTest.java

Updates the symbolic route analysis to track and use intermediate BGP attributes, based on the corresponding route-policy statements that enable/disable them, as is done in the concrete route simulation engine.

TransferBDD: Support intermediate BGP attributes

---

projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java
projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/ModelGenerationTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java
projects/minesweeper/src/test/java/org/batfish/minesweeper/question/transferbddvalidation/TransferBDDValidationAnswererTest.java

We made the retention of all paths optional because it is often a huge
performance hit to include it. However, we're finding users are often using the
'default' behavior that keeps all paths when they don't need it, only because
retaining all paths was the default. Rather than flip the default, which seems
potentially confusing, just remove the zero-argument and make users choose.
This commit includes no changes: any uses of the old method have true inlined
to keep behavior the same.

TransferBDD: remove zero-arg version

---

projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java
projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java
projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java
projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java
projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-interface

Continue killing BatfishException, which should never be used. In general, parser should never
crash but should warn, risky, fatal, or otherwise proceed. BatfishException in parsers is the
worst combination.
Most of the changes in the grammar are unreachable as catch-alls where we think we might add
an alternative without a test (what?!) So get rid of those.
For interface names, we should proceed happily instead of crashing when a new prefix
is added.

IOS: remove many BatfishExceptions, fix crashing on unhandled interface type

---

projects/batfish/src/main/antlr4/org/batfish/grammar/arista/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_asa/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_concatenated/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_nclu/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_ports/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_imish/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/f5_bigip_structured/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/flatvyos/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/frr/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/iptables/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/juniper/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/mrv/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto_nested/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/eos/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/ios/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/routing_table/nxos/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/grammar/vyos/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/BUILD.bazel
projects/batfish/src/main/antlr4/org/batfish/vendor/check_point_gateway/grammar/BUILD.bazel
skylark/antlr.bzl

Created antlr_grammar rule in skylark/antlr.bzl that encapsulates
the pattern for generating ANTLR parsers. This eliminates repetition
across 26 BUILD files.
The rule:
- Automatically identifies Lexer.g4 and Parser.g4 files to process
- Infers output files based on grammar file names
- Simplifies BUILD files from ~40 lines to ~20 lines per grammar
Replaces genrule-based approach with more maintainable rule-based
approach following patterns from pmd_test and ref_tests.
---
**Stack**:
- #9541
- #9540 ⬅

Refactor ANTLR grammar generation into Starlark rule
